// Léxico dos cursos: palavra → [classe, IPA (inglês americano, forma de
// citação), glosa pt-BR no sentido usado nas frases].
export const LEXICON = {
  a: ['determiner', '/ə/', 'um, uma'],
  about: ['preposition', '/əˈbaʊt/', 'sobre'],
  ac: ['noun', '/ˌeɪˈsiː/', 'ar-condicionado'],
  access: ['noun', '/ˈæksɛs/', 'acesso'],
  add: ['verb', '/æd/', 'acrescentar'],
  address: ['noun', '/ˈædrɛs/', 'endereço'],
  after: ['preposition', '/ˈæftər/', 'depois de'],
  air: ['noun', '/ɛr/', 'ar'],
  almost: ['adverb', '/ˈɔːlmoʊst/', 'quase'],
  an: ['determiner', '/ən/', 'um, uma'],
  any: ['determiner', '/ˈɛni/', 'algum, alguma'],
  anytime: ['adverb', '/ˈɛnitaɪm/', 'quando quiser'],
  appreciate: ['verb', '/əˈpriːʃieɪt/', 'agradecer, valorizar'],
  are: ['auxiliary verb', '/ɑːr/', 'são, estão'],
  at: ['preposition', '/æt/', 'em, às'],
  attached: ['adjective', '/əˈtætʃt/', 'anexado'],
  back: ['adverb', '/bæk/', 'de volta'],
  bag: ['noun', '/bæɡ/', 'mala, bolsa'],
  bags: ['noun', '/bæɡz/', 'malas'],
  be: ['verb', '/biː/', 'ser, estar'],
  bite: ['noun', '/baɪt/', 'mordida; algo para comer'],
  blocked: ['adjective', '/blɑːkt/', 'travado, impedido'],
  boarding: ['noun', '/ˈbɔːrdɪŋ/', 'embarque'],
  borrow: ['verb', '/ˈbɑːroʊ/', 'pegar emprestado'],
  bother: ['verb', '/ˈbɑːðər/', 'incomodar'],
  breakfast: ['noun', '/ˈbrɛkfəst/', 'café da manhã'],
  bus: ['noun', '/bʌs/', 'ônibus'],
  but: ['conjunction', '/bʌt/', 'mas'],
  by: ['preposition', '/baɪ/', 'até (prazo)'],
  call: ['noun', '/kɔːl/', 'chamada, call'],
  can: ['auxiliary verb', '/kæn/', 'poder'],
  "can't": ['auxiliary verb', '/kænt/', 'não poder'],
  'carry-on': ['noun', '/ˈkæri ɑːn/', 'bagagem de mão'],
  change: ['verb', '/tʃeɪndʒ/', 'trocar'],
  charger: ['noun', '/ˈtʃɑːrdʒər/', 'carregador'],
  chat: ['verb', '/tʃæt/', 'conversar'],
  check: ['verb', '/tʃɛk/', 'fazer (check-in)'],
  checking: ['verb', '/ˈtʃɛkɪŋ/', 'despachando'],
  checkout: ['noun', '/ˈtʃɛkaʊt/', 'saída do hotel'],
  circle: ['verb', '/ˈsɜːrkəl/', 'voltar (circle back)'],
  conditioning: ['noun', '/kənˈdɪʃənɪŋ/', 'condicionamento (ar-condicionado)'],
  connection: ['noun', '/kəˈnɛkʃən/', 'conexão'],
  cool: ['adjective', '/kuːl/', 'legal, massa'],
  could: ['auxiliary verb', '/kʊd/', 'poderia'],
  deadline: ['noun', '/ˈdɛdlaɪn/', 'prazo'],
  delayed: ['adjective', '/dɪˈleɪd/', 'atrasado'],
  "didn't": ['auxiliary verb', '/ˈdɪdənt/', 'não (passado)'],
  disagree: ['verb', '/ˌdɪsəˈɡriː/', 'discordar'],
  distance: ['noun', '/ˈdɪstəns/', 'distância'],
  do: ['auxiliary verb', '/duː/', 'fazer; auxiliar de pergunta'],
  does: ['auxiliary verb', '/dʌz/', 'auxiliar de pergunta (3ª pessoa)'],
  "don't": ['auxiliary verb', '/doʊnt/', 'não'],
  done: ['adjective', '/dʌn/', 'pronto, feito'],
  down: ['adjective', '/daʊn/', 'dentro, topando (gíria)'],
  downtown: ['adverb', '/ˌdaʊnˈtaʊn/', 'para o centro'],
  drop: ['verb', '/drɑːp/', 'deixar (drop off)'],
  email: ['noun', '/ˈiːmeɪl/', 'e-mail'],
  enough: ['adverb', '/ɪˈnʌf/', 'o bastante'],
  everyone: ['pronoun', '/ˈɛvriwʌn/', 'todo mundo, pessoal'],
  everything: ['pronoun', '/ˈɛvriθɪŋ/', 'tudo'],
  extra: ['adjective', '/ˈɛkstrə/', 'a mais, extra'],
  fair: ['adjective', '/fɛr/', 'justo'],
  fare: ['noun', '/fɛr/', 'tarifa'],
  favor: ['noun', '/ˈfeɪvər/', 'favor'],
  few: ['determiner', '/fjuː/', 'poucos'],
  file: ['noun', '/faɪl/', 'arquivo'],
  find: ['verb', '/faɪnd/', 'encontrar'],
  flight: ['noun', '/flaɪt/', 'voo'],
  following: ['verb', '/ˈfɑːloʊɪŋ/', 'retomando (follow up)'],
  for: ['preposition', '/fɔːr/', 'para, por'],
  forward: ['adverb', '/ˈfɔːrwərd/', 'adiante (look forward)'],
  free: ['adjective', '/friː/', 'livre, disponível'],
  friday: ['proper noun', '/ˈfraɪdeɪ/', 'sexta-feira'],
  gate: ['noun', '/ɡeɪt/', 'portão'],
  get: ['verb', '/ɡɛt/', 'conseguir, chegar'],
  give: ['verb', '/ɡɪv/', 'dar'],
  goes: ['verb', '/ɡoʊz/', 'vai'],
  going: ['verb', '/ˈɡoʊɪŋ/', 'indo'],
  good: ['adjective', '/ɡʊd/', 'bom'],
  grab: ['verb', '/ɡræb/', 'pegar, comer algo rápido'],
  great: ['adjective', '/ɡreɪt/', 'ótimo'],
  hand: ['noun', '/hænd/', 'mão, ajuda'],
  have: ['verb', '/hæv/', 'ter'],
  'heads-up': ['noun', '/ˈhɛdz ʌp/', 'aviso prévio'],
  hear: ['verb', '/hɪr/', 'ouvir'],
  here: ['adverb', '/hɪr/', 'aqui'],
  hop: ['verb', '/hɑːp/', 'entrar rapidinho (hop on)'],
  hour: ['noun', '/ˈaʊər/', 'hora'],
  how: ['adverb', '/haʊ/', 'como'],
  i: ['pronoun', '/aɪ/', 'eu'],
  "i'd": ['pronoun', '/aɪd/', 'eu (gostaria)'],
  "i'll": ['pronoun', '/aɪl/', 'eu vou'],
  "i'm": ['pronoun', '/aɪm/', 'eu estou, eu sou'],
  if: ['conjunction', '/ɪf/', 'se'],
  in: ['preposition', '/ɪn/', 'em, dentro de'],
  included: ['adjective', '/ɪnˈkluːdɪd/', 'incluído'],
  instead: ['adverb', '/ɪnˈstɛd/', 'em vez disso'],
  is: ['auxiliary verb', '/ɪz/', 'é, está'],
  "isn't": ['auxiliary verb', '/ˈɪzənt/', 'não é, não está'],
  it: ['pronoun', '/ɪt/', 'isso, ele, ela'],
  "it's": ['pronoun', '/ɪts/', 'é, está'],
  job: ['noun', '/dʒɑːb/', 'trabalho'],
  just: ['adverb', '/dʒʌst/', 'só, apenas'],
  keep: ['verb', '/kiːp/', 'manter'],
  know: ['verb', '/noʊ/', 'saber'],
  last: ['adjective', '/læst/', 'último'],
  late: ['adjective', '/leɪt/', 'atrasado'],
  later: ['adverb', '/ˈleɪtər/', 'mais tarde'],
  leave: ['verb', '/liːv/', 'deixar'],
  let: ['verb', '/lɛt/', 'deixar, permitir'],
  "let's": ['verb', '/lɛts/', 'vamos'],
  lifesaver: ['noun', '/ˈlaɪfseɪvər/', 'salva-vidas'],
  like: ['verb', '/laɪk/', 'gostar'],
  line: ['noun', '/laɪn/', 'linha'],
  logging: ['verb', '/ˈlɔːɡɪŋ/', 'saindo (log off)'],
  look: ['noun', '/lʊk/', 'olhada'],
  looking: ['verb', '/ˈlʊkɪŋ/', 'aguardando (look forward)'],
  lot: ['noun', '/lɑːt/', 'muito (a lot)'],
  luggage: ['noun', '/ˈlʌɡɪdʒ/', 'bagagem'],
  make: ['verb', '/meɪk/', 'fazer; conseguir ir (make it)'],
  makes: ['verb', '/meɪks/', 'faz'],
  many: ['determiner', '/ˈmɛni/', 'muitos (how many)'],
  me: ['pronoun', '/miː/', 'me, mim'],
  meet: ['verb', '/miːt/', 'encontrar'],
  mind: ['verb', '/maɪnd/', 'se importar'],
  minute: ['noun', '/ˈmɪnɪt/', 'minuto'],
  minutes: ['noun', '/ˈmɪnɪts/', 'minutos'],
  missed: ['verb', '/mɪst/', 'perdi'],
  monday: ['proper noun', '/ˈmʌndeɪ/', 'segunda-feira'],
  much: ['adverb', '/mʌtʃ/', 'quanto (how much)'],
  museum: ['noun', '/mjuˈziːəm/', 'museu'],
  mute: ['noun', '/mjuːt/', 'mudo'],
  my: ['determiner', '/maɪ/', 'meu, minha'],
  near: ['preposition', '/nɪr/', 'perto de'],
  next: ['adjective', '/nɛkst/', 'próximo'],
  no: ['determiner', '/noʊ/', 'nenhum; não'],
  noisy: ['adjective', '/ˈnɔɪzi/', 'barulhento'],
  not: ['particle', '/nɑːt/', 'não'],
  now: ['adverb', '/naʊ/', 'agora'],
  off: ['particle', '/ɔːf/', '(partícula: off)'],
  offline: ['adverb', '/ˌɔːfˈlaɪn/', 'fora da reunião'],
  on: ['preposition', '/ɑːn/', 'em, sobre'],
  one: ['pronoun', '/wʌn/', 'uma (I owe you one)'],
  'one-way': ['adjective', '/ˌwʌn ˈweɪ/', 'só de ida'],
  owe: ['verb', '/oʊ/', 'dever'],
  password: ['noun', '/ˈpæswɜːrd/', 'senha'],
  pick: ['verb', '/pɪk/', 'pegar (pick up)'],
  please: ['adverb', '/pliːz/', 'por favor'],
  point: ['noun', '/pɔɪnt/', 'ponto, argumento'],
  posted: ['adjective', '/ˈpoʊstɪd/', 'informado (keep posted)'],
  presentation: ['noun', '/ˌprɛzənˈteɪʃən/', 'apresentação'],
  problem: ['noun', '/ˈprɑːbləm/', 'problema'],
  push: ['verb', '/pʊʃ/', 'adiar, empurrar'],
  questions: ['noun', '/ˈkwɛstʃənz/', 'perguntas, dúvidas'],
  quick: ['adjective', '/kwɪk/', 'rápido'],
  really: ['adverb', '/ˈriːəli/', 'muito, de verdade'],
  reply: ['noun', '/rɪˈplaɪ/', 'resposta'],
  reservation: ['noun', '/ˌrɛzərˈveɪʃən/', 'reserva'],
  ride: ['noun', '/raɪd/', 'carona, corrida'],
  right: ['adverb', '/raɪt/', 'bem; né? (right?)'],
  room: ['noun', '/ruːm/', 'quarto'],
  rooms: ['noun', '/ruːmz/', 'quartos'],
  running: ['verb', '/ˈrʌnɪŋ/', 'ficando (running late)'],
  screen: ['noun', '/skriːn/', 'tela'],
  seat: ['noun', '/siːt/', 'assento'],
  see: ['verb', '/siː/', 'ver, entender'],
  sense: ['noun', '/sɛns/', 'sentido'],
  serious: ['adjective', '/ˈsɪriəs/', 'sério'],
  seriously: ['adverb', '/ˈsɪriəsli/', 'sério?'],
  seven: ['numeral', '/ˈsɛvən/', 'sete'],
  share: ['verb', '/ʃɛr/', 'compartilhar'],
  show: ['verb', '/ʃoʊ/', 'aparecer (show up)'],
  silva: ['proper noun', '/ˈsɪlvə/', 'Silva (sobrenome)'],
  sit: ['verb', '/sɪt/', 'sentar'],
  so: ['adverb', '/soʊ/', 'tão'],
  some: ['determiner', '/sʌm/', 'algumas'],
  something: ['pronoun', '/ˈsʌmθɪŋ/', 'alguma coisa'],
  soon: ['adverb', '/suːn/', 'logo'],
  sorry: ['adjective', '/ˈsɑːri/', 'desculpa'],
  started: ['verb', '/ˈstɑːrtɪd/', 'começado'],
  starts: ['verb', '/stɑːrts/', 'começa'],
  station: ['noun', '/ˈsteɪʃən/', 'estação'],
  steps: ['noun', '/stɛps/', 'passos'],
  stop: ['verb', '/stɑːp/', 'parar'],
  sucks: ['verb', '/sʌks/', 'é uma droga (gíria)'],
  sure: ['adjective', '/ʃʊr/', 'claro; certo'],
  swamped: ['adjective', '/swɑːmpt/', 'atolado'],
  take: ['verb', '/teɪk/', 'pegar, levar'],
  talk: ['verb', '/tɔːk/', 'falar'],
  tell: ['verb', '/tɛl/', 'contar, dizer'],
  ten: ['numeral', '/tɛn/', 'dez'],
  text: ['verb', '/tɛkst/', 'mandar mensagem'],
  thanks: ['interjection', '/θæŋks/', 'obrigado, valeu'],
  that: ['pronoun', '/ðæt/', 'isso, aquilo'],
  "that's": ['pronoun', '/ðæts/', 'isso é'],
  the: ['determiner', '/ðə/', 'o, a'],
  there: ['adverb', '/ðɛr/', 'lá'],
  think: ['verb', '/θɪŋk/', 'achar, pensar'],
  this: ['determiner', '/ðɪs/', 'este, esta, isso'],
  ticket: ['noun', '/ˈtɪkɪt/', 'passagem, bilhete'],
  time: ['noun', '/taɪm/', 'vez; hora'],
  to: ['preposition', '/tuː/', 'para, a'],
  today: ['adverb', '/təˈdeɪ/', 'hoje'],
  tomorrow: ['adverb', '/təˈmɑːroʊ/', 'amanhã'],
  tonight: ['adverb', '/təˈnaɪt/', 'hoje à noite'],
  too: ['adverb', '/tuː/', 'demais'],
  towels: ['noun', '/ˈtaʊəlz/', 'toalhas'],
  turn: ['verb', '/tɜːrn/', 'ligar (turn on)'],
  tweaks: ['noun', '/twiːks/', 'ajustes'],
  twenty: ['numeral', '/ˈtwɛnti/', 'vinte'],
  under: ['preposition', '/ˈʌndər/', 'no nome de, sob'],
  until: ['conjunction', '/ənˈtɪl/', 'até'],
  up: ['particle', '/ʌp/', '(partícula: up)'],
  walking: ['noun', '/ˈwɔːkɪŋ/', 'caminhada'],
  wanna: ['verb', '/ˈwɑːnə/', 'quer (want to)'],
  want: ['verb', '/wɑːnt/', 'querer'],
  was: ['verb', '/wɑːz/', 'foi, estava'],
  way: ['noun', '/weɪ/', 'caminho; jeito'],
  we: ['pronoun', '/wiː/', 'nós, a gente'],
  "we're": ['pronoun', '/wɪr/', 'nós estamos'],
  week: ['noun', '/wiːk/', 'semana'],
  weekend: ['noun', '/ˈwiːkɛnd/', 'fim de semana'],
  what: ['pronoun', '/wʌt/', 'o que, qual'],
  "what's": ['pronoun', '/wʌts/', 'qual é'],
  whatever: ['pronoun', '/wʌtˈɛvər/', 'o que (quer que seja)'],
  where: ['adverb', '/wɛr/', 'onde'],
  which: ['determiner', '/wɪtʃ/', 'qual'],
  'wi-fi': ['noun', '/ˈwaɪ faɪ/', 'Wi-Fi'],
  window: ['noun', '/ˈwɪndoʊ/', 'janela'],
  with: ['preposition', '/wɪð/', 'com'],
  within: ['preposition', '/wɪˈðɪn/', 'dentro de'],
  work: ['noun', '/wɜːrk/', 'trabalho'],
  working: ['verb', '/ˈwɜːrkɪŋ/', 'funcionando; trabalhando'],
  works: ['verb', '/wɜːrks/', 'funciona, serve'],
  worry: ['verb', '/ˈwɜːri/', 'se preocupar'],
  wrong: ['adjective', '/rɔːŋ/', 'errado'],
  you: ['pronoun', '/juː/', 'você'],
  "you're": ['pronoun', '/jʊr/', 'você está, você é'],
  your: ['determiner', '/jʊr/', 'seu, sua'],
};
