// Lote compras-1: curso novo "Compras sem Mistério" (A2, trilha Dia a dia),
// capítulos 1–6. Conteúdo original.

export const LEXICON = {
  buy: ['verb', '/baɪ/', 'comprar'],
  enter: ['verb', '/ˈɛntər/', 'digitar, entrar'],
  insert: ['verb', '/ɪnˈsɜːrt/', 'inserir'],
  pin: ['noun', '/pɪn/', 'senha do cartão'],
  paper: ['noun', '/ˈpeɪpər/', 'papel'],
  aisle: ['noun', '/aɪl/', 'corredor'],
  bigger: ['adjective', '/ˈbɪɡər/', 'maior'],
  cancel: ['verb', '/ˈkænsəl/', 'cancelar'],
  charged: ['verb', '/tʃɑːrdʒd/', 'cobrado'],
  complaint: ['noun', '/kəmˈpleɪnt/', 'reclamação'],
  damaged: ['adjective', '/ˈdæmɪdʒd/', 'danificado'],
  days: ['noun', '/deɪz/', 'dias'],
  declined: ['verb', '/dɪˈklaɪnd/', 'recusado'],
  delivered: ['verb', '/dɪˈlɪvərd/', 'entregue'],
  exchange: ['verb', '/ɪksˈtʃeɪndʒ/', 'trocar'],
  fits: ['verb', '/fɪts/', 'serve'],
  forgot: ['verb', '/fərˈɡɑːt/', 'esqueceu'],
  "forty-two": ['numeral', '/ˌfɔːrtiˈtuː/', 'quarenta e dois'],
  installments: ['noun', '/ɪnˈstɔːlmənts/', 'parcelas'],
  item: ['noun', '/ˈaɪtəm/', 'item'],
  list: ['noun', '/lɪst/', 'lista'],
  looks: ['verb', '/lʊks/', 'parece, fica'],
  only: ['adverb', '/ˈoʊnli/', 'só, apenas'],
  opened: ['verb', '/ˈoʊpənd/', 'abriu'],
  package: ['noun', '/ˈpækɪdʒ/', 'pacote'],
  perfectly: ['adverb', '/ˈpɜːrfɪktli/', 'perfeitamente'],
  plastic: ['noun', '/ˈplæstɪk/', 'plástico'],
  policy: ['noun', '/ˈpɑːləsi/', 'política, regra'],
  pound: ['noun', '/paʊnd/', 'libra (peso)'],
  product: ['noun', '/ˈprɑːdʌkt/', 'produto'],
  refund: ['noun', '/ˈriːfʌnd/', 'reembolso'],
  review: ['noun', '/rɪˈvjuː/', 'avaliação'],
  sale: ['noun', '/seɪl/', 'promoção, venda'],
  shipping: ['noun', '/ˈʃɪpɪŋ/', 'frete'],
  shopping: ['noun', '/ˈʃɑːpɪŋ/', 'compras'],
  size: ['noun', '/saɪz/', 'tamanho'],
  smaller: ['adjective', '/ˈsmɔːlər/', 'menor'],
  stock: ['noun', '/stɑːk/', 'estoque'],
  total: ['noun', '/ˈtoʊtəl/', 'total'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-shopping-a2',
    slug: 'shopping-a2',
    title: 'Compras sem Mistério',
    level: 'A2',
    category: 'survival',
    track: 'dia-a-dia',
    trackOrder: 3,
    order: 5,
    short: 'Mercado, roupas, pagamento, trocas, compras online e reclamações: tudo que você diz e ouve ao comprar.',
    long: 'Situações de compra do começo ao fim: achar o produto no mercado, experimentar roupa, pagar, trocar ou devolver, acompanhar uma entrega e reclamar com educação. Cada frase explica a estrutura ou a expressão usada.',
    lessons: [
      {
        id: 'lesson-shopping-a2-01',
        chapter: 1,
        title: 'No supermercado',
        description: 'Achar produtos, quantidades e o caixa.',
        units: [
          s('Excuse me, where can I find the rice?', 'Com licença, onde encontro o arroz?', '"Where can I find" é a pergunta padrão em qualquer loja.'),
          s("It's in aisle five.", 'Fica no corredor cinco.', '"Aisle" = corredor; o "s" é mudo: /aɪl/.'),
          s('I need a pound of ground beef.', 'Preciso de meio quilo de carne moída.', '"Pound" (lb) ≈ 450 g, unidade dos EUA. "Ground beef" = carne moída.'),
          s('Do you have this in a bigger size?', 'Vocês têm este num tamanho maior?', 'Comparativo: "big" → "bigger" (dobra o "g").'),
          s('Is this on sale?', 'Isto está em promoção?', '"On sale" = em promoção; "for sale" = à venda.'),
          s('Buy one, get one free.', 'Leve dois, pague um.', 'Promoção comum nos EUA (BOGO). Literal: "compre um, ganhe um grátis".'),
          s('Paper or plastic?', 'Sacola de papel ou de plástico?', 'Pergunta do caixa. Muitos lugares cobram pela sacola.'),
          s('Do you have a store card?', 'Você tem o cartão da loja?', 'Cartão de fidelidade que dá desconto.'),
          s('Where is the checkout?', 'Onde fica o caixa?', '"Checkout" = caixa; "self-checkout" = autoatendimento.'),
          s('I forgot my shopping list.', 'Esqueci minha lista de compras.', '"Shopping list" = lista de compras. Passado irregular: "forgot".'),
        ],
      },
      {
        id: 'lesson-shopping-a2-02',
        chapter: 2,
        title: 'Roupas e provador',
        description: 'Tamanho, cor, experimentar e decidir.',
        units: [
          s("I'm looking for a winter jacket.", 'Estou procurando uma jaqueta de inverno.', '"Look for" = procurar. Presente contínuo para o que você está fazendo.'),
          s('What size are you?', 'Qual é o seu tamanho?', 'Pergunta do vendedor. Resposta: "I\'m a medium".'),
          s('Does it come in blue?', 'Tem em azul?', '"Come in" + cor/tamanho = vir, estar disponível.'),
          s('Can I try this on?', 'Posso experimentar?', '"Try on" = experimentar roupa.'),
          s('It fits perfectly.', 'Serviu perfeitamente.', '"Fit" = servir (tamanho). Com he/she/it: "fits".'),
          s("It's a little tight.", 'Está um pouco apertado.', '"Tight" = apertado; "loose" = folgado.'),
          s('These shoes are too big.', 'Estes sapatos estão grandes demais.', '"Shoes" é plural: "these shoes are".'),
          s('It looks good on you.', 'Ficou bem em você.', '"Look good on" = ficar bem em alguém.'),
          s("I'll think about it.", 'Vou pensar.', 'Forma educada de não comprar agora.'),
          s("I'll take the black one.", 'Vou levar a preta.', '"One" substitui o substantivo: "the black one".'),
        ],
      },
      {
        id: 'lesson-shopping-a2-03',
        chapter: 3,
        title: 'Pagamento',
        description: 'Cartão, dinheiro, parcelas e recibo.',
        units: [
          s('How would you like to pay?', 'Como você prefere pagar?', 'Pergunta do caixa. "Would like" = gostaria.'),
          s('Can I pay with my phone?', 'Posso pagar com o celular?', '"Pay with" + meio de pagamento; "pay by card", "pay in cash".'),
          s('Insert your card, please.', 'Insira o cartão, por favor.', 'Na maquininha: "insert" (inserir), "tap" (aproximar), "swipe" (passar).'),
          s('Tap your card here.', 'Aproxime o cartão aqui.', '"Tap" = encostar, aproximar (pagamento sem contato).'),
          s('Enter your PIN.', 'Digite sua senha.', '"PIN" = senha numérica do cartão. "Enter" = digitar.'),
          s('Your card was declined.', 'Seu cartão foi recusado.', 'Voz passiva: "was declined". Tente outro cartão.'),
          s('Do you need a receipt?', 'Precisa do recibo?', '"Receipt" com "p" mudo: /rɪˈsiːt/.'),
          s('Can I pay in installments?', 'Posso parcelar?', '"Installments" = parcelas. Pouco comum nos EUA no varejo.'),
          s('Here is your change.', 'Aqui está o seu troco.', '"Change" = troco (e também mudança).'),
          s('The total is forty-two fifty.', 'O total é quarenta e dois e cinquenta.', 'Preços em dólares são lidos em dois blocos: "forty-two fifty" = $42.50.'),
        ],
      },
      {
        id: 'lesson-shopping-a2-04',
        chapter: 4,
        title: 'Trocas e devoluções',
        description: 'Trocar, devolver e pedir reembolso.',
        units: [
          s("I'd like to return this.", 'Eu gostaria de devolver isto.', '"Return" = devolver.'),
          s('Can I exchange it for a smaller size?', 'Posso trocar por um tamanho menor?', '"Exchange for" = trocar por.'),
          s('Do you have the receipt?', 'Você tem o recibo?', 'Pergunta comum antes de qualquer troca.'),
          s("It doesn't work.", 'Não está funcionando.', '"Work" = funcionar.'),
          s('It was damaged when I opened it.', 'Estava danificado quando abri.', 'Passado com "when": "when I opened it".'),
          s('Can I get a refund?', 'Posso ter o dinheiro de volta?', '"Refund" = reembolso.'),
          s("What's your return policy?", 'Qual é a política de devolução?', '"Return policy" = regras de troca e devolução.'),
          s('You have thirty days to return it.', 'Você tem trinta dias para devolver.', '"Have" + prazo + "to" + verbo.'),
          s('We can only give you store credit.', 'Só podemos dar crédito na loja.', '"Store credit" = vale para usar na própria loja.'),
          s('I never used it.', 'Eu nunca usei.', 'Passado simples + "never".'),
        ],
      },
      {
        id: 'lesson-shopping-a2-05',
        chapter: 5,
        title: 'Compras online e entregas',
        description: 'Pedido, frete, rastreio e entrega.',
        units: [
          s('I ordered it online last week.', 'Pedi pela internet semana passada.', '"Order" = pedir, encomendar. "Online" = pela internet.'),
          s('Is shipping free?', 'O frete é grátis?', '"Shipping" = frete, envio.'),
          s('When will it arrive?', 'Quando vai chegar?', 'Futuro com "will" em pergunta.'),
          s('My order is late.', 'Meu pedido está atrasado.', '"Order" como substantivo = pedido.'),
          s('Can I track my package?', 'Posso rastrear meu pacote?', '"Track" = rastrear. "Package" = pacote.'),
          s('It was delivered to the wrong address.', 'Foi entregue no endereço errado.', 'Voz passiva no passado: "was delivered".'),
          s('Nobody was home when they came.', 'Não tinha ninguém em casa quando eles vieram.', '"Nobody was" = não tinha ninguém.'),
          s('I want to cancel my order.', 'Quero cancelar meu pedido.', '"Cancel" = cancelar.'),
          s('The item is out of stock.', 'O item está esgotado.', '"Out of stock" = sem estoque.'),
          s('Please leave it at the door.', 'Por favor, deixe na porta.', 'Instrução comum para entregadores.'),
        ],
      },
      {
        id: 'lesson-shopping-a2-06',
        chapter: 6,
        title: 'Reclamar com educação',
        description: 'Resolver problemas sem perder a razão.',
        units: [
          s("I'm not happy with this product.", 'Não estou satisfeito com este produto.', '"Happy with" = satisfeito com.'),
          s("I'd like to make a complaint.", 'Eu gostaria de fazer uma reclamação.', '"Make a complaint" = reclamar formalmente.'),
          s('I was charged twice.', 'Fui cobrado duas vezes.', 'Voz passiva: "was charged".'),
          s('This is not what I ordered.', 'Isto não é o que eu pedi.', '"What I ordered" = o que eu pedi.'),
          s('Can I speak to the manager, please?', 'Posso falar com o gerente, por favor?', 'Pedido educado; "please" evita soar agressivo.'),
          s("I've been waiting for two weeks.", 'Estou esperando há duas semanas.', 'Present perfect contínuo + "for": ainda está esperando.'),
          s('What can you do about it?', 'O que vocês podem fazer a respeito?', '"About it" = a respeito disso.'),
          s('I understand, but this is not fair.', 'Entendo, mas isso não é justo.', '"I understand, but" mostra empatia e mantém o pedido.'),
          s('Thank you for solving this.', 'Obrigado por resolver.', '"Thank you for" + verbo com "-ing".'),
          s("I'll leave a review.", 'Vou deixar uma avaliação.', '"Leave a review" = avaliar a loja.'),
        ],
      },
    ],
  },
];
