// Lote debate-b2-1: curso novo "Argumentar e Debater" (B2, trilha Fluência), capítulos 1–6:
// opinar e justificar, evidências e exemplos, contra-argumentar, conceder e redirecionar,
// perguntas que testam um argumento, concluir e persuadir. Notas dizem o efeito da frase
// (firme, cortês, retórico). Conteúdo original.

export const LEXICON = {
  according: ["adverb", "/əˈkɔːrdɪŋ/", "de acordo (com)"],
  achieve: ["verb", "/əˈtʃiːv/", "conquistar, alcançar"],
  admittedly: ["adverb", "/ədˈmɪtɪdli/", "é preciso admitir"],
  affects: ["verb", "/əˈfɛkts/", "afeta"],
  agrees: ["verb", "/əˈɡriːz/", "concorda"],
  argue: ["verb", "/ˈɑːrɡjuː/", "defender, sustentar"],
  argument: ["noun", "/ˈɑːrɡjəmənt/", "argumento"],
  aside: ["adverb", "/əˈsaɪd/", "de lado"],
  assuming: ["verb", "/əˈsuːmɪŋ/", "presumindo"],
  backed: ["verb", "/bækt/", "apoiado"],
  ban: ["verb", "/bæn/", "proibir"],
  benefit: ["verb", "/ˈbɛnɪfɪt/", "beneficiar-se"],
  cars: ["noun", "/kɑːrz/", "carros"],
  cities: ["noun", "/ˈsɪtiz/", "cidades"],
  concerned: ["adjective", "/kənˈsɜːrnd/", "preocupado, envolvido"],
  concrete: ["adjective", "/ˈkɑːnkriːt/", "concreto"],
  consequences: ["noun", "/ˈkɑːnsəkwɛnsɪz/", "consequências"],
  contrary: ["noun", "/ˈkɑːntrɛri/", "contrário"],
  convinced: ["adjective", "/kənˈvɪnst/", "convencido"],
  crime: ["noun", "/kraɪm/", "crime"],
  differently: ["adverb", "/ˈdɪfrəntli/", "de outro jeito"],
  education: ["noun", "/ˌɛdʒuˈkeɪʃən/", "educação"],
  effects: ["noun", "/ɪˈfɛkts/", "efeitos"],
  evidence: ["noun", "/ˈɛvɪdəns/", "evidência"],
  fact: ["noun", "/fækt/", "fato"],
  fails: ["verb", "/feɪlz/", "falha"],
  fairness: ["noun", "/ˈfɛrnəs/", "justiça, equidade"],
  flaws: ["noun", "/flɔːz/", "falhas"],
  grant: ["verb", "/ɡrænt/", "admitir, conceder"],
  ignore: ["verb", "/ɪɡˈnɔːr/", "ignorar"],
  ignores: ["verb", "/ɪɡˈnɔːrz/", "ignora"],
  imagine: ["verb", "/ɪˈmædʒɪn/", "imaginar"],
  instance: ["noun", "/ˈɪnstəns/", "exemplo, caso"],
  involved: ["adjective", "/ɪnˈvɑːlvd/", "envolvido"],
  latest: ["adjective", "/ˈleɪtɪst/", "mais recente"],
  logic: ["noun", "/ˈlɑːdʒɪk/", "lógica"],
  "long-term": ["adjective", "/ˌlɔːŋ ˈtɜːrm/", "de longo prazo"],
  memory: ["noun", "/ˈmɛməri/", "memória"],
  necessarily: ["adverb", "/ˌnɛsəˈsɛrəli/", "necessariamente"],
  outweigh: ["verb", "/ˌaʊtˈweɪ/", "pesar mais que"],
  overlooks: ["verb", "/ˌoʊvərˈlʊks/", "ignora, deixa passar"],
  oversimplification: ["noun", "/ˌoʊvərˌsɪmpləfɪˈkeɪʃən/", "simplificação exagerada"],
  pays: ["verb", "/peɪz/", "paga"],
  personally: ["adverb", "/ˈpɜːrsənəli/", "pessoalmente"],
  plenty: ["noun", "/ˈplɛnti/", "bastante, muito"],
  proceed: ["verb", "/prəˈsiːd/", "prosseguir"],
  proof: ["noun", "/pruːf/", "prova"],
  reason: ["noun", "/ˈriːzən/", "motivo, razão"],
  rising: ["verb", "/ˈraɪzɪŋ/", "subindo"],
  safety: ["noun", "/ˈseɪfti/", "segurança"],
  solid: ["adjective", "/ˈsɑːlɪd/", "sólido"],
  solve: ["verb", "/sɑːlv/", "resolver"],
  strongly: ["adverb", "/ˈstrɔːŋli/", "firmemente"],
  supported: ["verb", "/səˈpɔːrtɪd/", "sustentado, apoiado"],
  urge: ["verb", "/ɜːrdʒ/", "pedir com insistência"],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-debate-b2-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-debate-b2',
    slug: 'argue-and-debate-b2',
    title: 'Argumentar e Debater',
    level: 'B2',
    category: 'social',
    track: 'fluencia',
    trackOrder: 4,
    order: 23,
    short: 'Defender uma ideia, rebater com educação e persuadir: o inglês de quem debate.',
    long: 'Como sustentar uma opinião, citar evidências, discordar sem ofender, ceder um ponto para ganhar outro e fechar com impacto. Cada frase vem com a função no debate e o tom que ela passa.',
    lessons: [
      lesson(1, 'Opinar e justificar', 'Dizer o que pensa e dar o motivo.', [
        s('In my view, remote work is here to stay.', 'Na minha visão, o trabalho remoto veio para ficar.', '"In my view" abre uma opinião pessoal com firmeza.'),
        s('I strongly believe that education should be free.', 'Acredito firmemente que a educação deveria ser gratuita.', '"Strongly believe" reforça a convicção.'),
        s('The reason I say this is that costs keep rising.', 'O motivo de eu dizer isso é que os custos não param de subir.', '"The reason is that" liga a opinião à justificativa.'),
        s('It seems to me that we are asking the wrong question.', 'Parece-me que estamos fazendo a pergunta errada.', '"It seems to me" é uma opinião mais cuidadosa.'),
        s('As far as I am concerned, safety comes first.', 'Quanto a mim, a segurança vem em primeiro lugar.', '"As far as I am concerned" = no que me diz respeito.'),
        s('I would argue that this is a matter of fairness.', 'Eu diria que isso é uma questão de justiça.', '"I would argue that" apresenta uma tese de forma educada.'),
        s('Personally, I think the benefits outweigh the risks.', 'Pessoalmente, acho que os benefícios superam os riscos.', '"Outweigh" = pesar mais que.'),
        s('That is exactly why we need a clear policy.', 'É exatamente por isso que precisamos de uma política clara.', '"That is why" conclui o raciocínio.'),
        s('To put it simply, the plan is too expensive.', 'Resumindo, o plano é caro demais.', '"To put it simply" simplifica antes da conclusão.'),
        s('I feel very strongly about this issue.', 'Tenho uma posição muito firme sobre esse assunto.', '"Feel strongly about" = ter opinião forte.'),
      ]),
      lesson(2, 'Evidências e exemplos', 'Sustentar o argumento com dados e casos.', [
        s('For instance, several cities have already done this.', 'Por exemplo, várias cidades já fizeram isso.', '"For instance" introduz um exemplo.'),
        s('Studies show that sleep affects memory.', 'Estudos mostram que o sono afeta a memória.', '"Studies show" cita pesquisa sem apontar uma.'),
        s('According to the latest report, crime is down.', 'De acordo com o relatório mais recente, o crime diminuiu.', '"According to" atribui a fonte.'),
        s('This is backed up by solid evidence.', 'Isso é sustentado por evidências sólidas.', '"Backed up by" = apoiado em.'),
        s('A good example of this is the new law.', 'Um bom exemplo disso é a nova lei.', 'Pede ao ouvinte que examine um caso.'),
        s('Let us look at the numbers more closely.', 'Vamos olhar os números mais de perto.', 'Convida a analisar os dados.'),
        s('That claim is not supported by the data.', 'Essa afirmação não é sustentada pelos dados.', '"Not supported by" = sem base nos dados.'),
        s('In fact, the opposite is true.', 'Na verdade, o contrário é verdade.', '"In fact" corrige com firmeza.'),
        s('Take, for example, the case of Japan.', 'Tome, por exemplo, o caso do Japão.', '"Take, for example" é um jeito retórico de exemplificar.'),
        s('There is plenty of proof that it works.', 'Há muita prova de que funciona.', '"Plenty of" = bastante; "proof" não tem plural.'),
      ]),
      lesson(3, 'Contra-argumentar', 'Rebater uma ideia com respeito.', [
        s('I take your point, but I see it differently.', 'Entendo o que você diz, mas vejo de outro jeito.', '"I take your point" reconhece o argumento antes de rebater.'),
        s('That might be true, but it overlooks one thing.', 'Pode ser verdade, mas isso ignora um ponto.', '"Overlook" = deixar passar, não considerar.'),
        s('I am not convinced that this will solve the problem.', 'Não estou convencido de que isso resolva o problema.', 'Cético, mas não hostil.'),
        s('On the contrary, it could make things worse.', 'Pelo contrário, pode piorar as coisas.', '"On the contrary" nega a ideia anterior.'),
        s('The problem with that argument is that it ignores costs.', 'O problema desse argumento é que ele ignora os custos.', 'Aponta a falha sem atacar a pessoa.'),
        s('That is an oversimplification.', 'Isso é uma simplificação exagerada.', '"Oversimplification" = simplificar demais.'),
        s('You are assuming that everyone agrees.', 'Você está presumindo que todos concordam.', 'Expõe uma premissa não provada.'),
        s('I would question that conclusion.', 'Eu questionaria essa conclusão.', '"Question" como verbo = pôr em dúvida.'),
        s('That does not necessarily follow.', 'Isso não decorre necessariamente.', 'Forma lógica de dizer "nem sempre é assim".'),
        s('By the same logic, we would have to ban cars.', 'Pela mesma lógica, teríamos que proibir os carros.', 'Reductio: leva o argumento ao extremo.'),
      ]),
      lesson(4, 'Conceder e redirecionar', 'Ceder um ponto para fortalecer o seu.', [
        s('I will grant you that the cost is high.', 'Concordo que o custo é alto.', '"Grant" = admitir um ponto.'),
        s('You are right about that, but there is more to it.', 'Você tem razão nisso, mas há mais coisa.', 'Concede e amplia a discussão.'),
        s('Admittedly, the plan has some flaws.', 'É verdade que o plano tem algumas falhas.', '"Admittedly" = é preciso admitir.'),
        s('Even so, the benefits are hard to ignore.', 'Mesmo assim, os benefícios são difíceis de ignorar.', '"Even so" retoma o ponto principal.'),
        s('That said, we should not give up yet.', 'Dito isso, não devemos desistir ainda.', '"That said" faz a virada depois da concessão.'),
        s('Fair enough, but let me explain why I disagree.', 'Justo, mas deixa eu explicar por que discordo.', 'Concede e pede espaço para falar.'),
        s('I accept that there are risks involved.', 'Aceito que há riscos envolvidos.', 'Admite sem abandonar a tese.'),
        s('While that is true, it is only half the story.', 'Embora seja verdade, é só metade da história.', '"While" com sentido de "embora".'),
        s('Let us set that aside and focus on the main issue.', 'Vamos deixar isso de lado e focar no assunto principal.', '"Set aside" = deixar de lado.'),
        s('The real question is who pays for it.', 'A verdadeira questão é quem paga por isso.', 'Redireciona o debate para o ponto que importa.'),
      ]),
      lesson(5, 'Perguntas que testam', 'Perguntar para esclarecer e para expor falhas.', [
        s('What exactly do you mean by that?', 'O que exatamente você quer dizer com isso?', '"What exactly" pede precisão.'),
        s('Could you give me a concrete example?', 'Você poderia me dar um exemplo concreto?', '"Concrete" = específico, real.'),
        s('How do you know that is the case?', 'Como você sabe que é assim?', 'Pede a base da afirmação.'),
        s('Who would benefit from this change?', 'Quem se beneficiaria dessa mudança?', 'Pergunta de interesse e justiça.'),
        s('What happens if the plan fails?', 'O que acontece se o plano falhar?', 'Testa o risco da proposta.'),
        s('Is that really the only option?', 'Será que essa é mesmo a única opção?', '"Really" faz a pergunta soar cética.'),
        s('Are you saying that we should do nothing?', 'Você está dizendo que não devemos fazer nada?', 'Exagera para o outro esclarecer.'),
        s('Where is the evidence for that claim?', 'Onde está a evidência dessa afirmação?', 'Direta; usar com cuidado, pois pode soar ríspida.'),
        s('Have you considered the long-term effects?', 'Você considerou os efeitos de longo prazo?', 'Pergunta educada que mostra uma lacuna.'),
        s('Would you say that again, more slowly?', 'Você poderia repetir, mais devagar?', 'Também vale em debate quando o ritmo é rápido.'),
      ]),
      lesson(6, 'Concluir e persuadir', 'Fechar com um resumo e um apelo.', [
        s('In conclusion, the evidence points one way.', 'Em conclusão, as evidências apontam para um lado.', '"In conclusion" sinaliza o fim.'),
        s('All things considered, I believe we should proceed.', 'Considerando tudo, acredito que devemos seguir em frente.', '"All things considered" resume o equilíbrio.'),
        s('The bottom line is that we cannot afford to wait.', 'O ponto central é que não podemos nos dar ao luxo de esperar.', '"The bottom line" = o essencial.'),
        s('I urge you to think about the consequences.', 'Peço que você pense nas consequências.', '"Urge" = pedir com insistência.'),
        s('We have a chance to get this right.', 'Temos a chance de acertar nisso.', 'Apelo positivo para a ação.'),
        s('Imagine what we could achieve together.', 'Imagine o que poderíamos conquistar juntos.', 'Convida o ouvinte a visualizar.'),
        s('The choice is clear, and the time is now.', 'A escolha é clara, e o momento é agora.', 'Fecho retórico com ritmo.'),
        s('Let me leave you with one final thought.', 'Deixa eu te deixar com um último pensamento.', 'Abre o fechamento.'),
        s('I hope I have made my position clear.', 'Espero ter deixado minha posição clara.', 'Encerra com cortesia.'),
        s('Thank you for listening, and I welcome your questions.', 'Obrigado por ouvir, e recebo suas perguntas.', 'Encerramento formal de apresentação ou debate.'),
      ]),
    ],
  },
];
