// Lote fluencia-2: Expressões Idiomáticas e Fluência (B2), capítulos 7–10:
// relacionamentos, problemas e soluções, opinião e discordância, esforço e ritmo.
// Mesmo curso do lote fluencia-1 (metadados idênticos): este lote só acrescenta
// lições e frases. Notas com registro e sentido literal × real. Conteúdo original.

export const LEXICON = {
  barking: ['verb', '/ˈbɑːrkɪŋ/', 'latindo'],
  batteries: ['noun', '/ˈbætəriz/', 'baterias, pilhas'],
  beg: ['verb', '/bɛɡ/', 'pedir, implorar'],
  blessing: ['noun', '/ˈblɛsɪŋ/', 'bênção'],
  bud: ['noun', '/bʌd/', 'broto'],
  burning: ['verb', '/ˈbɜːrnɪŋ/', 'queimando'],
  bush: ['noun', '/bʊʃ/', 'arbusto, moita'],
  differ: ['verb', '/ˈdɪfər/', 'divergir, discordar'],
  disguise: ['noun', '/dɪsˈɡaɪz/', 'disfarce'],
  ends: ['noun', '/ɛndz/', 'pontas, extremidades'],
  'fair-weather': ['adjective', '/ˈfɛrwɛðər/', 'só das horas boas'],
  fence: ['noun', '/fɛns/', 'cerca, muro'],
  grain: ['noun', '/ɡreɪn/', 'grão'],
  gun: ['noun', '/ɡʌn/', 'arma; tiro de largada'],
  honesty: ['noun', '/ˈɑːnəsti/', 'honestidade'],
  iceberg: ['noun', '/ˈaɪsbɜːrɡ/', 'iceberg'],
  knot: ['noun', '/nɑːt/', 'nó'],
  matter: ['noun', '/ˈmætər/', 'questão, assunto'],
  mile: ['noun', '/maɪl/', 'milha'],
  missing: ['verb', '/ˈmɪsɪŋ/', 'perdendo, deixando de captar'],
  nipped: ['verb', '/nɪpt/', 'cortou, beliscou'],
  "other's": ['pronoun', '/ˈʌðərz/', 'do outro'],
  pace: ['noun', '/peɪs/', 'ritmo, passo'],
  patch: ['verb', '/pætʃ/', 'remendar, consertar'],
  payment: ['noun', '/ˈpeɪmənt/', 'pagamento'],
  recharge: ['verb', '/riːˈtʃɑːrdʒ/', 'recarregar'],
  rock: ['noun', '/rɑːk/', 'rocha; apoio firme'],
  snag: ['noun', '/snæɡ/', 'empecilho, obstáculo'],
  stone: ['noun', '/stoʊn/', 'pedra'],
  thicker: ['adjective', '/ˈθɪkər/', 'mais grosso, mais forte'],
  throats: ['noun', '/θroʊts/', 'gargantas'],
  tied: ['verb', '/taɪd/', 'amarrou, deu (o nó)'],
  // O léxico geral tem uma entrada por palavra, sem contexto. Estas valem só para este lote
  // (os lotes já publicados não mudam) e corrigem o sentido nas frases daqui.
  beat: ['verb', '/biːt/', 'bater; rodear (beat around the bush)'],
  book: ['noun', '/bʊk/', 'livro (in my book = na minha visão)'],
  cold: ['adjective', '/koʊld/', 'frio'],
  hang: ['verb', '/hæŋ/', 'pendurar; aguentar (hang in there)'],
  last: ['adjective', '/læst/', 'último; passado (last June)'],
  one: ['numeral', '/wʌn/', 'um, uma'],
  over: ['preposition', '/ˈoʊvər/', 'ao longo de; por cima de'],
  park: ['noun', '/pɑːrk/', 'parque'],
  right: ['adverb', '/raɪt/', 'logo, imediatamente (right away)'],
  running: ['verb', '/ˈrʌnɪŋ/', 'rodando, funcionando'],
  square: ['noun', '/skwɛr/', 'quadrado; casa (square one = estaca zero)'],
  step: ['noun', '/stɛp/', 'passo'],
  tip: ['noun', '/tɪp/', 'ponta, topo'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-idioms-b2',
    slug: 'idioms-fluency-b2',
    title: 'Expressões Idiomáticas e Fluência',
    level: 'B2',
    category: 'social',
    track: 'fluencia',
    trackOrder: 1,
    order: 11,
    short: 'Idioms que nativos usam de verdade e os recursos que deixam sua fala natural: marcadores, opiniões suaves e histórias.',
    long: 'Expressões idiomáticas de trabalho, sentimentos, dinheiro e tempo, e as ferramentas de fluência que separam o B1 do B2: marcadores de conversa ("actually", "I mean"), como suavizar opiniões e como contar uma história. Cada nota traz o registro e o sentido literal × o real.',
    lessons: [
      {
        id: 'lesson-idioms-b2-07',
        chapter: 7,
        title: 'Idioms de relacionamentos',
        description: 'Falar de amizade, família e casal do jeito nativo.',
        units: [
          s('We hit it off right away.', 'A gente se deu bem logo de cara.', 'Informal. "Hit it off" = ter afinidade imediata com alguém. Não tem sentido de bater.'),
          s("They're always at each other's throats.", 'Eles vivem brigando.', 'Informal. Literal: "na garganta um do outro". Real: brigam o tempo todo.'),
          s("She's been a rock for me.", 'Ela tem sido meu porto seguro.', 'Neutro. Literal: "uma rocha". Real: pessoa firme em quem dá para confiar.'),
          s("We've grown apart over the years.", 'Nós nos afastamos ao longo dos anos.', 'Neutro. "Grow apart" = ir se distanciando aos poucos, sem briga.'),
          s("He's a fair-weather friend.", 'Ele só é amigo nas horas boas.', 'Neutro, crítico. Literal: "amigo de tempo bom". Some quando o clima fica difícil.'),
          s('I need to patch things up with my brother.', 'Preciso fazer as pazes com meu irmão.', 'Informal. Literal: "remendar as coisas". Real: consertar a relação depois de uma briga.'),
          s('They tied the knot last June.', 'Eles se casaram em junho do ano passado.', 'Informal. Literal: "deram o nó". Real: casaram. Em texto formal use "got married".'),
          s('She gave me the cold shoulder all week.', 'Ela me tratou com frieza a semana toda.', 'Neutro. "Give someone the cold shoulder" = ignorar de propósito, ser fria.'),
          s('We see eye to eye on most things.', 'A gente concorda na maioria das coisas.', 'Neutro. Literal: "ver olho no olho". Real: pensar parecido.'),
          s('Blood is thicker than water.', 'Os laços de família falam mais alto.', 'Neutro. Provérbio: o vínculo de família pesa mais que outros vínculos.'),
        ],
      },
      {
        id: 'lesson-idioms-b2-08',
        chapter: 8,
        title: 'Idioms de problemas e soluções',
        description: 'Expressões para contar o que deu errado e como resolver.',
        units: [
          s('We hit a snag with the payment.', 'Esbarramos num problema com o pagamento.', 'Neutro, comum no trabalho. "Snag" = empecilho inesperado. "Hit a snag" = esbarrar num problema.'),
          s("Let's not beat around the bush.", 'Vamos direto ao ponto.', 'Informal. Literal: "bater ao redor do arbusto". Real: rodear sem dizer o que importa.'),
          s("It's back to square one.", 'Voltamos à estaca zero.', 'Neutro. "Square one" = a casa de partida. Tudo o que foi feito se perdeu.'),
          s("That's a blessing in disguise.", 'No fim, isso foi até uma coisa boa.', 'Neutro. Literal: "bênção disfarçada". Real: algo ruim que acaba trazendo um benefício.'),
          s("We're in the same boat.", 'Estamos no mesmo barco.', 'Neutro. Igual ao português: a mesma situação difícil.'),
          s("It's just the tip of the iceberg.", 'Isso é só a ponta do iceberg.', 'Neutro. Igual ao português: o problema é bem maior do que aparece.'),
          s("I'll sleep on it.", 'Vou pensar com calma e te respondo amanhã.', 'Informal. Literal: "dormir sobre isso". Real: adiar a decisão para o dia seguinte.'),
          s('She nipped the problem in the bud.', 'Ela cortou o problema pela raiz.', 'Informal. "Bud" = broto. Real: resolver antes de crescer.'),
          s("Let's kill two birds with one stone.", 'Vamos matar dois coelhos com uma cajadada só.', 'Informal. Em inglês são "dois pássaros", em português "dois coelhos". Resolver duas coisas de uma vez.'),
          s("Don't jump the gun.", 'Não se precipite.', 'Informal. Literal: "pular o tiro" (largar antes do sinal). Real: agir antes da hora.'),
        ],
      },
      {
        id: 'lesson-idioms-b2-09',
        chapter: 9,
        title: 'Idioms de opinião e discordância',
        description: 'Concordar, discordar e duvidar com expressões naturais.',
        units: [
          s("I couldn't agree more.", 'Concordo plenamente.', 'Neutro. Literal: "não poderia concordar mais". Real: concordo totalmente.'),
          s("That's easier said than done.", 'É mais fácil falar do que fazer.', 'Neutro. Igual ao provérbio em português.'),
          s('I beg to differ.', 'Com todo o respeito, discordo.', 'Formal. Literal: "peço para diferir". Educado, mas firme. Soa antiquado em conversa casual.'),
          s("You're missing the point.", 'Você não está entendendo o ponto principal.', 'Neutro. "Miss the point" = não captar o que realmente importa. Pode soar ríspido.'),
          s("Let's agree to disagree.", 'Vamos concordar em discordar.', 'Neutro. Real: encerrar a discussão aceitando que cada um pensa diferente.'),
          s("That's a matter of opinion.", 'Isso é questão de opinião.', 'Neutro. Quando algo não é fato, é ponto de vista.'),
          s("He's barking up the wrong tree.", 'Ele está no caminho errado.', 'Informal. Literal: "latindo para a árvore errada". Real: procurar ou acusar a pessoa ou o lugar errado.'),
          s("I'm on the fence about it.", 'Estou em dúvida sobre isso.', 'Informal. Literal: "em cima da cerca". Real: indeciso entre duas opções, como "ficar em cima do muro".'),
          s('In my book, honesty comes first.', 'Para mim, a honestidade vem em primeiro lugar.', 'Informal. Literal: "no meu livro". Real: na minha visão, para mim.'),
          s('I take everything he says with a grain of salt.', 'Eu levo tudo o que ele diz com um pé atrás.', 'Neutro. Literal: "com um grão de sal". Real: com desconfiança, sem aceitar tudo como verdade.'),
        ],
      },
      {
        id: 'lesson-idioms-b2-10',
        chapter: 10,
        title: 'Idioms de esforço e ritmo',
        description: 'Falar de trabalho puxado, cansaço, persistência e energia.',
        units: [
          s("I'm swamped at work.", 'Estou atolado de trabalho.', 'Informal. "Swamped" = coberto de pântano. Real: com trabalho demais para dar conta.'),
          s("She's burning the candle at both ends.", 'Ela está se esgotando de tanto trabalhar.', 'Informal. Literal: "queimando a vela pelas duas pontas". Real: trabalhar e dormir pouco, sem descanso.'),
          s("Let's take it one step at a time.", 'Vamos um passo de cada vez.', 'Neutro. Igual ao português: sem pressa, uma etapa por vez.'),
          s("I'm running on empty.", 'Estou sem energia nenhuma.', 'Informal. Literal: "rodando no vazio" (como um carro sem combustível). Real: exausto.'),
          s('He gave it his all.', 'Ele deu o máximo de si.', 'Neutro. "Give it your all" = esforçar-se ao máximo, mesmo que não dê certo.'),
          s("Don't give up. Hang in there.", 'Não desista. Aguenta firme.', 'Informal. Literal: "fique pendurado aí". Real: persistir numa fase difícil.'),
          s("We're going the extra mile for this client.", 'Estamos fazendo além do esperado por esse cliente.', 'Neutro. Literal: "andar a milha extra". Real: fazer mais do que o necessário.'),
          s('That was a walk in the park.', 'Isso foi moleza.', 'Informal. Literal: "um passeio no parque". Real: muito fácil.'),
          s("Let's pick up the pace.", 'Vamos acelerar o ritmo.', 'Neutro. "Pick up the pace" = andar ou trabalhar mais rápido.'),
          s('I need to recharge my batteries.', 'Preciso recarregar as baterias.', 'Neutro. Igual ao português: descansar para recuperar a energia.'),
        ],
      },
    ],
  },
];
