// Lote fluencia-1: curso novo "Expressões Idiomáticas e Fluência" (B2, trilha
// Fluência), capítulos 1–6. Notas com registro e sentido literal × real.
// Conteúdo original.

export const LEXICON = {
  actually: ['adverb', '/ˈæktʃuəli/', 'na verdade'],
  basically: ['adverb', '/ˈbeɪsɪkli/', 'basicamente'],
  correct: ['verb', '/kəˈrɛkt/', 'corrigir'],
  luckily: ['adverb', '/ˈlʌkɪli/', 'por sorte'],
  against: ['preposition', '/əˈɡɛnst/', 'contra'],
  bad: ['adjective', '/bæd/', 'ruim'],
  ball: ['noun', '/bɔːl/', 'bola'],
  base: ['noun', '/beɪs/', 'base'],
  box: ['noun', '/bɑːks/', 'caixa'],
  butterflies: ['noun', '/ˈbʌtərflaɪz/', 'borboletas'],
  cloud: ['noun', '/klaʊd/', 'nuvem'],
  corners: ['noun', '/ˈkɔːrnərz/', 'cantos'],
  design: ['noun', '/dɪˈzaɪn/', 'design'],
  exactly: ['adverb', '/ɪɡˈzæktli/', 'exatamente'],
  flew: ['verb', '/fluː/', 'voou'],
  flies: ['verb', '/flaɪz/', 'voa'],
  fortune: ['noun', '/ˈfɔːrtʃən/', 'fortuna'],
  funny: ['adjective', '/ˈfʌni/', 'engraçado'],
  'go-to': ['adjective', '/ˈɡoʊtuː/', 'de referência'],
  joke: ['noun', '/dʒoʊk/', 'piada'],
  keeps: ['verb', '/kiːps/', 'mantém'],
  loaded: ['adjective', '/ˈloʊdɪd/', 'cheio da grana (gíria)'],
  loop: ['noun', '/luːp/', 'circuito, laço'],
  might: ['modal verb', '/maɪt/', 'talvez, poderia'],
  moon: ['noun', '/muːn/', 'lua'],
  nerves: ['noun', '/nɜːrvz/', 'nervos'],
  nick: ['noun', '/nɪk/', 'momento exato (nick of time)'],
  page: ['noun', '/peɪdʒ/', 'página'],
  possible: ['adjective', '/ˈpɑːsəbəl/', 'possível'],
  pretty: ['adverb', '/ˈprɪti/', 'bem, bastante'],
  respect: ['noun', '/rɪˈspɛkt/', 'respeito'],
  rolling: ['verb', '/ˈroʊlɪŋ/', 'rolando'],
  rope: ['noun', '/roʊp/', 'corda'],
  saving: ['verb', '/ˈseɪvɪŋ/', 'economizando'],
  short: ['adjective', '/ʃɔːrt/', 'curto'],
  situation: ['noun', '/ˌsɪtʃuˈeɪʃən/', 'situação'],
  sudden: ['adjective', '/ˈsʌdən/', 'repentino'],
  suggest: ['verb', '/səɡˈdʒɛst/', 'sugerir'],
  waste: ['verb', '/weɪst/', 'desperdiçar'],
  'win-win': ['adjective', '/ˌwɪnˈwɪn/', 'bom para todos'],
  wondering: ['verb', '/ˈwʌndərɪŋ/', 'me perguntando'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-idioms-b2',
    slug: 'idioms-fluency-b2',
    title: 'Expressões Idiomáticas e Fluência',
    level: 'B2',
    category: 'social',
    track: 'fluencia',
    trackOrder: 1,
    order: 11,
    short: 'Idioms que nativos usam de verdade e os recursos que deixam sua fala natural: marcadores, opiniões suaves e histórias.',
    long: 'Expressões idiomáticas de trabalho, sentimentos, dinheiro e tempo, e as ferramentas de fluência que separam o B1 do B2: marcadores de conversa ("actually", "I mean"), como suavizar opiniões e como contar uma história. Cada nota traz o registro e o sentido literal × o real.',
    lessons: [
      {
        id: 'lesson-idioms-b2-01',
        chapter: 1,
        title: 'Idioms de trabalho',
        description: 'Expressões que aparecem em reuniões e e-mails.',
        units: [
          s("Let's touch base next week.", 'Vamos nos falar semana que vem.', 'Informal/trabalho. Literal: "tocar a base". Real: fazer um contato rápido.'),
          s('We are on the same page.', 'Estamos alinhados.', 'Neutro. Literal: "na mesma página". Real: de acordo.'),
          s("Let's think outside the box.", 'Vamos pensar fora da caixa.', 'Neutro. Igual ao português.'),
          s("I'll keep you in the loop.", 'Vou te manter informado.', 'Trabalho. "In the loop" = por dentro do assunto.'),
          s('That project is back on track.', 'O projeto voltou aos trilhos.', '"On track" = no caminho certo.'),
          s("It's a win-win situation.", 'Todo mundo sai ganhando.', 'Neutro. "Win-win" = bom para os dois lados.'),
          s("Let's get the ball rolling.", 'Vamos dar o pontapé inicial.', 'Informal. Literal: "fazer a bola rolar".'),
          s('We need to cut corners to finish on time.', 'Precisamos simplificar para terminar no prazo.', 'Informal, às vezes negativo: "cut corners" = fazer de qualquer jeito.'),
          s("She's the go-to person for design.", 'Ela é a referência em design.', 'Informal. "Go-to" = a pessoa a quem se recorre.'),
          s("Let's call it a day.", 'Vamos encerrar por hoje.', 'Informal. Revisão do A1, agora no contexto de trabalho.'),
        ],
      },
      {
        id: 'lesson-idioms-b2-02',
        chapter: 2,
        title: 'Idioms de sentimentos',
        description: 'Dizer como você se sente com expressões nativas.',
        units: [
          s("I'm on cloud nine.", 'Estou nas nuvens.', 'Informal. Literal: "na nuvem nove". Real: muito feliz.'),
          s('I had butterflies in my stomach.', 'Eu estava com frio na barriga.', 'Informal. Literal: "borboletas no estômago".'),
          s('She was over the moon.', 'Ela ficou radiante.', 'Informal. Literal: "acima da lua".'),
          s("I'm feeling a bit down.", 'Estou meio pra baixo.', 'Informal. "Down" = triste, desanimado.'),
          s('He flew off the handle.', 'Ele perdeu a cabeça.', 'Informal. Literal: "voou do cabo". Real: explodiu de raiva.'),
          s('It broke my heart.', 'Partiu meu coração.', 'Neutro. Igual ao português.'),
          s("I'm at the end of my rope.", 'Estou no meu limite.', 'Informal. Literal: "no fim da minha corda".'),
          s('She keeps her cool under pressure.', 'Ela mantém a calma sob pressão.', '"Keep your cool" = manter a calma; "lose your cool" = perder.'),
          s('That really got on my nerves.', 'Aquilo me irritou de verdade.', 'Informal. "Get on someone\'s nerves" = irritar.'),
          s("I'm walking on air.", 'Estou flutuando de felicidade.', 'Informal. Literal: "andando no ar".'),
        ],
      },
      {
        id: 'lesson-idioms-b2-03',
        chapter: 3,
        title: 'Idioms de dinheiro e tempo',
        description: 'Expressões sobre gastar, economizar e prazos.',
        units: [
          s('Money is tight this month.', 'O dinheiro está curto este mês.', 'Neutro. "Tight" = apertado.'),
          s("We're saving for a rainy day.", 'Estamos guardando para imprevistos.', 'Neutro. Literal: "para um dia chuvoso".'),
          s('That car cost me a fortune.', 'Aquele carro me custou uma fortuna.', 'Neutro. Igual ao português.'),
          s('He is loaded.', 'Ele é cheio da grana.', 'Gíria. Literal: "carregado". Real: muito rico.'),
          s("We're running against the clock.", 'Estamos correndo contra o tempo.', 'Neutro. Igual ao português.'),
          s('Better late than never.', 'Antes tarde do que nunca.', 'Revisão: provérbio igual ao português.'),
          s('Time flies when you are having fun.', 'O tempo voa quando a gente se diverte.', 'Neutro. "Time flies" = o tempo voa.'),
          s("I'll do it in no time.", 'Faço isso rapidinho.', 'Informal. "In no time" = muito rápido.'),
          s('We finished in the nick of time.', 'Terminamos em cima da hora.', 'Informal. "In the nick of time" = no último instante.'),
          s("Let's not waste time.", 'Vamos não perder tempo.', '"Waste time" = perder tempo (desperdiçar). "Lose time" é outra coisa.'),
        ],
      },
      {
        id: 'lesson-idioms-b2-04',
        chapter: 4,
        title: 'Marcadores de conversa',
        description: 'As palavrinhas que deixam a fala natural.',
        units: [
          s('Well, it depends on the situation.', 'Bom, depende da situação.', '"Well" no começo ganha tempo para pensar.'),
          s("Actually, I think you're wrong.", 'Na verdade, acho que você está errado.', 'Falso cognato: "actually" = na verdade, não "atualmente".'),
          s('I mean, it is not that bad.', 'Quer dizer, não é tão ruim.', '"I mean" corrige ou explica o que você acabou de dizer.'),
          s('You know, I have been thinking about it.', 'Sabe, eu tenho pensado nisso.', '"You know" busca a atenção do outro. Não exagere.'),
          s('Anyway, back to the point.', 'Enfim, voltando ao assunto.', '"Anyway" retoma o assunto principal.'),
          s('By the way, did you call her?', 'Aliás, você ligou para ela?', '"By the way" (BTW) = a propósito.'),
          s('Basically, we need more time.', 'Basicamente, precisamos de mais tempo.', 'Resume a ideia principal.'),
          s('To be fair, he did try.', 'Para ser justo, ele tentou.', '"To be fair" reconhece o outro lado.'),
          s('So, what do you think?', 'Então, o que você acha?', '"So" no começo abre ou fecha um assunto.'),
          s('Let me put it this way.', 'Deixa eu explicar de outro jeito.', 'Reformula quando o outro não entendeu.'),
        ],
      },
      {
        id: 'lesson-idioms-b2-05',
        chapter: 5,
        title: 'Suavizando opiniões',
        description: 'Discordar e criticar sem soar rude.',
        units: [
          s("I'm not sure that's the best idea.", 'Não sei se essa é a melhor ideia.', 'Suaviza "that\'s a bad idea".'),
          s('It might be a good idea to wait.', 'Talvez seja uma boa ideia esperar.', '"Might" deixa a sugestão menos direta.'),
          s("I see your point, but I'd suggest something else.", 'Entendo seu ponto, mas eu sugeriria outra coisa.', 'Reconhece e depois propõe.'),
          s("It's not exactly what we expected.", 'Não é bem o que esperávamos.', '"Not exactly" suaviza uma crítica.'),
          s('Would it be possible to change the date?', 'Seria possível mudar a data?', 'Pedido indireto, mais educado que "Can you change…?".'),
          s('I was wondering if you could help me.', 'Eu queria saber se você poderia me ajudar.', 'Passado contínuo deixa o pedido bem educado.'),
          s('It seems a bit expensive to me.', 'Me parece um pouco caro.', '"A bit" e "seems" suavizam.'),
          s("Correct me if I'm wrong, but…", 'Me corrija se eu estiver errado, mas…', 'Abre uma discordância com humildade.'),
          s("With all due respect, I disagree.", 'Com todo o respeito, discordo.', 'Formal. Use com cuidado: pode soar tenso.'),
          s("That's one way to look at it.", 'Essa é uma forma de ver.', 'Discorda sem invalidar a pessoa.'),
        ],
      },
      {
        id: 'lesson-idioms-b2-06',
        chapter: 6,
        title: 'Contando uma história',
        description: 'Começar, criar suspense e terminar uma história.',
        units: [
          s("You won't believe what happened to me.", 'Você não vai acreditar no que aconteceu comigo.', 'Abertura clássica que prende a atenção.'),
          s('So there I was, waiting at the station.', 'Então lá estava eu, esperando na estação.', '"So there I was" coloca o ouvinte na cena.'),
          s('All of a sudden, the lights went out.', 'De repente, as luzes se apagaram.', '"All of a sudden" = de repente. "Go out" = apagar.'),
          s('At first, I thought it was a joke.', 'No começo, achei que era piada.', '"At first" = no começo (ideia que depois muda).'),
          s('It turned out that he was the new boss.', 'No fim, ele era o chefe novo.', '"It turned out that" = acabou que.'),
          s('To make a long story short, we missed the flight.', 'Resumindo, perdemos o voo.', '"To make a long story short" = resumindo.'),
          s('Luckily, nobody got hurt.', 'Por sorte, ninguém se machucou.', '"Luckily" = por sorte. "Get hurt" = machucar-se.'),
          s('In the end, everything worked out.', 'No fim, deu tudo certo.', '"Work out" = dar certo. "In the end" = no fim.'),
          s('Looking back, it was pretty funny.', 'Olhando para trás, foi bem engraçado.', '"Looking back" = em retrospecto.'),
          s("And that's how I met my wife.", 'E foi assim que conheci minha esposa.', 'Fecho natural de uma história.'),
        ],
      },
    ],
  },
];
