// Lote frases-2: Primeiras Frases, capítulos 8–12 (can, imperativo, like +
// -ing, passado com was/were, revisão). Conteúdo original.

export const LEXICON = {
  hi: ['interjection', '/haɪ/', 'oi'],
  julia: ['proper noun', '/ˈdʒuːliə/', 'Julia'],
  born: ['verb', '/bɔːrn/', 'nascido (be born = nascer)'],
  busy: ['adjective', '/ˈbɪzi/', 'ocupado'],
  careful: ['adjective', '/ˈkɛrfəl/', 'cuidadoso'],
  cooking: ['verb', '/ˈkʊkɪŋ/', 'cozinhar (atividade)'],
  dogs: ['noun', '/dɔːɡz/', 'cachorros'],
  doing: ['verb', '/ˈduːɪŋ/', 'fazendo, fazer'],
  drive: ['verb', '/draɪv/', 'dirigir'],
  favorite: ['adjective', '/ˈfeɪvərɪt/', 'favorito'],
  getting: ['verb', '/ˈɡɛtɪŋ/', 'ficando; getting up = levantar-se'],
  hates: ['verb', '/heɪts/', 'odeia'],
  little: ['adjective', '/ˈlɪtəl/', 'pouco, pequeno'],
  love: ['verb', '/lʌv/', 'amar, adorar'],
  music: ['noun', '/ˈmjuːzɪk/', 'música'],
  pizza: ['noun', '/ˈpiːtsə/', 'pizza'],
  repeat: ['verb', '/rɪˈpiːt/', 'repetir'],
  sign: ['verb', '/saɪn/', 'assinar'],
  song: ['noun', '/sɔːŋ/', 'canção, música'],
  touch: ['verb', '/tʌtʃ/', 'tocar, encostar'],
  "wasn't": ['verb', '/ˈwʌzənt/', 'não era, não estava (was not)'],
  weekends: ['noun', '/ˈwiːkɛndz/', 'fins de semana'],
  were: ['verb', '/wɜːr/', 'eram, estavam'],
  "weren't": ['verb', '/wɜːrnt/', 'não eram, não estavam (were not)'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-first-sentences-a1',
    slug: 'first-sentences-a1',
    title: 'Primeiras Frases',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 1,
    order: 10,
    short: 'Do zero às primeiras frases: apresentar-se, perguntar, negar, pedir, falar da rotina, do que gosta e do passado.',
    long: 'Monte frases completas desde a primeira aula: verbo "to be", perguntas e negativas, "there is", possessivos, presente simples, "can", imperativo, "like + -ing" e o passado com "was/were". Cada frase vem com a explicação da estrutura.',
    lessons: [
      {
        id: 'lesson-first-sentences-a1-08',
        chapter: 8,
        title: 'Can: habilidade e pedidos',
        description: 'Dizer o que você sabe fazer e pedir com educação.',
        units: [
          s('I can swim.', 'Eu sei nadar.', '"Can" + verbo base = conseguir, saber fazer. Nunca "can to swim".'),
          s("She can't drive.", 'Ela não sabe dirigir.', 'Negativa: "can\'t" (cannot). O verbo continua na base.'),
          s('Can you speak slowly?', 'Você pode falar devagar?', 'Pergunta: "can" antes do sujeito. Também serve para pedir.'),
          s('Can I sit here?', 'Posso sentar aqui?', '"Can I…?" pede permissão de forma simples.'),
          s('Could you help me, please?', 'Você poderia me ajudar, por favor?', '"Could" é a versão mais educada de "can" para pedidos.'),
          s('I can call you later.', 'Posso te ligar depois.', '"Can" também oferece algo.'),
          s("We can't hear you.", 'Não conseguimos te ouvir.', '"Can\'t" + verbo de percepção: hear, see.'),
          s('Can he come tomorrow?', 'Ele pode vir amanhã?', '"Can" não muda com he/she/it: nada de "cans".'),
          s('Yes, you can.', 'Sim, pode.', 'Resposta curta: sujeito + "can".'),
          s('I can play the guitar a little.', 'Eu sei tocar um pouco de violão.', '"A little" = um pouco. Instrumento com "the".'),
        ],
      },
      {
        id: 'lesson-first-sentences-a1-09',
        chapter: 9,
        title: 'Imperativo: instruções e avisos',
        description: 'Dar ordens, instruções e avisos com educação.',
        units: [
          s('Open the window, please.', 'Abra a janela, por favor.', 'Imperativo = verbo base, sem sujeito. "Please" deixa educado.'),
          s("Don't touch that.", 'Não toque nisso.', 'Imperativo negativo: "don\'t" + verbo base.'),
          s('Turn right at the light.', 'Vire à direita no semáforo.', '"The light" = o semáforo (traffic light).'),
          s('Wait here, please.', 'Espere aqui, por favor.', 'Frase comum em filas e recepções.'),
          s('Be careful!', 'Cuidado!', 'Imperativo de "to be": "be" + adjetivo.'),
          s("Don't be late.", 'Não se atrase.', 'Negativo com "be": "don\'t be".'),
          s('Take a seat.', 'Sente-se.', 'Forma educada de convidar alguém a sentar.'),
          s('Call me when you get home.', 'Me liga quando chegar em casa.', '"Get home" = chegar em casa, sem "to".'),
          s('Please sign here.', 'Por favor, assine aqui.', '"Sign" = assinar; o "g" é mudo: /saɪn/.'),
          s("Let's take a break.", 'Vamos fazer uma pausa.', '"Let\'s" + verbo = vamos (sugestão que inclui você).'),
        ],
      },
      {
        id: 'lesson-first-sentences-a1-10',
        chapter: 10,
        title: 'Gostos: like, love e hate',
        description: 'Falar do que você gosta e do que não gosta.',
        units: [
          s('I like music.', 'Eu gosto de música.', '"Like" + substantivo, sem "of": nunca "like of music".'),
          s('I love cooking.', 'Eu adoro cozinhar.', '"Love/like/hate" + verbo com "-ing" para atividades.'),
          s("She doesn't like waiting.", 'Ela não gosta de esperar.', 'Negativa com "doesn\'t" + "like" + "-ing".'),
          s('Do you like dogs?', 'Você gosta de cachorros?', 'Coisas em geral vão no plural: "dogs", "movies".'),
          s('He hates getting up early.', 'Ele odeia acordar cedo.', '"Hate" = odiar. "Get up" = levantar-se.'),
          s("I'd like a coffee.", 'Eu queria um café.', '"I\'d like" (I would like) = eu gostaria. Diferente de "I like" (gosto).'),
          s('What do you like doing on weekends?', 'O que você gosta de fazer nos fins de semana?', 'Pergunta sobre hobbies.'),
          s('I really like this song.', 'Eu gosto muito desta música.', '"Really" antes do verbo reforça. "Song" = canção.'),
          s("I don't mind.", 'Tanto faz para mim.', '"I don\'t mind" = não me importo, tanto faz.'),
          s('My favorite food is pizza.', 'Minha comida favorita é pizza.', 'EUA: "favorite"; Reino Unido: "favourite".'),
        ],
      },
      {
        id: 'lesson-first-sentences-a1-11',
        chapter: 11,
        title: 'Passado com was e were',
        description: 'Dizer onde estava e como foi.',
        units: [
          s('I was at home yesterday.', 'Eu estava em casa ontem.', 'Passado de "to be": "was" com I/he/she/it.'),
          s('We were very tired.', 'Nós estávamos muito cansados.', '"Were" com you/we/they.'),
          s('Was it expensive?', 'Foi caro?', 'Pergunta: "was/were" antes do sujeito.'),
          s("The movie wasn't good.", 'O filme não foi bom.', 'Negativa: "wasn\'t" (was not).'),
          s('Where were you last night?', 'Onde você estava ontem à noite?', '"Last night" = ontem à noite.'),
          s('It was a great trip.', 'Foi uma viagem ótima.', '"It was" para avaliar algo que passou.'),
          s("They weren't at the party.", 'Eles não estavam na festa.', '"Weren\'t" = were not.'),
          s('How was your weekend?', 'Como foi seu fim de semana?', 'Pergunta clássica de segunda-feira.'),
          s('There were many people.', 'Tinha muita gente.', 'Passado de "there are": "there were".'),
          s('I was born in Brazil.', 'Eu nasci no Brasil.', '"Be born" é passivo: sempre "I was born", nunca "I born".'),
        ],
      },
      {
        id: 'lesson-first-sentences-a1-12',
        chapter: 12,
        title: 'Revisão: primeiras conversas',
        description: 'Uma frase de cada estrutura do curso.',
        units: [
          s("Hi, I'm Ana. I'm from Brazil.", 'Oi, eu sou a Ana. Sou do Brasil.', 'Revisão de "to be": apresentação completa em duas frases.'),
          s('Are you a student?', 'Você é estudante?', 'Revisão de pergunta com "to be".'),
          s("I'm not busy now.", 'Não estou ocupado agora.', 'Revisão da negativa com "to be".'),
          s('Is there a bus stop near here?', 'Tem ponto de ônibus aqui perto?', 'Revisão de "there is".'),
          s('This is my wife, Julia.', 'Esta é minha esposa, Julia.', 'Revisão de possessivos e "this is" para apresentar.'),
          s('She works from home.', 'Ela trabalha de casa.', 'Revisão do "-s" de he/she/it.'),
          s("Do you have a pen? I don't have one.", 'Você tem caneta? Eu não tenho.', 'Revisão de "do" em pergunta e "don\'t" na negativa. "One" evita repetir "pen".'),
          s('Can you repeat that, please?', 'Pode repetir, por favor?', 'Revisão de "can" para pedidos: frase essencial para quem está aprendendo.'),
          s('I like walking in the park.', 'Gosto de caminhar no parque.', 'Revisão de "like" + "-ing".'),
          s('It was nice to meet you.', 'Foi um prazer te conhecer.', 'Revisão de "was": despedida depois de conhecer alguém.'),
        ],
      },
    ],
  },
];
