// Lote fundamentos-1: primeiro capítulo dos cursos da trilha Fundamentos
// (frases do zero, 1000 palavras essenciais, verbos essenciais). Conteúdo
// original. Palavras novas deste lote entram em LEXICON (somadas ao léxico base).

export const LEXICON = {
  am: ['auxiliary verb', '/æm/', 'sou, estou'],
  from: ['preposition', '/frʌm/', 'de (origem)'],
  brazil: ['proper noun', '/brəˈzɪl/', 'Brasil'],
  name: ['noun', '/neɪm/', 'nome'],
  student: ['noun', '/ˈstuːdənt/', 'estudante'],
  he: ['pronoun', '/hiː/', 'ele'],
  she: ['pronoun', '/ʃiː/', 'ela'],
  "he's": ['pronoun', '/hiːz/', 'ele é, ele está'],
  "she's": ['pronoun', '/ʃiːz/', 'ela é, ela está'],
  friend: ['noun', '/frɛnd/', 'amigo, amiga'],
  they: ['pronoun', '/ðeɪ/', 'eles, elas'],
  "they're": ['pronoun', '/ðɛr/', 'eles são, eles estão'],
  brothers: ['noun', '/ˈbrʌðərz/', 'irmãos'],
  happy: ['adjective', '/ˈhæpi/', 'feliz'],
  tired: ['adjective', '/ˈtaɪərd/', 'cansado'],
  "we're": ['pronoun', '/wɪr/', 'nós estamos'],
  home: ['noun', '/hoʊm/', 'casa, lar'],
  old: ['adjective', '/oʊld/', 'velho; de idade'],
  years: ['noun', '/jɪrz/', 'anos'],
  thirty: ['numeral', '/ˈθɜːrti/', 'trinta'],
  nice: ['adjective', '/naɪs/', 'prazer; legal'],
  meet: ['verb', '/miːt/', 'conhecer, encontrar'],
  // 1000 palavras — pessoas e família
  mother: ['noun', '/ˈmʌðər/', 'mãe'],
  father: ['noun', '/ˈfɑːðər/', 'pai'],
  brother: ['noun', '/ˈbrʌðər/', 'irmão'],
  sister: ['noun', '/ˈsɪstər/', 'irmã'],
  son: ['noun', '/sʌn/', 'filho'],
  daughter: ['noun', '/ˈdɔːtər/', 'filha'],
  husband: ['noun', '/ˈhʌzbənd/', 'marido'],
  wife: ['noun', '/waɪf/', 'esposa'],
  child: ['noun', '/tʃaɪld/', 'criança, filho'],
  children: ['noun', '/ˈtʃɪldrən/', 'crianças, filhos'],
  baby: ['noun', '/ˈbeɪbi/', 'bebê'],
  parents: ['noun', '/ˈpɛrənts/', 'pais (pai e mãe)'],
  grandmother: ['noun', '/ˈɡrænmʌðər/', 'avó'],
  grandfather: ['noun', '/ˈɡrænfɑːðər/', 'avô'],
  uncle: ['noun', '/ˈʌŋkəl/', 'tio'],
  aunt: ['noun', '/ænt/', 'tia'],
  cousin: ['noun', '/ˈkʌzən/', 'primo, prima'],
  family: ['noun', '/ˈfæməli/', 'família'],
  man: ['noun', '/mæn/', 'homem'],
  woman: ['noun', '/ˈwʊmən/', 'mulher'],
  // verbos essenciais (formas)
  went: ['verb', '/wɛnt/', 'foi (passado de go)'],
  gone: ['verb', '/ɡɔːn/', 'ido (particípio de go)'],
  go: ['verb', '/ɡoʊ/', 'ir'],
  had: ['verb', '/hæd/', 'teve, tinha'],
  did: ['verb', '/dɪd/', 'fez'],
  made: ['verb', '/meɪd/', 'fez, feito'],
  got: ['verb', '/ɡɑːt/', 'conseguiu, pegou'],
  gotten: ['verb', '/ˈɡɑːtən/', 'conseguido'],
  said: ['verb', '/sɛd/', 'disse, dito'],
  say: ['verb', '/seɪ/', 'dizer'],
  saw: ['verb', '/sɔː/', 'viu'],
  seen: ['verb', '/siːn/', 'visto'],
  came: ['verb', '/keɪm/', 'veio'],
  come: ['verb', '/kʌm/', 'vir; vindo'],
  took: ['verb', '/tʊk/', 'pegou, levou'],
  taken: ['verb', '/ˈteɪkən/', 'pegado, levado'],
  knew: ['verb', '/nuː/', 'sabia, conheceu'],
  known: ['verb', '/noʊn/', 'sabido, conhecido'],
  thought: ['verb', '/θɔːt/', 'pensou, pensado'],
  been: ['verb', '/bɪn/', 'sido, estado'],
};

export const COURSES = [
  {
    id: 'course-first-sentences-a1',
    slug: 'first-sentences-a1',
    title: 'Primeiras Frases',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 1,
    order: 10,
    short: 'Do zero às primeiras frases: apresentar-se, falar de quem é quem e como está.',
    long: 'Monte frases completas desde a primeira aula com o verbo "to be", pronomes e as expressões que você usa ao se apresentar.',
    lessons: [
      {
        id: 'lesson-first-sentences-a1-01',
        chapter: 1,
        title: 'Eu sou, você é',
        description: 'Apresentar-se e dizer de onde é, com o verbo "to be".',
        units: [
          ["I'm a student.", 'Eu sou estudante.', 'Em inglês a profissão vem com "a/an".', [["I'm", 'subject'], ['a student.', 'predicate_adj']]],
          ["I'm from Brazil.", 'Eu sou do Brasil.', '"From" indica origem.', [["I'm", 'subject'], ['from Brazil.', 'adverbial']]],
          ["What's your name?", 'Qual é o seu nome?', 'Pergunta básica de apresentação.', [["What's", 'predicate_verb'], ['your name?', 'subject']]],
          ['Nice to meet you.', 'Prazer em te conhecer.', 'Resposta natural ao ser apresentado.', [['Nice', 'predicate_adj'], ['to meet you.', 'predicate_verb']]],
          ["She's my friend.", 'Ela é minha amiga.', '"Friend" serve para amigo e amiga.', [["She's", 'subject'], ['my friend.', 'predicate_adj']]],
          ["He's my brother.", 'Ele é meu irmão.', 'Contração de "he is".', [["He's", 'subject'], ['my brother.', 'predicate_adj']]],
          ["They're my brothers.", 'Eles são meus irmãos.', '"They\'re" = "they are".', [["They're", 'subject'], ['my brothers.', 'predicate_adj']]],
          ["We're at home.", 'Nós estamos em casa.', '"At home" = em casa.', [["We're", 'subject'], ['at home.', 'adverbial']]],
          ["I'm thirty years old.", 'Eu tenho trinta anos.', 'Idade usa "to be": "I am thirty".', [["I'm", 'subject'], ['thirty years old.', 'predicate_adj']]],
          ['Are you tired?', 'Você está cansado?', 'Pergunta com "to be": o verbo vem antes.', [['Are', 'predicate_verb'], ['you', 'subject'], ['tired?', 'predicate_adj']]],
        ],
      },
    ],
  },
  {
    id: 'course-1000-words-a1',
    slug: '1000-essential-words',
    title: '1000 Palavras Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 2,
    order: 11,
    short: 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.',
    long: 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.',
    lessons: [
      {
        id: 'lesson-1000-words-a1-01',
        chapter: 1,
        title: 'Pessoas e família',
        description: 'Quem é quem na família e nas pessoas ao seu redor.',
        units: [
          { kind: 'word', text: 'mother', pt: 'mãe', example: ['My mother is a teacher.', 'Minha mãe é professora.'] },
          { kind: 'word', text: 'father', pt: 'pai', example: ['My father works at home.', 'Meu pai trabalha em casa.'] },
          { kind: 'word', text: 'brother', pt: 'irmão', example: ['I have one brother.', 'Eu tenho um irmão.'] },
          { kind: 'word', text: 'sister', pt: 'irmã', example: ['My sister lives in Rio.', 'Minha irmã mora no Rio.'] },
          { kind: 'word', text: 'son', pt: 'filho', example: ['Their son is five.', 'O filho deles tem cinco anos.'] },
          { kind: 'word', text: 'daughter', pt: 'filha', example: ['She has a daughter.', 'Ela tem uma filha.'] },
          { kind: 'word', text: 'husband', pt: 'marido', example: ['Her husband is from Chile.', 'O marido dela é do Chile.'] },
          { kind: 'word', text: 'wife', pt: 'esposa', example: ['His wife is a doctor.', 'A esposa dele é médica.'] },
          { kind: 'word', text: 'child', pt: 'criança', example: ['Every child needs sleep.', 'Toda criança precisa dormir.'] },
          { kind: 'word', text: 'children', pt: 'crianças, filhos', note: 'Plural irregular de "child".', example: ['The children are at school.', 'As crianças estão na escola.'] },
          { kind: 'word', text: 'baby', pt: 'bebê', example: ['The baby is sleeping.', 'O bebê está dormindo.'] },
          { kind: 'word', text: 'parents', pt: 'pais (pai e mãe)', note: '"Parents" não é "parentes" (relatives).', example: ['My parents live near me.', 'Meus pais moram perto de mim.'] },
          { kind: 'word', text: 'grandmother', pt: 'avó', example: ['My grandmother is ninety.', 'Minha avó tem noventa anos.'] },
          { kind: 'word', text: 'grandfather', pt: 'avô', example: ['My grandfather loves soccer.', 'Meu avô adora futebol.'] },
          { kind: 'word', text: 'uncle', pt: 'tio', example: ['My uncle has a big dog.', 'Meu tio tem um cachorro grande.'] },
          { kind: 'word', text: 'aunt', pt: 'tia', example: ['My aunt makes great cakes.', 'Minha tia faz bolos ótimos.'] },
          { kind: 'word', text: 'cousin', pt: 'primo, prima', example: ['My cousin is my best friend.', 'Meu primo é meu melhor amigo.'] },
          { kind: 'word', text: 'family', pt: 'família', example: ['I have a big family.', 'Eu tenho uma família grande.'] },
          { kind: 'word', text: 'man', pt: 'homem', example: ['That man is my neighbor.', 'Aquele homem é meu vizinho.'] },
          { kind: 'word', text: 'woman', pt: 'mulher', note: 'Plural: "women".', example: ['The woman at the door is my aunt.', 'A mulher na porta é minha tia.'] },
        ],
      },
    ],
  },
  {
    id: 'course-essential-verbs-a1',
    slug: 'essential-verbs',
    title: 'Verbos Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 3,
    order: 12,
    short: 'Os 100 verbos mais usados: base, passado e particípio, sempre com uma frase de exemplo.',
    long: 'Aprenda as três formas dos verbos mais importantes do inglês, incluindo os irregulares, ouvindo e escrevendo cada forma.',
    lessons: [
      {
        id: 'lesson-essential-verbs-a1-01',
        chapter: 1,
        title: 'Os 10 verbos mais usados',
        description: 'be, have, do, say, go, get, make, know, think, take.',
        units: [
          { kind: 'verb_forms', text: 'be was been', pt: 'ser, estar', note: 'Passado: "was" (I/he/she/it) e "were" (you/we/they).', example: ['I was tired yesterday.', 'Eu estava cansado ontem.'] },
          { kind: 'verb_forms', text: 'have had had', pt: 'ter', example: ['We had a great time.', 'A gente se divertiu muito.'] },
          { kind: 'verb_forms', text: 'do did done', pt: 'fazer', example: ['Did you do your homework?', 'Você fez sua lição?'] },
          { kind: 'verb_forms', text: 'say said said', pt: 'dizer', example: ['She said yes.', 'Ela disse sim.'] },
          { kind: 'verb_forms', text: 'go went gone', pt: 'ir', example: ['They went home early.', 'Eles foram para casa cedo.'] },
          { kind: 'verb_forms', text: 'get got gotten', pt: 'conseguir, pegar, ficar', note: 'No inglês britânico o particípio é "got".', example: ['I got a new job.', 'Eu consegui um emprego novo.'] },
          { kind: 'verb_forms', text: 'make made made', pt: 'fazer (criar)', example: ['She made a cake.', 'Ela fez um bolo.'] },
          { kind: 'verb_forms', text: 'know knew known', pt: 'saber, conhecer', example: ['I knew the answer.', 'Eu sabia a resposta.'] },
          { kind: 'verb_forms', text: 'think thought thought', pt: 'pensar, achar', example: ['I thought you were at work.', 'Achei que você estava no trabalho.'] },
          { kind: 'verb_forms', text: 'take took taken', pt: 'pegar, levar', example: ['He took the bus.', 'Ele pegou o ônibus.'] },
        ],
      },
    ],
  },
];
