// Lote gramatica-b2-1: curso novo "Gramática B2 em Uso" (B2, trilha Gramática), capítulos 1–8:
// wish/if only, condicionais mistos, causativo, orações relativas, gerúndio × infinitivo,
// ênfase, inversão e futuro perfeito/contínuo. Não repete o B1 ("Tempos Verbais" já cobre
// condicionais 0–3, passiva, discurso indireto e dedução). Conteúdo original.

export const LEXICON = {
  acts: ["verb", "/ækts/", "age, se comporta"],
  adding: ["verb", "/ˈædɪŋ/", "acrescentando"],
  avoids: ["verb", "/əˈvɔɪdz/", "evita"],
  champions: ["noun", "/ˈtʃæmpiənz/", "campeões"],
  circumstances: ["noun", "/ˈsɜːrkəmstænsɪz/", "circunstâncias"],
  eating: ["verb", "/ˈiːtɪŋ/", "comendo"],
  ended: ["verb", "/ˈɛndɪd/", "terminou"],
  fixed: ["verb", "/fɪkst/", "consertado"],
  fluent: ["adjective", "/ˈfluːənt/", "fluente"],
  flying: ["verb", "/ˈflaɪɪŋ/", "voando"],
  hardly: ["adverb", "/ˈhɑːrdli/", "mal, quase não"],
  hoping: ["verb", "/ˈhoʊpɪŋ/", "esperando, torcendo"],
  lasted: ["verb", "/ˈlæstɪd/", "durou"],
  locking: ["verb", "/ˈlɑːkɪŋ/", "trancando"],
  mark: ["noun", "/mɑːrk/", "Mark (nome próprio)"],
  nails: ["noun", "/neɪlz/", "unhas"],
  owned: ["verb", "/oʊnd/", "fosse dono de"],
  practiced: ["verb", "/ˈpræktɪst/", "praticado"],
  rang: ["verb", "/ræŋ/", "tocou (telefone)"],
  richer: ["adjective", "/ˈrɪtʃər/", "mais rico"],
  sooner: ["adverb", "/ˈsuːnər/", "mais cedo"],
  standing: ["verb", "/ˈstændɪŋ/", "em pé"],
  such: ["determiner", "/sʌtʃ/", "tal, tão"],
  surprise: ["noun", "/sərˈpraɪz/", "surpresa"],
  taller: ["adjective", "/ˈtɔːlər/", "mais alto"],
  telling: ["verb", "/ˈtɛlɪŋ/", "contando"],
  wishes: ["verb", "/ˈwɪʃɪz/", "deseja"],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-grammar-b2-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-grammar-b2',
    slug: 'grammar-in-use-b2',
    title: 'Gramática B2 em Uso',
    level: 'B2',
    category: 'grammar',
    track: 'gramatica',
    trackOrder: 1,
    order: 20,
    short: 'Wish, condicionais mistos, causativo, relativas, gerúndio × infinitivo, ênfase, inversão e futuro perfeito.',
    long: 'Os pontos de gramática que separam o inglês intermediário do avançado, sempre em frases curtas e naturais. Cada nota mostra a regra naquela frase e compara com o português, sem repetir o que o curso de Tempos Verbais do B1 já ensinou.',
    lessons: [
      lesson(1, 'Wish e if only', 'Desejos irreais sobre o presente, o passado e o comportamento dos outros.', [
        s('I wish I had more time.', 'Queria ter mais tempo.', '"Wish" + passado simples = desejo sobre o presente que não é real.'),
        s('I wish I lived closer to the beach.', 'Queria morar mais perto da praia.', 'O verbo vai ao passado (lived), mas o assunto é agora.'),
        s('If only I knew the answer.', 'Se ao menos eu soubesse a resposta.', '"If only" é um "wish" mais forte e mais emotivo.'),
        s('I wish I had studied harder.', 'Queria ter estudado mais.', '"Wish" + past perfect = arrependimento sobre o passado.'),
        s('She wishes she had never told him.', 'Ela queria nunca ter contado a ele.', 'Com "she", "wishes" leva s; a segunda parte segue no past perfect.'),
        s('If only we had left earlier.', 'Se ao menos a gente tivesse saído mais cedo.', '"If only" + past perfect = lamento por algo que já passou.'),
        s('I wish it would stop raining.', 'Queria que parasse de chover.', '"Wish" + would = reclamar do que incomoda e desejar que mude.'),
        s('I wish you would listen to me.', 'Queria que você me ouvisse.', '"Wish + would" pede mudança de comportamento do outro; não se usa com "I".'),
        s('I wish I were taller.', 'Queria ser mais alto.', 'Depois de "wish", "were" vale para todas as pessoas; "was" aparece na fala informal.'),
        s('He acts as if he owned the place.', 'Ele age como se fosse o dono do lugar.', '"As if" + passado simples = situação irreal no presente.'),
      ]),
      lesson(2, 'Condicionais mistos', 'Misturar passado e presente na mesma condição.', [
        s('If I had saved more, I would be richer now.', 'Se eu tivesse economizado mais, seria mais rico agora.', 'Misto: past perfect no "if" e would + verbo no resultado, que é o presente.'),
        s('If she had taken the job, she would live in Paris now.', 'Se ela tivesse aceitado o emprego, moraria em Paris agora.', 'Uma escolha do passado que ainda muda a vida de hoje.'),
        s('If I were you, I would have called him.', 'Se eu fosse você, teria ligado para ele.', 'Misto invertido: presente no "if" e passado no resultado.'),
        s('If he were more careful, he would not have lost his keys.', 'Se ele fosse mais cuidadoso, não teria perdido as chaves.', 'Uma característica de hoje explica o que aconteceu.'),
        s('If we had booked earlier, we would not be standing in this line.', 'Se tivéssemos reservado antes, não estaríamos nesta fila.', '"Would not be" + ing descreve a situação de agora.'),
        s('If you had listened, you would know what to do.', 'Se você tivesse ouvido, saberia o que fazer.', 'O resultado é no presente porque a atitude do passado não aconteceu.'),
        s('I would be fluent by now if I had practiced every day.', 'Eu já estaria fluente se tivesse praticado todo dia.', 'A ordem das partes pode inverter; o sentido é o mesmo.'),
        s("If I weren't so tired, I would have gone to the party.", 'Se eu não estivesse tão cansado, teria ido à festa.', '"Weren\'t" com "I" é a forma de "if" irreal.'),
        s('If they had won, they would be champions today.', 'Se eles tivessem ganhado, seriam campeões hoje.', 'Past perfect no "if" e would + verbo no resultado.'),
        s('We would still be friends if she had not moved away.', 'Ainda seríamos amigos se ela não tivesse se mudado.', '"Still" reforça que a situação continuaria até hoje.'),
      ]),
      lesson(3, 'Causativo: have e get', 'Mandar fazer, fazer alguém fazer e deixar algo em certo estado.', [
        s('I had my car repaired yesterday.', 'Mandei consertar meu carro ontem.', '"Have + objeto + particípio" = mandar fazer; quem faz o serviço não aparece.'),
        s('She is having her hair cut tomorrow.', 'Ela vai cortar o cabelo amanhã.', 'No contínuo, o futuro é marcado por "tomorrow"; alguém corta, não ela.'),
        s('We need to get the roof fixed.', 'Precisamos mandar arrumar o telhado.', '"Get + objeto + particípio" é mais informal que "have".'),
        s('He had his phone stolen on the train.', 'Roubaram o celular dele no trem.', 'O causativo também mostra algo ruim que acontece sem querer.'),
        s('I will have the report ready by Friday.', 'Vou deixar o relatório pronto até sexta.', '"Have + objeto + adjetivo" = deixar em certo estado.'),
        s('She had the waiter bring another menu.', 'Ela pediu para o garçom trazer outro cardápio.', '"Have + pessoa + verbo simples", sem "to" = fazer alguém fazer.'),
        s('I got my brother to help me move.', 'Convenci meu irmão a me ajudar na mudança.', '"Get + pessoa + to + verbo" = convencer alguém a fazer.'),
        s('Where do you get your nails done?', 'Onde você faz as unhas?', 'Pergunta comum: a pessoa paga por um serviço.'),
        s('They had the whole kitchen painted.', 'Eles mandaram pintar a cozinha inteira.', 'O particípio descreve o que aconteceu com o objeto, não quem pintou.'),
        s('Have you had your eyes checked lately?', 'Você fez um exame de vista ultimamente?', 'Present perfect + causativo: o segundo "had" é o particípio de "have".'),
      ]),
      lesson(4, 'Orações relativas', 'Who, which, that, whose, where e when em frases mais longas.', [
        s('The man who lives next door is a doctor.', 'O homem que mora ao lado é médico.', '"Who" se refere a pessoa e aqui é o sujeito da oração.'),
        s('This is the book that I told you about.', 'Este é o livro de que te falei.', '"That" pode sumir quando é objeto: "the book I told you about".'),
        s('The woman whose car was stolen called the police.', 'A mulher cujo carro foi roubado chamou a polícia.', '"Whose" = cujo; liga a posse sem usar artigo depois.'),
        s('That is the restaurant where we first met.', 'Aquele é o restaurante onde nos conhecemos.', '"Where" substitui "in which" quando se fala de lugar.'),
        s('My brother, who lives in Canada, is visiting us.', 'Meu irmão, que mora no Canadá, vem nos visitar.', 'Entre vírgulas, é informação extra: "that" não vale nesse caso.'),
        s('She is the person I was telling you about.', 'Ela é a pessoa de quem eu estava falando.', 'Pronome omitido; na fala natural a preposição fica no fim.'),
        s('I remember the day when we moved here.', 'Lembro do dia em que nos mudamos para cá.', '"When" depois de substantivo de tempo.'),
        s('Everything that he said was true.', 'Tudo o que ele disse era verdade.', 'Depois de "everything", "all" e "something" usa-se "that", não "what".'),
        s('The meeting, which lasted three hours, ended late.', 'A reunião, que durou três horas, terminou tarde.', '"Which" com vírgulas para coisas: acrescenta um dado.'),
        s('People who work from home save time.', 'Pessoas que trabalham em casa economizam tempo.', 'Sem vírgulas, define de quais pessoas se fala.'),
      ]),
      lesson(5, 'Gerúndio × infinitivo', 'Verbos que mudam de sentido conforme o que vem depois.', [
        s('I enjoy cooking for my friends.', 'Gosto de cozinhar para meus amigos.', '"Enjoy" é seguido de verbo com -ing.'),
        s('She decided to quit her job.', 'Ela decidiu largar o emprego.', '"Decide" pede infinitivo com "to".'),
        s('He avoids eating late at night.', 'Ele evita comer tarde da noite.', '"Avoid" também pede -ing.'),
        s('We hope to see you again soon.', 'Esperamos ver você de novo em breve.', '"Hope" pede infinitivo com "to".'),
        s('I stopped smoking two years ago.', 'Parei de fumar há dois anos.', '"Stop" + -ing = parar de fazer.'),
        s('I stopped to buy some water.', 'Parei para comprar água.', '"Stop" + to = parar uma coisa para fazer outra.'),
        s('I remember locking the door.', 'Lembro de ter trancado a porta.', '"Remember" + -ing = lembrar de algo que já foi feito.'),
        s('Remember to lock the door.', 'Lembre de trancar a porta.', '"Remember" + to = não esquecer de fazer.'),
        s('She tried to open the window, but it was stuck.', 'Ela tentou abrir a janela, mas estava emperrada.', '"Try" + to = tentar, fazer esforço.'),
        s('Try adding a little salt.', 'Experimente colocar um pouco de sal.', '"Try" + -ing = experimentar para ver o resultado.'),
      ]),
      lesson(6, 'Ênfase', 'Destacar quem, o quê e o que importa na frase.', [
        s('It was Mark who broke the window.', 'Foi o Mark que quebrou a janela.', '"It was ... who" destaca o sujeito.'),
        s('It is the price that worries me.', 'É o preço que me preocupa.', 'Estrutura de destaque com "that".'),
        s('What I need is a long vacation.', 'O que eu preciso é de umas férias longas.', '"What I need is" destaca o objeto da frase.'),
        s('What surprised me was her honesty.', 'O que me surpreendeu foi a honestidade dela.', '"What" faz o papel de sujeito da oração destacada.'),
        s('All I want is a quiet evening.', 'Tudo o que eu quero é uma noite tranquila.', '"All" com o sentido de "a única coisa".'),
        s('I did call you, but you did not answer.', 'Eu liguei sim, mas você não atendeu.', '"Did" antes do verbo reforça a afirmação.'),
        s('She does love her job.', 'Ela adora mesmo o trabalho dela.', '"Does" + verbo base reforça; o verbo não leva s.'),
        s('It was not until midnight that we got home.', 'Só à meia-noite chegamos em casa.', '"Not until" no início dá destaque ao momento.'),
        s('The thing that I like most is the food.', 'O que eu mais gosto é da comida.', '"The thing that" = alternativa a "what".'),
        s('It is exactly what I was hoping for.', 'É exatamente o que eu esperava.', '"Exactly" reforça a ideia de coincidência.'),
      ]),
      lesson(7, 'Inversão', 'Advérbios negativos no início da frase pedem auxiliar antes do sujeito.', [
        s('Never have I seen such a mess.', 'Nunca vi uma bagunça assim.', 'Advérbio negativo no início exige auxiliar + sujeito.'),
        s('Rarely does he complain about anything.', 'Raramente ele reclama de qualquer coisa.', '"Rarely" + does he; o verbo volta à forma base.'),
        s('Not only did she win, but she also broke the record.', 'Ela não só ganhou como também quebrou o recorde.', '"Not only" no início inverte a primeira parte.'),
        s('Hardly had we arrived when it started to rain.', 'Mal tínhamos chegado quando começou a chover.', '"Hardly" + past perfect invertido, ligado por "when".'),
        s('Under no circumstances should you open this door.', 'Em hipótese alguma você deve abrir esta porta.', 'Expressões negativas no início invertem com "should".'),
        s('Only then did I understand the problem.', 'Só então entendi o problema.', '"Only then" também inverte.'),
        s('Little did they know about the surprise.', 'Eles nem imaginavam a surpresa.', '"Little did" = não sabiam nada; estilo formal ou de narrativa.'),
        s('Had I known, I would have helped.', 'Se eu soubesse, teria ajudado.', 'Inversão sem "if" na terceira condicional; tom formal.'),
        s('Should you need anything, please call me.', 'Se precisar de algo, me ligue.', '"Should" invertido = "if you should"; formal e muito usado em e-mails.'),
        s('No sooner had he sat down than the phone rang.', 'Mal ele sentou e o telefone tocou.', '"No sooner ... than" liga dois acontecimentos em seguida.'),
      ]),
      lesson(8, 'Futuro perfeito e contínuo', 'Algo concluído ou em andamento num ponto do futuro.', [
        s('By next year, I will have finished my degree.', 'Até o ano que vem, terei terminado a faculdade.', 'Future perfect: algo concluído antes de um ponto no futuro.'),
        s('She will have left by the time we arrive.', 'Ela já terá saído quando a gente chegar.', 'Depois de "by the time" vem o presente simples; o verbo principal fica no future perfect.'),
        s('By June, we will have lived here for five years.', 'Em junho, vamos completar cinco anos morando aqui.', 'Future perfect com duração: "for" + período.'),
        s('This time tomorrow, I will be flying to Rome.', 'Amanhã a esta hora, estarei voando para Roma.', 'Future continuous: ação em andamento num momento futuro.'),
        s("Don't call at eight, we will be having dinner.", 'Não ligue às oito, estaremos jantando.', '"Will be" + -ing avisa que a pessoa estará ocupada.'),
        s('Will you be using the car tonight?', 'Você vai usar o carro hoje à noite?', 'Pergunta educada sobre planos, mais suave que "are you going to".'),
        s('By the end of the week, they will have been working on it for a month.', 'Até o fim da semana, eles estarão há um mês trabalhando nisso.', 'Future perfect continuous: duração acumulada até um ponto futuro.'),
        s('I will have been waiting for an hour by then.', 'Eu já estarei esperando há uma hora até lá.', 'Mesma forma, com foco na espera que continua.'),
        s('He will probably have forgotten about it by tomorrow.', 'Ele provavelmente já terá esquecido isso até amanhã.', 'O advérbio fica entre "will" e "have".'),
        s('We will not have finished before noon.', 'Não teremos terminado antes do meio-dia.', 'Negativa: "will not have" + particípio.'),
      ]),
    ],
  },
];
