// Lote historias-1: curso novo "Histórias em Trechos" (B1, trilha Fluência).
// Dez contos curtos e originais, cada um dividido em oito trechos para ouvir e
// escrever em sequência. A nota de cada trecho aponta a estrutura ou expressão
// que vale aprender. Conteúdo original.

export const LEXICON = {
  leo: ["proper noun", "/ˈliːoʊ/", "Leo"],
  lucas: ["proper noun", "/ˈluːkəs/", "Lucas"],
  maya: ["proper noun", "/ˈmaɪə/", "Maya"],
  pedro: ["proper noun", "/ˈpeɪdroʊ/", "Pedro"],
  sara: ["proper noun", "/ˈsɛrə/", "Sara"],
  suddenly: ["adverb", "/ˈsʌdənli/", "de repente"],
  tokyo: ["proper noun", "/ˈtoʊkioʊ/", "Tóquio"],
  tom: ["proper noun", "/tɑːm/", "Tom"],
  apologized: ["verb", "/əˈpɑːlədʒaɪzd/", "pediu desculpas"],
  asking: ["verb", "/ˈæskɪŋ/", "pedindo, perguntando"],
  attic: ["noun", "/ˈætɪk/", "sótão"],
  baked: ["verb", "/beɪkt/", "assou"],
  barely: ["adverb", "/ˈbɛrli/", "mal, quase não"],
  belonged: ["verb", "/bɪˈlɔːŋd/", "pertencia"],
  candle: ["noun", "/ˈkændəl/", "vela"],
  cared: ["verb", "/kɛrd/", "se importou"],
  choice: ["noun", "/tʃɔɪs/", "escolha"],
  covered: ["verb", "/ˈkʌvərd/", "cobriu"],
  dated: ["adjective", "/ˈdeɪtɪd/", "datado"],
  decided: ["verb", "/dɪˈsaɪdɪd/", "decidiu"],
  deer: ["noun", "/dɪr/", "cervo"],
  direction: ["noun", "/dəˈrɛkʃən/", "direção"],
  familiar: ["adjective", "/fəˈmɪljər/", "familiar"],
  fancy: ["adjective", "/ˈfænsi/", "chique"],
  "friend's": ["noun", "/frɛndz/", "do amigo"],
  gestures: ["noun", "/ˈdʒɛstʃərz/", "gestos"],
  giving: ["verb", "/ˈɡɪvɪŋ/", "dando"],
  including: ["preposition", "/ɪnˈkluːdɪŋ/", "incluindo"],
  interviewer: ["noun", "/ˈɪntərvjuːər/", "entrevistador"],
  knocked: ["verb", "/nɑːkt/", "bateu (na porta)"],
  language: ["noun", "/ˈlæŋɡwɪdʒ/", "língua, idioma"],
  laughed: ["verb", "/læft/", "riu"],
  mailed: ["verb", "/meɪld/", "enviou pelo correio"],
  mistakes: ["noun", "/mɪˈsteɪks/", "erros"],
  "neighbor's": ["noun", "/ˈneɪbərz/", "do vizinho"],
  note: ["noun", "/noʊt/", "bilhete, nota"],
  noticed: ["verb", "/ˈnoʊtɪst/", "notou"],
  path: ["noun", "/pæθ/", "trilha, caminho"],
  planned: ["verb", "/plænd/", "planejou"],
  politely: ["adverb", "/pəˈlaɪtli/", "educadamente"],
  practicing: ["verb", "/ˈpræktɪsɪŋ/", "praticando"],
  pulling: ["verb", "/ˈpʊlɪŋ/", "puxando, saindo"],
  received: ["verb", "/rɪˈsiːvd/", "recebeu"],
  recipe: ["noun", "/ˈrɛsəpi/", "receita"],
  rocks: ["noun", "/rɑːks/", "pedras"],
  searched: ["verb", "/sɜːrtʃt/", "pesquisou"],
  "sister's": ["noun", "/ˈsɪstərz/", "da irmã"],
  smiled: ["verb", "/smaɪld/", "sorriu"],
  spilled: ["verb", "/spɪld/", "derramou"],
  stain: ["noun", "/steɪn/", "mancha"],
  steep: ["adjective", "/stiːp/", "íngreme"],
  stranger: ["noun", "/ˈstreɪndʒər/", "desconhecido"],
  tasted: ["verb", "/ˈteɪstɪd/", "provou"],
  upstairs: ["adverb", "/ˌʌpˈstɛrz/", "no andar de cima"],
  waved: ["verb", "/weɪvd/", "acenou"],
  woke: ["verb", "/woʊk/", "acordou"],
  words: ["noun", "/wɜːrdz/", "palavras"],
};

const t = (text, pt, note) => ({ kind: 'story', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-stories-b1-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-stories-b1',
    slug: 'short-stories-b1',
    title: 'Histórias em Trechos',
    level: 'B1',
    category: 'stories',
    track: 'fluencia',
    trackOrder: 2,
    order: 17,
    short: 'Dez contos curtos, trecho por trecho: você ouve, escreve e acompanha a história até o fim.',
    long: 'Cada capítulo é um conto original dividido em oito trechos. Você pratica compreensão de uma narrativa contínua, tempos do passado, conectores e diálogo. A nota de cada trecho explica a estrutura ou a expressão usada.',
    lessons: [
      lesson(1, 'A chave errada', 'Um recomeço numa cidade nova.', [
        t('Lucas moved to a new city in the middle of winter.', 'Lucas se mudou para uma cidade nova no meio do inverno.', '"Move to" = mudar-se para. "In the middle of" = no meio de.'),
        t('On his first night, he came home late and very tired.', 'Na primeira noite, ele chegou em casa tarde e muito cansado.', '"Come home", sem "to": "came home".'),
        t("He tried his key, but the door wouldn't open.", 'Ele tentou a chave, mas a porta não abria.', '"Wouldn\'t" = recusa de um objeto: a porta "não queria" abrir.'),
        t('He tried again and again. Nothing happened.', 'Tentou de novo e de novo. Nada aconteceu.', '"Again and again" = repetidas vezes.'),
        t('Suddenly, a light came on inside the apartment.', 'De repente, uma luz acendeu dentro do apartamento.', '"Come on" (luz) = acender.'),
        t('An old woman opened the door and looked at him.', 'Uma senhora abriu a porta e olhou para ele.', '"Look at" = olhar para.'),
        t('She smiled and said that he lived upstairs.', 'Ela sorriu e disse que ele morava no andar de cima.', 'Discurso indireto: "you live" vira "he lived". "Upstairs" = no andar de cima.'),
        t('That was how Lucas met his first friend in the city.', 'Foi assim que Lucas conheceu seu primeiro amigo na cidade.', '"That was how" = foi assim que. "Meet" = conhecer (passado: met).'),
      ]),
      lesson(2, 'O último ônibus', 'Uma noite de chuva e uma escolha.', [
        t('It was raining hard when Maya left the office.', 'Chovia forte quando Maya saiu do escritório.', 'Passado contínuo para o cenário: "it was raining".'),
        t('She ran to the bus stop, but the last bus was pulling away.', 'Ela correu até o ponto, mas o último ônibus estava saindo.', '"Pull away" = arrancar, sair (veículo).'),
        t('She waved her arms, but the driver did not see her.', 'Ela acenou com os braços, mas o motorista não a viu.', '"Wave" = acenar.'),
        t('Her phone battery was almost dead.', 'A bateria do celular estava quase no fim.', '"Almost dead" = quase sem bateria.'),
        t('A taxi would cost too much, so she decided to walk.', 'Um táxi custaria caro demais, então ela decidiu andar.', '"Would cost" = hipótese. "Decide to" + verbo.'),
        t('After ten minutes, a car stopped next to her.', 'Depois de dez minutos, um carro parou ao lado dela.', '"Next to" = ao lado de.'),
        t('It was her manager, driving home the same way.', 'Era a gerente dela, voltando para casa pelo mesmo caminho.', '"The same way" = pelo mesmo caminho.'),
        t('She smiled and told Maya to get in.', 'Ela sorriu e disse para Maya entrar.', '"Tell someone to" + verbo = mandar, pedir. "Get in" = entrar no carro.'),
      ]),
      lesson(3, 'O bolo de aniversário', 'Uma surpresa que quase deu errado.', [
        t("Tom wanted to bake a cake for his sister's birthday.", 'Tom queria fazer um bolo para o aniversário da irmã.', '"Bake" = assar. "Sister\'s" = da irmã (posse com \'s).'),
        t('He had never baked anything before.', 'Ele nunca tinha assado nada antes.', 'Past perfect: "had never baked" = antes daquele momento.'),
        t('He followed a recipe he found online.', 'Ele seguiu uma receita que achou na internet.', '"Recipe" = receita. "That" foi omitido: "a recipe (that) he found".'),
        t('But he used salt instead of sugar.', 'Mas usou sal em vez de açúcar.', '"Instead of" = em vez de.'),
        t('When his sister tasted it, she made a funny face.', 'Quando a irmã provou, fez uma careta engraçada.', '"Taste" = provar. "Make a face" = fazer careta.'),
        t('Everyone laughed, including Tom.', 'Todo mundo riu, incluindo o Tom.', '"Including" = incluindo.'),
        t('They ordered a pizza and put a candle on it.', 'Eles pediram uma pizza e colocaram uma vela nela.', '"Order" = pedir (comida).'),
        t('His sister said it was the best birthday ever.', 'A irmã disse que foi o melhor aniversário de todos.', '"Ever" depois do superlativo = de todos os tempos.'),
      ]),
      lesson(4, 'Perdido na estação', 'Um turista, um mapa e um desconhecido.', [
        t('Pedro arrived in Tokyo with a paper map and no internet.', 'Pedro chegou a Tóquio com um mapa de papel e sem internet.', '"Arrive in" + cidade; "arrive at" + lugar específico.'),
        t('The station was huge and full of people.', 'A estação era enorme e cheia de gente.', '"Full of" = cheio de.'),
        t('Every sign seemed to point in a different direction.', 'Cada placa parecia apontar para um lado diferente.', '"Seem to" + verbo = parecer.'),
        t('He stood still, trying to understand the map.', 'Ele ficou parado, tentando entender o mapa.', '"Stand still" = ficar parado. "Trying to" = tentando.'),
        t('A young man asked if he needed help.', 'Um rapaz perguntou se ele precisava de ajuda.', 'Discurso indireto: "asked if he needed".'),
        t('They did not share a language, so they used gestures.', 'Eles não falavam a mesma língua, então usaram gestos.', '"Share a language" = ter uma língua em comum.'),
        t('The man walked with him all the way to the right platform.', 'O rapaz caminhou com ele até a plataforma certa.', '"All the way to" = até, o caminho todo.'),
        t('Pedro never learned his name, but he never forgot him.', 'Pedro nunca soube o nome dele, mas nunca o esqueceu.', '"Learn someone\'s name" = ficar sabendo o nome.'),
      ]),
      lesson(5, 'A entrevista', 'Nervos, café e uma resposta honesta.', [
        t('Ana woke up early on the day of her interview.', 'Ana acordou cedo no dia da entrevista.', '"Wake up", passado "woke up".'),
        t('She was so nervous that she could not eat breakfast.', 'Estava tão nervosa que não conseguiu tomar café.', '"So + adjetivo + that" = tão… que.'),
        t('On the way, she spilled coffee on her shirt.', 'No caminho, derrubou café na camisa.', '"Spill" = derramar. "On the way" = no caminho.'),
        t('There was no time to go back and change.', 'Não havia tempo para voltar e trocar de roupa.', '"Change" sozinho pode significar trocar de roupa.'),
        t('The interviewer noticed the stain and smiled.', 'O entrevistador notou a mancha e sorriu.', '"Notice" = notar. "Stain" = mancha.'),
        t('Ana decided to tell the truth about her morning.', 'Ana decidiu contar a verdade sobre a manhã.', '"Tell the truth" = dizer a verdade.'),
        t('They both laughed, and the rest of the interview felt easy.', 'Os dois riram, e o resto da entrevista pareceu fácil.', '"Feel" + adjetivo = parecer, dar a sensação de.'),
        t('A week later, she got the job.', 'Uma semana depois, ela conseguiu o emprego.', '"A week later" = uma semana depois. "Get the job" = conseguir a vaga.'),
      ]),
      lesson(6, 'O cachorro do vizinho', 'Um visitante inesperado.', [
        t('Every morning, a small brown dog sat outside my door.', 'Toda manhã, um cachorrinho marrom sentava na frente da minha porta.', 'Passado simples para hábito passado: "sat".'),
        t('At first, I did not know who he belonged to.', 'No início, eu não sabia de quem ele era.', '"Belong to" = pertencer a. Preposição no fim da pergunta indireta.'),
        t('I started giving him a little water.', 'Comecei a dar um pouco de água para ele.', '"Start" + -ing = começar a.'),
        t('Soon he was waiting for me every day.', 'Logo ele estava me esperando todo dia.', '"Wait for" = esperar por.'),
        t('One day, he did not come.', 'Um dia, ele não veio.', 'Frase curta para criar tensão na narrativa.'),
        t('I felt worried and knocked on my neighbor\'s door.', 'Fiquei preocupado e bati na porta do vizinho.', '"Knock on" = bater (na porta).'),
        t('She told me the dog was sick, but getting better.', 'Ela me contou que o cachorro estava doente, mas melhorando.', '"Get better" = melhorar.'),
        t('Now we walk him together every Sunday.', 'Agora passeamos com ele juntos todo domingo.', '"Walk a dog" = passear com o cachorro.'),
      ]),
      lesson(7, 'A carta antiga', 'Uma descoberta no sótão.', [
        t('While cleaning the attic, Sara found an old box.', 'Enquanto limpava o sótão, Sara achou uma caixa velha.', '"While" + -ing = enquanto fazia algo.'),
        t('Inside, there was a letter written by her grandfather.', 'Dentro, havia uma carta escrita pelo avô dela.', '"Written by" = particípio como adjetivo.'),
        t('It was dated fifty years ago.', 'Estava datada de cinquenta anos atrás.', '"Ago" = atrás, sempre depois do período.'),
        t('He had written it to a friend he never saw again.', 'Ele tinha escrito para um amigo que nunca mais viu.', 'Past perfect: "had written" antes do resto da história.'),
        t('The letter was never sent.', 'A carta nunca foi enviada.', 'Voz passiva no passado: "was never sent".'),
        t('Sara searched online and found the friend\'s family.', 'Sara pesquisou na internet e achou a família do amigo.', '"Search" = pesquisar.'),
        t('She mailed the letter with a short note of her own.', 'Ela mandou a carta pelo correio com um bilhete dela.', '"Of her own" = dela mesma.'),
        t('A month later, she received a reply full of old photos.', 'Um mês depois, recebeu uma resposta cheia de fotos antigas.', '"Reply" = resposta.'),
      ]),
      lesson(8, 'A trilha', 'Uma caminhada que mudou de plano.', [
        t('We planned to reach the top of the mountain by noon.', 'Planejamos chegar ao topo da montanha até o meio-dia.', '"By" + horário = até, no máximo.'),
        t('The path was steep and full of rocks.', 'A trilha era íngreme e cheia de pedras.', '"Steep" = íngreme.'),
        t('Halfway up, the weather changed quickly.', 'No meio da subida, o tempo mudou rápido.', '"Halfway up" = no meio da subida.'),
        t('Dark clouds covered the sky, and it got cold.', 'Nuvens escuras cobriram o céu, e esfriou.', '"Get cold" = esfriar.'),
        t('We had to make a choice: continue or turn back.', 'Tivemos que escolher: continuar ou voltar.', '"Turn back" = voltar, dar meia-volta.'),
        t('We decided that the top could wait for another day.', 'Decidimos que o topo podia esperar outro dia.', '"Could wait" = podia esperar.'),
        t('On the way down, we saw a family of deer.', 'Na descida, vimos uma família de cervos.', '"Deer" é igual no singular e no plural.'),
        t("It wasn't the trip we planned, but it was a good one.", 'Não foi a viagem que planejamos, mas foi boa.', '"A good one" evita repetir "trip".'),
      ]),
      lesson(9, 'O erro no restaurante', 'Um pedido trocado.', [
        t('Leo invited his parents to a fancy restaurant.', 'Leo convidou os pais para um restaurante chique.', '"Fancy" = chique, sofisticado.'),
        t('He ordered fish, but the waiter brought him soup.', 'Ele pediu peixe, mas o garçom trouxe sopa.', '"Bring", passado "brought".'),
        t('He was too shy to say anything.', 'Estava tímido demais para dizer algo.', '"Too + adjetivo + to" = demais para.'),
        t('His mother saw his face and called the waiter.', 'A mãe viu a cara dele e chamou o garçom.', '"Call the waiter" = chamar o garçom.'),
        t('She politely told him that there had been a mistake.', 'Ela disse educadamente que tinha havido um engano.', 'Discurso indireto: "there has been" vira "there had been". Forma educada de reclamar.'),
        t('The waiter apologized and brought the fish right away.', 'O garçom pediu desculpas e trouxe o peixe na hora.', '"Apologize" = pedir desculpas. "Right away" = imediatamente.'),
        t('He also brought a free dessert for the table.', 'Também trouxe uma sobremesa grátis para a mesa.', '"Free" = grátis.'),
        t('Leo learned that asking politely is not rude.', 'Leo aprendeu que pedir com educação não é falta de educação.', '"Politely" = educadamente. "Rude" = grosseiro.'),
      ]),
      lesson(10, 'Um ano depois', 'Olhando para trás.', [
        t('One year ago, I could barely order a coffee in English.', 'Um ano atrás, eu mal conseguia pedir um café em inglês.', '"Barely" = mal, quase não.'),
        t('I was afraid of making mistakes.', 'Eu tinha medo de errar.', '"Afraid of" + -ing.'),
        t('So I started practicing a little every day.', 'Então comecei a praticar um pouco todo dia.', '"A little every day" = um pouco todo dia.'),
        t('Some days were hard, and I wanted to give up.', 'Alguns dias foram difíceis, e eu quis desistir.', '"Give up" = desistir.'),
        t('But slowly, the words started to feel familiar.', 'Mas, aos poucos, as palavras começaram a soar familiares.', '"Slowly" = aos poucos.'),
        t('Last week, I had a whole conversation with a stranger.', 'Semana passada, tive uma conversa inteira com um desconhecido.', '"Whole" = inteiro. "Stranger" = desconhecido.'),
        t('I made mistakes, and nobody cared.', 'Errei, e ninguém ligou.', '"Nobody cared" = ninguém se importou.'),
        t("I'm still learning, but now I'm not afraid.", 'Ainda estou aprendendo, mas agora não tenho medo.', '"Still" = ainda. Fecha o curso com o presente.'),
      ]),
    ],
  },
];
