// Lote modais-1: curso novo "Verbos Modais" (B1, trilha Gramática), capítulos
// 1–8 (can, could, should, must, might, would, have to, may). Cada nota explica
// o sentido do modal naquela frase e compara com o português. Conteúdo original.

export const LEXICON = {
  passengers: ["noun", "/ˈpæsɪndʒərz/", "passageiros"],
  visitors: ["noun", "/ˈvɪzɪtərz/", "visitantes"],
  able: ["adjective", "/ˈeɪbəl/", "capaz"],
  admit: ["verb", "/ədˈmɪt/", "admitir"],
  dreams: ["noun", "/driːmz/", "sonhos"],
  "mustn't": ["verb", "/ˈmʌsənt/", "não pode (must not)"],
  ought: ["verb", "/ɔːt/", "deveria (ought to)"],
  rather: ["adverb", "/ˈræðər/", "de preferência"],
  seatbelt: ["noun", "/ˈsiːtbɛlt/", "cinto de segurança"],
  "shouldn't": ["verb", "/ˈʃʊdənt/", "não deveria (should not)"],
  uniform: ["noun", "/ˈjuːnɪfɔːrm/", "uniforme"],
  wear: ["verb", "/wɛr/", "usar, vestir"],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-modals-b1-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-modals-b1',
    slug: 'modal-verbs-b1',
    title: 'Verbos Modais',
    level: 'B1',
    category: 'grammar',
    track: 'gramatica',
    trackOrder: 4,
    order: 15,
    short: 'Can, could, should, must, might, would, have to e may: habilidade, permissão, conselho, obrigação e possibilidade.',
    long: 'Um capítulo por modal, com os sentidos que ele tem na fala real: habilidade, permissão, pedido, conselho, obrigação, proibição, possibilidade e hipótese. Modais não levam "to" nem "s" na terceira pessoa; cada frase mostra isso e compara com o português.',
    lessons: [
      lesson(1, 'Can', 'Habilidade, permissão e pedido informal.', [
        s('I can swim.', 'Eu sei nadar.', '"Can" = habilidade. Em português muitas vezes vira "saber".'),
        s('She can speak three languages.', 'Ela fala três idiomas.', 'Sem "s" e sem "to": "she can speak", nunca "she cans" ou "can to speak".'),
        s("I can't hear you.", 'Não estou te ouvindo.', '"Can\'t" com verbos de percepção (hear, see) = não conseguir agora.'),
        s('Can I sit here?', 'Posso sentar aqui?', '"Can I…?" = pedir permissão, informal.'),
        s('Can you help me with this?', 'Pode me ajudar com isso?', '"Can you…?" = pedido informal.'),
        s('You can use my phone.', 'Pode usar meu celular.', '"You can" = dar permissão.'),
        s("You can't park here.", 'Não pode estacionar aqui.', '"Can\'t" = proibição por regra.'),
        s('Can you see the sign?', 'Você consegue ver a placa?', 'Pergunta de capacidade.'),
        s('It can get very cold at night.', 'Pode fazer muito frio à noite.', '"Can" = algo que às vezes acontece.'),
        s('I will be able to help tomorrow.', 'Vou poder ajudar amanhã.', '"Can" não tem futuro: use "will be able to".'),
      ]),
      lesson(2, 'Could', 'Passado de can, pedido educado e possibilidade.', [
        s('I could run fast when I was young.', 'Eu corria rápido quando era jovem.', '"Could" = habilidade no passado.'),
        s("I couldn't sleep last night.", 'Não consegui dormir ontem à noite.', '"Couldn\'t" = não conseguir no passado.'),
        s('Could you open the window?', 'Você poderia abrir a janela?', '"Could you…?" = pedido mais educado que "can you".'),
        s('Could I ask a question?', 'Eu poderia fazer uma pergunta?', 'Permissão formal.'),
        s('It could rain later.', 'Pode chover mais tarde.', '"Could" = possibilidade.'),
        s('We could go to the movies.', 'A gente podia ir ao cinema.', '"We could" = sugestão.'),
        s('You could try again tomorrow.', 'Você podia tentar de novo amanhã.', 'Sugestão suave.'),
        s('I was able to fix it in the end.', 'No fim, consegui consertar.', 'Para um sucesso único no passado, prefira "was able to" a "could".'),
        s('Could you speak up a little?', 'Pode falar um pouco mais alto?', '"Speak up" = falar mais alto.'),
        s('How could you forget?', 'Como você pôde esquecer?', 'Surpresa ou reprovação.'),
      ]),
      lesson(3, 'Should', 'Conselho, expectativa e opinião.', [
        s('You should see a doctor.', 'Você deveria ir ao médico.', '"Should" = conselho.'),
        s("You shouldn't eat so late.", 'Você não deveria comer tão tarde.', 'Negativa: "shouldn\'t" + verbo.'),
        s('What should I do?', 'O que eu devo fazer?', 'Pedir conselho.'),
        s('Should I call her?', 'Devo ligar para ela?', 'Pergunta com inversão: should + sujeito.'),
        s('The package should arrive today.', 'O pacote deve chegar hoje.', '"Should" = expectativa, o normal é que aconteça.'),
        s('It should be easy.', 'Deve ser fácil.', 'Expectativa sobre algo.'),
        s('I think we should leave now.', 'Acho que a gente devia ir embora agora.', '"I think we should" = sugestão com opinião.'),
        s("I don't think you should go.", 'Acho que você não deveria ir.', 'Em inglês a negação fica em "don\'t think", não em "should".'),
        s('You should have told me.', 'Você deveria ter me contado.', '"Should have" + particípio = crítica sobre o passado.'),
        s('You ought to rest.', 'Você devia descansar.', '"Ought to" = "should", um pouco mais formal.'),
      ]),
      lesson(4, 'Must', 'Obrigação forte, proibição e dedução.', [
        s('I must finish this today.', 'Preciso terminar isso hoje.', '"Must" = obrigação que vem de quem fala.'),
        s('You must wear a seatbelt.', 'É obrigatório usar cinto.', 'Regra escrita ou ordem forte.'),
        s("You mustn't smoke here.", 'É proibido fumar aqui.', '"Mustn\'t" = proibido. Não é "não precisa".'),
        s('Passengers must show their tickets.', 'Os passageiros devem mostrar a passagem.', 'Tom de aviso oficial.'),
        s('You must try this cake!', 'Você tem que provar este bolo!', 'Recomendação entusiasmada.'),
        s('She must be at work.', 'Ela deve estar no trabalho.', '"Must" de dedução: quase certeza.'),
        s('You must be tired after the trip.', 'Você deve estar cansado depois da viagem.', 'Dedução gentil.'),
        s('It must have cost a lot.', 'Deve ter custado caro.', '"Must have" + particípio = dedução sobre o passado.'),
        s('I must admit I was wrong.', 'Tenho que admitir que estava errado.', 'Expressão fixa: "I must admit".'),
        s('Must we leave so early?', 'Temos mesmo que sair tão cedo?', 'Pergunta com "must" soa formal; na fala use "do we have to".'),
      ]),
      lesson(5, 'Might', 'Possibilidade e incerteza.', [
        s('I might go to the party.', 'Talvez eu vá à festa.', '"Might" = talvez. Em português usamos "talvez" + subjuntivo.'),
        s('It might rain this afternoon.', 'Pode ser que chova esta tarde.', 'Possibilidade sem certeza.'),
        s("She might not come.", 'Pode ser que ela não venha.', '"Might not" = talvez não.'),
        s('Take an umbrella. You might need it.', 'Leve um guarda-chuva. Talvez você precise.', 'Conselho com possibilidade.'),
        s('He might be sleeping.', 'Ele pode estar dormindo.', 'Might + be + -ing = possibilidade sobre agora.'),
        s('They might have left already.', 'Pode ser que já tenham ido embora.', '"Might have" + particípio = possibilidade no passado.'),
        s('You might want to check that again.', 'Talvez seja bom conferir isso de novo.', '"You might want to" = sugestão educada.'),
        s('I might as well stay home.', 'Então é melhor eu ficar em casa.', '"Might as well" = já que não tem opção melhor.'),
        s('This might be the best pizza in town.', 'Esta talvez seja a melhor pizza da cidade.', 'Opinião cautelosa.'),
        s('Might I suggest something?', 'Posso sugerir algo?', '"Might I" é muito formal, quase antiquado.'),
      ]),
      lesson(6, 'Would', 'Pedidos, ofertas, hipóteses e hábitos passados.', [
        s('Would you like some coffee?', 'Você aceita um café?', '"Would you like" = oferecer com educação.'),
        s("I'd like a glass of water.", 'Eu queria um copo de água.', '"I\'d like" = "I would like", pedido educado. Mais gentil que "I want".'),
        s('Would you mind waiting?', 'Você se importa de esperar?', '"Would you mind" + -ing = pedido muito educado.'),
        s('I would help you, but I am busy.', 'Eu te ajudaria, mas estou ocupado.', 'Hipótese: o que faria em outra situação.'),
        s('What would you do?', 'O que você faria?', 'Pergunta hipotética.'),
        s("I'd rather stay here.", 'Prefiro ficar aqui.', '"I\'d rather" + verbo = preferência.'),
        s('When I was a kid, we would play outside all day.', 'Quando eu era criança, a gente brincava lá fora o dia todo.', '"Would" = hábito no passado, como o imperfeito ("brincava").'),
        s('He said he would call.', 'Ele disse que ia ligar.', '"Would" no discurso indireto de "will".'),
        s("She wouldn't listen.", 'Ela não quis ouvir.', '"Wouldn\'t" = recusou-se.'),
        s('It would be great to see you.', 'Seria ótimo te ver.', '"It would be" = seria.'),
      ]),
      lesson(7, 'Have to', 'Obrigação externa e falta de necessidade.', [
        s('I have to work tomorrow.', 'Tenho que trabalhar amanhã.', '"Have to" = obrigação que vem de fora (regra, chefe).'),
        s('She has to wear a uniform.', 'Ela tem que usar uniforme.', 'Terceira pessoa: "has to".'),
        s("You don't have to come.", 'Você não precisa vir.', '"Don\'t have to" = não é necessário. Muito diferente de "mustn\'t".'),
        s('Do I have to pay now?', 'Tenho que pagar agora?', 'Pergunta com "do".'),
        s('We had to wait an hour.', 'Tivemos que esperar uma hora.', 'Passado de "must" e "have to": "had to".'),
        s('I will have to leave early.', 'Vou ter que sair cedo.', 'Futuro: "will have to".'),
        s("I've got to go.", 'Tenho que ir.', '"Have got to" = "have to", informal. Na fala: "I gotta go".'),
        s("You didn't have to do that.", 'Você não precisava ter feito isso.', 'Agradecimento: não era obrigação.'),
        s('Does he have to work on Sundays?', 'Ele tem que trabalhar aos domingos?', 'Terceira pessoa na pergunta: "does he have to".'),
        s('You need to sign here.', 'Você precisa assinar aqui.', '"Need to" = necessidade, muito usado no lugar de "have to".'),
      ]),
      lesson(8, 'May', 'Permissão formal e possibilidade.', [
        s('May I come in?', 'Posso entrar?', '"May I" = pedir permissão com formalidade.'),
        s('May I help you?', 'Posso ajudar?', 'Frase clássica de atendimento.'),
        s('You may leave now.', 'Pode sair agora.', '"You may" = permissão formal, de professor ou chefe.'),
        s('It may take a few days.', 'Pode levar alguns dias.', '"May" = possibilidade, tom neutro ou formal.'),
        s('He may be right.', 'Talvez ele tenha razão.', 'Possibilidade, como "might".'),
        s('Visitors may not take photos.', 'Visitantes não podem tirar fotos.', '"May not" em aviso = não é permitido.'),
        s('I may not be able to come.', 'Talvez eu não consiga vir.', '"May not" também = talvez não.'),
        s('She may have missed the train.', 'Ela pode ter perdido o trem.', '"May have" + particípio = possibilidade no passado.'),
        s('May I have the check, please?', 'Pode me trazer a conta, por favor?', 'Pedido educado no restaurante.'),
        s('May all your dreams come true.', 'Que todos os seus sonhos se realizem.', '"May" no início = desejo, em votos e cartões.'),
      ]),
    ],
  },
];
