// Lote palavras-6: 1000 Palavras Essenciais, temas 17–19 (direções e posições,
// animais, emoções e sentimentos). Conteúdo original.

export const LEXICON = {
  // direções e posições
  right: ['adverb', '/raɪt/', 'à direita; certo'],
  straight: ['adverb', '/streɪt/', 'reto'],
  north: ['noun', '/nɔːrθ/', 'norte'],
  south: ['noun', '/saʊθ/', 'sul'],
  east: ['noun', '/iːst/', 'leste'],
  west: ['noun', '/wɛst/', 'oeste'],
  next: ['adjective', '/nɛkst/', 'próximo; next to = ao lado de'],
  between: ['preposition', '/bɪˈtwiːn/', 'entre'],
  behind: ['preposition', '/bɪˈhaɪnd/', 'atrás de'],
  front: ['noun', '/frʌnt/', 'frente'],
  opposite: ['preposition', '/ˈɑːpəzɪt/', 'em frente a, do outro lado'],
  inside: ['adverb', '/ˌɪnˈsaɪd/', 'dentro'],
  above: ['preposition', '/əˈbʌv/', 'acima de'],
  below: ['preposition', '/bɪˈloʊ/', 'abaixo de'],
  under: ['preposition', '/ˈʌndər/', 'embaixo de'],
  across: ['preposition', '/əˈkrɔːs/', 'do outro lado de, atravessando'],
  near: ['preposition', '/nɪr/', 'perto de'],
  far: ['adjective', '/fɑːr/', 'longe'],
  up: ['adverb', '/ʌp/', 'para cima'],
  down: ['adverb', '/daʊn/', 'para baixo'],
  // animais
  dog: ['noun', '/dɔːɡ/', 'cachorro'],
  cat: ['noun', '/kæt/', 'gato'],
  bird: ['noun', '/bɜːrd/', 'pássaro'],
  horse: ['noun', '/hɔːrs/', 'cavalo'],
  cow: ['noun', '/kaʊ/', 'vaca'],
  pig: ['noun', '/pɪɡ/', 'porco'],
  sheep: ['noun', '/ʃiːp/', 'ovelha'],
  mouse: ['noun', '/maʊs/', 'rato, camundongo'],
  rabbit: ['noun', '/ˈræbɪt/', 'coelho'],
  snake: ['noun', '/sneɪk/', 'cobra'],
  monkey: ['noun', '/ˈmʌŋki/', 'macaco'],
  lion: ['noun', '/ˈlaɪən/', 'leão'],
  bear: ['noun', '/bɛr/', 'urso'],
  duck: ['noun', '/dʌk/', 'pato'],
  shark: ['noun', '/ʃɑːrk/', 'tubarão'],
  bee: ['noun', '/biː/', 'abelha'],
  spider: ['noun', '/ˈspaɪdər/', 'aranha'],
  insect: ['noun', '/ˈɪnsɛkt/', 'inseto'],
  pet: ['noun', '/pɛt/', 'animal de estimação'],
  animal: ['noun', '/ˈænɪməl/', 'animal'],
  // emoções
  sad: ['adjective', '/sæd/', 'triste'],
  angry: ['adjective', '/ˈæŋɡri/', 'bravo, com raiva'],
  scared: ['adjective', '/skɛrd/', 'com medo'],
  worried: ['adjective', '/ˈwɜːrid/', 'preocupado'],
  nervous: ['adjective', '/ˈnɜːrvəs/', 'nervoso, ansioso'],
  bored: ['adjective', '/bɔːrd/', 'entediado'],
  boring: ['adjective', '/ˈbɔːrɪŋ/', 'chato, entediante'],
  surprised: ['adjective', '/sərˈpraɪzd/', 'surpreso'],
  proud: ['adjective', '/praʊd/', 'orgulhoso'],
  lonely: ['adjective', '/ˈloʊnli/', 'sozinho, solitário'],
  embarrassed: ['adjective', '/ɪmˈbærəst/', 'envergonhado'],
  jealous: ['adjective', '/ˈdʒɛləs/', 'com ciúme, com inveja'],
  relaxed: ['adjective', '/rɪˈlækst/', 'relaxado'],
  confused: ['adjective', '/kənˈfjuːzd/', 'confuso'],
  grateful: ['adjective', '/ˈɡreɪtfəl/', 'grato'],
  upset: ['adjective', '/ʌpˈsɛt/', 'chateado'],
  calm: ['adjective', '/kɑːm/', 'calmo'],
};

const w = (text, pt, example, note = null) => ({ kind: 'word', text, pt, example, note });

export const COURSES = [
  {
    id: 'course-1000-words-a1',
    slug: '1000-essential-words',
    title: '1000 Palavras Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 2,
    order: 11,
    short: 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.',
    long: 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.',
    lessons: [
      {
        id: 'lesson-1000-words-a1-17',
        chapter: 17,
        title: 'Direções e posições',
        description: 'Onde fica, para onde ir e como explicar o caminho.',
        units: [
          w('left', 'esquerda', ['Turn left at the bank.', 'Vire à esquerda no banco.'], '"Turn left" sem preposição.'),
          w('right', 'direita', ['The store is on the right.', 'A loja fica à direita.'], '"On the right/left" = à direita/esquerda. "Right" também é "certo".'),
          w('straight', 'reto', ['Go straight for two blocks.', 'Siga reto por dois quarteirões.'], '"Block" = quarteirão.'),
          w('north', 'norte', ['The beach is north of the city.', 'A praia fica ao norte da cidade.']),
          w('south', 'sul', ['We drove south.', 'Dirigimos para o sul.']),
          w('east', 'leste', ['The sun rises in the east.', 'O sol nasce no leste.']),
          w('west', 'oeste', ['The sun sets in the west.', 'O sol se põe no oeste.']),
          w('next', 'ao lado', ['The pharmacy is next to the bank.', 'A farmácia fica ao lado do banco.'], '"Next to" = ao lado de.'),
          w('between', 'entre', ["It's between the school and the park.", 'Fica entre a escola e o parque.'], '"Between" é entre dois; "among" é entre vários.'),
          w('behind', 'atrás de', ['The car is behind the house.', 'O carro está atrás da casa.']),
          w('front', 'frente', ['Wait in front of the hotel.', 'Espere na frente do hotel.'], '"In front of" = na frente de.'),
          w('opposite', 'em frente a', ['The bank is opposite the station.', 'O banco fica em frente à estação.'], '"Opposite" = do outro lado, de frente. Diferente de "in front of".'),
          w('inside', 'dentro', ["It's cold, let's go inside.", 'Está frio, vamos entrar.']),
          w('outside', 'fora', ['The kids are playing outside.', 'As crianças estão brincando lá fora.']),
          w('above', 'acima de', ['The picture is above the sofa.', 'O quadro está acima do sofá.']),
          w('under', 'embaixo de', ['The cat is under the table.', 'O gato está embaixo da mesa.']),
          w('across', 'do outro lado de', ['The bakery is across the street.', 'A padaria fica do outro lado da rua.']),
          w('near', 'perto de', ['Is there a bank near here?', 'Tem um banco perto daqui?'], '"Near" sem "of": "near the hotel".'),
          w('far', 'longe', ['Is it far from here?', 'É longe daqui?'], '"Far from" = longe de.'),
          w('down', 'para baixo', ['Go down the stairs.', 'Desça a escada.'], '"Up" = para cima; "down" = para baixo. Também "down the street" = rua abaixo.'),
        ],
      },
      {
        id: 'lesson-1000-words-a1-18',
        chapter: 18,
        title: 'Animais',
        description: 'Animais de estimação, da fazenda e selvagens.',
        units: [
          w('dog', 'cachorro', ['My dog loves the park.', 'Meu cachorro adora o parque.']),
          w('cat', 'gato', ['The cat is sleeping.', 'O gato está dormindo.']),
          w('pet', 'animal de estimação', ['Do you have any pets?', 'Você tem algum animal de estimação?']),
          w('bird', 'pássaro', ['I can hear the birds.', 'Consigo ouvir os pássaros.']),
          w('fish', 'peixe', ['We have two fish at home.', 'Temos dois peixes em casa.'], 'Plural geralmente igual: "fish".'),
          w('horse', 'cavalo', ['She rides a horse.', 'Ela anda a cavalo.'], 'Andar a cavalo também é "ride".'),
          w('cow', 'vaca', ['The cows are in the field.', 'As vacas estão no pasto.']),
          w('pig', 'porco', ['The pig is very big.', 'O porco é muito grande.']),
          w('sheep', 'ovelha', ['There are many sheep on the farm.', 'Tem muitas ovelhas na fazenda.'], 'Plural igual ao singular: "one sheep, ten sheep".'),
          w('chicken', 'galinha, frango', ['The chickens lay eggs.', 'As galinhas botam ovos.'], 'O animal e a carne têm o mesmo nome.'),
          w('duck', 'pato', ['There are ducks in the lake.', 'Tem patos no lago.']),
          w('mouse', 'rato', ['I saw a mouse in the kitchen.', 'Vi um rato na cozinha.'], 'Plural irregular: "mice". Rato grande é "rat".'),
          w('rabbit', 'coelho', ['The rabbit is eating a carrot.', 'O coelho está comendo uma cenoura.']),
          w('snake', 'cobra', ['Be careful, there is a snake.', 'Cuidado, tem uma cobra.']),
          w('monkey', 'macaco', ['The monkeys are funny.', 'Os macacos são engraçados.']),
          w('lion', 'leão', ['The lion is sleeping.', 'O leão está dormindo.']),
          w('bear', 'urso', ['We saw a bear in the forest.', 'Vimos um urso na floresta.']),
          w('shark', 'tubarão', ['Are there sharks here?', 'Tem tubarão aqui?']),
          w('bee', 'abelha', ['I am allergic to bees.', 'Sou alérgico a abelha.']),
          w('spider', 'aranha', ["I'm scared of spiders.", 'Tenho medo de aranha.'], '"Scared of" = com medo de.'),
        ],
      },
      {
        id: 'lesson-1000-words-a1-19',
        chapter: 19,
        title: 'Emoções e sentimentos',
        description: 'Dizer como você se sente com a palavra certa.',
        units: [
          w('happy', 'feliz', ["I'm so happy for you.", 'Estou muito feliz por você.'], '"Happy for" = feliz por alguém.'),
          w('sad', 'triste', ['She looks sad today.', 'Ela parece triste hoje.']),
          w('angry', 'bravo', ['Why are you angry?', 'Por que você está bravo?'], '"Angry at/with" + pessoa.'),
          w('scared', 'com medo', ["Don't be scared.", 'Não tenha medo.'], '"Scared" = com medo; "scary" = assustador.'),
          w('worried', 'preocupado', ["I'm worried about the exam.", 'Estou preocupado com a prova.'], '"Worried about" = preocupado com.'),
          w('nervous', 'nervoso', ["I'm nervous before interviews.", 'Fico nervoso antes de entrevistas.'], 'Em inglês "nervous" é ansioso, não bravo.'),
          w('excited', 'animado', ["I'm excited about the trip.", 'Estou animado com a viagem.'], 'Falso cognato: "excited" = animado, empolgado.'),
          w('bored', 'entediado', ["I'm bored, let's go out.", 'Estou entediado, vamos sair.'], '"Bored" = entediado (a pessoa); "boring" = chato (a coisa).'),
          w('boring', 'chato', ['The movie was boring.', 'O filme foi chato.']),
          w('tired', 'cansado', ["I'm too tired to go out.", 'Estou cansado demais para sair.']),
          w('surprised', 'surpreso', ['I was surprised to see him.', 'Fiquei surpreso de ver ele.']),
          w('proud', 'orgulhoso', ["I'm proud of you.", 'Estou orgulhoso de você.'], '"Proud of" = orgulhoso de.'),
          w('lonely', 'solitário', ['She feels lonely in the new city.', 'Ela se sente sozinha na cidade nova.'], '"Lonely" é o sentimento; "alone" é estar sem companhia.'),
          w('embarrassed', 'envergonhado', ['I was so embarrassed.', 'Fiquei morrendo de vergonha.'], 'Falso cognato: "embarrassed" = com vergonha; grávida é "pregnant".'),
          w('jealous', 'com ciúme', ["He's jealous of his brother.", 'Ele tem ciúme do irmão.']),
          w('relaxed', 'relaxado', ['I feel relaxed on vacation.', 'Fico relaxado nas férias.']),
          w('confused', 'confuso', ["I'm confused, can you explain again?", 'Estou confuso, pode explicar de novo?']),
          w('grateful', 'grato', ["I'm grateful for your help.", 'Sou grato pela sua ajuda.']),
          w('upset', 'chateado', ['She was upset about the news.', 'Ela ficou chateada com a notícia.']),
          w('calm', 'calmo', ['Stay calm.', 'Fique calmo.'], 'O "l" é mudo: /kɑːm/.'),
        ],
      },
    ],
  },
];
