// Lote palavras-1: 1000 Palavras Essenciais, temas 2–4 (cores, números 1–20,
// itens essenciais do dia a dia). Cada palavra com significado, IPA, exemplo e
// nota quando há armadilha. Conteúdo original.

export const LEXICON = {
  // cores
  red: ['adjective', '/rɛd/', 'vermelho'],
  blue: ['adjective', '/bluː/', 'azul'],
  green: ['adjective', '/ɡriːn/', 'verde'],
  yellow: ['adjective', '/ˈjɛloʊ/', 'amarelo'],
  black: ['adjective', '/blæk/', 'preto'],
  white: ['adjective', '/waɪt/', 'branco'],
  orange: ['adjective', '/ˈɔːrɪndʒ/', 'laranja'],
  purple: ['adjective', '/ˈpɜːrpəl/', 'roxo'],
  pink: ['adjective', '/pɪŋk/', 'rosa'],
  brown: ['adjective', '/braʊn/', 'marrom'],
  gray: ['adjective', '/ɡreɪ/', 'cinza'],
  gold: ['adjective', '/ɡoʊld/', 'dourado; ouro'],
  silver: ['adjective', '/ˈsɪlvər/', 'prateado; prata'],
  beige: ['adjective', '/beɪʒ/', 'bege'],
  dark: ['adjective', '/dɑːrk/', 'escuro'],
  light: ['adjective', '/laɪt/', 'claro'],
  bright: ['adjective', '/braɪt/', 'vivo, brilhante'],
  color: ['noun', '/ˈkʌlər/', 'cor'],
  colorful: ['adjective', '/ˈkʌlərfəl/', 'colorido'],
  rainbow: ['noun', '/ˈreɪnboʊ/', 'arco-íris'],
  // números
  one: ['numeral', '/wʌn/', 'um'],
  three: ['numeral', '/θriː/', 'três'],
  four: ['numeral', '/fɔːr/', 'quatro'],
  five: ['numeral', '/faɪv/', 'cinco'],
  six: ['numeral', '/sɪks/', 'seis'],
  eight: ['numeral', '/eɪt/', 'oito'],
  nine: ['numeral', '/naɪn/', 'nove'],
  eleven: ['numeral', '/ɪˈlɛvən/', 'onze'],
  twelve: ['numeral', '/twɛlv/', 'doze'],
  thirteen: ['numeral', '/ˌθɜːrˈtiːn/', 'treze'],
  fourteen: ['numeral', '/ˌfɔːrˈtiːn/', 'catorze'],
  fifteen: ['numeral', '/ˌfɪfˈtiːn/', 'quinze'],
  sixteen: ['numeral', '/ˌsɪksˈtiːn/', 'dezesseis'],
  seventeen: ['numeral', '/ˌsɛvənˈtiːn/', 'dezessete'],
  eighteen: ['numeral', '/ˌeɪˈtiːn/', 'dezoito'],
  nineteen: ['numeral', '/ˌnaɪnˈtiːn/', 'dezenove'],
  twenty: ['numeral', '/ˈtwɛnti/', 'vinte'],
  // itens essenciais
  keys: ['noun', '/kiːz/', 'chaves'],
  wallet: ['noun', '/ˈwɑːlɪt/', 'carteira'],
  passport: ['noun', '/ˈpæspɔːrt/', 'passaporte'],
  charger: ['noun', '/ˈtʃɑːrdʒər/', 'carregador'],
  umbrella: ['noun', '/ʌmˈbrɛlə/', 'guarda-chuva'],
  glasses: ['noun', '/ˈɡlæsɪz/', 'óculos'],
  bag: ['noun', '/bæɡ/', 'bolsa, sacola, mala'],
  backpack: ['noun', '/ˈbækpæk/', 'mochila'],
  watch: ['noun', '/wɑːtʃ/', 'relógio de pulso'],
  money: ['noun', '/ˈmʌni/', 'dinheiro'],
  toothbrush: ['noun', '/ˈtuːθbrʌʃ/', 'escova de dentes'],
  towel: ['noun', '/ˈtaʊəl/', 'toalha'],
  medicine: ['noun', '/ˈmɛdɪsən/', 'remédio'],
  ticket: ['noun', '/ˈtɪkɪt/', 'passagem, ingresso'],
  notebook: ['noun', '/ˈnoʊtbʊk/', 'caderno'],
  headphones: ['noun', '/ˈhɛdfoʊnz/', 'fones de ouvido'],
  bottle: ['noun', '/ˈbɑːtəl/', 'garrafa'],
  tissues: ['noun', '/ˈtɪʃuːz/', 'lenços de papel'],
  jacket: ['noun', '/ˈdʒækɪt/', 'jaqueta'],
};

const w = (text, pt, example, note = null) => ({ kind: 'word', text, pt, example, note });

export const COURSES = [
  {
    id: 'course-1000-words-a1',
    slug: '1000-essential-words',
    title: '1000 Palavras Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 2,
    order: 11,
    short: 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.',
    long: 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.',
    lessons: [
      {
        id: 'lesson-1000-words-a1-02',
        chapter: 2,
        title: 'Cores',
        description: 'As cores básicas e como descrever tons.',
        units: [
          w('red', 'vermelho', ['She has a red car.', 'Ela tem um carro vermelho.'], 'Em inglês o adjetivo vem antes do substantivo: "a red car", não "a car red".'),
          w('blue', 'azul', ['The sky is blue today.', 'O céu está azul hoje.']),
          w('green', 'verde', ['I like green tea.', 'Eu gosto de chá verde.']),
          w('yellow', 'amarelo', ['The taxi is yellow.', 'O táxi é amarelo.']),
          w('black', 'preto', ['I want a black coffee.', 'Quero um café preto (sem leite).'], '"Black coffee" = café sem leite.'),
          w('white', 'branco', ['Her dress is white.', 'O vestido dela é branco.'], 'O "h" não é pronunciado: /waɪt/.'),
          w('orange', 'laranja', ['He wore an orange shirt.', 'Ele usou uma camisa laranja.'], 'Serve para a cor e para a fruta; como começa com som de vogal, usa "an": "an orange".'),
          w('purple', 'roxo', ['Purple is my favorite color.', 'Roxo é minha cor favorita.']),
          w('pink', 'rosa', ['She painted her room pink.', 'Ela pintou o quarto de rosa.'], 'A flor rosa é "rose"; a cor é "pink".'),
          w('brown', 'marrom', ['He has brown eyes.', 'Ele tem olhos castanhos.'], 'Para olhos e cabelo, "brown" = castanho.'),
          w('gray', 'cinza', ['The weather is gray and cold.', 'O tempo está cinzento e frio.'], 'EUA: "gray"; Reino Unido: "grey".'),
          w('gold', 'dourado', ['She wears a gold ring.', 'Ela usa um anel de ouro.']),
          w('silver', 'prateado', ['I have a silver phone.', 'Eu tenho um celular prateado.']),
          w('beige', 'bege', ['The walls are beige.', 'As paredes são bege.']),
          w('dark', 'escuro', ['I prefer dark blue.', 'Eu prefiro azul-escuro.'], '"Dark" vem antes da cor: "dark green" = verde-escuro.'),
          w('light', 'claro', ['She bought a light pink bag.', 'Ela comprou uma bolsa rosa-claro.'], '"Light" + cor = tom claro: "light blue" = azul-claro.'),
          w('bright', 'vivo, brilhante', ['The room has bright colors.', 'O quarto tem cores vivas.']),
          w('color', 'cor', ['What color is your car?', 'De que cor é o seu carro?'], 'Pergunta pela cor: "What color is…?". Reino Unido: "colour".'),
          w('colorful', 'colorido', ['The market is very colorful.', 'O mercado é muito colorido.']),
          w('rainbow', 'arco-íris', ['Look, a rainbow!', 'Olha, um arco-íris!']),
        ],
      },
      {
        id: 'lesson-1000-words-a1-03',
        chapter: 3,
        title: 'Números de 1 a 20',
        description: 'Contar, dizer idade e quantidades.',
        units: [
          w('one', 'um', ['I have one brother.', 'Eu tenho um irmão.'], 'Pronúncia /wʌn/, igual a "won".'),
          w('two', 'dois', ['We have two kids.', 'Nós temos dois filhos.'], 'Mesmo som de "to" e "too".'),
          w('three', 'três', ['The class starts at three.', 'A aula começa às três.'], 'O "th" é soprado, com a língua entre os dentes.'),
          w('four', 'quatro', ['There are four people here.', 'Tem quatro pessoas aqui.']),
          w('five', 'cinco', ['Give me five minutes.', 'Me dá cinco minutos.']),
          w('six', 'seis', ['I wake up at six.', 'Eu acordo às seis.']),
          w('seven', 'sete', ['The store opens at seven.', 'A loja abre às sete.']),
          w('eight', 'oito', ['She is eight years old.', 'Ela tem oito anos.'], 'Pronúncia /eɪt/: o "gh" é mudo.'),
          w('nine', 'nove', ['We have nine rooms.', 'Temos nove quartos.']),
          w('ten', 'dez', ['It costs ten dollars.', 'Custa dez dólares.']),
          w('eleven', 'onze', ['The bus leaves at eleven.', 'O ônibus sai às onze.']),
          w('twelve', 'doze', ['A dozen is twelve.', 'Uma dúzia são doze.']),
          w('thirteen', 'treze', ['He is thirteen.', 'Ele tem treze anos.'], 'De 13 a 19 a força está no fim: thir-TEEN. Em "thirty" (30) está no começo: THIR-ty.'),
          w('fourteen', 'catorze', ['I read fourteen pages.', 'Eu li catorze páginas.']),
          w('fifteen', 'quinze', ['Wait fifteen minutes.', 'Espere quinze minutos.'], 'É "fif-", não "five-": fifteen.'),
          w('sixteen', 'dezesseis', ['She turned sixteen.', 'Ela fez dezesseis anos.']),
          w('seventeen', 'dezessete', ['Room seventeen, please.', 'Quarto dezessete, por favor.']),
          w('eighteen', 'dezoito', ['You must be eighteen.', 'Você precisa ter dezoito anos.'], 'Só um "t": eighteen.'),
          w('nineteen', 'dezenove', ['The flight is at nineteen hundred.', 'O voo é às dezenove horas.']),
          w('twenty', 'vinte', ['I have twenty dollars.', 'Eu tenho vinte dólares.'], 'Na fala rápida americana soa "twenny".'),
        ],
      },
      {
        id: 'lesson-1000-words-a1-04',
        chapter: 4,
        title: 'Itens essenciais do dia a dia',
        description: 'O que levamos na bolsa, na mochila e na viagem.',
        units: [
          w('keys', 'chaves', ["I can't find my keys.", 'Não consigo achar minhas chaves.']),
          w('wallet', 'carteira', ['My wallet is in my bag.', 'Minha carteira está na bolsa.'], '"Wallet" = carteira de dinheiro; carteira de motorista é "driver\'s license".'),
          w('passport', 'passaporte', ["Don't forget your passport.", 'Não esqueça o passaporte.']),
          w('phone', 'celular, telefone', ['My phone is dead.', 'Meu celular descarregou.'], '"My phone is dead" = a bateria acabou.'),
          w('charger', 'carregador', ['Can I borrow your charger?', 'Posso pegar seu carregador emprestado?']),
          w('umbrella', 'guarda-chuva', ['Take an umbrella, it might rain.', 'Leve um guarda-chuva, pode chover.']),
          w('glasses', 'óculos', ['I need my glasses to read.', 'Preciso dos óculos para ler.'], 'Sempre no plural: "my glasses are…". "Sunglasses" = óculos de sol.'),
          w('bag', 'bolsa, sacola, mala', ['Do you need a bag?', 'Você precisa de sacola?']),
          w('backpack', 'mochila', ['My laptop is in my backpack.', 'Meu notebook está na mochila.']),
          w('watch', 'relógio de pulso', ['My watch is slow.', 'Meu relógio está atrasado.'], '"Watch" = relógio de pulso; relógio de parede é "clock".'),
          w('money', 'dinheiro', ["I don't have any money.", 'Não tenho dinheiro nenhum.'], 'Incontável: "much money", nunca "moneys".'),
          w('toothbrush', 'escova de dentes', ['I forgot my toothbrush.', 'Esqueci minha escova de dentes.']),
          w('towel', 'toalha', ['Can I have a clean towel?', 'Pode me dar uma toalha limpa?']),
          w('medicine', 'remédio', ['Take this medicine twice a day.', 'Tome este remédio duas vezes ao dia.']),
          w('ticket', 'passagem, ingresso', ['I bought the tickets online.', 'Comprei as passagens pela internet.']),
          w('notebook', 'caderno', ['Write it in your notebook.', 'Escreva no seu caderno.'], 'Falso cognato: "notebook" é caderno; o computador é "laptop".'),
          w('headphones', 'fones de ouvido', ['I always travel with headphones.', 'Eu sempre viajo com fones de ouvido.']),
          w('bottle', 'garrafa', ['A bottle of water, please.', 'Uma garrafa de água, por favor.']),
          w('tissues', 'lenços de papel', ['Do you have any tissues?', 'Você tem lenço de papel?']),
          w('jacket', 'jaqueta', ['Bring a jacket, it gets cold.', 'Traga uma jaqueta, esfria.']),
        ],
      },
    ],
  },
];
