// Lote palavras-10: 1000 Palavras Essenciais, temas 35–40 (verbos de ação 1–3,
// adjetivos opostos 1–2, advérbios de tempo e frequência). Conteúdo original.

export const LEXICON = {
  ago: ["adverb", "/əˈɡoʊ/", "atrás (tempo)"],
  carry: ["verb", "/ˈkæri/", "carregar"],
  climb: ["verb", "/klaɪm/", "escalar, subir"],
  dangerous: ["adjective", "/ˈdeɪndʒərəs/", "perigoso"],
  decide: ["verb", "/dɪˈsaɪd/", "decidir"],
  difficult: ["adjective", "/ˈdɪfɪkəlt/", "difícil"],
  dirty: ["adjective", "/ˈdɜːrti/", "sujo"],
  false: ["adjective", "/fɔːls/", "falso"],
  feed: ["verb", "/fiːd/", "alimentar"],
  fold: ["verb", "/foʊld/", "dobrar"],
  guess: ["verb", "/ɡɛs/", "adivinhar, achar"],
  hang: ["verb", "/hæŋ/", "pendurar"],
  jump: ["verb", "/dʒʌmp/", "pular"],
  lie: ["verb", "/laɪ/", "deitar-se; mentir"],
  loud: ["adjective", "/laʊd/", "alto (som)"],
  once: ["adverb", "/wʌns/", "uma vez"],
  pack: ["verb", "/pæk/", "fazer a mala, empacotar"],
  plug: ["verb", "/plʌɡ/", "ligar na tomada"],
  poor: ["adjective", "/pʊr/", "pobre"],
  promise: ["verb", "/ˈprɑːmɪs/", "prometer"],
  pull: ["verb", "/pʊl/", "puxar"],
  recently: ["adverb", "/ˈriːsəntli/", "recentemente"],
  shout: ["verb", "/ʃaʊt/", "gritar"],
  slow: ["adjective", "/sloʊ/", "lento"],
  soft: ["adjective", "/sɔːft/", "macio"],
  sweep: ["verb", "/swiːp/", "varrer"],
  throw: ["verb", "/θroʊ/", "jogar, arremessar"],
  weak: ["adjective", "/wiːk/", "fraco"],
  wet: ["adjective", "/wɛt/", "molhado"],
  whisper: ["verb", "/ˈwɪspər/", "sussurrar"],
  wish: ["verb", "/wɪʃ/", "desejar"],
};

const w = (text, pt, example, note = null) => ({ kind: 'word', text, pt, example, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-1000-words-a1-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-1000-words-a1',
    slug: '1000-essential-words',
    title: '1000 Palavras Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 2,
    order: 11,
    short: 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.',
    long: 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.',
    lessons: [
      lesson(35, 'Verbos de ação 1: movimento', 'Verbos do corpo e do movimento.', [
        w('walk', 'andar', ['We walk to school.', 'Vamos a pé para a escola.']),
        w('run', 'correr', ['I run every morning.', 'Corro toda manhã.']),
        w('jump', 'pular', ['The kids jump on the bed.', 'As crianças pulam na cama.']),
        w('sit', 'sentar', ['Sit here, please.', 'Sente aqui, por favor.']),
        w('stand', 'ficar de pé', ['Please stand up.', 'Por favor, levante-se.']),
        w('climb', 'escalar, subir', ['We climbed the hill.', 'Subimos o morro.'], 'O "b" é mudo: /klaɪm/.'),
        w('dance', 'dançar', ['Let\'s dance!', 'Vamos dançar!']),
        w('swim', 'nadar', ['Can you swim?', 'Você sabe nadar?']),
        w('push', 'empurrar', ['Push the door.', 'Empurre a porta.'], 'Em portas: "push" = empurre; "pull" = puxe.'),
        w('pull', 'puxar', ['Pull the rope.', 'Puxe a corda.']),
        w('carry', 'carregar', ['Can you carry this box?', 'Pode carregar esta caixa?']),
        w('throw', 'jogar, arremessar', ['Throw me the ball.', 'Joga a bola para mim.']),
        w('catch', 'pegar (no ar)', ['Catch!', 'Pega!']),
        w('turn', 'virar', ['Turn right here.', 'Vire à direita aqui.']),
        w('fall', 'cair', ["Don't fall!", 'Não caia!']),
        w('lie', 'deitar-se', ['Lie down and relax.', 'Deite e relaxe.'], '"Lie" também é mentir, com outro passado: "lied".'),
        w('hurry', 'apressar-se', ['Hurry up!', 'Anda logo!']),
        w('arrive', 'chegar', ['What time do you arrive?', 'Que horas você chega?']),
        w('leave', 'sair, partir', ['We leave at six.', 'Saímos às seis.']),
        w('return', 'voltar', ['I will return on Monday.', 'Volto na segunda.']),
      ]),
      lesson(36, 'Verbos de ação 2: casa e dia a dia', 'Verbos das tarefas diárias.', [
        w('wake', 'acordar', ['I wake up at seven.', 'Acordo às sete.']),
        w('wash', 'lavar', ['Wash your hands.', 'Lave as mãos.']),
        w('clean', 'limpar', ['I clean the house on Saturday.', 'Limpo a casa no sábado.']),
        w('cook', 'cozinhar', ['He cooks very well.', 'Ele cozinha muito bem.']),
        w('open', 'abrir', ['Open the window.', 'Abra a janela.']),
        w('close', 'fechar', ['Close the door.', 'Feche a porta.']),
        w('fix', 'consertar', ['Can you fix my bike?', 'Pode consertar minha bicicleta?']),
        w('break', 'quebrar', ["Don't break it.", 'Não quebre.']),
        w('build', 'construir', ['They build houses.', 'Eles constroem casas.']),
        w('cut', 'cortar', ['Cut the bread.', 'Corte o pão.']),
        w('fill', 'encher, preencher', ['Fill the glass.', 'Encha o copo.']),
        w('empty', 'esvaziar', ['Empty the trash.', 'Esvazie o lixo.']),
        w('hang', 'pendurar', ['Hang your coat here.', 'Pendure o casaco aqui.']),
        w('plug', 'ligar na tomada', ['Plug in the charger.', 'Coloque o carregador na tomada.']),
        w('switch', 'ligar, trocar', ['Switch off the TV.', 'Desligue a TV.'], '"Switch on/off" = ligar/desligar.'),
        w('pack', 'fazer a mala', ['I need to pack.', 'Preciso fazer a mala.']),
        w('fold', 'dobrar', ['Fold the clothes.', 'Dobre as roupas.']),
        w('sweep', 'varrer', ['Sweep the floor.', 'Varra o chão.']),
        w('feed', 'alimentar', ['Feed the cat.', 'Dê comida ao gato.']),
        w('water', 'regar', ['Water the plants.', 'Regue as plantas.']),
      ]),
      lesson(37, 'Verbos de ação 3: comunicação e mente', 'Falar, pensar e sentir.', [
        w('say', 'dizer', ['What did you say?', 'O que você disse?']),
        w('tell', 'contar, dizer a alguém', ['Tell me a story.', 'Me conte uma história.'], '"Tell" leva a pessoa; "say" não: "say something to me".'),
        w('ask', 'perguntar, pedir', ['Ask the teacher.', 'Pergunte ao professor.']),
        w('answer', 'responder', ['Answer the phone.', 'Atenda o telefone.']),
        w('explain', 'explicar', ['Can you explain it?', 'Pode explicar?'], '"Explain to me", nunca "explain me".'),
        w('talk', 'conversar', ["Let's talk later.", 'Vamos conversar depois.']),
        w('call', 'ligar', ['Call me tonight.', 'Me ligue hoje à noite.']),
        w('shout', 'gritar', ["Don't shout!", 'Não grite!']),
        w('whisper', 'sussurrar', ['She whispered a secret.', 'Ela sussurrou um segredo.']),
        w('think', 'pensar, achar', ['I think so.', 'Acho que sim.']),
        w('know', 'saber, conhecer', ['I know the answer.', 'Sei a resposta.']),
        w('believe', 'acreditar', ['I believe you.', 'Acredito em você.']),
        w('guess', 'adivinhar, achar', ['Guess what!', 'Adivinha!'], '"I guess" = acho que (informal).'),
        w('remember', 'lembrar', ['Remember to call.', 'Lembre de ligar.']),
        w('forget', 'esquecer', ["Don't forget.", 'Não esqueça.']),
        w('decide', 'decidir', ['You decide.', 'Você decide.']),
        w('agree', 'concordar', ['I agree.', 'Concordo.']),
        w('hope', 'esperar (ter esperança)', ['I hope so.', 'Espero que sim.']),
        w('wish', 'desejar', ['I wish you luck.', 'Te desejo sorte.']),
        w('promise', 'prometer', ['I promise.', 'Prometo.']),
      ]),
      lesson(38, 'Adjetivos opostos 1', 'Pares de adjetivos do dia a dia.', [
        w('good', 'bom', ['This is a good idea.', 'Esta é uma boa ideia.'], 'Oposto: "bad".'),
        w('bad', 'ruim', ['The weather is bad.', 'O tempo está ruim.']),
        w('new', 'novo', ['I have a new phone.', 'Tenho um celular novo.'], 'Oposto: "old".'),
        w('old', 'velho', ['This is an old house.', 'Esta é uma casa velha.']),
        w('hot', 'quente', ['The coffee is hot.', 'O café está quente.'], 'Oposto: "cold".'),
        w('cold', 'frio', ['The water is cold.', 'A água está fria.']),
        w('easy', 'fácil', ['The test was easy.', 'A prova foi fácil.'], 'Oposto: "difficult" ou "hard".'),
        w('difficult', 'difícil', ['English is not difficult.', 'Inglês não é difícil.']),
        w('fast', 'rápido', ['This car is fast.', 'Este carro é rápido.'], 'Oposto: "slow".'),
        w('slow', 'lento', ['The internet is slow.', 'A internet está lenta.']),
        w('open', 'aberto', ['The store is open.', 'A loja está aberta.'], 'Oposto: "closed".'),
        w('closed', 'fechado', ['The bank is closed.', 'O banco está fechado.']),
        w('full', 'cheio', ['The bus is full.', 'O ônibus está cheio.'], 'Oposto: "empty".'),
        w('empty', 'vazio', ['The room is empty.', 'A sala está vazia.']),
        w('clean', 'limpo', ['The kitchen is clean.', 'A cozinha está limpa.'], 'Oposto: "dirty".'),
        w('dirty', 'sujo', ['My shoes are dirty.', 'Meus sapatos estão sujos.']),
        w('early', 'cedo', ['I got up early.', 'Levantei cedo.'], 'Oposto: "late".'),
        w('late', 'tarde, atrasado', ['It is late.', 'Está tarde.']),
        w('right', 'certo', ['You are right.', 'Você tem razão.'], 'Oposto: "wrong".'),
        w('wrong', 'errado', ['That is the wrong answer.', 'Essa é a resposta errada.']),
      ]),
      lesson(39, 'Adjetivos opostos 2', 'Mais pares para descrever o mundo.', [
        w('rich', 'rico', ['He is very rich.', 'Ele é muito rico.'], 'Oposto: "poor".'),
        w('poor', 'pobre', ['The area is poor.', 'A região é pobre.']),
        w('strong', 'forte', ['This coffee is strong.', 'Este café está forte.'], 'Oposto: "weak".'),
        w('weak', 'fraco', ['The signal is weak.', 'O sinal está fraco.']),
        w('loud', 'alto (som)', ['The music is too loud.', 'A música está alta demais.'], 'Oposto: "quiet". Som alto é "loud", não "high".'),
        w('quiet', 'silencioso', ['The library is quiet.', 'A biblioteca é silenciosa.']),
        w('safe', 'seguro', ['This area is safe.', 'Esta região é segura.'], 'Oposto: "dangerous".'),
        w('dangerous', 'perigoso', ['That road is dangerous.', 'Aquela estrada é perigosa.']),
        w('true', 'verdadeiro', ['Is it true?', 'É verdade?'], 'Oposto: "false".'),
        w('false', 'falso', ['That is false.', 'Isso é falso.']),
        w('same', 'mesmo, igual', ['We have the same car.', 'Temos o mesmo carro.'], 'Oposto: "different".'),
        w('different', 'diferente', ['This one is different.', 'Este é diferente.']),
        w('hard', 'duro, difícil', ['The bed is too hard.', 'A cama está dura demais.'], 'Oposto: "soft".'),
        w('soft', 'macio, suave', ['The pillow is soft.', 'O travesseiro é macio.']),
        w('wet', 'molhado', ['My shoes are wet.', 'Meus sapatos estão molhados.'], 'Oposto: "dry".'),
        w('dry', 'seco', ['The towel is dry.', 'A toalha está seca.']),
        w('busy', 'ocupado', ['I am busy today.', 'Estou ocupado hoje.'], 'Oposto: "free".'),
        w('free', 'livre; grátis', ['Are you free tonight?', 'Você está livre hoje à noite?'], '"Free" também é grátis.'),
        w('happy', 'feliz', ['I am so happy.', 'Estou muito feliz.'], 'Oposto: "sad".'),
        w('sad', 'triste', ['Why are you sad?', 'Por que você está triste?']),
      ]),
      lesson(40, 'Advérbios de tempo e frequência', 'Quando e com que frequência.', [
        w('always', 'sempre', ['I always drink coffee.', 'Sempre tomo café.'], 'Vem antes do verbo principal e depois de "to be".'),
        w('usually', 'geralmente', ['I usually walk to work.', 'Geralmente vou a pé ao trabalho.']),
        w('often', 'com frequência', ['We often eat out.', 'Comemos fora com frequência.']),
        w('sometimes', 'às vezes', ['Sometimes I work late.', 'Às vezes trabalho até tarde.']),
        w('rarely', 'raramente', ['I rarely watch TV.', 'Raramente assisto TV.']),
        w('never', 'nunca', ['I never smoke.', 'Nunca fumo.'], 'Já é negativo: o verbo fica afirmativo.'),
        w('now', 'agora', ['I am busy now.', 'Estou ocupado agora.']),
        w('today', 'hoje', ["What's the date today?", 'Que dia é hoje?']),
        w('tomorrow', 'amanhã', ['See you tomorrow.', 'Até amanhã.']),
        w('yesterday', 'ontem', ['I called you yesterday.', 'Te liguei ontem.']),
        w('soon', 'logo, em breve', ['See you soon.', 'Até logo.']),
        w('later', 'mais tarde', ['Call me later.', 'Me liga mais tarde.']),
        w('already', 'já', ['I have already eaten.', 'Já comi.']),
        w('yet', 'ainda; já (pergunta)', ['Have you finished yet?', 'Você já terminou?'], 'Negativa: "not yet" = ainda não.'),
        w('still', 'ainda', ['I still live here.', 'Ainda moro aqui.']),
        w('again', 'de novo', ['Say it again.', 'Diga de novo.']),
        w('once', 'uma vez', ['I have been there once.', 'Já estive lá uma vez.']),
        w('twice', 'duas vezes', ['I brush my teeth twice a day.', 'Escovo os dentes duas vezes por dia.']),
        w('recently', 'recentemente', ['I moved here recently.', 'Me mudei para cá recentemente.']),
        w('ago', 'atrás (tempo)', ['I arrived two days ago.', 'Cheguei há dois dias.'], '"Ago" vem depois do período: "two days ago".'),
      ]),
    ],
  },
];
