// Lote palavras-11: 1000 Palavras Essenciais, temas 41–44 (preposições de lugar
// e tempo, conectores, palavras de pergunta, quantidades). Fecha o mapa das
// 1000 palavras. Conteúdo original.

export const LEXICON = {
  also: ["adverb", "/ˈɔːlsoʊ/", "também"],
  both: ["determiner", "/boʊθ/", "ambos"],
  during: ["preposition", "/ˈdʊrɪŋ/", "durante"],
  less: ["determiner", "/lɛs/", "menos"],
  none: ["pronoun", "/nʌn/", "nenhum"],
  several: ["determiner", "/ˈsɛvrəl/", "vários"],
  unless: ["conjunction", "/ənˈlɛs/", "a menos que"],
};

const w = (text, pt, example, note = null) => ({ kind: 'word', text, pt, example, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-1000-words-a1-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-1000-words-a1',
    slug: '1000-essential-words',
    title: '1000 Palavras Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 2,
    order: 11,
    short: 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.',
    long: 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.',
    lessons: [
      lesson(41, 'Preposições de lugar e tempo', 'Onde e quando.', [
        w('in', 'em, dentro', ['The keys are in my bag.', 'As chaves estão na minha bolsa.'], '"In" + cidade, país, mês, ano.'),
        w('on', 'em cima, em', ['The book is on the table.', 'O livro está na mesa.'], '"On" + dia, data, rua, superfície.'),
        w('at', 'em (ponto)', ['I am at work.', 'Estou no trabalho.'], '"At" + hora, endereço, ponto.'),
        w('under', 'embaixo de', ['The cat is under the bed.', 'O gato está debaixo da cama.']),
        w('above', 'acima de', ['The clock is above the door.', 'O relógio fica acima da porta.']),
        w('below', 'abaixo de', ['The temperature is below zero.', 'A temperatura está abaixo de zero.']),
        w('between', 'entre', ['Sit between us.', 'Sente entre nós.']),
        w('behind', 'atrás de', ['The park is behind the school.', 'O parque fica atrás da escola.']),
        w('next', 'ao lado (next to)', ['The bank is next to the pharmacy.', 'O banco fica ao lado da farmácia.']),
        w('near', 'perto de', ['I live near here.', 'Moro perto daqui.']),
        w('inside', 'dentro', ["Let's wait inside.", 'Vamos esperar dentro.']),
        w('outside', 'fora', ['The kids are outside.', 'As crianças estão lá fora.']),
        w('before', 'antes de', ['Call me before noon.', 'Me ligue antes do meio-dia.']),
        w('after', 'depois de', ['See you after class.', 'Te vejo depois da aula.']),
        w('during', 'durante', ['No phones during the movie.', 'Sem celular durante o filme.']),
        w('until', 'até (tempo)', ['The store is open until nine.', 'A loja abre até as nove.'], '"Until" é tempo; "up to" é quantidade.'),
        w('since', 'desde', ['I have lived here since May.', 'Moro aqui desde maio.'], '"Since" + ponto de início; "for" + período.'),
        w('for', 'por, durante', ['I lived there for two years.', 'Morei lá por dois anos.']),
        w('from', 'de (origem)', ['I am from Brazil.', 'Sou do Brasil.']),
        w('to', 'para, até', ['I go to work by bus.', 'Vou de ônibus para o trabalho.']),
      ]),
      lesson(42, 'Conectores', 'Palavras que ligam ideias.', [
        w('and', 'e', ['Coffee and milk.', 'Café com leite.']),
        w('but', 'mas', ['It is small but nice.', 'É pequeno, mas legal.']),
        w('or', 'ou', ['Tea or coffee?', 'Chá ou café?']),
        w('so', 'então, por isso', ['It was late, so I left.', 'Estava tarde, então fui embora.']),
        w('because', 'porque', ['I stayed because it rained.', 'Fiquei porque choveu.']),
        w('if', 'se', ['Call me if you need help.', 'Me liga se precisar de ajuda.']),
        w('when', 'quando', ['Call me when you arrive.', 'Me liga quando chegar.']),
        w('while', 'enquanto', ['I read while I wait.', 'Leio enquanto espero.']),
        w('although', 'embora', ['Although it was cold, we went out.', 'Embora estivesse frio, saímos.']),
        w('however', 'no entanto', ['It is cheap. However, it is slow.', 'É barato. No entanto, é lento.']),
        w('also', 'também', ['I also speak Spanish.', 'Também falo espanhol.'], '"Also" vem antes do verbo; "too" no fim da frase.'),
        w('too', 'também; demais', ['I like it too.', 'Eu também gosto.']),
        w('then', 'então, depois', ['First eat, then sleep.', 'Primeiro coma, depois durma.']),
        w('first', 'primeiro', ['First, open the app.', 'Primeiro, abra o aplicativo.']),
        w('finally', 'por fim', ['Finally, click save.', 'Por fim, clique em salvar.']),
        w('maybe', 'talvez', ['Maybe tomorrow.', 'Talvez amanhã.']),
        w('actually', 'na verdade', ['Actually, I disagree.', 'Na verdade, discordo.'], 'Falso cognato: não é "atualmente".'),
        w('anyway', 'enfim, de qualquer forma', ['Anyway, see you later.', 'Enfim, até mais.']),
        w('unless', 'a menos que', ['I will go unless it rains.', 'Vou, a menos que chova.']),
        w('though', 'mas, porém (no fim)', ['It is expensive. Good, though.', 'É caro. Mas é bom.'], 'No fim da frase, "though" = porém.'),
      ]),
      lesson(43, 'Palavras de pergunta', 'Quem, o quê, onde, quando, por quê, como.', [
        w('what', 'o que, qual', ['What is your name?', 'Qual é o seu nome?']),
        w('who', 'quem', ['Who is that?', 'Quem é aquele?']),
        w('where', 'onde', ['Where do you live?', 'Onde você mora?']),
        w('when', 'quando', ['When is your birthday?', 'Quando é seu aniversário?']),
        w('why', 'por que', ['Why are you late?', 'Por que você está atrasado?'], 'Resposta: "because…".'),
        w('how', 'como', ['How are you?', 'Como vai?']),
        w('which', 'qual (entre opções)', ['Which one do you want?', 'Qual você quer?'], '"Which" = entre opções definidas; "what" = em aberto.'),
        w('whose', 'de quem', ['Whose phone is this?', 'De quem é este celular?']),
        w('much', 'quanto (incontável)', ['How much is it?', 'Quanto custa?'], '"How much" para preço e incontáveis.'),
        w('many', 'quantos (contável)', ['How many people are coming?', 'Quantas pessoas vêm?']),
        w('long', 'quanto tempo', ['How long is the movie?', 'Quanto tempo dura o filme?']),
        w('often', 'com que frequência', ['How often do you run?', 'Com que frequência você corre?']),
        w('far', 'quão longe', ['How far is the beach?', 'Quão longe fica a praia?']),
        w('old', 'quantos anos', ['How old are you?', 'Quantos anos você tem?']),
        w('kind', 'tipo', ['What kind of music do you like?', 'Que tipo de música você gosta?']),
        w('time', 'que horas', ['What time is it?', 'Que horas são?']),
        w('mean', 'significar', ['What does this mean?', 'O que isso significa?']),
        w('about', 'que tal', ['What about pizza?', 'Que tal pizza?'], '"What about…?" = que tal…?'),
        w('else', 'mais', ['What else?', 'O que mais?']),
        w('come', 'como assim', ['How come?', 'Como assim?'], '"How come?" = por quê? (informal).'),
      ]),
      lesson(44, 'Quantidades', 'Muito, pouco, algum, nenhum.', [
        w('some', 'algum, um pouco', ['I need some water.', 'Preciso de um pouco de água.'], '"Some" em afirmativas e ofertas.'),
        w('any', 'algum, nenhum', ['Do you have any questions?', 'Vocês têm alguma pergunta?'], '"Any" em perguntas e negativas.'),
        w('many', 'muitos (contável)', ['There are many people here.', 'Tem muita gente aqui.']),
        w('much', 'muito (incontável)', ["I don't have much time.", 'Não tenho muito tempo.']),
        w('lot', 'muito (a lot of)', ['I have a lot of work.', 'Tenho muito trabalho.'], '"A lot of" serve para contável e incontável.'),
        w('few', 'poucos (contável)', ['I have a few friends here.', 'Tenho alguns amigos aqui.'], '"A few" = alguns; "few" = poucos (negativo).'),
        w('little', 'pouco (incontável)', ['I speak a little English.', 'Falo um pouco de inglês.']),
        w('enough', 'suficiente', ['Do we have enough money?', 'Temos dinheiro suficiente?']),
        w('all', 'todos, tudo', ['All my friends came.', 'Todos os meus amigos vieram.']),
        w('every', 'cada, todo', ['I run every day.', 'Corro todo dia.'], '"Every" + singular: "every day".'),
        w('each', 'cada', ['Each room has a bathroom.', 'Cada quarto tem banheiro.']),
        w('both', 'ambos', ['Both of them are doctors.', 'Os dois são médicos.']),
        w('none', 'nenhum', ['None of us knew.', 'Nenhum de nós sabia.']),
        w('more', 'mais', ['I need more time.', 'Preciso de mais tempo.']),
        w('less', 'menos (incontável)', ['Eat less sugar.', 'Coma menos açúcar.'], 'Com contáveis, o correto formal é "fewer".'),
        w('most', 'a maioria', ['Most people agree.', 'A maioria das pessoas concorda.']),
        w('half', 'metade', ['Half of the class was absent.', 'Metade da turma faltou.']),
        w('dozen', 'dúzia', ['A dozen eggs.', 'Uma dúzia de ovos.']),
        w('several', 'vários', ['I tried several times.', 'Tentei várias vezes.']),
        w('nothing', 'nada', ['There is nothing in the fridge.', 'Não tem nada na geladeira.']),
      ]),
    ],
  },
];
