// Lote palavras-4: 1000 Palavras Essenciais, temas 11–13 (comida básica, frutas e
// legumes, bebidas e sabores). Conteúdo original.

export const LEXICON = {
  // comida básica
  bread: ['noun', '/brɛd/', 'pão'],
  rice: ['noun', '/raɪs/', 'arroz'],
  beans: ['noun', '/biːnz/', 'feijão'],
  egg: ['noun', '/ɛɡ/', 'ovo'],
  meat: ['noun', '/miːt/', 'carne'],
  beef: ['noun', '/biːf/', 'carne de boi'],
  pork: ['noun', '/pɔːrk/', 'carne de porco'],
  fish: ['noun', '/fɪʃ/', 'peixe'],
  butter: ['noun', '/ˈbʌtər/', 'manteiga'],
  sugar: ['noun', '/ˈʃʊɡər/', 'açúcar'],
  salt: ['noun', '/sɔːlt/', 'sal'],
  pepper: ['noun', '/ˈpɛpər/', 'pimenta; pimentão'],
  oil: ['noun', '/ɔɪl/', 'óleo, azeite'],
  soup: ['noun', '/suːp/', 'sopa'],
  sandwich: ['noun', '/ˈsænwɪtʃ/', 'sanduíche'],
  breakfast: ['noun', '/ˈbrɛkfəst/', 'café da manhã'],
  lunch: ['noun', '/lʌntʃ/', 'almoço'],
  snack: ['noun', '/snæk/', 'lanche'],
  // frutas e legumes
  apple: ['noun', '/ˈæpəl/', 'maçã'],
  banana: ['noun', '/bəˈnænə/', 'banana'],
  grapes: ['noun', '/ɡreɪps/', 'uvas'],
  strawberry: ['noun', '/ˈstrɔːbɛri/', 'morango'],
  lemon: ['noun', '/ˈlɛmən/', 'limão-siciliano'],
  lime: ['noun', '/laɪm/', 'limão (taiti)'],
  pineapple: ['noun', '/ˈpaɪnæpəl/', 'abacaxi'],
  watermelon: ['noun', '/ˈwɔːtərmɛlən/', 'melancia'],
  mango: ['noun', '/ˈmæŋɡoʊ/', 'manga'],
  avocado: ['noun', '/ˌævəˈkɑːdoʊ/', 'abacate'],
  tomato: ['noun', '/təˈmeɪtoʊ/', 'tomate'],
  potato: ['noun', '/pəˈteɪtoʊ/', 'batata'],
  onion: ['noun', '/ˈʌnjən/', 'cebola'],
  garlic: ['noun', '/ˈɡɑːrlɪk/', 'alho'],
  carrot: ['noun', '/ˈkærət/', 'cenoura'],
  lettuce: ['noun', '/ˈlɛtɪs/', 'alface'],
  corn: ['noun', '/kɔːrn/', 'milho'],
  mushrooms: ['noun', '/ˈmʌʃruːmz/', 'cogumelos'],
  vegetables: ['noun', '/ˈvɛdʒtəbəlz/', 'legumes, verduras'],
  fruit: ['noun', '/fruːt/', 'fruta'],
  // bebidas e sabores
  juice: ['noun', '/dʒuːs/', 'suco'],
  tea: ['noun', '/tiː/', 'chá'],
  beer: ['noun', '/bɪr/', 'cerveja'],
  soda: ['noun', '/ˈsoʊdə/', 'refrigerante'],
  ice: ['noun', '/aɪs/', 'gelo'],
  sweet: ['adjective', '/swiːt/', 'doce'],
  salty: ['adjective', '/ˈsɔːlti/', 'salgado'],
  sour: ['adjective', '/ˈsaʊər/', 'azedo'],
  bitter: ['adjective', '/ˈbɪtər/', 'amargo'],
  spicy: ['adjective', '/ˈspaɪsi/', 'apimentado, picante'],
  tasty: ['adjective', '/ˈteɪsti/', 'saboroso'],
  hungry: ['adjective', '/ˈhʌŋɡri/', 'com fome'],
  thirsty: ['adjective', '/ˈθɜːrsti/', 'com sede'],
  empty: ['adjective', '/ˈɛmpti/', 'vazio'],
  cup: ['noun', '/kʌp/', 'xícara'],
  plate: ['noun', '/pleɪt/', 'prato'],
  fork: ['noun', '/fɔːrk/', 'garfo'],
  knife: ['noun', '/naɪf/', 'faca'],
  spoon: ['noun', '/spuːn/', 'colher'],
};

const w = (text, pt, example, note = null) => ({ kind: 'word', text, pt, example, note });

export const COURSES = [
  {
    id: 'course-1000-words-a1',
    slug: '1000-essential-words',
    title: '1000 Palavras Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 2,
    order: 11,
    short: 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.',
    long: 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.',
    lessons: [
      {
        id: 'lesson-1000-words-a1-11',
        chapter: 11,
        title: 'Comida básica e refeições',
        description: 'O que se come no dia a dia e as refeições do dia.',
        units: [
          w('breakfast', 'café da manhã', ['I have breakfast at seven.', 'Tomo café da manhã às sete.'], '"Have breakfast/lunch/dinner" = tomar café, almoçar, jantar.'),
          w('lunch', 'almoço', ["Let's have lunch together.", 'Vamos almoçar juntos.']),
          w('dinner', 'jantar', ['Dinner is ready.', 'O jantar está pronto.']),
          w('snack', 'lanche', ['I need a snack.', 'Preciso de um lanche.']),
          w('bread', 'pão', ['I buy fresh bread every day.', 'Compro pão fresco todo dia.'], 'Incontável: "some bread", "a loaf of bread" (um pão inteiro).'),
          w('rice', 'arroz', ['Rice and beans, please.', 'Arroz e feijão, por favor.'], 'Incontável: "rice is".'),
          w('beans', 'feijão', ['Brazilians eat a lot of beans.', 'Brasileiros comem muito feijão.'], 'Plural em inglês: "beans are".'),
          w('egg', 'ovo', ['I want two fried eggs.', 'Quero dois ovos fritos.']),
          w('meat', 'carne', ["I don't eat meat.", 'Eu não como carne.']),
          w('beef', 'carne de boi', ['The beef is very tender.', 'A carne está muito macia.'], 'O animal é "cow"; a carne é "beef". Porco: "pig" / "pork".'),
          w('chicken', 'frango', ['Grilled chicken with salad.', 'Frango grelhado com salada.']),
          w('fish', 'peixe', ['The fish is fresh today.', 'O peixe está fresco hoje.'], 'Plural geralmente igual: "two fish".'),
          w('cheese', 'queijo', ['A cheese sandwich, please.', 'Um sanduíche de queijo, por favor.']),
          w('butter', 'manteiga', ['Bread and butter.', 'Pão com manteiga.']),
          w('sugar', 'açúcar', ['No sugar, thanks.', 'Sem açúcar, obrigado.'], 'O "s" soa "sh": /ˈʃʊɡər/.'),
          w('salt', 'sal', ['Can you pass the salt?', 'Pode passar o sal?']),
          w('pepper', 'pimenta', ['Salt and pepper.', 'Sal e pimenta.'], '"Bell pepper" = pimentão.'),
          w('oil', 'óleo, azeite', ['Olive oil, please.', 'Azeite, por favor.'], 'Azeite de oliva = "olive oil".'),
          w('soup', 'sopa', ['The soup is too hot.', 'A sopa está quente demais.']),
          w('sandwich', 'sanduíche', ['I made a sandwich.', 'Fiz um sanduíche.'], 'O "d" some na fala: /ˈsænwɪtʃ/.'),
        ],
      },
      {
        id: 'lesson-1000-words-a1-12',
        chapter: 12,
        title: 'Frutas, legumes e verduras',
        description: 'Feira, mercado e salada.',
        units: [
          w('fruit', 'fruta', ['I eat fruit every day.', 'Como fruta todo dia.'], 'Geralmente incontável: "some fruit".'),
          w('vegetables', 'legumes, verduras', ['Eat your vegetables.', 'Coma seus legumes.'], 'Pronúncia com 3 sílabas: VEJ-tuh-buls.'),
          w('apple', 'maçã', ['An apple a day.', 'Uma maçã por dia.'], 'Começa com vogal: "an apple".'),
          w('banana', 'banana', ['Bananas are cheap here.', 'Banana é barata aqui.']),
          w('orange', 'laranja', ['Fresh orange juice.', 'Suco de laranja natural.']),
          w('grapes', 'uvas', ['A bunch of grapes.', 'Um cacho de uvas.']),
          w('strawberry', 'morango', ['Strawberry ice cream.', 'Sorvete de morango.']),
          w('lemon', 'limão-siciliano', ['Tea with lemon.', 'Chá com limão.'], 'O limão verde comum no Brasil é "lime".'),
          w('lime', 'limão (taiti)', ['Add some lime juice.', 'Coloque um pouco de suco de limão.']),
          w('pineapple', 'abacaxi', ['Pineapple on pizza?', 'Abacaxi na pizza?']),
          w('watermelon', 'melancia', ['Watermelon is perfect in summer.', 'Melancia é perfeita no verão.']),
          w('mango', 'manga', ['This mango is sweet.', 'Esta manga está doce.']),
          w('avocado', 'abacate', ['Avocado toast.', 'Torrada com abacate.'], 'Nos EUA abacate é salgado: guacamole, torrada.'),
          w('tomato', 'tomate', ['Tomato sauce.', 'Molho de tomate.'], 'Plural: "tomatoes".'),
          w('potato', 'batata', ['Mashed potatoes.', 'Purê de batata.'], 'Plural: "potatoes".'),
          w('onion', 'cebola', ['No onions, please.', 'Sem cebola, por favor.']),
          w('garlic', 'alho', ['Garlic bread.', 'Pão de alho.']),
          w('carrot', 'cenoura', ['Carrot cake.', 'Bolo de cenoura.']),
          w('lettuce', 'alface', ['Lettuce and tomato salad.', 'Salada de alface e tomate.'], 'Pronúncia /ˈlɛtɪs/, não "let-uce".'),
          w('corn', 'milho', ['Corn on the cob.', 'Milho na espiga.'], '"Popcorn" = pipoca.'),
        ],
      },
      {
        id: 'lesson-1000-words-a1-13',
        chapter: 13,
        title: 'Bebidas, sabores e mesa',
        description: 'Beber, descrever o sabor e os talheres.',
        units: [
          w('water', 'água', ['A glass of water, please.', 'Um copo de água, por favor.']),
          w('juice', 'suco', ['Orange juice, no ice.', 'Suco de laranja, sem gelo.']),
          w('coffee', 'café', ['I drink coffee every morning.', 'Tomo café toda manhã.']),
          w('tea', 'chá', ['Green tea, please.', 'Chá verde, por favor.']),
          w('milk', 'leite', ['Coffee with milk.', 'Café com leite.']),
          w('beer', 'cerveja', ['A cold beer, please.', 'Uma cerveja gelada, por favor.']),
          w('soda', 'refrigerante', ['Do you have soda?', 'Vocês têm refrigerante?'], 'Nos EUA varia por região: soda, pop, coke.'),
          w('ice', 'gelo', ['No ice, please.', 'Sem gelo, por favor.']),
          w('hungry', 'com fome', ["I'm hungry.", 'Estou com fome.'], 'Inglês usa "to be": "I am hungry", não "I have hunger".'),
          w('thirsty', 'com sede', ["I'm thirsty.", 'Estou com sede.']),
          w('sweet', 'doce', ['This cake is too sweet.', 'Este bolo está doce demais.']),
          w('salty', 'salgado', ['The fries are salty.', 'As batatas estão salgadas.']),
          w('sour', 'azedo', ['The milk is sour.', 'O leite está azedo.']),
          w('bitter', 'amargo', ['Black coffee is bitter.', 'Café puro é amargo.']),
          w('spicy', 'apimentado', ['Is it spicy?', 'É apimentado?'], '"Hot" também significa picante: "hot sauce".'),
          w('delicious', 'delicioso', ['The food was delicious.', 'A comida estava deliciosa.']),
          w('cup', 'xícara', ['A cup of coffee.', 'Uma xícara de café.'], '"Cup" = xícara; "glass" = copo de vidro; "mug" = caneca.'),
          w('plate', 'prato', ['Can I have another plate?', 'Pode me dar outro prato?'], '"Plate" = o objeto; "dish" = o prato de comida.'),
          w('fork', 'garfo', ['I need a fork.', 'Preciso de um garfo.']),
          w('knife', 'faca', ['This knife is sharp.', 'Esta faca está afiada.'], 'O "k" é mudo: /naɪf/. Plural: "knives".'),
        ],
      },
    ],
  },
];
