// Lote paragrafos-1: curso novo "Parágrafos" (B2, trilha Fluência). Dez tipos de
// texto (apresentação, rotina, cidade, viagem, opinião, e-mail formal, resenha,
// processo, comparação, planos), com quatro parágrafos cada: abertura,
// desenvolvimento, detalhe e fechamento. A nota aponta a função do parágrafo e
// os conectores. Conteúdo original.

export const LEXICON = {
  buying: ["verb", "/ˈbaɪɪŋ/", "comprando, comprar"],
  costa: ["proper noun", "/ˈkɑːstə/", "Costa"],
  daniel: ["proper noun", "/ˈdænjəl/", "Daniel"],
  madam: ["noun", "/ˈmædəm/", "senhora"],
  overall: ["adverb", "/ˌoʊvərˈɔːl/", "no geral"],
  portugal: ["proper noun", "/ˈpɔːrtʃəɡəl/", "Portugal"],
  renting: ["verb", "/ˈrɛntɪŋ/", "alugando, alugar"],
  sir: ["noun", "/sɜːr/", "senhor"],
  acting: ["noun", "/ˈæktɪŋ/", "atuação"],
  allow: ["verb", "/əˈlaʊ/", "permitir"],
  amount: ["noun", "/əˈmaʊnt/", "valor, quantia"],
  apartments: ["noun", "/əˈpɑːrtmənts/", "apartamentos"],
  bottom: ["noun", "/ˈbɑːtəm/", "fundo"],
  shops: ["noun", "/ʃɑːps/", "lojas"],
  coast: ["noun", "/koʊst/", "litoral"],
  complain: ["verb", "/kəmˈpleɪn/", "reclamar"],
  conclusion: ["noun", "/kənˈkluːʒən/", "conclusão"],
  contrast: ["noun", "/ˈkɑːntræst/", "contraste"],
  course: ["noun", "/kɔːrs/", "curso (of course = claro)"],
  criticism: ["noun", "/ˈkrɪtɪsɪzəm/", "crítica"],
  dialogue: ["noun", "/ˈdaɪəlɔːɡ/", "diálogo"],
  dough: ["noun", "/doʊ/", "massa"],
  easier: ["adjective", "/ˈiːziər/", "mais fácil"],
  energy: ["noun", "/ˈɛnərdʒi/", "energia"],
  especially: ["adverb", "/ɪˈspɛʃəli/", "especialmente"],
  families: ["noun", "/ˈfæməliz/", "famílias"],
  farmer: ["noun", "/ˈfɑːrmər/", "fazendeiro"],
  feels: ["verb", "/fiːlz/", "parece, sente"],
  film: ["noun", "/fɪlm/", "filme"],
  flexible: ["adjective", "/ˈflɛksəbəl/", "flexível"],
  flour: ["noun", "/ˈflaʊər/", "farinha"],
  gives: ["verb", "/ɡɪvz/", "dá"],
  grilled: ["adjective", "/ɡrɪld/", "grelhado"],
  harder: ["adjective", "/ˈhɑːrdər/", "mais difícil"],
  helping: ["verb", "/ˈhɛlpɪŋ/", "ajudando"],
  hollow: ["adjective", "/ˈhɑːloʊ/", "oco"],
  houses: ["noun", "/ˈhaʊzɪz/", "casas"],
  ingredients: ["noun", "/ɪnˈɡriːdiənts/", "ingredientes"],
  interviews: ["noun", "/ˈɪntərvjuːz/", "entrevistas"],
  items: ["noun", "/ˈaɪtəmz/", "itens"],
  life: ["noun", "/laɪf/", "vida"],
  mechanic: ["noun", "/məˈkænɪk/", "mecânico"],
  "medium-sized": ["adjective", "/ˈmiːdiəm saɪzd/", "de tamanho médio"],
  meetings: ["noun", "/ˈmiːtɪŋz/", "reuniões"],
  mix: ["verb", "/mɪks/", "misturar"],
  monthly: ["adjective", "/ˈmʌnθli/", "mensal"],
  mountains: ["noun", "/ˈmaʊntənz/", "montanhas"],
  natural: ["adjective", "/ˈnætʃərəl/", "natural"],
  nowhere: ["adverb", "/ˈnoʊwɛr/", "lugar nenhum"],
  ones: ["pronoun", "/wʌnz/", "os, aqueles"],
  parks: ["noun", "/pɑːrks/", "parques"],
  part: ["noun", "/pɑːrt/", "parte"],
  paying: ["verb", "/ˈpeɪɪŋ/", "pagando"],
  perfect: ["adjective", "/ˈpɜːrfɪkt/", "perfeito"],
  personal: ["adjective", "/ˈpɜːrsənəl/", "pessoal"],
  placed: ["verb", "/pleɪst/", "fez (pedido), colocou"],
  planning: ["verb", "/ˈplænɪŋ/", "planejando"],
  pleasant: ["adjective", "/ˈplɛzənt/", "agradável"],
  podcasts: ["noun", "/ˈpɑːdkæsts/", "podcasts"],
  positive: ["adjective", "/ˈpɑːzətɪv/", "positivo"],
  probably: ["adverb", "/ˈprɑːbəbli/", "provavelmente"],
  real: ["adjective", "/ˈriːəl/", "real"],
  relax: ["verb", "/rɪˈlæks/", "relaxar"],
  rented: ["verb", "/ˈrɛntɪd/", "alugou"],
  replacement: ["noun", "/rɪˈpleɪsmənt/", "substituto"],
  safer: ["adjective", "/ˈseɪfər/", "mais seguro"],
  scenes: ["noun", "/siːnz/", "cenas"],
  scheduled: ["adjective", "/ˈskɛdʒuːld/", "marcado, agendado"],
  selling: ["verb", "/ˈsɛlɪŋ/", "vendendo"],
  shorter: ["adjective", "/ˈʃɔːrtər/", "mais curto"],
  signal: ["noun", "/ˈsɪɡnəl/", "sinal"],
  simple: ["adjective", "/ˈsɪmpəl/", "simples"],
  somewhere: ["adverb", "/ˈsʌmwɛr/", "em algum lugar"],
  stability: ["noun", "/stəˈbɪləti/", "estabilidade"],
  stars: ["noun", "/stɑːrz/", "estrelas"],
  streets: ["noun", "/striːts/", "ruas"],
  them: ["pronoun", "/ðɛm/", "eles, os"],
  transport: ["noun", "/ˈtrænspɔːrt/", "transporte"],
  traveled: ["verb", "/ˈtrævəld/", "viajou"],
  village: ["noun", "/ˈvɪlɪdʒ/", "vilarejo"],
  workers: ["noun", "/ˈwɜːrkərz/", "trabalhadores"],
  yeast: ["noun", "/jiːst/", "fermento"],
};

const pg = (text, pt, note) => ({ kind: 'paragraph', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-paragraphs-b2-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-paragraphs-b2',
    slug: 'paragraphs-b2',
    title: 'Parágrafos',
    level: 'B2',
    category: 'writing',
    track: 'fluencia',
    trackOrder: 3,
    order: 18,
    short: 'Textos completos parágrafo por parágrafo: você ouve e escreve um texto inteiro com começo, meio e fim.',
    long: 'Dez tipos de texto do dia a dia (apresentação, rotina, cidade, viagem, opinião, e-mail formal, resenha, processo, comparação e planos), cada um em quatro parágrafos. A nota explica a função do parágrafo e os conectores que dão fluidez ao texto.',
    lessons: [
      lesson(1, 'Apresentação pessoal', 'Falar de si em um texto curto.', [
        pg('My name is Julia, and I am a nurse from the south of Brazil. I have worked in the same hospital for six years.', 'Meu nome é Julia e sou enfermeira do sul do Brasil. Trabalho no mesmo hospital há seis anos.', 'Abertura: quem você é e há quanto tempo. Present perfect com "for" para duração.'),
        pg('I chose this job because I like helping people. The hours are long, but I learn something new every day.', 'Escolhi esta profissão porque gosto de ajudar as pessoas. O horário é longo, mas aprendo algo novo todo dia.', 'Desenvolvimento: o motivo com "because" e um contraste com "but".'),
        pg('Outside work, I enjoy cooking and walking by the sea. On weekends, I usually visit my parents.', 'Fora do trabalho, gosto de cozinhar e de caminhar à beira-mar. Nos fins de semana, costumo visitar meus pais.', 'Detalhe pessoal: "enjoy" + -ing e advérbio de frequência antes do verbo.'),
        pg('I am learning English because I want to work abroad one day. My goal is to feel confident in any conversation.', 'Estou aprendendo inglês porque quero trabalhar no exterior um dia. Meu objetivo é me sentir confiante em qualquer conversa.', 'Fechamento: objetivo futuro. "Abroad" = no exterior, sem preposição.'),
      ]),
      lesson(2, 'Minha rotina', 'Descrever o dia com sequência.', [
        pg('My day starts at six, when my alarm goes off. First, I make coffee and check the weather.', 'Meu dia começa às seis, quando o despertador toca. Primeiro, faço café e vejo a previsão do tempo.', '"Go off" = tocar (alarme). "First" abre a sequência.'),
        pg('Then I take the train to work, which takes about forty minutes. I usually read or listen to podcasts on the way.', 'Depois pego o trem para o trabalho, o que leva uns quarenta minutos. Costumo ler ou ouvir podcasts no caminho.', '"Which" retoma a frase anterior. "Take" = pegar (transporte) e levar (tempo).'),
        pg('In the afternoon, I have meetings until five. After that, I go to the gym if I still have energy.', 'À tarde, tenho reuniões até as cinco. Depois disso, vou à academia se ainda tiver energia.', '"After that" continua a sequência. Condicional com presente.'),
        pg('Finally, I cook dinner and relax for an hour. I try to go to bed before eleven, but it does not always happen.', 'Por fim, faço o jantar e relaxo por uma hora. Tento dormir antes das onze, mas nem sempre acontece.', '"Finally" fecha a sequência. "Not always" = nem sempre.'),
      ]),
      lesson(3, 'Minha cidade', 'Descrever um lugar.', [
        pg('I live in a medium-sized city near the mountains. It is quiet during the week and busy on weekends.', 'Moro numa cidade de tamanho médio perto das montanhas. É tranquila durante a semana e movimentada nos fins de semana.', 'Abertura: onde fica e a impressão geral, com contraste de "quiet" e "busy".'),
        pg('The old town has narrow streets and colorful houses. There are small coffee shops on almost every corner.', 'O centro histórico tem ruas estreitas e casas coloridas. Há pequenos cafés em quase toda esquina.', 'Descrição com "there are". Adjetivos antes do substantivo.'),
        pg('However, public transport is not very good. Most people need a car to get around.', 'No entanto, o transporte público não é muito bom. A maioria das pessoas precisa de carro para se locomover.', '"However" introduz o lado negativo. "Get around" = locomover-se.'),
        pg('Overall, it is a pleasant place to live. I would recommend a visit in the spring, when the parks are full of flowers.', 'No geral, é um lugar agradável para morar. Eu recomendaria uma visita na primavera, quando os parques estão cheios de flores.', '"Overall" = no geral, conclusão. "Would recommend" = recomendação educada.'),
      ]),
      lesson(4, 'Uma viagem', 'Narrar no passado.', [
        pg('Last summer, my friends and I traveled to the coast of Portugal. We rented a small car and drove from town to town.', 'No verão passado, eu e meus amigos viajamos para o litoral de Portugal. Alugamos um carro pequeno e fomos de cidade em cidade.', 'Abertura com marcador de tempo. Passado simples para a sequência.'),
        pg('On the second day, the car broke down in the middle of nowhere. We had no signal, so we walked to the nearest village.', 'No segundo dia, o carro quebrou no meio do nada. Estávamos sem sinal, então andamos até o vilarejo mais próximo.', '"Break down" = quebrar (veículo). "In the middle of nowhere" = no meio do nada.'),
        pg('A farmer helped us and even invited us for lunch. We ate fresh bread and grilled fish while we waited for the mechanic.', 'Um fazendeiro nos ajudou e até nos convidou para almoçar. Comemos pão fresco e peixe grelhado enquanto esperávamos o mecânico.', '"Even" = até (surpresa). "While" liga duas ações simultâneas.'),
        pg('Looking back, that problem became the best part of the trip. Sometimes the plans that fail are the ones we remember.', 'Olhando para trás, aquele problema virou a melhor parte da viagem. Às vezes, os planos que dão errado são os que lembramos.', '"Looking back" = em retrospecto. Fechamento com reflexão.'),
      ]),
      lesson(5, 'Texto de opinião', 'Defender um ponto de vista.', [
        pg('Many companies now allow people to work from home. In my opinion, this is a positive change for most workers.', 'Muitas empresas agora permitem que as pessoas trabalhem de casa. Na minha opinião, é uma mudança positiva para a maioria dos trabalhadores.', 'Abertura: contexto e tese. "Allow someone to" + verbo.'),
        pg('First of all, people save time and money on transport. They can use those hours to rest or to be with their families.', 'Em primeiro lugar, as pessoas economizam tempo e dinheiro com transporte. Podem usar essas horas para descansar ou ficar com a família.', '"First of all" apresenta o primeiro argumento.'),
        pg('On the other hand, some people feel lonely at home. It can also be harder to separate work from personal life.', 'Por outro lado, algumas pessoas se sentem sozinhas em casa. Também pode ser mais difícil separar trabalho e vida pessoal.', '"On the other hand" apresenta o contra-argumento.'),
        pg('In conclusion, I believe the best option is a mix of both. Companies should let employees choose what works for them.', 'Em conclusão, acredito que a melhor opção é uma mistura dos dois. As empresas deveriam deixar os funcionários escolherem o que funciona para eles.', '"In conclusion" fecha. "Let someone" + verbo sem "to".'),
      ]),
      lesson(6, 'E-mail formal', 'Escrever para uma empresa.', [
        pg('Dear Sir or Madam, I am writing to complain about an order I placed on your website last month.', 'Prezados, escrevo para reclamar de um pedido que fiz no site de vocês no mês passado.', '"Dear Sir or Madam" quando não se sabe o nome. "I am writing to" abre e-mails formais.'),
        pg('The package arrived two weeks late, and one of the items was damaged. I have attached photos of the box and the product.', 'O pacote chegou com duas semanas de atraso, e um dos itens estava danificado. Anexei fotos da caixa e do produto.', 'Fatos objetivos, sem emoção. "Attach" = anexar.'),
        pg('I would appreciate it if you could send a replacement or refund the full amount.', 'Eu agradeceria se vocês pudessem enviar um substituto ou reembolsar o valor total.', '"I would appreciate it if you could" = pedido formal e educado.'),
        pg('I look forward to hearing from you soon. Kind regards, Daniel Costa.', 'Aguardo seu retorno em breve. Atenciosamente, Daniel Costa.', '"I look forward to" + -ing. "Kind regards" = atenciosamente.'),
      ]),
      lesson(7, 'Resenha', 'Avaliar um filme ou livro.', [
        pg('Last night I watched a film about a family that runs a small bakery. It is simple, but it stayed with me for hours.', 'Ontem à noite assisti a um filme sobre uma família que tem uma padaria pequena. É simples, mas ficou comigo por horas.', 'Abertura: o que é e a impressão geral. "Stay with me" = não sair da cabeça.'),
        pg('The acting is natural, especially from the two children. The dialogue feels real, as if you were listening to your neighbors.', 'As atuações são naturais, especialmente das duas crianças. Os diálogos parecem reais, como se você estivesse ouvindo seus vizinhos.', 'Ponto positivo. "As if" + passado = como se.'),
        pg('My only criticism is that the middle part is a little slow. Some scenes could have been shorter.', 'Minha única crítica é que a parte do meio é um pouco lenta. Algumas cenas poderiam ter sido mais curtas.', 'Ponto negativo suave. "Could have been" = poderia ter sido.'),
        pg('Overall, I would give it four stars out of five. It is perfect for a quiet evening at home.', 'No geral, eu daria quatro estrelas de cinco. É perfeito para uma noite tranquila em casa.', 'Nota final com "out of" = de (num total).'),
      ]),
      lesson(8, 'Descrever um processo', 'Explicar passo a passo.', [
        pg('Making good bread at home is easier than most people think. You only need flour, water, salt and yeast.', 'Fazer um bom pão em casa é mais fácil do que a maioria pensa. Você só precisa de farinha, água, sal e fermento.', 'Abertura com comparativo "easier than". Lista de ingredientes.'),
        pg('First, mix the ingredients in a large bowl until the dough comes together. Then cover it and let it rest for an hour.', 'Primeiro, misture os ingredientes numa tigela grande até a massa ficar homogênea. Depois cubra e deixe descansar por uma hora.', 'Imperativo para instruções. "Let it rest" = deixe descansar.'),
        pg('Once the dough has doubled in size, shape it into a ball. Bake it in a hot oven for about forty minutes.', 'Assim que a massa dobrar de tamanho, modele em forma de bola. Asse em forno quente por uns quarenta minutos.', '"Once" = assim que. Present perfect depois de "once" para ação concluída.'),
        pg('The bread is ready when it sounds hollow if you tap the bottom. Let it cool before you cut it.', 'O pão está pronto quando soa oco ao bater no fundo. Deixe esfriar antes de cortar.', 'Fechamento: como saber que terminou. "Before you" + presente.'),
      ]),
      lesson(9, 'Comparar opções', 'Prós e contras.', [
        pg('When people move to a new city, they often have to choose between renting and buying a home.', 'Quando as pessoas se mudam para uma cidade nova, muitas vezes têm que escolher entre alugar e comprar uma casa.', 'Abertura: apresenta as duas opções com "between… and".'),
        pg('Renting is more flexible. If you get a job somewhere else, you can leave without selling anything.', 'Alugar é mais flexível. Se você arranja emprego em outro lugar, pode ir embora sem vender nada.', 'Vantagem da primeira opção. Comparativo com "more".'),
        pg('Buying, by contrast, gives you stability. Although the monthly cost may be higher at first, you are paying for something that is yours.', 'Comprar, por outro lado, dá estabilidade. Embora o custo mensal possa ser mais alto no início, você está pagando por algo que é seu.', '"By contrast" = em contraste. "Although" introduz a concessão.'),
        pg('In the end, the right choice depends on your plans. If you are not sure where you will be in five years, renting is probably safer.', 'No fim, a escolha certa depende dos seus planos. Se você não sabe onde estará daqui a cinco anos, alugar provavelmente é mais seguro.', '"Depends on" + substantivo. Conclusão com recomendação condicional.'),
      ]),
      lesson(10, 'Planos para o futuro', 'Falar do que vem pela frente.', [
        pg('Next year is going to be a big year for me. I am planning to change jobs and move to a new city.', 'O ano que vem vai ser um ano importante para mim. Estou planejando mudar de emprego e de cidade.', '"Going to" para planos já decididos.'),
        pg('I have already started saving money and looking for apartments. By December, I hope to have a few interviews scheduled.', 'Já comecei a economizar e procurar apartamentos. Até dezembro, espero ter algumas entrevistas marcadas.', '"Already" com present perfect. "By" + data = até.'),
        pg('Of course, I am a little nervous. Leaving my friends will not be easy, and everything will be new.', 'Claro, estou um pouco nervoso. Deixar meus amigos não vai ser fácil, e tudo vai ser novo.', '"Will" para previsões. Gerúndio como sujeito: "Leaving my friends".'),
        pg('Still, I feel ready for the change. Whatever happens, I know I will learn a lot about myself.', 'Mesmo assim, me sinto pronto para a mudança. Aconteça o que acontecer, sei que vou aprender muito sobre mim mesmo.', '"Still" no início = mesmo assim. "Whatever happens" = aconteça o que acontecer.'),
      ]),
    ],
  },
];
