// Lote paragrafos-2: curso "Parágrafos" (B2), parágrafos 5 a 8 de cada um dos 10 textos
// (de 4 para 8 por capítulo, fatia 2 do plano #505). Cada texto continua com mais
// detalhes, contraste, exemplo e um segundo fechamento. Os capítulos e os parágrafos 1–4
// não mudam: o lote reaproveita os metadados do paragrafos-1 e usa unitOffset 4.
// Conteúdo original.

import { COURSES as BASE } from './paragrafos-1.mjs';

export const LEXICON = {
  adjust: ["verb", "/əˈdʒʌst/", "ajustar"],
  advantage: ["noun", "/ədˈvæntɪdʒ/", "vantagem"],
  agent: ["noun", "/ˈeɪdʒənt/", "atendente, agente"],
  bakeries: ["noun", "/ˈbeɪkəriz/", "padarias"],
  beginning: ["noun", "/bɪˈɡɪnɪŋ/", "começo"],
  builders: ["noun", "/ˈbɪldərz/", "pedreiros, construtores"],
  certain: ["adjective", "/ˈsɜːrtən/", "certo, seguro"],
  character: ["noun", "/ˈkærɪktər/", "caráter, personalidade"],
  climbed: ["verb", "/klaɪmd/", "subiu"],
  consumer: ["noun", "/kənˈsuːmər/", "consumidor"],
  contacted: ["verb", "/ˈkɑːntæktɪd/", "entrou em contato"],
  couple: ["noun", "/ˈkʌpəl/", "casal"],
  crust: ["noun", "/krʌst/", "casca (do pão)"],
  decisions: ["noun", "/dɪˈsɪʒənz/", "decisões"],
  deserves: ["verb", "/dɪˈzɜːrvz/", "merece"],
  directly: ["adverb", "/dəˈrɛktli/", "diretamente"],
  emotion: ["noun", "/ɪˈmoʊʃən/", "emoção"],
  emotional: ["adjective", "/ɪˈmoʊʃənəl/", "emocional"],
  enjoys: ["verb", "/ɪnˈdʒɔɪz/", "gosta, aproveita"],
  fastest: ["adjective", "/ˈfæstɪst/", "o mais rápido"],
  festival: ["noun", "/ˈfɛstəvəl/", "festival"],
  fishing: ["noun", "/ˈfɪʃɪŋ/", "pesca"],
  follows: ["verb", "/ˈfɑːloʊz/", "acompanha, segue"],
  freedom: ["noun", "/ˈfriːdəm/", "liberdade"],
  freezes: ["verb", "/ˈfriːzɪz/", "congela"],
  golden: ["adjective", "/ˈɡoʊldən/", "dourado"],
  guesthouse: ["noun", "/ˈɡɛsthaʊs/", "pousada"],
  helps: ["verb", "/hɛlps/", "ajuda"],
  herbs: ["noun", "/ɜːrbz/", "ervas"],
  hill: ["noun", "/hɪl/", "colina"],
  hosts: ["verb", "/hoʊsts/", "recebe, sedia"],
  hotels: ["noun", "/hoʊˈtɛlz/", "hotéis"],
  human: ["adjective", "/ˈhjuːmən/", "humano"],
  incredible: ["adjective", "/ɪnˈkrɛdəbəl/", "incrível"],
  interest: ["noun", "/ˈɪntrəst/", "juros, interesse"],
  join: ["verb", "/dʒɔɪn/", "entrar, participar"],
  knowing: ["verb", "/ˈnoʊɪŋ/", "saber, conhecer"],
  lasts: ["verb", "/læsts/", "dura"],
  lit: ["adjective", "/lɪt/", "iluminado"],
  loaf: ["noun", "/loʊf/", "pão (unidade)"],
  loan: ["noun", "/loʊn/", "financiamento, empréstimo"],
  losing: ["verb", "/ˈluːzɪŋ/", "perdendo"],
  maintenance: ["noun", "/ˈmeɪntənəns/", "manutenção"],
  managers: ["noun", "/ˈmænɪdʒərz/", "gerentes"],
  matters: ["verb", "/ˈmætərz/", "importa"],
  mention: ["noun", "/ˈmɛnʃən/", "menção"],
  organize: ["verb", "/ˈɔːrɡənaɪz/", "organizar"],
  others: ["pronoun", "/ˈʌðərz/", "outros"],
  owner: ["noun", "/ˈoʊnər/", "dono"],
  owners: ["noun", "/ˈoʊnərz/", "donos, proprietários"],
  owning: ["verb", "/ˈoʊnɪŋ/", "possuir, ter"],
  pale: ["adjective", "/peɪl/", "claro, pálido"],
  peace: ["noun", "/piːs/", "paz"],
  photography: ["noun", "/fəˈtɑːɡrəfi/", "fotografia"],
  physically: ["adverb", "/ˈfɪzɪkli/", "fisicamente"],
  present: ["adjective", "/ˈprɛzənt/", "presente"],
  printed: ["verb", "/ˈprɪntɪd/", "imprimiu"],
  productive: ["adjective", "/prəˈdʌktɪv/", "produtivo"],
  promised: ["verb", "/ˈprɑːmɪst/", "prometeu"],
  protect: ["verb", "/prəˈtɛkt/", "proteger"],
  protection: ["noun", "/prəˈtɛkʃən/", "proteção, defesa"],
  receive: ["verb", "/rɪˈsiːv/", "receber"],
  recent: ["adjective", "/ˈriːsənt/", "recente"],
  remind: ["verb", "/rɪˈmaɪnd/", "lembrar"],
  repairs: ["noun", "/rɪˈpɛrz/", "reparos"],
  residents: ["noun", "/ˈrɛzɪdənts/", "moradores"],
  restaurants: ["noun", "/ˈrɛstərɑːnts/", "restaurantes"],
  routine: ["noun", "/ruːˈtiːn/", "rotina"],
  satisfied: ["adjective", "/ˈsætɪsfaɪd/", "satisfeito"],
  schedules: ["noun", "/ˈskɛdʒuːlz/", "horários"],
  seeds: ["noun", "/siːdz/", "sementes"],
  side: ["noun", "/saɪd/", "lado"],
  slice: ["verb", "/slaɪs/", "fatiar"],
  special: ["adjective", "/ˈspɛʃəl/", "especial"],
  steam: ["noun", "/stiːm/", "vapor"],
  stories: ["noun", "/ˈstɔːriz/", "histórias"],
  stressful: ["adjective", "/ˈstrɛsfəl/", "estressante"],
  suitable: ["adjective", "/ˈsuːtəbəl/", "adequado"],
  sunrise: ["noun", "/ˈsʌnraɪz/", "nascer do sol"],
  supports: ["verb", "/səˈpɔːrts/", "apoia"],
  teachers: ["noun", "/ˈtiːtʃərz/", "professores"],
  teams: ["noun", "/tiːmz/", "equipes"],
  thousands: ["noun", "/ˈθaʊzəndz/", "milhares"],
  tourists: ["noun", "/ˈtʊrɪsts/", "turistas"],
  truly: ["adverb", "/ˈtruːli/", "realmente"],
  useful: ["adjective", "/ˈjuːsfəl/", "útil"],
  views: ["noun", "/vjuːz/", "paisagens, vistas"],
  watching: ["verb", "/ˈwɑːtʃɪŋ/", "olhando, assistindo"],
  whichever: ["determiner", "/wɪˈtʃɛvər/", "qualquer que seja"],
};

const pg = (text, pt, note) => ({ kind: 'paragraph', text, pt, note });
const more = (n, units) => ({ ...BASE[0].lessons[n - 1], unitOffset: 4, units });

export const COURSES = [
  {
    ...BASE[0],
    lessons: [
      more(1, [
        pg('My family is not very big, but we are close. My brother lives in the same city, so we meet for dinner every Sunday.', 'Minha família não é muito grande, mas somos próximos. Meu irmão mora na mesma cidade, então nos encontramos para jantar todo domingo.', 'Detalhe sobre a família: "but" contrasta e "so" mostra consequência.'),
        pg('Last year, I took a course in emergency care. It was difficult, but it helped me feel more prepared at work.', 'No ano passado, fiz um curso de atendimento de emergência. Foi difícil, mas me ajudou a me sentir mais preparada no trabalho.', 'Passado simples para um fato concluído. "Feel more prepared" = comparativo com adjetivo longo.'),
        pg('If I could change one thing, I would have more time to travel. I have never been outside Brazil, and that is my biggest dream.', 'Se eu pudesse mudar uma coisa, teria mais tempo para viajar. Nunca saí do Brasil, e esse é meu maior sonho.', 'Segunda condicional (if + passado, would) e present perfect com "never".'),
        pg('So, that is a little about me. I hope we can talk more soon, and I would love to hear about you too.', 'Então, isso é um pouco sobre mim. Espero que a gente converse mais em breve, e eu adoraria saber de você também.', 'Segundo fechamento: devolve a palavra ao leitor com "I would love to".'),
      ]),
      more(2, [
        pg('On Saturdays, my routine is completely different. I sleep late, and I do not look at my phone until noon.', 'Aos sábados, minha rotina é completamente diferente. Durmo até tarde e não olho o celular até o meio-dia.', 'Contraste com o dia de semana. "Until" marca o limite do tempo.'),
        pg('In the evening, I usually meet friends for dinner. We never plan much, but we always end up laughing.', 'À noite, geralmente encontro amigos para jantar. Nunca planejamos muito, mas sempre acabamos rindo.', '"End up" + -ing = acabar fazendo algo. Advérbios de frequência antes do verbo.'),
        pg('Of course, some days are harder than others. When work is stressful, I go for a short walk to clear my head.', 'Claro, alguns dias são mais difíceis que outros. Quando o trabalho está estressante, saio para uma caminhada curta para clarear a cabeça.', '"Clear my head" = espairecer. "When" abre uma situação habitual.'),
        pg('All in all, I like having a routine. It helps me use my time well, and it gives me energy for the things I enjoy.', 'No geral, gosto de ter uma rotina. Ela me ajuda a usar bem meu tempo e me dá energia para as coisas de que gosto.', '"All in all" fecha o texto. "Like having" = gostar de ter.'),
      ]),
      more(3, [
        pg('The food is another reason to visit. Local restaurants serve fresh fish, and the bakeries open before sunrise.', 'A comida é outro motivo para visitar. Os restaurantes locais servem peixe fresco, e as padarias abrem antes do nascer do sol.', '"Another reason" acrescenta um argumento à descrição.'),
        pg('In summer, the city hosts a music festival that lasts three days. Thousands of visitors come, so hotels fill up quickly.', 'No verão, a cidade recebe um festival de música que dura três dias. Milhares de visitantes vêm, então os hotéis lotam rapidamente.', '"That" abre uma oração relativa. "Fill up" = lotar.'),
        pg('Because of the tourists, prices have gone up in recent years. Some residents are worried that the old town is losing its character.', 'Por causa dos turistas, os preços subiram nos últimos anos. Alguns moradores temem que o centro histórico esteja perdendo o caráter.', '"Because of" + substantivo. Present perfect para mudança até agora.'),
        pg('Even so, I would not live anywhere else. The people are friendly, and the mountains are always there when I need peace.', 'Mesmo assim, eu não moraria em outro lugar. As pessoas são simpáticas, e as montanhas estão sempre lá quando preciso de paz.', '"Even so" retoma o lado positivo. "Would not live anywhere else" = escolha firme.'),
      ]),
      more(4, [
        pg('After the mechanic fixed the car, we continued along the coast. The roads were narrow, but the views were incredible.', 'Depois que o mecânico consertou o carro, seguimos pelo litoral. As estradas eram estreitas, mas as paisagens eram incríveis.', 'Sequência no passado com "after". Contraste com "but".'),
        pg('In a small fishing town, we stayed in a guesthouse run by an old couple. They told us stories about the sea every evening.', 'Numa pequena cidade de pescadores, ficamos numa pousada administrada por um casal de idosos. Eles nos contavam histórias do mar toda noite.', '"Run by" = administrada por (voz passiva reduzida). "Told us" + objeto indireto.'),
        pg('On the last day, we climbed a hill to watch the sunset. Nobody spoke for a while because it was so beautiful.', 'No último dia, subimos uma colina para ver o pôr do sol. Ninguém falou por um tempo porque era lindo demais.', '"To watch" = finalidade. "So + adjetivo" dá ênfase.'),
        pg('When we got home, we printed our favorite photos. I still keep one on my desk to remind me of that trip.', 'Quando chegamos em casa, imprimimos nossas fotos favoritas. Ainda guardo uma na minha mesa para me lembrar daquela viagem.', 'Fecha a narrativa voltando ao presente com "still". "Remind me of" = me lembrar de.'),
      ]),
      more(5, [
        pg('Another advantage is flexibility. Parents can adjust their schedules to pick up their children from school.', 'Outra vantagem é a flexibilidade. Pais podem ajustar seus horários para buscar os filhos na escola.', '"Another advantage" acrescenta um argumento. "Pick up" = buscar.'),
        pg('Some managers worry that teams work less when nobody is watching. However, studies show that many people are actually more productive at home.', 'Alguns gerentes temem que as equipes trabalhem menos quando ninguém está olhando. No entanto, estudos mostram que muitas pessoas são, na verdade, mais produtivas em casa.', 'Apresenta a objeção e a rebate com "however". "Actually" = na verdade.'),
        pg('Nevertheless, remote work is not suitable for every job. Doctors, teachers and builders, for example, must be physically present.', 'Mesmo assim, o trabalho remoto não serve para todas as profissões. Médicos, professores e pedreiros, por exemplo, precisam estar presentes.', '"Nevertheless" = ainda assim; mais formal que "but". "For example" no meio da frase.'),
        pg('To sum up, working from home is a useful option, not a solution for everyone. What matters most is that people have a real choice.', 'Resumindo, trabalhar de casa é uma opção útil, não uma solução para todos. O mais importante é que as pessoas tenham uma escolha real.', '"To sum up" fecha. "What matters most is" destaca a ideia final.'),
      ]),
      more(6, [
        pg('I first contacted your customer service team by phone on the third of the month. The agent promised to call me back, but nobody did.', 'Entrei em contato com o atendimento de vocês por telefone no dia três do mês. O atendente prometeu retornar, mas ninguém retornou.', 'Relata o histórico no passado. "Call back" = retornar a ligação.'),
        pg('This is the second time I have had a problem with your company. I have always been a satisfied customer, so I am disappointed.', 'Esta é a segunda vez que tenho um problema com a empresa de vocês. Sempre fui um cliente satisfeito, por isso estou decepcionado.', 'Present perfect para a experiência até agora. "So" liga causa e consequência.'),
        pg('If I do not receive an answer within seven days, I will have to contact a consumer protection office. I would prefer to solve this directly with you.', 'Se eu não receber uma resposta em até sete dias, terei que procurar um órgão de defesa do consumidor. Preferiria resolver isso diretamente com vocês.', 'Primeira condicional como aviso firme e educado. "Would prefer" suaviza.'),
        pg('Thank you for your time and attention to this matter. Please find my order number and contact details below.', 'Obrigado pelo seu tempo e atenção a este assunto. Seguem abaixo o número do pedido e meus dados de contato.', '"Please find ... below" = fórmula de e-mail formal.'),
      ]),
      more(7, [
        pg('The story follows the family during one difficult winter. When the bakery is about to close, they must decide whether to sell it.', 'A história acompanha a família durante um inverno difícil. Quando a padaria está prestes a fechar, eles precisam decidir se vão vendê-la.', '"Be about to" = estar prestes a. "Whether" introduz uma dúvida.'),
        pg('The photography deserves special mention. Every scene seems lit by the morning sun, which makes the bread look delicious.', 'A fotografia merece menção especial. Cada cena parece iluminada pelo sol da manhã, o que faz o pão parecer delicioso.', '"Which" retoma a frase inteira. "Make + objeto + verbo" sem "to".'),
        pg('I also liked the music, which is quiet and never takes over. It supports the emotion instead of telling you how to feel.', 'Gostei também da música, que é tranquila e nunca domina a cena. Ela apoia a emoção em vez de dizer como você deve se sentir.', '"Instead of" + -ing. "Take over" = dominar.'),
        pg('I recommend it to anyone who enjoys slow, human stories. If you want action, however, you should choose something else.', 'Recomendo a quem gosta de histórias lentas e humanas. Se você quer ação, porém, deve escolher outro filme.', 'Recomendação com ressalva. "However" no meio da frase, entre vírgulas.'),
      ]),
      more(8, [
        pg('If the crust is too pale, put the loaf back in the oven for five more minutes. A little steam in the oven helps it turn golden.', 'Se a casca estiver muito clara, coloque o pão de volta no forno por mais cinco minutos. Um pouco de vapor no forno ajuda a dourar.', 'Imperativo com "if". "Turn golden" = ficar dourado.'),
        pg('Do not worry if your first loaf is not perfect. Practice matters more than a perfect recipe.', 'Não se preocupe se o primeiro pão não ficar perfeito. A prática importa mais que uma receita perfeita.', 'Tranquiliza o leitor. "More than" compara.'),
        pg('You can also add seeds, nuts or herbs to the dough. Just remember to mix them in before the first rest.', 'Você também pode acrescentar sementes, castanhas ou ervas à massa. Só lembre de misturá-las antes do primeiro descanso.', '"Remember to" + verbo = não esquecer de fazer. "Mix in" = incorporar.'),
        pg('Fresh bread is best on the same day, but it also freezes well. Slice it first, so you can take out only what you need.', 'O pão fresco é melhor no mesmo dia, mas também congela bem. Fatie primeiro, para tirar só o que for usar.', '"Best" = superlativo. "So you can" = para que você possa.'),
      ]),
      more(9, [
        pg('Another point is maintenance. When you rent, the owner usually pays for repairs, while owners must cover every problem themselves.', 'Outro ponto é a manutenção. Quando você aluga, o dono geralmente paga os reparos, enquanto os proprietários precisam arcar com cada problema.', '"While" contrasta duas situações. "Themselves" reforça quem paga.'),
        pg('Interest rates also matter. When they are high, a loan can cost much more than it seems at the beginning.', 'As taxas de juros também importam. Quando estão altas, um financiamento pode custar bem mais do que parece no começo.', '"When they are high" = condição geral. "Much more than" = comparativo.'),
        pg('There is an emotional side as well. Many people feel proud of owning a home, but others prefer the freedom of moving whenever they want.', 'Há também um lado emocional. Muita gente sente orgulho de ter uma casa, mas outros preferem a liberdade de se mudar quando quiserem.', '"Proud of" + -ing. "Whenever" = sempre que.'),
        pg('Whichever option you choose, make a budget first. Knowing your numbers will protect you from decisions you may regret later.', 'Qualquer que seja a opção, faça um orçamento primeiro. Conhecer seus números vai protegê-lo de decisões de que pode se arrepender depois.', '"Whichever" = qualquer que seja. Sujeito com -ing: "Knowing your numbers".'),
      ]),
      more(10, [
        pg('My sister has promised to help me with the move. She will drive the truck, and I will organize the boxes.', 'Minha irmã prometeu me ajudar na mudança. Ela vai dirigir o caminhão, e eu vou organizar as caixas.', 'Present perfect para uma promessa feita. "Will" para decisões combinadas.'),
        pg('I also plan to join a language class in the new city. Meeting people is the fastest way to feel at home.', 'Também pretendo entrar numa aula de idiomas na cidade nova. Conhecer pessoas é o jeito mais rápido de se sentir em casa.', '"Plan to" + verbo. Sujeito com -ing e superlativo "the fastest".'),
        pg('In five years, I would like to be working in a job I truly enjoy. I hope to be living near the sea, too.', 'Daqui a cinco anos, gostaria de estar trabalhando num emprego de que realmente gosto. Espero estar morando perto do mar também.', 'Future continuous com infinitivo ("to be working"). "In five years" = daqui a cinco anos.'),
        pg('Of course, nothing is certain. But I would rather try and fail than wonder what could have happened.', 'Claro, nada é certo. Mas prefiro tentar e falhar a ficar me perguntando o que poderia ter acontecido.', '"Would rather ... than" compara preferências. "Could have happened" = possibilidade no passado.'),
      ]),
    ],
  },
];
