// Lote phrasal-3: Phrasal Verbs Essenciais, capítulos 13–20 (work, fill, check,
// hang, hold, keep; por tema: rotina e casa, relacionamentos). Conteúdo original.

export const LEXICON = {
  answers: ["noun", "/ˈænsərz/", "respostas"],
  apart: ["adverb", "/əˈpɑːrt/", "separado, à parte"],
  application: ["noun", "/ˌæplɪˈkeɪʃən/", "inscrição, candidatura"],
  blanks: ["noun", "/blæŋks/", "lacunas"],
  checked: ["verb", "/tʃɛkt/", "verificou, marcou"],
  dozed: ["verb", "/doʊzd/", "cochilou"],
  edge: ["noun", "/ɛdʒ/", "beirada"],
  ex: ["noun", "/ɛks/", "ex (namorado ou namorada)"],
  facts: ["noun", "/fækts/", "fatos"],
  filled: ["verb", "/fɪld/", "encheu, preencheu"],
  grass: ["noun", "/ɡræs/", "grama"],
  holding: ["verb", "/ˈhoʊldɪŋ/", "segurando"],
  hung: ["verb", "/hʌŋ/", "pendurou; desligou"],
  onto: ["preposition", "/ˈɑːntuː/", "em, sobre"],
  pronunciation: ["noun", "/prəˌnʌnsiˈeɪʃən/", "pronúncia"],
  quickly: ["adverb", "/ˈkwɪkli/", "rapidamente"],
  tears: ["noun", "/tɪrz/", "lágrimas"],
  video: ["noun", "/ˈvɪdioʊ/", "vídeo"],
};

const p = (text, pt, note) => ({ kind: 'phrasal', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-phrasal-b1-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-phrasal-b1',
    slug: 'phrasal-verbs-b1',
    title: 'Phrasal Verbs Essenciais',
    level: 'B1',
    category: 'grammar',
    track: 'gramatica',
    trackOrder: 1,
    order: 8,
    short: 'Os phrasal verbs que nativos mais usam, por verbo-base, em frases reais com o sentido de cada um.',
    long: 'Phrasal verbs organizados pelo verbo-base (get, take, put, come, go, look, turn, give, make, break, bring, run, set, call, pick). Cada frase explica o sentido real × o literal, o registro e se o phrasal é separável (o objeto pode ir no meio: "turn it off").',
    lessons: [
      lesson(13, 'Work', 'work out, work on, work up…', [
        p('I work out three times a week.', 'Malho três vezes por semana.', '"Work out" (sem objeto) = fazer exercício, malhar.'),
        p('Everything worked out in the end.', 'No fim, deu tudo certo.', '"Work out" = dar certo, resolver-se.'),
        p("I can't work out the answer.", 'Não consigo descobrir a resposta.', '"Work out" + objeto = descobrir, calcular. Separável: "work it out".'),
        p("We'll work it out together.", 'Vamos resolver isso juntos.', 'Com pronome, o objeto vai no meio: "work it out".'),
        p("I'm working on a new project.", 'Estou trabalhando num projeto novo.', '"Work on" = dedicar-se a algo. Não separável.'),
        p('She needs to work on her pronunciation.', 'Ela precisa melhorar a pronúncia.', '"Work on" também = praticar para melhorar.'),
        p("Don't get worked up about it.", 'Não fique nervoso com isso.', '"Get worked up" = ficar agitado, nervoso.'),
        p('He worked his way up to manager.', 'Ele foi subindo até virar gerente.', '"Work your way up" = subir aos poucos, por esforço.'),
        p('The plan did not work out.', 'O plano não deu certo.', 'Negativa de "work out" = não funcionar.'),
        p("It works out cheaper by train.", 'Sai mais barato de trem.', '"Work out" + adjetivo = sair (custo final).'),
      ]),
      lesson(14, 'Fill', 'fill in, fill out, fill up…', [
        p('Please fill in this form.', 'Por favor, preencha este formulário.', '"Fill in" = preencher (britânico). Separável.'),
        p('Fill out the application online.', 'Preencha a inscrição online.', '"Fill out" = preencher (americano).'),
        p('Fill in the blanks.', 'Complete as lacunas.', 'Instrução clássica de exercício.'),
        p('Can you fill me in on the meeting?', 'Pode me atualizar sobre a reunião?', '"Fill someone in" = pôr alguém a par.'),
        p('She filled in for me yesterday.', 'Ela me substituiu ontem.', '"Fill in for" = cobrir alguém no trabalho.'),
        p('I need to fill up the tank.', 'Preciso encher o tanque.', '"Fill up" = encher completamente.'),
        p('Fill it up, please.', 'Enche, por favor.', 'No posto: "fill it up" = completa o tanque.'),
        p("Don't fill up on bread.", 'Não se encha de pão.', '"Fill up on" = encher-se de alguma comida.'),
        p('The room filled up quickly.', 'A sala lotou rápido.', 'Sem objeto: "fill up" = lotar.'),
        p("I'm filled up, thanks.", 'Estou satisfeito, obrigado.', 'Informal para "estou cheio".'),
      ]),
      lesson(15, 'Check', 'check in, check out, check on…', [
        p('We checked in at the hotel at noon.', 'Fizemos check-in no hotel ao meio-dia.', '"Check in" = registrar-se na chegada.'),
        p('What time do we have to check out?', 'A que horas temos que fazer check-out?', '"Check out" = sair e pagar no hotel.'),
        p('Check out this video!', 'Olha este vídeo!', '"Check out" informal = dar uma olhada.'),
        p('Let me check out the menu first.', 'Deixa eu dar uma olhada no cardápio primeiro.', 'Separável: "check it out".'),
        p('Can you check on the kids?', 'Pode dar uma olhada nas crianças?', '"Check on" = verificar se está tudo bem.'),
        p("I'll check with my boss.", 'Vou confirmar com meu chefe.', '"Check with" = consultar alguém.'),
        p('Please check over your answers.', 'Por favor, revise suas respostas.', '"Check over" = revisar com atenção.'),
        p('I just wanted to check in.', 'Só queria saber como você está.', '"Check in" com alguém = dar notícias, saber como está.'),
        p('She checked off every item on the list.', 'Ela marcou cada item da lista.', '"Check off" = riscar da lista.'),
        p('Did you check the facts?', 'Você verificou os fatos?', 'Sem partícula: "check" = verificar. Compare com os phrasals.'),
      ]),
      lesson(16, 'Hang', 'hang out, hang up, hang on…', [
        p('We hang out every Friday.', 'A gente sai junto toda sexta.', '"Hang out" = passar tempo junto, sair.'),
        p("Don't hang up!", 'Não desliga!', '"Hang up" = desligar o telefone.'),
        p('He hung up on me.', 'Ele desligou na minha cara.', '"Hang up on someone" = desligar na cara.'),
        p('Hang on a second.', 'Espera um segundo.', '"Hang on" = esperar (informal).'),
        p('Hang on tight!', 'Segura firme!', '"Hang on" também = segurar firme.'),
        p('Hang up your coat here.', 'Pendure seu casaco aqui.', '"Hang up" + roupa = pendurar. Separável.'),
        p('Just hang in there.', 'Aguenta firme.', '"Hang in there" = não desista.'),
        p('Where do you usually hang out?', 'Onde você costuma sair?', 'Pergunta comum para conhecer alguém.'),
        p('I hung around for an hour.', 'Fiquei por ali uma hora.', '"Hang around" = ficar à toa num lugar.'),
        p("She's hung up on her ex.", 'Ela ainda está presa ao ex.', '"Hung up on" (adjetivo) = obcecado, preso emocionalmente.'),
      ]),
      lesson(17, 'Hold', 'hold on, hold back, hold up…', [
        p('Hold on, I will check.', 'Espera, vou verificar.', '"Hold on" = esperar, como "hang on".'),
        p('Sorry, I got held up in traffic.', 'Desculpe, fiquei preso no trânsito.', '"Held up" = atrasado.'),
        p("Hold up, that's not right.", 'Pera aí, isso não está certo.', '"Hold up" informal = espera aí.'),
        p("Don't hold back, tell me.", 'Não se segura, me conta.', '"Hold back" = conter-se.'),
        p('She held back her tears.', 'Ela segurou as lágrimas.', 'Separável: "held her tears back".'),
        p('Hold onto your ticket.', 'Guarde seu ingresso.', '"Hold onto" = guardar, não soltar.'),
        p('How are you holding up?', 'Como você está aguentando?', '"Hold up" = aguentar uma fase difícil.'),
        p('The bank was held up yesterday.', 'O banco foi assaltado ontem.', '"Hold up" + lugar = assaltar à mão armada.'),
        p('Can you hold off until Monday?', 'Pode esperar até segunda?', '"Hold off" = adiar.'),
        p('Hold it right there!', 'Pare aí mesmo!', 'Ordem para parar.'),
      ]),
      lesson(18, 'Keep', 'keep up, keep on, keep away…', [
        p('Keep up the good work!', 'Continue com o bom trabalho!', '"Keep up" = manter o nível.'),
        p("I can't keep up with you.", 'Não consigo te acompanhar.', '"Keep up with" = acompanhar o ritmo.'),
        p('He keeps on talking.', 'Ele não para de falar.', '"Keep on" + -ing = continuar insistindo.'),
        p('Keep away from the edge.', 'Fique longe da beirada.', '"Keep away from" = manter distância.'),
        p('Keep the noise down, please.', 'Façam menos barulho, por favor.', '"Keep down" = manter baixo. Separável.'),
        p('Keep it up!', 'Continue assim!', 'Incentivo curto.'),
        p('I try to keep up with the news.', 'Tento me manter atualizado com as notícias.', '"Keep up with" = manter-se informado.'),
        p('Keep off the grass.', 'Não pise na grama.', 'Placa comum: "keep off" = não entrar, não tocar.'),
        p('She kept me waiting for an hour.', 'Ela me deixou esperando uma hora.', '"Keep someone waiting" = deixar esperando.'),
        p("Keep it to yourself.", 'Guarde isso para você.', '"Keep to yourself" = não contar.'),
      ]),
      lesson(19, 'Por tema: casa e rotina', 'Phrasal verbs do dia a dia em casa.', [
        p('I wake up at six.', 'Acordo às seis.', '"Wake up" = acordar.'),
        p('I get up right away.', 'Me levanto na hora.', '"Get up" = levantar da cama.'),
        p('Can you clean up the kitchen?', 'Pode limpar a cozinha?', '"Clean up" = arrumar, limpar tudo.'),
        p('Take out the trash, please.', 'Leve o lixo para fora, por favor.', '"Take out" = levar para fora. Separável.'),
        p('I need to wash up.', 'Preciso lavar a louça.', '"Wash up" = lavar a louça (britânico); lavar-se (americano).'),
        p('Plug in the charger.', 'Coloque o carregador na tomada.', '"Plug in" = ligar na tomada.'),
        p('I ran out of milk.', 'Acabou o leite.', '"Run out of" = ficar sem.'),
        p('Put away your clothes.', 'Guarde suas roupas.', '"Put away" = guardar no lugar.'),
        p('I dozed off on the sofa.', 'Cochilei no sofá.', '"Doze off" = pegar no sono sem querer.'),
        p('Can you pick up some bread?', 'Pode comprar pão?', '"Pick up" = buscar, comprar de passagem.'),
      ]),
      lesson(20, 'Por tema: relacionamentos', 'Amizade, namoro e conflito.', [
        p('We get along really well.', 'A gente se dá muito bem.', '"Get along" = dar-se bem.'),
        p('They broke up last year.', 'Eles terminaram ano passado.', '"Break up" = terminar um relacionamento.'),
        p('He asked her out.', 'Ele a chamou para sair.', '"Ask out" = convidar para um encontro. Separável.'),
        p('I fell out with my cousin.', 'Briguei com meu primo.', '"Fall out with" = brigar e se afastar.'),
        p('They made up the next day.', 'Eles fizeram as pazes no dia seguinte.', '"Make up" = fazer as pazes.'),
        p('I look up to my mother.', 'Admiro minha mãe.', '"Look up to" = admirar.'),
        p("Don't let me down.", 'Não me decepcione.', '"Let down" = decepcionar. Separável.'),
        p('She stood me up.', 'Ela me deu um bolo.', '"Stand up" + pessoa = não aparecer no encontro.'),
        p('We grew apart over the years.', 'A gente se afastou com os anos.', '"Grow apart" = afastar-se aos poucos.'),
        p("I'll catch up with you later.", 'Te encontro mais tarde para colocar o papo em dia.', '"Catch up" = pôr a conversa em dia.'),
      ]),
    ],
  },
];
