// Lote phrasal-1: curso novo "Phrasal Verbs Essenciais" (B1, trilha Gramática),
// capítulos 1–6 por verbo-base (get, take, put, come/go, look, turn/give). Cada
// nota traz o sentido real × literal, o registro e se o phrasal separa
// ("separável": o objeto pode ir no meio). Conteúdo original.

export const LEXICON = {
  prices: ['noun', '/ˈpraɪsɪz/', 'preços'],
  along: ['particle', '/əˈlɔːŋ/', 'junto (get along = dar-se bem)'],
  bought: ['verb', '/bɔːt/', 'comprou'],
  boxes: ['noun', '/ˈbɑːksɪz/', 'caixas'],
  breakup: ['noun', '/ˈbreɪkʌp/', 'término (de namoro)'],
  dictionary: ['noun', '/ˈdɪkʃənɛri/', 'dicionário'],
  exams: ['noun', '/ɪɡˈzæmz/', 'provas'],
  fire: ['noun', '/ˈfaɪər/', 'fogo, incêndio'],
  firefighters: ['noun', '/ˈfaɪərfaɪtərz/', 'bombeiros'],
  listened: ['verb', '/ˈlɪsənd/', 'ouviu'],
  listening: ['verb', '/ˈlɪsənɪŋ/', 'ouvindo'],
  longer: ['adverb', '/ˈlɔːŋɡər/', 'mais (tempo)'],
  months: ['noun', '/mʌnθs/', 'meses'],
  photo: ['noun', '/ˈfoʊtoʊ/', 'foto'],
  programming: ['noun', '/ˈproʊɡræmɪŋ/', 'programação'],
  rid: ['adjective', '/rɪd/', 'livre (get rid of = livrar-se de)'],
  space: ['noun', '/speɪs/', 'espaço'],
  takes: ['verb', '/teɪks/', 'pega, leva; decola'],
  toys: ['noun', '/tɔɪz/', 'brinquedos'],
  true: ['adjective', '/truː/', 'verdadeiro'],
};

const p = (text, pt, note) => ({ kind: 'phrasal', text, pt, note });

export const COURSES = [
  {
    id: 'course-phrasal-b1',
    slug: 'phrasal-verbs-b1',
    title: 'Phrasal Verbs Essenciais',
    level: 'B1',
    category: 'grammar',
    track: 'gramatica',
    trackOrder: 1,
    order: 8,
    short: 'Os phrasal verbs que nativos mais usam, por verbo-base, em frases reais com o sentido de cada um.',
    long: 'Phrasal verbs organizados pelo verbo-base (get, take, put, come, go, look, turn, give). Cada frase explica o sentido real × o literal, o registro e se o phrasal é separável (o objeto pode ir no meio: "turn it off").',
    lessons: [
      {
        id: 'lesson-phrasal-b1-01',
        chapter: 1,
        title: 'Get',
        description: 'get up, get along, get over, get back, get on…',
        units: [
          p('I get up at six every day.', 'Eu me levanto às seis todo dia.', '"Get up" = levantar-se (da cama). Não separável. Neutro.'),
          p('Do you get along with your sister?', 'Você se dá bem com sua irmã?', '"Get along (with)" = dar-se bem com. Neutro.'),
          p('It took me months to get over the breakup.', 'Levei meses para superar o término.', '"Get over" = superar (doença, término). Não separável.'),
          p("I'll get back to you tomorrow.", 'Te dou um retorno amanhã.', '"Get back to" = dar retorno, responder depois. Muito usado no trabalho.'),
          p('Get on the bus at the next stop.', 'Suba no ônibus na próxima parada.', '"Get on/off" = subir/descer de ônibus, trem, avião. Carro é "get in/out".'),
          p('We need to get rid of these old boxes.', 'Precisamos nos livrar dessas caixas velhas.', '"Get rid of" = livrar-se de. Neutro.'),
          p('How did you get into programming?', 'Como você entrou para a programação?', '"Get into" = começar a se interessar ou a trabalhar com algo.'),
          p("Let's get together this weekend.", 'Vamos nos encontrar neste fim de semana.', '"Get together" = reunir-se. Informal.'),
          p("I can't get through to the bank.", 'Não consigo falar com o banco.', '"Get through (to)" = conseguir contato por telefone.'),
          p('He always gets away with it.', 'Ele sempre se safa.', '"Get away with" = sair impune. Informal.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-02',
        chapter: 2,
        title: 'Take',
        description: 'take off, take after, take up, take over, take back…',
        units: [
          p('The plane takes off at noon.', 'O avião decola ao meio-dia.', '"Take off" (sem objeto) = decolar.'),
          p('Take off your shoes, please.', 'Tire os sapatos, por favor.', '"Take off" (com objeto) = tirar roupa. Separável: "take your shoes off".'),
          p('She takes after her mother.', 'Ela puxou à mãe.', '"Take after" = parecer com (parente). Não separável.'),
          p('I took up yoga last year.', 'Comecei a fazer ioga no ano passado.', '"Take up" = começar um hobby.'),
          p('Who will take over the project?', 'Quem vai assumir o projeto?', '"Take over" = assumir o controle.'),
          p('I take back what I said.', 'Retiro o que eu disse.', '"Take back" = retirar (palavras) ou devolver. Separável.'),
          p("Let's take it easy today.", 'Vamos pegar leve hoje.', '"Take it easy" = pegar leve, relaxar. Informal.'),
          p('Can you take out the trash?', 'Pode levar o lixo para fora?', '"Take out" = levar para fora; também "take someone out" = levar para sair.'),
          p('This sofa takes up too much space.', 'Este sofá ocupa espaço demais.', '"Take up space" = ocupar espaço.'),
          p("I'll take care of it.", 'Eu cuido disso.', '"Take care of" = cuidar de, resolver.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-03',
        chapter: 3,
        title: 'Put',
        description: 'put on, put off, put up with, put away, put out…',
        units: [
          p('Put on your coat, it is cold.', 'Coloque o casaco, está frio.', '"Put on" = vestir, colocar. Separável: "put it on".'),
          p("Let's not put it off any longer.", 'Não vamos adiar mais.', '"Put off" = adiar. Separável.'),
          p("I can't put up with this noise.", 'Não aguento esse barulho.', '"Put up with" = tolerar. Não separável.'),
          p('Put away your toys.', 'Guarde seus brinquedos.', '"Put away" = guardar no lugar.'),
          p('The firefighters put out the fire.', 'Os bombeiros apagaram o fogo.', '"Put out" = apagar (fogo, cigarro).'),
          p('Can you put me through to sales?', 'Pode me transferir para vendas?', '"Put through" = transferir ligação.'),
          p('She put down her phone and listened.', 'Ela largou o celular e ouviu.', '"Put down" = colocar no chão/mesa, largar.'),
          p("I'll put together a report.", 'Vou montar um relatório.', '"Put together" = montar, organizar.'),
          p('They put up a new building downtown.', 'Construíram um prédio novo no centro.', '"Put up" = construir, erguer; também hospedar alguém.'),
          p('Please put your name down on the list.', 'Por favor, coloque seu nome na lista.', '"Put down" também é anotar, inscrever.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-04',
        chapter: 4,
        title: 'Come e go',
        description: 'come back, come up with, go on, go out, go over…',
        units: [
          p('When are you coming back?', 'Quando você volta?', '"Come back" = voltar (para cá).'),
          p('She came up with a great idea.', 'Ela teve uma ótima ideia.', '"Come up with" = inventar, ter (ideia, solução).'),
          p('The price came down last month.', 'O preço caiu no mês passado.', '"Come down" = baixar, cair.'),
          p('I came across an old photo.', 'Encontrei uma foto antiga por acaso.', '"Come across" = encontrar por acaso.'),
          p('Come on, we are late!', 'Vamos, estamos atrasados!', '"Come on" = vamos, anda logo. Informal.'),
          p('Please go on, I am listening.', 'Por favor, continue, estou ouvindo.', '"Go on" = continuar.'),
          p("Let's go out tonight.", 'Vamos sair hoje à noite.', '"Go out" = sair (para se divertir).'),
          p("Let's go over the plan again.", 'Vamos revisar o plano de novo.', '"Go over" = revisar.'),
          p('The alarm went off at three.', 'O alarme tocou às três.', '"Go off" = disparar, tocar (alarme); também estragar (comida).'),
          p('Prices keep going up.', 'Os preços continuam subindo.', '"Go up/down" = subir/descer (valores).'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-05',
        chapter: 5,
        title: 'Look',
        description: 'look for, look after, look up, look forward to…',
        units: [
          p("I'm looking for my keys.", 'Estou procurando minhas chaves.', '"Look for" = procurar. Não separável.'),
          p('Can you look after my dog?', 'Pode cuidar do meu cachorro?', '"Look after" = cuidar de. Não separável.'),
          p('Look it up in the dictionary.', 'Procure no dicionário.', '"Look up" = procurar informação. Separável: "look it up".'),
          p('I look forward to meeting you.', 'Estou ansioso para te conhecer.', '"Look forward to" + verbo com "-ing". Formal/neutro.'),
          p('Look out! A car is coming.', 'Cuidado! Vem um carro.', '"Look out" = cuidado! Informal.'),
          p('Can you look into this problem?', 'Pode investigar este problema?', '"Look into" = investigar, analisar.'),
          p('I look up to my father.', 'Admiro meu pai.', '"Look up to" = admirar alguém. Oposto: "look down on" = desprezar.'),
          p('We looked around the old town.', 'Demos uma volta pela cidade antiga.', '"Look around" = dar uma olhada ao redor.'),
          p('Can you look over my email before I send it?', 'Pode revisar meu e-mail antes de eu mandar?', '"Look over" = revisar rapidamente.'),
          p('Things are looking up.', 'As coisas estão melhorando.', '"Look up" (sem objeto) = melhorar.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-06',
        chapter: 6,
        title: 'Turn e give',
        description: 'turn on/off, turn down, turn up, give up, give back…',
        units: [
          p('Turn off the lights when you leave.', 'Apague as luzes quando sair.', '"Turn off/on" = desligar/ligar. Separável: "turn them off".'),
          p('Can you turn down the music?', 'Pode abaixar a música?', '"Turn down/up" = abaixar/aumentar volume.'),
          p('She turned down the job offer.', 'Ela recusou a oferta de emprego.', '"Turn down" também é recusar.'),
          p('He turned up late again.', 'Ele apareceu atrasado de novo.', '"Turn up" (sem objeto) = aparecer, chegar.'),
          p('It turned out to be true.', 'No fim, era verdade.', '"Turn out" = acabar sendo, revelar-se.'),
          p("Don't give up!", 'Não desista!', '"Give up" = desistir.'),
          p('I gave up sugar last year.', 'Larguei o açúcar no ano passado.', '"Give up" + coisa = largar um hábito.'),
          p('Give it back to me.', 'Me devolve isso.', '"Give back" = devolver. Separável.'),
          p('The teacher gave out the exams.', 'O professor distribuiu as provas.', '"Give out" = distribuir.'),
          p('I finally gave in and bought it.', 'No fim eu cedi e comprei.', '"Give in" = ceder, render-se.'),
        ],
      },
    ],
  },
];
