// Lote phrasal-2: Phrasal Verbs Essenciais, capítulos 7–12 (make, break, bring,
// run, set, call/pick). Conteúdo original.

export const LEXICON = {
  mexico: ['proper noun', '/ˈmɛksɪkoʊ/', 'México'],
  spanish: ['proper noun', '/ˈspænɪʃ/', 'espanhol'],
  women: ['noun', '/ˈwɪmɪn/', 'mulheres'],
  argued: ['verb', '/ˈɑːrɡjuːd/', 'discutiram, brigaram'],
  business: ['noun', '/ˈbɪznəs/', 'negócio, empresa'],
  changes: ['noun', '/ˈtʃeɪndʒɪz/', 'mudanças'],
  cried: ['verb', '/kraɪd/', 'chorou'],
  grandparents: ['noun', '/ˈɡrænpɛrənts/', 'avós'],
  law: ['noun', '/lɔː/', 'lei'],
  locked: ['adjective', '/lɑːkt/', 'trancado'],
  memories: ['noun', '/ˈmɛməriz/', 'lembranças'],
  most: ['determiner', '/moʊst/', 'o máximo, a maioria'],
  picked: ['verb', '/pɪkt/', 'pegou, escolheu'],
  picking: ['verb', '/ˈpɪkɪŋ/', 'pegando; melhorando'],
  points: ['noun', '/pɔɪnts/', 'pontos'],
  politics: ['noun', '/ˈpɑːlətɪks/', 'política'],
  projector: ['noun', '/prəˈdʒɛktər/', 'projetor'],
  record: ['noun', '/ˈrɛkərd/', 'recorde'],
  runs: ['verb', '/rʌnz/', 'administra; corre'],
  saying: ['verb', '/ˈseɪɪŋ/', 'dizendo'],
  sets: ['verb', '/sɛts/', 'põe-se (sol)'],
  world: ['noun', '/wɜːrld/', 'mundo'],
};

const p = (text, pt, note) => ({ kind: 'phrasal', text, pt, note });

export const COURSES = [
  {
    id: 'course-phrasal-b1',
    slug: 'phrasal-verbs-b1',
    title: 'Phrasal Verbs Essenciais',
    level: 'B1',
    category: 'grammar',
    track: 'gramatica',
    trackOrder: 1,
    order: 8,
    short: 'Os phrasal verbs que nativos mais usam, por verbo-base, em frases reais com o sentido de cada um.',
    long: 'Phrasal verbs organizados pelo verbo-base (get, take, put, come, go, look, turn, give, make, break, bring, run, set, call, pick). Cada frase explica o sentido real × o literal, o registro e se o phrasal é separável (o objeto pode ir no meio: "turn it off").',
    lessons: [
      {
        id: 'lesson-phrasal-b1-07',
        chapter: 7,
        title: 'Make',
        description: 'make up, make out, make up for, make it…',
        units: [
          p('She made up an excuse.', 'Ela inventou uma desculpa.', '"Make up" = inventar (história, desculpa). Separável.'),
          p('They argued, but they made up later.', 'Eles brigaram, mas fizeram as pazes depois.', '"Make up" (sem objeto) = fazer as pazes.'),
          p("I can't make out what he is saying.", 'Não consigo entender o que ele está dizendo.', '"Make out" = distinguir, entender (som, letra).'),
          p('I will make up for lost time.', 'Vou compensar o tempo perdido.', '"Make up for" = compensar.'),
          p('Women make up half of the team.', 'Mulheres formam metade do time.', '"Make up" = compor, formar.'),
          p('We made it to the airport on time.', 'Conseguimos chegar ao aeroporto a tempo.', '"Make it" = conseguir chegar, ter sucesso.'),
          p('Can you make sure the door is locked?', 'Pode confirmar que a porta está trancada?', '"Make sure" = garantir, conferir.'),
          p('Make yourself at home.', 'Fique à vontade.', 'Expressão fixa para receber visita.'),
          p("Let's make the most of the weekend.", 'Vamos aproveitar ao máximo o fim de semana.', '"Make the most of" = aproveitar ao máximo.'),
          p('I need to make up my mind.', 'Preciso me decidir.', '"Make up one\'s mind" = decidir-se.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-08',
        chapter: 8,
        title: 'Break',
        description: 'break down, break up, break into, break out…',
        units: [
          p('My car broke down on the highway.', 'Meu carro quebrou na rodovia.', '"Break down" = quebrar (máquina, veículo).'),
          p('She broke down and cried.', 'Ela desabou e chorou.', '"Break down" (pessoa) = desmoronar emocionalmente.'),
          p('They broke up after two years.', 'Eles terminaram depois de dois anos.', '"Break up (with)" = terminar namoro.'),
          p('Someone broke into our house.', 'Alguém arrombou nossa casa.', '"Break into" = invadir, arrombar. Não separável.'),
          p('A fire broke out in the kitchen.', 'Começou um incêndio na cozinha.', '"Break out" = começar de repente (fogo, guerra, doença).'),
          p("Let's break the task down into steps.", 'Vamos dividir a tarefa em etapas.', '"Break down" (com objeto) = dividir em partes. Separável.'),
          p('The meeting broke up at five.', 'A reunião terminou às cinco.', '"Break up" (grupo) = dispersar, acabar.'),
          p('He broke the news to his parents.', 'Ele contou a notícia aos pais.', '"Break the news" = dar uma notícia difícil.'),
          p("Let's take a break.", 'Vamos fazer uma pausa.', '"Break" como substantivo = pausa.'),
          p('She broke the record.', 'Ela bateu o recorde.', '"Break a record" = bater um recorde.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-09',
        chapter: 9,
        title: 'Bring',
        description: 'bring up, bring back, bring about, bring down…',
        units: [
          p("Don't bring up politics at dinner.", 'Não puxe o assunto política no jantar.', '"Bring up" = mencionar, puxar assunto. Separável.'),
          p('She was brought up by her grandparents.', 'Ela foi criada pelos avós.', '"Bring up" (criança) = criar, educar.'),
          p('This song brings back memories.', 'Esta música traz lembranças.', '"Bring back" = trazer de volta, lembrar.'),
          p('Please bring the book back tomorrow.', 'Por favor, devolva o livro amanhã.', '"Bring back" = devolver. Separável.'),
          p('The new law brought about many changes.', 'A nova lei provocou muitas mudanças.', '"Bring about" = causar, provocar. Formal.'),
          p('We need to bring down costs.', 'Precisamos reduzir custos.', '"Bring down" = reduzir.'),
          p('Can you bring the meeting forward to Monday?', 'Pode antecipar a reunião para segunda?', '"Bring forward" = antecipar.'),
          p('What brings you here today?', 'O que te traz aqui hoje?', 'Pergunta de abertura, simpática.'),
          p('Bring it on!', 'Pode vir!', 'Informal: aceitar um desafio.'),
          p('Bring a jacket, it gets cold at night.', 'Traga uma jaqueta, esfria à noite.', '"Bring" (sem partícula) = trazer.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-10',
        chapter: 10,
        title: 'Run',
        description: 'run out of, run into, run away, run over…',
        units: [
          p("We've run out of coffee.", 'Acabou o café.', '"Run out of" = ficar sem.'),
          p('I ran into an old friend yesterday.', 'Encontrei um velho amigo por acaso ontem.', '"Run into" = esbarrar em alguém por acaso.'),
          p('The dog ran away.', 'O cachorro fugiu.', '"Run away" = fugir.'),
          p('Let me run over the main points.', 'Deixa eu repassar os pontos principais.', '"Run over" = repassar rapidamente; também atropelar.'),
          p('The meeting ran over by twenty minutes.', 'A reunião passou vinte minutos do horário.', '"Run over" (tempo) = passar do horário.'),
          p('Time is running out.', 'O tempo está acabando.', '"Run out" (sem "of") = estar acabando.'),
          p('Can you run this by your manager?', 'Pode passar isso pelo seu gerente?', '"Run by" = consultar alguém antes de decidir.'),
          p('We ran into some problems.', 'Tivemos alguns problemas.', '"Run into problems" = encontrar problemas.'),
          p('She runs a small business.', 'Ela administra um pequeno negócio.', '"Run" (sem partícula) = administrar.'),
          p('It runs in the family.', 'É de família.', 'Expressão: característica herdada.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-11',
        chapter: 11,
        title: 'Set',
        description: 'set up, set off, set out, set back…',
        units: [
          p('Can you help me set up the projector?', 'Pode me ajudar a montar o projetor?', '"Set up" = montar, configurar. Separável.'),
          p('She set up her own company.', 'Ela abriu a própria empresa.', '"Set up" = fundar, criar.'),
          p('We set off early in the morning.', 'Saímos cedo de manhã.', '"Set off" = partir (viagem).'),
          p('The smoke set off the alarm.', 'A fumaça disparou o alarme.', '"Set off" (com objeto) = disparar.'),
          p('They set out to change the world.', 'Eles se propuseram a mudar o mundo.', '"Set out to" = ter como objetivo.'),
          p('The storm set us back two days.', 'A tempestade nos atrasou dois dias.', '"Set back" = atrasar. Substantivo: "setback" = revés.'),
          p('Set the alarm for six.', 'Coloque o despertador para as seis.', '"Set an alarm" = programar o despertador.'),
          p("Let's set a date for the meeting.", 'Vamos marcar uma data para a reunião.', '"Set a date" = marcar data.'),
          p('The sun sets at seven.', 'O sol se põe às sete.', '"Set" (sol) = pôr-se.'),
          p("I'm all set.", 'Estou pronto.', 'Informal. "All set" = tudo pronto.'),
        ],
      },
      {
        id: 'lesson-phrasal-b1-12',
        chapter: 12,
        title: 'Call e pick',
        description: 'call off, call back, pick up, pick out…',
        units: [
          p('They called off the game because of rain.', 'Cancelaram o jogo por causa da chuva.', '"Call off" = cancelar. Separável.'),
          p("I'll call you back in a minute.", 'Te ligo de volta em um minuto.', '"Call back" = retornar a ligação.'),
          p('The teacher called on me to answer.', 'O professor me chamou para responder.', '"Call on" = chamar alguém (em aula, reunião).'),
          p('Call me up when you are free.', 'Me liga quando estiver livre.', '"Call up" = telefonar. Informal.'),
          p('Can you pick me up at eight?', 'Pode me buscar às oito?', '"Pick up" = buscar alguém. Separável.'),
          p('Pick up your toys.', 'Recolha seus brinquedos.', '"Pick up" = pegar do chão.'),
          p('I picked up some Spanish in Mexico.', 'Aprendi um pouco de espanhol no México.', '"Pick up" = aprender sem estudar formalmente.'),
          p('Help me pick out a gift.', 'Me ajuda a escolher um presente.', '"Pick out" = escolher.'),
          p('Sales are picking up.', 'As vendas estão melhorando.', '"Pick up" (sem objeto) = melhorar, aumentar.'),
          p('Nobody picked up the phone.', 'Ninguém atendeu o telefone.', '"Pick up the phone" = atender.'),
        ],
      },
    ],
  },
];
