// Lote phrasal-b2-1: curso novo "Phrasal Verbs Avançados" (B2, trilha Gramática), capítulos 1–10.
// Continua "Phrasal Verbs Essenciais" (B1) com combinações menos óbvias, agrupadas por
// situação. Cada nota dá o sentido e diz se o phrasal verb é separável (pode ficar
// "turn it down") ou inseparável. Conteúdo original.

export const LEXICON = {
  bounced: ["verb", "/baʊnst/", "voltou, quicou"],
  carried: ["verb", "/ˈkærid/", "levou, carregou"],
  cheer: ["verb", "/tʃɪr/", "animar"],
  clever: ["adjective", "/ˈklɛvər/", "inteligente, esperto"],
  competitors: ["noun", "/kəmˈpɛtɪtərz/", "concorrentes"],
  count: ["verb", "/kaʊnt/", "contar, confiar"],
  coworkers: ["noun", "/ˈkoʊwɜːrkərz/", "colegas de trabalho"],
  cross: ["verb", "/krɔːs/", "riscar, cruzar"],
  detailed: ["adjective", "/ˈdiːteɪld/", "detalhado"],
  details: ["noun", "/ˈdiːteɪlz/", "detalhes"],
  doctors: ["noun", "/ˈdɑːktərz/", "médicos"],
  dragged: ["verb", "/dræɡd/", "se arrastou"],
  factory: ["noun", "/ˈfæktəri/", "fábrica"],
  failure: ["noun", "/ˈfeɪljər/", "fracasso"],
  falling: ["verb", "/ˈfɔːlɪŋ/", "caindo"],
  files: ["noun", "/faɪlz/", "arquivos"],
  flyers: ["noun", "/ˈflaɪərz/", "panfletos"],
  handed: ["verb", "/ˈhændɪd/", "entregou"],
  icy: ["adjective", "/ˈaɪsi/", "com gelo, gelado"],
  illness: ["noun", "/ˈɪlnəs/", "doença"],
  loss: ["noun", "/lɔːs/", "perda"],
  managed: ["verb", "/ˈmænɪdʒd/", "conseguiu"],
  newsletter: ["noun", "/ˈnuːzlɛtər/", "boletim por e-mail"],
  older: ["adjective", "/ˈoʊldər/", "mais velho"],
  opt: ["verb", "/ɑːpt/", "optar"],
  paperwork: ["noun", "/ˈpeɪpərwɜːrk/", "papelada"],
  phased: ["verb", "/feɪzd/", "retirado aos poucos"],
  proposal: ["noun", "/prəˈpoʊzəl/", "proposta"],
  pulled: ["verb", "/pʊld/", "puxou"],
  pushed: ["verb", "/pʊʃt/", "empurrou"],
  rights: ["noun", "/raɪts/", "direitos"],
  roads: ["noun", "/roʊdz/", "estradas"],
  ruled: ["verb", "/ruːld/", "descartou"],
  secret: ["noun", "/ˈsiːkrɪt/", "segredo"],
  shows: ["verb", "/ʃoʊz/", "mostra"],
  shut: ["verb", "/ʃʌt/", "fechar"],
  siblings: ["noun", "/ˈsɪblɪŋz/", "irmãos (irmãos e irmãs)"],
  sort: ["verb", "/sɔːrt/", "organizar, resolver"],
  speech: ["noun", "/spiːtʃ/", "discurso"],
  speed: ["verb", "/spiːd/", "acelerar"],
  stands: ["verb", "/stændz/", "fica de pé, se destaca"],
  surgery: ["noun", "/ˈsɜːrdʒəri/", "cirurgia"],
  survey: ["noun", "/ˈsɜːrveɪ/", "pesquisa, levantamento"],
  threw: ["verb", "/θruː/", "deu (festa), jogou"],
  tone: ["noun", "/toʊn/", "tom"],
  voted: ["verb", "/ˈvoʊtɪd/", "votou"],
  walks: ["verb", "/wɔːks/", "anda"],
  ways: ["noun", "/weɪz/", "jeitos, aspectos"],
  worn: ["verb", "/wɔːrn/", "gasto"],
  wound: ["verb", "/waʊnd/", "acabou (wind up)"],
  wrap: ["verb", "/ræp/", "encerrar, embrulhar"],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-phrasal-b2-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-phrasal-adv-b2',
    slug: 'advanced-phrasal-verbs-b2',
    title: 'Phrasal Verbs Avançados',
    level: 'B2',
    category: 'grammar',
    track: 'gramatica',
    trackOrder: 2,
    order: 24,
    short: 'Figure out, put up with, turn down: os phrasal verbs que aparecem em séries, reuniões e conversas reais.',
    long: 'Dez grupos de phrasal verbs para quem já domina os básicos. Cada frase mostra o sentido na situação e avisa se o verbo é separável ou não, que é o ponto em que mais se erra.',
    lessons: [
      lesson(1, 'Falar e agir', 'Bring up, carry out, cut down e outros de conversa e ação.', [
        s('She brought up the issue at lunch.', 'Ela tocou no assunto durante o almoço.', '"Bring up" = mencionar um assunto; separável: "bring it up".'),
        s('The team carried out a detailed survey.', 'A equipe realizou uma pesquisa detalhada.', '"Carry out" = executar, realizar; separável.'),
        s('I am trying to cut down on sugar.', 'Estou tentando reduzir o açúcar.', '"Cut down on" = reduzir o consumo; inseparável.'),
        s('Can you point out the mistake for me?', 'Você pode apontar o erro para mim?', '"Point out" = apontar, destacar; separável.'),
        s('He always shows off in front of his friends.', 'Ele sempre se exibe na frente dos amigos.', '"Show off" = se exibir, se gabar.'),
        s('Please fill me in on what I missed.', 'Me atualiza sobre o que eu perdi, por favor.', '"Fill in" = informar, atualizar; separável.'),
        s('They set up a meeting for Monday.', 'Eles marcaram uma reunião para segunda.', '"Set up" = organizar, marcar; separável.'),
        s('We need to stand up for our rights.', 'Precisamos defender nossos direitos.', '"Stand up for" = defender; inseparável.'),
        s('She talked me into joining the gym.', 'Ela me convenceu a entrar na academia.', '"Talk into" = convencer a fazer; separável.'),
        s('Do not let them talk you out of it.', 'Não deixe que eles te convençam do contrário.', '"Talk out of" = dissuadir.'),
      ]),
      lesson(2, 'Resolver e entender', 'Figure out, work out, sort out e companhia.', [
        s('I cannot figure out how this machine works.', 'Não consigo descobrir como esta máquina funciona.', '"Figure out" = entender, descobrir; separável.'),
        s('We will work out the details tomorrow.', 'Vamos acertar os detalhes amanhã.', '"Work out" = resolver, acertar; separável.'),
        s('It took a week to sort out the paperwork.', 'Levou uma semana para resolver a papelada.', '"Sort out" = organizar, resolver; separável.'),
        s('Let me think this over before I decide.', 'Deixa eu pensar nisso antes de decidir.', '"Think over" = ponderar; separável.'),
        s('The police are looking into the case.', 'A polícia está investigando o caso.', '"Look into" = investigar; inseparável.'),
        s('I came across an old photo of us.', 'Encontrei por acaso uma foto antiga nossa.', '"Come across" = achar sem procurar; inseparável.'),
        s('Can you make out what the sign says?', 'Você consegue ler o que diz a placa?', '"Make out" = distinguir, conseguir ler ou ouvir.'),
        s('He finally found out the truth.', 'Ele finalmente descobriu a verdade.', '"Find out" = descobrir uma informação.'),
        s('She gave away the secret by accident.', 'Ela entregou o segredo sem querer.', '"Give away" = revelar, entregar; separável.'),
        s('It turned out to be a great idea.', 'Acabou sendo uma ótima ideia.', '"Turn out" = acabar sendo, revelar-se.'),
      ]),
      lesson(3, 'Criar e superar', 'Come up with, go through, get over e outros de desafio.', [
        s('She came up with a clever solution.', 'Ela teve uma solução inteligente.', '"Come up with" = ter uma ideia; inseparável.'),
        s('They went through a difficult time.', 'Eles passaram por um período difícil.', '"Go through" = passar por, enfrentar.'),
        s('It took him months to get over the loss.', 'Ele levou meses para superar a perda.', '"Get over" = superar, recuperar-se.'),
        s('I am going to take up painting this year.', 'Vou começar a pintar este ano.', '"Take up" = começar um hobby; separável.'),
        s('We managed to get through the exam.', 'Conseguimos passar pela prova.', '"Get through" = conseguir terminar, atravessar.'),
        s('Do not give up on your dreams.', 'Não desista dos seus sonhos.', '"Give up on" = desistir de algo ou alguém.'),
        s('He bounced back after the failure.', 'Ele se recuperou depois do fracasso.', '"Bounce back" = se recuperar rápido.'),
        s('Hang in there, it will get better.', 'Aguente firme, vai melhorar.', '"Hang in there" = aguentar firme.'),
        s('She pulled through the surgery well.', 'Ela superou bem a cirurgia.', '"Pull through" = sobreviver, superar uma crise.'),
        s('We have to deal with this problem now.', 'Precisamos lidar com este problema agora.', '"Deal with" = lidar com; inseparável.'),
      ]),
      lesson(4, 'Aguentar e respeitar', 'Put up with, look up to e outras atitudes com as pessoas.', [
        s('I cannot put up with this noise any longer.', 'Não aguento mais esse barulho.', '"Put up with" = tolerar; inseparável.'),
        s('Many kids look up to their older siblings.', 'Muitas crianças admiram seus irmãos mais velhos.', '"Look up to" = admirar.'),
        s('Do not look down on people who work hard.', 'Não olhe de cima quem trabalha duro.', '"Look down on" = desprezar.'),
        s('She gets along well with her coworkers.', 'Ela se dá bem com os colegas de trabalho.', '"Get along with" = se dar bem com.'),
        s('They fell out over money last year.', 'Eles brigaram por causa de dinheiro no ano passado.', '"Fall out" = brigar, romper.'),
        s('We made up after a long talk.', 'Fizemos as pazes depois de uma longa conversa.', '"Make up" = fazer as pazes.'),
        s('He takes after his father in many ways.', 'Ele puxou ao pai em muitos aspectos.', '"Take after" = parecer-se com um familiar.'),
        s('I was brought up by my grandparents.', 'Fui criado pelos meus avós.', '"Bring up" na passiva = ser criado.'),
        s('Can I count on you to be there?', 'Posso contar com você para estar lá?', '"Count on" = contar com, confiar.'),
        s('She let me down when I needed her.', 'Ela me decepcionou quando eu precisei.', '"Let down" = decepcionar; separável.'),
      ]),
      lesson(5, 'Apoiar e perceber', 'Back up, step up, pick up on e verbos de percepção.', [
        s('Please back up your files before the update.', 'Faça backup dos seus arquivos antes da atualização.', '"Back up" = fazer cópia de segurança; separável.'),
        s('He backed me up in front of the boss.', 'Ele me apoiou diante do chefe.', '"Back up" = dar apoio a alguém.'),
        s('Someone has to step up and take charge.', 'Alguém tem que dar um passo à frente e assumir.', '"Step up" = assumir responsabilidade.'),
        s('She picked up on his nervous tone.', 'Ela percebeu o tom nervoso dele.', '"Pick up on" = notar algo sutil.'),
        s('You will pick up the language quickly there.', 'Você vai pegar o idioma rápido lá.', '"Pick up" = aprender sem esforço formal.'),
        s('I caught on to the joke a bit late.', 'Entendi a piada um pouco tarde.', '"Catch on" = entender, pegar o jeito.'),
        s('Keep an eye out for the delivery.', 'Fique de olho na entrega.', '"Keep an eye out for" = ficar atento a.'),
        s('Watch out for icy roads tonight.', 'Cuidado com estradas com gelo hoje à noite.', '"Watch out for" = tomar cuidado com.'),
        s('Look out, there is a car coming!', 'Cuidado, vem um carro!', '"Look out" = cuidado, aviso imediato.'),
        s('He has been going on about it all day.', 'Ele passou o dia inteiro falando disso.', '"Go on about" = falar sem parar sobre.'),
      ]),
      lesson(6, 'Quebrar e gastar', 'Fall apart, break down, wear out: o que se desfaz.', [
        s('The old sofa is falling apart.', 'O sofá velho está se desmanchando.', '"Fall apart" = se desfazer.'),
        s('Our car broke down on the highway.', 'Nosso carro quebrou na rodovia.', '"Break down" = quebrar, parar de funcionar.'),
        s('These shoes have worn out already.', 'Estes sapatos já se gastaram.', '"Wear out" = gastar com o uso.'),
        s('She broke down in tears at the news.', 'Ela desabou em lágrimas com a notícia.', '"Break down" = desabar emocionalmente.'),
        s('The deal fell through at the last minute.', 'O negócio deu errado na última hora.', '"Fall through" = fracassar, não se concretizar.'),
        s('A fire broke out in the building.', 'Um incêndio começou no prédio.', '"Break out" = começar de repente (fogo, guerra).'),
        s('Prices have been going up for months.', 'Os preços vêm subindo há meses.', '"Go up" = subir.'),
        s('The meeting dragged on for hours.', 'A reunião se arrastou por horas.', '"Drag on" = se arrastar, durar demais.'),
        s('Our plans fell apart after the storm.', 'Nossos planos desmoronaram depois da tempestade.', '"Fall apart" também vale para planos.'),
        s('I ran out of patience with him.', 'Perdi a paciência com ele.', '"Run out of" = ficar sem.'),
      ]),
      lesson(7, 'Segurar e entregar', 'Hold off, hold back, hand in e verbos de adiar e entregar.', [
        s('Let us hold off on the decision until Monday.', 'Vamos adiar a decisão até segunda.', '"Hold off" = adiar, esperar.'),
        s('She held back her tears during the speech.', 'Ela segurou as lágrimas durante o discurso.', '"Hold back" = conter.'),
        s('Please hand in your homework by Friday.', 'Entregue sua lição até sexta, por favor.', '"Hand in" = entregar (trabalho); separável.'),
        s('He handed out flyers on the street.', 'Ele distribuiu panfletos na rua.', '"Hand out" = distribuir.'),
        s('They put off the trip because of the weather.', 'Eles adiaram a viagem por causa do tempo.', '"Put off" = adiar; separável.'),
        s('The meeting has been pushed back to Thursday.', 'A reunião foi remarcada para quinta.', '"Push back" = adiar, empurrar para depois.'),
        s('I will drop by your office after lunch.', 'Passo no seu escritório depois do almoço.', '"Drop by" = dar uma passada.'),
        s('Can you drop off the keys at the front desk?', 'Você pode deixar as chaves na recepção?', '"Drop off" = deixar algo em um lugar.'),
        s('We should hold on until we get more data.', 'Devemos esperar até ter mais dados.', '"Hold on" = esperar, aguardar.'),
        s('She handed down the job to her cousin.', 'Ela passou o trabalho adiante para a prima.', '"Hand down" = passar adiante, herdar.'),
      ]),
      lesson(8, 'Recusar e cancelar', 'Turn down, call off, rule out e quem diz não.', [
        s('She turned down the job offer.', 'Ela recusou a oferta de emprego.', '"Turn down" = recusar; separável.'),
        s('They called off the wedding at the last minute.', 'Eles cancelaram o casamento na última hora.', '"Call off" = cancelar; separável.'),
        s('Doctors have ruled out any serious illness.', 'Os médicos descartaram qualquer doença grave.', '"Rule out" = descartar; separável.'),
        s('He backed out of the deal.', 'Ele desistiu do negócio.', '"Back out" = desistir de um compromisso.'),
        s('I will opt out of the newsletter.', 'Vou sair da lista da newsletter.', '"Opt out" = escolher não participar.'),
        s('The company has phased out that product.', 'A empresa foi retirando esse produto aos poucos.', '"Phase out" = eliminar gradualmente.'),
        s('Let me cross that off the list.', 'Deixa eu riscar isso da lista.', '"Cross off" = riscar.'),
        s('They shut down the factory last year.', 'Eles fecharam a fábrica no ano passado.', '"Shut down" = encerrar as atividades.'),
        s('The board voted down the proposal.', 'A diretoria rejeitou a proposta na votação.', '"Vote down" = rejeitar por voto.'),
        s('I had to say no and walk away.', 'Tive que dizer não e ir embora.', '"Walk away" = abandonar uma situação.'),
      ]),
      lesson(9, 'Acompanhar e atrasar', 'Catch up, keep up with, fall behind e ritmo.', [
        s('I need to catch up on my emails.', 'Preciso colocar meus e-mails em dia.', '"Catch up on" = colocar em dia.'),
        s('She walks so fast that I cannot keep up.', 'Ela anda tão rápido que não consigo acompanhar.', '"Keep up" = acompanhar o ritmo.'),
        s('He fell behind with the rent.', 'Ele atrasou o aluguel.', '"Fall behind" = ficar para trás, atrasar.'),
        s('We are catching up with our competitors.', 'Estamos alcançando nossos concorrentes.', '"Catch up with" = alcançar.'),
        s('It is hard to keep up with the news.', 'É difícil acompanhar as notícias.', '"Keep up with" = manter-se atualizado.'),
        s('Slow down, you are going too fast.', 'Devagar, você está indo rápido demais.', '"Slow down" = diminuir o ritmo.'),
        s('Speed up or we will miss the train.', 'Acelere ou perdemos o trem.', '"Speed up" = acelerar.'),
        s('Let us wrap up the meeting by five.', 'Vamos encerrar a reunião até as cinco.', '"Wrap up" = concluir.'),
        s('She wound up in a different city.', 'Ela acabou parando em outra cidade.', '"Wind up" = acabar em, terminar.'),
        s('Things are picking up at work.', 'As coisas estão melhorando no trabalho.', '"Pick up" = melhorar, ganhar ritmo.'),
      ]),
      lesson(10, 'Encontrar e se destacar', 'Run into, stand out, show up e situações sociais.', [
        s('I ran into an old friend at the airport.', 'Encontrei um velho amigo por acaso no aeroporto.', '"Run into" = encontrar por acaso.'),
        s('Her design really stands out.', 'O design dela se destaca de verdade.', '"Stand out" = se destacar.'),
        s('He did not show up for the interview.', 'Ele não apareceu para a entrevista.', '"Show up" = aparecer, comparecer.'),
        s('They split up after five years.', 'Eles se separaram depois de cinco anos.', '"Split up" = terminar um relacionamento.'),
        s('We should get together this weekend.', 'A gente devia se encontrar neste fim de semana.', '"Get together" = se reunir.'),
        s('I will see you off at the station.', 'Vou me despedir de você na estação.', '"See off" = ir se despedir.'),
        s('She took me in when I had nowhere to go.', 'Ela me acolheu quando eu não tinha para onde ir.', '"Take in" = acolher.'),
        s('They threw a party to cheer him up.', 'Eles fizeram uma festa para animá-lo.', '"Cheer up" = animar; separável.'),
        s('Do not leave me out of the plans.', 'Não me deixe fora dos planos.', '"Leave out" = excluir, deixar de fora.'),
        s('It is time to move on and start over.', 'É hora de seguir em frente e recomeçar.', '"Move on" = seguir em frente; "start over" = recomeçar.'),
      ]),
    ],
  },
];
