// Lote rotina-1: curso novo "Rotina e Vida em Casa" (A2, trilha Dia a dia),
// capítulos 1–6. Gramática de A2 dentro de situações de casa: presente simples ×
// contínuo, advérbios de frequência, passado, going to. Conteúdo original.

export const LEXICON = {
  boil: ['verb', '/bɔɪl/', 'ferver'],
  cut: ['verb', '/kʌt/', 'cortar'],
  leftovers: ['noun', '/ˈlɛftoʊvərz/', 'sobras'],
  twice: ['adverb', '/twaɪs/', 'duas vezes'],
  alarm: ['noun', '/əˈlɑːrm/', 'despertador, alarme'],
  barbecue: ['noun', '/ˈbɑːrbɪkjuː/', 'churrasco'],
  brush: ['verb', '/brʌʃ/', 'escovar'],
  burned: ['verb', '/bɜːrnd/', 'queimou'],
  button: ['noun', '/ˈbʌtən/', 'botão'],
  calendar: ['noun', '/ˈkælɪndər/', 'agenda, calendário'],
  cleaning: ['verb', '/ˈkliːnɪŋ/', 'limpando'],
  cooks: ['verb', '/kʊks/', 'cozinha'],
  dressed: ['adjective', '/drɛst/', 'vestido (get dressed = vestir-se)'],
  eggs: ['noun', '/ɛɡz/', 'ovos'],
  fast: ['adverb', '/fæst/', 'rápido'],
  fed: ['verb', '/fɛd/', 'alimentou'],
  fun: ['noun', '/fʌn/', 'diversão'],
  hate: ['verb', '/heɪt/', 'odiar'],
  ironing: ['noun', '/ˈaɪərnɪŋ/', 'passar roupa'],
  makeup: ['noun', '/ˈmeɪkʌp/', 'maquiagem'],
  making: ['verb', '/ˈmeɪkɪŋ/', 'fazendo'],
  mess: ['noun', '/mɛs/', 'bagunça'],
  neighbors: ['noun', '/ˈneɪbərz/', 'vizinhos'],
  onions: ['noun', '/ˈʌnjənz/', 'cebolas'],
  oven: ['noun', '/ˈʌvən/', 'forno'],
  "parents'": ['noun', '/ˈpɛrənts/', 'dos pais'],
  pieces: ['noun', '/ˈpiːsɪz/', 'pedaços'],
  plants: ['noun', '/plænts/', 'plantas'],
  preheating: ['verb', '/ˌpriːˈhiːtɪŋ/', 'preaquecendo'],
  puts: ['verb', '/pʊts/', 'coloca'],
  quit: ['verb', '/kwɪt/', 'parar, largar'],
  rained: ['verb', '/reɪnd/', 'choveu'],
  rarely: ['adverb', '/ˈrɛrli/', 'raramente'],
  series: ['noun', '/ˈsɪriːz/', 'série'],
  skips: ['verb', '/skɪps/', 'pula'],
  slept: ['verb', '/slɛpt/', 'dormiu'],
  smells: ['verb', '/smɛlz/', 'cheira'],
  smoke: ['verb', '/smoʊk/', 'fumar'],
  snooze: ['noun', '/snuːz/', 'soneca'],
  sometimes: ['adverb', '/ˈsʌmtaɪmz/', 'às vezes'],
  stayed: ['verb', '/steɪd/', 'ficou'],
  teeth: ['noun', '/tiːθ/', 'dentes'],
  toast: ['noun', '/toʊst/', 'torrada'],
  travel: ['verb', '/ˈtrævəl/', 'viajar'],
  trying: ['verb', '/ˈtraɪɪŋ/', 'tentando'],
  vacuum: ['verb', '/ˈvækjuːm/', 'aspirar'],
  watched: ['verb', '/wɑːtʃt/', 'assistiu'],
  whole: ['adjective', '/hoʊl/', 'inteiro'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-routine-a2',
    slug: 'daily-routine-a2',
    title: 'Rotina e Vida em Casa',
    level: 'A2',
    category: 'survival',
    track: 'dia-a-dia',
    trackOrder: 2,
    order: 4,
    short: 'Acordar, arrumar a casa, cozinhar, hábitos, fim de semana e planos: o inglês da sua rotina.',
    long: 'Frases do dia a dia em casa com a gramática do nível A2 aplicada: presente simples para hábitos, presente contínuo para o que está acontecendo, passado para contar o fim de semana e "going to" para planos. Cada frase explica a estrutura usada.',
    lessons: [
      {
        id: 'lesson-routine-a2-01',
        chapter: 1,
        title: 'Acordar e se arrumar',
        description: 'A manhã do despertador até sair de casa.',
        units: [
          s('My alarm goes off at six.', 'Meu despertador toca às seis.', '"Go off" = tocar (alarme). Presente simples para rotina.'),
          s('I usually hit the snooze button.', 'Eu geralmente aperto o soneca.', '"Snooze" = função soneca. "Usually" vai antes do verbo.'),
          s('I brush my teeth and take a shower.', 'Escovo os dentes e tomo banho.', 'Possessivo com partes do corpo: "my teeth". "Take a shower" = tomar banho.'),
          s("I'm getting dressed.", 'Estou me vestindo.', 'Presente contínuo para o que está acontecendo agora. "Get dressed" = vestir-se.'),
          s('I make my bed every morning.', 'Arrumo a cama toda manhã.', '"Make the bed" = arrumar a cama (não "arrange").'),
          s('She puts on makeup before work.', 'Ela se maquia antes do trabalho.', '"Put on makeup" = passar maquiagem.'),
          s('I have coffee and toast for breakfast.', 'Tomo café com torrada no café da manhã.', '"Have" + comida = comer/beber. "For breakfast" = no café da manhã.'),
          s("I'm running late!", 'Estou atrasado!', 'Presente contínuo: "running late" = atrasado agora.'),
          s("Don't forget your keys.", 'Não esqueça as chaves.', 'Imperativo negativo.'),
          s('I leave home at seven thirty.', 'Saio de casa às sete e meia.', '"Leave home" sem "the". Horário: "seven thirty".'),
        ],
      },
      {
        id: 'lesson-routine-a2-02',
        chapter: 2,
        title: 'Tarefas de casa',
        description: 'Quem faz o quê na casa.',
        units: [
          s('I do the laundry on Saturdays.', 'Lavo roupa aos sábados.', '"Do the laundry" = lavar roupa. Tarefas usam "do".'),
          s('Can you take out the trash?', 'Pode levar o lixo para fora?', '"Take out" = levar para fora. Pedido com "can".'),
          s("It's your turn to do the dishes.", 'É a sua vez de lavar a louça.', '"It\'s your turn to" = é a sua vez de.'),
          s('I need to vacuum the living room.', 'Preciso passar o aspirador na sala.', '"Vacuum" = aspirar. Grafia com dois "u".'),
          s('He is cleaning the bathroom now.', 'Ele está limpando o banheiro agora.', 'Presente contínuo + "now".'),
          s('Who fed the cat?', 'Quem deu comida para o gato?', '"Fed" = passado de "feed" (alimentar). Pergunta com "who" sem "did".'),
          s("I'll water the plants.", 'Eu rego as plantas.', '"Water" como verbo = regar. "Will" para oferta na hora.'),
          s('The house is a mess.', 'A casa está uma bagunça.', '"Mess" = bagunça. "Messy" = bagunçado.'),
          s("Let's clean up before they arrive.", 'Vamos arrumar antes que eles cheguem.', '"Clean up" = arrumar, limpar tudo. Depois de "before", presente.'),
          s('I hate ironing.', 'Odeio passar roupa.', '"Iron" = ferro de passar; o "r" quase some: /ˈaɪərnɪŋ/.'),
        ],
      },
      {
        id: 'lesson-routine-a2-03',
        chapter: 3,
        title: 'Na cozinha',
        description: 'Preparar comida e falar de receitas.',
        units: [
          s("What's for dinner?", 'O que tem para o jantar?', 'Pergunta clássica em casa.'),
          s("I'm making pasta tonight.", 'Vou fazer macarrão hoje à noite.', 'Presente contínuo para plano próximo e combinado.'),
          s('Can you set the table?', 'Pode pôr a mesa?', '"Set the table" = pôr a mesa.'),
          s('Cut the onions into small pieces.', 'Corte as cebolas em pedaços pequenos.', 'Imperativo de receita. "Into" = em (resultado).'),
          s('Boil the water first.', 'Ferva a água primeiro.', '"Boil" = ferver.'),
          s('The oven is preheating.', 'O forno está preaquecendo.', 'Presente contínuo para processo em andamento.'),
          s('It smells delicious.', 'Está com um cheiro delicioso.', '"Smell" + adjetivo = ter cheiro.'),
          s("We're out of eggs.", 'Acabaram os ovos.', '"Be out of" = estar sem.'),
          s('I burned the rice.', 'Queimei o arroz.', 'Passado regular: "burned" (ou "burnt" no Reino Unido).'),
          s('Leftovers are in the fridge.', 'As sobras estão na geladeira.', '"Leftovers" = sobras de comida, sempre plural.'),
        ],
      },
      {
        id: 'lesson-routine-a2-04',
        chapter: 4,
        title: 'Hábitos e frequência',
        description: 'Com que frequência você faz as coisas.',
        units: [
          s('I always drink water in the morning.', 'Sempre bebo água de manhã.', 'Escala: always (100%), usually, often, sometimes, rarely, never (0%).'),
          s('I often work late.', 'Muitas vezes trabalho até tarde.', '"Often" = com frequência; o "t" costuma ser mudo.'),
          s('She sometimes cooks for her neighbors.', 'Às vezes ela cozinha para os vizinhos.', '"Sometimes" pode ir no começo ou antes do verbo.'),
          s('We rarely eat out.', 'Raramente comemos fora.', '"Eat out" = comer fora.'),
          s('He never skips breakfast.', 'Ele nunca pula o café da manhã.', '"Skip" = pular, deixar de fazer.'),
          s('How often do you go to the gym?', 'Com que frequência você vai à academia?', '"How often" pergunta frequência.'),
          s('Twice a week.', 'Duas vezes por semana.', '"Once" = uma vez, "twice" = duas vezes, depois "three times".'),
          s("I'm usually in bed by eleven.", 'Geralmente estou na cama às onze.', 'Com "to be", o advérbio vem depois do verbo: "I\'m usually".'),
          s('I used to smoke, but I quit.', 'Eu fumava, mas parei.', '"Used to" = costumava (hábito do passado que acabou).'),
          s("I'm trying to sleep more.", 'Estou tentando dormir mais.', 'Presente contínuo para mudança em andamento.'),
        ],
      },
      {
        id: 'lesson-routine-a2-05',
        chapter: 5,
        title: 'Fim de semana',
        description: 'Contar o que você fez no passado.',
        units: [
          s('What did you do last weekend?', 'O que você fez no fim de semana passado?', 'Pergunta no passado: "did" + verbo base.'),
          s('I stayed home and relaxed.', 'Fiquei em casa e descansei.', 'Passados regulares: "stayed", "relaxed".'),
          s('We went to my parents\' house.', 'Fomos à casa dos meus pais.', '"Parents\' house": apóstrofo depois do "s" no plural.'),
          s('I watched a series all day.', 'Assisti a uma série o dia todo.', '"Series" é igual no singular e no plural.'),
          s('We had a barbecue with friends.', 'Fizemos um churrasco com amigos.', '"Have a barbecue" = fazer churrasco.'),
          s("I didn't do much.", 'Não fiz muita coisa.', 'Negativa no passado: "didn\'t" + verbo base.'),
          s('It rained the whole weekend.', 'Choveu o fim de semana inteiro.', '"The whole" = inteiro.'),
          s('We slept in on Sunday.', 'Dormimos até tarde no domingo.', '"Sleep in" = dormir até tarde. Passado irregular: "slept".'),
          s('Did you have fun?', 'Você se divertiu?', '"Have fun" = divertir-se.'),
          s('It went by so fast.', 'Passou muito rápido.', '"Go by" = passar (tempo). Passado: "went by".'),
        ],
      },
      {
        id: 'lesson-routine-a2-06',
        chapter: 6,
        title: 'Planos e agenda',
        description: 'Falar do que você vai fazer com going to.',
        units: [
          s("I'm going to visit my grandmother on Sunday.", 'Vou visitar minha avó no domingo.', '"Going to" + verbo = plano já decidido.'),
          s('What are you going to do tonight?', 'O que você vai fazer hoje à noite?', 'Pergunta com "going to": "are you going to…".'),
          s("We're not going to travel this year.", 'Não vamos viajar este ano.', 'Negativa: "not going to".'),
          s("It's going to rain.", 'Vai chover.', '"Going to" também é previsão com evidência (céu escuro).'),
          s("I'm meeting Ana at five.", 'Vou encontrar a Ana às cinco.', 'Presente contínuo para compromisso marcado.'),
          s("I'm free on Thursday.", 'Estou livre na quinta.', '"Free" = disponível.'),
          s("I'm busy until noon.", 'Estou ocupado até o meio-dia.', '"Until" = até (tempo).'),
          s("Let's plan something for Saturday.", 'Vamos planejar algo para sábado.', '"Let\'s" + verbo para sugerir.'),
          s("I'll check my calendar.", 'Vou ver minha agenda.', '"Will" para decisão na hora. "Calendar" = agenda.'),
          s('Maybe next week.', 'Talvez semana que vem.', 'Resposta curta e educada para adiar.'),
        ],
      },
    ],
  },
];
