// Lote ruas-1: Inglês das Ruas & Gírias Reais, capítulos 5–12. Cada nota diz o
// registro (neutro, informal, gíria) e, quando for expressão, o sentido literal
// × o sentido real. Conteúdo original.

export const LEXICON = {
  gimme: ['verb', '/ˈɡɪmi/', 'me dá (give me)'],
  lemme: ['verb', '/ˈlɛmi/', 'deixa eu (let me)'],
  sounds: ['verb', '/saʊndz/', 'soa, parece'],
  "what're": ['pronoun', '/ˈwʌtər/', 'o que (what are)'],
  "you've": ['pronoun', '/juːv/', 'você tem (you have)'],
  afford: ['verb', '/əˈfɔːrd/', 'ter condição de pagar'],
  agree: ['verb', '/əˈɡriː/', 'concordar'],
  amazing: ['adjective', '/əˈmeɪzɪŋ/', 'incrível'],
  awesome: ['adjective', '/ˈɔːsəm/', 'demais, incrível'],
  beat: ['adjective', '/biːt/', 'exausto (gíria)'],
  bit: ['noun', '/bɪt/', 'pouco (a bit = um pouco)'],
  boat: ['noun', '/boʊt/', 'barco'],
  bucks: ['noun', '/bʌks/', 'dólares (gíria)'],
  cake: ['noun', '/keɪk/', 'bolo'],
  chill: ['verb', '/tʃɪl/', 'relaxar (gíria)'],
  costs: ['verb', '/kɔːsts/', 'custa'],
  deal: ['noun', '/diːl/', 'negócio, coisa'],
  dunno: ['verb', '/dəˈnoʊ/', "não sei (don't know)"],
  ears: ['noun', '/ɪrz/', 'ouvidos, orelhas'],
  easy: ['adjective', '/ˈiːzi/', 'fácil, tranquilo'],
  excited: ['adjective', '/ɪkˈsaɪtɪd/', 'animado, empolgado'],
  fan: ['noun', '/fæn/', 'fã'],
  feeling: ['verb', '/ˈfiːlɪŋ/', 'sentindo'],
  finish: ['verb', '/ˈfɪnɪʃ/', 'terminar'],
  freaking: ['verb', '/ˈfriːkɪŋ/', 'surtando (freak out)'],
  gonna: ['verb', '/ˈɡʌnə/', 'vou, vai (going to)'],
  gotta: ['verb', '/ˈɡɑːtə/', 'tenho que (got to)'],
  hanging: ['verb', '/ˈhæŋɪŋ/', 'pendurado; aguentando'],
  hit: ['verb', '/hɪt/', 'bater, pegar'],
  huge: ['adjective', '/hjuːdʒ/', 'enorme'],
  kinda: ['adverb', '/ˈkaɪndə/', 'meio, um pouco (kind of)'],
  mood: ['noun', '/muːd/', 'humor, clima'],
  nailed: ['verb', '/neɪld/', 'acertou em cheio'],
  over: ['preposition', '/ˈoʊvər/', 'por cima; superado'],
  piece: ['noun', '/piːs/', 'pedaço'],
  pricey: ['adjective', '/ˈpraɪsi/', 'caro (informal)'],
  'rip-off': ['noun', '/ˈrɪpɔːf/', 'preço abusivo'],
  road: ['noun', '/roʊd/', 'estrada'],
  rocket: ['noun', '/ˈrɑːkɪt/', 'foguete'],
  same: ['adjective', '/seɪm/', 'mesmo'],
  science: ['noun', '/ˈsaɪəns/', 'ciência'],
  steal: ['noun', '/stiːl/', 'pechincha; roubar'],
  stressed: ['adjective', '/strɛst/', 'estressado'],
  than: ['conjunction', '/ðæn/', 'do que'],
  worries: ['noun', '/ˈwɜːriz/', 'preocupações'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-street-a1',
    slug: 'street-english-slang-a1',
    title: 'Inglês das Ruas & Gírias Reais',
    level: 'A1',
    category: 'street-slang',
    track: 'dia-a-dia',
    trackOrder: 1,
    order: 1,
    short: 'Gírias, reduções da fala e expressões que nativos usam de verdade, com o registro e o sentido real de cada uma.',
    long: 'Frases curtas do cotidiano com gírias frequentes ("what\'s up", "my bad", "I\'m down"), reduções ("gonna", "wanna", "gotta"), mensagens, dinheiro, cansaço, expressões idiomáticas e como discordar. Cada nota explica o registro (informal ou gíria) e o sentido literal × o real.',
    lessons: [
      {
        id: 'lesson-street-a1-05',
        chapter: 5,
        title: 'Elogios e empolgação',
        description: 'Reagir com entusiasmo do jeito nativo.',
        units: [
          s("That's awesome!", 'Que demais!', 'Informal. "Awesome" = incrível; nos EUA é usado para quase tudo que é bom.'),
          s('This place is amazing.', 'Este lugar é incrível.', 'Neutro. "Amazing" é mais forte que "good" e cabe em qualquer situação.'),
          s('You look great today.', 'Você está ótimo hoje.', 'Neutro. Elogio comum; "look" + adjetivo = estar com aparência.'),
          s("I'm so excited!", 'Estou muito animado!', 'Neutro. Falso cognato: "excited" = animado, empolgado (não tem sentido sexual).'),
          s('That was sick!', 'Aquilo foi irado!', 'Gíria. Literal: "doente". Real: incrível, muito bom. Evite em contexto formal.'),
          s('Nice job!', 'Mandou bem!', 'Informal. Elogio rápido por algo bem feito. Também "Good job!".'),
          s('You nailed it.', 'Você arrasou.', 'Informal. Literal: "você pregou (o prego)". Real: acertou em cheio.'),
          s("I'm a huge fan.", 'Sou muito fã.', 'Neutro. "Huge" = enorme, reforça "fan".'),
          s('That sounds like a plan.', 'Fechado, combinado.', 'Informal. Literal: "isso soa como um plano". Real: concordo, vamos fazer.'),
          s('Way to go!', 'Isso aí!', 'Informal. Literal: "caminho a seguir". Real: parabéns pelo feito.'),
        ],
      },
      {
        id: 'lesson-street-a1-06',
        chapter: 6,
        title: 'Reduções da fala',
        description: 'Gonna, wanna, gotta e outras formas que você vai ouvir sempre.',
        units: [
          s("I'm gonna be late.", 'Vou me atrasar.', 'Informal. "Gonna" = "going to". Na escrita formal use "going to".'),
          s('Do you wanna come?', 'Quer vir?', 'Informal. "Wanna" = "want to". Só antes de verbo.'),
          s('I gotta go.', 'Tenho que ir.', 'Informal. "Gotta" = "have got to" (ter que).'),
          s('Lemme see.', 'Deixa eu ver.', 'Informal. "Lemme" = "let me".'),
          s("I dunno.", 'Sei lá.', 'Informal. "Dunno" = "don\'t know". Muito comum na fala rápida.'),
          s("It's kinda cold.", 'Está meio frio.', 'Informal. "Kinda" = "kind of" = meio, um pouco.'),
          s('Gimme a second.', 'Me dá um segundo.', 'Informal. "Gimme" = "give me".'),
          s("What're you doing?", 'O que você está fazendo?', 'Informal. "What\'re" = "what are"; na fala soa "whaddaya".'),
          s("I've gotta finish this.", 'Tenho que terminar isto.', 'Informal. "I\'ve gotta" = "I have got to".'),
          s('Wanna grab a coffee?', 'Bora tomar um café?', 'Informal. Sem sujeito: "(Do you) wanna…". "Grab" = pegar rapidinho.'),
        ],
      },
      {
        id: 'lesson-street-a1-07',
        chapter: 7,
        title: 'Mensagens de texto',
        description: 'Frases curtas que nativos mandam no celular.',
        units: [
          s("Text me when you're there.", 'Me manda mensagem quando chegar.', 'Neutro. "Text" como verbo = mandar mensagem.'),
          s('Just checking in.', 'Só passando para saber como você está.', 'Neutro. Abre uma mensagem sem motivo urgente.'),
          s('Sorry, just saw this.', 'Desculpa, acabei de ver.', 'Informal. Sujeito omitido ("I just saw this"), típico de mensagem.'),
          s('Talk soon.', 'Até mais.', 'Informal. Encerra a conversa: "falamos logo".'),
          s('Sounds good.', 'Beleza.', 'Informal. Resposta curtíssima para concordar.'),
          s("I'm on it.", 'Já estou vendo isso.', 'Informal. Literal: "estou em cima disso". Real: já estou resolvendo.'),
          s('No worries.', 'De boa.', 'Informal. Responde a "sorry" ou "thanks": sem problema.'),
          s('Call me when you can.', 'Me liga quando puder.', 'Neutro. Pedido sem pressa.'),
          s("Can't talk now, I'm in a meeting.", 'Não posso falar agora, estou numa reunião.', 'Neutro. Sujeito omitido no começo, comum em mensagem.'),
          s('Let me know.', 'Me avisa.', 'Neutro. Fecha pedidos: "Let me know if you can come".'),
        ],
      },
      {
        id: 'lesson-street-a1-08',
        chapter: 8,
        title: 'Dinheiro na gíria',
        description: 'Falar de preço, grana e contas como nativo.',
        units: [
          s("I'm broke.", 'Estou duro.', 'Gíria. Literal: "estou quebrado". Real: sem dinheiro.'),
          s('It costs twenty bucks.', 'Custa vinte pratas.', 'Informal. "Bucks" = dólares. Não se usa para outras moedas no dia a dia.'),
          s("That's a rip-off.", 'Isso é um roubo.', 'Informal. "Rip-off" = preço abusivo.'),
          s('It was a steal.', 'Saiu barato demais.', 'Informal. Literal: "foi um roubo". Real: pechincha (o oposto de "rip-off").'),
          s("It's on me.", 'Deixa que eu pago.', 'Informal. Literal: "está em mim". Real: eu pago a conta.'),
          s("Let's split it.", 'Vamos dividir.', 'Neutro. "Split" = dividir a conta.'),
          s("It's a bit pricey.", 'Está um pouco caro.', 'Informal. "Pricey" = caro, mais leve que "expensive".'),
          s("I can't afford it.", 'Não tenho como pagar.', 'Neutro. "Afford" = ter condição de pagar.'),
          s('She makes good money.', 'Ela ganha bem.', 'Informal. "Make money" = ganhar dinheiro (nunca "win money" para salário).'),
          s("I'll pay you back tomorrow.", 'Te devolvo amanhã.', 'Neutro. "Pay back" = devolver dinheiro emprestado.'),
        ],
      },
      {
        id: 'lesson-street-a1-09',
        chapter: 9,
        title: 'Cansaço, estresse e humor',
        description: 'Dizer como você está sem soar como livro didático.',
        units: [
          s("I'm beat.", 'Estou morto de cansado.', 'Gíria. Literal: "estou batido". Real: exausto.'),
          s("I'm stressed out.", 'Estou estressado.', 'Informal. "Stressed out" é mais natural que só "stressed".'),
          s("I'm freaking out.", 'Estou surtando.', 'Gíria. "Freak out" = entrar em pânico, ficar muito nervoso.'),
          s('Just chill.', 'Relaxa.', 'Gíria. "Chill" = relaxar; "chill out" também.'),
          s("I'm not in the mood.", 'Não estou no clima.', 'Neutro. "In the mood (for)" = com vontade de.'),
          s("I'm feeling under the weather.", 'Estou meio indisposto.', 'Informal. Literal: "sob o tempo". Real: meio doente.'),
          s("I'm so done.", 'Cansei.', 'Gíria. "Done" = farto, sem paciência.'),
          s('Take it easy.', 'Vai com calma.', 'Informal. Também serve como despedida: "fica bem".'),
          s("It's been a long day.", 'O dia foi longo.', 'Neutro. Present perfect para o dia que ainda não acabou.'),
          s("I'm hanging in there.", 'Estou levando.', 'Informal. Literal: "estou pendurado aí". Real: aguentando firme.'),
        ],
      },
      {
        id: 'lesson-street-a1-10',
        chapter: 10,
        title: 'Expressões idiomáticas do dia a dia',
        description: 'Frases que não dá para traduzir palavra por palavra.',
        units: [
          s("It's a piece of cake.", 'É moleza.', 'Informal. Literal: "é um pedaço de bolo". Real: muito fácil.'),
          s('Break a leg!', 'Boa sorte!', 'Informal. Literal: "quebre uma perna". Real: boa sorte (antes de apresentação).'),
          s("Let's call it a day.", 'Vamos encerrar por hoje.', 'Informal. Literal: "vamos chamar de um dia". Real: parar de trabalhar.'),
          s("It's not rocket science.", 'Não é nenhum bicho de sete cabeças.', 'Informal. Literal: "não é ciência de foguete". Real: não é difícil.'),
          s("I'll keep an eye on it.", 'Vou ficar de olho.', 'Neutro. Mesmo sentido do português.'),
          s('Better late than never.', 'Antes tarde do que nunca.', 'Neutro. Provérbio igual ao português.'),
          s('We are in the same boat.', 'Estamos no mesmo barco.', 'Neutro. Mesmo sentido do português.'),
          s("Let's hit the road.", 'Vamos pegar a estrada.', 'Informal. Literal: "vamos bater na estrada". Real: vamos embora.'),
          s("It costs an arm and a leg.", 'Custa os olhos da cara.', 'Informal. Literal: "custa um braço e uma perna". Real: muito caro.'),
          s("I'm all ears.", 'Sou todo ouvidos.', 'Informal. Mesmo sentido do português.'),
        ],
      },
      {
        id: 'lesson-street-a1-11',
        chapter: 11,
        title: 'Discordar e reclamar',
        description: 'Dizer não, discordar e reclamar sem ser grosso.',
        units: [
          s("I don't think so.", 'Acho que não.', 'Neutro. Discordância suave. Nunca "I think not" na fala do dia a dia.'),
          s("I'm not so sure.", 'Não tenho tanta certeza.', 'Neutro. Discorda sem confronto.'),
          s("That's not what I meant.", 'Não foi isso que eu quis dizer.', 'Neutro. "Meant" = passado de "mean".'),
          s('Give me a break.', 'Me poupe.', 'Informal. Literal: "me dá uma pausa". Real: não acredito, fala sério.'),
          s("It's not a big deal.", 'Não é nada demais.', 'Informal. "Big deal" = coisa importante.'),
          s("I'm over it.", 'Já superei.', 'Informal. Literal: "estou por cima disso". Real: não me incomoda mais.'),
          s("That's not fair.", 'Isso não é justo.', 'Neutro. "Fair" = justo.'),
          s("You've got a point.", 'Você tem razão nisso.', 'Informal. Concorda em parte: "faz sentido o que você disse".'),
          s("Let's agree to disagree.", 'Vamos concordar em discordar.', 'Neutro. Encerra a discussão com educação.'),
          s('Come on!', 'Qual é!', 'Informal. Pode ser incentivo ("vamos!") ou reclamação ("ah, fala sério!"), depende do tom.'),
        ],
      },
      {
        id: 'lesson-street-a1-12',
        chapter: 12,
        title: 'Revisão: gírias em conversa',
        description: 'Uma frase de cada capítulo do curso.',
        units: [
          s("What's up?", 'E aí?', 'Revisão de cumprimentos. Resposta: "Not much, you?".'),
          s("Sure, I'm down.", 'Claro, tô dentro.', 'Revisão de combinar programa. "I\'m down" = topo.'),
          s('No way!', 'Não acredito!', 'Revisão de reações. Literal: "nenhum jeito".'),
          s('Thanks, I owe you one.', 'Valeu, te devo uma.', 'Revisão de favores.'),
          s('You nailed it.', 'Você arrasou.', 'Revisão de elogios.'),
          s("I'm gonna grab a coffee.", 'Vou pegar um café.', 'Revisão de reduções: "gonna" + "grab".'),
          s('No worries, talk soon.', 'De boa, falamos logo.', 'Revisão de mensagens.'),
          s("I'm broke this month.", 'Estou duro este mês.', 'Revisão de dinheiro.'),
          s("I'm beat, let's call it a day.", 'Estou morto, vamos encerrar por hoje.', 'Revisão de cansaço e expressões idiomáticas.'),
          s("It's not a big deal.", 'Não é nada demais.', 'Revisão de discordar sem brigar.'),
        ],
      },
    ],
  },
];
