// Lote saude-1: curso novo "Saúde e Bem-estar" (A2, trilha Dia a dia),
// capítulos 1–6. Conteúdo original; não substitui orientação médica.

export const LEXICON = {
  avoid: ['verb', '/əˈvɔɪd/', 'evitar'],
  rinse: ['verb', '/rɪns/', 'enxaguar'],
  stretch: ['verb', '/strɛtʃ/', 'alongar'],
  visiting: ['adjective', '/ˈvɪzɪtɪŋ/', 'de visita'],
  admitted: ['verb', '/ədˈmɪtɪd/', 'internado, admitido'],
  alcohol: ['noun', '/ˈælkəhɔːl/', 'álcool'],
  allergy: ['noun', '/ˈælərdʒi/', 'alergia'],
  appointment: ['noun', '/əˈpɔɪntmənt/', 'consulta, horário marcado'],
  blood: ['noun', '/blʌd/', 'sangue'],
  cavity: ['noun', '/ˈkævəti/', 'cárie'],
  copy: ['noun', '/ˈkɑːpi/', 'cópia'],
  cough: ['noun', '/kɔːf/', 'tosse'],
  cutting: ['verb', '/ˈkʌtɪŋ/', 'cortando, diminuindo'],
  dizzy: ['adjective', '/ˈdɪzi/', 'tonto'],
  earliest: ['adjective', '/ˈɜːrliɪst/', 'mais cedo'],
  emergency: ['noun', '/ɪˈmɜːrdʒənsi/', 'emergência'],
  fill: ['verb', '/fɪl/', 'preencher; obturar'],
  form: ['noun', '/fɔːrm/', 'formulário'],
  gets: ['verb', '/ɡɛts/', 'fica'],
  health: ['noun', '/hɛlθ/', 'saúde'],
  hurt: ['verb', '/hɜːrt/', 'doer, machucar'],
  hurts: ['verb', '/hɜːrts/', 'dói'],
  medicines: ['noun', '/ˈmɛdɪsənz/', 'remédios'],
  membership: ['noun', '/ˈmɛmbərʃɪp/', 'matrícula, plano'],
  needs: ['verb', '/niːdz/', 'precisa'],
  pill: ['noun', '/pɪl/', 'comprimido'],
  pregnant: ['adjective', '/ˈprɛɡnənt/', 'grávida'],
  prescribe: ['verb', '/prɪˈskraɪb/', 'receitar'],
  pressure: ['noun', '/ˈprɛʃər/', 'pressão'],
  records: ['noun', '/ˈrɛkərdz/', 'registros, prontuário'],
  reschedule: ['verb', '/ˌriːˈskɛdʒuːl/', 'remarcar'],
  rest: ['verb', '/rɛst/', 'descansar'],
  runny: ['adjective', '/ˈrʌni/', 'escorrendo'],
  seems: ['verb', '/siːmz/', 'parece'],
  sensitive: ['adjective', '/ˈsɛnsətɪv/', 'sensível'],
  shape: ['noun', '/ʃeɪp/', 'forma'],
  test: ['noun', '/tɛst/', 'exame, teste'],
  tests: ['noun', '/tɛsts/', 'exames'],
  toothache: ['noun', '/ˈtuːθeɪk/', 'dor de dente'],
  wide: ['adverb', '/waɪd/', 'bem aberto, largo'],
  worse: ['adjective', '/wɜːrs/', 'pior'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-health-a2',
    slug: 'health-a2',
    title: 'Saúde e Bem-estar',
    level: 'A2',
    category: 'survival',
    track: 'dia-a-dia',
    trackOrder: 4,
    order: 6,
    short: 'Marcar consulta, explicar sintomas, entender a receita, ir ao dentista, cuidar do corpo e lidar com o hospital.',
    long: 'O inglês que você precisa quando o assunto é saúde: marcar horário, descrever o que sente, entender o que o médico diz, dentista, academia e seguro saúde. Cada frase explica a estrutura ou a expressão usada.',
    lessons: [
      {
        id: 'lesson-health-a2-01',
        chapter: 1,
        title: 'Marcando consulta',
        description: 'Ligar, pedir horário e confirmar.',
        units: [
          s("I'd like to make an appointment.", 'Eu gostaria de marcar uma consulta.', '"Make an appointment" = marcar horário (médico, dentista, cabeleireiro).'),
          s('Is the doctor available tomorrow?', 'O médico tem horário amanhã?', '"Available" = disponível.'),
          s("What's the earliest appointment?", 'Qual é o horário mais cedo?', 'Superlativo: "early" → "earliest".'),
          s('Is this your first visit?', 'É a sua primeira consulta?', '"Visit" = consulta, visita.'),
          s('Do you have health insurance?', 'Você tem plano de saúde?', '"Health insurance" = plano/seguro saúde.'),
          s('Please arrive fifteen minutes early.', 'Por favor, chegue quinze minutos antes.', 'Instrução comum da recepção.'),
          s('I need to reschedule my appointment.', 'Preciso remarcar minha consulta.', '"Reschedule" = remarcar.'),
          s('Can I cancel for Friday?', 'Posso cancelar a de sexta?', '"For Friday" = a marcada para sexta.'),
          s('Please fill out this form.', 'Por favor, preencha este formulário.', '"Fill out" = preencher (EUA); Reino Unido: "fill in".'),
          s('The doctor will see you now.', 'O médico vai te atender agora.', '"See" = atender (paciente).'),
        ],
      },
      {
        id: 'lesson-health-a2-02',
        chapter: 2,
        title: 'No médico: sintomas',
        description: 'Descrever o que você sente e há quanto tempo.',
        units: [
          s('What seems to be the problem?', 'Qual parece ser o problema?', 'Pergunta de abertura do médico.'),
          s("I've had a headache for three days.", 'Estou com dor de cabeça há três dias.', 'Present perfect + "for" = há (ainda sente).'),
          s('My back hurts when I sit.', 'Minhas costas doem quando sento.', '"Hurt" = doer. "My back hurts" (costas no singular).'),
          s('I feel dizzy.', 'Estou tonto.', '"Dizzy" = tonto.'),
          s("I can't sleep at night.", 'Não consigo dormir à noite.', '"Can\'t" = não consigo.'),
          s('I have a runny nose and a cough.', 'Estou com o nariz escorrendo e tosse.', '"Runny nose" = coriza. "Cough" = tosse, /kɔːf/.'),
          s("I think it's an allergy.", 'Acho que é alergia.', '"Allergy" = alergia; força no começo: AL-ler-gy.'),
          s('Does it hurt here?', 'Dói aqui?', 'Pergunta do médico durante o exame.'),
          s("I'm allergic to some medicines.", 'Tenho alergia a alguns remédios.', 'Diga sempre antes de receber receita.'),
          s("I'm pregnant.", 'Estou grávida.', 'Falso cognato: grávida é "pregnant", não "embarrassed".'),
        ],
      },
      {
        id: 'lesson-health-a2-03',
        chapter: 3,
        title: 'Exames, receita e tratamento',
        description: 'Entender o que o médico manda fazer.',
        units: [
          s("I'm going to prescribe some medicine.", 'Vou receitar um remédio.', '"Prescribe" = receitar. "Prescription" = receita.'),
          s('Take one pill twice a day.', 'Tome um comprimido duas vezes ao dia.', '"Twice a day" = duas vezes ao dia.'),
          s('Take it with food.', 'Tome junto com comida.', 'Instrução comum de remédio.'),
          s('Avoid alcohol while taking this.', 'Evite álcool enquanto tomar isto.', '"Avoid" + substantivo ou verbo com "-ing".'),
          s('We need to run some tests.', 'Precisamos fazer alguns exames.', '"Run tests" = fazer exames.'),
          s('You need a blood test.', 'Você precisa de um exame de sangue.', '"Blood test" = exame de sangue.'),
          s('The results will be ready on Monday.', 'Os resultados ficam prontos na segunda.', 'Futuro com "will".'),
          s('You should rest for a few days.', 'Você deveria descansar alguns dias.', '"Should" = recomendação.'),
          s('Come back if it gets worse.', 'Volte se piorar.', '"Get worse" = piorar; "get better" = melhorar.'),
          s('Is it serious?', 'É grave?', '"Serious" = grave (em saúde) ou sério.'),
        ],
      },
      {
        id: 'lesson-health-a2-04',
        chapter: 4,
        title: 'No dentista',
        description: 'Dor de dente, limpeza e tratamento.',
        units: [
          s('I have a toothache.', 'Estou com dor de dente.', '"Toothache" = dor de dente, uma palavra só.'),
          s('My tooth is sensitive to cold.', 'Meu dente está sensível ao frio.', '"Sensitive" = sensível. Falso cognato de "sensible" (sensato).'),
          s("I'd like a cleaning.", 'Eu gostaria de fazer uma limpeza.', '"Cleaning" = limpeza (profilaxia).'),
          s('Open wide, please.', 'Abra bem, por favor.', 'Instrução do dentista.'),
          s('You have a cavity.', 'Você tem uma cárie.', '"Cavity" = cárie.'),
          s('We need to fill it.', 'Precisamos obturar.', '"Fill" = obturar; "filling" = obturação.'),
          s('Will it hurt?', 'Vai doer?', 'Pergunta com "will" antes do sujeito.'),
          s("You'll feel a little pressure.", 'Você vai sentir uma leve pressão.', 'Futuro com "will" contraído.'),
          s('Rinse your mouth, please.', 'Enxágue a boca, por favor.', '"Rinse" = enxaguar.'),
          s("Don't eat for two hours.", 'Não coma por duas horas.', 'Imperativo negativo + "for" + tempo.'),
        ],
      },
      {
        id: 'lesson-health-a2-05',
        chapter: 5,
        title: 'Academia e bem-estar',
        description: 'Exercício, sono e alimentação.',
        units: [
          s("I'm trying to get in shape.", 'Estou tentando entrar em forma.', '"Get in shape" = entrar em forma.'),
          s('I work out three times a week.', 'Treino três vezes por semana.', '"Work out" = malhar, treinar.'),
          s('How much does a membership cost?', 'Quanto custa a mensalidade?', '"Membership" = matrícula, plano de academia.'),
          s('Can you show me how to use this machine?', 'Pode me mostrar como usar esta máquina?', '"How to" + verbo = como fazer.'),
          s("I'm sore from yesterday.", 'Estou dolorido de ontem.', '"Sore" = dolorido (músculo).'),
          s('I need to drink more water.', 'Preciso beber mais água.', '"More" + substantivo.'),
          s("I'm cutting down on sugar.", 'Estou diminuindo o açúcar.', '"Cut down on" = diminuir o consumo de.'),
          s('I sleep about seven hours a night.', 'Durmo umas sete horas por noite.', '"About" = mais ou menos. "A night" = por noite.'),
          s('Stretch before you run.', 'Alongue antes de correr.', '"Stretch" = alongar.'),
          s('I feel much better now.', 'Me sinto muito melhor agora.', '"Much" reforça comparativo: "much better".'),
        ],
      },
      {
        id: 'lesson-health-a2-06',
        chapter: 6,
        title: 'Hospital e seguro saúde',
        description: 'Pronto-socorro, internação e cobertura.',
        units: [
          s('Where is the emergency room?', 'Onde fica o pronto-socorro?', '"Emergency room" (ER) = pronto-socorro.'),
          s('He needs to see a doctor right now.', 'Ele precisa ver um médico agora.', '"Right now" = agora mesmo.'),
          s('How long is the wait?', 'Quanto tempo de espera?', 'Pergunta comum no pronto-socorro.'),
          s('She was admitted last night.', 'Ela foi internada ontem à noite.', '"Be admitted" = ser internado.'),
          s('Visiting hours are from two to eight.', 'O horário de visita é das duas às oito.', '"From… to…" = de… a….'),
          s('Does my insurance cover this?', 'Meu plano cobre isso?', '"Cover" = cobrir (seguro).'),
          s('Here is my insurance card.', 'Aqui está a carteirinha do plano.', '"Insurance card" = carteirinha do plano.'),
          s('Can I get a copy of my records?', 'Posso ter uma cópia do meu prontuário?', '"Medical records" = prontuário.'),
          s('When can he go home?', 'Quando ele pode ir para casa?', '"Go home" sem "to".'),
          s('Get well soon!', 'Melhoras!', 'Expressão fixa para desejar recuperação.'),
        ],
      },
    ],
  },
];
