// Lote sobrevivencia-1: curso novo "Sobrevivência" (A2, trilha Dia a dia),
// capítulos 1–10. Frases para se virar quando o inglês falha e para resolver
// burocracia do dia a dia. Conteúdo original.

export const LEXICON = {
  atm: ["noun", "/ˌeɪtiːˈɛm/", "caixa eletrônico"],
  b: ["noun", "/biː/", "letra B"],
  c: ["noun", "/siː/", "letra C"],
  k: ["noun", "/keɪ/", "letra K"],
  s: ["noun", "/ɛs/", "letra S"],
  v: ["noun", "/viː/", "letra V"],
  sim: ["noun", "/sɪm/", "SIM (chip)"],
  express: ["adjective", "/ɪkˈsprɛs/", "expresso"],
  birth: ["noun", "/bɜːrθ/", "nascimento"],
  block: ["verb", "/blɑːk/", "bloquear"],
  boy: ["noun", "/bɔɪ/", "menino"],
  broken: ["adjective", "/ˈbroʊkən/", "quebrado"],
  case: ["noun", "/keɪs/", "capa, caso"],
  current: ["adjective", "/ˈkɜːrənt/", "atual"],
  dead: ["adjective", "/dɛd/", "morto; sem bateria"],
  deposit: ["noun", "/dɪˈpɑːzɪt/", "depósito, caução"],
  documents: ["noun", "/ˈdɑːkjəmənts/", "documentos"],
  electricity: ["noun", "/ɪˌlɛkˈtrɪsəti/", "eletricidade, luz"],
  fee: ["noun", "/fiː/", "taxa"],
  fragile: ["adjective", "/ˈfrædʒəl/", "frágil"],
  heater: ["noun", "/ˈhiːtər/", "aquecedor"],
  landlord: ["noun", "/ˈlændlɔːrd/", "proprietário"],
  locksmith: ["noun", "/ˈlɑːksmɪθ/", "chaveiro"],
  patience: ["noun", "/ˈpeɪʃəns/", "paciência"],
  rate: ["noun", "/reɪt/", "taxa"],
  recognize: ["verb", "/ˈrɛkəgnaɪz/", "reconhecer"],
  renew: ["verb", "/rɪˈnuː/", "renovar"],
  restroom: ["noun", "/ˈrɛstruːm/", "banheiro"],
  saved: ["verb", "/seɪvd/", "salvou"],
  stamp: ["noun", "/stæmp/", "selo"],
  standard: ["adjective", "/ˈstændərd/", "padrão"],
  tracking: ["noun", "/ˈtrækɪŋ/", "rastreamento"],
  transfer: ["verb", "/trænsˈfɜːr/", "transferir"],
  utilities: ["noun", "/juːˈtɪlətiz/", "contas de consumo"],
  withdraw: ["verb", "/wɪðˈdrɔː/", "sacar"],
  yours: ["pronoun", "/jʊrz/", "seu, o seu"],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-survival-a2-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-survival-a2',
    slug: 'survival-english-a2',
    title: 'Sobrevivência',
    level: 'A2',
    category: 'survival',
    track: 'dia-a-dia',
    trackOrder: 6,
    order: 14,
    short: 'Quando o inglês falha: pedir para repetir, soletrar, pedir ajuda, resolver banco, correio, documentos e contas.',
    long: 'As frases que salvam quando você não entende ou precisa resolver algo prático: pedir para repetir e soletrar, pedir ajuda, falar ao telefone, banco, correios, documentos, objetos perdidos, moradia e contas. Cada frase explica o uso.',
    lessons: [
      lesson(1, 'Quando você não entende', 'Pedir calma e esclarecimento.', [
        s("Sorry, I didn't understand.", 'Desculpe, não entendi.', 'Passado: "didn\'t understand". Mais natural que "I don\'t understand" depois de ouvir algo.'),
        s('Could you speak more slowly?', 'Você poderia falar mais devagar?', '"More slowly" = mais devagar.'),
        s("I'm still learning English.", 'Ainda estou aprendendo inglês.', 'Avisa e gera paciência do outro lado.'),
        s('What does that mean?', 'O que isso significa?', 'Pergunta sobre uma palavra.'),
        s('Could you say that in another way?', 'Pode dizer de outro jeito?', '"In another way" = de outro jeito.'),
        s('Do you mean tomorrow?', 'Você quer dizer amanhã?', '"Do you mean…?" confirma o que entendeu.'),
        s("I'm not sure I follow.", 'Não sei se estou acompanhando.', '"Follow" = acompanhar o raciocínio.'),
        s('Can you write it down for me?', 'Pode escrever para mim?', '"Write down" = anotar.'),
        s('How do you say this in English?', 'Como se diz isso em inglês?', 'Aponte para o objeto e pergunte.'),
        s('Is there someone who speaks Portuguese?', 'Tem alguém que fala português?', '"Someone who" + verbo.'),
      ]),
      lesson(2, 'Repetir e soletrar', 'Conferir nomes, números e endereços.', [
        s('Sorry, can you repeat that?', 'Desculpe, pode repetir?', 'O pedido mais útil de todos.'),
        s('One more time, please.', 'Mais uma vez, por favor.', 'Forma curta.'),
        s('How do you spell that?', 'Como se escreve isso?', '"Spell" = soletrar.'),
        s('Is that B as in boy?', 'É B de boy?', '"B as in boy" confirma letras que soam parecido.'),
        s('My last name is Silva, S I L V A.', 'Meu sobrenome é Silva, S I L V A.', 'Soletre letra por letra.'),
        s("Sorry, I didn't catch your name.", 'Desculpe, não peguei seu nome.', '"Catch" = entender, pegar (o que foi dito).'),
        s('Could you say the number again?', 'Pode dizer o número de novo?', '"Again" no fim = de novo.'),
        s('Let me check I have it right.', 'Deixa eu conferir se anotei certo.', '"Have it right" = ter entendido certo.'),
        s('Is it with a C or a K?', 'É com C ou com K?', 'Pergunta útil para nomes.'),
        s('Thank you for your patience.', 'Obrigado pela paciência.', '"Patience" = paciência.'),
      ]),
      lesson(3, 'Pedindo ajuda', 'Pedir ajuda a desconhecidos.', [
        s('Excuse me, can you help me?', 'Com licença, pode me ajudar?', 'Abertura educada com estranhos.'),
        s("I'm looking for the train station.", 'Estou procurando a estação de trem.', '"Look for" = procurar.'),
        s('Is it far from here?', 'É longe daqui?', '"Far from" = longe de.'),
        s('Could you show me on the map?', 'Pode me mostrar no mapa?', 'Mostre o celular com o mapa.'),
        s('Where can I buy a SIM card?', 'Onde posso comprar um chip de celular?', '"SIM card" = chip de celular.'),
        s("My phone is dead. Can I use yours?", 'Meu celular descarregou. Posso usar o seu?', '"Dead" = sem bateria.'),
        s('Is there a restroom nearby?', 'Tem banheiro por perto?', '"Restroom" = banheiro público (EUA).'),
        s('Where is the nearest ATM?', 'Onde fica o caixa eletrônico mais próximo?', '"ATM" = caixa eletrônico.'),
        s('Thank you so much, you saved me.', 'Muito obrigado, você me salvou.', 'Agradecimento caloroso.'),
        s('Sorry to bother you.', 'Desculpe incomodar.', '"Bother" = incomodar.'),
      ]),
      lesson(4, 'Ao telefone', 'Ligar, atender e deixar recado.', [
        s('Hello, can I speak to Mr. Brown?', 'Olá, posso falar com o Sr. Brown?', '"Speak to" + pessoa.'),
        s('Who is calling, please?', 'Quem gostaria?', 'Fala de quem atende.'),
        s("This is Ana speaking.", 'Aqui é a Ana.', 'Ao telefone use "this is".'),
        s('Hold on a second, please.', 'Um momento, por favor.', '"Hold on" = aguardar.'),
        s("He's not here right now.", 'Ele não está agora.', '"Right now" = neste momento.'),
        s('Can I leave a message?', 'Posso deixar um recado?', '"Leave a message" = deixar recado.'),
        s('The line is busy.', 'A linha está ocupada.', '"Busy" = ocupado.'),
        s('Sorry, the connection is bad.', 'Desculpe, a ligação está ruim.', '"Connection" = conexão.'),
        s("I'll call back later.", 'Ligo mais tarde.', '"Call back" = retornar a ligação.'),
        s('Thanks for calling.', 'Obrigado por ligar.', 'Encerramento padrão.'),
      ]),
      lesson(5, 'No banco', 'Conta, cartão, transferência e caixa eletrônico.', [
        s("I'd like to open an account.", 'Eu gostaria de abrir uma conta.', '"Open an account" = abrir conta.'),
        s('What documents do I need?', 'Quais documentos eu preciso?', 'Pergunta essencial em qualquer balcão.'),
        s('I want to transfer money to Brazil.', 'Quero transferir dinheiro para o Brasil.', '"Transfer" = transferir.'),
        s("The ATM kept my card.", 'O caixa eletrônico engoliu meu cartão.', '"Keep" = reter. Passado: "kept".'),
        s("I forgot my PIN.", 'Esqueci a senha do cartão.', '"PIN" = senha numérica.'),
        s('Is there a fee?', 'Tem taxa?', '"Fee" = taxa, tarifa.'),
        s('What is the exchange rate?', 'Qual é o câmbio?', '"Exchange rate" = taxa de câmbio.'),
        s('I need to block my card.', 'Preciso bloquear meu cartão.', '"Block" = bloquear.'),
        s("There's a charge I don't recognize.", 'Tem uma cobrança que não reconheço.', '"Recognize" = reconhecer.'),
        s('Can I withdraw cash here?', 'Posso sacar dinheiro aqui?', '"Withdraw" = sacar.'),
      ]),
      lesson(6, 'Nos correios', 'Enviar e receber cartas e pacotes.', [
        s('I want to send this package to Brazil.', 'Quero enviar este pacote para o Brasil.', '"Send to" + destino.'),
        s('How long will it take?', 'Quanto tempo vai levar?', '"Take" + tempo = demorar.'),
        s('How much is it to send a letter?', 'Quanto custa mandar uma carta?', '"How much is it to" + verbo.'),
        s('Can I track it?', 'Posso rastrear?', '"Track" = rastrear.'),
        s('I need a stamp.', 'Preciso de um selo.', '"Stamp" = selo.'),
        s('Please fill out this form.', 'Por favor, preencha este formulário.', '"Fill out" = preencher.'),
        s("I'm here to pick up a package.", 'Vim retirar um pacote.', '"Pick up" = retirar, buscar.'),
        s('Here is the tracking number.', 'Aqui está o código de rastreio.', '"Tracking number" = código de rastreio.'),
        s('Is it fragile?', 'É frágil?', 'Pergunta do atendente.'),
        s('Express or standard?', 'Expresso ou normal?', 'Tipo de envio.'),
      ]),
      lesson(7, 'Documentos e cadastro', 'Formulários, identificação e cadastros.', [
        s('Can I see your ID, please?', 'Posso ver seu documento, por favor?', '"ID" = documento de identidade.'),
        s('Please fill in your full name.', 'Por favor, preencha seu nome completo.', '"Full name" = nome completo.'),
        s("What's your date of birth?", 'Qual sua data de nascimento?', '"Date of birth" = data de nascimento.'),
        s("What's your current address?", 'Qual seu endereço atual?', '"Current" = atual.'),
        s('Sign here, please.', 'Assine aqui, por favor.', '"Sign" = assinar.'),
        s('Do you have a copy of your passport?', 'Você tem uma cópia do passaporte?', '"Copy" = cópia.'),
        s('I need to renew my visa.', 'Preciso renovar meu visto.', '"Renew" = renovar.'),
        s('It will be ready in five business days.', 'Fica pronto em cinco dias úteis.', '"Business days" = dias úteis.'),
        s('Please take a number and wait.', 'Por favor, pegue uma senha e aguarde.', '"Take a number" = pegar senha de atendimento.'),
        s('Which line should I stand in?', 'Em qual fila devo ficar?', '"Stand in line" = ficar na fila.'),
      ]),
      lesson(8, 'Perdeu, esqueceu, quebrou', 'Resolver objetos perdidos e imprevistos.', [
        s('I lost my phone.', 'Perdi meu celular.', 'Passado: "lost".'),
        s("I think I left it on the bus.", 'Acho que deixei no ônibus.', '"Leave" = esquecer em algum lugar. Passado: "left".'),
        s('Is there a lost and found?', 'Tem achados e perdidos?', '"Lost and found" = achados e perdidos.'),
        s("It's a black phone with a blue case.", 'É um celular preto com capinha azul.', 'Descreva cor e detalhe.'),
        s('My key broke in the door.', 'Minha chave quebrou na porta.', '"Break" passado: "broke".'),
        s("I'm locked out.", 'Fiquei trancado do lado de fora.', '"Locked out" = trancado para fora.'),
        s('Can you call a locksmith?', 'Pode chamar um chaveiro?', '"Locksmith" = chaveiro.'),
        s('My flight was changed.', 'Meu voo foi alterado.', 'Voz passiva.'),
        s('I missed my bus.', 'Perdi o ônibus.', '"Miss" = perder (transporte, horário).'),
        s('What should I do now?', 'O que devo fazer agora?', '"Should" = dever (conselho).'),
      ]),
      lesson(9, 'Moradia e contas', 'Aluguel, contas de casa e manutenção.', [
        s("I'm looking for an apartment to rent.", 'Estou procurando um apartamento para alugar.', '"To rent" = para alugar.'),
        s('How much is the rent?', 'Quanto é o aluguel?', '"Rent" = aluguel.'),
        s('Are utilities included?', 'As contas estão incluídas?', '"Utilities" = água, luz, gás.'),
        s('Is there a deposit?', 'Tem caução?', '"Deposit" = caução, depósito.'),
        s('When is the rent due?', 'Quando vence o aluguel?', '"Due" = com vencimento.'),
        s('The heater is broken.', 'O aquecedor está quebrado.', '"Heater" = aquecedor.'),
        s('Can you send someone to fix it?', 'Pode mandar alguém consertar?', 'Pedido ao proprietário.'),
        s('The electricity is off.', 'Está sem luz.', '"Off" = desligado.'),
        s('I need to pay the water bill.', 'Preciso pagar a conta de água.', '"Bill" = conta.'),
        s('The landlord will call you.', 'O proprietário vai te ligar.', '"Landlord" = proprietário (quem aluga).'),
      ]),
      lesson(10, 'Revisão: se virando em inglês', 'Uma frase de cada capítulo.', [
        s('Could you speak more slowly?', 'Poderia falar mais devagar?', 'Revisão: quando não entende.'),
        s('How do you spell that?', 'Como se escreve isso?', 'Revisão: soletrar.'),
        s('Excuse me, can you help me?', 'Com licença, pode me ajudar?', 'Revisão: pedir ajuda.'),
        s('Can I leave a message?', 'Posso deixar um recado?', 'Revisão: telefone.'),
        s('Is there a fee?', 'Tem taxa?', 'Revisão: banco.'),
        s('Can I track it?', 'Posso rastrear?', 'Revisão: correios.'),
        s('Sign here, please.', 'Assine aqui, por favor.', 'Revisão: documentos.'),
        s('Is there a lost and found?', 'Tem achados e perdidos?', 'Revisão: objetos perdidos.'),
        s('Are utilities included?', 'As contas estão incluídas?', 'Revisão: moradia.'),
        s('Thank you for your patience.', 'Obrigado pela paciência.', 'Revisão: fechamento educado.'),
      ]),
    ],
  },
];
