// Lote social-1: curso novo "Vida Social" (A2, trilha Dia a dia), capítulos
// 1–6. Conteúdo original.

export const LEXICON = {
  anyway: ['adverb', '/ˈɛniweɪ/', 'enfim, de qualquer forma'],
  apology: ['noun', '/əˈpɑːlədʒi/', 'pedido de desculpas'],
  "mark's": ['proper noun', '/mɑːrks/', 'do Mark'],
  oh: ['interjection', '/oʊ/', 'ah, oh'],
  accepted: ['verb', '/əkˈsɛptɪd/', 'aceito'],
  brings: ['verb', '/brɪŋz/', 'traz'],
  depends: ['verb', '/dɪˈpɛndz/', 'depende'],
  each: ['determiner', '/iːtʃ/', 'cada'],
  explain: ['verb', '/ɪkˈspleɪn/', 'explicar'],
  fault: ['noun', '/fɔːlt/', 'culpa'],
  feelings: ['noun', '/ˈfiːlɪŋz/', 'sentimentos'],
  finally: ['adverb', '/ˈfaɪnəli/', 'finalmente'],
  hard: ['adjective', '/hɑːrd/', 'duro, difícil'],
  huh: ['interjection', '/hʌ/', 'né?'],
  interesting: ['adjective', '/ˈɪntrəstɪŋ/', 'interessante'],
  inviting: ['verb', '/ɪnˈvaɪtɪŋ/', 'convidar'],
  kind: ['adjective', '/kaɪnd/', 'gentil'],
  means: ['verb', '/miːnz/', 'significa'],
  met: ['verb', '/mɛt/', 'conheceu, encontrou'],
  misunderstood: ['verb', '/ˌmɪsʌndərˈstʊd/', 'entendeu mal'],
  opinion: ['noun', '/əˈpɪnjən/', 'opinião'],
  other: ['pronoun', '/ˈʌðər/', 'outro'],
  pleasure: ['noun', '/ˈplɛʒər/', 'prazer'],
  prefer: ['verb', '/prɪˈfɜːr/', 'preferir'],
  sports: ['noun', '/spɔːrts/', 'esportes'],
  strong: ['adjective', '/strɔːŋ/', 'forte'],
  totally: ['adverb', '/ˈtoʊtəli/', 'totalmente'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-social-a2',
    slug: 'social-life-a2',
    title: 'Vida Social',
    level: 'A2',
    category: 'social',
    track: 'dia-a-dia',
    trackOrder: 5,
    order: 7,
    short: 'Conhecer gente, convidar, puxar conversa, elogiar, dar opinião e pedir desculpas com naturalidade.',
    long: 'As conversas que fazem amizade: apresentar-se e lembrar nomes, convidar e recusar sem ser grosso, conversa fiada, elogios, opiniões e como resolver mal-entendidos. Cada frase explica o registro e a estrutura.',
    lessons: [
      {
        id: 'lesson-social-a2-01',
        chapter: 1,
        title: 'Conhecendo pessoas',
        description: 'Apresentar-se, lembrar nomes e continuar a conversa.',
        units: [
          s("Hi, I don't think we've met.", 'Oi, acho que ainda não nos conhecemos.', 'Neutro. Present perfect: "we\'ve met" = já nos conhecemos.'),
          s("I'm Ana, a friend of Mark's.", 'Sou a Ana, amiga do Mark.', '"A friend of + nome\'s" = amigo de alguém.'),
          s('Sorry, what was your name again?', 'Desculpa, qual era o seu nome mesmo?', 'Neutro. "Again" no fim = mesmo, de novo. Passado "was" suaviza.'),
          s('How do you know each other?', 'De onde vocês se conhecem?', '"Each other" = um ao outro.'),
          s('We went to school together.', 'Estudamos juntos.', 'Passado: "went to school together".'),
          s('What brings you here?', 'O que te traz aqui?', 'Neutro. Pergunta aberta para puxar assunto.'),
          s('Have we met before?', 'Já nos vimos antes?', 'Present perfect em pergunta sobre experiência.'),
          s('I have heard a lot about you.', 'Ouvi falar muito de você.', 'Neutro e simpático; "a lot about" = muito sobre.'),
          s('Let me introduce you to my wife.', 'Deixa eu te apresentar à minha esposa.', '"Introduce to" = apresentar a.'),
          s('Great to finally meet you.', 'Que bom finalmente te conhecer.', '"Finally" = finalmente.'),
        ],
      },
      {
        id: 'lesson-social-a2-02',
        chapter: 2,
        title: 'Convites',
        description: 'Convidar, aceitar e recusar com educação.',
        units: [
          s('Would you like to come to my party?', 'Você gostaria de vir à minha festa?', 'Convite educado: "Would you like to" + verbo.'),
          s("We're having a barbecue on Saturday.", 'Vamos fazer um churrasco no sábado.', 'Presente contínuo para evento marcado.'),
          s("I'd love to!", 'Eu adoraria!', 'Resposta animada: "I\'d love to" (to sem verbo depois).'),
          s("Sorry, I can't make it.", 'Desculpa, não vou conseguir ir.', '"Make it" = conseguir ir, chegar.'),
          s('Maybe another time?', 'Quem sabe outra vez?', 'Recusa suave que deixa a porta aberta.'),
          s('Can I bring a friend?', 'Posso levar um amigo?', '"Bring" = levar junto.'),
          s('Should I bring anything?', 'Devo levar alguma coisa?', 'Pergunta educada do convidado.'),
          s("What's the dress code?", 'Qual é o traje?', '"Dress code" = código de vestimenta.'),
          s('Thanks for inviting me.', 'Obrigado pelo convite.', '"Thanks for" + verbo com "-ing".'),
          s("Let me check and I'll let you know.", 'Deixa eu ver e te aviso.', 'Resposta para ganhar tempo.'),
        ],
      },
      {
        id: 'lesson-social-a2-03',
        chapter: 3,
        title: 'Puxando conversa',
        description: 'Conversa fiada que quebra o gelo.',
        units: [
          s('Nice weather today, huh?', 'Que tempo bom hoje, né?', 'Informal. "Huh?" no fim = né?'),
          s('Have you been here before?', 'Você já veio aqui antes?', 'Present perfect para experiência.'),
          s('How do you like the city so far?', 'O que está achando da cidade até agora?', '"How do you like" = o que você acha. "So far" = até agora.'),
          s('What do you do for fun?', 'O que você faz para se divertir?', '"For fun" = por diversão.'),
          s('Are you into sports?', 'Você curte esporte?', 'Informal. "Be into" = gostar muito de.'),
          s("I've heard great things about this place.", 'Ouvi coisas ótimas sobre este lugar.', 'Present perfect sem data.'),
          s('That sounds interesting.', 'Isso parece interessante.', '"Sound" + adjetivo = parecer (pelo que se ouve).'),
          s('Tell me more.', 'Me conta mais.', 'Mostra interesse e mantém a conversa.'),
          s('Oh really? Me too!', 'Sério? Eu também!', '"Me too" para concordar com afirmativa.'),
          s('Anyway, it was nice talking to you.', 'Bom, foi bom conversar com você.', '"Anyway" encerra ou muda de assunto.'),
        ],
      },
      {
        id: 'lesson-social-a2-04',
        chapter: 4,
        title: 'Elogios e agradecimentos',
        description: 'Elogiar sem exagero e agradecer do jeito certo.',
        units: [
          s('I love your shoes!', 'Amei seus sapatos!', 'Informal. Elogio comum e espontâneo.'),
          s('You look great in that color.', 'Essa cor fica ótima em você.', '"Look great in" + cor/roupa.'),
          s('Your English is really good.', 'Seu inglês é muito bom.', '"Really" reforça o adjetivo.'),
          s('This is delicious, did you make it?', 'Está delicioso, foi você que fez?', 'Elogio + pergunta mantém a conversa.'),
          s('Thanks, that means a lot.', 'Obrigado, isso significa muito.', '"That means a lot" = fico muito grato.'),
          s("You're too kind.", 'Você é muito gentil.', 'Resposta modesta a um elogio.'),
          s('Thank you so much for your help.', 'Muito obrigado pela sua ajuda.', '"So much" reforça o agradecimento.'),
          s('I really appreciate it.', 'Agradeço muito.', '"Appreciate" = agradecer, valorizar.'),
          s("You're welcome.", 'De nada.', 'Resposta padrão a "thank you".'),
          s('My pleasure.', 'Foi um prazer.', 'Resposta mais calorosa que "you\'re welcome".'),
        ],
      },
      {
        id: 'lesson-social-a2-05',
        chapter: 5,
        title: 'Dando opinião',
        description: 'Dizer o que você acha, concordar e discordar.',
        units: [
          s('In my opinion, it was too long.', 'Na minha opinião, foi longo demais.', '"In my opinion" abre uma opinião.'),
          s('I think you are right.', 'Acho que você tem razão.', 'Em inglês "ter razão" é "be right".'),
          s('I totally agree.', 'Concordo totalmente.', '"Agree" já é verbo: nunca "I am agree".'),
          s("I'm not sure I agree.", 'Não sei se concordo.', 'Discordância suave.'),
          s('It depends.', 'Depende.', '"It depends on" + algo.'),
          s('What do you think?', 'O que você acha?', 'Devolve a pergunta e inclui o outro.'),
          s('I see what you mean.', 'Entendo o que você quer dizer.', '"Mean" = querer dizer.'),
          s("That's a good point.", 'Bem lembrado.', 'Reconhece o argumento do outro.'),
          s('To be honest, I prefer the first one.', 'Para ser sincero, prefiro o primeiro.', '"To be honest" suaviza uma opinião direta.'),
          s("I don't have a strong opinion.", 'Não tenho uma opinião forte.', 'Jeito neutro de não entrar na discussão.'),
        ],
      },
      {
        id: 'lesson-social-a2-06',
        chapter: 6,
        title: 'Desculpas e mal-entendidos',
        description: 'Pedir desculpas, esclarecer e fazer as pazes.',
        units: [
          s("I'm sorry, I didn't mean to hurt you.", 'Desculpa, não quis te magoar.', '"Didn\'t mean to" = não tive a intenção de.'),
          s('It was my fault.', 'A culpa foi minha.', '"Fault" = culpa.'),
          s('I think you misunderstood me.', 'Acho que você me entendeu mal.', '"Misunderstand" = entender errado.'),
          s('Let me explain.', 'Deixa eu explicar.', 'Abre o esclarecimento.'),
          s("That's not what I said.", 'Não foi isso que eu disse.', '"What I said" = o que eu disse.'),
          s("No hard feelings.", 'Sem ressentimentos.', 'Informal. Encerra o conflito.'),
          s('Apology accepted.', 'Desculpas aceitas.', 'Resposta direta a um pedido de desculpas.'),
          s("Let's forget about it.", 'Vamos esquecer isso.', '"Forget about" = esquecer (assunto).'),
          s('I owe you an apology.', 'Te devo desculpas.', '"Owe" = dever (algo a alguém).'),
          s("We're good.", 'Está tudo bem entre a gente.', 'Informal. Confirma que o conflito acabou.'),
        ],
      },
    ],
  },
];
