// Lote tempos-2: Tempos Verbais em Uso, capítulos 7–16 (condicionais zero a
// terceiro, voz passiva, discurso indireto, modais de dedução no presente e no
// passado, revisão). Cada nota explica a estrutura e compara com o português.
// Conteúdo original.

export const LEXICON = {
  anna: ["proper noun", "/ˈænə/", "Anna"],
  french: ["noun", "/frɛntʃ/", "francês"],
  paris: ["proper noun", "/ˈpærɪs/", "Paris"],
  porto: ["proper noun", "/ˈpɔːrtoʊ/", "Porto"],
  recife: ["proper noun", "/rɛˈsiːfeɪ/", "Recife"],
  accept: ["verb", "/əkˈsɛpt/", "aceitar"],
  announced: ["verb", "/əˈnaʊnst/", "anunciado"],
  anywhere: ["adverb", "/ˈɛniwɛr/", "em qualquer lugar"],
  caught: ["verb", "/kɔːt/", "pegou, pegado"],
  cleaned: ["verb", "/kliːnd/", "limpo"],
  closer: ["adverb", "/ˈkloʊsər/", "mais perto"],
  "couldn't": ["verb", "/ˈkʊdənt/", "não podia (could not)"],
  earlier: ["adverb", "/ˈɜːrliər/", "mais cedo, antes"],
  fired: ["verb", "/ˈfaɪərd/", "demitido"],
  invited: ["verb", "/ɪnˈvaɪtɪd/", "convidado"],
  joking: ["verb", "/ˈdʒoʊkɪŋ/", "brincando"],
  lottery: ["noun", "/ˈlɑːtəri/", "loteria"],
  melts: ["verb", "/mɛlts/", "derrete"],
  must: ["verb", "/mʌst/", "dever, ter que"],
  painted: ["verb", "/ˈpeɪntɪd/", "pintado"],
  passed: ["verb", "/pæst/", "passou"],
  repaired: ["verb", "/rɪˈpɛrd/", "consertado"],
  says: ["verb", "/sɛz/", "diz"],
  signed: ["verb", "/saɪnd/", "assinado"],
  stolen: ["verb", "/ˈstoʊlən/", "roubado"],
  stuck: ["adjective", "/stʌk/", "preso"],
  studied: ["verb", "/ˈstʌdid/", "estudou, estudado"],
  wants: ["verb", "/wɑːnts/", "quer"],
  wonder: ["verb", "/ˈwʌndər/", "perguntar-se"],
  "wouldn't": ["verb", "/ˈwʊdənt/", "não faria (would not)"],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-tenses-b1-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-tenses-b1',
    slug: 'verb-tenses-b1',
    title: 'Tempos Verbais em Uso',
    level: 'B1',
    category: 'grammar',
    track: 'gramatica',
    trackOrder: 2,
    order: 9,
    short: 'Os tempos verbais que mais confundem brasileiros, em pares, com a comparação com o português.',
    long: 'Presente simples × contínuo, passado simples × contínuo, present perfect × passado, present perfect contínuo, futuro (will, going to, presente contínuo) e past perfect. Cada frase explica por que aquele tempo foi usado e como fica em português.',
    lessons: [
      lesson(7, 'Condicional zero e primeira', 'Verdades gerais e possibilidades reais.', [
        s('If you heat ice, it melts.', 'Se você aquece gelo, ele derrete.', 'Zero conditional: if + presente, presente. Verdade que sempre acontece.'),
        s('If I drink coffee at night, I can\'t sleep.', 'Se tomo café à noite, não consigo dormir.', 'Zero conditional para hábito pessoal: sempre que acontece.'),
        s('If it rains tomorrow, we will stay home.', 'Se chover amanhã, vamos ficar em casa.', 'First conditional: if + presente, will + verbo. Em português usamos o futuro do subjuntivo ("chover"); em inglês, presente.'),
        s('If you study, you will pass the test.', 'Se você estudar, vai passar na prova.', 'Nunca "if you will study": depois de "if", presente.'),
        s("I'll call you if I need help.", 'Te ligo se precisar de ajuda.', 'A oração com "if" pode vir no fim, sem vírgula.'),
        s('Unless you hurry, you will miss the bus.', 'A menos que se apresse, vai perder o ônibus.', '"Unless" = "if not". Não use negativa depois de "unless".'),
        s('If you see Anna, tell her to call me.', 'Se vir a Anna, diga para ela me ligar.', 'Condicional com imperativo: if + presente, ordem.'),
        s('When I get home, I will text you.', 'Quando eu chegar em casa, te mando mensagem.', '"When" também pede presente para futuro: "when I get", não "when I will get".'),
        s('As soon as the store opens, I will buy it.', 'Assim que a loja abrir, vou comprar.', '"As soon as" + presente com sentido de futuro.'),
        s('If the train is late, we might miss the show.', 'Se o trem atrasar, talvez a gente perca o show.', '"Might" no lugar de "will" deixa a consequência menos certa.'),
      ]),
      lesson(8, 'Segunda condicional', 'Situações imaginárias no presente.', [
        s('If I had more money, I would travel more.', 'Se eu tivesse mais dinheiro, viajaria mais.', 'Second conditional: if + passado, would + verbo. Situação imaginária agora.'),
        s('If I were you, I would accept the offer.', 'Se eu fosse você, aceitaria a oferta.', '"If I were you" é a forma padrão para dar conselho; "were" para todas as pessoas.'),
        s('If she lived closer, we would see her more.', 'Se ela morasse mais perto, a veríamos mais.', 'O passado aqui não é tempo passado: é hipótese, como o imperfeito do subjuntivo.'),
        s('What would you do if you won the lottery?', 'O que você faria se ganhasse na loteria?', 'Pergunta hipotética clássica.'),
        s("If I knew the answer, I would tell you.", 'Se eu soubesse a resposta, te contaria.', 'Implica que não sei a resposta.'),
        s("I wouldn't do that if I were you.", 'Eu não faria isso se fosse você.', 'Negativa: "wouldn\'t" + verbo.'),
        s('If we had a car, we could go to the beach.', 'Se tivéssemos carro, poderíamos ir à praia.', '"Could" = "would be able to".'),
        s("If it weren't so expensive, I would buy it.", 'Se não fosse tão caro, eu compraria.', 'Negativa na oração com "if": "weren\'t".'),
        s('I wish I spoke French.', 'Queria falar francês.', '"I wish" + passado = desejo sobre o presente, mesma lógica da segunda condicional.'),
        s('If I could live anywhere, I would choose Lisbon.', 'Se eu pudesse morar em qualquer lugar, escolheria Lisboa.', '"Could" no lugar de "had" para capacidade imaginária.'),
      ]),
      lesson(9, 'Terceira condicional', 'Imaginar um passado diferente.', [
        s('If I had left earlier, I would have caught the train.', 'Se eu tivesse saído mais cedo, teria pegado o trem.', 'Third conditional: if + past perfect, would have + particípio. O passado não aconteceu assim.'),
        s("If you had told me, I would have helped.", 'Se você tivesse me contado, eu teria ajudado.', 'Arrependimento ou crítica sobre o passado.'),
        s("We wouldn't have got lost if we had used the map.", 'Não teríamos nos perdido se tivéssemos usado o mapa.', 'A oração com "if" pode vir depois.'),
        s('If she had studied, she would have passed.', 'Se ela tivesse estudado, teria passado.', 'Na fala: "she\'d have passed".'),
        s('What would you have done in my place?', 'O que você teria feito no meu lugar?', 'Pergunta sobre um passado imaginário.'),
        s("If it hadn't rained, we would have gone to the park.", 'Se não tivesse chovido, teríamos ido ao parque.', 'Negativa: "hadn\'t" + particípio.'),
        s('I would have called you if I had known.', 'Eu teria te ligado se soubesse.', 'Em português falado usamos "se soubesse"; em inglês precisa de "had known".'),
        s('I wish I had listened to you.', 'Queria ter te escutado.', '"I wish" + past perfect = arrependimento sobre o passado.'),
        s('If I had taken that job, I would live in Paris now.', 'Se eu tivesse aceitado aquele emprego, moraria em Paris agora.', 'Condicional mista: passado imaginado com resultado no presente.'),
        s('You should have told me earlier.', 'Você deveria ter me contado antes.', '"Should have" + particípio = crítica sobre o passado, parente da terceira condicional.'),
      ]),
      lesson(10, 'Voz passiva: presente e passado', 'Quando a ação importa mais que quem fez.', [
        s('English is spoken all over the world.', 'Inglês é falado no mundo todo.', 'Passiva: be + particípio. Quem fala não importa.'),
        s('The office is cleaned every night.', 'O escritório é limpo toda noite.', 'Presente simples na passiva: "is cleaned".'),
        s('This bridge was built in 1920.', 'Esta ponte foi construída em 1920.', 'Passado na passiva: "was built".'),
        s('My bike was stolen last week.', 'Minha bicicleta foi roubada semana passada.', 'Não sabemos quem roubou, então a passiva é natural.'),
        s('The book was written by a young nurse.', 'O livro foi escrito por uma jovem enfermeira.', '"By" apresenta o agente quando ele é informação nova.'),
        s('Are credit cards accepted here?', 'Aceitam cartão de crédito aqui?', 'Pergunta na passiva: be antes do sujeito. Em português usamos sujeito indeterminado.'),
        s('Breakfast is served from seven to ten.', 'O café da manhã é servido das sete às dez.', 'Passiva comum em avisos de hotel.'),
        s('I was born in Recife.', 'Nasci em Recife.', '"Be born" é sempre passiva em inglês: nunca "I born".'),
        s('The meeting was canceled.', 'A reunião foi cancelada.', 'Aviso típico: o agente é óbvio ou irrelevante.'),
        s('Were you invited to the party?', 'Você foi convidado para a festa?', 'Passado na passiva, forma de pergunta.'),
      ]),
      lesson(11, 'Voz passiva: outros tempos', 'Passiva com perfect, futuro, contínuo e modais.', [
        s('The package has been delivered.', 'O pacote foi entregue.', 'Present perfect passivo: has/have been + particípio. Resultado agora.'),
        s('The results will be announced tomorrow.', 'Os resultados serão anunciados amanhã.', 'Futuro passivo: will be + particípio.'),
        s('The road is being repaired.', 'A estrada está sendo consertada.', 'Contínuo passivo: is being + particípio.'),
        s('This form must be signed.', 'Este formulário precisa ser assinado.', 'Modal passivo: modal + be + particípio.'),
        s('The tickets can be bought online.', 'Os ingressos podem ser comprados online.', '"Can be" + particípio = é possível.'),
        s('All the rooms have been booked.', 'Todos os quartos foram reservados.', 'Plural: "have been".'),
        s('The house was being painted when we arrived.', 'A casa estava sendo pintada quando chegamos.', 'Passado contínuo passivo: was being + particípio.'),
        s('The work had been finished before noon.', 'O trabalho tinha sido terminado antes do meio-dia.', 'Past perfect passivo: had been + particípio.'),
        s('I got stuck in traffic.', 'Fiquei preso no trânsito.', '"Get" + particípio é a passiva informal da fala.'),
        s('He got fired last month.', 'Ele foi demitido mês passado.', '"Get fired" é mais comum na fala do que "was fired".'),
      ]),
      lesson(12, 'Discurso indireto: afirmações', 'Contar o que alguém disse.', [
        s('She said she was tired.', 'Ela disse que estava cansada.', 'Presente vira passado: "I am tired" → "she was tired".'),
        s('He told me he lived in Porto.', 'Ele me disse que morava no Porto.', '"Tell" pede objeto (told me); "say" não (said that).'),
        s('They said they had finished.', 'Disseram que tinham terminado.', 'Passado ou present perfect vira past perfect.'),
        s('She said she would call later.', 'Ela disse que ligaria mais tarde.', '"Will" vira "would".'),
        s('He said he could help us.', 'Ele disse que podia nos ajudar.', '"Can" vira "could".'),
        s('You said you were coming!', 'Você disse que vinha!', 'Presente contínuo vira passado contínuo.'),
        s('She told us the store was closed.', 'Ela nos disse que a loja estava fechada.', '"That" pode ser omitido depois de "said" e "told".'),
        s('He says he is busy.', 'Ele diz que está ocupado.', 'Com "says" no presente, o tempo não muda.'),
        s('I told you it would rain.', 'Eu te disse que ia chover.', 'Previsão passada: "will" vira "would".'),
        s('She said she had seen the movie the day before.', 'Ela disse que tinha visto o filme no dia anterior.', '"Yesterday" vira "the day before" quando o contexto mudou.'),
      ]),
      lesson(13, 'Discurso indireto: perguntas e pedidos', 'Contar perguntas, ordens e pedidos.', [
        s('She asked me where I lived.', 'Ela me perguntou onde eu morava.', 'Pergunta indireta: ordem de afirmação, sem "did" e sem inversão.'),
        s('He asked if I was ready.', 'Ele perguntou se eu estava pronto.', 'Pergunta de sim ou não vira "if" ou "whether".'),
        s('They asked what time the show started.', 'Perguntaram a que horas o show começava.', 'Nada de "what time did the show start" no indireto.'),
        s('Do you know where the station is?', 'Você sabe onde fica a estação?', 'Pergunta indireta educada: "where the station is", não "where is the station".'),
        s('Can you tell me how much it costs?', 'Pode me dizer quanto custa?', 'Mais educado que "How much does it cost?".'),
        s('She told me to wait outside.', 'Ela me mandou esperar lá fora.', 'Ordem: tell + pessoa + to + verbo.'),
        s('He asked me to close the door.', 'Ele me pediu para fechar a porta.', 'Pedido: ask + pessoa + to + verbo.'),
        s('The doctor told me not to run.', 'O médico me disse para não correr.', 'Ordem negativa: "not to" + verbo.'),
        s('I wonder if she got my message.', 'Será que ela recebeu minha mensagem?', '"I wonder if" = "será que", com ordem de afirmação.'),
        s("I don't know what he wants.", 'Não sei o que ele quer.', 'Sem "does": "what he wants", não "what does he want".'),
      ]),
      lesson(14, 'Dedução no presente', 'Must, might, can\'t para tirar conclusões.', [
        s('She must be tired.', 'Ela deve estar cansada.', '"Must" de dedução: tenho quase certeza de que sim.'),
        s("That can't be true.", 'Isso não pode ser verdade.', '"Can\'t" de dedução: tenho quase certeza de que não. Nunca "mustn\'t" com esse sentido.'),
        s('He might be at home.', 'Ele pode estar em casa.', '"Might" = talvez, uns 50%.'),
        s('It could be the neighbor.', 'Pode ser o vizinho.', '"Could" = possibilidade, como "might".'),
        s('They may know the answer.', 'Talvez eles saibam a resposta.', '"May" = possibilidade, um pouco mais formal.'),
        s('You must be joking!', 'Você só pode estar brincando!', 'Expressão fixa de surpresa.'),
        s('She must be working late.', 'Ela deve estar trabalhando até tarde.', 'Modal + be + -ing para dedução sobre agora.'),
        s("He can't be hungry. He just ate.", 'Ele não pode estar com fome. Acabou de comer.', 'A dedução vem com a evidência.'),
        s('This must be your first time here.', 'Esta deve ser sua primeira vez aqui.', '"Must" também para deduzir com gentileza.'),
        s("The keys might be in the car.", 'As chaves podem estar no carro.', 'Negativa de "might": "might not" = talvez não.'),
      ]),
      lesson(15, 'Dedução no passado', 'Must have, might have, can\'t have.', [
        s('She must have forgotten.', 'Ela deve ter esquecido.', 'Must have + particípio = quase certeza sobre o passado.'),
        s("He can't have seen us.", 'Ele não pode ter nos visto.', "Can't have + particípio = quase certeza de que não aconteceu."),
        s('They might have missed the bus.', 'Eles podem ter perdido o ônibus.', 'Might have + particípio = talvez tenha acontecido.'),
        s('I must have left my phone at work.', 'Devo ter deixado o celular no trabalho.', 'Dedução sobre algo que você mesmo fez.'),
        s('You could have called me.', 'Você podia ter me ligado.', '"Could have" também critica: era possível e não fez.'),
        s('It must have been hard for you.', 'Deve ter sido difícil para você.', 'Frase de empatia muito usada.'),
        s("She couldn't have known.", 'Ela não tinha como saber.', '"Couldn\'t have" = era impossível.'),
        s('The road must have been closed.', 'A estrada deve ter sido fechada.', 'Dedução com passiva: must have been + particípio.'),
        s('He may have taken the wrong train.', 'Ele pode ter pegado o trem errado.', '"May have" = "might have", um pouco mais formal.'),
        s('Someone must have taken it by mistake.', 'Alguém deve ter levado por engano.', '"By mistake" = por engano.'),
      ]),
      lesson(16, 'Revisão: tempos avançados', 'Uma frase de cada estrutura.', [
        s('If it rains tomorrow, we will stay home.', 'Se chover amanhã, vamos ficar em casa.', 'Revisão: primeira condicional.'),
        s('If I were you, I would accept the offer.', 'Se eu fosse você, aceitaria a oferta.', 'Revisão: segunda condicional.'),
        s('If you had told me, I would have helped.', 'Se você tivesse me contado, eu teria ajudado.', 'Revisão: terceira condicional.'),
        s('This bridge was built in 1920.', 'Esta ponte foi construída em 1920.', 'Revisão: passiva no passado.'),
        s('The package has been delivered.', 'O pacote foi entregue.', 'Revisão: passiva no present perfect.'),
        s('She said she was tired.', 'Ela disse que estava cansada.', 'Revisão: discurso indireto.'),
        s('She asked me where I lived.', 'Ela me perguntou onde eu morava.', 'Revisão: pergunta indireta.'),
        s('She must be tired.', 'Ela deve estar cansada.', 'Revisão: dedução no presente.'),
        s('She must have forgotten.', 'Ela deve ter esquecido.', 'Revisão: dedução no passado.'),
        s('I wish I had listened to you.', 'Queria ter te escutado.', 'Revisão: arrependimento com "I wish".'),
      ]),
    ],
  },
];
