// Lote trabalho-1: Inglês no Trabalho, capítulos 4–9 (apresentações, feedback,
// prazos e negociação, ligações com clientes, pedir ajuda e delegar, small talk).
// Notas com o registro (formal, neutro, informal). Conteúdo original.

export const LEXICON = {
  as: ['conjunction', '/æz/', 'como'],
  "how's": ['adverb', '/haʊz/', 'como está (how is)'],
  linguaflow: ['proper noun', '/ˈlɪŋɡwəfloʊ/', 'Linguaflow'],
  maybe: ['adverb', '/ˈmeɪbi/', 'talvez'],
  sales: ['noun', '/seɪlz/', 'vendas'],
  welcome: ['adjective', '/ˈwɛlkəm/', 'bem-vindo'],
  approach: ['noun', '/əˈproʊtʃ/', 'abordagem'],
  available: ['adjective', '/əˈveɪləbəl/', 'disponível'],
  best: ['adjective', '/bɛst/', 'melhor'],
  breaking: ['verb', '/ˈbreɪkɪŋ/', 'cortando (ligação), quebrando'],
  care: ['noun', '/kɛr/', 'cuidado'],
  catching: ['verb', '/ˈkætʃɪŋ/', 'pegando; catching up = pôr o papo em dia'],
  client: ['noun', '/ˈklaɪənt/', 'cliente'],
  coming: ['verb', '/ˈkʌmɪŋ/', 'vindo'],
  considered: ['verb', '/kənˈsɪdərd/', 'considerou'],
  different: ['adjective', '/ˈdɪfərənt/', 'diferente'],
  else: ['adverb', '/ɛls/', 'mais, outro'],
  end: ['noun', '/ɛnd/', 'fim, final'],
  example: ['noun', '/ɪɡˈzæmpəl/', 'exemplo'],
  extend: ['verb', '/ɪkˈstɛnd/', 'estender, prorrogar'],
  feedback: ['noun', '/ˈfiːdbæk/', 'retorno, feedback'],
  flexibility: ['noun', '/ˌflɛksəˈbɪləti/', 'flexibilidade'],
  halfway: ['adverb', '/ˌhæfˈweɪ/', 'no meio do caminho'],
  handle: ['verb', '/ˈhændəl/', 'cuidar de, lidar com'],
  handled: ['verb', '/ˈhændəld/', 'lidou com'],
  hold: ['verb', '/hoʊld/', 'aguardar (na linha), segurar'],
  holidays: ['noun', '/ˈhɑːlədeɪz/', 'feriados, férias'],
  improve: ['verb', '/ɪmˈpruːv/', 'melhorar'],
  jumping: ['verb', '/ˈdʒʌmpɪŋ/', 'pulando; jumping in = entrar para ajudar'],
  liked: ['verb', '/laɪkt/', 'gostou'],
  moment: ['noun', '/ˈmoʊmənt/', 'momento'],
  move: ['verb', '/muːv/', 'mover, passar'],
  offer: ['noun', '/ˈɔːfər/', 'oferta'],
  overview: ['noun', '/ˈoʊvərvjuː/', 'visão geral'],
  percent: ['noun', '/pərˈsɛnt/', 'por cento'],
  plans: ['noun', '/plænz/', 'planos'],
  price: ['noun', '/praɪs/', 'preço'],
  project: ['noun', '/ˈprɑːdʒɛkt/', 'projeto'],
  reduce: ['verb', '/rɪˈduːs/', 'reduzir'],
  scope: ['noun', '/skoʊp/', 'escopo'],
  slide: ['noun', '/slaɪd/', 'slide'],
  slides: ['noun', '/slaɪdz/', 'slides'],
  spell: ['verb', '/spɛl/', 'soletrar'],
  takeaway: ['noun', '/ˈteɪkəweɪ/', 'mensagem principal'],
  taking: ['verb', '/ˈteɪkɪŋ/', 'dando, pegando'],
  tasks: ['noun', '/tæsks/', 'tarefas'],
  team: ['noun', '/tiːm/', 'time, equipe'],
  thing: ['noun', '/θɪŋ/', 'coisa'],
  tight: ['adjective', '/taɪt/', 'apertado'],
  timing: ['noun', '/ˈtaɪmɪŋ/', 'tempo, ritmo'],
  writing: ['noun', '/ˈraɪtɪŋ/', 'escrita'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });

export const COURSES = [
  {
    id: 'course-work-b1',
    slug: 'english-at-work-b1',
    title: 'Inglês no Trabalho',
    level: 'B1',
    category: 'business',
    track: 'trabalho',
    trackOrder: 1,
    order: 3,
    short: 'Reuniões, e-mails, apresentações, feedback, prazos e clientes: o inglês de escritório e trabalho remoto.',
    long: 'Expressões usadas de verdade no trabalho: conduzir reuniões, escrever e-mails, apresentar resultados, dar e receber feedback, negociar prazos, falar com clientes, delegar e conversar com colegas. Cada nota indica o registro (formal, neutro ou informal).',
    lessons: [
      {
        id: 'lesson-work-b1-04',
        chapter: 4,
        title: 'Apresentações',
        description: 'Abrir, conduzir e fechar uma apresentação.',
        units: [
          s("Today I'd like to talk about our results.", 'Hoje eu gostaria de falar sobre nossos resultados.', 'Neutro. Abertura clássica: "Today I\'d like to talk about…".'),
          s("I'll start with a quick overview.", 'Vou começar com uma visão geral rápida.', 'Neutro. "Overview" = visão geral.'),
          s('As you can see on this slide,', 'Como vocês podem ver neste slide,', 'Neutro. Conecta a fala ao que está na tela.'),
          s('Sales went up by ten percent.', 'As vendas subiram dez por cento.', 'Neutro. "Go up by" = subir em (quantidade). O contrário: "go down by".'),
          s("Let's move on to the next point.", 'Vamos passar para o próximo ponto.', 'Neutro. "Move on to" = passar para.'),
          s('This is the key takeaway.', 'Esta é a mensagem principal.', 'Neutro. "Takeaway" = o que o público deve lembrar.'),
          s("I'll leave time for questions at the end.", 'Vou deixar tempo para perguntas no final.', 'Neutro. "At the end" = no final.'),
          s("That's a great question.", 'Ótima pergunta.', 'Neutro. Ganha tempo para pensar na resposta.'),
          s("I don't have that number now, but I'll send it later.", 'Não tenho esse número agora, mas envio depois.', 'Neutro. Jeito profissional de não saber na hora.'),
          s('Thank you for your time.', 'Obrigado pelo seu tempo.', 'Formal. Fechamento padrão de apresentação.'),
        ],
      },
      {
        id: 'lesson-work-b1-05',
        chapter: 5,
        title: 'Dar e receber feedback',
        description: 'Elogiar, sugerir melhorias e aceitar críticas.',
        units: [
          s('You did a great job on this.', 'Você fez um ótimo trabalho nisso.', 'Neutro. "Do a great job" = fazer um ótimo trabalho.'),
          s('I really liked how you handled the client.', 'Gostei muito de como você lidou com o cliente.', 'Neutro. Elogio específico funciona melhor que genérico. "Handle" = lidar.'),
          s('One thing you could improve is the timing.', 'Uma coisa que você poderia melhorar é o tempo.', 'Neutro. Crítica suavizada com "could".'),
          s('Have you considered a different approach?', 'Você já pensou numa abordagem diferente?', 'Neutro. Sugestão em forma de pergunta.'),
          s('Maybe we could try it another way.', 'Talvez a gente pudesse tentar de outro jeito.', 'Neutro. "Maybe" e "could" deixam a sugestão educada.'),
          s('Thanks for the feedback.', 'Obrigado pelo retorno.', 'Neutro. "Feedback" é incontável: nunca "feedbacks".'),
          s('That makes sense, I will work on it.', 'Faz sentido, vou trabalhar nisso.', 'Neutro. Aceita a crítica e mostra ação.'),
          s('Could you give me an example?', 'Você poderia me dar um exemplo?', 'Neutro. Pede clareza sem soar defensivo.'),
          s('I see where you are coming from.', 'Entendo seu ponto de vista.', 'Informal. Literal: "vejo de onde você vem". Real: entendo o motivo.'),
          s('Keep up the good work.', 'Continue assim.', 'Neutro. "Keep up" = manter.'),
        ],
      },
      {
        id: 'lesson-work-b1-06',
        chapter: 6,
        title: 'Prazos e negociação',
        description: 'Negociar prazo, escopo e preço sem desgaste.',
        units: [
          s('When do you need this by?', 'Até quando você precisa disso?', 'Neutro. "By" + data = até (no máximo).'),
          s('The deadline is too tight.', 'O prazo está apertado demais.', 'Neutro. "Tight deadline" = prazo apertado.'),
          s('Can we extend the deadline?', 'Podemos estender o prazo?', 'Neutro. "Extend" = prorrogar.'),
          s("We can do it if we reduce the scope.", 'Conseguimos fazer se reduzirmos o escopo.', 'Neutro. Condição com "if" + presente.'),
          s("That's our best offer.", 'Essa é nossa melhor oferta.', 'Neutro. Sinaliza limite na negociação.'),
          s('Is there any flexibility on the price?', 'Tem alguma flexibilidade no preço?', 'Formal. Pergunta de negociação sem confronto.'),
          s("Let's meet halfway.", 'Vamos chegar a um meio-termo.', 'Informal. Literal: "vamos nos encontrar no meio do caminho".'),
          s("I'll need to check with my manager.", 'Preciso ver com meu gerente.', 'Neutro. Ganha tempo e divide a decisão.'),
          s('Can you put that in writing?', 'Pode colocar isso por escrito?', 'Neutro. "In writing" = por escrito.'),
          s('We have a deal.', 'Negócio fechado.', 'Neutro. Fecha o acordo.'),
        ],
      },
      {
        id: 'lesson-work-b1-07',
        chapter: 7,
        title: 'Ligações com clientes',
        description: 'Atender, anotar recado e resolver por telefone.',
        units: [
          s('Hello, this is Ana from Linguaflow.', 'Olá, aqui é a Ana, da Linguaflow.', 'Neutro. Ao telefone diga "this is", nunca "I am".'),
          s('How can I help you today?', 'Como posso ajudar hoje?', 'Neutro. Abertura de atendimento.'),
          s('Could you spell your last name?', 'Pode soletrar seu sobrenome?', 'Neutro. "Last name" = sobrenome.'),
          s('Let me check that for you.', 'Deixa eu verificar isso para você.', 'Neutro. Enquanto procura a informação.'),
          s('Could you hold for a moment?', 'Pode aguardar um instante?', 'Formal. "Hold" = aguardar na linha.'),
          s("She's not available right now.", 'Ela não está disponível agora.', 'Neutro. Jeito educado de dizer que a pessoa não pode atender.'),
          s('Can I take a message?', 'Quer deixar recado?', 'Neutro. "Take a message" = anotar recado.'),
          s('Sorry, you are breaking up.', 'Desculpe, está cortando.', 'Informal. "Break up" aqui = a ligação está falhando.'),
          s('I will call you back in five minutes.', 'Te retorno em cinco minutos.', 'Neutro. "Call back" = retornar a ligação.'),
          s('Is there anything else I can help with?', 'Posso ajudar em mais alguma coisa?', 'Neutro. Fechamento de atendimento.'),
        ],
      },
      {
        id: 'lesson-work-b1-08',
        chapter: 8,
        title: 'Pedir ajuda e delegar',
        description: 'Distribuir tarefas e pedir apoio sem soar mandão.',
        units: [
          s('Could you help me with this report?', 'Você pode me ajudar com este relatório?', 'Neutro. "Help with" + tarefa.'),
          s('Would you mind taking a look?', 'Você se importaria de dar uma olhada?', 'Formal. "Would you mind" + verbo com "-ing".'),
          s('Can you take care of this?', 'Você pode cuidar disso?', 'Neutro. "Take care of" = cuidar de, resolver.'),
          s('Who is in charge of this project?', 'Quem é o responsável por este projeto?', 'Neutro. "In charge of" = responsável por.'),
          s("I'll handle the slides.", 'Eu cuido dos slides.', 'Neutro. "Handle" = cuidar de, dar conta de.'),
          s('Let me know if you need anything.', 'Me avisa se precisar de algo.', 'Neutro. Oferece apoio.'),
          s("I'm not sure how to do this.", 'Não sei bem como fazer isso.', 'Neutro. Admitir a dúvida cedo evita retrabalho.'),
          s('Could you walk me through it?', 'Você pode me explicar passo a passo?', 'Informal. "Walk through" = explicar passo a passo.'),
          s('Can we split the tasks?', 'Podemos dividir as tarefas?', 'Neutro. "Split" = dividir.'),
          s('Thanks for jumping in.', 'Obrigado por entrar para ajudar.', 'Informal. "Jump in" = entrar para ajudar de repente.'),
        ],
      },
      {
        id: 'lesson-work-b1-09',
        chapter: 9,
        title: 'Conversa informal no escritório',
        description: 'Small talk com colegas antes e depois das reuniões.',
        units: [
          s('How was your weekend?', 'Como foi seu fim de semana?', 'Informal. Abertura mais comum de segunda-feira.'),
          s('Any plans for the holidays?', 'Algum plano para o feriado?', 'Informal. "Holidays" = feriados, férias de fim de ano.'),
          s("How's it going with the new project?", 'Como está indo o projeto novo?', 'Informal. "How\'s it going" = como vai.'),
          s('Did you see the game last night?', 'Você viu o jogo ontem à noite?', 'Informal. Esporte é assunto seguro no escritório.'),
          s("It's been a busy week.", 'A semana foi corrida.', 'Neutro. Present perfect para a semana que ainda não acabou.'),
          s('Want to grab lunch?', 'Bora almoçar?', 'Informal. "(Do you) want to grab lunch?".'),
          s('Welcome to the team!', 'Bem-vindo ao time!', 'Neutro. Recebe colega novo.'),
          s('How long have you been here?', 'Há quanto tempo você trabalha aqui?', 'Neutro. Present perfect contínuo: começou no passado e continua.'),
          s('Nice catching up with you.', 'Foi bom colocar o papo em dia.', 'Informal. "Catch up" = colocar a conversa em dia.'),
          s('See you at the meeting.', 'Te vejo na reunião.', 'Neutro. Despedida entre colegas.'),
        ],
      },
    ],
  },
];
