// Lote trabalho-b2-1: curso novo "Reuniões e Negociação" (B2, trilha Trabalho), capítulos 1–8:
// conduzir reuniões, opinar com diplomacia, propor e contrapropor, preço e condições,
// objeções e concessões, fechar acordo, apresentar resultados e lidar com conflitos e prazos.
// Continua "Inglês no Trabalho" (B1). Conteúdo original.

export const LEXICON = {
  actions: ["noun", "/ˈækʃənz/", "ações"],
  advocate: ["noun", "/ˈædvəkət/", "advogado, defensor"],
  agenda: ["noun", "/əˈdʒɛndə/", "pauta"],
  agreed: ["verb", "/əˈɡriːd/", "combinamos, concordamos"],
  ahead: ["adverb", "/əˈhɛd/", "à frente, adiante"],
  beyond: ["preposition", "/biˈɑːnd/", "além de, fora de"],
  breaker: ["noun", "/ˈbreɪkər/", "o que quebra, impeditivo"],
  bulk: ["noun", "/bʌlk/", "grande quantidade"],
  "check-in": ["noun", "/ˈtʃɛk ɪn/", "alinhamento, encontro de acompanhamento"],
  circulate: ["verb", "/ˈsɜːrkjəleɪt/", "distribuir, circular"],
  closing: ["verb", "/ˈkloʊzɪŋ/", "fechando"],
  commit: ["verb", "/kəˈmɪt/", "se comprometer"],
  common: ["adjective", "/ˈkɑːmən/", "comum"],
  compared: ["verb", "/kəmˈpɛrd/", "comparado"],
  competitive: ["adjective", "/kəmˈpɛtətɪv/", "competitivo"],
  compromise: ["verb", "/ˈkɑːmprəmaɪz/", "ceder, fazer concessão"],
  conclusions: ["noun", "/kənˈkluːʒənz/", "conclusões"],
  congratulations: ["noun", "/kənˌɡrætʃəˈleɪʃənz/", "parabéns"],
  control: ["noun", "/kənˈtroʊl/", "controle"],
  delivery: ["noun", "/dɪˈlɪvəri/", "entrega"],
  "devil's": ["noun", "/ˈdɛvəlz/", "do diabo"],
  draw: ["verb", "/drɔː/", "redigir, desenhar"],
  error: ["noun", "/ˈɛrər/", "erro"],
  escalate: ["verb", "/ˈɛskəleɪt/", "escalar, levar a um nível acima"],
  exception: ["noun", "/ɪkˈsɛpʃən/", "exceção"],
  explore: ["verb", "/ɪkˈsplɔːr/", "explorar"],
  figure: ["noun", "/ˈfɪɡjər/", "valor, número"],
  figures: ["noun", "/ˈfɪɡjərz/", "números, dados"],
  frustration: ["noun", "/frʌˈstreɪʃən/", "frustração"],
  gap: ["noun", "/ɡæp/", "diferença, lacuna"],
  growth: ["noun", "/ɡroʊθ/", "crescimento"],
  hands: ["noun", "/hændz/", "mãos"],
  highlight: ["verb", "/ˈhaɪlaɪt/", "destacar"],
  issue: ["noun", "/ˈɪʃuː/", "assunto, problema"],
  joining: ["verb", "/ˈdʒɔɪnɪŋ/", "entrando, participando"],
  management: ["noun", "/ˈmænɪdʒmənt/", "gerência, gestão"],
  maria: ["proper noun", "/məˈriːə/", "Maria (nome próprio)"],
  "one-year": ["adjective", "/ˌwʌn ˈjɪr/", "de um ano"],
  orders: ["noun", "/ˈɔːrdərz/", "pedidos"],
  parts: ["noun", "/pɑːrts/", "peças, partes"],
  period: ["noun", "/ˈpɪriəd/", "período"],
  practice: ["noun", "/ˈpræktɪs/", "prática"],
  prepared: ["adjective", "/prɪˈpɛrd/", "disposto, preparado"],
  profits: ["noun", "/ˈprɑːfɪts/", "lucros"],
  proposing: ["verb", "/prəˈpoʊzɪŋ/", "propondo"],
  provided: ["conjunction", "/prəˈvaɪdɪd/", "desde que"],
  quote: ["noun", "/kwoʊt/", "cotação, orçamento"],
  rates: ["noun", "/reɪts/", "preços, taxas"],
  realistic: ["adjective", "/ˌriːəˈlɪstɪk/", "realista"],
  reasoning: ["noun", "/ˈriːzənɪŋ/", "raciocínio"],
  responsibility: ["noun", "/rɪˌspɑːnsəˈbɪləti/", "responsabilidade"],
  revised: ["adjective", "/rɪˈvaɪzd/", "revisado"],
  risk: ["noun", "/rɪsk/", "risco"],
  rose: ["verb", "/roʊz/", "subiu"],
  sharply: ["adverb", "/ˈʃɑːrpli/", "bruscamente"],
  sides: ["noun", "/saɪdz/", "lados"],
  slightly: ["adverb", "/ˈslaɪtli/", "ligeiramente"],
  steady: ["adjective", "/ˈstɛdi/", "estável"],
  suggestions: ["noun", "/səɡˈdʒɛstʃənz/", "sugestões"],
  sum: ["verb", "/sʌm/", "somar, resumir"],
  summary: ["noun", "/ˈsʌməri/", "resumo"],
  target: ["noun", "/ˈtɑːrɡɪt/", "meta, alvo"],
  tend: ["verb", "/tɛnd/", "tender"],
  terms: ["noun", "/tɜːrmz/", "condições, termos"],
  themselves: ["pronoun", "/ðəmˈsɛlvz/", "eles mesmos"],
  timeline: ["noun", "/ˈtaɪmlaɪn/", "cronograma, linha do tempo"],
  trend: ["noun", "/trɛnd/", "tendência"],
  trial: ["noun", "/ˈtraɪəl/", "teste, experimental"],
  updated: ["verb", "/ʌpˈdeɪtɪd/", "atualizado"],
  warranty: ["noun", "/ˈwɔːrənti/", "garantia"],
  willing: ["adjective", "/ˈwɪlɪŋ/", "disposto"],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const lesson = (n, title, description, units) => ({
  id: `lesson-negotiation-b2-${String(n).padStart(2, '0')}`, chapter: n, title, description, units,
});

export const COURSES = [
  {
    id: 'course-negotiation-b2',
    slug: 'meetings-negotiation-b2',
    title: 'Reuniões e Negociação',
    level: 'B2',
    category: 'business',
    track: 'trabalho',
    trackOrder: 1,
    order: 22,
    short: 'Conduzir reuniões, discordar com diplomacia, negociar preço e fechar acordos em inglês.',
    long: 'O inglês de quem decide e negocia: abrir e conduzir reuniões, opinar sem ser ríspido, propor, contrapropor, ceder e fechar um acordo. Cada nota explica o tom da frase (neutro, diplomático, firme) e o que evitar para não soar agressivo.',
    lessons: [
      lesson(1, 'Conduzir a reunião', 'Abrir, organizar a pauta, dar a palavra e manter o foco.', [
        s('Thank you all for joining on short notice.', 'Obrigado a todos por entrarem em cima da hora.', '"On short notice" = com pouca antecedência; boa abertura de agradecimento.'),
        s('Let me start by going over the agenda.', 'Deixa eu começar revendo a pauta.', '"Go over" = revisar; "agenda" = pauta da reunião.'),
        s('We have three items to cover today.', 'Temos três itens para tratar hoje.', '"Cover" = tratar de um assunto.'),
        s('Could we keep to the point, please?', 'Podemos manter o foco, por favor?', '"Keep to the point" corta divagações com educação.'),
        s('I will hand over to Maria for the budget update.', 'Passo a palavra para a Maria sobre o orçamento.', '"Hand over to" = passar a palavra.'),
        s('Does anyone have anything to add?', 'Alguém tem algo a acrescentar?', 'Convite aberto; mais suave que "any questions?".'),
        s('We are running a bit behind schedule.', 'Estamos um pouco atrasados no horário.', '"Behind schedule" = atrasado em relação ao previsto.'),
        s('Let us park that issue and come back to it.', 'Vamos deixar esse assunto de lado e voltar a ele.', '"Park an issue" = adiar um tema sem descartá-lo.'),
        s('To sum up, we agreed on two actions.', 'Resumindo, combinamos duas ações.', '"To sum up" fecha com um resumo.'),
        s('I will circulate the minutes by tomorrow.', 'Vou enviar a ata até amanhã.', '"Minutes" = ata da reunião; "circulate" = distribuir.'),
      ]),
      lesson(2, 'Opinar com diplomacia', 'Concordar, discordar e questionar sem criar atrito.', [
        s('I see where you are coming from.', 'Entendo o seu ponto de vista.', '"Where you are coming from" = de onde vem seu raciocínio.'),
        s('That is a fair point, but I have a concern.', 'É um bom argumento, mas tenho uma preocupação.', 'Reconhece o outro lado antes de discordar.'),
        s('I am not sure that would work in practice.', 'Não tenho certeza de que isso funcionaria na prática.', 'Duvidar sem negar de frente.'),
        s('With respect, I think we are missing something.', 'Com todo o respeito, acho que estamos deixando algo passar.', '"With respect" suaviza a discordância.'),
        s('Could you walk me through your reasoning?', 'Você poderia me explicar seu raciocínio passo a passo?', '"Walk me through" = explicar em detalhe.'),
        s('I tend to agree, although there is a risk.', 'Tendo a concordar, embora haja um risco.', '"I tend to" suaviza a concordância.'),
        s("Let me play devil's advocate for a moment.", 'Deixa eu bancar o advogado do diabo por um momento.', 'Frase fixa para levantar uma objeção sem hostilidade.'),
        s('I would rather not commit to that yet.', 'Prefiro não me comprometer com isso ainda.', '"Would rather not" recusa com delicadeza.'),
        s('Can we explore other options first?', 'Podemos explorar outras opções antes?', 'Em vez de dizer "não", propõe ampliar as alternativas.'),
        s('I am afraid I have to disagree on that.', 'Infelizmente preciso discordar nesse ponto.', '"I am afraid" aqui é cortesia, não medo.'),
      ]),
      lesson(3, 'Propor e contrapropor', 'Apresentar uma oferta e responder com outra.', [
        s('Here is what we are proposing.', 'Aqui está o que estamos propondo.', 'Abre uma proposta de forma direta e neutra.'),
        s('We would be willing to offer a longer contract.', 'Estaríamos dispostos a oferecer um contrato mais longo.', '"Be willing to" mostra flexibilidade.'),
        s('Would you consider a smaller order to start?', 'Vocês considerariam um pedido menor para começar?', '"Would you consider" = pergunta educada de contraproposta.'),
        s('How would you feel about a trial period?', 'O que você acharia de um período de teste?', 'Sondar a reação antes de propor de vez.'),
        s('That is a little higher than we expected.', 'Isso está um pouco acima do que esperávamos.', 'Recusa o valor sem dizer "no".'),
        s('We are looking for something more flexible.', 'Estamos buscando algo mais flexível.', 'Indica a direção desejada sem fechar a porta.'),
        s('What would it take to move forward today?', 'O que seria preciso para avançarmos hoje?', 'Pergunta direta que revela o que o outro lado quer.'),
        s('If we agree to this, we need something in return.', 'Se concordarmos com isso, precisamos de algo em troca.', '"In return" = em troca; base de toda concessão.'),
        s('Let me put another option on the table.', 'Deixa eu colocar outra opção na mesa.', '"Put on the table" = apresentar para discussão.'),
        s('We can meet you halfway on the delivery date.', 'Podemos chegar a um meio-termo na data de entrega.', '"Meet halfway" = ceder metade do caminho.'),
      ]),
      lesson(4, 'Preço e condições', 'Falar de valor, desconto, prazo de pagamento e garantia.', [
        s('Our rates are competitive for this market.', 'Nossos preços são competitivos para este mercado.', '"Competitive" = em linha ou abaixo da concorrência.'),
        s('Is there any room for a discount?', 'Há alguma margem para desconto?', '"Room" = margem, espaço para negociar.'),
        s('We can offer ten percent off for bulk orders.', 'Podemos dar dez por cento de desconto em pedidos grandes.', '"Bulk order" = pedido em grande quantidade.'),
        s('What are your payment terms?', 'Quais são as suas condições de pagamento?', '"Terms" = condições, no plural.'),
        s('Payment is due within thirty days.', 'O pagamento vence em trinta dias.', '"Due within" = com vencimento em até.'),
        s('Does the price include delivery?', 'O preço inclui a entrega?', 'Pergunta de conferência que evita surpresa depois.'),
        s('There is a one-year warranty on all parts.', 'Há garantia de um ano em todas as peças.', '"Warranty" = garantia do produto.'),
        s('We would need a deposit up front.', 'Precisaríamos de um sinal adiantado.', '"Up front" = adiantado, no início.'),
        s('That figure is not within our budget.', 'Esse valor não cabe no nosso orçamento.', '"Within budget" = dentro do orçamento.'),
        s('Could you send us a revised quote?', 'Vocês poderiam nos enviar uma cotação revisada?', '"Quote" = cotação, orçamento formal.'),
      ]),
      lesson(5, 'Objeções e concessões', 'Resistir, ceder e condicionar, mantendo a relação.', [
        s('I understand your position, but we cannot go that far.', 'Entendo sua posição, mas não podemos ir tão longe.', 'Reconhece e limita na mesma frase.'),
        s('That is a deal breaker for us.', 'Isso é um impeditivo para nós.', '"Deal breaker" = condição que inviabiliza o negócio.'),
        s('We could make an exception this once.', 'Poderíamos abrir uma exceção desta vez.', '"Make an exception" = abrir uma exceção.'),
        s('I am prepared to compromise on the timeline.', 'Estou disposto a ceder no cronograma.', '"Compromise on" = ceder em um ponto.'),
        s('We are not in a position to agree to that.', 'Não estamos em condição de aceitar isso.', 'Recusa formal que evita culpar a pessoa.'),
        s('Provided that you sign today, we can do it.', 'Desde que vocês assinem hoje, conseguimos fazer.', '"Provided that" = desde que; condição firme.'),
        s('Let us find some common ground.', 'Vamos encontrar um ponto em comum.', '"Common ground" = terreno comum.'),
        s('We are open to suggestions on this point.', 'Estamos abertos a sugestões neste ponto.', 'Convida o outro lado a propor.'),
        s('I wish I could help, but my hands are tied.', 'Eu queria poder ajudar, mas estou de mãos atadas.', '"My hands are tied" = não tenho autonomia para decidir.'),
        s('That is as far as we can go.', 'Esse é o nosso limite.', 'Fecha uma negociação sem espaço para ceder mais.'),
      ]),
      lesson(6, 'Fechar o acordo', 'Confirmar o que foi combinado e definir os próximos passos.', [
        s('So, do we have a deal?', 'Então, estamos combinados?', '"Do we have a deal?" propõe fechar na hora.'),
        s('I think we are all on the same page now.', 'Acho que agora estamos todos alinhados.', '"On the same page" = alinhados.'),
        s('Let me confirm what we have agreed.', 'Deixa eu confirmar o que combinamos.', 'Recapitular evita mal-entendidos.'),
        s('We will draw up the contract this week.', 'Vamos redigir o contrato esta semana.', '"Draw up" = redigir um documento formal.'),
        s('Please review the terms before you sign.', 'Revise as condições antes de assinar, por favor.', '"Sign" = assinar; "review" = revisar.'),
        s('I will follow up with a summary in writing.', 'Vou enviar um resumo por escrito em seguida.', '"Follow up" = dar continuidade depois.'),
        s('We are happy to move ahead on these terms.', 'Teremos prazer em seguir adiante nestas condições.', 'Aceita formalmente a proposta.'),
        s('Congratulations, this is a win for both sides.', 'Parabéns, é bom para os dois lados.', '"Win-win" é a ideia de um acordo bom para todos.'),
        s('Who will be the point of contact?', 'Quem será o ponto de contato?', '"Point of contact" = responsável pela comunicação.'),
        s('Let us schedule a check-in for next month.', 'Vamos marcar um alinhamento para o mês que vem.', '"Check-in" = encontro de acompanhamento.'),
      ]),
      lesson(7, 'Apresentar resultados', 'Falar de números, tendências e comparações.', [
        s('Sales rose by twelve percent last quarter.', 'As vendas subiram doze por cento no último trimestre.', '"Rise by" indica o tamanho da variação.'),
        s('Revenue has remained steady this year.', 'A receita se manteve estável neste ano.', '"Remain steady" = ficar estável.'),
        s('Costs dropped sharply after the change.', 'Os custos caíram bruscamente depois da mudança.', '"Sharply" = de forma brusca.'),
        s('We are slightly ahead of our target.', 'Estamos um pouco à frente da meta.', '"Ahead of target" = acima da meta.'),
        s('The figures speak for themselves.', 'Os números falam por si.', 'Expressão para dizer que os dados são convincentes.'),
        s('Compared to last year, profits are up.', 'Em comparação com o ano passado, os lucros subiram.', '"Compared to" abre uma comparação.'),
        s('This trend is expected to continue.', 'Espera-se que essa tendência continue.', '"Expected to" = a previsão é que.'),
        s('The main driver of growth was online sales.', 'O principal motor do crescimento foi a venda online.', '"Driver" = fator que impulsiona.'),
        s('As you can see on this slide, the gap is closing.', 'Como vocês podem ver neste slide, a diferença está diminuindo.', '"Gap" = diferença, lacuna.'),
        s('Let me highlight the key takeaway.', 'Deixa eu destacar o ponto principal.', '"Key takeaway" = lição ou conclusão central.'),
      ]),
      lesson(8, 'Conflitos e prazos', 'Atrasos, falhas de entrega e conversas difíceis.', [
        s('I am afraid we will miss the deadline.', 'Receio que a gente perca o prazo.', 'Dá a má notícia com tom cuidadoso.'),
        s('The delay was due to circumstances beyond our control.', 'O atraso foi causado por fatores fora do nosso controle.', '"Beyond our control" = fora do nosso alcance.'),
        s('We take full responsibility for the error.', 'Assumimos toda a responsabilidade pelo erro.', 'Assumir sem rodeios gera confiança.'),
        s('How can we put this right?', 'Como podemos corrigir isso?', '"Put right" = corrigir, resolver.'),
        s('We need to escalate this to management.', 'Precisamos levar isso à gerência.', '"Escalate" = subir o problema para um nível acima.'),
        s('I would like to clear up a misunderstanding.', 'Gostaria de esclarecer um mal-entendido.', '"Clear up" = esclarecer.'),
        s('Let us not jump to conclusions.', 'Vamos não tirar conclusões precipitadas.', '"Jump to conclusions" = concluir cedo demais.'),
        s('Can we agree on a realistic new date?', 'Podemos combinar uma nova data realista?', 'Busca solução em vez de culpa.'),
        s('I understand your frustration, and I am sorry.', 'Entendo sua frustração e peço desculpas.', 'Reconhece a emoção antes da solução.'),
        s('We will keep you updated every step of the way.', 'Vamos manter você informado a cada etapa.', '"Every step of the way" = durante todo o caminho.'),
      ]),
    ],
  },
];
