// Lote verbos-2: Verbos Essenciais, módulo 2 (see, come, want, look, use, find,
// give, tell, work, call). Cada verbo em quatro frases (presente, passado, futuro
// com will, present perfect) com nota gramatical; capítulo final revisa as
// três formas. Conteúdo original.

export const LEXICON = {
  fridays: ['proper noun', '/ˈfraɪdeɪz/', 'sextas-feiras'],
  japan: ['proper noun', '/dʒəˈpæn/', 'Japão'],
  spring: ['noun', '/sprɪŋ/', 'primavera'],
  "you'll": ['pronoun', '/juːl/', 'você vai (you will)'],
  advice: ['noun', '/ədˈvaɪs/', 'conselho(s)'],
  anyone: ['pronoun', '/ˈɛniwʌn/', 'alguém, ninguém'],
  app: ['noun', '/æp/', 'aplicativo'],
  boss: ['noun', '/bɔːs/', 'chefe'],
  called: ['verb', '/kɔːld/', 'ligou, chamou'],
  comes: ['verb', '/kʌmz/', 'vem (he/she/it)'],
  deals: ['noun', '/diːlz/', 'ofertas, negócios'],
  everywhere: ['adverb', '/ˈɛvriwɛr/', 'em todo lugar'],
  found: ['verb', '/faʊnd/', 'achou, encontrado'],
  gave: ['verb', '/ɡeɪv/', 'deu'],
  given: ['verb', '/ˈɡɪvən/', 'dado'],
  his: ['determiner', '/hɪz/', 'dele'],
  looked: ['verb', '/lʊkt/', 'olhou, pareceu'],
  movie: ['noun', '/ˈmuːvi/', 'filme'],
  never: ['adverb', '/ˈnɛvər/', 'nunca'],
  online: ['adverb', '/ˌɑːnˈlaɪn/', 'na internet'],
  party: ['noun', '/ˈpɑːrti/', 'festa'],
  place: ['noun', '/pleɪs/', 'lugar'],
  plan: ['noun', '/plæn/', 'plano'],
  smoking: ['noun', '/ˈsmoʊkɪŋ/', 'fumar, o hábito de fumar'],
  told: ['verb', '/toʊld/', 'contou, disse'],
  truth: ['noun', '/truːθ/', 'verdade'],
  used: ['verb', '/juːzd/', 'usou, usado'],
  wanted: ['verb', '/ˈwɑːntɪd/', 'quis, queria'],
  "won't": ['modal verb', '/woʊnt/', 'não vai (will not)'],
  worked: ['verb', '/wɜːrkt/', 'trabalhou'],
  year: ['noun', '/jɪr/', 'ano'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const verbForms = (text, pt, note, example) => ({ kind: 'verb_forms', text, pt, note, example });

export const COURSES = [
  {
    id: 'course-essential-verbs-a1',
    slug: 'essential-verbs',
    title: 'Verbos Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 3,
    order: 12,
    short: 'Os verbos mais usados em frases separadas por tempo: presente, passado, futuro e present perfect.',
    long: 'Cada verbo aparece em quatro frases reais, uma por tempo verbal, com a explicação gramatical de cada forma. No fim de cada módulo, você revisa as três formas (base, passado e particípio).',
    lessons: [
      {
        id: 'lesson-essential-verbs-a1-07',
        chapter: 7,
        title: 'see e come',
        description: 'Ver e vir nos quatro tempos.',
        units: [
          s('I see my parents every Sunday.', 'Eu vejo meus pais todo domingo.', 'Presente de "see" (ver). "Every Sunday" indica hábito. Com he/she/it: "sees".'),
          s('I saw a great movie last night.', 'Vi um filme ótimo ontem à noite.', 'Passado irregular de "see": "saw". "Last night" = ontem à noite.'),
          s('I will see you tomorrow.', 'Vejo você amanhã.', 'Futuro com "will". Na fala vira "I\'ll see you" ou só "See you tomorrow".'),
          s('Have you seen my keys?', 'Você viu minhas chaves?', 'Present perfect: have + "seen". Usado quando o resultado importa agora (as chaves sumiram).'),
          s('She comes to work by train.', 'Ela vem para o trabalho de trem.', 'Presente de "come" (vir) com he/she/it: "comes".'),
          s('They came to the party late.', 'Eles chegaram tarde na festa.', 'Passado irregular: "came".'),
          s('Will you come with us?', 'Você vem com a gente?', 'Futuro em pergunta: "will" antes do sujeito. Convite natural.'),
          s('Spring has come early this year.', 'A primavera chegou cedo este ano.', 'Particípio de "come" é igual à base: "come". "This year" combina com present perfect.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-08',
        chapter: 8,
        title: 'want e look',
        description: 'Querer e olhar/parecer nos quatro tempos.',
        units: [
          s('I want a new job.', 'Eu quero um emprego novo.', '"Want" + substantivo, ou "want to" + verbo: "I want to travel".'),
          s('He wanted to call you.', 'Ele queria ligar para você.', 'Passado regular: "wanted". O "-ed" soa /ɪd/ depois de "t".'),
          s('You will want to see this.', 'Você vai querer ver isto.', 'Futuro com "will". Expressão comum para chamar a atenção.'),
          s('I have always wanted to visit Japan.', 'Sempre quis visitar o Japão.', 'Present perfect + "always": desejo que vem do passado até hoje.'),
          s('You look tired.', 'Você parece cansado.', '"Look" + adjetivo = parecer. "Look at" + objeto = olhar para.'),
          s('She looked at the map.', 'Ela olhou o mapa.', 'Passado regular: "looked" (o "-ed" soa /t/). "Look at" = olhar para.'),
          s('I will look for it later.', 'Vou procurar depois.', '"Look for" = procurar (phrasal verb). Futuro com "will".'),
          s("I've looked everywhere.", 'Já procurei em todo lugar.', 'Present perfect: "have looked". "Everywhere" = em todo lugar.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-09',
        chapter: 9,
        title: 'use e find',
        description: 'Usar e encontrar nos quatro tempos.',
        units: [
          s('I use my phone for everything.', 'Uso o celular para tudo.', 'Presente de "use" (verbo): o "s" soa /z/: /juːz/.'),
          s('We used a map to find the hotel.', 'Usamos um mapa para achar o hotel.', 'Passado regular: "used". Não confunda com "used to" (costumava).'),
          s('Will you use the car today?', 'Você vai usar o carro hoje?', 'Futuro em pergunta com "will".'),
          s("I've never used this app.", 'Nunca usei este aplicativo.', 'Present perfect + "never": experiência que nunca aconteceu.'),
          s('I always find good deals online.', 'Sempre acho boas ofertas na internet.', '"Find" = encontrar, achar. "Deal" = oferta, negócio.'),
          s('She found her passport in the car.', 'Ela achou o passaporte no carro.', 'Passado irregular: "found".'),
          s("You'll find it on the second floor.", 'Você vai encontrar no segundo andar.', 'Futuro com "will" contraído: "you\'ll". Muito usado para dar direções.'),
          s('Have you found a place to stay?', 'Você já achou um lugar para ficar?', 'Present perfect: "have found". Pergunta sobre algo que pode já ter acontecido.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-10',
        chapter: 10,
        title: 'give e tell',
        description: 'Dar e contar/dizer nos quatro tempos.',
        units: [
          s('My parents give me advice.', 'Meus pais me dão conselhos.', '"Give" + pessoa + coisa: "give me advice". "Advice" é incontável.'),
          s('He gave me his number.', 'Ele me deu o número dele.', 'Passado irregular: "gave".'),
          s("I'll give it back tomorrow.", 'Devolvo amanhã.', '"Give back" = devolver (phrasal verb). Objeto no meio: "give it back".'),
          s('She has given up smoking.', 'Ela parou de fumar.', '"Give up" = desistir, largar um hábito. Particípio irregular: "given".'),
          s('Tell me about your trip.', 'Me conte sobre a sua viagem.', '"Tell" + pessoa: "tell me". "Say" não leva a pessoa direto: "say to me".'),
          s('She told me the truth.', 'Ela me contou a verdade.', 'Passado irregular: "told". "Tell the truth" = dizer a verdade.'),
          s("I won't tell anyone.", 'Não vou contar para ninguém.', 'Futuro negativo: "won\'t" = "will not".'),
          s('Have you told your boss?', 'Você já contou para o seu chefe?', 'Present perfect: "have told". Particípio igual ao passado.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-11',
        chapter: 11,
        title: 'work e call',
        description: 'Trabalhar/funcionar e ligar/chamar nos quatro tempos.',
        units: [
          s('I work from home on Fridays.', 'Trabalho de casa às sextas.', '"Work from home" = trabalhar remoto. "Work" também é funcionar: "it works".'),
          s('He worked there for five years.', 'Ele trabalhou lá por cinco anos.', 'Passado regular: "worked". Com "for" + período terminado, passado simples.'),
          s('Will this plan work?', 'Esse plano vai dar certo?', '"Work" = funcionar, dar certo. Futuro em pergunta.'),
          s('I have worked here since January.', 'Trabalho aqui desde janeiro.', 'Present perfect + "since": começou no passado e continua. Em português usamos o presente.'),
          s('Call me when you arrive.', 'Me liga quando chegar.', '"Call" = ligar. Depois de "when" o inglês usa presente ("arrive").'),
          s('I called the hotel yesterday.', 'Liguei para o hotel ontem.', 'Passado regular: "called". "Call" não leva "to": "call the hotel".'),
          s("I'll call you back.", 'Eu te ligo de volta.', '"Call back" = retornar a ligação. Objeto no meio: "call you back".'),
          s('Has anyone called?', 'Alguém ligou?', 'Present perfect em pergunta com "has": "anyone" pede verbo no singular.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-12',
        chapter: 12,
        title: 'Revisão: módulo 2',
        description: 'Base, passado e particípio dos 10 verbos do módulo 2.',
        units: [
          verbForms('see saw seen', 'ver', 'Base "see" · passado "saw" · particípio "seen". Irregular.', ['I saw a great movie last night.', 'Vi um filme ótimo ontem à noite.']),
          verbForms('come came come', 'vir', 'Base "come" · passado "came" · particípio "come" (igual à base).', ['They came to the party late.', 'Eles chegaram tarde na festa.']),
          verbForms('want wanted wanted', 'querer', 'Regular: passado e particípio com "-ed" (/ɪd/ depois de "t").', ['He wanted to call you.', 'Ele queria ligar para você.']),
          verbForms('look looked looked', 'olhar, parecer', 'Regular: "-ed" soa /t/ depois de "k".', ['She looked at the map.', 'Ela olhou o mapa.']),
          verbForms('use used used', 'usar', 'Regular: "-d" soa /d/. "Used to" (costumava) é outra estrutura.', ['We used a map to find the hotel.', 'Usamos um mapa para achar o hotel.']),
          verbForms('find found found', 'encontrar', 'Base "find" · passado e particípio "found".', ['She found her passport in the car.', 'Ela achou o passaporte no carro.']),
          verbForms('give gave given', 'dar', 'Base "give" · passado "gave" · particípio "given".', ['He gave me his number.', 'Ele me deu o número dele.']),
          verbForms('tell told told', 'contar, dizer', 'Base "tell" · passado e particípio "told".', ['She told me the truth.', 'Ela me contou a verdade.']),
          verbForms('work worked worked', 'trabalhar, funcionar', 'Regular: "-ed" soa /t/.', ['He worked there for five years.', 'Ele trabalhou lá por cinco anos.']),
          verbForms('call called called', 'ligar, chamar', 'Regular: "-ed" soa /d/.', ['I called the hotel yesterday.', 'Liguei para o hotel ontem.']),
        ],
      },
    ],
  },
];
