// Lote verbos-6: Verbos Essenciais, módulos 6 e 7 (lose, pay, meet, include,
// continue, set, learn, change, lead, understand; watch, follow, stop, create,
// speak, read, spend, grow, open, walk). Quatro frases por verbo (presente,
// passado, futuro com will, present perfect) com nota; revisão por módulo.
// Conteúdo original.

export const LEXICON = {
  tomatoes: ["noun", "/təˈmeɪtoʊz/", "tomates"],
  band: ["noun", "/bænd/", "banda"],
  continue: ["verb", "/kənˈtɪnjuː/", "continuar"],
  continues: ["verb", "/kənˈtɪnjuːz/", "continua"],
  create: ["verb", "/kriˈeɪt/", "criar"],
  created: ["verb", "/kriˈeɪtɪd/", "criou"],
  creates: ["verb", "/kriˈeɪts/", "cria"],
  exit: ["noun", "/ˈɛɡzɪt/", "saída"],
  followed: ["verb", "/ˈfɑːloʊd/", "seguiu"],
  grew: ["verb", "/ɡruː/", "cresceu"],
  grow: ["verb", "/ɡroʊ/", "crescer"],
  grown: ["verb", "/ɡroʊn/", "crescido"],
  include: ["verb", "/ɪnˈkluːd/", "incluir"],
  includes: ["verb", "/ɪnˈkluːdz/", "inclui"],
  jobs: ["noun", "/dʒɑːbz/", "empregos"],
  languages: ["noun", "/ˈlæŋɡwɪdʒɪz/", "idiomas"],
  lead: ["verb", "/liːd/", "liderar, levar a"],
  leads: ["verb", "/liːdz/", "lidera"],
  learned: ["verb", "/lɜːrnd/", "aprendeu"],
  lessons: ["noun", "/ˈlɛsənz/", "aulas"],
  miles: ["noun", "/maɪlz/", "milhas"],
  opens: ["verb", "/ˈoʊpənz/", "abre"],
  rise: ["verb", "/raɪz/", "subir"],
  savings: ["noun", "/ˈseɪvɪŋz/", "economias"],
  signs: ["noun", "/saɪnz/", "placas"],
  speaks: ["verb", "/spiːks/", "fala"],
  spend: ["verb", "/spɛnd/", "gastar, passar (tempo)"],
  spent: ["verb", "/spɛnt/", "gastou, passou"],
  spoke: ["verb", "/spoʊk/", "falou"],
  spoken: ["verb", "/ˈspoʊkən/", "falado"],
  stopped: ["verb", "/stɑːpt/", "parou"],
  understood: ["verb", "/ˌʌndərˈstʊd/", "entendeu"],
  version: ["noun", "/ˈvɜːrʒən/", "versão"],
  videos: ["noun", "/ˈvɪdioʊz/", "vídeos"],
  walked: ["verb", "/wɔːkt/", "caminhou"],
  wedding: ["noun", "/ˈwɛdɪŋ/", "casamento"],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const vf = (text, pt, note, example) => ({ kind: 'verb_forms', text, pt, note, example });

export const COURSES = [
  {
    id: 'course-essential-verbs-a1',
    slug: 'essential-verbs',
    title: 'Verbos Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 3,
    order: 12,
    short: 'Os verbos mais usados em frases separadas por tempo: presente, passado, futuro e present perfect.',
    long: 'Cada verbo aparece em quatro frases reais, uma por tempo verbal, com a explicação gramatical de cada forma. No fim de cada módulo, você revisa as três formas (base, passado e particípio).',
    lessons: [
      {
        id: 'lesson-essential-verbs-a1-31', chapter: 31, title: 'lose e pay', description: 'Perder e pagar nos quatro tempos.',
        units: [
          s('I always lose my keys.', 'Eu sempre perco minhas chaves.', 'Presente de "lose" (perder). Pronúncia /luːz/; "loose" = solto.'),
          s('We lost the game.', 'Perdemos o jogo.', 'Passado irregular: "lost".'),
          s("You won't lose anything.", 'Você não vai perder nada.', 'Futuro negativo: "won\'t" + base.'),
          s("I've lost my wallet.", 'Perdi minha carteira (e ainda não achei).', 'Present perfect: resultado agora.'),
          s('I pay my rent every month.', 'Pago meu aluguel todo mês.', '"Pay" = pagar. "Rent" = aluguel.'),
          s('She paid for the tickets.', 'Ela pagou as passagens.', 'Passado irregular: "paid". "Pay for" + o que se compra.'),
          s("I'll pay you back next week.", 'Te pago semana que vem.', '"Pay back" = devolver dinheiro.'),
          s('Have you paid the bill?', 'Você já pagou a conta?', 'Present perfect em pergunta.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-32', chapter: 32, title: 'meet e include', description: 'Encontrar/conhecer e incluir nos quatro tempos.',
        units: [
          s('We meet every Friday.', 'A gente se encontra toda sexta.', '"Meet" = encontrar-se (combinado).'),
          s('I met my wife at work.', 'Conheci minha esposa no trabalho.', 'Passado irregular: "met". "Meet" também é conhecer alguém.'),
          s("I'll meet you at the station.", 'Te encontro na estação.', 'Futuro com "will".'),
          s('Have you met my brother?', 'Você já conhece meu irmão?', 'Present perfect para apresentar alguém.'),
          s('The price includes breakfast.', 'O preço inclui café da manhã.', '"Include" = incluir. Com he/she/it: "includes".'),
          s('They included me in the plan.', 'Eles me incluíram no plano.', 'Passado regular: "included".'),
          s('The next version will include more lessons.', 'A próxima versão vai incluir mais aulas.', 'Futuro com "will".'),
          s("I've included the report in the email.", 'Incluí o relatório no e-mail.', 'Present perfect: ação recente com resultado.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-33', chapter: 33, title: 'continue e learn', description: 'Continuar e aprender nos quatro tempos.',
        units: [
          s('The road continues for miles.', 'A estrada continua por quilômetros.', '"Continue" com he/she/it: "continues". "Miles" = milhas.'),
          s('We continued after lunch.', 'Continuamos depois do almoço.', 'Passado regular: "continued".'),
          s('Prices will continue to rise.', 'Os preços vão continuar subindo.', '"Continue to" + verbo = continuar a.'),
          s('It has continued to rain all week.', 'Continuou chovendo a semana toda.', 'Present perfect: começou e continua.'),
          s('I learn a new word every day.', 'Aprendo uma palavra nova todo dia.', '"Learn" = aprender (quem aprende). "Teach" = ensinar.'),
          s('She learned to swim as a child.', 'Ela aprendeu a nadar quando criança.', 'Passado: "learned" (EUA) ou "learnt" (Reino Unido).'),
          s('You will learn fast.', 'Você vai aprender rápido.', '"Fast" = rápido (advérbio).'),
          s("I've learned a lot this year.", 'Aprendi muito este ano.', 'Present perfect + "this year".'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-34', chapter: 34, title: 'change e understand', description: 'Mudar/trocar e entender nos quatro tempos.',
        units: [
          s('I change my password every month.', 'Mudo minha senha todo mês.', '"Change" = mudar, trocar.'),
          s('She changed her mind.', 'Ela mudou de ideia.', '"Change your mind" = mudar de ideia.'),
          s('This will change everything.', 'Isso vai mudar tudo.', 'Futuro com "will".'),
          s('The city has changed a lot.', 'A cidade mudou muito.', 'Present perfect: mudança com efeito agora.'),
          s('I understand what you mean.', 'Entendo o que você quer dizer.', '"Understand" é verbo de estado: não vai para o contínuo.'),
          s("I didn't understand the question.", 'Não entendi a pergunta.', 'Passado negativo: "didn\'t" + base.'),
          s('You will understand later.', 'Você vai entender depois.', 'Futuro com "will".'),
          s('Have you understood the rules?', 'Você entendeu as regras?', 'Particípio irregular: "understood".'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-35', chapter: 35, title: 'lead e set', description: 'Liderar/levar a e definir/pôr nos quatro tempos.',
        units: [
          s('She leads a team of ten.', 'Ela lidera uma equipe de dez.', '"Lead" /liːd/ = liderar.'),
          s('He led the project last year.', 'Ele liderou o projeto no ano passado.', 'Passado irregular: "led" /lɛd/.'),
          s('This road will lead you to the beach.', 'Esta estrada vai te levar à praia.', '"Lead to" = levar a.'),
          s('Small changes have led to big results.', 'Pequenas mudanças levaram a grandes resultados.', 'Particípio: "led".'),
          s('I set my alarm for six.', 'Coloco o despertador para as seis.', '"Set" = programar, pôr. Base, passado e particípio iguais.'),
          s('We set a goal last month.', 'Definimos uma meta no mês passado.', 'Passado igual à base: "set".'),
          s("I'll set the table.", 'Eu ponho a mesa.', '"Set the table" = pôr a mesa.'),
          s('Have you set a date for the wedding?', 'Vocês já marcaram a data do casamento?', '"Set a date" = marcar a data.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-36', chapter: 36, title: 'Revisão: módulo 6', description: 'Base, passado e particípio dos 10 verbos do módulo 6.',
        units: [
          vf('lose lost lost', 'perder', 'Base "lose" · passado e particípio "lost".', ['We lost the game.', 'Perdemos o jogo.']),
          vf('pay paid paid', 'pagar', 'Base "pay" · passado e particípio "paid" (não "payed").', ['She paid for the tickets.', 'Ela pagou as passagens.']),
          vf('meet met met', 'encontrar, conhecer', 'Base "meet" · passado e particípio "met".', ['I met my wife at work.', 'Conheci minha esposa no trabalho.']),
          vf('include included included', 'incluir', 'Regular.', ['They included me in the plan.', 'Eles me incluíram no plano.']),
          vf('continue continued continued', 'continuar', 'Regular.', ['We continued after lunch.', 'Continuamos depois do almoço.']),
          vf('set set set', 'pôr, definir', 'As três formas são iguais.', ['We set a goal last month.', 'Definimos uma meta no mês passado.']),
          vf('learn learned learned', 'aprender', 'Regular nos EUA; no Reino Unido também "learnt".', ['She learned to swim as a child.', 'Ela aprendeu a nadar quando criança.']),
          vf('change changed changed', 'mudar', 'Regular.', ['She changed her mind.', 'Ela mudou de ideia.']),
          vf('lead led led', 'liderar', 'Base "lead" /liːd/ · passado e particípio "led" /lɛd/.', ['He led the project last year.', 'Ele liderou o projeto no ano passado.']),
          vf('understand understood understood', 'entender', 'Base "understand" · passado e particípio "understood".', ["I didn't understand the question.", 'Não entendi a pergunta.']),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-37', chapter: 37, title: 'watch e follow', description: 'Assistir e seguir nos quatro tempos.',
        units: [
          s('I watch the news every night.', 'Assisto ao jornal toda noite.', '"Watch" = assistir com atenção (TV, jogo). Com he/she/it: "watches".'),
          s('We watched a movie yesterday.', 'Assistimos a um filme ontem.', 'Passado regular: "watched" (/t/).'),
          s("I'll watch the kids tonight.", 'Eu cuido das crianças hoje à noite.', '"Watch" também é vigiar, cuidar.'),
          s("I've never watched that series.", 'Nunca assisti a essa série.', 'Present perfect + "never".'),
          s('Follow me, please.', 'Me siga, por favor.', 'Imperativo de "follow".'),
          s('We followed the signs to the exit.', 'Seguimos as placas até a saída.', 'Passado regular: "followed".'),
          s('I will follow your advice.', 'Vou seguir seu conselho.', '"Advice" é incontável.'),
          s('She has followed this band for years.', 'Ela acompanha essa banda há anos.', 'Present perfect + "for".'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-38', chapter: 38, title: 'stop e create', description: 'Parar e criar nos quatro tempos.',
        units: [
          s('The bus stops here.', 'O ônibus para aqui.', '"Stop" com he/she/it: "stops".'),
          s('It stopped raining.', 'Parou de chover.', '"Stop" + "-ing" = parar de fazer.'),
          s("I'll stop at the store on the way.", 'Vou passar no mercado no caminho.', '"Stop at" = dar uma parada em.'),
          s("I've stopped drinking coffee.", 'Parei de tomar café.', 'Present perfect: mudança de hábito.'),
          s('She creates videos for work.', 'Ela cria vídeos para o trabalho.', '"Create" = criar.'),
          s('He created his own company.', 'Ele criou a própria empresa.', 'Passado regular: "created".'),
          s('We will create a new plan.', 'Vamos criar um plano novo.', 'Futuro com "will".'),
          s('The company has created many jobs.', 'A empresa criou muitos empregos.', 'Present perfect: resultado atual.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-39', chapter: 39, title: 'speak e read', description: 'Falar e ler nos quatro tempos.',
        units: [
          s('She speaks three languages.', 'Ela fala três idiomas.', '"Speak" + idioma. "Speak" é mais formal que "talk".'),
          s('I spoke to the manager.', 'Falei com o gerente.', 'Passado irregular: "spoke".'),
          s('Will you speak at the meeting?', 'Você vai falar na reunião?', 'Pergunta com "will".'),
          s("I've spoken to her about it.", 'Já falei com ela sobre isso.', 'Particípio irregular: "spoken".'),
          s('I read before bed.', 'Leio antes de dormir.', '"Read" presente: /riːd/.'),
          s('I read that book last year.', 'Li esse livro no ano passado.', 'Passado igual na escrita, mas pronúncia /rɛd/.'),
          s("I'll read it tonight.", 'Vou ler hoje à noite.', 'Futuro: "will read" /riːd/.'),
          s('Have you read the news?', 'Você leu a notícia?', 'Particípio "read" /rɛd/.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-40', chapter: 40, title: 'spend e grow', description: 'Gastar/passar tempo e crescer nos quatro tempos.',
        units: [
          s('I spend too much money on coffee.', 'Gasto dinheiro demais com café.', '"Spend on" = gastar com.'),
          s('We spent the weekend at the beach.', 'Passamos o fim de semana na praia.', '"Spend time" = passar tempo. Passado: "spent".'),
          s("I'll spend more time with my family.", 'Vou passar mais tempo com minha família.', 'Futuro com "will".'),
          s("We've spent all our savings.", 'Gastamos todas as nossas economias.', 'Particípio: "spent".'),
          s('Tomatoes grow fast in summer.', 'Tomates crescem rápido no verão.', '"Grow" = crescer; também cultivar.'),
          s('I grew up in a small town.', 'Cresci numa cidade pequena.', '"Grow up" = crescer (infância). Passado: "grew".'),
          s('The company will grow next year.', 'A empresa vai crescer no ano que vem.', 'Futuro com "will".'),
          s('Your kids have grown so much!', 'Seus filhos cresceram muito!', 'Particípio irregular: "grown".'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-41', chapter: 41, title: 'open e walk', description: 'Abrir e andar nos quatro tempos.',
        units: [
          s('The bank opens at ten.', 'O banco abre às dez.', 'Horário fixo com presente simples.'),
          s('She opened the window.', 'Ela abriu a janela.', 'Passado regular: "opened".'),
          s("I'll open the door for you.", 'Eu abro a porta para você.', 'Oferta com "will".'),
          s('A new restaurant has opened downtown.', 'Um restaurante novo abriu no centro.', 'Present perfect: novidade recente.'),
          s('I walk to work.', 'Vou a pé para o trabalho.', '"Walk to" = ir a pé até.'),
          s('We walked along the beach.', 'Caminhamos pela praia.', '"Walk along" = caminhar ao longo de.'),
          s("I'll walk the dog later.", 'Vou passear com o cachorro depois.', '"Walk the dog" = levar o cachorro para passear.'),
          s("I've walked ten thousand steps today.", 'Já andei dez mil passos hoje.', 'Present perfect + "today".'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-42', chapter: 42, title: 'Revisão: módulo 7', description: 'Base, passado e particípio dos 10 verbos do módulo 7.',
        units: [
          vf('watch watched watched', 'assistir', 'Regular: "-ed" soa /t/.', ['We watched a movie yesterday.', 'Assistimos a um filme ontem.']),
          vf('follow followed followed', 'seguir', 'Regular.', ['We followed the signs to the exit.', 'Seguimos as placas até a saída.']),
          vf('stop stopped stopped', 'parar', 'Regular, dobra o "p": stopped.', ['It stopped raining.', 'Parou de chover.']),
          vf('create created created', 'criar', 'Regular.', ['He created his own company.', 'Ele criou a própria empresa.']),
          vf('speak spoke spoken', 'falar', 'Base "speak" · passado "spoke" · particípio "spoken".', ['I spoke to the manager.', 'Falei com o gerente.']),
          vf('read read read', 'ler', 'Escrita igual; pronúncia /riːd/ · /rɛd/ · /rɛd/.', ['I read that book last year.', 'Li esse livro no ano passado.']),
          vf('spend spent spent', 'gastar, passar (tempo)', 'Base "spend" · passado e particípio "spent".', ['We spent the weekend at the beach.', 'Passamos o fim de semana na praia.']),
          vf('grow grew grown', 'crescer', 'Base "grow" · passado "grew" · particípio "grown".', ['I grew up in a small town.', 'Cresci numa cidade pequena.']),
          vf('open opened opened', 'abrir', 'Regular.', ['She opened the window.', 'Ela abriu a janela.']),
          vf('walk walked walked', 'andar, caminhar', 'Regular; o "l" é mudo: /wɔːk/.', ['We walked along the beach.', 'Caminhamos pela praia.']),
        ],
      },
    ],
  },
];
