// Lote verbos-1: Verbos Essenciais refeito por tempo verbal. Cada verbo vira
// frases separadas (presente, passado, futuro com will, present perfect), cada
// uma com nota gramatical; o último capítulo revisa as três formas.
// Substitui o capítulo 1 publicado em fundamentos-1 (que juntava as três formas
// numa única digitação). Conteúdo original.

export const LEXICON = {
  // pronomes e determinantes
  him: ['pronoun', '/hɪm/', 'ele, o, lhe'],
  someone: ['pronoun', '/ˈsʌmwʌn/', 'alguém'],
  people: ['noun', '/ˈpiːpəl/', 'pessoas'],
  // verbos (formas)
  was: ['verb', '/wʌz/', 'era, estava'],
  will: ['modal verb', '/wɪl/', 'marca de futuro'],
  has: ['verb', '/hæz/', 'tem (he/she/it)'],
  makes: ['verb', '/meɪks/', 'faz (he/she/it)'],
  done: ['verb', '/dʌn/', 'feito (particípio de do)'],
  gotten: ['verb', '/ˈɡɑːtən/', 'conseguido, recebido'],
  known: ['verb', '/noʊn/', 'sabido, conhecido'],
  taken: ['verb', '/ˈteɪkən/', 'pegado, levado'],
  took: ['verb', '/tʊk/', 'pegou, levou'],
  knew: ['verb', '/nuː/', 'sabia, conheceu'],
  thought: ['verb', '/θɔːt/', 'pensou, pensado'],
  said: ['verb', '/sɛd/', 'disse, dito'],
  made: ['verb', '/meɪd/', 'fez, feito'],
  went: ['verb', '/wɛnt/', 'foi (passado de go)'],
  gone: ['verb', '/ɡɔːn/', 'ido (particípio de go)'],
  got: ['verb', '/ɡɑːt/', 'conseguiu, pegou'],
  did: ['verb', '/dɪd/', 'fez'],
  had: ['verb', '/hæd/', 'teve, tinha'],
  been: ['verb', '/bɪn/', 'sido, estado'],
  see: ['verb', '/siː/', 'ver'],
  // substantivos
  teacher: ['noun', '/ˈtiːtʃər/', 'professor, professora'],
  cats: ['noun', '/kæts/', 'gatos'],
  cold: ['noun', '/koʊld/', 'resfriado; frio'],
  meeting: ['noun', '/ˈmiːtɪŋ/', 'reunião'],
  car: ['noun', '/kɑːr/', 'carro'],
  homework: ['noun', '/ˈhoʊmwɜːrk/', 'lição de casa'],
  dishes: ['noun', '/ˈdɪʃɪz/', 'louça, pratos'],
  dinner: ['noun', '/ˈdɪnər/', 'jantar'],
  hello: ['interjection', '/həˈloʊ/', 'olá'],
  times: ['noun', '/taɪmz/', 'vezes'],
  bus: ['noun', '/bʌs/', 'ônibus'],
  beach: ['noun', '/biːtʃ/', 'praia'],
  sunday: ['proper noun', '/ˈsʌndeɪ/', 'domingo'],
  bed: ['noun', '/bɛd/', 'cama'],
  store: ['noun', '/stɔːr/', 'loja, mercado'],
  phone: ['noun', '/foʊn/', 'celular, telefone'],
  message: ['noun', '/ˈmɛsɪdʒ/', 'mensagem'],
  mistake: ['noun', '/mɪˈsteɪk/', 'erro'],
  decision: ['noun', '/dɪˈsɪʒən/', 'decisão'],
  answer: ['noun', '/ˈænsər/', 'resposta'],
  trip: ['noun', '/trɪp/', 'viagem'],
  shower: ['noun', '/ˈʃaʊər/', 'banho de chuveiro'],
  train: ['noun', '/treɪn/', 'trem'],
  hours: ['noun', '/aʊərz/', 'horas'],
  pen: ['noun', '/pɛn/', 'caneta'],
  morning: ['noun', '/ˈmɔːrnɪŋ/', 'manhã'],
  night: ['noun', '/naɪt/', 'noite'],
  week: ['noun', '/wiːk/', 'semana'],
  everything: ['pronoun', '/ˈɛvriθɪŋ/', 'tudo'],
  coffee: ['noun', '/ˈkɔːfi/', 'café'],
  // adjetivos, advérbios, outros
  great: ['adjective', '/ɡreɪt/', 'ótimo'],
  wrong: ['adjective', '/rɔːŋ/', 'errado'],
  right: ['adjective', '/raɪt/', 'certo'],
  early: ['adverb', '/ˈɜːrli/', 'cedo'],
  later: ['adverb', '/ˈleɪtər/', 'depois, mais tarde'],
  tonight: ['adverb', '/təˈnaɪt/', 'hoje à noite'],
  together: ['adverb', '/təˈɡɛðər/', 'juntos'],
  always: ['adverb', '/ˈɔːlweɪz/', 'sempre'],
  before: ['adverb', '/bɪˈfɔːr/', 'antes'],
  there: ['adverb', '/ðɛr/', 'lá'],
  last: ['adjective', '/læst/', 'passado, último'],
  many: ['determiner', '/ˈmɛni/', 'muitos'],
  two: ['numeral', '/tuː/', 'dois'],
  ten: ['numeral', '/tɛn/', 'dez'],
  seven: ['numeral', '/ˈsɛvən/', 'sete'],
  every: ['determiner', '/ˈɛvri/', 'todo, cada'],
  new: ['adjective', '/nuː/', 'novo'],
  after: ['preposition', '/ˈæftər/', 'depois de'],
  about: ['preposition', '/əˈbaʊt/', 'sobre, em'],
  by: ['preposition', '/baɪ/', 'de (meio), por'],
  when: ['conjunction', '/wɛn/', 'quando'],
  up: ['particle', '/ʌp/', 'para cima (partícula)'],
  yesterday: ['adverb', '/ˈjɛstərdeɪ/', 'ontem'],
  her: ['determiner', '/hɜːr/', 'dela; a, lhe'],
};

const verbForms = (text, pt, note, example) => ({ kind: 'verb_forms', text, pt, note, example });

export const COURSES = [
  {
    id: 'course-essential-verbs-a1',
    slug: 'essential-verbs',
    title: 'Verbos Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 3,
    order: 12,
    short: 'Os verbos mais usados em frases separadas por tempo: presente, passado, futuro e present perfect.',
    long: 'Cada verbo aparece em quatro frases reais, uma por tempo verbal, com a explicação gramatical de cada forma. No fim, você revisa as três formas (base, passado e particípio).',
    retireUnits: ['unit-essential-verbs-a1-01-09', 'unit-essential-verbs-a1-01-10'],
    lessons: [
      {
        id: 'lesson-essential-verbs-a1-01',
        chapter: 1,
        title: 'be e have',
        description: 'Ser/estar e ter nos quatro tempos.',
        units: [
          { kind: 'sentence', text: 'I am a teacher.', pt: 'Eu sou professor.', note: 'Presente de "be": I am, you/we/they are, he/she/it is. O mesmo verbo serve para "ser" e "estar".' },
          { kind: 'sentence', text: 'I was at home yesterday.', pt: 'Eu estava em casa ontem.', note: 'Passado de "be": "was" (I/he/she/it) e "were" (you/we/they). "Yesterday" pede o passado simples.' },
          { kind: 'sentence', text: 'I will be there tomorrow.', pt: 'Eu vou estar lá amanhã.', note: 'Futuro com "will" + verbo na forma base: "will be". "Will" não muda com a pessoa.' },
          { kind: 'sentence', text: 'I have been here before.', pt: 'Eu já estive aqui antes.', note: 'Present perfect: have/has + particípio ("been"). Fala de experiência sem data definida.' },
          { kind: 'sentence', text: 'We have two cats.', pt: 'Nós temos dois gatos.', note: 'Presente de "have": "have" (I/you/we/they) e "has" (he/she/it).' },
          { kind: 'sentence', text: 'She had a cold last week.', pt: 'Ela teve um resfriado semana passada.', note: 'Passado de "have": "had", igual para todas as pessoas. "Last week" marca o passado.' },
          { kind: 'sentence', text: 'They will have a meeting at ten.', pt: 'Eles vão ter uma reunião às dez.', note: 'Futuro: "will have". Depois de "will" o verbo nunca leva -s: "she will have", não "will has".' },
          { kind: 'sentence', text: 'I have had this car for years.', pt: 'Eu tenho este carro há anos.', note: 'Present perfect de "have": "have had". Com "for" + período, algo que começou no passado e continua até hoje.' },
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-02',
        chapter: 2,
        title: 'do e say',
        description: 'Fazer (tarefas) e dizer nos quatro tempos.',
        units: [
          { kind: 'sentence', text: 'I do my homework at night.', pt: 'Eu faço minha lição à noite.', note: 'Presente de "do" (fazer tarefas e atividades). Com he/she/it: "does".' },
          { kind: 'sentence', text: 'He did the dishes after dinner.', pt: 'Ele lavou a louça depois do jantar.', note: 'Passado de "do": "did", igual para todas as pessoas. "Do the dishes" é expressão fixa: lavar a louça.' },
          { kind: 'sentence', text: 'I will do it later.', pt: 'Eu vou fazer isso depois.', note: 'Futuro: "will do". "It" retoma algo que já foi mencionado.' },
          { kind: 'sentence', text: 'We have done everything.', pt: 'Nós já fizemos tudo.', note: 'Present perfect: have + "done". "Done" é o particípio irregular de "do".' },
          { kind: 'sentence', text: 'They always say hello.', pt: 'Eles sempre dizem olá.', note: 'Presente de "say" (dizer). Advérbios de frequência como "always" vêm antes do verbo principal.' },
          { kind: 'sentence', text: 'She said no.', pt: 'Ela disse não.', note: 'Passado de "say": "said", pronunciado /sɛd/ (não "seid").' },
          { kind: 'sentence', text: 'What will you say to him?', pt: 'O que você vai dizer para ele?', note: 'Futuro em pergunta: "will" vem antes do sujeito ("will you say").' },
          { kind: 'sentence', text: 'I have said it many times.', pt: 'Eu já disse isso muitas vezes.', note: 'Present perfect: "have said". "Many times" indica repetição sem data exata.' },
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-03',
        chapter: 3,
        title: 'go e get',
        description: 'Ir e conseguir/ficar nos quatro tempos.',
        units: [
          { kind: 'sentence', text: 'I go to work by bus.', pt: 'Eu vou para o trabalho de ônibus.', note: 'Presente de "go". Meio de transporte usa "by": by bus, by car. Com he/she/it: "goes".' },
          { kind: 'sentence', text: 'We went to the beach on Sunday.', pt: 'Nós fomos à praia no domingo.', note: 'Passado irregular de "go": "went". Dias da semana usam "on".' },
          { kind: 'sentence', text: 'I will go to bed early tonight.', pt: 'Vou dormir cedo hoje à noite.', note: 'Futuro: "will go". "Go to bed" = ir dormir.' },
          { kind: 'sentence', text: 'She has gone to the store.', pt: 'Ela foi ao mercado (e ainda não voltou).', note: '"Has gone": a pessoa foi e ainda está lá. Compare com "has been": foi e já voltou.' },
          { kind: 'sentence', text: 'I get up at seven.', pt: 'Eu me levanto às sete.', note: '"Get up" é um phrasal verb: levantar-se da cama. "Get" muda de sentido com a partícula.' },
          { kind: 'sentence', text: 'He got a new phone.', pt: 'Ele ganhou um celular novo.', note: 'Passado de "get": "got". "Get" + objeto = conseguir, receber, ganhar.' },
          { kind: 'sentence', text: 'It will get cold at night.', pt: 'Vai esfriar à noite.', note: '"Get" + adjetivo = ficar: get cold, get tired. Futuro com "will".' },
          { kind: 'sentence', text: 'Have you gotten my message?', pt: 'Você recebeu minha mensagem?', note: 'Particípio americano: "gotten" (no britânico, "got"). Na pergunta do present perfect, "have" vem antes do sujeito.' },
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-04',
        chapter: 4,
        title: 'make e know',
        description: 'Fazer (criar) e saber/conhecer nos quatro tempos.',
        units: [
          { kind: 'sentence', text: 'My mother makes great coffee.', pt: 'Minha mãe faz um café ótimo.', note: '"Make" = fazer no sentido de criar ou produzir; "do" = realizar tarefas. Com he/she/it: "makes".' },
          { kind: 'sentence', text: 'I made a mistake.', pt: 'Eu cometi um erro.', note: 'Passado de "make": "made". Diz-se "make a mistake", nunca "do a mistake".' },
          { kind: 'sentence', text: 'We will make dinner together.', pt: 'Nós vamos fazer o jantar juntos.', note: 'Futuro: "will make". Refeições usam "make": make dinner, make lunch.' },
          { kind: 'sentence', text: 'They have made a decision.', pt: 'Eles tomaram uma decisão.', note: 'Present perfect: "have made". "Make a decision" = tomar uma decisão.' },
          { kind: 'sentence', text: 'I know her sister.', pt: 'Eu conheço a irmã dela.', note: '"Know" = saber ou conhecer. O "k" é mudo: /noʊ/.' },
          { kind: 'sentence', text: 'I knew the answer.', pt: 'Eu sabia a resposta.', note: 'Passado irregular de "know": "knew", com o mesmo som de "new".' },
          { kind: 'sentence', text: 'You will know when you see it.', pt: 'Você vai saber quando vir.', note: 'Futuro: "will know". Depois de "when", o inglês usa o presente ("see") mesmo falando do futuro.' },
          { kind: 'sentence', text: 'I have known him for ten years.', pt: 'Eu o conheço há dez anos.', note: 'Present perfect + "for": conhecer desde o passado até hoje. Em português usamos presente + "há".' },
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-05',
        chapter: 5,
        title: 'think e take',
        description: 'Pensar/achar e pegar/levar nos quatro tempos.',
        units: [
          { kind: 'sentence', text: "I think you're right.", pt: 'Eu acho que você está certo.', note: '"Think" = achar, pensar. O "that" é opcional: "I think (that) you\'re right".' },
          { kind: 'sentence', text: 'I thought about you yesterday.', pt: 'Pensei em você ontem.', note: 'Passado de "think": "thought" /θɔːt/. "Think about" = pensar em.' },
          { kind: 'sentence', text: 'I will think about it.', pt: 'Vou pensar no assunto.', note: 'Futuro: "will think". Frase comum para adiar uma decisão com educação.' },
          { kind: 'sentence', text: 'Have you thought about the trip?', pt: 'Você já pensou na viagem?', note: 'Present perfect: have + "thought" (o particípio é igual ao passado).' },
          { kind: 'sentence', text: 'I take a shower every morning.', pt: 'Eu tomo banho toda manhã.', note: '"Take a shower" = tomar banho. "Every" + período indica hábito e pede o presente simples.' },
          { kind: 'sentence', text: 'He took the wrong train.', pt: 'Ele pegou o trem errado.', note: 'Passado de "take": "took". "Take" = pegar (transporte), levar.' },
          { kind: 'sentence', text: 'It will take two hours.', pt: 'Vai levar duas horas.', note: '"Take" + tempo = demorar, levar. Futuro com "will".' },
          { kind: 'sentence', text: 'Someone has taken my pen.', pt: 'Alguém pegou minha caneta.', note: 'Present perfect: "has taken". Mostra o resultado agora: a caneta não está aqui.' },
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-06',
        chapter: 6,
        title: 'Revisão: as três formas',
        description: 'Base, passado e particípio dos 10 verbos do módulo.',
        units: [
          verbForms('be was been', 'ser, estar', 'Base "be" · passado "was/were" · particípio "been". Irregular: o passado muda com a pessoa.', ['I have been here before.', 'Eu já estive aqui antes.']),
          verbForms('have had had', 'ter', 'Base "have" · passado "had" · particípio "had". No presente, "has" com he/she/it.', ['I have had this car for years.', 'Eu tenho este carro há anos.']),
          verbForms('do did done', 'fazer', 'Base "do" · passado "did" · particípio "done". "Did" também forma perguntas no passado.', ['We have done everything.', 'Nós já fizemos tudo.']),
          verbForms('say said said', 'dizer', 'Base "say" · passado e particípio "said" /sɛd/.', ['She said no.', 'Ela disse não.']),
          verbForms('go went gone', 'ir', 'Base "go" · passado "went" · particípio "gone". "Went" não se parece com a base: decore.', ['We went to the beach on Sunday.', 'Nós fomos à praia no domingo.']),
          verbForms('get got gotten', 'conseguir, ficar', 'Base "get" · passado "got" · particípio "gotten" (EUA) ou "got" (Reino Unido).', ['He got a new phone.', 'Ele ganhou um celular novo.']),
          verbForms('make made made', 'fazer (criar)', 'Base "make" · passado e particípio "made".', ['I made a mistake.', 'Eu cometi um erro.']),
          verbForms('know knew known', 'saber, conhecer', 'Base "know" · passado "knew" · particípio "known". O "k" é sempre mudo.', ['I knew the answer.', 'Eu sabia a resposta.']),
          verbForms('think thought thought', 'pensar, achar', 'Base "think" · passado e particípio "thought".', ['I thought about you yesterday.', 'Pensei em você ontem.']),
          verbForms('take took taken', 'pegar, levar', 'Base "take" · passado "took" · particípio "taken".', ['He took the wrong train.', 'Ele pegou o trem errado.']),
        ],
      },
    ],
  },
];
