// Lote verbos-5: Verbos Essenciais, módulo 5 (move, like, live, believe, hold,
// bring, happen, write, sit, stand). Quatro frases por verbo (presente, passado,
// futuro com will, present perfect) com nota gramatical; revisão das três formas.
// Conteúdo original.

export const LEXICON = {
  canada: ['proper noun', '/ˈkænədə/', 'Canadá'],
  italian: ['adjective', '/ɪˈtæliən/', 'italiano'],
  rio: ['proper noun', '/ˈriːoʊ/', 'Rio'],
  stand: ['verb', '/stænd/', 'ficar de pé; suportar'],
  abroad: ['adverb', '/əˈbrɔːd/', 'no exterior'],
  arms: ['noun', '/ɑːrmz/', 'braços'],
  believe: ['verb', '/bɪˈliːv/', 'acreditar'],
  believed: ['verb', '/bɪˈliːvd/', 'acreditou'],
  books: ['noun', '/bʊks/', 'livros'],
  brought: ['verb', '/brɔːt/', 'trouxe, levou'],
  building: ['noun', '/ˈbɪldɪŋ/', 'prédio'],
  century: ['noun', '/ˈsɛntʃəri/', 'século'],
  dessert: ['noun', '/dɪˈzɜːrt/', 'sobremesa'],
  flowers: ['noun', '/ˈflaʊərz/', 'flores'],
  gift: ['noun', '/ɡɪft/', 'presente'],
  happened: ['verb', '/ˈhæpənd/', 'aconteceu'],
  happens: ['verb', '/ˈhæpənz/', 'acontece'],
  held: ['verb', '/hɛld/', 'segurou, realizou'],
  journal: ['noun', '/ˈdʒɜːrnəl/', 'diário'],
  letter: ['noun', '/ˈlɛtər/', 'carta, letra'],
  lived: ['verb', '/lɪvd/', 'morou, viveu'],
  luck: ['noun', '/lʌk/', 'sorte'],
  men: ['noun', '/mɛn/', 'homens'],
  moved: ['verb', '/muːvd/', 'mudou-se, moveu'],
  sat: ['verb', '/sæt/', 'sentou'],
  stood: ['verb', '/stʊd/', 'ficou de pé'],
  story: ['noun', '/ˈstɔːri/', 'história'],
  while: ['noun', '/waɪl/', 'tempo (a while = um tempo)'],
  write: ['verb', '/raɪt/', 'escrever'],
  written: ['verb', '/ˈrɪtən/', 'escrito'],
  wrote: ['verb', '/roʊt/', 'escreveu'],
};

const s = (text, pt, note) => ({ kind: 'sentence', text, pt, note });
const verbForms = (text, pt, note, example) => ({ kind: 'verb_forms', text, pt, note, example });

export const COURSES = [
  {
    id: 'course-essential-verbs-a1',
    slug: 'essential-verbs',
    title: 'Verbos Essenciais',
    level: 'A1',
    category: 'grammar',
    track: 'fundamentos',
    trackOrder: 3,
    order: 12,
    short: 'Os verbos mais usados em frases separadas por tempo: presente, passado, futuro e present perfect.',
    long: 'Cada verbo aparece em quatro frases reais, uma por tempo verbal, com a explicação gramatical de cada forma. No fim de cada módulo, você revisa as três formas (base, passado e particípio).',
    lessons: [
      {
        id: 'lesson-essential-verbs-a1-25',
        chapter: 25,
        title: 'move e like',
        description: 'Mudar/mover e gostar nos quatro tempos.',
        units: [
          s('We move to a new apartment next month.', 'A gente se muda para um apartamento novo mês que vem.', 'Presente com sentido de futuro já marcado. "Move" = mudar de casa, mover.'),
          s('They moved to Canada last year.', 'Eles se mudaram para o Canadá no ano passado.', 'Passado regular: "moved" (/d/).'),
          s("I'll move the car.", 'Vou tirar o carro.', 'Futuro com "will" para decisão na hora.'),
          s('She has moved three times.', 'Ela já se mudou três vezes.', 'Present perfect + número de vezes, sem data.'),
          s('I like this song.', 'Gosto desta música.', '"Like" + substantivo, sem "of".'),
          s('He liked the gift.', 'Ele gostou do presente.', 'Passado regular: "liked" (/t/).'),
          s("You'll like this place.", 'Você vai gostar deste lugar.', 'Futuro com "will" para previsão.'),
          s("I've always liked Italian food.", 'Sempre gostei de comida italiana.', 'Present perfect + "always": gosto que vem de longe e continua.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-26',
        chapter: 26,
        title: 'live e believe',
        description: 'Morar/viver e acreditar nos quatro tempos.',
        units: [
          s('I live near the beach.', 'Moro perto da praia.', '"Live" = morar. "Near" = perto de, sem "of".'),
          s('We lived in Rio for two years.', 'Moramos no Rio por dois anos.', 'Passado com "for" + período já terminado.'),
          s('They will live abroad for a while.', 'Eles vão morar fora por um tempo.', '"Abroad" = no exterior. "For a while" = por um tempo.'),
          s("I've lived here since 2020.", 'Moro aqui desde 2020.', 'Present perfect + "since": ainda mora aqui.'),
          s("I don't believe you.", 'Não acredito em você.', '"Believe" + pessoa, sem preposição.'),
          s('Nobody believed his story.', 'Ninguém acreditou na história dele.', 'Passado regular: "believed".'),
          s("You won't believe what happened.", 'Você não vai acreditar no que aconteceu.', 'Abertura clássica de fofoca: "won\'t believe".'),
          s("I've never believed in luck.", 'Nunca acreditei em sorte.', '"Believe in" = acreditar em (ideia, existência).'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-27',
        chapter: 27,
        title: 'hold e bring',
        description: 'Segurar/realizar e trazer nos quatro tempos.',
        units: [
          s('Hold my bag, please.', 'Segura minha bolsa, por favor.', 'Imperativo de "hold" (segurar).'),
          s('She held the baby in her arms.', 'Ela segurou o bebê nos braços.', 'Passado irregular: "held".'),
          s('We will hold the meeting online.', 'Vamos fazer a reunião online.', '"Hold a meeting" = realizar uma reunião.'),
          s('The police have held two men.', 'A polícia deteve dois homens.', 'Particípio "held". "Police" sempre pede verbo no plural.'),
          s('Bring your passport.', 'Traga seu passaporte.', '"Bring" = trazer (para cá); "take" = levar (para lá).'),
          s('He brought flowers to the party.', 'Ele levou flores para a festa.', 'Passado irregular: "brought" /brɔːt/.'),
          s("I'll bring dessert.", 'Eu levo a sobremesa.', 'Oferta com "will". "Dessert" = sobremesa (um "s"); "desert" = deserto.'),
          s('Have you brought your laptop?', 'Você trouxe seu notebook?', 'Present perfect: "have brought".'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-28',
        chapter: 28,
        title: 'happen e write',
        description: 'Acontecer e escrever nos quatro tempos.',
        units: [
          s('What happens next?', 'O que acontece depois?', '"Happen" com he/she/it: "happens". Não usa objeto.'),
          s('What happened?', 'O que aconteceu?', 'Passado regular: "happened". Pergunta essencial.'),
          s('It will happen again.', 'Vai acontecer de novo.', 'Futuro com "will" para previsão.'),
          s('This has never happened before.', 'Isso nunca aconteceu antes.', 'Present perfect + "never" + "before".'),
          s('I write in my journal every night.', 'Escrevo no meu diário toda noite.', 'Presente para hábito. "Journal" = diário.'),
          s('She wrote a letter to her grandmother.', 'Ela escreveu uma carta para a avó.', 'Passado irregular: "wrote".'),
          s("I'll write it down.", 'Vou anotar.', '"Write down" = anotar. Objeto no meio: "write it down".'),
          s('He has written three books.', 'Ele escreveu três livros.', 'Particípio irregular: "written" (dois "t").'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-29',
        chapter: 29,
        title: 'sit e stand',
        description: 'Sentar e ficar de pé/aguentar nos quatro tempos.',
        units: [
          s('Please sit down.', 'Por favor, sente-se.', '"Sit down" = sentar-se.'),
          s('We sat by the window.', 'Sentamos perto da janela.', 'Passado irregular: "sat". "By" = ao lado de.'),
          s("I'll sit in the back.", 'Vou sentar atrás.', '"In the back" = na parte de trás.'),
          s("I've sat here all day.", 'Fiquei sentado aqui o dia todo.', 'Particípio igual ao passado: "sat".'),
          s('Stand in line, please.', 'Fique na fila, por favor.', '"Stand in line" = ficar na fila.'),
          s('He stood up to speak.', 'Ele se levantou para falar.', 'Passado irregular: "stood". "Stand up" = levantar-se.'),
          s("I can't stand the noise.", 'Não suporto o barulho.', '"Can\'t stand" = não suportar. Sentido diferente de "ficar de pé".'),
          s('The building has stood here for a century.', 'O prédio está aqui há um século.', 'Particípio "stood". Present perfect + "for" = há.'),
        ],
      },
      {
        id: 'lesson-essential-verbs-a1-30',
        chapter: 30,
        title: 'Revisão: módulo 5',
        description: 'Base, passado e particípio dos 10 verbos do módulo 5.',
        units: [
          verbForms('move moved moved', 'mudar, mover', 'Regular: "-d" soa /d/.', ['They moved to Canada last year.', 'Eles se mudaram para o Canadá no ano passado.']),
          verbForms('like liked liked', 'gostar', 'Regular: "-d" soa /t/.', ['He liked the gift.', 'Ele gostou do presente.']),
          verbForms('live lived lived', 'morar, viver', 'Regular: "-d" soa /d/.', ['We lived in Rio for two years.', 'Moramos no Rio por dois anos.']),
          verbForms('believe believed believed', 'acreditar', 'Regular.', ['Nobody believed his story.', 'Ninguém acreditou na história dele.']),
          verbForms('hold held held', 'segurar, realizar', 'Base "hold" · passado e particípio "held".', ['She held the baby in her arms.', 'Ela segurou o bebê nos braços.']),
          verbForms('bring brought brought', 'trazer', 'Base "bring" · passado e particípio "brought".', ['He brought flowers to the party.', 'Ele levou flores para a festa.']),
          verbForms('happen happened happened', 'acontecer', 'Regular.', ['What happened?', 'O que aconteceu?']),
          verbForms('write wrote written', 'escrever', 'Base "write" · passado "wrote" · particípio "written".', ['She wrote a letter to her grandmother.', 'Ela escreveu uma carta para a avó.']),
          verbForms('sit sat sat', 'sentar', 'Base "sit" · passado e particípio "sat".', ['We sat by the window.', 'Sentamos perto da janela.']),
          verbForms('stand stood stood', 'ficar de pé, aguentar', 'Base "stand" · passado e particípio "stood".', ['He stood up to speak.', 'Ele se levantou para falar.']),
        ],
      },
    ],
  },
];
