// Lote viagem-2: Viagem sem Aperto, capítulos 8–11 (café e padaria, farmácia,
// pedir direções, emergências). O que o aluno diz e o que ouve, com nota de uso.
// Conteúdo original.

export const LEXICON = {
  english: ['proper noun', '/ˈɪŋɡlɪʃ/', 'inglês'],
  help: ['interjection', '/hɛlp/', 'socorro; ajudar'],
  "i've": ['pronoun', '/aɪv/', 'eu tenho (I have)'],
  ambulance: ['noun', '/ˈæmbjələns/', 'ambulância'],
  and: ['conjunction', '/ænd/', 'e'],
  breathing: ['verb', '/ˈbriːðɪŋ/', 'respirando'],
  contact: ['verb', '/ˈkɑːntækt/', 'contatar'],
  corner: ['noun', '/ˈkɔːrnər/', 'esquina'],
  croissant: ['noun', '/krəˈsɑːnt/', 'croissant'],
  embassy: ['noun', '/ˈɛmbəsi/', 'embaixada'],
  far: ['adjective', '/fɑːr/', 'longe'],
  fever: ['noun', '/ˈfiːvər/', 'febre'],
  fresh: ['adjective', '/frɛʃ/', 'fresco'],
  headache: ['noun', '/ˈhɛdeɪk/', 'dor de cabeça'],
  heat: ['verb', '/hiːt/', 'aquecer'],
  hospital: ['noun', '/ˈhɑːspɪtəl/', 'hospital'],
  large: ['adjective', '/lɑːrdʒ/', 'grande'],
  left: ['adverb', '/lɛft/', 'à esquerda'],
  lost: ['adjective', '/lɔːst/', 'perdido; perdeu'],
  map: ['noun', '/mæp/', 'mapa'],
  milk: ['noun', '/mɪlk/', 'leite'],
  miss: ['verb', '/mɪs/', 'errar, perder; sentir falta'],
  nearest: ['adjective', '/ˈnɪrɪst/', 'mais próximo'],
  oat: ['noun', '/oʊt/', 'aveia'],
  often: ['adverb', '/ˈɔːfən/', 'frequentemente'],
  or: ['conjunction', '/ɔːr/', 'ou'],
  penicillin: ['noun', '/ˌpɛnɪˈsɪlɪn/', 'penicilina'],
  pills: ['noun', '/pɪlz/', 'comprimidos'],
  police: ['noun', '/pəˈliːs/', 'polícia'],
  prescription: ['noun', '/prɪˈskrɪpʃən/', 'receita médica'],
  report: ['verb', '/rɪˈpɔːrt/', 'registrar, relatar'],
  safe: ['adjective', '/seɪf/', 'seguro'],
  second: ['adjective', '/ˈsɛkənd/', 'segundo'],
  should: ['modal verb', '/ʃʊd/', 'deveria'],
  since: ['preposition', '/sɪns/', 'desde'],
  sleepy: ['adjective', '/ˈsliːpi/', 'com sono'],
  slowly: ['adverb', '/ˈsloʊli/', 'devagar'],
  sore: ['adjective', '/sɔːr/', 'dolorido'],
  speak: ['verb', '/spiːk/', 'falar'],
  stole: ['verb', '/stoʊl/', 'roubou'],
  straight: ['adverb', '/streɪt/', 'reto, em frente'],
  sunscreen: ['noun', '/ˈsʌnskriːn/', 'protetor solar'],
  theft: ['noun', '/θɛft/', 'furto, roubo'],
  throat: ['noun', '/θroʊt/', 'garganta'],
  walk: ['noun', '/wɔːk/', 'caminhada; andar'],
  well: ['adverb', '/wɛl/', 'bem'],
  wifi: ['noun', '/ˈwaɪfaɪ/', 'wi-fi'],
};

const s = (text, pt, note, groups = []) => ({ kind: 'sentence', text, pt, note, groups });

export const COURSES = [
  {
    id: 'course-travel-a2',
    slug: 'travel-no-stress-a2',
    title: 'Viagem sem Aperto',
    level: 'A2',
    category: 'travel',
    track: 'viagem',
    trackOrder: 1,
    order: 2,
    short: 'Aeroporto, hotel, transporte, restaurante, farmácia e emergências: as frases que você realmente precisa na viagem.',
    long: 'Situações de viagem com o que você diz e o que ouve do outro lado: despachar mala, resolver problema no quarto, pegar metrô, pedir no restaurante e no café, comprar remédio, pedir direções e lidar com emergências.',
    lessons: [
      {
        id: 'lesson-travel-a2-08',
        chapter: 8,
        title: 'Café e padaria',
        description: 'Pedir café, tamanhos, leite e algo para comer.',
        units: [
          s('Can I get a large coffee?', 'Pode me ver um café grande?', '"Can I get" é o jeito mais comum de pedir no balcão nos EUA. Tamanhos: small, medium, large.', [['Can', 'predicate_verb'], ['I', 'subject'], ['get', 'predicate_verb'], ['a large coffee?', 'direct_object']]),
          s('For here or to go?', 'Para comer aqui ou para levar?', 'Pergunta do atendente. Responda "For here" (aqui) ou "To go" (para levar).', [['For here', 'adverbial'], ['or', 'discourse_marker'], ['to go?', 'adverbial']]),
          s('With milk, please.', 'Com leite, por favor.', '"With" = com; "without" = sem. Vale para açúcar: "no sugar" = sem açúcar.', [['With milk,', 'adverbial'], ['please.', 'discourse_marker']]),
          s('Do you have oat milk?', 'Vocês têm leite de aveia?', 'Leites vegetais: oat (aveia), almond (amêndoa), soy (soja).', [['Do', 'predicate_verb'], ['you', 'subject'], ['have', 'predicate_verb'], ['oat milk?', 'direct_object']]),
          s("What's the name for the order?", 'Qual o nome para o pedido?', 'Em cafés dos EUA escrevem seu nome no copo. Soletre se precisar.', [["What's", 'predicate_verb'], ['the name', 'subject'], ['for the order?', 'adverbial']]),
          s("I'll have a croissant too.", 'Vou querer um croissant também.', '"Too" no fim da frase = também.', [["I'll have", 'predicate_verb'], ['a croissant', 'direct_object'], ['too.', 'adverbial']]),
          s('Is it fresh?', 'Está fresquinho?', '"Fresh" = fresco, feito hoje. Pergunta comum na padaria.', [['Is', 'predicate_verb'], ['it', 'subject'], ['fresh?', 'predicate_adj']]),
          s('Can you heat it up?', 'Pode esquentar?', '"Heat up" = esquentar (phrasal verb). O objeto vai no meio: "heat it up".', [['Can', 'predicate_verb'], ['you', 'subject'], ['heat', 'predicate_verb'], ['it', 'direct_object'], ['up?', 'predicate_verb']]),
          s('Is there wifi here?', 'Tem wi-fi aqui?', 'Pronúncia americana: /ˈwaɪfaɪ/. Pergunte a senha: "What\'s the password?".', [['Is there', 'predicate_verb'], ['wifi', 'subject'], ['here?', 'adverbial']]),
          s("What's the wifi password?", 'Qual a senha do wi-fi?', '"Password" = senha. Resposta costuma vir no recibo.', [["What's", 'predicate_verb'], ['the wifi password?', 'subject']]),
        ],
      },
      {
        id: 'lesson-travel-a2-09',
        chapter: 9,
        title: 'Na farmácia',
        description: 'Explicar sintomas e pedir remédio sem receita.',
        units: [
          s('I need something for a headache.', 'Preciso de algo para dor de cabeça.', '"Something for" + problema = remédio para. Outras dores: stomachache, toothache, backache.', [['I', 'subject'], ['need', 'predicate_verb'], ['something', 'direct_object'], ['for a headache.', 'adverbial']]),
          s('I have a sore throat.', 'Estou com dor de garganta.', 'Sintomas usam "have": I have a fever, I have a cough.', [['I', 'subject'], ['have', 'predicate_verb'], ['a sore throat.', 'direct_object']]),
          s("I've had a fever since yesterday.", 'Estou com febre desde ontem.', 'Present perfect + "since" para algo que começou no passado e continua.', [["I've had", 'predicate_verb'], ['a fever', 'direct_object'], ['since yesterday.', 'adverbial']]),
          s('Do I need a prescription?', 'Preciso de receita?', '"Prescription" = receita médica. Sem receita: "over the counter".', [['Do', 'predicate_verb'], ['I', 'subject'], ['need', 'predicate_verb'], ['a prescription?', 'direct_object']]),
          s('How often should I take it?', 'De quanto em quanto tempo devo tomar?', '"Take" é o verbo para tomar remédio. "How often" = com que frequência.', [['How often', 'adverbial'], ['should', 'predicate_verb'], ['I', 'subject'], ['take', 'predicate_verb'], ['it?', 'direct_object']]),
          s('Take two pills every six hours.', 'Tome dois comprimidos a cada seis horas.', 'Fala do farmacêutico. "Every" + número de horas = a cada.', [['Take', 'predicate_verb'], ['two pills', 'direct_object'], ['every six hours.', 'adverbial']]),
          s('Is it safe for children?', 'É seguro para crianças?', '"Safe" = seguro (sem perigo). "Children" é o plural irregular de "child".', [['Is', 'predicate_verb'], ['it', 'subject'], ['safe', 'predicate_adj'], ['for children?', 'adverbial']]),
          s("I'm allergic to penicillin.", 'Tenho alergia a penicilina.', 'Informação de segurança: diga antes de aceitar qualquer remédio.', [["I'm", 'subject'], ['allergic', 'predicate_adj'], ['to penicillin.', 'adverbial']]),
          s('Does it make you sleepy?', 'Dá sono?', '"Make you" + adjetivo = deixar você. "Drowsy" é o termo da bula.', [['Does', 'predicate_verb'], ['it', 'subject'], ['make', 'predicate_verb'], ['you', 'direct_object'], ['sleepy?', 'predicate_adj']]),
          s('Where can I find sunscreen?', 'Onde encontro protetor solar?', '"Where can I find" é útil em qualquer loja. "Aisle" = corredor.', [['Where', 'adverbial'], ['can', 'predicate_verb'], ['I', 'subject'], ['find', 'predicate_verb'], ['sunscreen?', 'direct_object']]),
        ],
      },
      {
        id: 'lesson-travel-a2-10',
        chapter: 10,
        title: 'Pedindo direções',
        description: 'Perguntar o caminho e entender a resposta.',
        units: [
          s('Excuse me, how do I get to the station?', 'Com licença, como chego à estação?', '"How do I get to" = como chego a. Começar com "Excuse me" é o jeito educado de abordar alguém.', [['Excuse me,', 'discourse_marker'], ['how', 'adverbial'], ['do', 'predicate_verb'], ['I', 'subject'], ['get', 'predicate_verb'], ['to the station?', 'adverbial']]),
          s('Is it far from here?', 'É longe daqui?', '"Far" = longe; "close" ou "near" = perto.', [['Is', 'predicate_verb'], ['it', 'subject'], ['far', 'predicate_adj'], ['from here?', 'adverbial']]),
          s("It's a ten minute walk.", 'São dez minutos a pé.', '"Ten minute" fica no singular porque funciona como adjetivo de "walk".', [["It's", 'predicate_verb'], ['a ten minute walk.', 'predicate_adj']]),
          s('Go straight and turn left.', 'Siga reto e vire à esquerda.', 'Imperativo para direções: go straight (siga reto), turn left/right (vire).', [['Go', 'predicate_verb'], ['straight', 'adverbial'], ['and', 'discourse_marker'], ['turn', 'predicate_verb'], ['left.', 'adverbial']]),
          s("It's on the corner.", 'Fica na esquina.', '"On the corner" = na esquina. "Across the street" = do outro lado da rua.', [["It's", 'predicate_verb'], ['on the corner.', 'adverbial']]),
          s('Take the second right.', 'Pegue a segunda à direita.', '"Take the first/second right" = entre na primeira/segunda rua à direita.', [['Take', 'predicate_verb'], ['the second right.', 'direct_object']]),
          s("You can't miss it.", 'Não tem como errar.', 'Frase comum no fim de uma explicação: o lugar é fácil de achar.', [['You', 'subject'], ["can't miss", 'predicate_verb'], ['it.', 'direct_object']]),
          s('Can you show me on the map?', 'Pode me mostrar no mapa?', '"Show me" = me mostrar. Útil quando a explicação fica confusa.', [['Can', 'predicate_verb'], ['you', 'subject'], ['show', 'predicate_verb'], ['me', 'indirect_object'], ['on the map?', 'adverbial']]),
          s("Sorry, I'm not from here.", 'Desculpe, não sou daqui.', 'Resposta que você pode ouvir (ou dar) quando a pessoa não sabe o caminho.', [['Sorry,', 'discourse_marker'], ["I'm", 'subject'], ['not from here.', 'adverbial']]),
          s("I think I'm lost.", 'Acho que estou perdido.', '"Lost" = perdido. "I think" suaviza e pede ajuda sem dramatizar.', [['I think', 'discourse_marker'], ["I'm", 'subject'], ['lost.', 'predicate_adj']]),
        ],
      },
      {
        id: 'lesson-travel-a2-11',
        chapter: 11,
        title: 'Emergências',
        description: 'Pedir ajuda, ligar para emergência e registrar ocorrência.',
        units: [
          s('Help! Call an ambulance!', 'Socorro! Chame uma ambulância!', 'Nos EUA o número de emergência é 911; na Europa, 112.', [['Help!', 'discourse_marker'], ['Call', 'predicate_verb'], ['an ambulance!', 'direct_object']]),
          s('Someone stole my wallet.', 'Alguém roubou minha carteira.', '"Stole" é o passado irregular de "steal" (roubar).', [['Someone', 'subject'], ['stole', 'predicate_verb'], ['my wallet.', 'direct_object']]),
          s('I need to report a theft.', 'Preciso registrar um roubo.', '"Report" = registrar ocorrência. "Theft" = furto, roubo.', [['I', 'subject'], ['need', 'predicate_verb'], ['to report a theft.', 'direct_object']]),
          s('Where is the nearest hospital?', 'Onde fica o hospital mais próximo?', '"The nearest" = o mais próximo (superlativo de "near").', [['Where', 'adverbial'], ['is', 'predicate_verb'], ['the nearest hospital?', 'subject']]),
          s('I lost my passport.', 'Perdi meu passaporte.', '"Lost" = passado de "lose" (perder). Procure a embaixada: "embassy".', [['I', 'subject'], ['lost', 'predicate_verb'], ['my passport.', 'direct_object']]),
          s('Can you call the police?', 'Pode chamar a polícia?', '"Police" é sempre plural no verbo: "the police are coming".', [['Can', 'predicate_verb'], ['you', 'subject'], ['call', 'predicate_verb'], ['the police?', 'direct_object']]),
          s("My friend isn't breathing.", 'Meu amigo não está respirando.', 'Presente contínuo para o que está acontecendo agora. Fale devagar e claro.', [['My friend', 'subject'], ["isn't breathing.", 'predicate_verb']]),
          s("I don't speak English well.", 'Eu não falo inglês bem.', 'Diga isso logo no começo: a pessoa vai falar mais devagar.', [['I', 'subject'], ["don't speak", 'predicate_verb'], ['English', 'direct_object'], ['well.', 'adverbial']]),
          s('Please speak slowly.', 'Por favor, fale devagar.', '"Slowly" = devagar (advérbio de "slow").', [['Please', 'discourse_marker'], ['speak', 'predicate_verb'], ['slowly.', 'adverbial']]),
          s('I need to contact my embassy.', 'Preciso falar com minha embaixada.', '"Contact" = entrar em contato. A embaixada ajuda com passaporte perdido.', [['I', 'subject'], ['need', 'predicate_verb'], ['to contact my embassy.', 'direct_object']]),
        ],
      },
    ],
  },
];
