// Lote viagem-3: Viagem sem Aperto, capítulos 12–15 (segurança e embarque, no
// avião, imigração e alfândega, bagagem extraviada e atrasos). Conteúdo original.

export const LEXICON = {
  lisbon: ['proper noun', '/ˈlɪzbən/', 'Lisboa'],
  may: ['modal verb', '/meɪ/', 'poder (permissão formal)'],
  step: ['verb', '/stɛp/', 'dar um passo, passar'],
  airline: ['noun', '/ˈɛrlaɪn/', 'companhia aérea'],
  arrive: ['verb', '/əˈraɪv/', 'chegar'],
  baggage: ['noun', '/ˈbæɡɪdʒ/', 'bagagem'],
  belt: ['noun', '/bɛlt/', 'esteira; cinto'],
  blanket: ['noun', '/ˈblæŋkɪt/', 'cobertor'],
  canceled: ['verb', '/ˈkænsəld/', 'cancelado'],
  changed: ['verb', '/tʃeɪndʒd/', 'mudou, mudado'],
  claim: ['noun', '/kleɪm/', 'retirada; reclamação'],
  declare: ['verb', '/dɪˈklɛr/', 'declarar'],
  delay: ['noun', '/dɪˈleɪ/', 'atraso'],
  deliver: ['verb', '/dɪˈlɪvər/', 'entregar'],
  descent: ['noun', '/dɪˈsɛnt/', 'descida'],
  fasten: ['verb', '/ˈfæsən/', 'afivelar, apertar'],
  final: ['adjective', '/ˈfaɪnəl/', 'final, último'],
  first: ['adjective', '/fɜːrst/', 'primeiro'],
  group: ['noun', '/ɡruːp/', 'grupo'],
  hotel: ['noun', '/hoʊˈtɛl/', 'hotel'],
  laptop: ['noun', '/ˈlæptɑːp/', 'notebook (computador)'],
  liquids: ['noun', '/ˈlɪkwɪdz/', 'líquidos'],
  meal: ['noun', '/miːl/', 'refeição'],
  nothing: ['pronoun', '/ˈnʌθɪŋ/', 'nada'],
  of: ['preposition', '/ʌv/', 'de'],
  office: ['noun', '/ˈɔːfɪs/', 'escritório, balcão'],
  our: ['determiner', '/aʊər/', 'nosso'],
  out: ['adverb', '/aʊt/', 'para fora'],
  pass: ['noun', '/pæs/', 'cartão, passe'],
  pasta: ['noun', '/ˈpɑːstə/', 'massa'],
  purpose: ['noun', '/ˈpɜːrpəs/', 'propósito, motivo'],
  put: ['verb', '/pʊt/', 'colocar'],
  rebook: ['verb', '/ˌriːˈbʊk/', 'remarcar'],
  return: ['adjective', '/rɪˈtɜːrn/', 'de volta'],
  seats: ['noun', '/siːts/', 'assentos'],
  shoes: ['noun', '/ʃuːz/', 'sapatos'],
  starting: ['verb', '/ˈstɑːrtɪŋ/', 'começando'],
  stay: ['verb', '/steɪ/', 'ficar'],
  staying: ['verb', '/ˈsteɪɪŋ/', 'ficando, hospedado'],
  suitcase: ['noun', '/ˈsuːtkeɪs/', 'mala'],
  switch: ['verb', '/swɪtʃ/', 'trocar'],
  tag: ['noun', '/tæɡ/', 'etiqueta'],
  through: ['adverb', '/θruː/', 'através'],
  vacation: ['noun', '/veɪˈkeɪʃən/', 'férias'],
  visit: ['noun', '/ˈvɪzɪt/', 'visita'],
  voucher: ['noun', '/ˈvaʊtʃər/', 'vale'],
  weeks: ['noun', '/wiːks/', 'semanas'],
};

const s = (text, pt, note, groups = []) => ({ kind: 'sentence', text, pt, note, groups });

export const COURSES = [
  {
    id: 'course-travel-a2',
    slug: 'travel-no-stress-a2',
    title: 'Viagem sem Aperto',
    level: 'A2',
    category: 'travel',
    track: 'viagem',
    trackOrder: 1,
    order: 2,
    short: 'Aeroporto, avião, imigração, hotel, transporte, restaurante, farmácia e emergências: as frases que você realmente precisa na viagem.',
    long: 'Situações de viagem com o que você diz e o que ouve do outro lado: despachar mala, passar pela segurança e pela imigração, falar com a tripulação, resolver bagagem extraviada, pedir no restaurante e no café, comprar remédio, pedir direções e lidar com emergências.',
    lessons: [
      {
        id: 'lesson-travel-a2-12',
        chapter: 12,
        title: 'Segurança e embarque',
        description: 'Raio-x, líquidos, portão e chamada de embarque.',
        units: [
          s('Please put your bag on the belt.', 'Por favor, coloque sua bolsa na esteira.', 'Fala do agente de segurança. "Belt" = esteira (também é cinto).', [['Please', 'discourse_marker'], ['put', 'predicate_verb'], ['your bag', 'direct_object'], ['on the belt.', 'adverbial']]),
          s('Take your laptop out of the bag.', 'Tire o notebook da bolsa.', '"Take out of" = tirar de dentro. O computador portátil é "laptop" (notebook é caderno).', [['Take', 'predicate_verb'], ['your laptop', 'direct_object'], ['out of the bag.', 'adverbial']]),
          s('Do I need to take off my shoes?', 'Preciso tirar os sapatos?', '"Take off" = tirar (roupa, sapato). O contrário é "put on".', [['Do', 'predicate_verb'], ['I', 'subject'], ['need', 'predicate_verb'], ['to take off my shoes?', 'direct_object']]),
          s('Any liquids in your bag?', 'Algum líquido na bolsa?', 'Pergunta curta do agente (forma reduzida de "Do you have any liquids…?").', [['Any liquids', 'direct_object'], ['in your bag?', 'adverbial']]),
          s('Step through, please.', 'Passe, por favor.', 'Ordem para atravessar o detector de metais. "Step" = dar um passo.', [['Step', 'predicate_verb'], ['through,', 'adverbial'], ['please.', 'discourse_marker']]),
          s('The gate has changed.', 'O portão mudou.', 'Present perfect para uma mudança com efeito agora. Confira o painel: "departures board".', [['The gate', 'subject'], ['has changed.', 'predicate_verb']]),
          s('We are now boarding group two.', 'Estamos embarcando agora o grupo dois.', 'Aviso do portão. Seu grupo está no cartão de embarque.', [['We', 'subject'], ['are now boarding', 'predicate_verb'], ['group two.', 'direct_object']]),
          s('May I see your boarding pass?', 'Posso ver seu cartão de embarque?', '"May I" é pedido de permissão bem formal, típico de funcionário.', [['May', 'predicate_verb'], ['I', 'subject'], ['see', 'predicate_verb'], ['your boarding pass?', 'direct_object']]),
          s('This is the final call for flight two ten.', 'Esta é a última chamada para o voo duzentos e dez.', '"Final call" = última chamada. Números de voo costumam ser lidos em grupos: "two ten".', [['This', 'subject'], ['is', 'predicate_verb'], ['the final call', 'predicate_adj'], ['for flight two ten.', 'adverbial']]),
          s('Is this the line for Lisbon?', 'Esta é a fila para Lisboa?', '"Line" (EUA) ou "queue" (Reino Unido) = fila.', [['Is', 'predicate_verb'], ['this', 'subject'], ['the line', 'predicate_adj'], ['for Lisbon?', 'adverbial']]),
        ],
      },
      {
        id: 'lesson-travel-a2-13',
        chapter: 13,
        title: 'No avião',
        description: 'Assento, bagagem de mão, comida e pedidos à tripulação.',
        units: [
          s("I think you're in my seat.", 'Acho que você está no meu assento.', '"I think" deixa a frase educada; mostre o cartão de embarque.', [['I think', 'discourse_marker'], ["you're", 'subject'], ['in my seat.', 'adverbial']]),
          s('Can you help me with my bag?', 'Pode me ajudar com a minha mala?', '"Help me with" + objeto = ajudar com. Útil para colocar a mala no compartimento.', [['Can', 'predicate_verb'], ['you', 'subject'], ['help', 'predicate_verb'], ['me', 'direct_object'], ['with my bag?', 'adverbial']]),
          s('Please fasten your seat belt.', 'Por favor, aperte o cinto de segurança.', '"Fasten" = afivelar; o "t" é mudo: /ˈfæsən/.', [['Please', 'discourse_marker'], ['fasten', 'predicate_verb'], ['your seat belt.', 'direct_object']]),
          s('Chicken or pasta?', 'Frango ou massa?', 'Pergunta típica do serviço de bordo. Responda só com a opção: "Pasta, please".', [['Chicken', 'direct_object'], ['or', 'discourse_marker'], ['pasta?', 'direct_object']]),
          s('Could I have a blanket?', 'Poderia me dar um cobertor?', '"Could I have" é o pedido educado padrão. "Pillow" = travesseiro.', [['Could', 'predicate_verb'], ['I', 'subject'], ['have', 'predicate_verb'], ['a blanket?', 'direct_object']]),
          s('May I switch seats?', 'Posso trocar de assento?', '"Switch seats" = trocar de lugar. "Seats" fica no plural.', [['May', 'predicate_verb'], ['I', 'subject'], ['switch', 'predicate_verb'], ['seats?', 'direct_object']]),
          s('Excuse me, can I get out?', 'Com licença, posso passar?', 'Para sair do assento da janela. "Get out" = sair.', [['Excuse me,', 'discourse_marker'], ['can', 'predicate_verb'], ['I', 'subject'], ['get out?', 'predicate_verb']]),
          s('How long is the flight?', 'Quanto tempo dura o voo?', '"How long" pergunta duração. Resposta: "About nine hours".', [['How long', 'adverbial'], ['is', 'predicate_verb'], ['the flight?', 'subject']]),
          s('We are starting our descent.', 'Estamos iniciando a descida.', 'Aviso do piloto. "Descent" = descida; "landing" = pouso.', [['We', 'subject'], ['are starting', 'predicate_verb'], ['our descent.', 'direct_object']]),
          s('Please keep your seat belt on.', 'Por favor, mantenha o cinto afivelado.', '"Keep on" = manter (ligado, colocado). O objeto fica no meio: "keep it on".', [['Please', 'discourse_marker'], ['keep', 'predicate_verb'], ['your seat belt', 'direct_object'], ['on.', 'adverbial']]),
        ],
      },
      {
        id: 'lesson-travel-a2-14',
        chapter: 14,
        title: 'Imigração e alfândega',
        description: 'Motivo da viagem, hospedagem e declarar itens.',
        units: [
          s('What is the purpose of your visit?', 'Qual o motivo da sua visita?', 'Pergunta clássica do oficial. Respostas: tourism, business, visiting family.', [['What', 'predicate_adj'], ['is', 'predicate_verb'], ['the purpose of your visit?', 'subject']]),
          s("I'm here on vacation.", 'Estou aqui de férias.', '"On vacation" (EUA) ou "on holiday" (Reino Unido) = de férias.', [["I'm", 'subject'], ['here', 'adverbial'], ['on vacation.', 'adverbial']]),
          s('How long will you stay?', 'Quanto tempo vai ficar?', 'Futuro com "will". Responda com o período: "Two weeks".', [['How long', 'adverbial'], ['will', 'predicate_verb'], ['you', 'subject'], ['stay?', 'predicate_verb']]),
          s("I'm staying for two weeks.", 'Vou ficar duas semanas.', 'Presente contínuo para plano já decidido. "For" + período.', [["I'm staying", 'predicate_verb'], ['for two weeks.', 'adverbial']]),
          s('Where are you staying?', 'Onde você vai ficar hospedado?', 'Tenha o endereço do hotel à mão.', [['Where', 'adverbial'], ['are', 'predicate_verb'], ['you', 'subject'], ['staying?', 'predicate_verb']]),
          s("I'm staying at a hotel downtown.", 'Vou ficar num hotel no centro.', '"Downtown" (EUA) = centro da cidade; no Reino Unido, "city centre".', [["I'm staying", 'predicate_verb'], ['at a hotel', 'adverbial'], ['downtown.', 'adverbial']]),
          s('Do you have anything to declare?', 'Tem algo a declarar?', 'Pergunta da alfândega. "Declare" = declarar mercadorias.', [['Do', 'predicate_verb'], ['you', 'subject'], ['have', 'predicate_verb'], ['anything to declare?', 'direct_object']]),
          s('No, nothing to declare.', 'Não, nada a declarar.', '"Nothing" já é negativo: não use "not" junto.', [['No,', 'discourse_marker'], ['nothing', 'direct_object'], ['to declare.', 'predicate_verb']]),
          s('Is this your first time here?', 'É a sua primeira vez aqui?', '"First time" = primeira vez. Pergunta simpática, às vezes para puxar conversa.', [['Is', 'predicate_verb'], ['this', 'subject'], ['your first time', 'predicate_adj'], ['here?', 'adverbial']]),
          s('Can I see your return ticket?', 'Posso ver sua passagem de volta?', '"Return ticket" = passagem de volta; "round trip" = ida e volta (EUA).', [['Can', 'predicate_verb'], ['I', 'subject'], ['see', 'predicate_verb'], ['your return ticket?', 'direct_object']]),
        ],
      },
      {
        id: 'lesson-travel-a2-15',
        chapter: 15,
        title: 'Bagagem extraviada e atrasos',
        description: 'Registrar mala perdida, conexão perdida e remarcação.',
        units: [
          s("My suitcase didn't arrive.", 'Minha mala não chegou.', 'Passado negativo: "didn\'t" + verbo base (arrive, não arrived).', [['My suitcase', 'subject'], ["didn't arrive.", 'predicate_verb']]),
          s('Where is the lost baggage office?', 'Onde fica o balcão de bagagem extraviada?', '"Lost baggage" ou "baggage services" = setor de bagagem perdida.', [['Where', 'adverbial'], ['is', 'predicate_verb'], ['the lost baggage office?', 'subject']]),
          s("It's a black suitcase with a red tag.", 'É uma mala preta com uma etiqueta vermelha.', 'Descreva cor, tamanho e marca. "Tag" = etiqueta.', [["It's", 'predicate_verb'], ['a black suitcase', 'predicate_adj'], ['with a red tag.', 'adverbial']]),
          s('Here is my baggage claim tag.', 'Aqui está o comprovante da minha bagagem.', 'O "baggage claim tag" é o adesivo que você recebeu no check-in.', [['Here', 'adverbial'], ['is', 'predicate_verb'], ['my baggage claim tag.', 'subject']]),
          s('Can you deliver it to my hotel?', 'Podem entregar no meu hotel?', '"Deliver" = entregar. Pergunte sempre: a companhia costuma levar sem custo.', [['Can', 'predicate_verb'], ['you', 'subject'], ['deliver', 'predicate_verb'], ['it', 'direct_object'], ['to my hotel?', 'adverbial']]),
          s('My flight was canceled.', 'Meu voo foi cancelado.', 'Voz passiva no passado: "was" + particípio. Britânico: "cancelled".', [['My flight', 'subject'], ['was canceled.', 'predicate_verb']]),
          s('Can you rebook me on the next flight?', 'Pode me remarcar no próximo voo?', '"Rebook" = remarcar. "The next flight" = o próximo voo.', [['Can', 'predicate_verb'], ['you', 'subject'], ['rebook', 'predicate_verb'], ['me', 'direct_object'], ['on the next flight?', 'adverbial']]),
          s('Will the airline pay for the hotel?', 'A companhia aérea paga o hotel?', '"Airline" = companhia aérea. Pergunte por "vouchers" de hotel e comida.', [['Will', 'predicate_verb'], ['the airline', 'subject'], ['pay', 'predicate_verb'], ['for the hotel?', 'adverbial']]),
          s('How long is the delay?', 'Qual é o tamanho do atraso?', '"Delay" = atraso (substantivo). "Delayed" = atrasado.', [['How long', 'adverbial'], ['is', 'predicate_verb'], ['the delay?', 'subject']]),
          s('Can I get a meal voucher?', 'Posso receber um vale-refeição?', '"Voucher" = vale. Muitas companhias dão em atrasos longos.', [['Can', 'predicate_verb'], ['I', 'subject'], ['get', 'predicate_verb'], ['a meal voucher?', 'direct_object']]),
        ],
      },
    ],
  },
];
