// Lote viagem-1: restaurante completo em Viagem sem Aperto (capítulos 4–7).
// Frases que o aluno diz e que ouve do garçom, cada uma com nota de uso.
// Conteúdo original.

export const LEXICON = {
  anything: ['pronoun', '/ˈɛniθɪŋ/', 'algo, alguma coisa'],
  excuse: ['verb', '/ɪkˈskjuːz/', 'desculpar (excuse me = com licença)'],
  medium: ['adjective', '/ˈmiːdiəm/', 'médio; ao ponto'],
  separate: ['adjective', '/ˈsɛpərət/', 'separado'],
  "we've": ['pronoun', '/wiːv/', 'nós temos (we have)'],
  would: ['modal verb', '/wʊd/', 'gostaria; condicional'],
  all: ['determiner', '/ɔːl/', 'tudo, todos'],
  allergic: ['adjective', '/əˈlɜːrdʒɪk/', 'alérgico'],
  away: ['adverb', '/əˈweɪ/', 'embora; (right away) já'],
  bill: ['noun', '/bɪl/', 'conta'],
  booked: ['adjective', '/bʊkt/', 'reservado, lotado'],
  bring: ['verb', '/brɪŋ/', 'trazer'],
  card: ['noun', '/kɑːrd/', 'cartão'],
  cards: ['noun', '/kɑːrdz/', 'cartões'],
  chair: ['noun', '/tʃɛr/', 'cadeira'],
  checks: ['noun', '/tʃɛks/', 'contas (EUA)'],
  cheese: ['noun', '/tʃiːz/', 'queijo'],
  chicken: ['noun', '/ˈtʃɪkən/', 'frango'],
  credit: ['noun', '/ˈkrɛdɪt/', 'crédito'],
  delicious: ['adjective', '/dɪˈlɪʃəs/', 'delicioso'],
  drink: ['verb', '/drɪŋk/', 'beber'],
  eat: ['verb', '/iːt/', 'comer'],
  food: ['noun', '/fuːd/', 'comida'],
  fries: ['noun', '/fraɪz/', 'batata frita'],
  fully: ['adverb', '/ˈfʊli/', 'totalmente'],
  gluten: ['noun', '/ˈɡluːtən/', 'glúten'],
  high: ['adjective', '/haɪ/', 'alto'],
  long: ['adjective', '/lɔːŋ/', 'longo, muito (tempo)'],
  menu: ['noun', '/ˈmɛnjuː/', 'cardápio'],
  more: ['determiner', '/mɔːr/', 'mais'],
  need: ['verb', '/niːd/', 'precisar'],
  nuts: ['noun', '/nʌts/', 'castanhas, nozes'],
  option: ['noun', '/ˈɑːpʃən/', 'opção'],
  order: ['verb', '/ˈɔːrdər/', 'pedir (comida)'],
  ordered: ['verb', '/ˈɔːrdərd/', 'pediu, pedido'],
  outside: ['adverb', '/ˌaʊtˈsaɪd/', 'lá fora'],
  pay: ['verb', '/peɪ/', 'pagar'],
  peanuts: ['noun', '/ˈpiːnʌts/', 'amendoins'],
  person: ['noun', '/ˈpɜːrsən/', 'pessoa'],
  rare: ['adjective', '/rɛr/', 'mal passado; raro'],
  ready: ['adjective', '/ˈrɛdi/', 'pronto'],
  recommend: ['verb', '/ˌrɛkəˈmɛnd/', 'recomendar'],
  salad: ['noun', '/ˈsæləd/', 'salada'],
  service: ['noun', '/ˈsɜːrvɪs/', 'serviço'],
  split: ['verb', '/splɪt/', 'dividir'],
  steak: ['noun', '/steɪk/', 'bife'],
  still: ['adverb', '/stɪl/', 'ainda'],
  table: ['noun', '/ˈteɪbəl/', 'mesa'],
  thank: ['verb', '/θæŋk/', 'agradecer'],
  tip: ['noun', '/tɪp/', 'gorjeta'],
  vegan: ['adjective', '/ˈviːɡən/', 'vegano'],
  vegetarian: ['noun', '/ˌvɛdʒəˈtɛriən/', 'vegetariano'],
  wait: ['noun', '/weɪt/', 'espera; esperar'],
  waiting: ['verb', '/ˈweɪtɪŋ/', 'esperando'],
  warm: ['verb', '/wɔːrm/', 'esquentar; morno'],
  water: ['noun', '/ˈwɔːtər/', 'água'],
  without: ['preposition', '/wɪˈðaʊt/', 'sem'],
};

const s = (text, pt, note, groups = []) => ({ kind: 'sentence', text, pt, note, groups });

export const COURSES = [
  {
    id: 'course-travel-a2',
    slug: 'travel-no-stress-a2',
    title: 'Viagem sem Aperto',
    level: 'A2',
    category: 'travel',
    track: 'viagem',
    trackOrder: 1,
    order: 2,
    short: 'Aeroporto, hotel, transporte e restaurante: as frases que você realmente precisa na viagem.',
    long: 'Situações de viagem com o que você diz e o que ouve do outro lado: despachar mala, resolver problema no quarto, pegar metrô, reservar mesa, pedir, avisar de alergia e pagar a conta.',
    lessons: [
      {
        id: 'lesson-travel-a2-04',
        chapter: 4,
        title: 'Restaurante: reserva e mesa',
        description: 'Reservar, chegar, esperar e escolher onde sentar.',
        units: [
          s("I'd like to make a reservation for tonight.", 'Eu gostaria de fazer uma reserva para hoje à noite.', '"Make a reservation" = fazer reserva. "I\'d like to" é o jeito educado de pedir.', [["I'd like", 'predicate_verb'], ['to make a reservation', 'direct_object'], ['for tonight.', 'adverbial']]),
          s('A table for two, please.', 'Uma mesa para dois, por favor.', 'Forma curta e natural ao chegar sem reserva. "For" + número de pessoas.', [['A table', 'direct_object'], ['for two,', 'adverbial'], ['please.', 'discourse_marker']]),
          s('Do you have a reservation?', 'Você tem reserva?', 'Você vai ouvir isso na entrada. Responda "Yes, under Silva" (em nome de Silva) ou "No, we don\'t".', [['Do', 'predicate_verb'], ['you', 'subject'], ['have', 'predicate_verb'], ['a reservation?', 'direct_object']]),
          s('The reservation is under Silva.', 'A reserva está no nome de Silva.', '"Under" + nome = em nome de. Não se diz "in the name of" no dia a dia.', [['The reservation', 'subject'], ['is', 'predicate_verb'], ['under Silva.', 'adverbial']]),
          s("How long is the wait?", 'Quanto tempo de espera?', '"Wait" aqui é substantivo: a espera. Resposta típica: "About twenty minutes".', [['How long', 'adverbial'], ['is', 'predicate_verb'], ['the wait?', 'subject']]),
          s("It's about a twenty minute wait.", 'A espera é de uns vinte minutos.', 'Fala do recepcionista. "About" = mais ou menos. "Twenty minute" fica no singular porque funciona como adjetivo.', [["It's", 'predicate_verb'], ['about a twenty minute wait.', 'predicate_adj']]),
          s('Can we sit outside?', 'Podemos sentar lá fora?', '"Outside" = área externa; "inside" = dentro. "Can we" pede permissão.', [['Can', 'predicate_verb'], ['we', 'subject'], ['sit', 'predicate_verb'], ['outside?', 'adverbial']]),
          s('Is this table free?', 'Esta mesa está livre?', '"Free" aqui é "desocupada", não "grátis". Também se diz "Is this table taken?".', [['Is', 'predicate_verb'], ['this table', 'subject'], ['free?', 'predicate_adj']]),
          s('Right this way, please.', 'Por aqui, por favor.', 'O garçom diz isso ao levar você até a mesa. "Right" só reforça: "bem por aqui".', [['Right this way,', 'adverbial'], ['please.', 'discourse_marker']]),
          s("We're still waiting for one more person.", 'Ainda estamos esperando mais uma pessoa.', '"Still" = ainda. Presente contínuo (are waiting) para algo acontecendo agora.', [["We're", 'subject'], ['still', 'adverbial'], ['waiting', 'predicate_verb'], ['for one more person.', 'direct_object']]),
          s('Could we have a high chair?', 'Poderia nos trazer uma cadeirinha de bebê?', '"High chair" = cadeira alta para bebê. "Could we have" é mais educado que "can we have".', [['Could', 'predicate_verb'], ['we', 'subject'], ['have', 'predicate_verb'], ['a high chair?', 'direct_object']]),
          s("Sorry, we're fully booked tonight.", 'Desculpe, estamos lotados hoje à noite.', '"Fully booked" = sem mesas/vagas para reserva. Vale também para hotel.', [['Sorry,', 'discourse_marker'], ["we're", 'subject'], ['fully booked', 'predicate_adj'], ['tonight.', 'adverbial']]),
        ],
      },
      {
        id: 'lesson-travel-a2-05',
        chapter: 5,
        title: 'Restaurante: fazendo o pedido',
        description: 'Cardápio, perguntas ao garçom, pedido e ponto da carne.',
        units: [
          s('Can I see the menu, please?', 'Posso ver o cardápio, por favor?', '"Menu" = cardápio. Em bares também se ouve "drinks menu" para a carta de bebidas.', [['Can', 'predicate_verb'], ['I', 'subject'], ['see', 'predicate_verb'], ['the menu,', 'direct_object'], ['please?', 'discourse_marker']]),
          s('Are you ready to order?', 'Estão prontos para pedir?', 'Pergunta do garçom. Se não estiver: "We need a few more minutes".', [['Are', 'predicate_verb'], ['you', 'subject'], ['ready to order?', 'predicate_adj']]),
          s('We need a few more minutes.', 'Precisamos de mais alguns minutos.', '"A few" = alguns (contável). Resposta educada para ganhar tempo.', [['We', 'subject'], ['need', 'predicate_verb'], ['a few more minutes.', 'direct_object']]),
          s('What do you recommend?', 'O que você recomenda?', 'Ótima pergunta para descobrir o prato da casa. "Recommend" tem um só "c" e dois "m".', [['What', 'direct_object'], ['do', 'predicate_verb'], ['you', 'subject'], ['recommend?', 'predicate_verb']]),
          s("I'll have the chicken, please.", 'Vou querer o frango, por favor.', '"I\'ll have" = vou querer. É o jeito mais comum de pedir; "I want" soa rude.', [["I'll have", 'predicate_verb'], ['the chicken,', 'direct_object'], ['please.', 'discourse_marker']]),
          s('How would you like your steak?', 'Como você quer o ponto da carne?', 'Fala do garçom. Respostas: "rare" (mal passado), "medium" (ao ponto), "well done" (bem passado).', [['How', 'adverbial'], ['would', 'predicate_verb'], ['you', 'subject'], ['like', 'predicate_verb'], ['your steak?', 'direct_object']]),
          s('Medium rare, please.', 'Ao ponto para mal, por favor.', '"Medium rare" = rosado por dentro. A escala: rare, medium rare, medium, medium well, well done.', [['Medium rare,', 'predicate_adj'], ['please.', 'discourse_marker']]),
          s('Does it come with fries?', 'Vem com batata frita?', '"Come with" = acompanha. "Fries" é o termo americano; no Reino Unido, "chips".', [['Does', 'predicate_verb'], ['it', 'subject'], ['come with', 'predicate_verb'], ['fries?', 'direct_object']]),
          s('Can I get a salad instead?', 'Posso trocar por uma salada?', '"Instead" = em vez disso, no lugar. "Can I get" é pedido informal comum nos EUA.', [['Can', 'predicate_verb'], ['I', 'subject'], ['get', 'predicate_verb'], ['a salad', 'direct_object'], ['instead?', 'adverbial']]),
          s('Anything to drink?', 'Algo para beber?', 'Pergunta curta do garçom (forma reduzida de "Would you like anything to drink?").', [['Anything', 'direct_object'], ['to drink?', 'predicate_verb']]),
          s('Just water, please.', 'Só água, por favor.', 'Em muitos lugares a água da torneira é grátis: "tap water". Garrafa: "bottled water".', [['Just', 'adverbial'], ['water,', 'direct_object'], ['please.', 'discourse_marker']]),
          s("That's all for now, thanks.", 'É só isso por enquanto, obrigado.', '"For now" = por enquanto: deixa claro que talvez peça mais depois.', [["That's", 'predicate_verb'], ['all', 'predicate_adj'], ['for now,', 'adverbial'], ['thanks.', 'discourse_marker']]),
        ],
      },
      {
        id: 'lesson-travel-a2-06',
        chapter: 6,
        title: 'Restaurante: alergias e problemas',
        description: 'Restrições alimentares, pedidos especiais e reclamar com educação.',
        units: [
          s("I'm allergic to peanuts.", 'Eu tenho alergia a amendoim.', '"Allergic to" + alimento. Diga isso antes de pedir; é informação de segurança.', [["I'm", 'subject'], ['allergic', 'predicate_adj'], ['to peanuts.', 'adverbial']]),
          s('Does this have any nuts in it?', 'Isso tem alguma castanha?', '"Nuts" cobre castanhas, nozes e amêndoas. "Any" em perguntas = algum.', [['Does', 'predicate_verb'], ['this', 'subject'], ['have', 'predicate_verb'], ['any nuts', 'direct_object'], ['in it?', 'adverbial']]),
          s("I'm a vegetarian.", 'Eu sou vegetariano.', 'Profissões e grupos usam "a/an": "I\'m a vegetarian", "I\'m a vegan".', [["I'm", 'subject'], ['a vegetarian.', 'predicate_adj']]),
          s('Is there a vegan option?', 'Tem opção vegana?', '"Is there" = existe, tem. Vegan = sem nenhum produto animal.', [['Is there', 'predicate_verb'], ['a vegan option?', 'subject']]),
          s('Can you make it without cheese?', 'Dá para fazer sem queijo?', '"Without" = sem. "Make it" se refere ao prato já mencionado.', [['Can', 'predicate_verb'], ['you', 'subject'], ['make', 'predicate_verb'], ['it', 'direct_object'], ['without cheese?', 'adverbial']]),
          s("I can't eat gluten.", 'Eu não posso comer glúten.', '"Can\'t" = não posso. Mais claro para restrição médica do que "I don\'t eat".', [['I', 'subject'], ["can't eat", 'predicate_verb'], ['gluten.', 'direct_object']]),
          s("Excuse me, this isn't what I ordered.", 'Com licença, isso não é o que eu pedi.', '"Excuse me" chama a atenção com educação. "Ordered" = passado de "order" (pedir comida).', [['Excuse me,', 'discourse_marker'], ['this', 'subject'], ["isn't", 'predicate_verb'], ['what I ordered.', 'predicate_adj']]),
          s('My food is cold.', 'Minha comida está fria.', 'Reclamação direta e educada; complete com "Could you warm it up?" (pode esquentar?).', [['My food', 'subject'], ['is', 'predicate_verb'], ['cold.', 'predicate_adj']]),
          s('Could you warm it up, please?', 'Você poderia esquentar, por favor?', '"Warm up" é phrasal verb: esquentar. O objeto "it" vai no meio: "warm it up".', [['Could', 'predicate_verb'], ['you', 'subject'], ['warm', 'predicate_verb'], ['it', 'direct_object'], ['up,', 'predicate_verb'], ['please?', 'discourse_marker']]),
          s("We've been waiting for a long time.", 'Estamos esperando faz muito tempo.', 'Present perfect contínuo: começou no passado e continua agora. Tom de reclamação educada.', [["We've been waiting", 'predicate_verb'], ['for a long time.', 'adverbial']]),
          s("I'm sorry about that.", 'Peço desculpas por isso.', 'Resposta típica do garçom. "Sorry about" + problema.', [["I'm", 'subject'], ['sorry', 'predicate_adj'], ['about that.', 'adverbial']]),
          s("I'll bring you a new one right away.", 'Vou trazer outro para você agora mesmo.', 'Fala do garçom. "Right away" = imediatamente. "A new one" evita repetir o nome do prato.', [["I'll bring", 'predicate_verb'], ['you', 'indirect_object'], ['a new one', 'direct_object'], ['right away.', 'adverbial']]),
        ],
      },
      {
        id: 'lesson-travel-a2-07',
        chapter: 7,
        title: 'Restaurante: conta e gorjeta',
        description: 'Pedir a conta, dividir, pagar com cartão e deixar gorjeta.',
        units: [
          s('Can we have the check, please?', 'Pode trazer a conta, por favor?', '"Check" (EUA) ou "bill" (Reino Unido) = conta. Nunca "account".', [['Can', 'predicate_verb'], ['we', 'subject'], ['have', 'predicate_verb'], ['the check,', 'direct_object'], ['please?', 'discourse_marker']]),
          s('Is service included?', 'O serviço está incluído?', 'Em muitos países a gorjeta não vem na conta. "Included" = incluído.', [['Is', 'predicate_verb'], ['service', 'subject'], ['included?', 'predicate_adj']]),
          s('Can we split the bill?', 'Podemos dividir a conta?', '"Split" = dividir. "Split it evenly" = dividir igualmente.', [['Can', 'predicate_verb'], ['we', 'subject'], ['split', 'predicate_verb'], ['the bill?', 'direct_object']]),
          s('Separate checks, please.', 'Contas separadas, por favor.', 'Cada pessoa paga a sua parte. Diga isso antes de a conta chegar.', [['Separate checks,', 'direct_object'], ['please.', 'discourse_marker']]),
          s('Do you take credit cards?', 'Vocês aceitam cartão de crédito?', '"Take" = aceitar (forma de pagamento). "Cash only" = só dinheiro.', [['Do', 'predicate_verb'], ['you', 'subject'], ['take', 'predicate_verb'], ['credit cards?', 'direct_object']]),
          s("I'll pay by card.", 'Vou pagar no cartão.', '"By card" / "in cash" = no cartão / em dinheiro. Repare: by card, mas in cash.', [["I'll pay", 'predicate_verb'], ['by card.', 'adverbial']]),
          s('Would you like to add a tip?', 'Gostaria de adicionar gorjeta?', 'Aparece na maquininha ou é dito pelo garçom. "Tip" = gorjeta.', [['Would', 'predicate_verb'], ['you', 'subject'], ['like', 'predicate_verb'], ['to add a tip?', 'direct_object']]),
          s('Keep the change.', 'Pode ficar com o troco.', 'Forma simples de deixar gorjeta pagando em dinheiro. "Change" = troco.', [['Keep', 'predicate_verb'], ['the change.', 'direct_object']]),
          s('I think there is a mistake on the bill.', 'Acho que tem um erro na conta.', '"I think" suaviza a reclamação. "On the bill" = na conta (preposição "on").', [['I think', 'discourse_marker'], ['there is', 'predicate_verb'], ['a mistake', 'subject'], ['on the bill.', 'adverbial']]),
          s("We didn't order this.", 'Nós não pedimos isso.', 'Passado negativo: "didn\'t" + verbo na forma base (order, não ordered).', [['We', 'subject'], ["didn't order", 'predicate_verb'], ['this.', 'direct_object']]),
          s('Can I get this to go?', 'Pode embalar para viagem?', '"To go" (EUA) = para levar; no Reino Unido, "to take away". Serve para sobras também.', [['Can', 'predicate_verb'], ['I', 'subject'], ['get', 'predicate_verb'], ['this', 'direct_object'], ['to go?', 'adverbial']]),
          s('Everything was delicious, thank you.', 'Estava tudo delicioso, obrigado.', 'Elogio ao sair. "Everything" pede verbo no singular: "everything was".', [['Everything', 'subject'], ['was', 'predicate_verb'], ['delicious,', 'predicate_adj'], ['thank you.', 'discourse_marker']]),
        ],
      },
    ],
  },
];
