-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-spoken-reductions-a2', 'spoken-reductions-a2', 'Inglês Falado: Reduções', 'Piloto: as reduções que as séries usam o tempo todo e quase ninguém ensina (c''mon, gotcha, shoulda, outta).', 'Curso piloto sobre a fala real: formas encurtadas como "c''mon", "gotcha", "shoulda", "outta" e "tryna". Cada frase mostra a forma completa, o registro (informal ou gíria) e a armadilha. Você ouve, digita palavra por palavra e vê tradução, IPA e explicação. É um piloto de um capítulo: a continuação depende do áudio e do seu uso.', 'A2', 'street-slang', 19, 'fluencia', 4, false, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-spoken-reductions-a2-01', 'course-spoken-reductions-a2', 1, 'Reduções além do gonna', 'Gotcha, c''mon, shoulda, outta e outras formas que você ouve em séries.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-spoken-reductions-a2-01-01', 'lesson-spoken-reductions-a2-01', 1, 'sentence', 'C''mon, we''re gonna miss the bus.', 'Anda, a gente vai perder o ônibus.', '/kəˈmɑːn wɪr ˈɡʌnə mɪs ðə bʌs/', 'Informal. "C''mon" = "come on": anda, vamos (com pressa ou incentivo). Aparece muito antes de uma ordem.', '[{"start":0,"end":6,"role":"discourse_marker","surface":"C''mon,"},{"start":7,"end":12,"role":"subject","surface":"we''re"},{"start":13,"end":23,"role":"predicate_verb","surface":"gonna miss"},{"start":24,"end":32,"role":"direct_object","surface":"the bus."}]'::jsonb, '[{"surface":"C''mon","pos":"verb","ipa":"/kəˈmɑːn/","gloss":"vamos, anda (come on)"},{"surface":"we''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"miss","pos":"verb","ipa":"/mɪs/","gloss":"errar, perder; sentir falta"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-02', 'lesson-spoken-reductions-a2-01', 2, 'sentence', 'Gotcha, I''ll call you later.', 'Entendi, ligo para você mais tarde.', '/ˈɡɑːtʃə aɪl kɔːl juː ˈleɪtər/', 'Informal. "Gotcha" = "got you": entendi, pode deixar. Não confunda com "gotcha" como "pegadinha".', '[{"start":0,"end":7,"role":"discourse_marker","surface":"Gotcha,"},{"start":8,"end":12,"role":"subject","surface":"I''ll"},{"start":13,"end":21,"role":"predicate_verb","surface":"call you"},{"start":22,"end":28,"role":"adverbial","surface":"later."}]'::jsonb, '[{"surface":"Gotcha","pos":"verb","ipa":"/ˈɡɑːtʃə/","gloss":"entendi, pode deixar (got you)"},{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"call","pos":"verb","ipa":"/kɔːl/","gloss":"ligar, chamar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-03', 'lesson-spoken-reductions-a2-01', 3, 'sentence', 'I shoulda called you.', 'Eu devia ter ligado para você.', '/aɪ ˈʃʊdə kɔːld juː/', 'Informal. "Shoulda" = "should have" (devia ter). Na escrita use "should have"; nunca "should of".', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":16,"role":"predicate_verb","surface":"shoulda called"},{"start":17,"end":21,"role":"direct_object","surface":"you."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"shoulda","pos":"verb","ipa":"/ˈʃʊdə/","gloss":"devia ter (should have)"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-04', 'lesson-spoken-reductions-a2-01', 4, 'sentence', 'You coulda told me!', 'Você podia ter me contado!', '/juː ˈkʊdə toʊld miː/', 'Informal. "Coulda" = "could have" (podia ter). Costuma soar como reclamação, não como pedido.', '[{"start":0,"end":3,"role":"subject","surface":"You"},{"start":4,"end":15,"role":"predicate_verb","surface":"coulda told"},{"start":16,"end":19,"role":"direct_object","surface":"me!"}]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"coulda","pos":"verb","ipa":"/ˈkʊdə/","gloss":"podia ter (could have)"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-05', 'lesson-spoken-reductions-a2-01', 5, 'sentence', 'We''re outta milk.', 'Acabou o leite.', '/wɪr ˈaʊtə mɪlk/', 'Informal. "Outta" = "out of". "Outta milk" = sem leite. Também em "Get outta here!" (Sai daqui! / Não acredito!).', '[{"start":0,"end":5,"role":"subject","surface":"We''re"},{"start":6,"end":11,"role":"predicate_verb","surface":"outta"},{"start":12,"end":17,"role":"direct_object","surface":"milk."}]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"outta","pos":"preposition","ipa":"/ˈaʊtə/","gloss":"sem, fora de (out of)"},{"surface":"milk","pos":"noun","ipa":"/mɪlk/","gloss":"leite"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-06', 'lesson-spoken-reductions-a2-01', 6, 'sentence', 'Whaddya want for dinner?', 'O que você quer para o jantar?', '/ˈwʌdjə wɑːnt fɔːr ˈdɪnər/', 'Informal. "Whaddya" = "what do you". Na fala o "do" some e o som junta "what" com "you".', '[{"start":0,"end":7,"role":"subject","surface":"Whaddya"},{"start":8,"end":12,"role":"predicate_verb","surface":"want"},{"start":13,"end":24,"role":"adverbial","surface":"for dinner?"}]'::jsonb, '[{"surface":"Whaddya","pos":"pronoun","ipa":"/ˈwʌdjə/","gloss":"o que você (what do you)"},{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"dinner","pos":"noun","ipa":"/ˈdɪnər/","gloss":"jantar"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-07', 'lesson-spoken-reductions-a2-01', 7, 'sentence', 'I''m tryna sleep.', 'Estou tentando dormir.', '/aɪm ˈtraɪnə sliːp/', 'Gíria. "Tryna" = "trying to". Comum na fala jovem e em mensagens; evite em texto formal.', '[{"start":0,"end":3,"role":"subject","surface":"I''m"},{"start":4,"end":16,"role":"predicate_verb","surface":"tryna sleep."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"tryna","pos":"verb","ipa":"/ˈtraɪnə/","gloss":"tentando (trying to)"},{"surface":"sleep","pos":"verb","ipa":"/sliːp/","gloss":"dormir"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-08', 'lesson-spoken-reductions-a2-01', 8, 'sentence', 'That ain''t right.', 'Isso não está certo.', '/ðæt eɪnt raɪt/', 'Informal. "Ain''t" substitui "isn''t", "aren''t" ou "am not". Muito usado na fala; evite na escrita formal.', '[{"start":0,"end":4,"role":"subject","surface":"That"},{"start":5,"end":10,"role":"predicate_verb","surface":"ain''t"},{"start":11,"end":17,"role":"predicate_adj","surface":"right."}]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"ain''t","pos":"verb","ipa":"/eɪnt/","gloss":"não é, não está (isn’t, aren’t)"},{"surface":"right","pos":"adjective","ipa":"/raɪt/","gloss":"certo, correto"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-09', 'lesson-spoken-reductions-a2-01', 9, 'sentence', 'I got a lotta work today.', 'Tenho um monte de trabalho hoje.', '/aɪ ɡɑːt ə ˈlɑːtə wɜːrk təˈdeɪ/', 'Informal. "Lotta" = "lot of". "A lotta work" = muito trabalho. Na escrita, "a lot of".', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":5,"role":"predicate_verb","surface":"got"},{"start":6,"end":18,"role":"direct_object","surface":"a lotta work"},{"start":19,"end":25,"role":"adverbial","surface":"today."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"tenho (I got = I have)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lotta","pos":"noun","ipa":"/ˈlɑːtə/","gloss":"um monte de (a lot of)"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-spoken-reductions-a2-01-10', 'lesson-spoken-reductions-a2-01', 10, 'sentence', 'Wait, you gonna eat that?', 'Espera, você vai comer isso?', '/weɪt juː ˈɡʌnə iːt ðæt/', 'Informal. Na fala o "are" some: "You gonna…?" = "Are you going to…?". Só funciona em pergunta direta e informal.', '[{"start":0,"end":5,"role":"discourse_marker","surface":"Wait,"},{"start":6,"end":9,"role":"subject","surface":"you"},{"start":10,"end":19,"role":"predicate_verb","surface":"gonna eat"},{"start":20,"end":25,"role":"direct_object","surface":"that?"}]'::jsonb, '[{"surface":"Wait","pos":"verb","ipa":"/weɪt/","gloss":"esperar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"eat","pos":"verb","ipa":"/iːt/","gloss":"comer"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
