-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-street-a1', 'street-english-slang-a1', 'Inglês das Ruas & Gírias Reais', 'Gírias, reduções da fala e expressões que nativos usam de verdade, com o registro e o sentido real de cada uma.', 'Frases curtas do cotidiano com gírias frequentes ("what''s up", "my bad", "I''m down"), reduções ("gonna", "wanna", "gotta"), mensagens, dinheiro, cansaço, expressões idiomáticas e como discordar. Cada nota explica o registro (informal ou gíria) e o sentido literal × o real.', 'A1', 'street-slang', 1, 'dia-a-dia', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-street-a1-05', 'course-street-a1', 5, 'Elogios e empolgação', 'Reagir com entusiasmo do jeito nativo.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-street-a1-05-01', 'lesson-street-a1-05', 1, 'sentence', 'That''s awesome!', 'Que demais!', '/ðæts ˈɔːsəm/', 'Informal. "Awesome" = incrível; nos EUA é usado para quase tudo que é bom.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"awesome","pos":"adjective","ipa":"/ˈɔːsəm/","gloss":"demais, incrível"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-02', 'lesson-street-a1-05', 2, 'sentence', 'This place is amazing.', 'Este lugar é incrível.', '/ðɪs pleɪs ɪz əˈmeɪzɪŋ/', 'Neutro. "Amazing" é mais forte que "good" e cabe em qualquer situação.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"place","pos":"noun","ipa":"/pleɪs/","gloss":"lugar"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"amazing","pos":"adjective","ipa":"/əˈmeɪzɪŋ/","gloss":"incrível"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-03', 'lesson-street-a1-05', 3, 'sentence', 'You look great today.', 'Você está ótimo hoje.', '/juː lʊk ɡreɪt təˈdeɪ/', 'Neutro. Elogio comum; "look" + adjetivo = estar com aparência.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-04', 'lesson-street-a1-05', 4, 'sentence', 'I''m so excited!', 'Estou muito animado!', '/aɪm soʊ ɪkˈsaɪtɪd/', 'Neutro. Falso cognato: "excited" = animado, empolgado (não tem sentido sexual).', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"excited","pos":"adjective","ipa":"/ɪkˈsaɪtɪd/","gloss":"animado, empolgado"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-05', 'lesson-street-a1-05', 5, 'sentence', 'That was sick!', 'Aquilo foi irado!', '/ðæt wɑːz sɪk/', 'Gíria. Literal: "doente". Real: incrível, muito bom. Evite em contexto formal.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"sick","pos":"adjective","ipa":"/sɪk/","gloss":"doente, enjoado"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-06', 'lesson-street-a1-05', 6, 'sentence', 'Nice job!', 'Mandou bem!', '/naɪs dʒɑːb/', 'Informal. Elogio rápido por algo bem feito. Também "Good job!".', '[]'::jsonb, '[{"surface":"Nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-07', 'lesson-street-a1-05', 7, 'sentence', 'You nailed it.', 'Você arrasou.', '/juː neɪld ɪt/', 'Informal. Literal: "você pregou (o prego)". Real: acertou em cheio.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"nailed","pos":"verb","ipa":"/neɪld/","gloss":"acertou em cheio"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-08', 'lesson-street-a1-05', 8, 'sentence', 'I''m a huge fan.', 'Sou muito fã.', '/aɪm ə hjuːdʒ fæn/', 'Neutro. "Huge" = enorme, reforça "fan".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"huge","pos":"adjective","ipa":"/hjuːdʒ/","gloss":"enorme"},{"surface":"fan","pos":"noun","ipa":"/fæn/","gloss":"fã"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-09', 'lesson-street-a1-05', 9, 'sentence', 'That sounds like a plan.', 'Fechado, combinado.', '/ðæt saʊndz laɪk ə plæn/', 'Informal. Literal: "isso soa como um plano". Real: concordo, vamos fazer.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"sounds","pos":"verb","ipa":"/saʊndz/","gloss":"soa, parece"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"plan","pos":"noun","ipa":"/plæn/","gloss":"plano"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-05-10', 'lesson-street-a1-05', 10, 'sentence', 'Way to go!', 'Isso aí!', '/weɪ tuː ɡoʊ/', 'Informal. Literal: "caminho a seguir". Real: parabéns pelo feito.', '[]'::jsonb, '[{"surface":"Way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-street-a1-06', 'course-street-a1', 6, 'Reduções da fala', 'Gonna, wanna, gotta e outras formas que você vai ouvir sempre.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-street-a1-06-01', 'lesson-street-a1-06', 1, 'sentence', 'I''m gonna be late.', 'Vou me atrasar.', '/aɪm ˈɡʌnə biː leɪt/', 'Informal. "Gonna" = "going to". Na escrita formal use "going to".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-02', 'lesson-street-a1-06', 2, 'sentence', 'Do you wanna come?', 'Quer vir?', '/duː juː ˈwɑːnə kʌm/', 'Informal. "Wanna" = "want to". Só antes de verbo.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"wanna","pos":"verb","ipa":"/ˈwɑːnə/","gloss":"quer (want to)"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-03', 'lesson-street-a1-06', 3, 'sentence', 'I gotta go.', 'Tenho que ir.', '/aɪ ˈɡɑːtə ɡoʊ/', 'Informal. "Gotta" = "have got to" (ter que).', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"gotta","pos":"verb","ipa":"/ˈɡɑːtə/","gloss":"tenho que (got to)"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-04', 'lesson-street-a1-06', 4, 'sentence', 'Lemme see.', 'Deixa eu ver.', '/ˈlɛmi siː/', 'Informal. "Lemme" = "let me".', '[]'::jsonb, '[{"surface":"Lemme","pos":"verb","ipa":"/ˈlɛmi/","gloss":"deixa eu (let me)"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-05', 'lesson-street-a1-06', 5, 'sentence', 'I dunno.', 'Sei lá.', '/aɪ dəˈnoʊ/', 'Informal. "Dunno" = "don''t know". Muito comum na fala rápida.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"dunno","pos":"verb","ipa":"/dəˈnoʊ/","gloss":"não sei (don''t know)"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-06', 'lesson-street-a1-06', 6, 'sentence', 'It''s kinda cold.', 'Está meio frio.', '/ɪts ˈkaɪndə koʊld/', 'Informal. "Kinda" = "kind of" = meio, um pouco.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"kinda","pos":"adverb","ipa":"/ˈkaɪndə/","gloss":"meio, um pouco (kind of)"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-07', 'lesson-street-a1-06', 7, 'sentence', 'Gimme a second.', 'Me dá um segundo.', '/ˈɡɪmi ə ˈsɛkənd/', 'Informal. "Gimme" = "give me".', '[]'::jsonb, '[{"surface":"Gimme","pos":"verb","ipa":"/ˈɡɪmi/","gloss":"me dá (give me)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"second","pos":"adjective","ipa":"/ˈsɛkənd/","gloss":"segundo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-08', 'lesson-street-a1-06', 8, 'sentence', 'What''re you doing?', 'O que você está fazendo?', '/ˈwʌtər juː ˈduːɪŋ/', 'Informal. "What''re" = "what are"; na fala soa "whaddaya".', '[]'::jsonb, '[{"surface":"What''re","pos":"pronoun","ipa":"/ˈwʌtər/","gloss":"o que (what are)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"doing","pos":"verb","ipa":"/ˈduːɪŋ/","gloss":"fazendo, fazer"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-09', 'lesson-street-a1-06', 9, 'sentence', 'I''ve gotta finish this.', 'Tenho que terminar isto.', '/aɪv ˈɡɑːtə ˈfɪnɪʃ ðɪs/', 'Informal. "I''ve gotta" = "I have got to".', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"gotta","pos":"verb","ipa":"/ˈɡɑːtə/","gloss":"tenho que (got to)"},{"surface":"finish","pos":"verb","ipa":"/ˈfɪnɪʃ/","gloss":"terminar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-06-10', 'lesson-street-a1-06', 10, 'sentence', 'Wanna grab a coffee?', 'Bora tomar um café?', '/ˈwɑːnə ɡræb ə ˈkɔːfi/', 'Informal. Sem sujeito: "(Do you) wanna…". "Grab" = pegar rapidinho.', '[]'::jsonb, '[{"surface":"Wanna","pos":"verb","ipa":"/ˈwɑːnə/","gloss":"quer (want to)"},{"surface":"grab","pos":"verb","ipa":"/ɡræb/","gloss":"pegar, comer algo rápido"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-street-a1-07', 'course-street-a1', 7, 'Mensagens de texto', 'Frases curtas que nativos mandam no celular.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-street-a1-07-01', 'lesson-street-a1-07', 1, 'sentence', 'Text me when you''re there.', 'Me manda mensagem quando chegar.', '/tɛkst miː wɛn jʊr ðɛr/', 'Neutro. "Text" como verbo = mandar mensagem.', '[]'::jsonb, '[{"surface":"Text","pos":"verb","ipa":"/tɛkst/","gloss":"mandar mensagem"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"you''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-02', 'lesson-street-a1-07', 2, 'sentence', 'Just checking in.', 'Só passando para saber como você está.', '/dʒʌst ˈtʃɛkɪŋ ɪn/', 'Neutro. Abre uma mensagem sem motivo urgente.', '[]'::jsonb, '[{"surface":"Just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"checking","pos":"verb","ipa":"/ˈtʃɛkɪŋ/","gloss":"despachando"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-03', 'lesson-street-a1-07', 3, 'sentence', 'Sorry, just saw this.', 'Desculpa, acabei de ver.', '/ˈsɑːri dʒʌst sɔː ðɪs/', 'Informal. Sujeito omitido ("I just saw this"), típico de mensagem.', '[]'::jsonb, '[{"surface":"Sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"saw","pos":"verb","ipa":"/sɔː/","gloss":"viu"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-04', 'lesson-street-a1-07', 4, 'sentence', 'Talk soon.', 'Até mais.', '/tɔːk suːn/', 'Informal. Encerra a conversa: "falamos logo".', '[]'::jsonb, '[{"surface":"Talk","pos":"verb","ipa":"/tɔːk/","gloss":"falar"},{"surface":"soon","pos":"adverb","ipa":"/suːn/","gloss":"logo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-05', 'lesson-street-a1-07', 5, 'sentence', 'Sounds good.', 'Beleza.', '/saʊndz ɡʊd/', 'Informal. Resposta curtíssima para concordar.', '[]'::jsonb, '[{"surface":"Sounds","pos":"verb","ipa":"/saʊndz/","gloss":"soa, parece"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-06', 'lesson-street-a1-07', 6, 'sentence', 'I''m on it.', 'Já estou vendo isso.', '/aɪm ɑːn ɪt/', 'Informal. Literal: "estou em cima disso". Real: já estou resolvendo.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-07', 'lesson-street-a1-07', 7, 'sentence', 'No worries.', 'De boa.', '/noʊ ˈwɜːriz/', 'Informal. Responde a "sorry" ou "thanks": sem problema.', '[]'::jsonb, '[{"surface":"No","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"worries","pos":"noun","ipa":"/ˈwɜːriz/","gloss":"preocupações"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-08', 'lesson-street-a1-07', 8, 'sentence', 'Call me when you can.', 'Me liga quando puder.', '/kɔːl miː wɛn juː kæn/', 'Neutro. Pedido sem pressa.', '[]'::jsonb, '[{"surface":"Call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-09', 'lesson-street-a1-07', 9, 'sentence', 'Can''t talk now, I''m in a meeting.', 'Não posso falar agora, estou numa reunião.', '/kænt tɔːk naʊ aɪm ɪn ə ˈmiːtɪŋ/', 'Neutro. Sujeito omitido no começo, comum em mensagem.', '[]'::jsonb, '[{"surface":"Can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"talk","pos":"verb","ipa":"/tɔːk/","gloss":"falar"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-07-10', 'lesson-street-a1-07', 10, 'sentence', 'Let me know.', 'Me avisa.', '/lɛt miː noʊ/', 'Neutro. Fecha pedidos: "Let me know if you can come".', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-street-a1-08', 'course-street-a1', 8, 'Dinheiro na gíria', 'Falar de preço, grana e contas como nativo.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-street-a1-08-01', 'lesson-street-a1-08', 1, 'sentence', 'I''m broke.', 'Estou duro.', '/aɪm broʊk/', 'Gíria. Literal: "estou quebrado". Real: sem dinheiro.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"broke","pos":"verb","ipa":"/broʊk/","gloss":"quebrou"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-02', 'lesson-street-a1-08', 2, 'sentence', 'It costs twenty bucks.', 'Custa vinte pratas.', '/ɪt kɔːsts ˈtwɛnti bʌks/', 'Informal. "Bucks" = dólares. Não se usa para outras moedas no dia a dia.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"},{"surface":"twenty","pos":"numeral","ipa":"/ˈtwɛnti/","gloss":"vinte"},{"surface":"bucks","pos":"noun","ipa":"/bʌks/","gloss":"dólares (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-03', 'lesson-street-a1-08', 3, 'sentence', 'That''s a rip-off.', 'Isso é um roubo.', '/ðæts ə ˈrɪpɔːf/', 'Informal. "Rip-off" = preço abusivo.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"rip-off","pos":"noun","ipa":"/ˈrɪpɔːf/","gloss":"preço abusivo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-04', 'lesson-street-a1-08', 4, 'sentence', 'It was a steal.', 'Saiu barato demais.', '/ɪt wɑːz ə stiːl/', 'Informal. Literal: "foi um roubo". Real: pechincha (o oposto de "rip-off").', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"steal","pos":"noun","ipa":"/stiːl/","gloss":"pechincha; roubar"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-05', 'lesson-street-a1-08', 5, 'sentence', 'It''s on me.', 'Deixa que eu pago.', '/ɪts ɑːn miː/', 'Informal. Literal: "está em mim". Real: eu pago a conta.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-06', 'lesson-street-a1-08', 6, 'sentence', 'Let''s split it.', 'Vamos dividir.', '/lɛts splɪt ɪt/', 'Neutro. "Split" = dividir a conta.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"split","pos":"verb","ipa":"/splɪt/","gloss":"dividir"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-07', 'lesson-street-a1-08', 7, 'sentence', 'It''s a bit pricey.', 'Está um pouco caro.', '/ɪts ə bɪt ˈpraɪsi/', 'Informal. "Pricey" = caro, mais leve que "expensive".', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"pricey","pos":"adjective","ipa":"/ˈpraɪsi/","gloss":"caro (informal)"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-08', 'lesson-street-a1-08', 8, 'sentence', 'I can''t afford it.', 'Não tenho como pagar.', '/aɪ kænt əˈfɔːrd ɪt/', 'Neutro. "Afford" = ter condição de pagar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"afford","pos":"verb","ipa":"/əˈfɔːrd/","gloss":"ter condição de pagar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-09', 'lesson-street-a1-08', 9, 'sentence', 'She makes good money.', 'Ela ganha bem.', '/ʃiː meɪks ɡʊd ˈmʌni/', 'Informal. "Make money" = ganhar dinheiro (nunca "win money" para salário).', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"makes","pos":"verb","ipa":"/meɪks/","gloss":"faz"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"money","pos":"noun","ipa":"/ˈmʌni/","gloss":"dinheiro"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-08-10', 'lesson-street-a1-08', 10, 'sentence', 'I''ll pay you back tomorrow.', 'Te devolvo amanhã.', '/aɪl peɪ juː bæk təˈmɑːroʊ/', 'Neutro. "Pay back" = devolver dinheiro emprestado.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"pay","pos":"verb","ipa":"/peɪ/","gloss":"pagar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-street-a1-09', 'course-street-a1', 9, 'Cansaço, estresse e humor', 'Dizer como você está sem soar como livro didático.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-street-a1-09-01', 'lesson-street-a1-09', 1, 'sentence', 'I''m beat.', 'Estou morto de cansado.', '/aɪm biːt/', 'Gíria. Literal: "estou batido". Real: exausto.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"beat","pos":"adjective","ipa":"/biːt/","gloss":"exausto (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-02', 'lesson-street-a1-09', 2, 'sentence', 'I''m stressed out.', 'Estou estressado.', '/aɪm strɛst aʊt/', 'Informal. "Stressed out" é mais natural que só "stressed".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"stressed","pos":"adjective","ipa":"/strɛst/","gloss":"estressado"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-03', 'lesson-street-a1-09', 3, 'sentence', 'I''m freaking out.', 'Estou surtando.', '/aɪm ˈfriːkɪŋ aʊt/', 'Gíria. "Freak out" = entrar em pânico, ficar muito nervoso.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"freaking","pos":"verb","ipa":"/ˈfriːkɪŋ/","gloss":"surtando (freak out)"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-04', 'lesson-street-a1-09', 4, 'sentence', 'Just chill.', 'Relaxa.', '/dʒʌst tʃɪl/', 'Gíria. "Chill" = relaxar; "chill out" também.', '[]'::jsonb, '[{"surface":"Just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"chill","pos":"verb","ipa":"/tʃɪl/","gloss":"relaxar (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-05', 'lesson-street-a1-09', 5, 'sentence', 'I''m not in the mood.', 'Não estou no clima.', '/aɪm nɑːt ɪn ðə muːd/', 'Neutro. "In the mood (for)" = com vontade de.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"mood","pos":"noun","ipa":"/muːd/","gloss":"humor, clima"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-06', 'lesson-street-a1-09', 6, 'sentence', 'I''m feeling under the weather.', 'Estou meio indisposto.', '/aɪm ˈfiːlɪŋ ˈʌndər ðə ˈwɛðər/', 'Informal. Literal: "sob o tempo". Real: meio doente.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"feeling","pos":"verb","ipa":"/ˈfiːlɪŋ/","gloss":"sentindo"},{"surface":"under","pos":"preposition","ipa":"/ˈʌndər/","gloss":"no nome de, sob"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-07', 'lesson-street-a1-09', 7, 'sentence', 'I''m so done.', 'Cansei.', '/aɪm soʊ dʌn/', 'Gíria. "Done" = farto, sem paciência.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"done","pos":"adjective","ipa":"/dʌn/","gloss":"pronto, feito"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-08', 'lesson-street-a1-09', 8, 'sentence', 'Take it easy.', 'Vai com calma.', '/teɪk ɪt ˈiːzi/', 'Informal. Também serve como despedida: "fica bem".', '[]'::jsonb, '[{"surface":"Take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"easy","pos":"adjective","ipa":"/ˈiːzi/","gloss":"fácil, tranquilo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-09', 'lesson-street-a1-09', 9, 'sentence', 'It''s been a long day.', 'O dia foi longo.', '/ɪts bɪn ə lɔːŋ deɪ/', 'Neutro. Present perfect para o dia que ainda não acabou.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-09-10', 'lesson-street-a1-09', 10, 'sentence', 'I''m hanging in there.', 'Estou levando.', '/aɪm ˈhæŋɪŋ ɪn ðɛr/', 'Informal. Literal: "estou pendurado aí". Real: aguentando firme.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"hanging","pos":"verb","ipa":"/ˈhæŋɪŋ/","gloss":"pendurado; aguentando"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-street-a1-10', 'course-street-a1', 10, 'Expressões idiomáticas do dia a dia', 'Frases que não dá para traduzir palavra por palavra.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-street-a1-10-01', 'lesson-street-a1-10', 1, 'sentence', 'It''s a piece of cake.', 'É moleza.', '/ɪts ə piːs ʌv keɪk/', 'Informal. Literal: "é um pedaço de bolo". Real: muito fácil.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"piece","pos":"noun","ipa":"/piːs/","gloss":"pedaço"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"cake","pos":"noun","ipa":"/keɪk/","gloss":"bolo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-02', 'lesson-street-a1-10', 2, 'sentence', 'Break a leg!', 'Boa sorte!', '/breɪk ə lɛɡ/', 'Informal. Literal: "quebre uma perna". Real: boa sorte (antes de apresentação).', '[]'::jsonb, '[{"surface":"Break","pos":"noun","ipa":"/breɪk/","gloss":"pausa, intervalo"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"leg","pos":"noun","ipa":"/lɛɡ/","gloss":"perna"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-03', 'lesson-street-a1-10', 3, 'sentence', 'Let''s call it a day.', 'Vamos encerrar por hoje.', '/lɛts kɔːl ɪt ə deɪ/', 'Informal. Literal: "vamos chamar de um dia". Real: parar de trabalhar.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-04', 'lesson-street-a1-10', 4, 'sentence', 'It''s not rocket science.', 'Não é nenhum bicho de sete cabeças.', '/ɪts nɑːt ˈrɑːkɪt ˈsaɪəns/', 'Informal. Literal: "não é ciência de foguete". Real: não é difícil.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"rocket","pos":"noun","ipa":"/ˈrɑːkɪt/","gloss":"foguete"},{"surface":"science","pos":"noun","ipa":"/ˈsaɪəns/","gloss":"ciência"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-05', 'lesson-street-a1-10', 5, 'sentence', 'I''ll keep an eye on it.', 'Vou ficar de olho.', '/aɪl kiːp ən aɪ ɑːn ɪt/', 'Neutro. Mesmo sentido do português.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"eye","pos":"noun","ipa":"/aɪ/","gloss":"olho"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-06', 'lesson-street-a1-10', 6, 'sentence', 'Better late than never.', 'Antes tarde do que nunca.', '/ˈbɛtər leɪt ðæn ˈnɛvər/', 'Neutro. Provérbio igual ao português.', '[]'::jsonb, '[{"surface":"Better","pos":"adjective","ipa":"/ˈbɛtər/","gloss":"melhor"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"than","pos":"conjunction","ipa":"/ðæn/","gloss":"do que"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-07', 'lesson-street-a1-10', 7, 'sentence', 'We are in the same boat.', 'Estamos no mesmo barco.', '/wiː ɑːr ɪn ðə seɪm boʊt/', 'Neutro. Mesmo sentido do português.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"same","pos":"adjective","ipa":"/seɪm/","gloss":"mesmo"},{"surface":"boat","pos":"noun","ipa":"/boʊt/","gloss":"barco"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-08', 'lesson-street-a1-10', 8, 'sentence', 'Let''s hit the road.', 'Vamos pegar a estrada.', '/lɛts hɪt ðə roʊd/', 'Informal. Literal: "vamos bater na estrada". Real: vamos embora.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"hit","pos":"verb","ipa":"/hɪt/","gloss":"bater, pegar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"road","pos":"noun","ipa":"/roʊd/","gloss":"estrada"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-09', 'lesson-street-a1-10', 9, 'sentence', 'It costs an arm and a leg.', 'Custa os olhos da cara.', '/ɪt kɔːsts ən ɑːrm ænd ə lɛɡ/', 'Informal. Literal: "custa um braço e uma perna". Real: muito caro.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"arm","pos":"noun","ipa":"/ɑːrm/","gloss":"braço"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"leg","pos":"noun","ipa":"/lɛɡ/","gloss":"perna"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-10-10', 'lesson-street-a1-10', 10, 'sentence', 'I''m all ears.', 'Sou todo ouvidos.', '/aɪm ɔːl ɪrz/', 'Informal. Mesmo sentido do português.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"ears","pos":"noun","ipa":"/ɪrz/","gloss":"ouvidos, orelhas"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-street-a1-11', 'course-street-a1', 11, 'Discordar e reclamar', 'Dizer não, discordar e reclamar sem ser grosso.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-street-a1-11-01', 'lesson-street-a1-11', 1, 'sentence', 'I don''t think so.', 'Acho que não.', '/aɪ doʊnt θɪŋk soʊ/', 'Neutro. Discordância suave. Nunca "I think not" na fala do dia a dia.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-02', 'lesson-street-a1-11', 2, 'sentence', 'I''m not so sure.', 'Não tenho tanta certeza.', '/aɪm nɑːt soʊ ʃʊr/', 'Neutro. Discorda sem confronto.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"sure","pos":"adjective","ipa":"/ʃʊr/","gloss":"claro; certo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-03', 'lesson-street-a1-11', 3, 'sentence', 'That''s not what I meant.', 'Não foi isso que eu quis dizer.', '/ðæts nɑːt wʌt aɪ mɛnt/', 'Neutro. "Meant" = passado de "mean".', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"meant","pos":"verb","ipa":"/mɛnt/","gloss":"quis dizer, significou"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-04', 'lesson-street-a1-11', 4, 'sentence', 'Give me a break.', 'Me poupe.', '/ɡɪv miː ə breɪk/', 'Informal. Literal: "me dá uma pausa". Real: não acredito, fala sério.', '[]'::jsonb, '[{"surface":"Give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"break","pos":"noun","ipa":"/breɪk/","gloss":"pausa, intervalo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-05', 'lesson-street-a1-11', 5, 'sentence', 'It''s not a big deal.', 'Não é nada demais.', '/ɪts nɑːt ə bɪɡ diːl/', 'Informal. "Big deal" = coisa importante.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"big","pos":"adjective","ipa":"/bɪɡ/","gloss":"grande"},{"surface":"deal","pos":"noun","ipa":"/diːl/","gloss":"negócio, coisa"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-06', 'lesson-street-a1-11', 6, 'sentence', 'I''m over it.', 'Já superei.', '/aɪm ˈoʊvər ɪt/', 'Informal. Literal: "estou por cima disso". Real: não me incomoda mais.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"por cima; superado"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-07', 'lesson-street-a1-11', 7, 'sentence', 'That''s not fair.', 'Isso não é justo.', '/ðæts nɑːt fɛr/', 'Neutro. "Fair" = justo.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"fair","pos":"adjective","ipa":"/fɛr/","gloss":"justo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-08', 'lesson-street-a1-11', 8, 'sentence', 'You''ve got a point.', 'Você tem razão nisso.', '/juːv ɡɑːt ə pɔɪnt/', 'Informal. Concorda em parte: "faz sentido o que você disse".', '[]'::jsonb, '[{"surface":"You''ve","pos":"pronoun","ipa":"/juːv/","gloss":"você tem (you have)"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-09', 'lesson-street-a1-11', 9, 'sentence', 'Let''s agree to disagree.', 'Vamos concordar em discordar.', '/lɛts əˈɡriː tuː ˌdɪsəˈɡriː/', 'Neutro. Encerra a discussão com educação.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"disagree","pos":"verb","ipa":"/ˌdɪsəˈɡriː/","gloss":"discordar"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-11-10', 'lesson-street-a1-11', 10, 'sentence', 'Come on!', 'Qual é!', '/kʌm ɑːn/', 'Informal. Pode ser incentivo ("vamos!") ou reclamação ("ah, fala sério!"), depende do tom.', '[]'::jsonb, '[{"surface":"Come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-street-a1-12', 'course-street-a1', 12, 'Revisão: gírias em conversa', 'Uma frase de cada capítulo do curso.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-street-a1-12-01', 'lesson-street-a1-12', 1, 'sentence', 'What''s up?', 'E aí?', '/wʌts ʌp/', 'Revisão de cumprimentos. Resposta: "Not much, you?".', '[]'::jsonb, '[{"surface":"What''s","pos":"pronoun","ipa":"/wʌts/","gloss":"qual é"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-02', 'lesson-street-a1-12', 2, 'sentence', 'Sure, I''m down.', 'Claro, tô dentro.', '/ʃʊr aɪm daʊn/', 'Revisão de combinar programa. "I''m down" = topo.', '[]'::jsonb, '[{"surface":"Sure","pos":"adjective","ipa":"/ʃʊr/","gloss":"claro; certo"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-03', 'lesson-street-a1-12', 3, 'sentence', 'No way!', 'Não acredito!', '/noʊ weɪ/', 'Revisão de reações. Literal: "nenhum jeito".', '[]'::jsonb, '[{"surface":"No","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-04', 'lesson-street-a1-12', 4, 'sentence', 'Thanks, I owe you one.', 'Valeu, te devo uma.', '/θæŋks aɪ oʊ juː wʌn/', 'Revisão de favores.', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"owe","pos":"verb","ipa":"/oʊ/","gloss":"dever"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-05', 'lesson-street-a1-12', 5, 'sentence', 'You nailed it.', 'Você arrasou.', '/juː neɪld ɪt/', 'Revisão de elogios.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"nailed","pos":"verb","ipa":"/neɪld/","gloss":"acertou em cheio"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-06', 'lesson-street-a1-12', 6, 'sentence', 'I''m gonna grab a coffee.', 'Vou pegar um café.', '/aɪm ˈɡʌnə ɡræb ə ˈkɔːfi/', 'Revisão de reduções: "gonna" + "grab".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"grab","pos":"verb","ipa":"/ɡræb/","gloss":"pegar, comer algo rápido"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-07', 'lesson-street-a1-12', 7, 'sentence', 'No worries, talk soon.', 'De boa, falamos logo.', '/noʊ ˈwɜːriz tɔːk suːn/', 'Revisão de mensagens.', '[]'::jsonb, '[{"surface":"No","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"worries","pos":"noun","ipa":"/ˈwɜːriz/","gloss":"preocupações"},{"surface":"talk","pos":"verb","ipa":"/tɔːk/","gloss":"falar"},{"surface":"soon","pos":"adverb","ipa":"/suːn/","gloss":"logo"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-08', 'lesson-street-a1-12', 8, 'sentence', 'I''m broke this month.', 'Estou duro este mês.', '/aɪm broʊk ðɪs mʌnθ/', 'Revisão de dinheiro.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"broke","pos":"verb","ipa":"/broʊk/","gloss":"quebrou"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-09', 'lesson-street-a1-12', 9, 'sentence', 'I''m beat, let''s call it a day.', 'Estou morto, vamos encerrar por hoje.', '/aɪm biːt lɛts kɔːl ɪt ə deɪ/', 'Revisão de cansaço e expressões idiomáticas.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"beat","pos":"adjective","ipa":"/biːt/","gloss":"exausto (gíria)"},{"surface":"let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-street-a1-12-10', 'lesson-street-a1-12', 10, 'sentence', 'It''s not a big deal.', 'Não é nada demais.', '/ɪts nɑːt ə bɪɡ diːl/', 'Revisão de discordar sem brigar.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"big","pos":"adjective","ipa":"/bɪɡ/","gloss":"grande"},{"surface":"deal","pos":"noun","ipa":"/diːl/","gloss":"negócio, coisa"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
