-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-interview-b1', 'job-interview-b1', 'Entrevista de Emprego', 'Responder as perguntas clássicas de entrevista em inglês: apresentação, experiência, pontos fortes, situações, salário e perguntas finais.', 'Oito capítulos que seguem a ordem real de uma entrevista: abertura e small talk, falar de si, experiência, pontos fortes e fracos, perguntas de situação (método STAR), motivação, salário e disponibilidade, e perguntas para o entrevistador com o follow-up. As notas explicam o tom e os erros comuns de brasileiros.', 'B1', 'business', 16, 'trabalho', 2, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-interview-b1-01', 'course-interview-b1', 1, 'Abertura e small talk', 'Os primeiros minutos da entrevista.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-interview-b1-01-01', 'lesson-interview-b1-01', 1, 'sentence', 'Nice to meet you. Thanks for having me.', 'Prazer. Obrigado pelo convite.', '/naɪs tuː miːt juː θæŋks fɔːr ˈhævɪŋ miː/', '"Thanks for having me" = obrigado por me receber. Abertura natural.', '[]'::jsonb, '[{"surface":"Nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"having","pos":"verb","ipa":"/ˈhævɪŋ/","gloss":"receber, ter"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-02', 'lesson-interview-b1-01', 2, 'sentence', 'Thank you for the opportunity.', 'Obrigado pela oportunidade.', '/θæŋk juː fɔːr ðə ˌɑːpərˈtuːnəti/', 'Frase segura para abrir ou fechar.', '[]'::jsonb, '[{"surface":"Thank","pos":"verb","ipa":"/θæŋk/","gloss":"agradecer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"opportunity","pos":"noun","ipa":"/ˌɑːpərˈtuːnəti/","gloss":"oportunidade"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-03', 'lesson-interview-b1-01', 3, 'sentence', 'Can you hear me well?', 'Você está me ouvindo bem?', '/kæn juː hɪr miː wɛl/', 'Em entrevista online, confirme o áudio logo no início.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"hear","pos":"verb","ipa":"/hɪr/","gloss":"ouvir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-04', 'lesson-interview-b1-01', 4, 'sentence', 'Sorry, my connection dropped for a second.', 'Desculpe, minha conexão caiu por um segundo.', '/ˈsɑːri maɪ kəˈnɛkʃən drɑːpt fɔːr ə ˈsɛkənd/', '"Drop" = cair (conexão).', '[]'::jsonb, '[{"surface":"Sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"connection","pos":"noun","ipa":"/kəˈnɛkʃən/","gloss":"conexão"},{"surface":"dropped","pos":"verb","ipa":"/drɑːpt/","gloss":"caiu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"second","pos":"adjective","ipa":"/ˈsɛkənd/","gloss":"segundo"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-05', 'lesson-interview-b1-01', 5, 'sentence', 'I''m doing well, thank you. How about you?', 'Estou bem, obrigado. E você?', '/aɪm ˈduːɪŋ wɛl θæŋk juː haʊ əˈbaʊt juː/', 'Devolva a pergunta: faz parte do small talk.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"doing","pos":"verb","ipa":"/ˈduːɪŋ/","gloss":"fazendo, fazer"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"},{"surface":"thank","pos":"verb","ipa":"/θæŋk/","gloss":"agradecer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-06', 'lesson-interview-b1-01', 6, 'sentence', 'I found the office easily.', 'Achei o escritório facilmente.', '/aɪ faʊnd ðə ˈɔːfɪs ˈiːzəli/', 'Resposta curta para "Did you find us okay?".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"office","pos":"noun","ipa":"/ˈɔːfɪs/","gloss":"escritório, balcão"},{"surface":"easily","pos":"adverb","ipa":"/ˈiːzəli/","gloss":"facilmente"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-07', 'lesson-interview-b1-01', 7, 'sentence', 'I''m really excited about this role.', 'Estou muito animado com esta vaga.', '/aɪm ˈriːəli ɪkˈsaɪtɪd əˈbaʊt ðɪs roʊl/', '"Role" = vaga, função. "Excited" é positivo, não tem sentido sexual.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"excited","pos":"adjective","ipa":"/ɪkˈsaɪtɪd/","gloss":"animado, empolgado"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"role","pos":"noun","ipa":"/roʊl/","gloss":"função, vaga"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-08', 'lesson-interview-b1-01', 8, 'sentence', 'Should I share my screen?', 'Devo compartilhar minha tela?', '/ʃʊd aɪ ʃɛr maɪ skriːn/', 'Útil em entrevistas técnicas online.', '[]'::jsonb, '[{"surface":"Should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"share","pos":"verb","ipa":"/ʃɛr/","gloss":"compartilhar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"screen","pos":"noun","ipa":"/skriːn/","gloss":"tela"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-09', 'lesson-interview-b1-01', 9, 'sentence', 'Could you tell me a bit about the team?', 'Poderia me falar um pouco sobre a equipe?', '/kʊd juː tɛl miː ə bɪt əˈbaʊt ðə tiːm/', 'Pergunta boa se o entrevistador abrir espaço no início.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-01-10', 'lesson-interview-b1-01', 10, 'sentence', 'I''m ready whenever you are.', 'Estou pronto quando você quiser.', '/aɪm ˈrɛdi wɛnˈɛvər juː ɑːr/', 'Mostra calma e disposição.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"ready","pos":"adjective","ipa":"/ˈrɛdi/","gloss":"pronto"},{"surface":"whenever","pos":"conjunction","ipa":"/wɛnˈɛvər/","gloss":"quando quer que"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-interview-b1-02', 'course-interview-b1', 2, 'Fale sobre você', 'A resposta de "Tell me about yourself".')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-interview-b1-02-01', 'lesson-interview-b1-02', 1, 'sentence', 'I''m a software developer with five years of experience.', 'Sou desenvolvedor de software com cinco anos de experiência.', '/aɪm ə ˈsɔːftwɛr dɪˈvɛləpər wɪð faɪv jɪrz ʌv ɪkˈspɪriəns/', 'Comece pelo presente: quem você é hoje, em uma frase.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"software","pos":"noun","ipa":"/ˈsɔːftwɛr/","gloss":"software"},{"surface":"developer","pos":"noun","ipa":"/dɪˈvɛləpər/","gloss":"desenvolvedor"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"experience","pos":"noun","ipa":"/ɪkˈspɪriəns/","gloss":"experiência"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-02', 'lesson-interview-b1-02', 2, 'sentence', 'I currently work at a small tech company.', 'Atualmente trabalho numa pequena empresa de tecnologia.', '/aɪ ˈkɜːrəntli wɜːrk æt ə smɔːl tɛk ˈkʌmpəni/', '"Currently" = atualmente. "Actually" é "na verdade".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"currently","pos":"adverb","ipa":"/ˈkɜːrəntli/","gloss":"atualmente"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"small","pos":"adjective","ipa":"/smɔːl/","gloss":"pequeno"},{"surface":"tech","pos":"noun","ipa":"/tɛk/","gloss":"tecnologia"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-03', 'lesson-interview-b1-02', 3, 'sentence', 'I''m responsible for the mobile app.', 'Sou responsável pelo aplicativo mobile.', '/aɪm rɪˈspɑːnsəbəl fɔːr ðə ˈmoʊbəl æp/', '"Responsible for" + substantivo ou -ing.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"responsible","pos":"adjective","ipa":"/rɪˈspɑːnsəbəl/","gloss":"responsável"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"mobile","pos":"adjective","ipa":"/ˈmoʊbəl/","gloss":"móvel, mobile"},{"surface":"app","pos":"noun","ipa":"/æp/","gloss":"aplicativo"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-04', 'lesson-interview-b1-02', 4, 'sentence', 'Before that, I worked in customer support.', 'Antes disso, trabalhei com suporte ao cliente.', '/bɪˈfɔːr ðæt aɪ wɜːrkt ɪn ˈkʌstəmər səˈpɔːrt/', 'Depois do presente, um passo no passado.', '[]'::jsonb, '[{"surface":"Before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"customer","pos":"noun","ipa":"/ˈkʌstəmər/","gloss":"cliente"},{"surface":"support","pos":"verb","ipa":"/səˈpɔːrt/","gloss":"apoiar"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-05', 'lesson-interview-b1-02', 5, 'sentence', 'I studied engineering in Campinas.', 'Estudei engenharia em Campinas.', '/aɪ ˈstʌdid ˌɛndʒɪˈnɪrɪŋ ɪn kɑːmˈpiːnəs/', 'Formação em uma frase, sem detalhes demais.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"studied","pos":"verb","ipa":"/ˈstʌdid/","gloss":"estudou, estudado"},{"surface":"engineering","pos":"noun","ipa":"/ˌɛndʒɪˈnɪrɪŋ/","gloss":"engenharia"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"Campinas","pos":"proper noun","ipa":"/kɑːmˈpiːnəs/","gloss":"Campinas"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-06', 'lesson-interview-b1-02', 6, 'sentence', 'I''m passionate about solving problems.', 'Sou apaixonado por resolver problemas.', '/aɪm ˈpæʃənət əˈbaʊt ˈsɑːlvɪŋ ˈprɑːbləmz/', '"Passionate about" + -ing.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"passionate","pos":"adjective","ipa":"/ˈpæʃənət/","gloss":"apaixonado"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"solving","pos":"verb","ipa":"/ˈsɑːlvɪŋ/","gloss":"resolver"},{"surface":"problems","pos":"noun","ipa":"/ˈprɑːbləmz/","gloss":"problemas"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-07', 'lesson-interview-b1-02', 7, 'sentence', 'That''s why I applied for this position.', 'Por isso me candidatei a esta vaga.', '/ðæts waɪ aɪ əˈplaɪd fɔːr ðɪs pəˈzɪʃən/', 'Feche ligando sua história à vaga.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"why","pos":"adverb","ipa":"/waɪ/","gloss":"por que"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"applied","pos":"verb","ipa":"/əˈplaɪd/","gloss":"candidatou-se"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"position","pos":"noun","ipa":"/pəˈzɪʃən/","gloss":"cargo, vaga"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-08', 'lesson-interview-b1-02', 8, 'sentence', 'I''m looking for a new challenge.', 'Estou procurando um novo desafio.', '/aɪm ˈlʊkɪŋ fɔːr ə nuː ˈtʃælɪndʒ/', 'Motivo neutro e positivo para mudar.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"challenge","pos":"noun","ipa":"/ˈtʃælɪndʒ/","gloss":"desafio"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-09', 'lesson-interview-b1-02', 9, 'sentence', 'In my free time, I like to run.', 'No tempo livre, gosto de correr.', '/ɪn maɪ friː taɪm aɪ laɪk tuː rʌn/', 'Um detalhe pessoal curto humaniza, mas não precisa.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"free","pos":"adjective","ipa":"/friː/","gloss":"livre, disponível"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"run","pos":"verb","ipa":"/rʌn/","gloss":"correr; administrar"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-02-10', 'lesson-interview-b1-02', 10, 'sentence', 'I''d be happy to go into more detail.', 'Posso detalhar mais, se quiser.', '/aɪd biː ˈhæpi tuː ɡoʊ ˈɪntuː mɔːr ˈdiːteɪl/', 'Deixa a porta aberta sem falar demais.', '[]'::jsonb, '[{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"happy","pos":"adjective","ipa":"/ˈhæpi/","gloss":"feliz"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"into","pos":"preposition","ipa":"/ˈɪntuː/","gloss":"para dentro de"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"detail","pos":"noun","ipa":"/ˈdiːteɪl/","gloss":"detalhe"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-interview-b1-03', 'course-interview-b1', 3, 'Experiência e resultados', 'Contar o que fez com números.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-interview-b1-03-01', 'lesson-interview-b1-03', 1, 'sentence', 'I led a team of four people.', 'Liderei uma equipe de quatro pessoas.', '/aɪ lɛd ə tiːm ʌv fɔːr ˈpiːpəl/', '"Led" = passado de "lead".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"led","pos":"verb","ipa":"/lɛd/","gloss":"liderou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"four","pos":"numeral","ipa":"/fɔːr/","gloss":"quatro"},{"surface":"people","pos":"noun","ipa":"/ˈpiːpəl/","gloss":"pessoas"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-02', 'lesson-interview-b1-03', 2, 'sentence', 'I improved the loading time by forty percent.', 'Melhorei o tempo de carregamento em quarenta por cento.', '/aɪ ɪmˈpruːvd ðə ˈloʊdɪŋ taɪm baɪ ˈfɔːrti pərˈsɛnt/', '"By" + número = em quanto mudou.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"improved","pos":"verb","ipa":"/ɪmˈpruːvd/","gloss":"melhorou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"loading","pos":"noun","ipa":"/ˈloʊdɪŋ/","gloss":"carregamento"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"forty","pos":"numeral","ipa":"/ˈfɔːrti/","gloss":"quarenta"},{"surface":"percent","pos":"noun","ipa":"/pərˈsɛnt/","gloss":"por cento"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-03', 'lesson-interview-b1-03', 3, 'sentence', 'We launched the product in six months.', 'Lançamos o produto em seis meses.', '/wiː lɔːntʃt ðə ˈprɑːdʌkt ɪn sɪks mʌnθs/', 'Resultado com prazo.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"launched","pos":"verb","ipa":"/lɔːntʃt/","gloss":"lançou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"product","pos":"noun","ipa":"/ˈprɑːdʌkt/","gloss":"produto"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"six","pos":"numeral","ipa":"/sɪks/","gloss":"seis"},{"surface":"months","pos":"noun","ipa":"/mʌnθs/","gloss":"meses"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-04', 'lesson-interview-b1-03', 4, 'sentence', 'I was in charge of the budget.', 'Eu era responsável pelo orçamento.', '/aɪ wɑːz ɪn tʃɑːrdʒ ʌv ðə ˈbʌdʒɪt/', '"In charge of" = responsável por.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"charge","pos":"noun","ipa":"/tʃɑːrdʒ/","gloss":"cobrança"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"budget","pos":"noun","ipa":"/ˈbʌdʒɪt/","gloss":"orçamento"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-05', 'lesson-interview-b1-03', 5, 'sentence', 'I worked closely with the design team.', 'Trabalhei de perto com a equipe de design.', '/aɪ wɜːrkt ˈkloʊsli wɪð ðə dɪˈzaɪn tiːm/', '"Closely" = de perto.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"},{"surface":"closely","pos":"adverb","ipa":"/ˈkloʊsli/","gloss":"de perto"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"design","pos":"noun","ipa":"/dɪˈzaɪn/","gloss":"design"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-06', 'lesson-interview-b1-03', 6, 'sentence', 'My main achievement was reducing costs.', 'Minha principal conquista foi reduzir custos.', '/maɪ meɪn əˈtʃiːvmənt wɑːz rɪˈduːsɪŋ kɔːsts/', '"Achievement" = conquista.', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"main","pos":"adjective","ipa":"/meɪn/","gloss":"principal"},{"surface":"achievement","pos":"noun","ipa":"/əˈtʃiːvmənt/","gloss":"conquista"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"reducing","pos":"verb","ipa":"/rɪˈduːsɪŋ/","gloss":"reduzindo"},{"surface":"costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-07', 'lesson-interview-b1-03', 7, 'sentence', 'I have experience with both startups and large companies.', 'Tenho experiência em startups e em empresas grandes.', '/aɪ hæv ɪkˈspɪriəns wɪð boʊθ ˈstɑːrtʌps ænd lɑːrdʒ ˈkʌmpəniz/', '"Experience with" ou "experience in".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"experience","pos":"noun","ipa":"/ɪkˈspɪriəns/","gloss":"experiência"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"both","pos":"determiner","ipa":"/boʊθ/","gloss":"ambos"},{"surface":"startups","pos":"noun","ipa":"/ˈstɑːrtʌps/","gloss":"startups"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"large","pos":"adjective","ipa":"/lɑːrdʒ/","gloss":"grande"},{"surface":"companies","pos":"noun","ipa":"/ˈkʌmpəniz/","gloss":"empresas"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-08', 'lesson-interview-b1-03', 8, 'sentence', 'I trained new employees.', 'Treinei funcionários novos.', '/aɪ treɪnd nuː ɪmˈplɔɪiːz/', 'Verbos de ação no passado soam fortes.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"trained","pos":"verb","ipa":"/treɪnd/","gloss":"treinou"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"employees","pos":"noun","ipa":"/ɪmˈplɔɪiːz/","gloss":"funcionários"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-09', 'lesson-interview-b1-03', 9, 'sentence', 'I have been working remotely for three years.', 'Trabalho remotamente há três anos.', '/aɪ hæv bɪn ˈwɜːrkɪŋ rɪˈmoʊtli fɔːr θriː jɪrz/', 'Present perfect contínuo: começou no passado e continua. Nunca "I work remotely since".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"working","pos":"verb","ipa":"/ˈwɜːrkɪŋ/","gloss":"funcionando; trabalhando"},{"surface":"remotely","pos":"adverb","ipa":"/rɪˈmoʊtli/","gloss":"remotamente"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"three","pos":"numeral","ipa":"/θriː/","gloss":"três"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-03-10', 'lesson-interview-b1-03', 10, 'sentence', 'I learned a lot from that project.', 'Aprendi muito com aquele projeto.', '/aɪ lɜːrnd ə lɑːt frʌm ðæt ˈprɑːdʒɛkt/', 'Mostra reflexão sobre a experiência.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"learned","pos":"verb","ipa":"/lɜːrnd/","gloss":"aprendeu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lot","pos":"noun","ipa":"/lɑːt/","gloss":"muito (a lot)"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"project","pos":"noun","ipa":"/ˈprɑːdʒɛkt/","gloss":"projeto"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-interview-b1-04', 'course-interview-b1', 4, 'Pontos fortes e fracos', 'Falar de qualidades sem arrogância.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-interview-b1-04-01', 'lesson-interview-b1-04', 1, 'sentence', 'One of my strengths is communication.', 'Um dos meus pontos fortes é a comunicação.', '/wʌn ʌv maɪ strɛŋkθs ɪz kəˌmjuːnɪˈkeɪʃən/', '"Strengths" = pontos fortes.', '[]'::jsonb, '[{"surface":"One","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"strengths","pos":"noun","ipa":"/strɛŋkθs/","gloss":"pontos fortes"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"communication","pos":"noun","ipa":"/kəˌmjuːnɪˈkeɪʃən/","gloss":"comunicação"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-02', 'lesson-interview-b1-04', 2, 'sentence', 'I''m very organized and detail-oriented.', 'Sou muito organizado e atento aos detalhes.', '/aɪm ˈvɛri ˈɔːrɡənaɪzd ænd ˈdiːteɪl ˈɔːriɛntɪd/', '"Detail-oriented" é expressão comum em vagas.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"very","pos":"adverb","ipa":"/ˈvɛri/","gloss":"muito"},{"surface":"organized","pos":"adjective","ipa":"/ˈɔːrɡənaɪzd/","gloss":"organizado"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"detail-oriented","pos":"adjective","ipa":"/ˈdiːteɪl ˈɔːriɛntɪd/","gloss":"atento aos detalhes"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-03', 'lesson-interview-b1-04', 3, 'sentence', 'I work well under pressure.', 'Trabalho bem sob pressão.', '/aɪ wɜːrk wɛl ˈʌndər ˈprɛʃər/', 'Frase clássica, melhor se vier com exemplo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"},{"surface":"under","pos":"preposition","ipa":"/ˈʌndər/","gloss":"no nome de, sob"},{"surface":"pressure","pos":"noun","ipa":"/ˈprɛʃər/","gloss":"pressão"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-04', 'lesson-interview-b1-04', 4, 'sentence', 'For example, last year we had a tight deadline.', 'Por exemplo, ano passado tivemos um prazo apertado.', '/fɔːr ɪɡˈzæmpəl læst jɪr wiː hæd ə taɪt ˈdɛdlaɪn/', 'Todo ponto forte precisa de um exemplo real.', '[]'::jsonb, '[{"surface":"For","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"example","pos":"noun","ipa":"/ɪɡˈzæmpəl/","gloss":"exemplo"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"tight","pos":"adjective","ipa":"/taɪt/","gloss":"apertado"},{"surface":"deadline","pos":"noun","ipa":"/ˈdɛdlaɪn/","gloss":"prazo"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-05', 'lesson-interview-b1-04', 5, 'sentence', 'I learn new tools quickly.', 'Aprendo ferramentas novas rápido.', '/aɪ lɜːrn nuː tuːlz ˈkwɪkli/', 'Ponto forte concreto.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"learn","pos":"verb","ipa":"/lɜːrn/","gloss":"aprender"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"tools","pos":"noun","ipa":"/tuːlz/","gloss":"ferramentas"},{"surface":"quickly","pos":"adverb","ipa":"/ˈkwɪkli/","gloss":"rapidamente"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-06', 'lesson-interview-b1-04', 6, 'sentence', 'My weakness is that I sometimes take on too much.', 'Meu ponto fraco é que às vezes assumo coisas demais.', '/maɪ ˈwiːknəs ɪz ðæt aɪ ˈsʌmtaɪmz teɪk ɑːn tuː mʌtʃ/', '"Take on" = assumir tarefas.', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"weakness","pos":"noun","ipa":"/ˈwiːknəs/","gloss":"ponto fraco"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"sometimes","pos":"adverb","ipa":"/ˈsʌmtaɪmz/","gloss":"às vezes"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-07', 'lesson-interview-b1-04', 7, 'sentence', 'I''m working on it by using a task list.', 'Estou melhorando isso usando uma lista de tarefas.', '/aɪm ˈwɜːrkɪŋ ɑːn ɪt baɪ ˈjuːzɪŋ ə tæsk lɪst/', 'Depois da fraqueza, diga o que está fazendo para melhorar.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"working","pos":"verb","ipa":"/ˈwɜːrkɪŋ/","gloss":"funcionando; trabalhando"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"using","pos":"verb","ipa":"/ˈjuːzɪŋ/","gloss":"usando"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"task","pos":"noun","ipa":"/tæsk/","gloss":"tarefa"},{"surface":"list","pos":"noun","ipa":"/lɪst/","gloss":"lista"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-08', 'lesson-interview-b1-04', 8, 'sentence', 'Public speaking used to be hard for me.', 'Falar em público costumava ser difícil para mim.', '/ˈpʌblɪk ˈspiːkɪŋ juːzd tuː biː hɑːrd fɔːr miː/', '"Used to" = no passado, não mais.', '[]'::jsonb, '[{"surface":"Public","pos":"adjective","ipa":"/ˈpʌblɪk/","gloss":"público"},{"surface":"speaking","pos":"verb","ipa":"/ˈspiːkɪŋ/","gloss":"falar"},{"surface":"used","pos":"verb","ipa":"/juːzd/","gloss":"usou, usado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"hard","pos":"adjective","ipa":"/hɑːrd/","gloss":"duro, difícil"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-09', 'lesson-interview-b1-04', 9, 'sentence', 'Now I feel more confident.', 'Agora me sinto mais confiante.', '/naʊ aɪ fiːl mɔːr ˈkɑːnfɪdənt/', 'Mostra evolução.', '[]'::jsonb, '[{"surface":"Now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"feel","pos":"verb","ipa":"/fiːl/","gloss":"sentir"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"confident","pos":"adjective","ipa":"/ˈkɑːnfɪdənt/","gloss":"confiante"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-04-10', 'lesson-interview-b1-04', 10, 'sentence', 'My colleagues would say I am reliable.', 'Meus colegas diriam que sou confiável.', '/maɪ ˈkɑːliːɡz wʊd seɪ aɪ æm rɪˈlaɪəbəl/', '"Would say" = forma educada de se elogiar pela voz dos outros.', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"colleagues","pos":"noun","ipa":"/ˈkɑːliːɡz/","gloss":"colegas"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"reliable","pos":"adjective","ipa":"/rɪˈlaɪəbəl/","gloss":"confiável"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-interview-b1-05', 'course-interview-b1', 5, 'Perguntas de situação', 'Responder com situação, tarefa, ação e resultado.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-interview-b1-05-01', 'lesson-interview-b1-05', 1, 'sentence', 'Let me give you an example.', 'Deixa eu te dar um exemplo.', '/lɛt miː ɡɪv juː ən ɪɡˈzæmpəl/', 'Abertura para resposta de situação (STAR).', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"example","pos":"noun","ipa":"/ɪɡˈzæmpəl/","gloss":"exemplo"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-02', 'lesson-interview-b1-05', 2, 'sentence', 'At my last job, a client was very unhappy.', 'No meu último emprego, um cliente estava muito insatisfeito.', '/æt maɪ læst dʒɑːb ə ˈklaɪənt wɑːz ˈvɛri ʌnˈhæpi/', 'S de Situation: o contexto em uma frase.', '[]'::jsonb, '[{"surface":"At","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"trabalho"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"client","pos":"noun","ipa":"/ˈklaɪənt/","gloss":"cliente"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"very","pos":"adverb","ipa":"/ˈvɛri/","gloss":"muito"},{"surface":"unhappy","pos":"adjective","ipa":"/ʌnˈhæpi/","gloss":"insatisfeito"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-03', 'lesson-interview-b1-05', 3, 'sentence', 'My task was to keep the account.', 'Minha tarefa era manter a conta.', '/maɪ tæsk wɑːz tuː kiːp ðə əˈkaʊnt/', 'T de Task: qual era o seu papel.', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"task","pos":"noun","ipa":"/tæsk/","gloss":"tarefa"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"account","pos":"noun","ipa":"/əˈkaʊnt/","gloss":"conta (cadastro)"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-04', 'lesson-interview-b1-05', 4, 'sentence', 'First, I listened to all his complaints.', 'Primeiro, ouvi todas as reclamações dele.', '/fɜːrst aɪ ˈlɪsənd tuː ɔːl hɪz kəmˈpleɪnts/', 'A de Action: o que você fez, com "I", não "we".', '[]'::jsonb, '[{"surface":"First","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"listened","pos":"verb","ipa":"/ˈlɪsənd/","gloss":"ouviu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"complaints","pos":"noun","ipa":"/kəmˈpleɪnts/","gloss":"reclamações"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-05', 'lesson-interview-b1-05', 5, 'sentence', 'Then I proposed a new plan.', 'Depois propus um plano novo.', '/ðɛn aɪ prəˈpoʊzd ə nuː plæn/', 'Continue a sequência com "then".', '[]'::jsonb, '[{"surface":"Then","pos":"adverb","ipa":"/ðɛn/","gloss":"então, depois"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"proposed","pos":"verb","ipa":"/prəˈpoʊzd/","gloss":"propôs"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"plan","pos":"noun","ipa":"/plæn/","gloss":"plano"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-06', 'lesson-interview-b1-05', 6, 'sentence', 'In the end, he renewed the contract.', 'No fim, ele renovou o contrato.', '/ɪn ðə ɛnd hiː rɪˈnuːd ðə ˈkɑːntrækt/', 'R de Result: o resultado concreto.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"end","pos":"noun","ipa":"/ɛnd/","gloss":"fim, final"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"renewed","pos":"verb","ipa":"/rɪˈnuːd/","gloss":"renovou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"contract","pos":"noun","ipa":"/ˈkɑːntrækt/","gloss":"contrato"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-07', 'lesson-interview-b1-05', 7, 'sentence', 'I disagreed with my manager once.', 'Uma vez discordei do meu gerente.', '/aɪ ˌdɪsəˈɡriːd wɪð maɪ ˈmænɪdʒər wʌns/', 'Pergunta comum sobre conflito.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"disagreed","pos":"verb","ipa":"/ˌdɪsəˈɡriːd/","gloss":"discordou"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"manager","pos":"noun","ipa":"/ˈmænɪdʒər/","gloss":"gerente"},{"surface":"once","pos":"adverb","ipa":"/wʌns/","gloss":"uma vez"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-08', 'lesson-interview-b1-05', 8, 'sentence', 'We talked about it privately.', 'Conversamos sobre isso em particular.', '/wiː tɔːkt əˈbaʊt ɪt ˈpraɪvətli/', 'Mostra maturidade no conflito.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"talked","pos":"verb","ipa":"/tɔːkt/","gloss":"conversou"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"privately","pos":"adverb","ipa":"/ˈpraɪvətli/","gloss":"em particular"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-09', 'lesson-interview-b1-05', 9, 'sentence', 'I made a mistake, and I told my team right away.', 'Cometi um erro e contei para a equipe na hora.', '/aɪ meɪd ə mɪˈsteɪk ænd aɪ toʊld maɪ tiːm raɪt əˈweɪ/', '"Make a mistake", nunca "do a mistake".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"mistake","pos":"noun","ipa":"/mɪˈsteɪk/","gloss":"erro"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"away","pos":"adverb","ipa":"/əˈweɪ/","gloss":"embora; (right away) já"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-05-10', 'lesson-interview-b1-05', 10, 'sentence', 'What I learned was to ask for help earlier.', 'O que aprendi foi pedir ajuda mais cedo.', '/wʌt aɪ lɜːrnd wɑːz tuː æsk fɔːr hɛlp ˈɜːrliər/', 'Feche com o aprendizado.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"learned","pos":"verb","ipa":"/lɜːrnd/","gloss":"aprendeu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"ask","pos":"verb","ipa":"/æsk/","gloss":"perguntar, pedir"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"earlier","pos":"adverb","ipa":"/ˈɜːrliər/","gloss":"mais cedo, antes"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-interview-b1-06', 'course-interview-b1', 6, 'Motivação e a empresa', 'Por que esta vaga e esta empresa.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-interview-b1-06-01', 'lesson-interview-b1-06', 1, 'sentence', 'I admire your company culture.', 'Admiro a cultura da sua empresa.', '/aɪ ədˈmaɪər jʊr ˈkʌmpəni ˈkʌltʃər/', 'Cite algo específico que você pesquisou.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"admire","pos":"verb","ipa":"/ədˈmaɪər/","gloss":"admirar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"},{"surface":"culture","pos":"noun","ipa":"/ˈkʌltʃər/","gloss":"cultura"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-02', 'lesson-interview-b1-06', 2, 'sentence', 'I read about your new product.', 'Li sobre o novo produto de vocês.', '/aɪ riːd əˈbaʊt jʊr nuː ˈprɑːdʌkt/', 'Mostra que pesquisou.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"product","pos":"noun","ipa":"/ˈprɑːdʌkt/","gloss":"produto"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-03', 'lesson-interview-b1-06', 3, 'sentence', 'I want to grow in this area.', 'Quero crescer nesta área.', '/aɪ wɑːnt tuː ɡroʊ ɪn ðɪs ˈɛriə/', 'Motivação de carreira.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"grow","pos":"verb","ipa":"/ɡroʊ/","gloss":"crescer"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"area","pos":"noun","ipa":"/ˈɛriə/","gloss":"área"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-04', 'lesson-interview-b1-06', 4, 'sentence', 'This role matches my experience.', 'Esta vaga combina com a minha experiência.', '/ðɪs roʊl ˈmætʃɪz maɪ ɪkˈspɪriəns/', '"Match" = combinar com.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"role","pos":"noun","ipa":"/roʊl/","gloss":"função, vaga"},{"surface":"matches","pos":"verb","ipa":"/ˈmætʃɪz/","gloss":"combina com"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"experience","pos":"noun","ipa":"/ɪkˈspɪriəns/","gloss":"experiência"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-05', 'lesson-interview-b1-06', 5, 'sentence', 'I believe I can add value to the team.', 'Acredito que posso agregar valor à equipe.', '/aɪ bɪˈliːv aɪ kæn æd ˈvæljuː tuː ðə tiːm/', '"Add value" = agregar valor.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"believe","pos":"verb","ipa":"/bɪˈliːv/","gloss":"acreditar"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"add","pos":"verb","ipa":"/æd/","gloss":"acrescentar"},{"surface":"value","pos":"noun","ipa":"/ˈvæljuː/","gloss":"valor"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-06', 'lesson-interview-b1-06', 6, 'sentence', 'In five years, I see myself leading a team.', 'Daqui a cinco anos, me vejo liderando uma equipe.', '/ɪn faɪv jɪrz aɪ siː maɪˈsɛlf ˈliːdɪŋ ə tiːm/', '"See myself" + -ing = me vejo fazendo.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"myself","pos":"pronoun","ipa":"/maɪˈsɛlf/","gloss":"eu mesmo, me"},{"surface":"leading","pos":"verb","ipa":"/ˈliːdɪŋ/","gloss":"liderando"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-07', 'lesson-interview-b1-06', 7, 'sentence', 'I''m leaving because there is no room to grow.', 'Estou saindo porque não tem espaço para crescer.', '/aɪm ˈliːvɪŋ bɪˈkɔːz ðɛr ɪz noʊ ruːm tuː ɡroʊ/', 'Nunca fale mal do emprego atual; foque no que busca.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"leaving","pos":"verb","ipa":"/ˈliːvɪŋ/","gloss":"saindo"},{"surface":"because","pos":"conjunction","ipa":"/bɪˈkɔːz/","gloss":"porque"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"no","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"grow","pos":"verb","ipa":"/ɡroʊ/","gloss":"crescer"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-08', 'lesson-interview-b1-06', 8, 'sentence', 'I''m looking for a more international environment.', 'Busco um ambiente mais internacional.', '/aɪm ˈlʊkɪŋ fɔːr ə mɔːr ˌɪntərˈnæʃənəl ɪnˈvaɪrənmənt/', 'Motivo positivo.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"international","pos":"adjective","ipa":"/ˌɪntərˈnæʃənəl/","gloss":"internacional"},{"surface":"environment","pos":"noun","ipa":"/ɪnˈvaɪrənmənt/","gloss":"ambiente"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-09', 'lesson-interview-b1-06', 9, 'sentence', 'I share your values.', 'Compartilho dos valores de vocês.', '/aɪ ʃɛr jʊr ˈvæljuːz/', 'Frase curta de alinhamento.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"share","pos":"verb","ipa":"/ʃɛr/","gloss":"compartilhar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"values","pos":"noun","ipa":"/ˈvæljuːz/","gloss":"valores"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-06-10', 'lesson-interview-b1-06', 10, 'sentence', 'Your mission really speaks to me.', 'A missão de vocês me toca muito.', '/jʊr ˈmɪʃən ˈriːəli spiːks tuː miː/', '"Speaks to me" = tem a ver comigo.', '[]'::jsonb, '[{"surface":"Your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"mission","pos":"noun","ipa":"/ˈmɪʃən/","gloss":"missão"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"speaks","pos":"verb","ipa":"/spiːks/","gloss":"fala"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-interview-b1-07', 'course-interview-b1', 7, 'Salário e disponibilidade', 'Negociar com clareza e educação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-interview-b1-07-01', 'lesson-interview-b1-07', 1, 'sentence', 'What is the salary range for this role?', 'Qual é a faixa salarial desta vaga?', '/wʌt ɪz ðə ˈsæləri reɪndʒ fɔːr ðɪs roʊl/', '"Salary range" = faixa salarial.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"salary","pos":"noun","ipa":"/ˈsæləri/","gloss":"salário"},{"surface":"range","pos":"noun","ipa":"/reɪndʒ/","gloss":"faixa"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"role","pos":"noun","ipa":"/roʊl/","gloss":"função, vaga"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-02', 'lesson-interview-b1-07', 2, 'sentence', 'I''m looking for something around sixty thousand a year.', 'Busco algo em torno de sessenta mil por ano.', '/aɪm ˈlʊkɪŋ fɔːr ˈsʌmθɪŋ əˈraʊnd ˈsɪksti ˈθaʊzənd ə jɪr/', 'Em muitos países o salário é anual.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"something","pos":"pronoun","ipa":"/ˈsʌmθɪŋ/","gloss":"alguma coisa"},{"surface":"around","pos":"adverb","ipa":"/əˈraʊnd/","gloss":"ao redor, por"},{"surface":"sixty","pos":"numeral","ipa":"/ˈsɪksti/","gloss":"sessenta"},{"surface":"thousand","pos":"numeral","ipa":"/ˈθaʊzənd/","gloss":"mil"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-03', 'lesson-interview-b1-07', 3, 'sentence', 'I''m open to discussing it.', 'Estou aberto a conversar sobre isso.', '/aɪm ˈoʊpən tuː dɪˈskʌsɪŋ ɪt/', '"Open to" + -ing.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"discussing","pos":"verb","ipa":"/dɪˈskʌsɪŋ/","gloss":"discutindo, conversando sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-04', 'lesson-interview-b1-07', 4, 'sentence', 'Is there flexibility on the salary?', 'Tem flexibilidade no salário?', '/ɪz ðɛr ˌflɛksəˈbɪləti ɑːn ðə ˈsæləri/', 'Pergunta educada de negociação.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"flexibility","pos":"noun","ipa":"/ˌflɛksəˈbɪləti/","gloss":"flexibilidade"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"salary","pos":"noun","ipa":"/ˈsæləri/","gloss":"salário"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-05', 'lesson-interview-b1-07', 5, 'sentence', 'What benefits do you offer?', 'Que benefícios vocês oferecem?', '/wʌt ˈbɛnəfɪts duː juː ˈɔːfər/', 'Pergunta sobre o pacote.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"benefits","pos":"noun","ipa":"/ˈbɛnəfɪts/","gloss":"benefícios"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"offer","pos":"noun","ipa":"/ˈɔːfər/","gloss":"oferta"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-06', 'lesson-interview-b1-07', 6, 'sentence', 'I can start in two weeks.', 'Posso começar em duas semanas.', '/aɪ kæn stɑːrt ɪn tuː wiːks/', 'Aviso prévio costuma ser de duas semanas nos EUA.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"start","pos":"verb","ipa":"/stɑːrt/","gloss":"começar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"weeks","pos":"noun","ipa":"/wiːks/","gloss":"semanas"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-07', 'lesson-interview-b1-07', 7, 'sentence', 'I need to give my current employer a month of notice.', 'Preciso dar um mês de aviso prévio ao meu empregador atual.', '/aɪ niːd tuː ɡɪv maɪ ˈkɜːrənt ɪmˈplɔɪər ə mʌnθ ʌv ˈnoʊtɪs/', '"Give notice" = dar aviso prévio.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"current","pos":"adjective","ipa":"/ˈkɜːrənt/","gloss":"atual"},{"surface":"employer","pos":"noun","ipa":"/ɪmˈplɔɪər/","gloss":"empregador"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"notice","pos":"noun","ipa":"/ˈnoʊtɪs/","gloss":"aviso"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-08', 'lesson-interview-b1-07', 8, 'sentence', 'Is this position remote or hybrid?', 'Esta vaga é remota ou híbrida?', '/ɪz ðɪs pəˈzɪʃən rɪˈmoʊt ɔːr ˈhaɪbrɪd/', '"Hybrid" = parte remoto, parte presencial.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"position","pos":"noun","ipa":"/pəˈzɪʃən/","gloss":"cargo, vaga"},{"surface":"remote","pos":"adjective","ipa":"/rɪˈmoʊt/","gloss":"remoto"},{"surface":"or","pos":"conjunction","ipa":"/ɔːr/","gloss":"ou"},{"surface":"hybrid","pos":"adjective","ipa":"/ˈhaɪbrɪd/","gloss":"híbrido"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-09', 'lesson-interview-b1-07', 9, 'sentence', 'Would I need to relocate?', 'Eu precisaria me mudar?', '/wʊd aɪ niːd tuː ˌriːˈloʊkeɪt/', '"Relocate" = mudar de cidade pelo trabalho.', '[]'::jsonb, '[{"surface":"Would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"relocate","pos":"verb","ipa":"/ˌriːˈloʊkeɪt/","gloss":"mudar-se (de cidade)"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-07-10', 'lesson-interview-b1-07', 10, 'sentence', 'Could I have some time to think about the offer?', 'Posso ter um tempo para pensar na proposta?', '/kʊd aɪ hæv sʌm taɪm tuː θɪŋk əˈbaʊt ðə ˈɔːfər/', 'Pedido comum e aceito.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"offer","pos":"noun","ipa":"/ˈɔːfər/","gloss":"oferta"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-interview-b1-08', 'course-interview-b1', 8, 'Perguntas finais e follow-up', 'Fechar bem e depois da entrevista.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-interview-b1-08-01', 'lesson-interview-b1-08', 1, 'sentence', 'Do you have any questions for us?', 'Você tem alguma pergunta para nós?', '/duː juː hæv ˈɛni ˈkwɛstʃənz fɔːr ʌs/', 'Sempre tenha pelo menos duas perguntas.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"questions","pos":"noun","ipa":"/ˈkwɛstʃənz/","gloss":"perguntas, dúvidas"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-02', 'lesson-interview-b1-08', 2, 'sentence', 'What does a typical day look like?', 'Como é um dia típico?', '/wʌt dʌz ə ˈtɪpɪkəl deɪ lʊk laɪk/', 'Pergunta segura e útil.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"typical","pos":"adjective","ipa":"/ˈtɪpɪkəl/","gloss":"típico"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-03', 'lesson-interview-b1-08', 3, 'sentence', 'How do you measure success in this role?', 'Como vocês medem sucesso nesta função?', '/haʊ duː juː ˈmɛʒər səkˈsɛs ɪn ðɪs roʊl/', 'Mostra foco em resultado.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"measure","pos":"verb","ipa":"/ˈmɛʒər/","gloss":"medir"},{"surface":"success","pos":"noun","ipa":"/səkˈsɛs/","gloss":"sucesso"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"role","pos":"noun","ipa":"/roʊl/","gloss":"função, vaga"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-04', 'lesson-interview-b1-08', 4, 'sentence', 'What are the next steps?', 'Quais são os próximos passos?', '/wʌt ɑːr ðə nɛkst stɛps/', 'Pergunta de fechamento.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"steps","pos":"noun","ipa":"/stɛps/","gloss":"passos"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-05', 'lesson-interview-b1-08', 5, 'sentence', 'When can I expect to hear from you?', 'Quando posso esperar um retorno?', '/wɛn kæn aɪ ɪkˈspɛkt tuː hɪr frʌm juː/', '"Hear from" = ter notícias de.', '[]'::jsonb, '[{"surface":"When","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"expect","pos":"verb","ipa":"/ɪkˈspɛkt/","gloss":"esperar (expectativa)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"hear","pos":"verb","ipa":"/hɪr/","gloss":"ouvir"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-06', 'lesson-interview-b1-08', 6, 'sentence', 'Thank you for your time today.', 'Obrigado pelo seu tempo hoje.', '/θæŋk juː fɔːr jʊr taɪm təˈdeɪ/', 'Encerramento educado.', '[]'::jsonb, '[{"surface":"Thank","pos":"verb","ipa":"/θæŋk/","gloss":"agradecer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-07', 'lesson-interview-b1-08', 7, 'sentence', 'I''m looking forward to hearing from you.', 'Fico no aguardo do seu retorno.', '/aɪm ˈlʊkɪŋ ˈfɔːrwərd tuː ˈhɪrɪŋ frʌm juː/', '"Looking forward to" + -ing. Frase padrão de e-mail.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"forward","pos":"adverb","ipa":"/ˈfɔːrwərd/","gloss":"adiante (look forward)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"hearing","pos":"verb","ipa":"/ˈhɪrɪŋ/","gloss":"ouvir, ter notícias"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-08', 'lesson-interview-b1-08', 8, 'sentence', 'I just wanted to follow up on my interview.', 'Só queria dar um retorno sobre a minha entrevista.', '/aɪ dʒʌst ˈwɑːntɪd tuː ˈfɑːloʊ ʌp ɑːn maɪ ˈɪntərvjuː/', '"Follow up" = retomar o contato. Envie uma semana depois.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"wanted","pos":"verb","ipa":"/ˈwɑːntɪd/","gloss":"quis, queria"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"follow","pos":"verb","ipa":"/ˈfɑːloʊ/","gloss":"seguir"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"interview","pos":"noun","ipa":"/ˈɪntərvjuː/","gloss":"entrevista"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-09', 'lesson-interview-b1-08', 9, 'sentence', 'I really enjoyed our conversation.', 'Gostei muito da nossa conversa.', '/aɪ ˈriːəli ɪnˈdʒɔɪd aʊər ˌkɑːnvərˈseɪʃən/', 'Abertura de e-mail de agradecimento.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"enjoyed","pos":"verb","ipa":"/ɪnˈdʒɔɪd/","gloss":"gostou"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"conversation","pos":"noun","ipa":"/ˌkɑːnvərˈseɪʃən/","gloss":"conversa"}]'::jsonb, NULL, NULL),
  ('unit-interview-b1-08-10', 'lesson-interview-b1-08', 10, 'sentence', 'I''m happy to accept the offer.', 'Fico feliz em aceitar a proposta.', '/aɪm ˈhæpi tuː əkˈsɛpt ðə ˈɔːfər/', 'Aceitar formalmente.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"happy","pos":"adjective","ipa":"/ˈhæpi/","gloss":"feliz"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"accept","pos":"verb","ipa":"/əkˈsɛpt/","gloss":"aceitar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"offer","pos":"noun","ipa":"/ˈɔːfər/","gloss":"oferta"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
