-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-1000-words-a1', '1000-essential-words', '1000 Palavras Essenciais', 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.', 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.', 'A1', 'grammar', 11, 'fundamentos', 2, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-05', 'course-1000-words-a1', 5, 'Números de 21 em diante', 'Dezenas, centenas, milhares e ordinais.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-05-01', 'lesson-1000-words-a1-05', 1, 'word', 'twenty-one', 'vinte e um', '/ˌtwɛntiˈwʌn/', 'De 21 a 99 as dezenas levam hífen: twenty-one, forty-five.', '[]'::jsonb, '[{"surface":"twenty-one","pos":"numeral","ipa":"/ˌtwɛntiˈwʌn/","gloss":"vinte e um"}]'::jsonb, 'She''s twenty-one years old.', 'Ela tem vinte e um anos.'),
  ('unit-1000-words-a1-05-02', 'lesson-1000-words-a1-05', 2, 'word', 'thirty', 'trinta', '/ˈθɜːrti/', 'Força no começo: THIR-ty. Em "thirteen" (13) a força vai no fim.', '[]'::jsonb, '[{"surface":"thirty","pos":"numeral","ipa":"/ˈθɜːrti/","gloss":"trinta"}]'::jsonb, 'The trip takes thirty minutes.', 'A viagem leva trinta minutos.'),
  ('unit-1000-words-a1-05-03', 'lesson-1000-words-a1-05', 3, 'word', 'forty', 'quarenta', '/ˈfɔːrti/', 'Sem "u": forty, embora seja "four".', '[]'::jsonb, '[{"surface":"forty","pos":"numeral","ipa":"/ˈfɔːrti/","gloss":"quarenta"}]'::jsonb, 'I have forty emails.', 'Tenho quarenta e-mails.'),
  ('unit-1000-words-a1-05-04', 'lesson-1000-words-a1-05', 4, 'word', 'fifty', 'cinquenta', '/ˈfɪfti/', NULL, '[]'::jsonb, '[{"surface":"fifty","pos":"numeral","ipa":"/ˈfɪfti/","gloss":"cinquenta"}]'::jsonb, 'It costs fifty dollars.', 'Custa cinquenta dólares.'),
  ('unit-1000-words-a1-05-05', 'lesson-1000-words-a1-05', 5, 'word', 'sixty', 'sessenta', '/ˈsɪksti/', NULL, '[]'::jsonb, '[{"surface":"sixty","pos":"numeral","ipa":"/ˈsɪksti/","gloss":"sessenta"}]'::jsonb, 'There are sixty minutes in an hour.', 'Uma hora tem sessenta minutos.'),
  ('unit-1000-words-a1-05-06', 'lesson-1000-words-a1-05', 6, 'word', 'seventy', 'setenta', '/ˈsɛvənti/', NULL, '[]'::jsonb, '[{"surface":"seventy","pos":"numeral","ipa":"/ˈsɛvənti/","gloss":"setenta"}]'::jsonb, 'My grandfather is seventy.', 'Meu avô tem setenta anos.'),
  ('unit-1000-words-a1-05-07', 'lesson-1000-words-a1-05', 7, 'word', 'eighty', 'oitenta', '/ˈeɪti/', 'Só um "t": eighty.', '[]'::jsonb, '[{"surface":"eighty","pos":"numeral","ipa":"/ˈeɪti/","gloss":"oitenta"}]'::jsonb, 'The bus holds eighty people.', 'O ônibus leva oitenta pessoas.'),
  ('unit-1000-words-a1-05-08', 'lesson-1000-words-a1-05', 8, 'word', 'ninety', 'noventa', '/ˈnaɪnti/', 'Mantém o "e" de "nine": ninety.', '[]'::jsonb, '[{"surface":"ninety","pos":"numeral","ipa":"/ˈnaɪnti/","gloss":"noventa"}]'::jsonb, 'I got ninety percent.', 'Tirei noventa por cento.'),
  ('unit-1000-words-a1-05-09', 'lesson-1000-words-a1-05', 9, 'word', 'hundred', 'cem', '/ˈhʌndrəd/', 'Não vai para o plural com número: "two hundred", não "two hundreds".', '[]'::jsonb, '[{"surface":"hundred","pos":"numeral","ipa":"/ˈhʌndrəd/","gloss":"cem, centena"}]'::jsonb, 'A hundred people came.', 'Cem pessoas vieram.'),
  ('unit-1000-words-a1-05-10', 'lesson-1000-words-a1-05', 10, 'word', 'thousand', 'mil', '/ˈθaʊzənd/', 'Também sem plural com número: "five thousand".', '[]'::jsonb, '[{"surface":"thousand","pos":"numeral","ipa":"/ˈθaʊzənd/","gloss":"mil"}]'::jsonb, 'The ticket costs a thousand dollars.', 'A passagem custa mil dólares.'),
  ('unit-1000-words-a1-05-11', 'lesson-1000-words-a1-05', 11, 'word', 'million', 'milhão', '/ˈmɪljən/', NULL, '[]'::jsonb, '[{"surface":"million","pos":"numeral","ipa":"/ˈmɪljən/","gloss":"milhão"}]'::jsonb, 'The city has a million people.', 'A cidade tem um milhão de pessoas.'),
  ('unit-1000-words-a1-05-12', 'lesson-1000-words-a1-05', 12, 'word', 'zero', 'zero', '/ˈzɪroʊ/', 'Em telefones também se diz "oh": "five oh two".', '[]'::jsonb, '[{"surface":"zero","pos":"numeral","ipa":"/ˈzɪroʊ/","gloss":"zero"}]'::jsonb, 'It''s zero degrees outside.', 'Está zero grau lá fora.'),
  ('unit-1000-words-a1-05-13', 'lesson-1000-words-a1-05', 13, 'word', 'half', 'metade, meio', '/hæf/', 'O "l" é mudo: /hæf/.', '[]'::jsonb, '[{"surface":"half","pos":"noun","ipa":"/hæf/","gloss":"metade, meio"}]'::jsonb, 'I ate half of the cake.', 'Comi metade do bolo.'),
  ('unit-1000-words-a1-05-14', 'lesson-1000-words-a1-05', 14, 'word', 'dozen', 'dúzia', '/ˈdʌzən/', NULL, '[]'::jsonb, '[{"surface":"dozen","pos":"noun","ipa":"/ˈdʌzən/","gloss":"dúzia"}]'::jsonb, 'A dozen eggs, please.', 'Uma dúzia de ovos, por favor.'),
  ('unit-1000-words-a1-05-15', 'lesson-1000-words-a1-05', 15, 'word', 'first', 'primeiro', '/fɜːrst/', 'Datas usam ordinais: "May first" = primeiro de maio.', '[]'::jsonb, '[{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"}]'::jsonb, 'This is my first trip.', 'Esta é minha primeira viagem.'),
  ('unit-1000-words-a1-05-16', 'lesson-1000-words-a1-05', 16, 'word', 'second', 'segundo', '/ˈsɛkənd/', NULL, '[]'::jsonb, '[{"surface":"second","pos":"adjective","ipa":"/ˈsɛkənd/","gloss":"segundo"}]'::jsonb, 'Take the second street.', 'Pegue a segunda rua.'),
  ('unit-1000-words-a1-05-17', 'lesson-1000-words-a1-05', 17, 'word', 'third', 'terceiro', '/θɜːrd/', NULL, '[]'::jsonb, '[{"surface":"third","pos":"adjective","ipa":"/θɜːrd/","gloss":"terceiro"}]'::jsonb, 'We live on the third floor.', 'Moramos no terceiro andar.'),
  ('unit-1000-words-a1-05-18', 'lesson-1000-words-a1-05', 18, 'word', 'fourth', 'quarto (ordinal)', '/fɔːrθ/', NULL, '[]'::jsonb, '[{"surface":"fourth","pos":"adjective","ipa":"/fɔːrθ/","gloss":"quarto (ordinal)"}]'::jsonb, 'July fourth is a holiday.', 'Quatro de julho é feriado.'),
  ('unit-1000-words-a1-05-19', 'lesson-1000-words-a1-05', 19, 'word', 'fifth', 'quinto', '/fɪfθ/', NULL, '[]'::jsonb, '[{"surface":"fifth","pos":"adjective","ipa":"/fɪfθ/","gloss":"quinto"}]'::jsonb, 'He finished fifth.', 'Ele terminou em quinto.'),
  ('unit-1000-words-a1-05-20', 'lesson-1000-words-a1-05', 20, 'word', 'number', 'número', '/ˈnʌmbər/', NULL, '[]'::jsonb, '[{"surface":"number","pos":"noun","ipa":"/ˈnʌmbər/","gloss":"número"}]'::jsonb, 'What''s your phone number?', 'Qual é o seu número de telefone?')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-06', 'course-1000-words-a1', 6, 'Dias da semana e meses', 'Agenda, datas e aniversários.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-06-01', 'lesson-1000-words-a1-06', 1, 'word', 'Monday', 'segunda-feira', '/ˈmʌndeɪ/', 'Dias e meses sempre com maiúscula em inglês. Preposição: "on Monday".', '[]'::jsonb, '[{"surface":"Monday","pos":"proper noun","ipa":"/ˈmʌndeɪ/","gloss":"segunda-feira"}]'::jsonb, 'I start work on Monday.', 'Começo a trabalhar na segunda.'),
  ('unit-1000-words-a1-06-02', 'lesson-1000-words-a1-06', 2, 'word', 'Tuesday', 'terça-feira', '/ˈtuːzdeɪ/', NULL, '[]'::jsonb, '[{"surface":"Tuesday","pos":"proper noun","ipa":"/ˈtuːzdeɪ/","gloss":"terça-feira"}]'::jsonb, 'The class is on Tuesday.', 'A aula é na terça.'),
  ('unit-1000-words-a1-06-03', 'lesson-1000-words-a1-06', 3, 'word', 'Wednesday', 'quarta-feira', '/ˈwɛnzdeɪ/', 'Pronúncia /ˈwɛnzdeɪ/: o primeiro "d" é mudo.', '[]'::jsonb, '[{"surface":"Wednesday","pos":"proper noun","ipa":"/ˈwɛnzdeɪ/","gloss":"quarta-feira"}]'::jsonb, 'Let''s meet on Wednesday.', 'Vamos nos ver na quarta.'),
  ('unit-1000-words-a1-06-04', 'lesson-1000-words-a1-06', 4, 'word', 'Thursday', 'quinta-feira', '/ˈθɜːrzdeɪ/', NULL, '[]'::jsonb, '[{"surface":"Thursday","pos":"proper noun","ipa":"/ˈθɜːrzdeɪ/","gloss":"quinta-feira"}]'::jsonb, 'The store closes early on Thursday.', 'A loja fecha cedo na quinta.'),
  ('unit-1000-words-a1-06-05', 'lesson-1000-words-a1-06', 5, 'word', 'Friday', 'sexta-feira', '/ˈfraɪdeɪ/', NULL, '[]'::jsonb, '[{"surface":"Friday","pos":"proper noun","ipa":"/ˈfraɪdeɪ/","gloss":"sexta-feira"}]'::jsonb, 'We go out on Friday nights.', 'Saímos nas sextas à noite.'),
  ('unit-1000-words-a1-06-06', 'lesson-1000-words-a1-06', 6, 'word', 'Saturday', 'sábado', '/ˈsætərdeɪ/', NULL, '[]'::jsonb, '[{"surface":"Saturday","pos":"proper noun","ipa":"/ˈsætərdeɪ/","gloss":"sábado"}]'::jsonb, 'I sleep late on Saturday.', 'Durmo até tarde no sábado.'),
  ('unit-1000-words-a1-06-07', 'lesson-1000-words-a1-06', 7, 'word', 'Sunday', 'domingo', '/ˈsʌndeɪ/', NULL, '[]'::jsonb, '[{"surface":"Sunday","pos":"proper noun","ipa":"/ˈsʌndeɪ/","gloss":"domingo"}]'::jsonb, 'The market is open on Sunday.', 'O mercado abre no domingo.'),
  ('unit-1000-words-a1-06-08', 'lesson-1000-words-a1-06', 8, 'word', 'weekend', 'fim de semana', '/ˈwiːkɛnd/', 'EUA: "on the weekend"; Reino Unido: "at the weekend".', '[]'::jsonb, '[{"surface":"weekend","pos":"noun","ipa":"/ˈwiːkɛnd/","gloss":"fim de semana"}]'::jsonb, 'What are you doing this weekend?', 'O que você vai fazer neste fim de semana?'),
  ('unit-1000-words-a1-06-09', 'lesson-1000-words-a1-06', 9, 'word', 'January', 'janeiro', '/ˈdʒænjuɛri/', 'Meses usam "in": "in January". Com dia, "on": "on January 5th".', '[]'::jsonb, '[{"surface":"January","pos":"proper noun","ipa":"/ˈdʒænjuɛri/","gloss":"janeiro"}]'::jsonb, 'My birthday is in January.', 'Meu aniversário é em janeiro.'),
  ('unit-1000-words-a1-06-10', 'lesson-1000-words-a1-06', 10, 'word', 'February', 'fevereiro', '/ˈfɛbruɛri/', NULL, '[]'::jsonb, '[{"surface":"February","pos":"proper noun","ipa":"/ˈfɛbruɛri/","gloss":"fevereiro"}]'::jsonb, 'February is a short month.', 'Fevereiro é um mês curto.'),
  ('unit-1000-words-a1-06-11', 'lesson-1000-words-a1-06', 11, 'word', 'March', 'março', '/mɑːrtʃ/', 'Nos EUA a primavera começa em março, ao contrário do Brasil.', '[]'::jsonb, '[{"surface":"March","pos":"proper noun","ipa":"/mɑːrtʃ/","gloss":"março"}]'::jsonb, 'Spring starts in March.', 'A primavera começa em março.'),
  ('unit-1000-words-a1-06-12', 'lesson-1000-words-a1-06', 12, 'word', 'April', 'abril', '/ˈeɪprəl/', NULL, '[]'::jsonb, '[{"surface":"April","pos":"proper noun","ipa":"/ˈeɪprəl/","gloss":"abril"}]'::jsonb, 'It rains a lot in April.', 'Chove muito em abril.'),
  ('unit-1000-words-a1-06-13', 'lesson-1000-words-a1-06', 13, 'word', 'June', 'junho', '/dʒuːn/', NULL, '[]'::jsonb, '[{"surface":"June","pos":"proper noun","ipa":"/dʒuːn/","gloss":"junho"}]'::jsonb, 'School ends in June.', 'As aulas terminam em junho.'),
  ('unit-1000-words-a1-06-14', 'lesson-1000-words-a1-06', 14, 'word', 'July', 'julho', '/dʒʊˈlaɪ/', 'Força no fim: ju-LY.', '[]'::jsonb, '[{"surface":"July","pos":"proper noun","ipa":"/dʒʊˈlaɪ/","gloss":"julho"}]'::jsonb, 'We travel every July.', 'Viajamos todo mês de julho.'),
  ('unit-1000-words-a1-06-15', 'lesson-1000-words-a1-06', 15, 'word', 'August', 'agosto', '/ˈɔːɡəst/', NULL, '[]'::jsonb, '[{"surface":"August","pos":"proper noun","ipa":"/ˈɔːɡəst/","gloss":"agosto"}]'::jsonb, 'August is very hot here.', 'Agosto é muito quente aqui.'),
  ('unit-1000-words-a1-06-16', 'lesson-1000-words-a1-06', 16, 'word', 'September', 'setembro', '/sɛpˈtɛmbər/', NULL, '[]'::jsonb, '[{"surface":"September","pos":"proper noun","ipa":"/sɛpˈtɛmbər/","gloss":"setembro"}]'::jsonb, 'Classes start in September.', 'As aulas começam em setembro.'),
  ('unit-1000-words-a1-06-17', 'lesson-1000-words-a1-06', 17, 'word', 'October', 'outubro', '/ɑːkˈtoʊbər/', NULL, '[]'::jsonb, '[{"surface":"October","pos":"proper noun","ipa":"/ɑːkˈtoʊbər/","gloss":"outubro"}]'::jsonb, 'Halloween is in October.', 'O Halloween é em outubro.'),
  ('unit-1000-words-a1-06-18', 'lesson-1000-words-a1-06', 18, 'word', 'November', 'novembro', '/noʊˈvɛmbər/', NULL, '[]'::jsonb, '[{"surface":"November","pos":"proper noun","ipa":"/noʊˈvɛmbər/","gloss":"novembro"}]'::jsonb, 'The trip is in November.', 'A viagem é em novembro.'),
  ('unit-1000-words-a1-06-19', 'lesson-1000-words-a1-06', 19, 'word', 'December', 'dezembro', '/dɪˈsɛmbər/', NULL, '[]'::jsonb, '[{"surface":"December","pos":"proper noun","ipa":"/dɪˈsɛmbər/","gloss":"dezembro"}]'::jsonb, 'Christmas is in December.', 'O Natal é em dezembro.'),
  ('unit-1000-words-a1-06-20', 'lesson-1000-words-a1-06', 20, 'word', 'May', 'maio', '/meɪ/', '"May" também é verbo modal ("may I…?" = posso…?).', '[]'::jsonb, '[{"surface":"May","pos":"modal verb","ipa":"/meɪ/","gloss":"poder (permissão formal)"}]'::jsonb, 'The concert is in May.', 'O show é em maio.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-07', 'course-1000-words-a1', 7, 'Horas e partes do dia', 'Dizer as horas, marcar compromissos e falar de hoje e amanhã.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-07-01', 'lesson-1000-words-a1-07', 1, 'word', 'time', 'tempo, hora', '/taɪm/', '"What time is it?" é a pergunta das horas. "Time" também é "vez": three times.', '[]'::jsonb, '[{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"tempo, hora"}]'::jsonb, 'What time is it?', 'Que horas são?'),
  ('unit-1000-words-a1-07-02', 'lesson-1000-words-a1-07', 2, 'word', 'hour', 'hora', '/aʊər/', 'O "h" é mudo: /aʊər/. Por isso "an hour".', '[]'::jsonb, '[{"surface":"hour","pos":"noun","ipa":"/aʊər/","gloss":"hora"}]'::jsonb, 'The flight is two hours long.', 'O voo dura duas horas.'),
  ('unit-1000-words-a1-07-03', 'lesson-1000-words-a1-07', 3, 'word', 'minute', 'minuto', '/ˈmɪnɪt/', NULL, '[]'::jsonb, '[{"surface":"minute","pos":"noun","ipa":"/ˈmɪnɪt/","gloss":"minuto"}]'::jsonb, 'Wait a minute.', 'Espere um minuto.'),
  ('unit-1000-words-a1-07-04', 'lesson-1000-words-a1-07', 4, 'word', 'o''clock', 'em ponto', '/əˈklɑːk/', 'Só com horas cheias: "three o''clock", nunca "three thirty o''clock".', '[]'::jsonb, '[{"surface":"o''clock","pos":"adverb","ipa":"/əˈklɑːk/","gloss":"em ponto"}]'::jsonb, 'It''s three o''clock.', 'São três em ponto.'),
  ('unit-1000-words-a1-07-05', 'lesson-1000-words-a1-07', 5, 'word', 'half', 'meia (hora)', '/hæf/', '"Half past" = e meia. Nos EUA é mais comum dizer "six thirty".', '[]'::jsonb, '[{"surface":"half","pos":"noun","ipa":"/hæf/","gloss":"metade, meio"}]'::jsonb, 'It''s half past six.', 'São seis e meia.'),
  ('unit-1000-words-a1-07-06', 'lesson-1000-words-a1-07', 6, 'word', 'quarter', 'quinze minutos', '/ˈkwɔːrtər/', '"Quarter past" = e quinze; "quarter to" = quinze para.', '[]'::jsonb, '[{"surface":"quarter","pos":"noun","ipa":"/ˈkwɔːrtər/","gloss":"quarto (15 minutos)"}]'::jsonb, 'It''s a quarter to five.', 'São quinze para as cinco.'),
  ('unit-1000-words-a1-07-07', 'lesson-1000-words-a1-07', 7, 'word', 'morning', 'manhã', '/ˈmɔːrnɪŋ/', '"In the morning", "in the afternoon", "in the evening", mas "at night".', '[]'::jsonb, '[{"surface":"morning","pos":"noun","ipa":"/ˈmɔːrnɪŋ/","gloss":"manhã"}]'::jsonb, 'I run in the morning.', 'Eu corro de manhã.'),
  ('unit-1000-words-a1-07-08', 'lesson-1000-words-a1-07', 8, 'word', 'noon', 'meio-dia', '/nuːn/', NULL, '[]'::jsonb, '[{"surface":"noon","pos":"noun","ipa":"/nuːn/","gloss":"meio-dia"}]'::jsonb, 'Let''s have lunch at noon.', 'Vamos almoçar ao meio-dia.'),
  ('unit-1000-words-a1-07-09', 'lesson-1000-words-a1-07', 9, 'word', 'afternoon', 'tarde', '/ˌæftərˈnuːn/', NULL, '[]'::jsonb, '[{"surface":"afternoon","pos":"noun","ipa":"/ˌæftərˈnuːn/","gloss":"tarde"}]'::jsonb, 'The meeting is in the afternoon.', 'A reunião é à tarde.'),
  ('unit-1000-words-a1-07-10', 'lesson-1000-words-a1-07', 10, 'word', 'evening', 'noite (início)', '/ˈiːvnɪŋ/', '"Good evening" = boa noite ao chegar; "good night" = ao se despedir.', '[]'::jsonb, '[{"surface":"evening","pos":"noun","ipa":"/ˈiːvnɪŋ/","gloss":"noite (início), fim de tarde"}]'::jsonb, 'Good evening, everyone.', 'Boa noite a todos.'),
  ('unit-1000-words-a1-07-11', 'lesson-1000-words-a1-07', 11, 'word', 'night', 'noite', '/naɪt/', NULL, '[]'::jsonb, '[{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, 'I work at night.', 'Eu trabalho à noite.'),
  ('unit-1000-words-a1-07-12', 'lesson-1000-words-a1-07', 12, 'word', 'midnight', 'meia-noite', '/ˈmɪdnaɪt/', NULL, '[]'::jsonb, '[{"surface":"midnight","pos":"noun","ipa":"/ˈmɪdnaɪt/","gloss":"meia-noite"}]'::jsonb, 'The party ends at midnight.', 'A festa termina à meia-noite.'),
  ('unit-1000-words-a1-07-13', 'lesson-1000-words-a1-07', 13, 'word', 'today', 'hoje', '/təˈdeɪ/', NULL, '[]'::jsonb, '[{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, 'I''m free today.', 'Estou livre hoje.'),
  ('unit-1000-words-a1-07-14', 'lesson-1000-words-a1-07', 14, 'word', 'tomorrow', 'amanhã', '/təˈmɑːroʊ/', NULL, '[]'::jsonb, '[{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, 'See you tomorrow.', 'Até amanhã.'),
  ('unit-1000-words-a1-07-15', 'lesson-1000-words-a1-07', 15, 'word', 'yesterday', 'ontem', '/ˈjɛstərdeɪ/', NULL, '[]'::jsonb, '[{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, 'I called you yesterday.', 'Liguei para você ontem.'),
  ('unit-1000-words-a1-07-16', 'lesson-1000-words-a1-07', 16, 'word', 'now', 'agora', '/naʊ/', NULL, '[]'::jsonb, '[{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, 'I''m busy now.', 'Estou ocupado agora.'),
  ('unit-1000-words-a1-07-17', 'lesson-1000-words-a1-07', 17, 'word', 'soon', 'logo, em breve', '/suːn/', NULL, '[]'::jsonb, '[{"surface":"soon","pos":"adverb","ipa":"/suːn/","gloss":"logo, em breve"}]'::jsonb, 'The bus will come soon.', 'O ônibus vai chegar logo.'),
  ('unit-1000-words-a1-07-18', 'lesson-1000-words-a1-07', 18, 'word', 'late', 'atrasado, tarde', '/leɪt/', '"Late" = atrasado; "later" = mais tarde.', '[]'::jsonb, '[{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado, tarde"}]'::jsonb, 'Sorry, I''m late.', 'Desculpe, estou atrasado.'),
  ('unit-1000-words-a1-07-19', 'lesson-1000-words-a1-07', 19, 'word', 'early', 'cedo', '/ˈɜːrli/', NULL, '[]'::jsonb, '[{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"}]'::jsonb, 'I get up early.', 'Eu acordo cedo.'),
  ('unit-1000-words-a1-07-20', 'lesson-1000-words-a1-07', 20, 'word', 'schedule', 'horário, agenda', '/ˈskɛdʒuːl/', 'EUA: /ˈskɛdʒuːl/; Reino Unido: /ˈʃɛdjuːl/.', '[]'::jsonb, '[{"surface":"schedule","pos":"noun","ipa":"/ˈskɛdʒuːl/","gloss":"horário, agenda"}]'::jsonb, 'What''s your schedule tomorrow?', 'Como está sua agenda amanhã?')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
