-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-essential-verbs-a1', 'essential-verbs', 'Verbos Essenciais', 'Os verbos mais usados em frases separadas por tempo: presente, passado, futuro e present perfect.', 'Cada verbo aparece em quatro frases reais, uma por tempo verbal, com a explicação gramatical de cada forma. No fim de cada módulo, você revisa as três formas (base, passado e particípio).', 'A1', 'grammar', 12, 'fundamentos', 3, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-07', 'course-essential-verbs-a1', 7, 'see e come', 'Ver e vir nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-07-01', 'lesson-essential-verbs-a1-07', 1, 'sentence', 'I see my parents every Sunday.', 'Eu vejo meus pais todo domingo.', '/aɪ siː maɪ ˈpɛrənts ˈɛvri ˈsʌndeɪ/', 'Presente de "see" (ver). "Every Sunday" indica hábito. Com he/she/it: "sees".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"parents","pos":"noun","ipa":"/ˈpɛrənts/","gloss":"pais (pai e mãe)"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"Sunday","pos":"proper noun","ipa":"/ˈsʌndeɪ/","gloss":"domingo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-07-02', 'lesson-essential-verbs-a1-07', 2, 'sentence', 'I saw a great movie last night.', 'Vi um filme ótimo ontem à noite.', '/aɪ sɔː ə ɡreɪt ˈmuːvi læst naɪt/', 'Passado irregular de "see": "saw". "Last night" = ontem à noite.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"saw","pos":"verb","ipa":"/sɔː/","gloss":"viu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"movie","pos":"noun","ipa":"/ˈmuːvi/","gloss":"filme"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-07-03', 'lesson-essential-verbs-a1-07', 3, 'sentence', 'I will see you tomorrow.', 'Vejo você amanhã.', '/aɪ wɪl siː juː təˈmɑːroʊ/', 'Futuro com "will". Na fala vira "I''ll see you" ou só "See you tomorrow".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-07-04', 'lesson-essential-verbs-a1-07', 4, 'sentence', 'Have you seen my keys?', 'Você viu minhas chaves?', '/hæv juː siːn maɪ kiːz/', 'Present perfect: have + "seen". Usado quando o resultado importa agora (as chaves sumiram).', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"seen","pos":"verb","ipa":"/siːn/","gloss":"visto"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-07-05', 'lesson-essential-verbs-a1-07', 5, 'sentence', 'She comes to work by train.', 'Ela vem para o trabalho de trem.', '/ʃiː kʌmz tuː wɜːrk baɪ treɪn/', 'Presente de "come" (vir) com he/she/it: "comes".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"comes","pos":"verb","ipa":"/kʌmz/","gloss":"vem (he/she/it)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"train","pos":"noun","ipa":"/treɪn/","gloss":"trem"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-07-06', 'lesson-essential-verbs-a1-07', 6, 'sentence', 'They came to the party late.', 'Eles chegaram tarde na festa.', '/ðeɪ keɪm tuː ðə ˈpɑːrti leɪt/', 'Passado irregular: "came".', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"came","pos":"verb","ipa":"/keɪm/","gloss":"veio"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"party","pos":"noun","ipa":"/ˈpɑːrti/","gloss":"festa"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-07-07', 'lesson-essential-verbs-a1-07', 7, 'sentence', 'Will you come with us?', 'Você vem com a gente?', '/wɪl juː kʌm wɪð ʌs/', 'Futuro em pergunta: "will" antes do sujeito. Convite natural.', '[]'::jsonb, '[{"surface":"Will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-07-08', 'lesson-essential-verbs-a1-07', 8, 'sentence', 'Spring has come early this year.', 'A primavera chegou cedo este ano.', '/sprɪŋ hæz kʌm ˈɜːrli ðɪs jɪr/', 'Particípio de "come" é igual à base: "come". "This year" combina com present perfect.', '[]'::jsonb, '[{"surface":"Spring","pos":"noun","ipa":"/sprɪŋ/","gloss":"primavera"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-08', 'course-essential-verbs-a1', 8, 'want e look', 'Querer e olhar/parecer nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-08-01', 'lesson-essential-verbs-a1-08', 1, 'sentence', 'I want a new job.', 'Eu quero um emprego novo.', '/aɪ wɑːnt ə nuː dʒɑːb/', '"Want" + substantivo, ou "want to" + verbo: "I want to travel".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-08-02', 'lesson-essential-verbs-a1-08', 2, 'sentence', 'He wanted to call you.', 'Ele queria ligar para você.', '/hiː ˈwɑːntɪd tuː kɔːl juː/', 'Passado regular: "wanted". O "-ed" soa /ɪd/ depois de "t".', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"wanted","pos":"verb","ipa":"/ˈwɑːntɪd/","gloss":"quis, queria"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-08-03', 'lesson-essential-verbs-a1-08', 3, 'sentence', 'You will want to see this.', 'Você vai querer ver isto.', '/juː wɪl wɑːnt tuː siː ðɪs/', 'Futuro com "will". Expressão comum para chamar a atenção.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-08-04', 'lesson-essential-verbs-a1-08', 4, 'sentence', 'I have always wanted to visit Japan.', 'Sempre quis visitar o Japão.', '/aɪ hæv ˈɔːlweɪz ˈwɑːntɪd tuː ˈvɪzɪt dʒəˈpæn/', 'Present perfect + "always": desejo que vem do passado até hoje.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"always","pos":"adverb","ipa":"/ˈɔːlweɪz/","gloss":"sempre"},{"surface":"wanted","pos":"verb","ipa":"/ˈwɑːntɪd/","gloss":"quis, queria"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"visit","pos":"noun","ipa":"/ˈvɪzɪt/","gloss":"visita"},{"surface":"Japan","pos":"proper noun","ipa":"/dʒəˈpæn/","gloss":"Japão"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-08-05', 'lesson-essential-verbs-a1-08', 5, 'sentence', 'You look tired.', 'Você parece cansado.', '/juː lʊk ˈtaɪərd/', '"Look" + adjetivo = parecer. "Look at" + objeto = olhar para.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-08-06', 'lesson-essential-verbs-a1-08', 6, 'sentence', 'She looked at the map.', 'Ela olhou o mapa.', '/ʃiː lʊkt æt ðə mæp/', 'Passado regular: "looked" (o "-ed" soa /t/). "Look at" = olhar para.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"looked","pos":"verb","ipa":"/lʊkt/","gloss":"olhou, pareceu"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"map","pos":"noun","ipa":"/mæp/","gloss":"mapa"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-08-07', 'lesson-essential-verbs-a1-08', 7, 'sentence', 'I will look for it later.', 'Vou procurar depois.', '/aɪ wɪl lʊk fɔːr ɪt ˈleɪtər/', '"Look for" = procurar (phrasal verb). Futuro com "will".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-08-08', 'lesson-essential-verbs-a1-08', 8, 'sentence', 'I''ve looked everywhere.', 'Já procurei em todo lugar.', '/aɪv lʊkt ˈɛvriwɛr/', 'Present perfect: "have looked". "Everywhere" = em todo lugar.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"looked","pos":"verb","ipa":"/lʊkt/","gloss":"olhou, pareceu"},{"surface":"everywhere","pos":"adverb","ipa":"/ˈɛvriwɛr/","gloss":"em todo lugar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-09', 'course-essential-verbs-a1', 9, 'use e find', 'Usar e encontrar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-09-01', 'lesson-essential-verbs-a1-09', 1, 'sentence', 'I use my phone for everything.', 'Uso o celular para tudo.', '/aɪ juːz maɪ foʊn fɔːr ˈɛvriθɪŋ/', 'Presente de "use" (verbo): o "s" soa /z/: /juːz/.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"use","pos":"verb","ipa":"/juːz/","gloss":"usar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"phone","pos":"noun","ipa":"/foʊn/","gloss":"celular, telefone"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"everything","pos":"pronoun","ipa":"/ˈɛvriθɪŋ/","gloss":"tudo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-09-02', 'lesson-essential-verbs-a1-09', 2, 'sentence', 'We used a map to find the hotel.', 'Usamos um mapa para achar o hotel.', '/wiː juːzd ə mæp tuː faɪnd ðə hoʊˈtɛl/', 'Passado regular: "used". Não confunda com "used to" (costumava).', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"used","pos":"verb","ipa":"/juːzd/","gloss":"usou, usado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"map","pos":"noun","ipa":"/mæp/","gloss":"mapa"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"find","pos":"verb","ipa":"/faɪnd/","gloss":"encontrar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"hotel","pos":"noun","ipa":"/hoʊˈtɛl/","gloss":"hotel"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-09-03', 'lesson-essential-verbs-a1-09', 3, 'sentence', 'Will you use the car today?', 'Você vai usar o carro hoje?', '/wɪl juː juːz ðə kɑːr təˈdeɪ/', 'Futuro em pergunta com "will".', '[]'::jsonb, '[{"surface":"Will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"use","pos":"verb","ipa":"/juːz/","gloss":"usar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-09-04', 'lesson-essential-verbs-a1-09', 4, 'sentence', 'I''ve never used this app.', 'Nunca usei este aplicativo.', '/aɪv ˈnɛvər juːzd ðɪs æp/', 'Present perfect + "never": experiência que nunca aconteceu.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"used","pos":"verb","ipa":"/juːzd/","gloss":"usou, usado"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"app","pos":"noun","ipa":"/æp/","gloss":"aplicativo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-09-05', 'lesson-essential-verbs-a1-09', 5, 'sentence', 'I always find good deals online.', 'Sempre acho boas ofertas na internet.', '/aɪ ˈɔːlweɪz faɪnd ɡʊd diːlz ˌɑːnˈlaɪn/', '"Find" = encontrar, achar. "Deal" = oferta, negócio.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"always","pos":"adverb","ipa":"/ˈɔːlweɪz/","gloss":"sempre"},{"surface":"find","pos":"verb","ipa":"/faɪnd/","gloss":"encontrar"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"deals","pos":"noun","ipa":"/diːlz/","gloss":"ofertas, negócios"},{"surface":"online","pos":"adverb","ipa":"/ˌɑːnˈlaɪn/","gloss":"na internet"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-09-06', 'lesson-essential-verbs-a1-09', 6, 'sentence', 'She found her passport in the car.', 'Ela achou o passaporte no carro.', '/ʃiː faʊnd hɜːr ˈpæspɔːrt ɪn ðə kɑːr/', 'Passado irregular: "found".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"passport","pos":"noun","ipa":"/ˈpæspɔːrt/","gloss":"passaporte"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-09-07', 'lesson-essential-verbs-a1-09', 7, 'sentence', 'You''ll find it on the second floor.', 'Você vai encontrar no segundo andar.', '/juːl faɪnd ɪt ɑːn ðə ˈsɛkənd flɔːr/', 'Futuro com "will" contraído: "you''ll". Muito usado para dar direções.', '[]'::jsonb, '[{"surface":"You''ll","pos":"pronoun","ipa":"/juːl/","gloss":"você vai (you will)"},{"surface":"find","pos":"verb","ipa":"/faɪnd/","gloss":"encontrar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"second","pos":"adjective","ipa":"/ˈsɛkənd/","gloss":"segundo"},{"surface":"floor","pos":"noun","ipa":"/flɔːr/","gloss":"andar; chão"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-09-08', 'lesson-essential-verbs-a1-09', 8, 'sentence', 'Have you found a place to stay?', 'Você já achou um lugar para ficar?', '/hæv juː faʊnd ə pleɪs tuː steɪ/', 'Present perfect: "have found". Pergunta sobre algo que pode já ter acontecido.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"place","pos":"noun","ipa":"/pleɪs/","gloss":"lugar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"stay","pos":"verb","ipa":"/steɪ/","gloss":"ficar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-10', 'course-essential-verbs-a1', 10, 'give e tell', 'Dar e contar/dizer nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-10-01', 'lesson-essential-verbs-a1-10', 1, 'sentence', 'My parents give me advice.', 'Meus pais me dão conselhos.', '/maɪ ˈpɛrənts ɡɪv miː ədˈvaɪs/', '"Give" + pessoa + coisa: "give me advice". "Advice" é incontável.', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"parents","pos":"noun","ipa":"/ˈpɛrənts/","gloss":"pais (pai e mãe)"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"advice","pos":"noun","ipa":"/ədˈvaɪs/","gloss":"conselho(s)"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-10-02', 'lesson-essential-verbs-a1-10', 2, 'sentence', 'He gave me his number.', 'Ele me deu o número dele.', '/hiː ɡeɪv miː hɪz ˈnʌmbər/', 'Passado irregular: "gave".', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"gave","pos":"verb","ipa":"/ɡeɪv/","gloss":"deu"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"number","pos":"noun","ipa":"/ˈnʌmbər/","gloss":"número"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-10-03', 'lesson-essential-verbs-a1-10', 3, 'sentence', 'I''ll give it back tomorrow.', 'Devolvo amanhã.', '/aɪl ɡɪv ɪt bæk təˈmɑːroʊ/', '"Give back" = devolver (phrasal verb). Objeto no meio: "give it back".', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-10-04', 'lesson-essential-verbs-a1-10', 4, 'sentence', 'She has given up smoking.', 'Ela parou de fumar.', '/ʃiː hæz ˈɡɪvən ʌp ˈsmoʊkɪŋ/', '"Give up" = desistir, largar um hábito. Particípio irregular: "given".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"given","pos":"verb","ipa":"/ˈɡɪvən/","gloss":"dado"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"smoking","pos":"noun","ipa":"/ˈsmoʊkɪŋ/","gloss":"fumar, o hábito de fumar"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-10-05', 'lesson-essential-verbs-a1-10', 5, 'sentence', 'Tell me about your trip.', 'Me conte sobre a sua viagem.', '/tɛl miː əˈbaʊt jʊr trɪp/', '"Tell" + pessoa: "tell me". "Say" não leva a pessoa direto: "say to me".', '[]'::jsonb, '[{"surface":"Tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"trip","pos":"noun","ipa":"/trɪp/","gloss":"viagem"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-10-06', 'lesson-essential-verbs-a1-10', 6, 'sentence', 'She told me the truth.', 'Ela me contou a verdade.', '/ʃiː toʊld miː ðə truːθ/', 'Passado irregular: "told". "Tell the truth" = dizer a verdade.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"truth","pos":"noun","ipa":"/truːθ/","gloss":"verdade"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-10-07', 'lesson-essential-verbs-a1-10', 7, 'sentence', 'I won''t tell anyone.', 'Não vou contar para ninguém.', '/aɪ woʊnt tɛl ˈɛniwʌn/', 'Futuro negativo: "won''t" = "will not".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"won''t","pos":"modal verb","ipa":"/woʊnt/","gloss":"não vai (will not)"},{"surface":"tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"anyone","pos":"pronoun","ipa":"/ˈɛniwʌn/","gloss":"alguém, ninguém"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-10-08', 'lesson-essential-verbs-a1-10', 8, 'sentence', 'Have you told your boss?', 'Você já contou para o seu chefe?', '/hæv juː toʊld jʊr bɔːs/', 'Present perfect: "have told". Particípio igual ao passado.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"boss","pos":"noun","ipa":"/bɔːs/","gloss":"chefe"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-11', 'course-essential-verbs-a1', 11, 'work e call', 'Trabalhar/funcionar e ligar/chamar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-11-01', 'lesson-essential-verbs-a1-11', 1, 'sentence', 'I work from home on Fridays.', 'Trabalho de casa às sextas.', '/aɪ wɜːrk frʌm hoʊm ɑːn ˈfraɪdeɪz/', '"Work from home" = trabalhar remoto. "Work" também é funcionar: "it works".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"Fridays","pos":"proper noun","ipa":"/ˈfraɪdeɪz/","gloss":"sextas-feiras"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-11-02', 'lesson-essential-verbs-a1-11', 2, 'sentence', 'He worked there for five years.', 'Ele trabalhou lá por cinco anos.', '/hiː wɜːrkt ðɛr fɔːr faɪv jɪrz/', 'Passado regular: "worked". Com "for" + período terminado, passado simples.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-11-03', 'lesson-essential-verbs-a1-11', 3, 'sentence', 'Will this plan work?', 'Esse plano vai dar certo?', '/wɪl ðɪs plæn wɜːrk/', '"Work" = funcionar, dar certo. Futuro em pergunta.', '[]'::jsonb, '[{"surface":"Will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"plan","pos":"noun","ipa":"/plæn/","gloss":"plano"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-11-04', 'lesson-essential-verbs-a1-11', 4, 'sentence', 'I have worked here since January.', 'Trabalho aqui desde janeiro.', '/aɪ hæv wɜːrkt hɪr sɪns ˈdʒænjuɛri/', 'Present perfect + "since": começou no passado e continua. Em português usamos o presente.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"since","pos":"preposition","ipa":"/sɪns/","gloss":"desde"},{"surface":"January","pos":"proper noun","ipa":"/ˈdʒænjuɛri/","gloss":"janeiro"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-11-05', 'lesson-essential-verbs-a1-11', 5, 'sentence', 'Call me when you arrive.', 'Me liga quando chegar.', '/kɔːl miː wɛn juː əˈraɪv/', '"Call" = ligar. Depois de "when" o inglês usa presente ("arrive").', '[]'::jsonb, '[{"surface":"Call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"arrive","pos":"verb","ipa":"/əˈraɪv/","gloss":"chegar"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-11-06', 'lesson-essential-verbs-a1-11', 6, 'sentence', 'I called the hotel yesterday.', 'Liguei para o hotel ontem.', '/aɪ kɔːld ðə hoʊˈtɛl ˈjɛstərdeɪ/', 'Passado regular: "called". "Call" não leva "to": "call the hotel".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"hotel","pos":"noun","ipa":"/hoʊˈtɛl/","gloss":"hotel"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-11-07', 'lesson-essential-verbs-a1-11', 7, 'sentence', 'I''ll call you back.', 'Eu te ligo de volta.', '/aɪl kɔːl juː bæk/', '"Call back" = retornar a ligação. Objeto no meio: "call you back".', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-11-08', 'lesson-essential-verbs-a1-11', 8, 'sentence', 'Has anyone called?', 'Alguém ligou?', '/hæz ˈɛniwʌn kɔːld/', 'Present perfect em pergunta com "has": "anyone" pede verbo no singular.', '[]'::jsonb, '[{"surface":"Has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"anyone","pos":"pronoun","ipa":"/ˈɛniwʌn/","gloss":"alguém, ninguém"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-12', 'course-essential-verbs-a1', 12, 'Revisão: módulo 2', 'Base, passado e particípio dos 10 verbos do módulo 2.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-12-01', 'lesson-essential-verbs-a1-12', 1, 'verb_forms', 'see saw seen', 'ver', '/siː sɔː siːn/', 'Base "see" · passado "saw" · particípio "seen". Irregular.', '[]'::jsonb, '[{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"saw","pos":"verb","ipa":"/sɔː/","gloss":"viu"},{"surface":"seen","pos":"verb","ipa":"/siːn/","gloss":"visto"}]'::jsonb, 'I saw a great movie last night.', 'Vi um filme ótimo ontem à noite.'),
  ('unit-essential-verbs-a1-12-02', 'lesson-essential-verbs-a1-12', 2, 'verb_forms', 'come came come', 'vir', '/kʌm keɪm kʌm/', 'Base "come" · passado "came" · particípio "come" (igual à base).', '[]'::jsonb, '[{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"came","pos":"verb","ipa":"/keɪm/","gloss":"veio"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"}]'::jsonb, 'They came to the party late.', 'Eles chegaram tarde na festa.'),
  ('unit-essential-verbs-a1-12-03', 'lesson-essential-verbs-a1-12', 3, 'verb_forms', 'want wanted wanted', 'querer', '/wɑːnt ˈwɑːntɪd ˈwɑːntɪd/', 'Regular: passado e particípio com "-ed" (/ɪd/ depois de "t").', '[]'::jsonb, '[{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"wanted","pos":"verb","ipa":"/ˈwɑːntɪd/","gloss":"quis, queria"},{"surface":"wanted","pos":"verb","ipa":"/ˈwɑːntɪd/","gloss":"quis, queria"}]'::jsonb, 'He wanted to call you.', 'Ele queria ligar para você.'),
  ('unit-essential-verbs-a1-12-04', 'lesson-essential-verbs-a1-12', 4, 'verb_forms', 'look looked looked', 'olhar, parecer', '/lʊk lʊkt lʊkt/', 'Regular: "-ed" soa /t/ depois de "k".', '[]'::jsonb, '[{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"looked","pos":"verb","ipa":"/lʊkt/","gloss":"olhou, pareceu"},{"surface":"looked","pos":"verb","ipa":"/lʊkt/","gloss":"olhou, pareceu"}]'::jsonb, 'She looked at the map.', 'Ela olhou o mapa.'),
  ('unit-essential-verbs-a1-12-05', 'lesson-essential-verbs-a1-12', 5, 'verb_forms', 'use used used', 'usar', '/juːz juːzd juːzd/', 'Regular: "-d" soa /d/. "Used to" (costumava) é outra estrutura.', '[]'::jsonb, '[{"surface":"use","pos":"verb","ipa":"/juːz/","gloss":"usar"},{"surface":"used","pos":"verb","ipa":"/juːzd/","gloss":"usou, usado"},{"surface":"used","pos":"verb","ipa":"/juːzd/","gloss":"usou, usado"}]'::jsonb, 'We used a map to find the hotel.', 'Usamos um mapa para achar o hotel.'),
  ('unit-essential-verbs-a1-12-06', 'lesson-essential-verbs-a1-12', 6, 'verb_forms', 'find found found', 'encontrar', '/faɪnd faʊnd faʊnd/', 'Base "find" · passado e particípio "found".', '[]'::jsonb, '[{"surface":"find","pos":"verb","ipa":"/faɪnd/","gloss":"encontrar"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"}]'::jsonb, 'She found her passport in the car.', 'Ela achou o passaporte no carro.'),
  ('unit-essential-verbs-a1-12-07', 'lesson-essential-verbs-a1-12', 7, 'verb_forms', 'give gave given', 'dar', '/ɡɪv ɡeɪv ˈɡɪvən/', 'Base "give" · passado "gave" · particípio "given".', '[]'::jsonb, '[{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"gave","pos":"verb","ipa":"/ɡeɪv/","gloss":"deu"},{"surface":"given","pos":"verb","ipa":"/ˈɡɪvən/","gloss":"dado"}]'::jsonb, 'He gave me his number.', 'Ele me deu o número dele.'),
  ('unit-essential-verbs-a1-12-08', 'lesson-essential-verbs-a1-12', 8, 'verb_forms', 'tell told told', 'contar, dizer', '/tɛl toʊld toʊld/', 'Base "tell" · passado e particípio "told".', '[]'::jsonb, '[{"surface":"tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"}]'::jsonb, 'She told me the truth.', 'Ela me contou a verdade.'),
  ('unit-essential-verbs-a1-12-09', 'lesson-essential-verbs-a1-12', 9, 'verb_forms', 'work worked worked', 'trabalhar, funcionar', '/wɜːrk wɜːrkt wɜːrkt/', 'Regular: "-ed" soa /t/.', '[]'::jsonb, '[{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"}]'::jsonb, 'He worked there for five years.', 'Ele trabalhou lá por cinco anos.'),
  ('unit-essential-verbs-a1-12-10', 'lesson-essential-verbs-a1-12', 10, 'verb_forms', 'call called called', 'ligar, chamar', '/kɔːl kɔːld kɔːld/', 'Regular: "-ed" soa /d/.', '[]'::jsonb, '[{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"}]'::jsonb, 'I called the hotel yesterday.', 'Liguei para o hotel ontem.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
