-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-essential-verbs-a1', 'essential-verbs', 'Verbos Essenciais', 'Os verbos mais usados em frases separadas por tempo: presente, passado, futuro e present perfect.', 'Cada verbo aparece em quatro frases reais, uma por tempo verbal, com a explicação gramatical de cada forma. No fim de cada módulo, você revisa as três formas (base, passado e particípio).', 'A1', 'grammar', 12, 'fundamentos', 3, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-31', 'course-essential-verbs-a1', 31, 'lose e pay', 'Perder e pagar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-31-01', 'lesson-essential-verbs-a1-31', 1, 'sentence', 'I always lose my keys.', 'Eu sempre perco minhas chaves.', '/aɪ ˈɔːlweɪz luːz maɪ kiːz/', 'Presente de "lose" (perder). Pronúncia /luːz/; "loose" = solto.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"always","pos":"adverb","ipa":"/ˈɔːlweɪz/","gloss":"sempre"},{"surface":"lose","pos":"verb","ipa":"/luːz/","gloss":"perder"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-31-02', 'lesson-essential-verbs-a1-31', 2, 'sentence', 'We lost the game.', 'Perdemos o jogo.', '/wiː lɔːst ðə ɡeɪm/', 'Passado irregular: "lost".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"game","pos":"noun","ipa":"/ɡeɪm/","gloss":"jogo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-31-03', 'lesson-essential-verbs-a1-31', 3, 'sentence', 'You won''t lose anything.', 'Você não vai perder nada.', '/juː woʊnt luːz ˈɛniθɪŋ/', 'Futuro negativo: "won''t" + base.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"won''t","pos":"modal verb","ipa":"/woʊnt/","gloss":"não vai (will not)"},{"surface":"lose","pos":"verb","ipa":"/luːz/","gloss":"perder"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-31-04', 'lesson-essential-verbs-a1-31', 4, 'sentence', 'I''ve lost my wallet.', 'Perdi minha carteira (e ainda não achei).', '/aɪv lɔːst maɪ ˈwɑːlɪt/', 'Present perfect: resultado agora.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"wallet","pos":"noun","ipa":"/ˈwɑːlɪt/","gloss":"carteira"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-31-05', 'lesson-essential-verbs-a1-31', 5, 'sentence', 'I pay my rent every month.', 'Pago meu aluguel todo mês.', '/aɪ peɪ maɪ rɛnt ˈɛvri mʌnθ/', '"Pay" = pagar. "Rent" = aluguel.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"pay","pos":"verb","ipa":"/peɪ/","gloss":"pagar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"rent","pos":"verb","ipa":"/rɛnt/","gloss":"alugar"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-31-06', 'lesson-essential-verbs-a1-31', 6, 'sentence', 'She paid for the tickets.', 'Ela pagou as passagens.', '/ʃiː peɪd fɔːr ðə ˈtɪkɪts/', 'Passado irregular: "paid". "Pay for" + o que se compra.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"paid","pos":"verb","ipa":"/peɪd/","gloss":"pagou"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"tickets","pos":"noun","ipa":"/ˈtɪkɪts/","gloss":"ingressos"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-31-07', 'lesson-essential-verbs-a1-31', 7, 'sentence', 'I''ll pay you back next week.', 'Te pago semana que vem.', '/aɪl peɪ juː bæk nɛkst wiːk/', '"Pay back" = devolver dinheiro.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"pay","pos":"verb","ipa":"/peɪ/","gloss":"pagar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-31-08', 'lesson-essential-verbs-a1-31', 8, 'sentence', 'Have you paid the bill?', 'Você já pagou a conta?', '/hæv juː peɪd ðə bɪl/', 'Present perfect em pergunta.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"paid","pos":"verb","ipa":"/peɪd/","gloss":"pagou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bill","pos":"noun","ipa":"/bɪl/","gloss":"conta"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-32', 'course-essential-verbs-a1', 32, 'meet e include', 'Encontrar/conhecer e incluir nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-32-01', 'lesson-essential-verbs-a1-32', 1, 'sentence', 'We meet every Friday.', 'A gente se encontra toda sexta.', '/wiː miːt ˈɛvri ˈfraɪdeɪ/', '"Meet" = encontrar-se (combinado).', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"Friday","pos":"proper noun","ipa":"/ˈfraɪdeɪ/","gloss":"sexta-feira"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-32-02', 'lesson-essential-verbs-a1-32', 2, 'sentence', 'I met my wife at work.', 'Conheci minha esposa no trabalho.', '/aɪ mɛt maɪ waɪf æt wɜːrk/', 'Passado irregular: "met". "Meet" também é conhecer alguém.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"wife","pos":"noun","ipa":"/waɪf/","gloss":"esposa"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-32-03', 'lesson-essential-verbs-a1-32', 3, 'sentence', 'I''ll meet you at the station.', 'Te encontro na estação.', '/aɪl miːt juː æt ðə ˈsteɪʃən/', 'Futuro com "will".', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"station","pos":"noun","ipa":"/ˈsteɪʃən/","gloss":"estação"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-32-04', 'lesson-essential-verbs-a1-32', 4, 'sentence', 'Have you met my brother?', 'Você já conhece meu irmão?', '/hæv juː mɛt maɪ ˈbrʌðər/', 'Present perfect para apresentar alguém.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"brother","pos":"noun","ipa":"/ˈbrʌðər/","gloss":"irmão"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-32-05', 'lesson-essential-verbs-a1-32', 5, 'sentence', 'The price includes breakfast.', 'O preço inclui café da manhã.', '/ðə praɪs ɪnˈkluːdz ˈbrɛkfəst/', '"Include" = incluir. Com he/she/it: "includes".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"price","pos":"noun","ipa":"/praɪs/","gloss":"preço"},{"surface":"includes","pos":"verb","ipa":"/ɪnˈkluːdz/","gloss":"inclui"},{"surface":"breakfast","pos":"noun","ipa":"/ˈbrɛkfəst/","gloss":"café da manhã"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-32-06', 'lesson-essential-verbs-a1-32', 6, 'sentence', 'They included me in the plan.', 'Eles me incluíram no plano.', '/ðeɪ ɪnˈkluːdɪd miː ɪn ðə plæn/', 'Passado regular: "included".', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"included","pos":"adjective","ipa":"/ɪnˈkluːdɪd/","gloss":"incluído"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"plan","pos":"noun","ipa":"/plæn/","gloss":"plano"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-32-07', 'lesson-essential-verbs-a1-32', 7, 'sentence', 'The next version will include more lessons.', 'A próxima versão vai incluir mais aulas.', '/ðə nɛkst ˈvɜːrʒən wɪl ɪnˈkluːd mɔːr ˈlɛsənz/', 'Futuro com "will".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"version","pos":"noun","ipa":"/ˈvɜːrʒən/","gloss":"versão"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"include","pos":"verb","ipa":"/ɪnˈkluːd/","gloss":"incluir"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"lessons","pos":"noun","ipa":"/ˈlɛsənz/","gloss":"aulas"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-32-08', 'lesson-essential-verbs-a1-32', 8, 'sentence', 'I''ve included the report in the email.', 'Incluí o relatório no e-mail.', '/aɪv ɪnˈkluːdɪd ðə rɪˈpɔːrt ɪn ðə ˈiːmeɪl/', 'Present perfect: ação recente com resultado.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"included","pos":"adjective","ipa":"/ɪnˈkluːdɪd/","gloss":"incluído"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"report","pos":"verb","ipa":"/rɪˈpɔːrt/","gloss":"registrar, relatar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"email","pos":"noun","ipa":"/ˈiːmeɪl/","gloss":"e-mail"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-33', 'course-essential-verbs-a1', 33, 'continue e learn', 'Continuar e aprender nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-33-01', 'lesson-essential-verbs-a1-33', 1, 'sentence', 'The road continues for miles.', 'A estrada continua por quilômetros.', '/ðə roʊd kənˈtɪnjuːz fɔːr maɪlz/', '"Continue" com he/she/it: "continues". "Miles" = milhas.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"road","pos":"noun","ipa":"/roʊd/","gloss":"estrada"},{"surface":"continues","pos":"verb","ipa":"/kənˈtɪnjuːz/","gloss":"continua"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"miles","pos":"noun","ipa":"/maɪlz/","gloss":"milhas"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-33-02', 'lesson-essential-verbs-a1-33', 2, 'sentence', 'We continued after lunch.', 'Continuamos depois do almoço.', '/wiː kənˈtɪnjuːd ˈæftər lʌntʃ/', 'Passado regular: "continued".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"continued","pos":"verb","ipa":"/kənˈtɪnjuːd/","gloss":"continuou"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"lunch","pos":"noun","ipa":"/lʌntʃ/","gloss":"almoço"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-33-03', 'lesson-essential-verbs-a1-33', 3, 'sentence', 'Prices will continue to rise.', 'Os preços vão continuar subindo.', '/ˈpraɪsɪz wɪl kənˈtɪnjuː tuː raɪz/', '"Continue to" + verbo = continuar a.', '[]'::jsonb, '[{"surface":"Prices","pos":"noun","ipa":"/ˈpraɪsɪz/","gloss":"preços"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"continue","pos":"verb","ipa":"/kənˈtɪnjuː/","gloss":"continuar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"rise","pos":"verb","ipa":"/raɪz/","gloss":"subir"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-33-04', 'lesson-essential-verbs-a1-33', 4, 'sentence', 'It has continued to rain all week.', 'Continuou chovendo a semana toda.', '/ɪt hæz kənˈtɪnjuːd tuː reɪn ɔːl wiːk/', 'Present perfect: começou e continua.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"continued","pos":"verb","ipa":"/kənˈtɪnjuːd/","gloss":"continuou"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"rain","pos":"verb","ipa":"/reɪn/","gloss":"chover; chuva"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-33-05', 'lesson-essential-verbs-a1-33', 5, 'sentence', 'I learn a new word every day.', 'Aprendo uma palavra nova todo dia.', '/aɪ lɜːrn ə nuː wɜːrd ˈɛvri deɪ/', '"Learn" = aprender (quem aprende). "Teach" = ensinar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"learn","pos":"verb","ipa":"/lɜːrn/","gloss":"aprender"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"word","pos":"noun","ipa":"/wɜːrd/","gloss":"palavra"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-33-06', 'lesson-essential-verbs-a1-33', 6, 'sentence', 'She learned to swim as a child.', 'Ela aprendeu a nadar quando criança.', '/ʃiː lɜːrnd tuː swɪm æz ə tʃaɪld/', 'Passado: "learned" (EUA) ou "learnt" (Reino Unido).', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"learned","pos":"verb","ipa":"/lɜːrnd/","gloss":"aprendeu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"swim","pos":"verb","ipa":"/swɪm/","gloss":"nadar"},{"surface":"as","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"child","pos":"noun","ipa":"/tʃaɪld/","gloss":"criança, filho"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-33-07', 'lesson-essential-verbs-a1-33', 7, 'sentence', 'You will learn fast.', 'Você vai aprender rápido.', '/juː wɪl lɜːrn fæst/', '"Fast" = rápido (advérbio).', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"learn","pos":"verb","ipa":"/lɜːrn/","gloss":"aprender"},{"surface":"fast","pos":"adverb","ipa":"/fæst/","gloss":"rápido"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-33-08', 'lesson-essential-verbs-a1-33', 8, 'sentence', 'I''ve learned a lot this year.', 'Aprendi muito este ano.', '/aɪv lɜːrnd ə lɑːt ðɪs jɪr/', 'Present perfect + "this year".', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"learned","pos":"verb","ipa":"/lɜːrnd/","gloss":"aprendeu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lot","pos":"noun","ipa":"/lɑːt/","gloss":"muito (a lot)"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-34', 'course-essential-verbs-a1', 34, 'change e understand', 'Mudar/trocar e entender nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-34-01', 'lesson-essential-verbs-a1-34', 1, 'sentence', 'I change my password every month.', 'Mudo minha senha todo mês.', '/aɪ tʃeɪndʒ maɪ ˈpæswɜːrd ˈɛvri mʌnθ/', '"Change" = mudar, trocar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"password","pos":"noun","ipa":"/ˈpæswɜːrd/","gloss":"senha"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-34-02', 'lesson-essential-verbs-a1-34', 2, 'sentence', 'She changed her mind.', 'Ela mudou de ideia.', '/ʃiː tʃeɪndʒd hɜːr maɪnd/', '"Change your mind" = mudar de ideia.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"changed","pos":"verb","ipa":"/tʃeɪndʒd/","gloss":"mudou, mudado"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"mind","pos":"verb","ipa":"/maɪnd/","gloss":"se importar"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-34-03', 'lesson-essential-verbs-a1-34', 3, 'sentence', 'This will change everything.', 'Isso vai mudar tudo.', '/ðɪs wɪl tʃeɪndʒ ˈɛvriθɪŋ/', 'Futuro com "will".', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"},{"surface":"everything","pos":"pronoun","ipa":"/ˈɛvriθɪŋ/","gloss":"tudo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-34-04', 'lesson-essential-verbs-a1-34', 4, 'sentence', 'The city has changed a lot.', 'A cidade mudou muito.', '/ðə ˈsɪti hæz tʃeɪndʒd ə lɑːt/', 'Present perfect: mudança com efeito agora.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"city","pos":"noun","ipa":"/ˈsɪti/","gloss":"cidade"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"changed","pos":"verb","ipa":"/tʃeɪndʒd/","gloss":"mudou, mudado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lot","pos":"noun","ipa":"/lɑːt/","gloss":"muito (a lot)"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-34-05', 'lesson-essential-verbs-a1-34', 5, 'sentence', 'I understand what you mean.', 'Entendo o que você quer dizer.', '/aɪ ˌʌndərˈstænd wʌt juː miːn/', '"Understand" é verbo de estado: não vai para o contínuo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"mean","pos":"verb","ipa":"/miːn/","gloss":"significar, querer dizer"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-34-06', 'lesson-essential-verbs-a1-34', 6, 'sentence', 'I didn''t understand the question.', 'Não entendi a pergunta.', '/aɪ ˈdɪdənt ˌʌndərˈstænd ðə ˈkwɛstʃən/', 'Passado negativo: "didn''t" + base.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"question","pos":"noun","ipa":"/ˈkwɛstʃən/","gloss":"pergunta"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-34-07', 'lesson-essential-verbs-a1-34', 7, 'sentence', 'You will understand later.', 'Você vai entender depois.', '/juː wɪl ˌʌndərˈstænd ˈleɪtər/', 'Futuro com "will".', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-34-08', 'lesson-essential-verbs-a1-34', 8, 'sentence', 'Have you understood the rules?', 'Você entendeu as regras?', '/hæv juː ˌʌndərˈstʊd ðə ruːlz/', 'Particípio irregular: "understood".', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"understood","pos":"verb","ipa":"/ˌʌndərˈstʊd/","gloss":"entendeu"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"rules","pos":"noun","ipa":"/ruːlz/","gloss":"regras"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-35', 'course-essential-verbs-a1', 35, 'lead e set', 'Liderar/levar a e definir/pôr nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-35-01', 'lesson-essential-verbs-a1-35', 1, 'sentence', 'She leads a team of ten.', 'Ela lidera uma equipe de dez.', '/ʃiː liːdz ə tiːm ʌv tɛn/', '"Lead" /liːd/ = liderar.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"leads","pos":"verb","ipa":"/liːdz/","gloss":"lidera"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-35-02', 'lesson-essential-verbs-a1-35', 2, 'sentence', 'He led the project last year.', 'Ele liderou o projeto no ano passado.', '/hiː lɛd ðə ˈprɑːdʒɛkt læst jɪr/', 'Passado irregular: "led" /lɛd/.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"led","pos":"verb","ipa":"/lɛd/","gloss":"liderou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"project","pos":"noun","ipa":"/ˈprɑːdʒɛkt/","gloss":"projeto"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-35-03', 'lesson-essential-verbs-a1-35', 3, 'sentence', 'This road will lead you to the beach.', 'Esta estrada vai te levar à praia.', '/ðɪs roʊd wɪl liːd juː tuː ðə biːtʃ/', '"Lead to" = levar a.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"road","pos":"noun","ipa":"/roʊd/","gloss":"estrada"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"lead","pos":"verb","ipa":"/liːd/","gloss":"liderar, levar a"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"beach","pos":"noun","ipa":"/biːtʃ/","gloss":"praia"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-35-04', 'lesson-essential-verbs-a1-35', 4, 'sentence', 'Small changes have led to big results.', 'Pequenas mudanças levaram a grandes resultados.', '/smɔːl ˈtʃeɪndʒɪz hæv lɛd tuː bɪɡ rɪˈzʌlts/', 'Particípio: "led".', '[]'::jsonb, '[{"surface":"Small","pos":"adjective","ipa":"/smɔːl/","gloss":"pequeno"},{"surface":"changes","pos":"noun","ipa":"/ˈtʃeɪndʒɪz/","gloss":"mudanças"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"led","pos":"verb","ipa":"/lɛd/","gloss":"liderou"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"big","pos":"adjective","ipa":"/bɪɡ/","gloss":"grande"},{"surface":"results","pos":"noun","ipa":"/rɪˈzʌlts/","gloss":"resultados"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-35-05', 'lesson-essential-verbs-a1-35', 5, 'sentence', 'I set my alarm for six.', 'Coloco o despertador para as seis.', '/aɪ sɛt maɪ əˈlɑːrm fɔːr sɪks/', '"Set" = programar, pôr. Base, passado e particípio iguais.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"alarm","pos":"noun","ipa":"/əˈlɑːrm/","gloss":"despertador, alarme"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"six","pos":"numeral","ipa":"/sɪks/","gloss":"seis"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-35-06', 'lesson-essential-verbs-a1-35', 6, 'sentence', 'We set a goal last month.', 'Definimos uma meta no mês passado.', '/wiː sɛt ə ɡoʊl læst mʌnθ/', 'Passado igual à base: "set".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"goal","pos":"noun","ipa":"/ɡoʊl/","gloss":"meta"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-35-07', 'lesson-essential-verbs-a1-35', 7, 'sentence', 'I''ll set the table.', 'Eu ponho a mesa.', '/aɪl sɛt ðə ˈteɪbəl/', '"Set the table" = pôr a mesa.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"table","pos":"noun","ipa":"/ˈteɪbəl/","gloss":"mesa"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-35-08', 'lesson-essential-verbs-a1-35', 8, 'sentence', 'Have you set a date for the wedding?', 'Vocês já marcaram a data do casamento?', '/hæv juː sɛt ə deɪt fɔːr ðə ˈwɛdɪŋ/', '"Set a date" = marcar a data.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"date","pos":"noun","ipa":"/deɪt/","gloss":"data"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"wedding","pos":"noun","ipa":"/ˈwɛdɪŋ/","gloss":"casamento"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-36', 'course-essential-verbs-a1', 36, 'Revisão: módulo 6', 'Base, passado e particípio dos 10 verbos do módulo 6.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-36-01', 'lesson-essential-verbs-a1-36', 1, 'verb_forms', 'lose lost lost', 'perder', '/luːz lɔːst lɔːst/', 'Base "lose" · passado e particípio "lost".', '[]'::jsonb, '[{"surface":"lose","pos":"verb","ipa":"/luːz/","gloss":"perder"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"}]'::jsonb, 'We lost the game.', 'Perdemos o jogo.'),
  ('unit-essential-verbs-a1-36-02', 'lesson-essential-verbs-a1-36', 2, 'verb_forms', 'pay paid paid', 'pagar', '/peɪ peɪd peɪd/', 'Base "pay" · passado e particípio "paid" (não "payed").', '[]'::jsonb, '[{"surface":"pay","pos":"verb","ipa":"/peɪ/","gloss":"pagar"},{"surface":"paid","pos":"verb","ipa":"/peɪd/","gloss":"pagou"},{"surface":"paid","pos":"verb","ipa":"/peɪd/","gloss":"pagou"}]'::jsonb, 'She paid for the tickets.', 'Ela pagou as passagens.'),
  ('unit-essential-verbs-a1-36-03', 'lesson-essential-verbs-a1-36', 3, 'verb_forms', 'meet met met', 'encontrar, conhecer', '/miːt mɛt mɛt/', 'Base "meet" · passado e particípio "met".', '[]'::jsonb, '[{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"}]'::jsonb, 'I met my wife at work.', 'Conheci minha esposa no trabalho.'),
  ('unit-essential-verbs-a1-36-04', 'lesson-essential-verbs-a1-36', 4, 'verb_forms', 'include included included', 'incluir', '/ɪnˈkluːd ɪnˈkluːdɪd ɪnˈkluːdɪd/', 'Regular.', '[]'::jsonb, '[{"surface":"include","pos":"verb","ipa":"/ɪnˈkluːd/","gloss":"incluir"},{"surface":"included","pos":"adjective","ipa":"/ɪnˈkluːdɪd/","gloss":"incluído"},{"surface":"included","pos":"adjective","ipa":"/ɪnˈkluːdɪd/","gloss":"incluído"}]'::jsonb, 'They included me in the plan.', 'Eles me incluíram no plano.'),
  ('unit-essential-verbs-a1-36-05', 'lesson-essential-verbs-a1-36', 5, 'verb_forms', 'continue continued continued', 'continuar', '/kənˈtɪnjuː kənˈtɪnjuːd kənˈtɪnjuːd/', 'Regular.', '[]'::jsonb, '[{"surface":"continue","pos":"verb","ipa":"/kənˈtɪnjuː/","gloss":"continuar"},{"surface":"continued","pos":"verb","ipa":"/kənˈtɪnjuːd/","gloss":"continuou"},{"surface":"continued","pos":"verb","ipa":"/kənˈtɪnjuːd/","gloss":"continuou"}]'::jsonb, 'We continued after lunch.', 'Continuamos depois do almoço.'),
  ('unit-essential-verbs-a1-36-06', 'lesson-essential-verbs-a1-36', 6, 'verb_forms', 'set set set', 'pôr, definir', '/sɛt sɛt sɛt/', 'As três formas são iguais.', '[]'::jsonb, '[{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"},{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"},{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"}]'::jsonb, 'We set a goal last month.', 'Definimos uma meta no mês passado.'),
  ('unit-essential-verbs-a1-36-07', 'lesson-essential-verbs-a1-36', 7, 'verb_forms', 'learn learned learned', 'aprender', '/lɜːrn lɜːrnd lɜːrnd/', 'Regular nos EUA; no Reino Unido também "learnt".', '[]'::jsonb, '[{"surface":"learn","pos":"verb","ipa":"/lɜːrn/","gloss":"aprender"},{"surface":"learned","pos":"verb","ipa":"/lɜːrnd/","gloss":"aprendeu"},{"surface":"learned","pos":"verb","ipa":"/lɜːrnd/","gloss":"aprendeu"}]'::jsonb, 'She learned to swim as a child.', 'Ela aprendeu a nadar quando criança.'),
  ('unit-essential-verbs-a1-36-08', 'lesson-essential-verbs-a1-36', 8, 'verb_forms', 'change changed changed', 'mudar', '/tʃeɪndʒ tʃeɪndʒd tʃeɪndʒd/', 'Regular.', '[]'::jsonb, '[{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"},{"surface":"changed","pos":"verb","ipa":"/tʃeɪndʒd/","gloss":"mudou, mudado"},{"surface":"changed","pos":"verb","ipa":"/tʃeɪndʒd/","gloss":"mudou, mudado"}]'::jsonb, 'She changed her mind.', 'Ela mudou de ideia.'),
  ('unit-essential-verbs-a1-36-09', 'lesson-essential-verbs-a1-36', 9, 'verb_forms', 'lead led led', 'liderar', '/liːd lɛd lɛd/', 'Base "lead" /liːd/ · passado e particípio "led" /lɛd/.', '[]'::jsonb, '[{"surface":"lead","pos":"verb","ipa":"/liːd/","gloss":"liderar, levar a"},{"surface":"led","pos":"verb","ipa":"/lɛd/","gloss":"liderou"},{"surface":"led","pos":"verb","ipa":"/lɛd/","gloss":"liderou"}]'::jsonb, 'He led the project last year.', 'Ele liderou o projeto no ano passado.'),
  ('unit-essential-verbs-a1-36-10', 'lesson-essential-verbs-a1-36', 10, 'verb_forms', 'understand understood understood', 'entender', '/ˌʌndərˈstænd ˌʌndərˈstʊd ˌʌndərˈstʊd/', 'Base "understand" · passado e particípio "understood".', '[]'::jsonb, '[{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"understood","pos":"verb","ipa":"/ˌʌndərˈstʊd/","gloss":"entendeu"},{"surface":"understood","pos":"verb","ipa":"/ˌʌndərˈstʊd/","gloss":"entendeu"}]'::jsonb, 'I didn''t understand the question.', 'Não entendi a pergunta.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-37', 'course-essential-verbs-a1', 37, 'watch e follow', 'Assistir e seguir nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-37-01', 'lesson-essential-verbs-a1-37', 1, 'sentence', 'I watch the news every night.', 'Assisto ao jornal toda noite.', '/aɪ wɑːtʃ ðə nuːz ˈɛvri naɪt/', '"Watch" = assistir com atenção (TV, jogo). Com he/she/it: "watches".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"watch","pos":"noun","ipa":"/wɑːtʃ/","gloss":"relógio de pulso"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"news","pos":"noun","ipa":"/nuːz/","gloss":"notícia(s)"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-37-02', 'lesson-essential-verbs-a1-37', 2, 'sentence', 'We watched a movie yesterday.', 'Assistimos a um filme ontem.', '/wiː wɑːtʃt ə ˈmuːvi ˈjɛstərdeɪ/', 'Passado regular: "watched" (/t/).', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"watched","pos":"verb","ipa":"/wɑːtʃt/","gloss":"assistiu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"movie","pos":"noun","ipa":"/ˈmuːvi/","gloss":"filme"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-37-03', 'lesson-essential-verbs-a1-37', 3, 'sentence', 'I''ll watch the kids tonight.', 'Eu cuido das crianças hoje à noite.', '/aɪl wɑːtʃ ðə kɪdz təˈnaɪt/', '"Watch" também é vigiar, cuidar.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"watch","pos":"noun","ipa":"/wɑːtʃ/","gloss":"relógio de pulso"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"kids","pos":"noun","ipa":"/kɪdz/","gloss":"crianças, filhos"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-37-04', 'lesson-essential-verbs-a1-37', 4, 'sentence', 'I''ve never watched that series.', 'Nunca assisti a essa série.', '/aɪv ˈnɛvər wɑːtʃt ðæt ˈsɪriːz/', 'Present perfect + "never".', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"watched","pos":"verb","ipa":"/wɑːtʃt/","gloss":"assistiu"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"series","pos":"noun","ipa":"/ˈsɪriːz/","gloss":"série"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-37-05', 'lesson-essential-verbs-a1-37', 5, 'sentence', 'Follow me, please.', 'Me siga, por favor.', '/ˈfɑːloʊ miː pliːz/', 'Imperativo de "follow".', '[]'::jsonb, '[{"surface":"Follow","pos":"verb","ipa":"/ˈfɑːloʊ/","gloss":"seguir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-37-06', 'lesson-essential-verbs-a1-37', 6, 'sentence', 'We followed the signs to the exit.', 'Seguimos as placas até a saída.', '/wiː ˈfɑːloʊd ðə saɪnz tuː ðə ˈɛɡzɪt/', 'Passado regular: "followed".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"followed","pos":"verb","ipa":"/ˈfɑːloʊd/","gloss":"seguiu"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"signs","pos":"noun","ipa":"/saɪnz/","gloss":"placas"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"exit","pos":"noun","ipa":"/ˈɛɡzɪt/","gloss":"saída"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-37-07', 'lesson-essential-verbs-a1-37', 7, 'sentence', 'I will follow your advice.', 'Vou seguir seu conselho.', '/aɪ wɪl ˈfɑːloʊ jʊr ədˈvaɪs/', '"Advice" é incontável.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"follow","pos":"verb","ipa":"/ˈfɑːloʊ/","gloss":"seguir"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"advice","pos":"noun","ipa":"/ədˈvaɪs/","gloss":"conselho(s)"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-37-08', 'lesson-essential-verbs-a1-37', 8, 'sentence', 'She has followed this band for years.', 'Ela acompanha essa banda há anos.', '/ʃiː hæz ˈfɑːloʊd ðɪs bænd fɔːr jɪrz/', 'Present perfect + "for".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"followed","pos":"verb","ipa":"/ˈfɑːloʊd/","gloss":"seguiu"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"band","pos":"noun","ipa":"/bænd/","gloss":"banda"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-38', 'course-essential-verbs-a1', 38, 'stop e create', 'Parar e criar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-38-01', 'lesson-essential-verbs-a1-38', 1, 'sentence', 'The bus stops here.', 'O ônibus para aqui.', '/ðə bʌs stɑːps hɪr/', '"Stop" com he/she/it: "stops".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"},{"surface":"stops","pos":"noun","ipa":"/stɑːps/","gloss":"paradas"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-38-02', 'lesson-essential-verbs-a1-38', 2, 'sentence', 'It stopped raining.', 'Parou de chover.', '/ɪt stɑːpt ˈreɪnɪŋ/', '"Stop" + "-ing" = parar de fazer.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"stopped","pos":"verb","ipa":"/stɑːpt/","gloss":"parou"},{"surface":"raining","pos":"verb","ipa":"/ˈreɪnɪŋ/","gloss":"chovendo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-38-03', 'lesson-essential-verbs-a1-38', 3, 'sentence', 'I''ll stop at the store on the way.', 'Vou passar no mercado no caminho.', '/aɪl stɑːp æt ðə stɔːr ɑːn ðə weɪ/', '"Stop at" = dar uma parada em.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"stop","pos":"verb","ipa":"/stɑːp/","gloss":"parar"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"store","pos":"noun","ipa":"/stɔːr/","gloss":"loja, mercado"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-38-04', 'lesson-essential-verbs-a1-38', 4, 'sentence', 'I''ve stopped drinking coffee.', 'Parei de tomar café.', '/aɪv stɑːpt ˈdrɪŋkɪŋ ˈkɔːfi/', 'Present perfect: mudança de hábito.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"stopped","pos":"verb","ipa":"/stɑːpt/","gloss":"parou"},{"surface":"drinking","pos":"verb","ipa":"/ˈdrɪŋkɪŋ/","gloss":"bebendo"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-38-05', 'lesson-essential-verbs-a1-38', 5, 'sentence', 'She creates videos for work.', 'Ela cria vídeos para o trabalho.', '/ʃiː kriˈeɪts ˈvɪdioʊz fɔːr wɜːrk/', '"Create" = criar.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"creates","pos":"verb","ipa":"/kriˈeɪts/","gloss":"cria"},{"surface":"videos","pos":"noun","ipa":"/ˈvɪdioʊz/","gloss":"vídeos"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-38-06', 'lesson-essential-verbs-a1-38', 6, 'sentence', 'He created his own company.', 'Ele criou a própria empresa.', '/hiː kriˈeɪtɪd hɪz oʊn ˈkʌmpəni/', 'Passado regular: "created".', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"created","pos":"verb","ipa":"/kriˈeɪtɪd/","gloss":"criou"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"own","pos":"verb","ipa":"/oʊn/","gloss":"ser dono, responsável"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-38-07', 'lesson-essential-verbs-a1-38', 7, 'sentence', 'We will create a new plan.', 'Vamos criar um plano novo.', '/wiː wɪl kriˈeɪt ə nuː plæn/', 'Futuro com "will".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"create","pos":"verb","ipa":"/kriˈeɪt/","gloss":"criar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"plan","pos":"noun","ipa":"/plæn/","gloss":"plano"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-38-08', 'lesson-essential-verbs-a1-38', 8, 'sentence', 'The company has created many jobs.', 'A empresa criou muitos empregos.', '/ðə ˈkʌmpəni hæz kriˈeɪtɪd ˈmɛni dʒɑːbz/', 'Present perfect: resultado atual.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"created","pos":"verb","ipa":"/kriˈeɪtɪd/","gloss":"criou"},{"surface":"many","pos":"determiner","ipa":"/ˈmɛni/","gloss":"muitos (how many)"},{"surface":"jobs","pos":"noun","ipa":"/dʒɑːbz/","gloss":"empregos"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-39', 'course-essential-verbs-a1', 39, 'speak e read', 'Falar e ler nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-39-01', 'lesson-essential-verbs-a1-39', 1, 'sentence', 'She speaks three languages.', 'Ela fala três idiomas.', '/ʃiː spiːks θriː ˈlæŋɡwɪdʒɪz/', '"Speak" + idioma. "Speak" é mais formal que "talk".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"speaks","pos":"verb","ipa":"/spiːks/","gloss":"fala"},{"surface":"three","pos":"numeral","ipa":"/θriː/","gloss":"três"},{"surface":"languages","pos":"noun","ipa":"/ˈlæŋɡwɪdʒɪz/","gloss":"idiomas"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-39-02', 'lesson-essential-verbs-a1-39', 2, 'sentence', 'I spoke to the manager.', 'Falei com o gerente.', '/aɪ spoʊk tuː ðə ˈmænɪdʒər/', 'Passado irregular: "spoke".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"spoke","pos":"verb","ipa":"/spoʊk/","gloss":"falou"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"manager","pos":"noun","ipa":"/ˈmænɪdʒər/","gloss":"gerente"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-39-03', 'lesson-essential-verbs-a1-39', 3, 'sentence', 'Will you speak at the meeting?', 'Você vai falar na reunião?', '/wɪl juː spiːk æt ðə ˈmiːtɪŋ/', 'Pergunta com "will".', '[]'::jsonb, '[{"surface":"Will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"speak","pos":"verb","ipa":"/spiːk/","gloss":"falar"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-39-04', 'lesson-essential-verbs-a1-39', 4, 'sentence', 'I''ve spoken to her about it.', 'Já falei com ela sobre isso.', '/aɪv ˈspoʊkən tuː hɜːr əˈbaʊt ɪt/', 'Particípio irregular: "spoken".', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"spoken","pos":"verb","ipa":"/ˈspoʊkən/","gloss":"falado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-39-05', 'lesson-essential-verbs-a1-39', 5, 'sentence', 'I read before bed.', 'Leio antes de dormir.', '/aɪ riːd bɪˈfɔːr bɛd/', '"Read" presente: /riːd/.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"bed","pos":"noun","ipa":"/bɛd/","gloss":"cama"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-39-06', 'lesson-essential-verbs-a1-39', 6, 'sentence', 'I read that book last year.', 'Li esse livro no ano passado.', '/aɪ riːd ðæt bʊk læst jɪr/', 'Passado igual na escrita, mas pronúncia /rɛd/.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"book","pos":"verb","ipa":"/bʊk/","gloss":"reservar; livro"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-39-07', 'lesson-essential-verbs-a1-39', 7, 'sentence', 'I''ll read it tonight.', 'Vou ler hoje à noite.', '/aɪl riːd ɪt təˈnaɪt/', 'Futuro: "will read" /riːd/.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-39-08', 'lesson-essential-verbs-a1-39', 8, 'sentence', 'Have you read the news?', 'Você leu a notícia?', '/hæv juː riːd ðə nuːz/', 'Particípio "read" /rɛd/.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"news","pos":"noun","ipa":"/nuːz/","gloss":"notícia(s)"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-40', 'course-essential-verbs-a1', 40, 'spend e grow', 'Gastar/passar tempo e crescer nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-40-01', 'lesson-essential-verbs-a1-40', 1, 'sentence', 'I spend too much money on coffee.', 'Gasto dinheiro demais com café.', '/aɪ spɛnd tuː mʌtʃ ˈmʌni ɑːn ˈkɔːfi/', '"Spend on" = gastar com.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"spend","pos":"verb","ipa":"/spɛnd/","gloss":"gastar, passar (tempo)"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"money","pos":"noun","ipa":"/ˈmʌni/","gloss":"dinheiro"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-40-02', 'lesson-essential-verbs-a1-40', 2, 'sentence', 'We spent the weekend at the beach.', 'Passamos o fim de semana na praia.', '/wiː spɛnt ðə ˈwiːkɛnd æt ðə biːtʃ/', '"Spend time" = passar tempo. Passado: "spent".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"spent","pos":"verb","ipa":"/spɛnt/","gloss":"gastou, passou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"weekend","pos":"noun","ipa":"/ˈwiːkɛnd/","gloss":"fim de semana"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"beach","pos":"noun","ipa":"/biːtʃ/","gloss":"praia"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-40-03', 'lesson-essential-verbs-a1-40', 3, 'sentence', 'I''ll spend more time with my family.', 'Vou passar mais tempo com minha família.', '/aɪl spɛnd mɔːr taɪm wɪð maɪ ˈfæməli/', 'Futuro com "will".', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"spend","pos":"verb","ipa":"/spɛnd/","gloss":"gastar, passar (tempo)"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"family","pos":"noun","ipa":"/ˈfæməli/","gloss":"família"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-40-04', 'lesson-essential-verbs-a1-40', 4, 'sentence', 'We''ve spent all our savings.', 'Gastamos todas as nossas economias.', '/wiːv spɛnt ɔːl aʊər ˈseɪvɪŋz/', 'Particípio: "spent".', '[]'::jsonb, '[{"surface":"We''ve","pos":"pronoun","ipa":"/wiːv/","gloss":"nós temos (we have)"},{"surface":"spent","pos":"verb","ipa":"/spɛnt/","gloss":"gastou, passou"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"savings","pos":"noun","ipa":"/ˈseɪvɪŋz/","gloss":"economias"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-40-05', 'lesson-essential-verbs-a1-40', 5, 'sentence', 'Tomatoes grow fast in summer.', 'Tomates crescem rápido no verão.', '/təˈmeɪtoʊz ɡroʊ fæst ɪn ˈsʌmər/', '"Grow" = crescer; também cultivar.', '[]'::jsonb, '[{"surface":"Tomatoes","pos":"noun","ipa":"/təˈmeɪtoʊz/","gloss":"tomates"},{"surface":"grow","pos":"verb","ipa":"/ɡroʊ/","gloss":"crescer"},{"surface":"fast","pos":"adverb","ipa":"/fæst/","gloss":"rápido"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"summer","pos":"noun","ipa":"/ˈsʌmər/","gloss":"verão"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-40-06', 'lesson-essential-verbs-a1-40', 6, 'sentence', 'I grew up in a small town.', 'Cresci numa cidade pequena.', '/aɪ ɡruː ʌp ɪn ə smɔːl taʊn/', '"Grow up" = crescer (infância). Passado: "grew".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"grew","pos":"verb","ipa":"/ɡruː/","gloss":"cresceu"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"small","pos":"adjective","ipa":"/smɔːl/","gloss":"pequeno"},{"surface":"town","pos":"noun","ipa":"/taʊn/","gloss":"cidade pequena"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-40-07', 'lesson-essential-verbs-a1-40', 7, 'sentence', 'The company will grow next year.', 'A empresa vai crescer no ano que vem.', '/ðə ˈkʌmpəni wɪl ɡroʊ nɛkst jɪr/', 'Futuro com "will".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"grow","pos":"verb","ipa":"/ɡroʊ/","gloss":"crescer"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-40-08', 'lesson-essential-verbs-a1-40', 8, 'sentence', 'Your kids have grown so much!', 'Seus filhos cresceram muito!', '/jʊr kɪdz hæv ɡroʊn soʊ mʌtʃ/', 'Particípio irregular: "grown".', '[]'::jsonb, '[{"surface":"Your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"kids","pos":"noun","ipa":"/kɪdz/","gloss":"crianças, filhos"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"grown","pos":"verb","ipa":"/ɡroʊn/","gloss":"crescido"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-41', 'course-essential-verbs-a1', 41, 'open e walk', 'Abrir e andar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-41-01', 'lesson-essential-verbs-a1-41', 1, 'sentence', 'The bank opens at ten.', 'O banco abre às dez.', '/ðə bæŋk ˈoʊpənz æt tɛn/', 'Horário fixo com presente simples.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bank","pos":"noun","ipa":"/bæŋk/","gloss":"banco"},{"surface":"opens","pos":"verb","ipa":"/ˈoʊpənz/","gloss":"abre"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-41-02', 'lesson-essential-verbs-a1-41', 2, 'sentence', 'She opened the window.', 'Ela abriu a janela.', '/ʃiː ˈoʊpənd ðə ˈwɪndoʊ/', 'Passado regular: "opened".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"opened","pos":"verb","ipa":"/ˈoʊpənd/","gloss":"abriu"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"window","pos":"noun","ipa":"/ˈwɪndoʊ/","gloss":"janela"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-41-03', 'lesson-essential-verbs-a1-41', 3, 'sentence', 'I''ll open the door for you.', 'Eu abro a porta para você.', '/aɪl ˈoʊpən ðə dɔːr fɔːr juː/', 'Oferta com "will".', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"door","pos":"noun","ipa":"/dɔːr/","gloss":"porta"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-41-04', 'lesson-essential-verbs-a1-41', 4, 'sentence', 'A new restaurant has opened downtown.', 'Um restaurante novo abriu no centro.', '/ə nuː ˈrɛstərɑːnt hæz ˈoʊpənd ˌdaʊnˈtaʊn/', 'Present perfect: novidade recente.', '[]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"restaurant","pos":"noun","ipa":"/ˈrɛstərɑːnt/","gloss":"restaurante"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"opened","pos":"verb","ipa":"/ˈoʊpənd/","gloss":"abriu"},{"surface":"downtown","pos":"adverb","ipa":"/ˌdaʊnˈtaʊn/","gloss":"para o centro"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-41-05', 'lesson-essential-verbs-a1-41', 5, 'sentence', 'I walk to work.', 'Vou a pé para o trabalho.', '/aɪ wɔːk tuː wɜːrk/', '"Walk to" = ir a pé até.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-41-06', 'lesson-essential-verbs-a1-41', 6, 'sentence', 'We walked along the beach.', 'Caminhamos pela praia.', '/wiː wɔːkt əˈlɔːŋ ðə biːtʃ/', '"Walk along" = caminhar ao longo de.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"walked","pos":"verb","ipa":"/wɔːkt/","gloss":"caminhou"},{"surface":"along","pos":"particle","ipa":"/əˈlɔːŋ/","gloss":"junto (get along = dar-se bem)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"beach","pos":"noun","ipa":"/biːtʃ/","gloss":"praia"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-41-07', 'lesson-essential-verbs-a1-41', 7, 'sentence', 'I''ll walk the dog later.', 'Vou passear com o cachorro depois.', '/aɪl wɔːk ðə dɔːɡ ˈleɪtər/', '"Walk the dog" = levar o cachorro para passear.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"dog","pos":"noun","ipa":"/dɔːɡ/","gloss":"cachorro"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-41-08', 'lesson-essential-verbs-a1-41', 8, 'sentence', 'I''ve walked ten thousand steps today.', 'Já andei dez mil passos hoje.', '/aɪv wɔːkt tɛn ˈθaʊzənd stɛps təˈdeɪ/', 'Present perfect + "today".', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"walked","pos":"verb","ipa":"/wɔːkt/","gloss":"caminhou"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"thousand","pos":"numeral","ipa":"/ˈθaʊzənd/","gloss":"mil"},{"surface":"steps","pos":"noun","ipa":"/stɛps/","gloss":"passos"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-42', 'course-essential-verbs-a1', 42, 'Revisão: módulo 7', 'Base, passado e particípio dos 10 verbos do módulo 7.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-42-01', 'lesson-essential-verbs-a1-42', 1, 'verb_forms', 'watch watched watched', 'assistir', '/wɑːtʃ wɑːtʃt wɑːtʃt/', 'Regular: "-ed" soa /t/.', '[]'::jsonb, '[{"surface":"watch","pos":"noun","ipa":"/wɑːtʃ/","gloss":"relógio de pulso"},{"surface":"watched","pos":"verb","ipa":"/wɑːtʃt/","gloss":"assistiu"},{"surface":"watched","pos":"verb","ipa":"/wɑːtʃt/","gloss":"assistiu"}]'::jsonb, 'We watched a movie yesterday.', 'Assistimos a um filme ontem.'),
  ('unit-essential-verbs-a1-42-02', 'lesson-essential-verbs-a1-42', 2, 'verb_forms', 'follow followed followed', 'seguir', '/ˈfɑːloʊ ˈfɑːloʊd ˈfɑːloʊd/', 'Regular.', '[]'::jsonb, '[{"surface":"follow","pos":"verb","ipa":"/ˈfɑːloʊ/","gloss":"seguir"},{"surface":"followed","pos":"verb","ipa":"/ˈfɑːloʊd/","gloss":"seguiu"},{"surface":"followed","pos":"verb","ipa":"/ˈfɑːloʊd/","gloss":"seguiu"}]'::jsonb, 'We followed the signs to the exit.', 'Seguimos as placas até a saída.'),
  ('unit-essential-verbs-a1-42-03', 'lesson-essential-verbs-a1-42', 3, 'verb_forms', 'stop stopped stopped', 'parar', '/stɑːp stɑːpt stɑːpt/', 'Regular, dobra o "p": stopped.', '[]'::jsonb, '[{"surface":"stop","pos":"verb","ipa":"/stɑːp/","gloss":"parar"},{"surface":"stopped","pos":"verb","ipa":"/stɑːpt/","gloss":"parou"},{"surface":"stopped","pos":"verb","ipa":"/stɑːpt/","gloss":"parou"}]'::jsonb, 'It stopped raining.', 'Parou de chover.'),
  ('unit-essential-verbs-a1-42-04', 'lesson-essential-verbs-a1-42', 4, 'verb_forms', 'create created created', 'criar', '/kriˈeɪt kriˈeɪtɪd kriˈeɪtɪd/', 'Regular.', '[]'::jsonb, '[{"surface":"create","pos":"verb","ipa":"/kriˈeɪt/","gloss":"criar"},{"surface":"created","pos":"verb","ipa":"/kriˈeɪtɪd/","gloss":"criou"},{"surface":"created","pos":"verb","ipa":"/kriˈeɪtɪd/","gloss":"criou"}]'::jsonb, 'He created his own company.', 'Ele criou a própria empresa.'),
  ('unit-essential-verbs-a1-42-05', 'lesson-essential-verbs-a1-42', 5, 'verb_forms', 'speak spoke spoken', 'falar', '/spiːk spoʊk ˈspoʊkən/', 'Base "speak" · passado "spoke" · particípio "spoken".', '[]'::jsonb, '[{"surface":"speak","pos":"verb","ipa":"/spiːk/","gloss":"falar"},{"surface":"spoke","pos":"verb","ipa":"/spoʊk/","gloss":"falou"},{"surface":"spoken","pos":"verb","ipa":"/ˈspoʊkən/","gloss":"falado"}]'::jsonb, 'I spoke to the manager.', 'Falei com o gerente.'),
  ('unit-essential-verbs-a1-42-06', 'lesson-essential-verbs-a1-42', 6, 'verb_forms', 'read read read', 'ler', '/riːd riːd riːd/', 'Escrita igual; pronúncia /riːd/ · /rɛd/ · /rɛd/.', '[]'::jsonb, '[{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"}]'::jsonb, 'I read that book last year.', 'Li esse livro no ano passado.'),
  ('unit-essential-verbs-a1-42-07', 'lesson-essential-verbs-a1-42', 7, 'verb_forms', 'spend spent spent', 'gastar, passar (tempo)', '/spɛnd spɛnt spɛnt/', 'Base "spend" · passado e particípio "spent".', '[]'::jsonb, '[{"surface":"spend","pos":"verb","ipa":"/spɛnd/","gloss":"gastar, passar (tempo)"},{"surface":"spent","pos":"verb","ipa":"/spɛnt/","gloss":"gastou, passou"},{"surface":"spent","pos":"verb","ipa":"/spɛnt/","gloss":"gastou, passou"}]'::jsonb, 'We spent the weekend at the beach.', 'Passamos o fim de semana na praia.'),
  ('unit-essential-verbs-a1-42-08', 'lesson-essential-verbs-a1-42', 8, 'verb_forms', 'grow grew grown', 'crescer', '/ɡroʊ ɡruː ɡroʊn/', 'Base "grow" · passado "grew" · particípio "grown".', '[]'::jsonb, '[{"surface":"grow","pos":"verb","ipa":"/ɡroʊ/","gloss":"crescer"},{"surface":"grew","pos":"verb","ipa":"/ɡruː/","gloss":"cresceu"},{"surface":"grown","pos":"verb","ipa":"/ɡroʊn/","gloss":"crescido"}]'::jsonb, 'I grew up in a small town.', 'Cresci numa cidade pequena.'),
  ('unit-essential-verbs-a1-42-09', 'lesson-essential-verbs-a1-42', 9, 'verb_forms', 'open opened opened', 'abrir', '/ˈoʊpən ˈoʊpənd ˈoʊpənd/', 'Regular.', '[]'::jsonb, '[{"surface":"open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"opened","pos":"verb","ipa":"/ˈoʊpənd/","gloss":"abriu"},{"surface":"opened","pos":"verb","ipa":"/ˈoʊpənd/","gloss":"abriu"}]'::jsonb, 'She opened the window.', 'Ela abriu a janela.'),
  ('unit-essential-verbs-a1-42-10', 'lesson-essential-verbs-a1-42', 10, 'verb_forms', 'walk walked walked', 'andar, caminhar', '/wɔːk wɔːkt wɔːkt/', 'Regular; o "l" é mudo: /wɔːk/.', '[]'::jsonb, '[{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"},{"surface":"walked","pos":"verb","ipa":"/wɔːkt/","gloss":"caminhou"},{"surface":"walked","pos":"verb","ipa":"/wɔːkt/","gloss":"caminhou"}]'::jsonb, 'We walked along the beach.', 'Caminhamos pela praia.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
