-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-1000-words-a1', '1000-essential-words', '1000 Palavras Essenciais', 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.', 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.', 'A1', 'grammar', 11, 'fundamentos', 2, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-17', 'course-1000-words-a1', 17, 'Direções e posições', 'Onde fica, para onde ir e como explicar o caminho.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-17-01', 'lesson-1000-words-a1-17', 1, 'word', 'left', 'esquerda', '/lɛft/', '"Turn left" sem preposição.', '[]'::jsonb, '[{"surface":"left","pos":"adverb","ipa":"/lɛft/","gloss":"à esquerda"}]'::jsonb, 'Turn left at the bank.', 'Vire à esquerda no banco.'),
  ('unit-1000-words-a1-17-02', 'lesson-1000-words-a1-17', 2, 'word', 'right', 'direita', '/raɪt/', '"On the right/left" = à direita/esquerda. "Right" também é "certo".', '[]'::jsonb, '[{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"à direita; certo"}]'::jsonb, 'The store is on the right.', 'A loja fica à direita.'),
  ('unit-1000-words-a1-17-03', 'lesson-1000-words-a1-17', 3, 'word', 'straight', 'reto', '/streɪt/', '"Block" = quarteirão.', '[]'::jsonb, '[{"surface":"straight","pos":"adverb","ipa":"/streɪt/","gloss":"reto"}]'::jsonb, 'Go straight for two blocks.', 'Siga reto por dois quarteirões.'),
  ('unit-1000-words-a1-17-04', 'lesson-1000-words-a1-17', 4, 'word', 'north', 'norte', '/nɔːrθ/', NULL, '[]'::jsonb, '[{"surface":"north","pos":"noun","ipa":"/nɔːrθ/","gloss":"norte"}]'::jsonb, 'The beach is north of the city.', 'A praia fica ao norte da cidade.'),
  ('unit-1000-words-a1-17-05', 'lesson-1000-words-a1-17', 5, 'word', 'south', 'sul', '/saʊθ/', NULL, '[]'::jsonb, '[{"surface":"south","pos":"noun","ipa":"/saʊθ/","gloss":"sul"}]'::jsonb, 'We drove south.', 'Dirigimos para o sul.'),
  ('unit-1000-words-a1-17-06', 'lesson-1000-words-a1-17', 6, 'word', 'east', 'leste', '/iːst/', NULL, '[]'::jsonb, '[{"surface":"east","pos":"noun","ipa":"/iːst/","gloss":"leste"}]'::jsonb, 'The sun rises in the east.', 'O sol nasce no leste.'),
  ('unit-1000-words-a1-17-07', 'lesson-1000-words-a1-17', 7, 'word', 'west', 'oeste', '/wɛst/', NULL, '[]'::jsonb, '[{"surface":"west","pos":"noun","ipa":"/wɛst/","gloss":"oeste"}]'::jsonb, 'The sun sets in the west.', 'O sol se põe no oeste.'),
  ('unit-1000-words-a1-17-08', 'lesson-1000-words-a1-17', 8, 'word', 'next', 'ao lado', '/nɛkst/', '"Next to" = ao lado de.', '[]'::jsonb, '[{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo; next to = ao lado de"}]'::jsonb, 'The pharmacy is next to the bank.', 'A farmácia fica ao lado do banco.'),
  ('unit-1000-words-a1-17-09', 'lesson-1000-words-a1-17', 9, 'word', 'between', 'entre', '/bɪˈtwiːn/', '"Between" é entre dois; "among" é entre vários.', '[]'::jsonb, '[{"surface":"between","pos":"preposition","ipa":"/bɪˈtwiːn/","gloss":"entre"}]'::jsonb, 'It''s between the school and the park.', 'Fica entre a escola e o parque.'),
  ('unit-1000-words-a1-17-10', 'lesson-1000-words-a1-17', 10, 'word', 'behind', 'atrás de', '/bɪˈhaɪnd/', NULL, '[]'::jsonb, '[{"surface":"behind","pos":"preposition","ipa":"/bɪˈhaɪnd/","gloss":"atrás de"}]'::jsonb, 'The car is behind the house.', 'O carro está atrás da casa.'),
  ('unit-1000-words-a1-17-11', 'lesson-1000-words-a1-17', 11, 'word', 'front', 'frente', '/frʌnt/', '"In front of" = na frente de.', '[]'::jsonb, '[{"surface":"front","pos":"noun","ipa":"/frʌnt/","gloss":"frente"}]'::jsonb, 'Wait in front of the hotel.', 'Espere na frente do hotel.'),
  ('unit-1000-words-a1-17-12', 'lesson-1000-words-a1-17', 12, 'word', 'opposite', 'em frente a', '/ˈɑːpəzɪt/', '"Opposite" = do outro lado, de frente. Diferente de "in front of".', '[]'::jsonb, '[{"surface":"opposite","pos":"preposition","ipa":"/ˈɑːpəzɪt/","gloss":"em frente a, do outro lado"}]'::jsonb, 'The bank is opposite the station.', 'O banco fica em frente à estação.'),
  ('unit-1000-words-a1-17-13', 'lesson-1000-words-a1-17', 13, 'word', 'inside', 'dentro', '/ˌɪnˈsaɪd/', NULL, '[]'::jsonb, '[{"surface":"inside","pos":"adverb","ipa":"/ˌɪnˈsaɪd/","gloss":"dentro"}]'::jsonb, 'It''s cold, let''s go inside.', 'Está frio, vamos entrar.'),
  ('unit-1000-words-a1-17-14', 'lesson-1000-words-a1-17', 14, 'word', 'outside', 'fora', '/ˌaʊtˈsaɪd/', NULL, '[]'::jsonb, '[{"surface":"outside","pos":"adverb","ipa":"/ˌaʊtˈsaɪd/","gloss":"lá fora"}]'::jsonb, 'The kids are playing outside.', 'As crianças estão brincando lá fora.'),
  ('unit-1000-words-a1-17-15', 'lesson-1000-words-a1-17', 15, 'word', 'above', 'acima de', '/əˈbʌv/', NULL, '[]'::jsonb, '[{"surface":"above","pos":"preposition","ipa":"/əˈbʌv/","gloss":"acima de"}]'::jsonb, 'The picture is above the sofa.', 'O quadro está acima do sofá.'),
  ('unit-1000-words-a1-17-16', 'lesson-1000-words-a1-17', 16, 'word', 'under', 'embaixo de', '/ˈʌndər/', NULL, '[]'::jsonb, '[{"surface":"under","pos":"preposition","ipa":"/ˈʌndər/","gloss":"embaixo de"}]'::jsonb, 'The cat is under the table.', 'O gato está embaixo da mesa.'),
  ('unit-1000-words-a1-17-17', 'lesson-1000-words-a1-17', 17, 'word', 'across', 'do outro lado de', '/əˈkrɔːs/', NULL, '[]'::jsonb, '[{"surface":"across","pos":"preposition","ipa":"/əˈkrɔːs/","gloss":"do outro lado de, atravessando"}]'::jsonb, 'The bakery is across the street.', 'A padaria fica do outro lado da rua.'),
  ('unit-1000-words-a1-17-18', 'lesson-1000-words-a1-17', 18, 'word', 'near', 'perto de', '/nɪr/', '"Near" sem "of": "near the hotel".', '[]'::jsonb, '[{"surface":"near","pos":"preposition","ipa":"/nɪr/","gloss":"perto de"}]'::jsonb, 'Is there a bank near here?', 'Tem um banco perto daqui?'),
  ('unit-1000-words-a1-17-19', 'lesson-1000-words-a1-17', 19, 'word', 'far', 'longe', '/fɑːr/', '"Far from" = longe de.', '[]'::jsonb, '[{"surface":"far","pos":"adjective","ipa":"/fɑːr/","gloss":"longe"}]'::jsonb, 'Is it far from here?', 'É longe daqui?'),
  ('unit-1000-words-a1-17-20', 'lesson-1000-words-a1-17', 20, 'word', 'down', 'para baixo', '/daʊn/', '"Up" = para cima; "down" = para baixo. Também "down the street" = rua abaixo.', '[]'::jsonb, '[{"surface":"down","pos":"adverb","ipa":"/daʊn/","gloss":"para baixo"}]'::jsonb, 'Go down the stairs.', 'Desça a escada.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-18', 'course-1000-words-a1', 18, 'Animais', 'Animais de estimação, da fazenda e selvagens.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-18-01', 'lesson-1000-words-a1-18', 1, 'word', 'dog', 'cachorro', '/dɔːɡ/', NULL, '[]'::jsonb, '[{"surface":"dog","pos":"noun","ipa":"/dɔːɡ/","gloss":"cachorro"}]'::jsonb, 'My dog loves the park.', 'Meu cachorro adora o parque.'),
  ('unit-1000-words-a1-18-02', 'lesson-1000-words-a1-18', 2, 'word', 'cat', 'gato', '/kæt/', NULL, '[]'::jsonb, '[{"surface":"cat","pos":"noun","ipa":"/kæt/","gloss":"gato"}]'::jsonb, 'The cat is sleeping.', 'O gato está dormindo.'),
  ('unit-1000-words-a1-18-03', 'lesson-1000-words-a1-18', 3, 'word', 'pet', 'animal de estimação', '/pɛt/', NULL, '[]'::jsonb, '[{"surface":"pet","pos":"noun","ipa":"/pɛt/","gloss":"animal de estimação"}]'::jsonb, 'Do you have any pets?', 'Você tem algum animal de estimação?'),
  ('unit-1000-words-a1-18-04', 'lesson-1000-words-a1-18', 4, 'word', 'bird', 'pássaro', '/bɜːrd/', NULL, '[]'::jsonb, '[{"surface":"bird","pos":"noun","ipa":"/bɜːrd/","gloss":"pássaro"}]'::jsonb, 'I can hear the birds.', 'Consigo ouvir os pássaros.'),
  ('unit-1000-words-a1-18-05', 'lesson-1000-words-a1-18', 5, 'word', 'fish', 'peixe', '/fɪʃ/', 'Plural geralmente igual: "fish".', '[]'::jsonb, '[{"surface":"fish","pos":"noun","ipa":"/fɪʃ/","gloss":"peixe"}]'::jsonb, 'We have two fish at home.', 'Temos dois peixes em casa.'),
  ('unit-1000-words-a1-18-06', 'lesson-1000-words-a1-18', 6, 'word', 'horse', 'cavalo', '/hɔːrs/', 'Andar a cavalo também é "ride".', '[]'::jsonb, '[{"surface":"horse","pos":"noun","ipa":"/hɔːrs/","gloss":"cavalo"}]'::jsonb, 'She rides a horse.', 'Ela anda a cavalo.'),
  ('unit-1000-words-a1-18-07', 'lesson-1000-words-a1-18', 7, 'word', 'cow', 'vaca', '/kaʊ/', NULL, '[]'::jsonb, '[{"surface":"cow","pos":"noun","ipa":"/kaʊ/","gloss":"vaca"}]'::jsonb, 'The cows are in the field.', 'As vacas estão no pasto.'),
  ('unit-1000-words-a1-18-08', 'lesson-1000-words-a1-18', 8, 'word', 'pig', 'porco', '/pɪɡ/', NULL, '[]'::jsonb, '[{"surface":"pig","pos":"noun","ipa":"/pɪɡ/","gloss":"porco"}]'::jsonb, 'The pig is very big.', 'O porco é muito grande.'),
  ('unit-1000-words-a1-18-09', 'lesson-1000-words-a1-18', 9, 'word', 'sheep', 'ovelha', '/ʃiːp/', 'Plural igual ao singular: "one sheep, ten sheep".', '[]'::jsonb, '[{"surface":"sheep","pos":"noun","ipa":"/ʃiːp/","gloss":"ovelha"}]'::jsonb, 'There are many sheep on the farm.', 'Tem muitas ovelhas na fazenda.'),
  ('unit-1000-words-a1-18-10', 'lesson-1000-words-a1-18', 10, 'word', 'chicken', 'galinha, frango', '/ˈtʃɪkən/', 'O animal e a carne têm o mesmo nome.', '[]'::jsonb, '[{"surface":"chicken","pos":"noun","ipa":"/ˈtʃɪkən/","gloss":"frango"}]'::jsonb, 'The chickens lay eggs.', 'As galinhas botam ovos.'),
  ('unit-1000-words-a1-18-11', 'lesson-1000-words-a1-18', 11, 'word', 'duck', 'pato', '/dʌk/', NULL, '[]'::jsonb, '[{"surface":"duck","pos":"noun","ipa":"/dʌk/","gloss":"pato"}]'::jsonb, 'There are ducks in the lake.', 'Tem patos no lago.'),
  ('unit-1000-words-a1-18-12', 'lesson-1000-words-a1-18', 12, 'word', 'mouse', 'rato', '/maʊs/', 'Plural irregular: "mice". Rato grande é "rat".', '[]'::jsonb, '[{"surface":"mouse","pos":"noun","ipa":"/maʊs/","gloss":"rato, camundongo"}]'::jsonb, 'I saw a mouse in the kitchen.', 'Vi um rato na cozinha.'),
  ('unit-1000-words-a1-18-13', 'lesson-1000-words-a1-18', 13, 'word', 'rabbit', 'coelho', '/ˈræbɪt/', NULL, '[]'::jsonb, '[{"surface":"rabbit","pos":"noun","ipa":"/ˈræbɪt/","gloss":"coelho"}]'::jsonb, 'The rabbit is eating a carrot.', 'O coelho está comendo uma cenoura.'),
  ('unit-1000-words-a1-18-14', 'lesson-1000-words-a1-18', 14, 'word', 'snake', 'cobra', '/sneɪk/', NULL, '[]'::jsonb, '[{"surface":"snake","pos":"noun","ipa":"/sneɪk/","gloss":"cobra"}]'::jsonb, 'Be careful, there is a snake.', 'Cuidado, tem uma cobra.'),
  ('unit-1000-words-a1-18-15', 'lesson-1000-words-a1-18', 15, 'word', 'monkey', 'macaco', '/ˈmʌŋki/', NULL, '[]'::jsonb, '[{"surface":"monkey","pos":"noun","ipa":"/ˈmʌŋki/","gloss":"macaco"}]'::jsonb, 'The monkeys are funny.', 'Os macacos são engraçados.'),
  ('unit-1000-words-a1-18-16', 'lesson-1000-words-a1-18', 16, 'word', 'lion', 'leão', '/ˈlaɪən/', NULL, '[]'::jsonb, '[{"surface":"lion","pos":"noun","ipa":"/ˈlaɪən/","gloss":"leão"}]'::jsonb, 'The lion is sleeping.', 'O leão está dormindo.'),
  ('unit-1000-words-a1-18-17', 'lesson-1000-words-a1-18', 17, 'word', 'bear', 'urso', '/bɛr/', NULL, '[]'::jsonb, '[{"surface":"bear","pos":"noun","ipa":"/bɛr/","gloss":"urso"}]'::jsonb, 'We saw a bear in the forest.', 'Vimos um urso na floresta.'),
  ('unit-1000-words-a1-18-18', 'lesson-1000-words-a1-18', 18, 'word', 'shark', 'tubarão', '/ʃɑːrk/', NULL, '[]'::jsonb, '[{"surface":"shark","pos":"noun","ipa":"/ʃɑːrk/","gloss":"tubarão"}]'::jsonb, 'Are there sharks here?', 'Tem tubarão aqui?'),
  ('unit-1000-words-a1-18-19', 'lesson-1000-words-a1-18', 19, 'word', 'bee', 'abelha', '/biː/', NULL, '[]'::jsonb, '[{"surface":"bee","pos":"noun","ipa":"/biː/","gloss":"abelha"}]'::jsonb, 'I am allergic to bees.', 'Sou alérgico a abelha.'),
  ('unit-1000-words-a1-18-20', 'lesson-1000-words-a1-18', 20, 'word', 'spider', 'aranha', '/ˈspaɪdər/', '"Scared of" = com medo de.', '[]'::jsonb, '[{"surface":"spider","pos":"noun","ipa":"/ˈspaɪdər/","gloss":"aranha"}]'::jsonb, 'I''m scared of spiders.', 'Tenho medo de aranha.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-19', 'course-1000-words-a1', 19, 'Emoções e sentimentos', 'Dizer como você se sente com a palavra certa.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-19-01', 'lesson-1000-words-a1-19', 1, 'word', 'happy', 'feliz', '/ˈhæpi/', '"Happy for" = feliz por alguém.', '[]'::jsonb, '[{"surface":"happy","pos":"adjective","ipa":"/ˈhæpi/","gloss":"feliz"}]'::jsonb, 'I''m so happy for you.', 'Estou muito feliz por você.'),
  ('unit-1000-words-a1-19-02', 'lesson-1000-words-a1-19', 2, 'word', 'sad', 'triste', '/sæd/', NULL, '[]'::jsonb, '[{"surface":"sad","pos":"adjective","ipa":"/sæd/","gloss":"triste"}]'::jsonb, 'She looks sad today.', 'Ela parece triste hoje.'),
  ('unit-1000-words-a1-19-03', 'lesson-1000-words-a1-19', 3, 'word', 'angry', 'bravo', '/ˈæŋɡri/', '"Angry at/with" + pessoa.', '[]'::jsonb, '[{"surface":"angry","pos":"adjective","ipa":"/ˈæŋɡri/","gloss":"bravo, com raiva"}]'::jsonb, 'Why are you angry?', 'Por que você está bravo?'),
  ('unit-1000-words-a1-19-04', 'lesson-1000-words-a1-19', 4, 'word', 'scared', 'com medo', '/skɛrd/', '"Scared" = com medo; "scary" = assustador.', '[]'::jsonb, '[{"surface":"scared","pos":"adjective","ipa":"/skɛrd/","gloss":"com medo"}]'::jsonb, 'Don''t be scared.', 'Não tenha medo.'),
  ('unit-1000-words-a1-19-05', 'lesson-1000-words-a1-19', 5, 'word', 'worried', 'preocupado', '/ˈwɜːrid/', '"Worried about" = preocupado com.', '[]'::jsonb, '[{"surface":"worried","pos":"adjective","ipa":"/ˈwɜːrid/","gloss":"preocupado"}]'::jsonb, 'I''m worried about the exam.', 'Estou preocupado com a prova.'),
  ('unit-1000-words-a1-19-06', 'lesson-1000-words-a1-19', 6, 'word', 'nervous', 'nervoso', '/ˈnɜːrvəs/', 'Em inglês "nervous" é ansioso, não bravo.', '[]'::jsonb, '[{"surface":"nervous","pos":"adjective","ipa":"/ˈnɜːrvəs/","gloss":"nervoso, ansioso"}]'::jsonb, 'I''m nervous before interviews.', 'Fico nervoso antes de entrevistas.'),
  ('unit-1000-words-a1-19-07', 'lesson-1000-words-a1-19', 7, 'word', 'excited', 'animado', '/ɪkˈsaɪtɪd/', 'Falso cognato: "excited" = animado, empolgado.', '[]'::jsonb, '[{"surface":"excited","pos":"adjective","ipa":"/ɪkˈsaɪtɪd/","gloss":"animado, empolgado"}]'::jsonb, 'I''m excited about the trip.', 'Estou animado com a viagem.'),
  ('unit-1000-words-a1-19-08', 'lesson-1000-words-a1-19', 8, 'word', 'bored', 'entediado', '/bɔːrd/', '"Bored" = entediado (a pessoa); "boring" = chato (a coisa).', '[]'::jsonb, '[{"surface":"bored","pos":"adjective","ipa":"/bɔːrd/","gloss":"entediado"}]'::jsonb, 'I''m bored, let''s go out.', 'Estou entediado, vamos sair.'),
  ('unit-1000-words-a1-19-09', 'lesson-1000-words-a1-19', 9, 'word', 'boring', 'chato', '/ˈbɔːrɪŋ/', NULL, '[]'::jsonb, '[{"surface":"boring","pos":"adjective","ipa":"/ˈbɔːrɪŋ/","gloss":"chato, entediante"}]'::jsonb, 'The movie was boring.', 'O filme foi chato.'),
  ('unit-1000-words-a1-19-10', 'lesson-1000-words-a1-19', 10, 'word', 'tired', 'cansado', '/ˈtaɪərd/', NULL, '[]'::jsonb, '[{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"}]'::jsonb, 'I''m too tired to go out.', 'Estou cansado demais para sair.'),
  ('unit-1000-words-a1-19-11', 'lesson-1000-words-a1-19', 11, 'word', 'surprised', 'surpreso', '/sərˈpraɪzd/', NULL, '[]'::jsonb, '[{"surface":"surprised","pos":"adjective","ipa":"/sərˈpraɪzd/","gloss":"surpreso"}]'::jsonb, 'I was surprised to see him.', 'Fiquei surpreso de ver ele.'),
  ('unit-1000-words-a1-19-12', 'lesson-1000-words-a1-19', 12, 'word', 'proud', 'orgulhoso', '/praʊd/', '"Proud of" = orgulhoso de.', '[]'::jsonb, '[{"surface":"proud","pos":"adjective","ipa":"/praʊd/","gloss":"orgulhoso"}]'::jsonb, 'I''m proud of you.', 'Estou orgulhoso de você.'),
  ('unit-1000-words-a1-19-13', 'lesson-1000-words-a1-19', 13, 'word', 'lonely', 'solitário', '/ˈloʊnli/', '"Lonely" é o sentimento; "alone" é estar sem companhia.', '[]'::jsonb, '[{"surface":"lonely","pos":"adjective","ipa":"/ˈloʊnli/","gloss":"sozinho, solitário"}]'::jsonb, 'She feels lonely in the new city.', 'Ela se sente sozinha na cidade nova.'),
  ('unit-1000-words-a1-19-14', 'lesson-1000-words-a1-19', 14, 'word', 'embarrassed', 'envergonhado', '/ɪmˈbærəst/', 'Falso cognato: "embarrassed" = com vergonha; grávida é "pregnant".', '[]'::jsonb, '[{"surface":"embarrassed","pos":"adjective","ipa":"/ɪmˈbærəst/","gloss":"envergonhado"}]'::jsonb, 'I was so embarrassed.', 'Fiquei morrendo de vergonha.'),
  ('unit-1000-words-a1-19-15', 'lesson-1000-words-a1-19', 15, 'word', 'jealous', 'com ciúme', '/ˈdʒɛləs/', NULL, '[]'::jsonb, '[{"surface":"jealous","pos":"adjective","ipa":"/ˈdʒɛləs/","gloss":"com ciúme, com inveja"}]'::jsonb, 'He''s jealous of his brother.', 'Ele tem ciúme do irmão.'),
  ('unit-1000-words-a1-19-16', 'lesson-1000-words-a1-19', 16, 'word', 'relaxed', 'relaxado', '/rɪˈlækst/', NULL, '[]'::jsonb, '[{"surface":"relaxed","pos":"adjective","ipa":"/rɪˈlækst/","gloss":"relaxado"}]'::jsonb, 'I feel relaxed on vacation.', 'Fico relaxado nas férias.'),
  ('unit-1000-words-a1-19-17', 'lesson-1000-words-a1-19', 17, 'word', 'confused', 'confuso', '/kənˈfjuːzd/', NULL, '[]'::jsonb, '[{"surface":"confused","pos":"adjective","ipa":"/kənˈfjuːzd/","gloss":"confuso"}]'::jsonb, 'I''m confused, can you explain again?', 'Estou confuso, pode explicar de novo?'),
  ('unit-1000-words-a1-19-18', 'lesson-1000-words-a1-19', 18, 'word', 'grateful', 'grato', '/ˈɡreɪtfəl/', NULL, '[]'::jsonb, '[{"surface":"grateful","pos":"adjective","ipa":"/ˈɡreɪtfəl/","gloss":"grato"}]'::jsonb, 'I''m grateful for your help.', 'Sou grato pela sua ajuda.'),
  ('unit-1000-words-a1-19-19', 'lesson-1000-words-a1-19', 19, 'word', 'upset', 'chateado', '/ʌpˈsɛt/', NULL, '[]'::jsonb, '[{"surface":"upset","pos":"adjective","ipa":"/ʌpˈsɛt/","gloss":"chateado"}]'::jsonb, 'She was upset about the news.', 'Ela ficou chateada com a notícia.'),
  ('unit-1000-words-a1-19-20', 'lesson-1000-words-a1-19', 20, 'word', 'calm', 'calmo', '/kɑːm/', 'O "l" é mudo: /kɑːm/.', '[]'::jsonb, '[{"surface":"calm","pos":"adjective","ipa":"/kɑːm/","gloss":"calmo"}]'::jsonb, 'Stay calm.', 'Fique calmo.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
