-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-work-b1', 'english-at-work-b1', 'Inglês no Trabalho', 'Reuniões, e-mails, apresentações, feedback, prazos e clientes: o inglês de escritório e trabalho remoto.', 'Expressões usadas de verdade no trabalho: conduzir reuniões, escrever e-mails, apresentar resultados, dar e receber feedback, negociar prazos, falar com clientes, delegar e conversar com colegas. Cada nota indica o registro (formal, neutro ou informal).', 'B1', 'business', 3, 'trabalho', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-04', 'course-work-b1', 4, 'Apresentações', 'Abrir, conduzir e fechar uma apresentação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-04-01', 'lesson-work-b1-04', 1, 'sentence', 'Today I''d like to talk about our results.', 'Hoje eu gostaria de falar sobre nossos resultados.', '/təˈdeɪ aɪd laɪk tuː tɔːk əˈbaʊt aʊər rɪˈzʌlts/', 'Neutro. Abertura clássica: "Today I''d like to talk about…".', '[]'::jsonb, '[{"surface":"Today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"},{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"talk","pos":"verb","ipa":"/tɔːk/","gloss":"falar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"results","pos":"noun","ipa":"/rɪˈzʌlts/","gloss":"resultados"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-02', 'lesson-work-b1-04', 2, 'sentence', 'I''ll start with a quick overview.', 'Vou começar com uma visão geral rápida.', '/aɪl stɑːrt wɪð ə kwɪk ˈoʊvərvjuː/', 'Neutro. "Overview" = visão geral.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"start","pos":"verb","ipa":"/stɑːrt/","gloss":"começar"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"quick","pos":"adjective","ipa":"/kwɪk/","gloss":"rápido"},{"surface":"overview","pos":"noun","ipa":"/ˈoʊvərvjuː/","gloss":"visão geral"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-03', 'lesson-work-b1-04', 3, 'sentence', 'As you can see on this slide,', 'Como vocês podem ver neste slide,', '/æz juː kæn siː ɑːn ðɪs slaɪd/', 'Neutro. Conecta a fala ao que está na tela.', '[]'::jsonb, '[{"surface":"As","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"slide","pos":"noun","ipa":"/slaɪd/","gloss":"slide"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-04', 'lesson-work-b1-04', 4, 'sentence', 'Sales went up by ten percent.', 'As vendas subiram dez por cento.', '/seɪlz wɛnt ʌp baɪ tɛn pərˈsɛnt/', 'Neutro. "Go up by" = subir em (quantidade). O contrário: "go down by".', '[]'::jsonb, '[{"surface":"Sales","pos":"noun","ipa":"/seɪlz/","gloss":"vendas"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"percent","pos":"noun","ipa":"/pərˈsɛnt/","gloss":"por cento"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-05', 'lesson-work-b1-04', 5, 'sentence', 'Let''s move on to the next point.', 'Vamos passar para o próximo ponto.', '/lɛts muːv ɑːn tuː ðə nɛkst pɔɪnt/', 'Neutro. "Move on to" = passar para.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"move","pos":"verb","ipa":"/muːv/","gloss":"mover, passar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-06', 'lesson-work-b1-04', 6, 'sentence', 'This is the key takeaway.', 'Esta é a mensagem principal.', '/ðɪs ɪz ðə kiː ˈteɪkəweɪ/', 'Neutro. "Takeaway" = o que o público deve lembrar.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"key","pos":"noun","ipa":"/kiː/","gloss":"chave"},{"surface":"takeaway","pos":"noun","ipa":"/ˈteɪkəweɪ/","gloss":"mensagem principal"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-07', 'lesson-work-b1-04', 7, 'sentence', 'I''ll leave time for questions at the end.', 'Vou deixar tempo para perguntas no final.', '/aɪl liːv taɪm fɔːr ˈkwɛstʃənz æt ðə ɛnd/', 'Neutro. "At the end" = no final.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"leave","pos":"verb","ipa":"/liːv/","gloss":"deixar"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"questions","pos":"noun","ipa":"/ˈkwɛstʃənz/","gloss":"perguntas, dúvidas"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"end","pos":"noun","ipa":"/ɛnd/","gloss":"fim, final"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-08', 'lesson-work-b1-04', 8, 'sentence', 'That''s a great question.', 'Ótima pergunta.', '/ðæts ə ɡreɪt ˈkwɛstʃən/', 'Neutro. Ganha tempo para pensar na resposta.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"question","pos":"noun","ipa":"/ˈkwɛstʃən/","gloss":"pergunta"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-09', 'lesson-work-b1-04', 9, 'sentence', 'I don''t have that number now, but I''ll send it later.', 'Não tenho esse número agora, mas envio depois.', '/aɪ doʊnt hæv ðæt ˈnʌmbər naʊ bʌt aɪl sɛnd ɪt ˈleɪtər/', 'Neutro. Jeito profissional de não saber na hora.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"number","pos":"noun","ipa":"/ˈnʌmbər/","gloss":"número"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"send","pos":"verb","ipa":"/sɛnd/","gloss":"enviar, mandar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-04-10', 'lesson-work-b1-04', 10, 'sentence', 'Thank you for your time.', 'Obrigado pelo seu tempo.', '/θæŋk juː fɔːr jʊr taɪm/', 'Formal. Fechamento padrão de apresentação.', '[]'::jsonb, '[{"surface":"Thank","pos":"verb","ipa":"/θæŋk/","gloss":"agradecer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-05', 'course-work-b1', 5, 'Dar e receber feedback', 'Elogiar, sugerir melhorias e aceitar críticas.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-05-01', 'lesson-work-b1-05', 1, 'sentence', 'You did a great job on this.', 'Você fez um ótimo trabalho nisso.', '/juː dɪd ə ɡreɪt dʒɑːb ɑːn ðɪs/', 'Neutro. "Do a great job" = fazer um ótimo trabalho.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"trabalho"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-02', 'lesson-work-b1-05', 2, 'sentence', 'I really liked how you handled the client.', 'Gostei muito de como você lidou com o cliente.', '/aɪ ˈriːəli laɪkt haʊ juː ˈhændəld ðə ˈklaɪənt/', 'Neutro. Elogio específico funciona melhor que genérico. "Handle" = lidar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"liked","pos":"verb","ipa":"/laɪkt/","gloss":"gostou"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"handled","pos":"verb","ipa":"/ˈhændəld/","gloss":"lidou com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"client","pos":"noun","ipa":"/ˈklaɪənt/","gloss":"cliente"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-03', 'lesson-work-b1-05', 3, 'sentence', 'One thing you could improve is the timing.', 'Uma coisa que você poderia melhorar é o tempo.', '/wʌn θɪŋ juː kʊd ɪmˈpruːv ɪz ðə ˈtaɪmɪŋ/', 'Neutro. Crítica suavizada com "could".', '[]'::jsonb, '[{"surface":"One","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"thing","pos":"noun","ipa":"/θɪŋ/","gloss":"coisa"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"improve","pos":"verb","ipa":"/ɪmˈpruːv/","gloss":"melhorar"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"timing","pos":"noun","ipa":"/ˈtaɪmɪŋ/","gloss":"tempo, ritmo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-04', 'lesson-work-b1-05', 4, 'sentence', 'Have you considered a different approach?', 'Você já pensou numa abordagem diferente?', '/hæv juː kənˈsɪdərd ə ˈdɪfərənt əˈproʊtʃ/', 'Neutro. Sugestão em forma de pergunta.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"considered","pos":"verb","ipa":"/kənˈsɪdərd/","gloss":"considerou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"different","pos":"adjective","ipa":"/ˈdɪfərənt/","gloss":"diferente"},{"surface":"approach","pos":"noun","ipa":"/əˈproʊtʃ/","gloss":"abordagem"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-05', 'lesson-work-b1-05', 5, 'sentence', 'Maybe we could try it another way.', 'Talvez a gente pudesse tentar de outro jeito.', '/ˈmeɪbi wiː kʊd traɪ ɪt əˈnʌðər weɪ/', 'Neutro. "Maybe" e "could" deixam a sugestão educada.', '[]'::jsonb, '[{"surface":"Maybe","pos":"adverb","ipa":"/ˈmeɪbi/","gloss":"talvez"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"try","pos":"verb","ipa":"/traɪ/","gloss":"experimentar, tentar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"another","pos":"determiner","ipa":"/əˈnʌðər/","gloss":"outro, mais um"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-06', 'lesson-work-b1-05', 6, 'sentence', 'Thanks for the feedback.', 'Obrigado pelo retorno.', '/θæŋks fɔːr ðə ˈfiːdbæk/', 'Neutro. "Feedback" é incontável: nunca "feedbacks".', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"feedback","pos":"noun","ipa":"/ˈfiːdbæk/","gloss":"retorno, feedback"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-07', 'lesson-work-b1-05', 7, 'sentence', 'That makes sense, I will work on it.', 'Faz sentido, vou trabalhar nisso.', '/ðæt meɪks sɛns aɪ wɪl wɜːrk ɑːn ɪt/', 'Neutro. Aceita a crítica e mostra ação.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"makes","pos":"verb","ipa":"/meɪks/","gloss":"faz"},{"surface":"sense","pos":"noun","ipa":"/sɛns/","gloss":"sentido"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-08', 'lesson-work-b1-05', 8, 'sentence', 'Could you give me an example?', 'Você poderia me dar um exemplo?', '/kʊd juː ɡɪv miː ən ɪɡˈzæmpəl/', 'Neutro. Pede clareza sem soar defensivo.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"example","pos":"noun","ipa":"/ɪɡˈzæmpəl/","gloss":"exemplo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-09', 'lesson-work-b1-05', 9, 'sentence', 'I see where you are coming from.', 'Entendo seu ponto de vista.', '/aɪ siː wɛr juː ɑːr ˈkʌmɪŋ frʌm/', 'Informal. Literal: "vejo de onde você vem". Real: entendo o motivo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"coming","pos":"verb","ipa":"/ˈkʌmɪŋ/","gloss":"vindo"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-05-10', 'lesson-work-b1-05', 10, 'sentence', 'Keep up the good work.', 'Continue assim.', '/kiːp ʌp ðə ɡʊd wɜːrk/', 'Neutro. "Keep up" = manter.', '[]'::jsonb, '[{"surface":"Keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-06', 'course-work-b1', 6, 'Prazos e negociação', 'Negociar prazo, escopo e preço sem desgaste.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-06-01', 'lesson-work-b1-06', 1, 'sentence', 'When do you need this by?', 'Até quando você precisa disso?', '/wɛn duː juː niːd ðɪs baɪ/', 'Neutro. "By" + data = até (no máximo).', '[]'::jsonb, '[{"surface":"When","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-02', 'lesson-work-b1-06', 2, 'sentence', 'The deadline is too tight.', 'O prazo está apertado demais.', '/ðə ˈdɛdlaɪn ɪz tuː taɪt/', 'Neutro. "Tight deadline" = prazo apertado.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"deadline","pos":"noun","ipa":"/ˈdɛdlaɪn/","gloss":"prazo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"tight","pos":"adjective","ipa":"/taɪt/","gloss":"apertado"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-03', 'lesson-work-b1-06', 3, 'sentence', 'Can we extend the deadline?', 'Podemos estender o prazo?', '/kæn wiː ɪkˈstɛnd ðə ˈdɛdlaɪn/', 'Neutro. "Extend" = prorrogar.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"extend","pos":"verb","ipa":"/ɪkˈstɛnd/","gloss":"estender, prorrogar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"deadline","pos":"noun","ipa":"/ˈdɛdlaɪn/","gloss":"prazo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-04', 'lesson-work-b1-06', 4, 'sentence', 'We can do it if we reduce the scope.', 'Conseguimos fazer se reduzirmos o escopo.', '/wiː kæn duː ɪt ɪf wiː rɪˈduːs ðə skoʊp/', 'Neutro. Condição com "if" + presente.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"reduce","pos":"verb","ipa":"/rɪˈduːs/","gloss":"reduzir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"scope","pos":"noun","ipa":"/skoʊp/","gloss":"escopo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-05', 'lesson-work-b1-06', 5, 'sentence', 'That''s our best offer.', 'Essa é nossa melhor oferta.', '/ðæts aʊər bɛst ˈɔːfər/', 'Neutro. Sinaliza limite na negociação.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"best","pos":"adjective","ipa":"/bɛst/","gloss":"melhor"},{"surface":"offer","pos":"noun","ipa":"/ˈɔːfər/","gloss":"oferta"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-06', 'lesson-work-b1-06', 6, 'sentence', 'Is there any flexibility on the price?', 'Tem alguma flexibilidade no preço?', '/ɪz ðɛr ˈɛni ˌflɛksəˈbɪləti ɑːn ðə praɪs/', 'Formal. Pergunta de negociação sem confronto.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"flexibility","pos":"noun","ipa":"/ˌflɛksəˈbɪləti/","gloss":"flexibilidade"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"price","pos":"noun","ipa":"/praɪs/","gloss":"preço"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-07', 'lesson-work-b1-06', 7, 'sentence', 'Let''s meet halfway.', 'Vamos chegar a um meio-termo.', '/lɛts miːt ˌhæfˈweɪ/', 'Informal. Literal: "vamos nos encontrar no meio do caminho".', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"halfway","pos":"adverb","ipa":"/ˌhæfˈweɪ/","gloss":"no meio do caminho"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-08', 'lesson-work-b1-06', 8, 'sentence', 'I''ll need to check with my manager.', 'Preciso ver com meu gerente.', '/aɪl niːd tuː tʃɛk wɪð maɪ ˈmænɪdʒər/', 'Neutro. Ganha tempo e divide a decisão.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"manager","pos":"noun","ipa":"/ˈmænɪdʒər/","gloss":"gerente"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-09', 'lesson-work-b1-06', 9, 'sentence', 'Can you put that in writing?', 'Pode colocar isso por escrito?', '/kæn juː pʊt ðæt ɪn ˈraɪtɪŋ/', 'Neutro. "In writing" = por escrito.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"writing","pos":"noun","ipa":"/ˈraɪtɪŋ/","gloss":"escrita"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-06-10', 'lesson-work-b1-06', 10, 'sentence', 'We have a deal.', 'Negócio fechado.', '/wiː hæv ə diːl/', 'Neutro. Fecha o acordo.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"deal","pos":"noun","ipa":"/diːl/","gloss":"negócio, coisa"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-07', 'course-work-b1', 7, 'Ligações com clientes', 'Atender, anotar recado e resolver por telefone.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-07-01', 'lesson-work-b1-07', 1, 'sentence', 'Hello, this is Ana from Linguaflow.', 'Olá, aqui é a Ana, da Linguaflow.', '/həˈloʊ ðɪs ɪz ˈænə frʌm ˈlɪŋɡwəfloʊ/', 'Neutro. Ao telefone diga "this is", nunca "I am".', '[]'::jsonb, '[{"surface":"Hello","pos":"interjection","ipa":"/həˈloʊ/","gloss":"olá"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"Ana","pos":"proper noun","ipa":"/ˈænə/","gloss":"Ana"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"Linguaflow","pos":"proper noun","ipa":"/ˈlɪŋɡwəfloʊ/","gloss":"Linguaflow"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-02', 'lesson-work-b1-07', 2, 'sentence', 'How can I help you today?', 'Como posso ajudar hoje?', '/haʊ kæn aɪ hɛlp juː təˈdeɪ/', 'Neutro. Abertura de atendimento.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-03', 'lesson-work-b1-07', 3, 'sentence', 'Could you spell your last name?', 'Pode soletrar seu sobrenome?', '/kʊd juː spɛl jʊr læst neɪm/', 'Neutro. "Last name" = sobrenome.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"spell","pos":"verb","ipa":"/spɛl/","gloss":"soletrar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"name","pos":"noun","ipa":"/neɪm/","gloss":"nome"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-04', 'lesson-work-b1-07', 4, 'sentence', 'Let me check that for you.', 'Deixa eu verificar isso para você.', '/lɛt miː tʃɛk ðæt fɔːr juː/', 'Neutro. Enquanto procura a informação.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-05', 'lesson-work-b1-07', 5, 'sentence', 'Could you hold for a moment?', 'Pode aguardar um instante?', '/kʊd juː hoʊld fɔːr ə ˈmoʊmənt/', 'Formal. "Hold" = aguardar na linha.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"hold","pos":"verb","ipa":"/hoʊld/","gloss":"aguardar (na linha), segurar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"moment","pos":"noun","ipa":"/ˈmoʊmənt/","gloss":"momento"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-06', 'lesson-work-b1-07', 6, 'sentence', 'She''s not available right now.', 'Ela não está disponível agora.', '/ʃiːz nɑːt əˈveɪləbəl raɪt naʊ/', 'Neutro. Jeito educado de dizer que a pessoa não pode atender.', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"available","pos":"adjective","ipa":"/əˈveɪləbəl/","gloss":"disponível"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-07', 'lesson-work-b1-07', 7, 'sentence', 'Can I take a message?', 'Quer deixar recado?', '/kæn aɪ teɪk ə ˈmɛsɪdʒ/', 'Neutro. "Take a message" = anotar recado.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"message","pos":"noun","ipa":"/ˈmɛsɪdʒ/","gloss":"mensagem"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-08', 'lesson-work-b1-07', 8, 'sentence', 'Sorry, you are breaking up.', 'Desculpe, está cortando.', '/ˈsɑːri juː ɑːr ˈbreɪkɪŋ ʌp/', 'Informal. "Break up" aqui = a ligação está falhando.', '[]'::jsonb, '[{"surface":"Sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"breaking","pos":"verb","ipa":"/ˈbreɪkɪŋ/","gloss":"cortando (ligação), quebrando"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-09', 'lesson-work-b1-07', 9, 'sentence', 'I will call you back in five minutes.', 'Te retorno em cinco minutos.', '/aɪ wɪl kɔːl juː bæk ɪn faɪv ˈmɪnɪts/', 'Neutro. "Call back" = retornar a ligação.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"},{"surface":"minutes","pos":"noun","ipa":"/ˈmɪnɪts/","gloss":"minutos"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-07-10', 'lesson-work-b1-07', 10, 'sentence', 'Is there anything else I can help with?', 'Posso ajudar em mais alguma coisa?', '/ɪz ðɛr ˈɛniθɪŋ ɛls aɪ kæn hɛlp wɪð/', 'Neutro. Fechamento de atendimento.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"},{"surface":"else","pos":"adverb","ipa":"/ɛls/","gloss":"mais, outro"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-08', 'course-work-b1', 8, 'Pedir ajuda e delegar', 'Distribuir tarefas e pedir apoio sem soar mandão.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-08-01', 'lesson-work-b1-08', 1, 'sentence', 'Could you help me with this report?', 'Você pode me ajudar com este relatório?', '/kʊd juː hɛlp miː wɪð ðɪs rɪˈpɔːrt/', 'Neutro. "Help with" + tarefa.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"report","pos":"verb","ipa":"/rɪˈpɔːrt/","gloss":"registrar, relatar"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-02', 'lesson-work-b1-08', 2, 'sentence', 'Would you mind taking a look?', 'Você se importaria de dar uma olhada?', '/wʊd juː maɪnd ˈteɪkɪŋ ə lʊk/', 'Formal. "Would you mind" + verbo com "-ing".', '[]'::jsonb, '[{"surface":"Would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"mind","pos":"verb","ipa":"/maɪnd/","gloss":"se importar"},{"surface":"taking","pos":"verb","ipa":"/ˈteɪkɪŋ/","gloss":"dando, pegando"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-03', 'lesson-work-b1-08', 3, 'sentence', 'Can you take care of this?', 'Você pode cuidar disso?', '/kæn juː teɪk kɛr ʌv ðɪs/', 'Neutro. "Take care of" = cuidar de, resolver.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"care","pos":"noun","ipa":"/kɛr/","gloss":"cuidado"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-04', 'lesson-work-b1-08', 4, 'sentence', 'Who is in charge of this project?', 'Quem é o responsável por este projeto?', '/huː ɪz ɪn tʃɑːrdʒ ʌv ðɪs ˈprɑːdʒɛkt/', 'Neutro. "In charge of" = responsável por.', '[]'::jsonb, '[{"surface":"Who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"charge","pos":"noun","ipa":"/tʃɑːrdʒ/","gloss":"cobrança"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"project","pos":"noun","ipa":"/ˈprɑːdʒɛkt/","gloss":"projeto"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-05', 'lesson-work-b1-08', 5, 'sentence', 'I''ll handle the slides.', 'Eu cuido dos slides.', '/aɪl ˈhændəl ðə slaɪdz/', 'Neutro. "Handle" = cuidar de, dar conta de.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"handle","pos":"verb","ipa":"/ˈhændəl/","gloss":"cuidar de, lidar com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"slides","pos":"noun","ipa":"/slaɪdz/","gloss":"slides"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-06', 'lesson-work-b1-08', 6, 'sentence', 'Let me know if you need anything.', 'Me avisa se precisar de algo.', '/lɛt miː noʊ ɪf juː niːd ˈɛniθɪŋ/', 'Neutro. Oferece apoio.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-07', 'lesson-work-b1-08', 7, 'sentence', 'I''m not sure how to do this.', 'Não sei bem como fazer isso.', '/aɪm nɑːt ʃʊr haʊ tuː duː ðɪs/', 'Neutro. Admitir a dúvida cedo evita retrabalho.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"sure","pos":"adjective","ipa":"/ʃʊr/","gloss":"claro; certo"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-08', 'lesson-work-b1-08', 8, 'sentence', 'Could you walk me through it?', 'Você pode me explicar passo a passo?', '/kʊd juː wɔːk miː θruː ɪt/', 'Informal. "Walk through" = explicar passo a passo.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-09', 'lesson-work-b1-08', 9, 'sentence', 'Can we split the tasks?', 'Podemos dividir as tarefas?', '/kæn wiː splɪt ðə tæsks/', 'Neutro. "Split" = dividir.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"split","pos":"verb","ipa":"/splɪt/","gloss":"dividir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"tasks","pos":"noun","ipa":"/tæsks/","gloss":"tarefas"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-08-10', 'lesson-work-b1-08', 10, 'sentence', 'Thanks for jumping in.', 'Obrigado por entrar para ajudar.', '/θæŋks fɔːr ˈdʒʌmpɪŋ ɪn/', 'Informal. "Jump in" = entrar para ajudar de repente.', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"jumping","pos":"verb","ipa":"/ˈdʒʌmpɪŋ/","gloss":"pulando; jumping in = entrar para ajudar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-09', 'course-work-b1', 9, 'Conversa informal no escritório', 'Small talk com colegas antes e depois das reuniões.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-09-01', 'lesson-work-b1-09', 1, 'sentence', 'How was your weekend?', 'Como foi seu fim de semana?', '/haʊ wɑːz jʊr ˈwiːkɛnd/', 'Informal. Abertura mais comum de segunda-feira.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"weekend","pos":"noun","ipa":"/ˈwiːkɛnd/","gloss":"fim de semana"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-02', 'lesson-work-b1-09', 2, 'sentence', 'Any plans for the holidays?', 'Algum plano para o feriado?', '/ˈɛni plænz fɔːr ðə ˈhɑːlədeɪz/', 'Informal. "Holidays" = feriados, férias de fim de ano.', '[]'::jsonb, '[{"surface":"Any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"plans","pos":"noun","ipa":"/plænz/","gloss":"planos"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"holidays","pos":"noun","ipa":"/ˈhɑːlədeɪz/","gloss":"feriados, férias"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-03', 'lesson-work-b1-09', 3, 'sentence', 'How''s it going with the new project?', 'Como está indo o projeto novo?', '/haʊz ɪt ˈɡoʊɪŋ wɪð ðə nuː ˈprɑːdʒɛkt/', 'Informal. "How''s it going" = como vai.', '[]'::jsonb, '[{"surface":"How''s","pos":"adverb","ipa":"/haʊz/","gloss":"como está (how is)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"project","pos":"noun","ipa":"/ˈprɑːdʒɛkt/","gloss":"projeto"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-04', 'lesson-work-b1-09', 4, 'sentence', 'Did you see the game last night?', 'Você viu o jogo ontem à noite?', '/dɪd juː siː ðə ɡeɪm læst naɪt/', 'Informal. Esporte é assunto seguro no escritório.', '[]'::jsonb, '[{"surface":"Did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"game","pos":"noun","ipa":"/ɡeɪm/","gloss":"jogo"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-05', 'lesson-work-b1-09', 5, 'sentence', 'It''s been a busy week.', 'A semana foi corrida.', '/ɪts bɪn ə ˈbɪzi wiːk/', 'Neutro. Present perfect para a semana que ainda não acabou.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"busy","pos":"adjective","ipa":"/ˈbɪzi/","gloss":"ocupado"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-06', 'lesson-work-b1-09', 6, 'sentence', 'Want to grab lunch?', 'Bora almoçar?', '/wɑːnt tuː ɡræb lʌntʃ/', 'Informal. "(Do you) want to grab lunch?".', '[]'::jsonb, '[{"surface":"Want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"grab","pos":"verb","ipa":"/ɡræb/","gloss":"pegar, comer algo rápido"},{"surface":"lunch","pos":"noun","ipa":"/lʌntʃ/","gloss":"almoço"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-07', 'lesson-work-b1-09', 7, 'sentence', 'Welcome to the team!', 'Bem-vindo ao time!', '/ˈwɛlkəm tuː ðə tiːm/', 'Neutro. Recebe colega novo.', '[]'::jsonb, '[{"surface":"Welcome","pos":"adjective","ipa":"/ˈwɛlkəm/","gloss":"bem-vindo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-08', 'lesson-work-b1-09', 8, 'sentence', 'How long have you been here?', 'Há quanto tempo você trabalha aqui?', '/haʊ lɔːŋ hæv juː bɪn hɪr/', 'Neutro. Present perfect contínuo: começou no passado e continua.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-09', 'lesson-work-b1-09', 9, 'sentence', 'Nice catching up with you.', 'Foi bom colocar o papo em dia.', '/naɪs ˈkætʃɪŋ ʌp wɪð juː/', 'Informal. "Catch up" = colocar a conversa em dia.', '[]'::jsonb, '[{"surface":"Nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"catching","pos":"verb","ipa":"/ˈkætʃɪŋ/","gloss":"pegando; catching up = pôr o papo em dia"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-09-10', 'lesson-work-b1-09', 10, 'sentence', 'See you at the meeting.', 'Te vejo na reunião.', '/siː juː æt ðə ˈmiːtɪŋ/', 'Neutro. Despedida entre colegas.', '[]'::jsonb, '[{"surface":"See","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
