-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-tenses-b1', 'verb-tenses-b1', 'Tempos Verbais em Uso', 'Os tempos verbais que mais confundem brasileiros, em pares, com a comparação com o português.', 'Presente simples × contínuo, passado simples × contínuo, present perfect × passado, present perfect contínuo, futuro (will, going to, presente contínuo) e past perfect. Cada frase explica por que aquele tempo foi usado e como fica em português.', 'B1', 'grammar', 9, 'gramatica', 2, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-tenses-b1-01', 'course-tenses-b1', 1, 'Presente simples × contínuo', 'Hábito ou fato × o que está acontecendo agora.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-tenses-b1-01-01', 'lesson-tenses-b1-01', 1, 'sentence', 'I work in a bank.', 'Trabalho num banco.', '/aɪ wɜːrk ɪn ə bæŋk/', 'Presente simples: fato permanente, rotina.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bank","pos":"noun","ipa":"/bæŋk/","gloss":"banco"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-02', 'lesson-tenses-b1-01', 2, 'sentence', 'I''m working from home this week.', 'Estou trabalhando de casa esta semana.', '/aɪm ˈwɜːrkɪŋ frʌm hoʊm ðɪs wiːk/', 'Presente contínuo: situação temporária ("this week").', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"working","pos":"verb","ipa":"/ˈwɜːrkɪŋ/","gloss":"funcionando; trabalhando"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-03', 'lesson-tenses-b1-01', 3, 'sentence', 'She usually drinks tea.', 'Ela geralmente bebe chá.', '/ʃiː ˈjuːʒuəli drɪŋks tiː/', 'Hábito com advérbio de frequência → presente simples.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"usually","pos":"adverb","ipa":"/ˈjuːʒuəli/","gloss":"geralmente"},{"surface":"drinks","pos":"verb","ipa":"/drɪŋks/","gloss":"bebe"},{"surface":"tea","pos":"noun","ipa":"/tiː/","gloss":"chá"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-04', 'lesson-tenses-b1-01', 4, 'sentence', 'She''s drinking coffee today.', 'Hoje ela está tomando café.', '/ʃiːz ˈdrɪŋkɪŋ ˈkɔːfi təˈdeɪ/', 'Exceção ao hábito, agora → contínuo.', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"drinking","pos":"verb","ipa":"/ˈdrɪŋkɪŋ/","gloss":"bebendo"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-05', 'lesson-tenses-b1-01', 5, 'sentence', 'Water boils at one hundred degrees.', 'A água ferve a cem graus.', '/ˈwɔːtər bɔɪlz æt wʌn ˈhʌndrəd dɪˈɡriːz/', 'Verdade geral → presente simples.', '[]'::jsonb, '[{"surface":"Water","pos":"noun","ipa":"/ˈwɔːtər/","gloss":"água"},{"surface":"boils","pos":"verb","ipa":"/bɔɪlz/","gloss":"ferve"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"hundred","pos":"numeral","ipa":"/ˈhʌndrəd/","gloss":"cem, centena"},{"surface":"degrees","pos":"noun","ipa":"/dɪˈɡriːz/","gloss":"graus"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-06', 'lesson-tenses-b1-01', 6, 'sentence', 'The water is boiling.', 'A água está fervendo.', '/ðə ˈwɔːtər ɪz ˈbɔɪlɪŋ/', 'Acontecendo neste momento → contínuo.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"water","pos":"noun","ipa":"/ˈwɔːtər/","gloss":"água"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"boiling","pos":"verb","ipa":"/ˈbɔɪlɪŋ/","gloss":"fervendo"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-07', 'lesson-tenses-b1-01', 7, 'sentence', 'I think you are right.', 'Acho que você tem razão.', '/aɪ θɪŋk juː ɑːr raɪt/', '"Think" de opinião não vai para o contínuo: "I''m thinking" é "estou pensando (refletindo)".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-08', 'lesson-tenses-b1-01', 8, 'sentence', 'I don''t understand this word.', 'Não entendo esta palavra.', '/aɪ doʊnt ˌʌndərˈstænd ðɪs wɜːrd/', 'Verbos de estado (understand, know, want, like) quase nunca vão para o contínuo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"word","pos":"noun","ipa":"/wɜːrd/","gloss":"palavra"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-09', 'lesson-tenses-b1-01', 9, 'sentence', 'What are you doing?', 'O que você está fazendo?', '/wʌt ɑːr juː ˈduːɪŋ/', 'Pergunta sobre agora → contínuo.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"doing","pos":"verb","ipa":"/ˈduːɪŋ/","gloss":"fazendo, fazer"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-01-10', 'lesson-tenses-b1-01', 10, 'sentence', 'What do you do?', 'O que você faz? (profissão)', '/wʌt duː juː duː/', 'Pergunta sobre o que a pessoa faz na vida → presente simples.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-tenses-b1-02', 'course-tenses-b1', 2, 'Passado simples × contínuo', 'Ação terminada × ação em andamento no passado.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-tenses-b1-02-01', 'lesson-tenses-b1-02', 1, 'sentence', 'I called you at nine.', 'Te liguei às nove.', '/aɪ kɔːld juː æt naɪn/', 'Passado simples: ação curta, terminada.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"nine","pos":"numeral","ipa":"/naɪn/","gloss":"nove"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-02', 'lesson-tenses-b1-02', 2, 'sentence', 'I was cooking when you called.', 'Eu estava cozinhando quando você ligou.', '/aɪ wɑːz ˈkʊkɪŋ wɛn juː kɔːld/', 'Contínuo = a ação longa; simples = a que interrompe.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"cooking","pos":"verb","ipa":"/ˈkʊkɪŋ/","gloss":"cozinhar (atividade)"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-03', 'lesson-tenses-b1-02', 3, 'sentence', 'It was raining all morning.', 'Choveu a manhã inteira.', '/ɪt wɑːz ˈreɪnɪŋ ɔːl ˈmɔːrnɪŋ/', 'Contínuo enfatiza a duração no passado.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"raining","pos":"verb","ipa":"/ˈreɪnɪŋ/","gloss":"chovendo"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"morning","pos":"noun","ipa":"/ˈmɔːrnɪŋ/","gloss":"manhã"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-04', 'lesson-tenses-b1-02', 4, 'sentence', 'While I was driving, I saw an accident.', 'Enquanto dirigia, vi um acidente.', '/waɪl aɪ wɑːz ˈdraɪvɪŋ aɪ sɔː ən ˈæksɪdənt/', '"While" costuma vir com o contínuo.', '[]'::jsonb, '[{"surface":"While","pos":"noun","ipa":"/waɪl/","gloss":"tempo (a while = um tempo)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"driving","pos":"verb","ipa":"/ˈdraɪvɪŋ/","gloss":"dirigindo"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"saw","pos":"verb","ipa":"/sɔː/","gloss":"viu"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"accident","pos":"noun","ipa":"/ˈæksɪdənt/","gloss":"acidente"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-05', 'lesson-tenses-b1-02', 5, 'sentence', 'What were you doing at midnight?', 'O que você estava fazendo à meia-noite?', '/wʌt wɜːr juː ˈduːɪŋ æt ˈmɪdnaɪt/', 'Pergunta sobre um momento exato do passado.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"were","pos":"verb","ipa":"/wɜːr/","gloss":"eram, estavam"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"doing","pos":"verb","ipa":"/ˈduːɪŋ/","gloss":"fazendo, fazer"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"midnight","pos":"noun","ipa":"/ˈmɪdnaɪt/","gloss":"meia-noite"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-06', 'lesson-tenses-b1-02', 6, 'sentence', 'We met in two thousand eighteen.', 'Nos conhecemos em dois mil e dezoito.', '/wiː mɛt ɪn tuː ˈθaʊzənd ˌeɪˈtiːn/', 'Data definida → passado simples.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"thousand","pos":"numeral","ipa":"/ˈθaʊzənd/","gloss":"mil"},{"surface":"eighteen","pos":"numeral","ipa":"/ˌeɪˈtiːn/","gloss":"dezoito"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-07', 'lesson-tenses-b1-02', 7, 'sentence', 'She was living in Rome at the time.', 'Ela estava morando em Roma na época.', '/ʃiː wɑːz ˈlɪvɪŋ ɪn roʊm æt ðə taɪm/', 'Situação temporária no passado → contínuo.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"living","pos":"adjective","ipa":"/ˈlɪvɪŋ/","gloss":"de estar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"Rome","pos":"proper noun","ipa":"/roʊm/","gloss":"Roma"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-08', 'lesson-tenses-b1-02', 8, 'sentence', 'I fell while I was running.', 'Caí enquanto corria.', '/aɪ fɛl waɪl aɪ wɑːz ˈrʌnɪŋ/', 'Interrupção: "fell" (simples) + "was running" (contínuo).', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"fell","pos":"verb","ipa":"/fɛl/","gloss":"caiu"},{"surface":"while","pos":"noun","ipa":"/waɪl/","gloss":"tempo (a while = um tempo)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"running","pos":"verb","ipa":"/ˈrʌnɪŋ/","gloss":"ficando (running late)"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-09', 'lesson-tenses-b1-02', 9, 'sentence', 'They were talking when the teacher came in.', 'Eles estavam conversando quando o professor entrou.', '/ðeɪ wɜːr ˈtɔːkɪŋ wɛn ðə ˈtiːtʃər keɪm ɪn/', '"Come in" = entrar.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"were","pos":"verb","ipa":"/wɜːr/","gloss":"eram, estavam"},{"surface":"talking","pos":"verb","ipa":"/ˈtɔːkɪŋ/","gloss":"conversar"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"teacher","pos":"noun","ipa":"/ˈtiːtʃər/","gloss":"professor, professora"},{"surface":"came","pos":"verb","ipa":"/keɪm/","gloss":"veio"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-02-10', 'lesson-tenses-b1-02', 10, 'sentence', 'I didn''t hear the phone. I was sleeping.', 'Não ouvi o telefone. Estava dormindo.', '/aɪ ˈdɪdənt hɪr ðə foʊn aɪ wɑːz ˈsliːpɪŋ/', 'O contínuo explica o contexto.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"hear","pos":"verb","ipa":"/hɪr/","gloss":"ouvir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"phone","pos":"noun","ipa":"/foʊn/","gloss":"celular, telefone"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"sleeping","pos":"verb","ipa":"/ˈsliːpɪŋ/","gloss":"dormindo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-tenses-b1-03', 'course-tenses-b1', 3, 'Present perfect × passado simples', 'Sem data e ligado ao agora × com data e terminado.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-tenses-b1-03-01', 'lesson-tenses-b1-03', 1, 'sentence', 'I''ve been to London.', 'Já estive em Londres.', '/aɪv bɪn tuː ˈlʌndən/', 'Present perfect: experiência de vida, sem data.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"London","pos":"proper noun","ipa":"/ˈlʌndən/","gloss":"Londres"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-02', 'lesson-tenses-b1-03', 2, 'sentence', 'I went to London in May.', 'Fui a Londres em maio.', '/aɪ wɛnt tuː ˈlʌndən ɪn meɪ/', 'Com data ("in May") → passado simples.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"London","pos":"proper noun","ipa":"/ˈlʌndən/","gloss":"Londres"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"May","pos":"modal verb","ipa":"/meɪ/","gloss":"poder (permissão formal)"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-03', 'lesson-tenses-b1-03', 3, 'sentence', 'I''ve lost my keys.', 'Perdi minhas chaves (e ainda não achei).', '/aɪv lɔːst maɪ kiːz/', 'Resultado no presente → present perfect.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-04', 'lesson-tenses-b1-03', 4, 'sentence', 'I lost my keys yesterday.', 'Perdi minhas chaves ontem.', '/aɪ lɔːst maɪ kiːz ˈjɛstərdeɪ/', '"Yesterday" exige passado simples.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-05', 'lesson-tenses-b1-03', 5, 'sentence', 'Have you ever eaten sushi?', 'Você já comeu sushi?', '/hæv juː ˈɛvər ˈiːtən ˈsuːʃi/', '"Ever" = alguma vez na vida.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"ever","pos":"adverb","ipa":"/ˈɛvər/","gloss":"alguma vez, já"},{"surface":"eaten","pos":"verb","ipa":"/ˈiːtən/","gloss":"comido"},{"surface":"sushi","pos":"noun","ipa":"/ˈsuːʃi/","gloss":"sushi"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-06', 'lesson-tenses-b1-03', 6, 'sentence', 'She hasn''t called yet.', 'Ela ainda não ligou.', '/ʃiː ˈhæzənt kɔːld jɛt/', '"Yet" no fim de negativas = ainda.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"hasn''t","pos":"verb","ipa":"/ˈhæzənt/","gloss":"não (has not)"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"yet","pos":"adverb","ipa":"/jɛt/","gloss":"ainda"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-07', 'lesson-tenses-b1-03', 7, 'sentence', 'I''ve just finished.', 'Acabei de terminar.', '/aɪv dʒʌst ˈfɪnɪʃt/', '"Just" = acabei de.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"finished","pos":"verb","ipa":"/ˈfɪnɪʃt/","gloss":"terminou, terminado"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-08', 'lesson-tenses-b1-03', 8, 'sentence', 'We''ve known each other for years.', 'Nos conhecemos há anos.', '/wiːv noʊn iːtʃ ˈʌðər fɔːr jɪrz/', 'Português usa presente + "há"; inglês usa present perfect + "for".', '[]'::jsonb, '[{"surface":"We''ve","pos":"pronoun","ipa":"/wiːv/","gloss":"nós temos (we have)"},{"surface":"known","pos":"verb","ipa":"/noʊn/","gloss":"sabido, conhecido"},{"surface":"each","pos":"determiner","ipa":"/iːtʃ/","gloss":"cada"},{"surface":"other","pos":"pronoun","ipa":"/ˈʌðər/","gloss":"outro"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-09', 'lesson-tenses-b1-03', 9, 'sentence', 'He has worked here since March.', 'Ele trabalha aqui desde março.', '/hiː hæz wɜːrkt hɪr sɪns mɑːrtʃ/', '"Since" + ponto de início, e ainda trabalha.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"since","pos":"preposition","ipa":"/sɪns/","gloss":"desde"},{"surface":"March","pos":"proper noun","ipa":"/mɑːrtʃ/","gloss":"março"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-03-10', 'lesson-tenses-b1-03', 10, 'sentence', 'Did you see the game last night?', 'Você viu o jogo ontem à noite?', '/dɪd juː siː ðə ɡeɪm læst naɪt/', '"Last night" = tempo terminado → passado simples.', '[]'::jsonb, '[{"surface":"Did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"game","pos":"noun","ipa":"/ɡeɪm/","gloss":"jogo"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-tenses-b1-04', 'course-tenses-b1', 4, 'Present perfect contínuo', 'Algo que começou e continua, com foco na duração.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-tenses-b1-04-01', 'lesson-tenses-b1-04', 1, 'sentence', 'I''ve been studying English for two years.', 'Estudo inglês há dois anos.', '/aɪv bɪn ˈstʌdiɪŋ ˈɪŋɡlɪʃ fɔːr tuː jɪrz/', 'Have been + "-ing" + "for": começou e continua.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"studying","pos":"verb","ipa":"/ˈstʌdiɪŋ/","gloss":"estudando"},{"surface":"English","pos":"proper noun","ipa":"/ˈɪŋɡlɪʃ/","gloss":"inglês"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-02', 'lesson-tenses-b1-04', 2, 'sentence', 'It''s been raining since morning.', 'Está chovendo desde de manhã.', '/ɪts bɪn ˈreɪnɪŋ sɪns ˈmɔːrnɪŋ/', '"Since" + início.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"raining","pos":"verb","ipa":"/ˈreɪnɪŋ/","gloss":"chovendo"},{"surface":"since","pos":"preposition","ipa":"/sɪns/","gloss":"desde"},{"surface":"morning","pos":"noun","ipa":"/ˈmɔːrnɪŋ/","gloss":"manhã"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-03', 'lesson-tenses-b1-04', 3, 'sentence', 'How long have you been waiting?', 'Há quanto tempo você está esperando?', '/haʊ lɔːŋ hæv juː bɪn ˈweɪtɪŋ/', '"How long" pergunta a duração.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-04', 'lesson-tenses-b1-04', 4, 'sentence', 'You look tired. Have you been working late?', 'Você parece cansado. Tem trabalhado até tarde?', '/juː lʊk ˈtaɪərd hæv juː bɪn ˈwɜːrkɪŋ leɪt/', 'Explica um resultado visível agora.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"},{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"working","pos":"verb","ipa":"/ˈwɜːrkɪŋ/","gloss":"funcionando; trabalhando"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-05', 'lesson-tenses-b1-04', 5, 'sentence', 'She''s been learning to drive.', 'Ela tem aprendido a dirigir.', '/ʃiːz bɪn ˈlɜːrnɪŋ tuː draɪv/', 'Atividade repetida recentemente.', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"learning","pos":"verb","ipa":"/ˈlɜːrnɪŋ/","gloss":"aprendendo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"drive","pos":"verb","ipa":"/draɪv/","gloss":"dirigir"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-06', 'lesson-tenses-b1-04', 6, 'sentence', 'I''ve been thinking about your idea.', 'Tenho pensado na sua ideia.', '/aɪv bɪn ˈθɪŋkɪŋ əˈbaʊt jʊr aɪˈdiːə/', 'Aqui "think" = refletir, então vai para o contínuo.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"thinking","pos":"verb","ipa":"/ˈθɪŋkɪŋ/","gloss":"pensando"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"idea","pos":"noun","ipa":"/aɪˈdiːə/","gloss":"ideia"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-07', 'lesson-tenses-b1-04', 7, 'sentence', 'We''ve been living here for ten years.', 'Moramos aqui há dez anos.', '/wiːv bɪn ˈlɪvɪŋ hɪr fɔːr tɛn jɪrz/', 'Com "live" e "work", simples e contínuo são quase iguais.', '[]'::jsonb, '[{"surface":"We''ve","pos":"pronoun","ipa":"/wiːv/","gloss":"nós temos (we have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"living","pos":"adjective","ipa":"/ˈlɪvɪŋ/","gloss":"de estar"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-08', 'lesson-tenses-b1-04', 8, 'sentence', 'I''ve been calling you all day!', 'Estou te ligando o dia todo!', '/aɪv bɪn ˈkɔːlɪŋ juː ɔːl deɪ/', 'Ênfase na repetição e na irritação.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"calling","pos":"verb","ipa":"/ˈkɔːlɪŋ/","gloss":"ligando"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-09', 'lesson-tenses-b1-04', 9, 'sentence', 'I''ve read the book.', 'Li o livro (terminei).', '/aɪv riːd ðə bʊk/', 'Present perfect simples = resultado, terminado.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"book","pos":"verb","ipa":"/bʊk/","gloss":"reservar; livro"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-04-10', 'lesson-tenses-b1-04', 10, 'sentence', 'I''ve been reading the book.', 'Estou lendo o livro (ainda não terminei).', '/aɪv bɪn ˈriːdɪŋ ðə bʊk/', 'Contínuo = atividade em andamento.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"reading","pos":"noun","ipa":"/ˈriːdɪŋ/","gloss":"leitura"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"book","pos":"verb","ipa":"/bʊk/","gloss":"reservar; livro"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-tenses-b1-05', 'course-tenses-b1', 5, 'Futuro: will, going to e presente contínuo', 'Decisão na hora, plano, previsão e compromisso marcado.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-tenses-b1-05-01', 'lesson-tenses-b1-05', 1, 'sentence', 'I''ll help you.', 'Eu te ajudo.', '/aɪl hɛlp juː/', '"Will" = decisão na hora ou oferta.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-02', 'lesson-tenses-b1-05', 2, 'sentence', 'I''m going to study medicine.', 'Vou estudar medicina.', '/aɪm ˈɡoʊɪŋ tuː ˈstʌdi ˈmɛdɪsən/', '"Going to" = plano decidido antes.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"study","pos":"verb","ipa":"/ˈstʌdi/","gloss":"estudar"},{"surface":"medicine","pos":"noun","ipa":"/ˈmɛdɪsən/","gloss":"remédio"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-03', 'lesson-tenses-b1-05', 3, 'sentence', 'I''m meeting Paul at six.', 'Vou encontrar o Paul às seis.', '/aɪm ˈmiːtɪŋ pɔːl æt sɪks/', 'Presente contínuo = compromisso com hora marcada.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"Paul","pos":"proper noun","ipa":"/pɔːl/","gloss":"Paul"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"six","pos":"numeral","ipa":"/sɪks/","gloss":"seis"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-04', 'lesson-tenses-b1-05', 4, 'sentence', 'Look at those clouds. It is going to rain.', 'Olha essas nuvens. Vai chover.', '/lʊk æt ðoʊz klaʊdz ɪt ɪz ˈɡoʊɪŋ tuː reɪn/', '"Going to" = previsão com evidência.', '[]'::jsonb, '[{"surface":"Look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"those","pos":"determiner","ipa":"/ðoʊz/","gloss":"aqueles, essas"},{"surface":"clouds","pos":"noun","ipa":"/klaʊdz/","gloss":"nuvens"},{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"rain","pos":"verb","ipa":"/reɪn/","gloss":"chover; chuva"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-05', 'lesson-tenses-b1-05', 5, 'sentence', 'I think it will be a great year.', 'Acho que vai ser um ótimo ano.', '/aɪ θɪŋk ɪt wɪl biː ə ɡreɪt jɪr/', '"Will" = previsão por opinião.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-06', 'lesson-tenses-b1-05', 6, 'sentence', 'The train leaves at eight tomorrow.', 'O trem sai às oito amanhã.', '/ðə treɪn liːvz æt eɪt təˈmɑːroʊ/', 'Horário oficial → presente simples, mesmo sendo futuro.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"train","pos":"noun","ipa":"/treɪn/","gloss":"trem"},{"surface":"leaves","pos":"verb","ipa":"/liːvz/","gloss":"sai, parte"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"eight","pos":"numeral","ipa":"/eɪt/","gloss":"oito"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-07', 'lesson-tenses-b1-05', 7, 'sentence', 'I won''t tell anyone.', 'Não vou contar para ninguém.', '/aɪ woʊnt tɛl ˈɛniwʌn/', '"Won''t" = promessa negativa.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"won''t","pos":"modal verb","ipa":"/woʊnt/","gloss":"não vai (will not)"},{"surface":"tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"anyone","pos":"pronoun","ipa":"/ˈɛniwʌn/","gloss":"alguém, ninguém"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-08', 'lesson-tenses-b1-05', 8, 'sentence', 'Will you marry me?', 'Você quer se casar comigo?', '/wɪl juː ˈmæri miː/', '"Will you" também faz pedidos.', '[]'::jsonb, '[{"surface":"Will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"marry","pos":"verb","ipa":"/ˈmæri/","gloss":"casar-se com"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-09', 'lesson-tenses-b1-05', 9, 'sentence', 'I''ll call you when I get there.', 'Te ligo quando chegar lá.', '/aɪl kɔːl juː wɛn aɪ ɡɛt ðɛr/', 'Depois de "when" no futuro, o inglês usa presente ("get").', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-05-10', 'lesson-tenses-b1-05', 10, 'sentence', 'What are you going to do after college?', 'O que você vai fazer depois da faculdade?', '/wʌt ɑːr juː ˈɡoʊɪŋ tuː duː ˈæftər ˈkɑːlɪdʒ/', 'Pergunta sobre planos → "going to".', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"college","pos":"noun","ipa":"/ˈkɑːlɪdʒ/","gloss":"faculdade"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-tenses-b1-06', 'course-tenses-b1', 6, 'Past perfect', 'O passado antes do passado.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-tenses-b1-06-01', 'lesson-tenses-b1-06', 1, 'sentence', 'When I arrived, the movie had started.', 'Quando cheguei, o filme já tinha começado.', '/wɛn aɪ əˈraɪvd ðə ˈmuːvi hæd ˈstɑːrtɪd/', 'Had + particípio = ação anterior a outra no passado.', '[]'::jsonb, '[{"surface":"When","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"arrived","pos":"verb","ipa":"/əˈraɪvd/","gloss":"chegou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"movie","pos":"noun","ipa":"/ˈmuːvi/","gloss":"filme"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"started","pos":"verb","ipa":"/ˈstɑːrtɪd/","gloss":"começado"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-02', 'lesson-tenses-b1-06', 2, 'sentence', 'I had never seen snow before that trip.', 'Eu nunca tinha visto neve antes daquela viagem.', '/aɪ hæd ˈnɛvər siːn snoʊ bɪˈfɔːr ðæt trɪp/', '"Had never" = nunca tinha.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"seen","pos":"verb","ipa":"/siːn/","gloss":"visto"},{"surface":"snow","pos":"verb","ipa":"/snoʊ/","gloss":"nevar; neve"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"trip","pos":"noun","ipa":"/trɪp/","gloss":"viagem"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-03', 'lesson-tenses-b1-06', 3, 'sentence', 'She was tired because she had worked all day.', 'Ela estava cansada porque tinha trabalhado o dia todo.', '/ʃiː wɑːz ˈtaɪərd bɪˈkɔːz ʃiː hæd wɜːrkt ɔːl deɪ/', 'Explica a causa anterior.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"},{"surface":"because","pos":"conjunction","ipa":"/bɪˈkɔːz/","gloss":"porque"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-04', 'lesson-tenses-b1-06', 4, 'sentence', 'By the time we got there, they had left.', 'Quando chegamos, eles já tinham ido embora.', '/baɪ ðə taɪm wiː ɡɑːt ðɛr ðeɪ hæd lɛft/', '"By the time" = quando (até o momento em que).', '[]'::jsonb, '[{"surface":"By","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"they","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"left","pos":"adverb","ipa":"/lɛft/","gloss":"à esquerda"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-05', 'lesson-tenses-b1-06', 5, 'sentence', 'He told me he had lost his job.', 'Ele me disse que tinha perdido o emprego.', '/hiː toʊld miː hiː hæd lɔːst hɪz dʒɑːb/', 'Discurso indireto: passado recua para past perfect.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-06', 'lesson-tenses-b1-06', 6, 'sentence', 'Had you met her before?', 'Você já tinha conhecido ela antes?', '/hæd juː mɛt hɜːr bɪˈfɔːr/', 'Pergunta: "had" antes do sujeito.', '[]'::jsonb, '[{"surface":"Had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-07', 'lesson-tenses-b1-06', 7, 'sentence', 'I realized I had forgotten my wallet.', 'Percebi que tinha esquecido a carteira.', '/aɪ ˈriːəlaɪzd aɪ hæd fərˈɡɑːtən maɪ ˈwɑːlɪt/', '"Realize" = perceber (falso cognato de "realizar").', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"realized","pos":"verb","ipa":"/ˈriːəlaɪzd/","gloss":"percebeu"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"forgotten","pos":"verb","ipa":"/fərˈɡɑːtən/","gloss":"esquecido"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"wallet","pos":"noun","ipa":"/ˈwɑːlɪt/","gloss":"carteira"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-08', 'lesson-tenses-b1-06', 8, 'sentence', 'The store had closed when I got there.', 'A loja já tinha fechado quando cheguei.', '/ðə stɔːr hæd kloʊzd wɛn aɪ ɡɑːt ðɛr/', 'Duas ações passadas; a primeira vai para o past perfect.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"store","pos":"noun","ipa":"/stɔːr/","gloss":"loja, mercado"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"closed","pos":"verb","ipa":"/kloʊzd/","gloss":"fechou, fechado"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-09', 'lesson-tenses-b1-06', 9, 'sentence', 'I didn''t go because I hadn''t finished.', 'Não fui porque não tinha terminado.', '/aɪ ˈdɪdənt ɡoʊ bɪˈkɔːz aɪ ˈhædənt ˈfɪnɪʃt/', 'Negativa: "hadn''t" + particípio.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"because","pos":"conjunction","ipa":"/bɪˈkɔːz/","gloss":"porque"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"hadn''t","pos":"verb","ipa":"/ˈhædənt/","gloss":"não tinha (had not)"},{"surface":"finished","pos":"verb","ipa":"/ˈfɪnɪʃt/","gloss":"terminou, terminado"}]'::jsonb, NULL, NULL),
  ('unit-tenses-b1-06-10', 'lesson-tenses-b1-06', 10, 'sentence', 'After she had eaten, she went to bed.', 'Depois de comer, ela foi dormir.', '/ˈæftər ʃiː hæd ˈiːtən ʃiː wɛnt tuː bɛd/', 'Com "after" o past perfect é opcional, mas marca a ordem.', '[]'::jsonb, '[{"surface":"After","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"eaten","pos":"verb","ipa":"/ˈiːtən/","gloss":"comido"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"bed","pos":"noun","ipa":"/bɛd/","gloss":"cama"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
