-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-negotiation-b2', 'meetings-negotiation-b2', 'Reuniões e Negociação', 'Conduzir reuniões, discordar com diplomacia, negociar preço e fechar acordos em inglês.', 'O inglês de quem decide e negocia: abrir e conduzir reuniões, opinar sem ser ríspido, propor, contrapropor, ceder e fechar um acordo. Cada nota explica o tom da frase (neutro, diplomático, firme) e o que evitar para não soar agressivo.', 'B2', 'business', 22, 'trabalho', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-negotiation-b2-01', 'course-negotiation-b2', 1, 'Conduzir a reunião', 'Abrir, organizar a pauta, dar a palavra e manter o foco.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-negotiation-b2-01-01', 'lesson-negotiation-b2-01', 1, 'sentence', 'Thank you all for joining on short notice.', 'Obrigado a todos por entrarem em cima da hora.', '/θæŋk juː ɔːl fɔːr ˈdʒɔɪnɪŋ ɑːn ʃɔːrt ˈnoʊtɪs/', '"On short notice" = com pouca antecedência; boa abertura de agradecimento.', '[]'::jsonb, '[{"surface":"Thank","pos":"verb","ipa":"/θæŋk/","gloss":"agradecer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"joining","pos":"verb","ipa":"/ˈdʒɔɪnɪŋ/","gloss":"entrando, participando"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"short","pos":"adjective","ipa":"/ʃɔːrt/","gloss":"curto"},{"surface":"notice","pos":"noun","ipa":"/ˈnoʊtɪs/","gloss":"aviso"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-02', 'lesson-negotiation-b2-01', 2, 'sentence', 'Let me start by going over the agenda.', 'Deixa eu começar revendo a pauta.', '/lɛt miː stɑːrt baɪ ˈɡoʊɪŋ ˈoʊvər ðə əˈdʒɛndə/', '"Go over" = revisar; "agenda" = pauta da reunião.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"start","pos":"verb","ipa":"/stɑːrt/","gloss":"começar"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"por cima; superado"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"agenda","pos":"noun","ipa":"/əˈdʒɛndə/","gloss":"pauta"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-03', 'lesson-negotiation-b2-01', 3, 'sentence', 'We have three items to cover today.', 'Temos três itens para tratar hoje.', '/wiː hæv θriː ˈaɪtəmz tuː ˈkʌvər təˈdeɪ/', '"Cover" = tratar de um assunto.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"three","pos":"numeral","ipa":"/θriː/","gloss":"três"},{"surface":"items","pos":"noun","ipa":"/ˈaɪtəmz/","gloss":"itens"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"cover","pos":"noun","ipa":"/ˈkʌvər/","gloss":"entrada (cover charge)"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-04', 'lesson-negotiation-b2-01', 4, 'sentence', 'Could we keep to the point, please?', 'Podemos manter o foco, por favor?', '/kʊd wiː kiːp tuː ðə pɔɪnt pliːz/', '"Keep to the point" corta divagações com educação.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-05', 'lesson-negotiation-b2-01', 5, 'sentence', 'I will hand over to Maria for the budget update.', 'Passo a palavra para a Maria sobre o orçamento.', '/aɪ wɪl hænd ˈoʊvər tuː məˈriːə fɔːr ðə ˈbʌdʒɪt ʌpˈdeɪt/', '"Hand over to" = passar a palavra.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"hand","pos":"noun","ipa":"/hænd/","gloss":"mão, ajuda"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"por cima; superado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"Maria","pos":"proper noun","ipa":"/məˈriːə/","gloss":"Maria (nome próprio)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"budget","pos":"noun","ipa":"/ˈbʌdʒɪt/","gloss":"orçamento"},{"surface":"update","pos":"verb","ipa":"/ʌpˈdeɪt/","gloss":"atualizar"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-06', 'lesson-negotiation-b2-01', 6, 'sentence', 'Does anyone have anything to add?', 'Alguém tem algo a acrescentar?', '/dʌz ˈɛniwʌn hæv ˈɛniθɪŋ tuː æd/', 'Convite aberto; mais suave que "any questions?".', '[]'::jsonb, '[{"surface":"Does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"anyone","pos":"pronoun","ipa":"/ˈɛniwʌn/","gloss":"alguém, ninguém"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"add","pos":"verb","ipa":"/æd/","gloss":"acrescentar"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-07', 'lesson-negotiation-b2-01', 7, 'sentence', 'We are running a bit behind schedule.', 'Estamos um pouco atrasados no horário.', '/wiː ɑːr ˈrʌnɪŋ ə bɪt bɪˈhaɪnd ˈskɛdʒuːl/', '"Behind schedule" = atrasado em relação ao previsto.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"running","pos":"verb","ipa":"/ˈrʌnɪŋ/","gloss":"ficando (running late)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"behind","pos":"preposition","ipa":"/bɪˈhaɪnd/","gloss":"atrás"},{"surface":"schedule","pos":"noun","ipa":"/ˈskɛdʒuːl/","gloss":"horário, agenda"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-08', 'lesson-negotiation-b2-01', 8, 'sentence', 'Let us park that issue and come back to it.', 'Vamos deixar esse assunto de lado e voltar a ele.', '/lɛt ʌs pɑːrk ðæt ˈɪʃuː ænd kʌm bæk tuː ɪt/', '"Park an issue" = adiar um tema sem descartá-lo.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"},{"surface":"park","pos":"verb","ipa":"/pɑːrk/","gloss":"estacionar"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"issue","pos":"noun","ipa":"/ˈɪʃuː/","gloss":"assunto, problema"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-09', 'lesson-negotiation-b2-01', 9, 'sentence', 'To sum up, we agreed on two actions.', 'Resumindo, combinamos duas ações.', '/tuː sʌm ʌp wiː əˈɡriːd ɑːn tuː ˈækʃənz/', '"To sum up" fecha com um resumo.', '[]'::jsonb, '[{"surface":"To","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"sum","pos":"verb","ipa":"/sʌm/","gloss":"somar, resumir"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"agreed","pos":"verb","ipa":"/əˈɡriːd/","gloss":"combinamos, concordamos"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"actions","pos":"noun","ipa":"/ˈækʃənz/","gloss":"ações"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-01-10', 'lesson-negotiation-b2-01', 10, 'sentence', 'I will circulate the minutes by tomorrow.', 'Vou enviar a ata até amanhã.', '/aɪ wɪl ˈsɜːrkjəleɪt ðə ˈmɪnɪts baɪ təˈmɑːroʊ/', '"Minutes" = ata da reunião; "circulate" = distribuir.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"circulate","pos":"verb","ipa":"/ˈsɜːrkjəleɪt/","gloss":"distribuir, circular"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"minutes","pos":"noun","ipa":"/ˈmɪnɪts/","gloss":"minutos"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-negotiation-b2-02', 'course-negotiation-b2', 2, 'Opinar com diplomacia', 'Concordar, discordar e questionar sem criar atrito.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-negotiation-b2-02-01', 'lesson-negotiation-b2-02', 1, 'sentence', 'I see where you are coming from.', 'Entendo o seu ponto de vista.', '/aɪ siː wɛr juː ɑːr ˈkʌmɪŋ frʌm/', '"Where you are coming from" = de onde vem seu raciocínio.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"coming","pos":"verb","ipa":"/ˈkʌmɪŋ/","gloss":"vindo"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-02', 'lesson-negotiation-b2-02', 2, 'sentence', 'That is a fair point, but I have a concern.', 'É um bom argumento, mas tenho uma preocupação.', '/ðæt ɪz ə fɛr pɔɪnt bʌt aɪ hæv ə kənˈsɜːrn/', 'Reconhece o outro lado antes de discordar.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"fair","pos":"adjective","ipa":"/fɛr/","gloss":"justo"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"concern","pos":"noun","ipa":"/kənˈsɜːrn/","gloss":"preocupação"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-03', 'lesson-negotiation-b2-02', 3, 'sentence', 'I am not sure that would work in practice.', 'Não tenho certeza de que isso funcionaria na prática.', '/aɪ æm nɑːt ʃʊr ðæt wʊd wɜːrk ɪn ˈpræktɪs/', 'Duvidar sem negar de frente.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"sure","pos":"adjective","ipa":"/ʃʊr/","gloss":"claro; certo"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"practice","pos":"noun","ipa":"/ˈpræktɪs/","gloss":"prática"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-04', 'lesson-negotiation-b2-02', 4, 'sentence', 'With respect, I think we are missing something.', 'Com todo o respeito, acho que estamos deixando algo passar.', '/wɪð rɪˈspɛkt aɪ θɪŋk wiː ɑːr ˈmɪsɪŋ ˈsʌmθɪŋ/', '"With respect" suaviza a discordância.', '[]'::jsonb, '[{"surface":"With","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"respect","pos":"noun","ipa":"/rɪˈspɛkt/","gloss":"respeito"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"missing","pos":"verb","ipa":"/ˈmɪsɪŋ/","gloss":"perdendo, deixando de captar"},{"surface":"something","pos":"pronoun","ipa":"/ˈsʌmθɪŋ/","gloss":"alguma coisa"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-05', 'lesson-negotiation-b2-02', 5, 'sentence', 'Could you walk me through your reasoning?', 'Você poderia me explicar seu raciocínio passo a passo?', '/kʊd juː wɔːk miː θruː jʊr ˈriːzənɪŋ/', '"Walk me through" = explicar em detalhe.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"reasoning","pos":"noun","ipa":"/ˈriːzənɪŋ/","gloss":"raciocínio"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-06', 'lesson-negotiation-b2-02', 6, 'sentence', 'I tend to agree, although there is a risk.', 'Tendo a concordar, embora haja um risco.', '/aɪ tɛnd tuː əˈɡriː ɔːlˈðoʊ ðɛr ɪz ə rɪsk/', '"I tend to" suaviza a concordância.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"tend","pos":"verb","ipa":"/tɛnd/","gloss":"tender"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"although","pos":"conjunction","ipa":"/ɔːlˈðoʊ/","gloss":"embora"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"risk","pos":"noun","ipa":"/rɪsk/","gloss":"risco"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-07', 'lesson-negotiation-b2-02', 7, 'sentence', 'Let me play devil''s advocate for a moment.', 'Deixa eu bancar o advogado do diabo por um momento.', '/lɛt miː pleɪ ˈdɛvəlz ˈædvəkət fɔːr ə ˈmoʊmənt/', 'Frase fixa para levantar uma objeção sem hostilidade.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"play","pos":"verb","ipa":"/pleɪ/","gloss":"jogar, tocar, brincar"},{"surface":"devil''s","pos":"noun","ipa":"/ˈdɛvəlz/","gloss":"do diabo"},{"surface":"advocate","pos":"noun","ipa":"/ˈædvəkət/","gloss":"advogado, defensor"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"moment","pos":"noun","ipa":"/ˈmoʊmənt/","gloss":"momento"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-08', 'lesson-negotiation-b2-02', 8, 'sentence', 'I would rather not commit to that yet.', 'Prefiro não me comprometer com isso ainda.', '/aɪ wʊd ˈræðər nɑːt kəˈmɪt tuː ðæt jɛt/', '"Would rather not" recusa com delicadeza.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"rather","pos":"adverb","ipa":"/ˈræðər/","gloss":"de preferência"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"commit","pos":"verb","ipa":"/kəˈmɪt/","gloss":"se comprometer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"yet","pos":"adverb","ipa":"/jɛt/","gloss":"ainda"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-09', 'lesson-negotiation-b2-02', 9, 'sentence', 'Can we explore other options first?', 'Podemos explorar outras opções antes?', '/kæn wiː ɪkˈsplɔːr ˈʌðər ˈɑːpʃənz fɜːrst/', 'Em vez de dizer "não", propõe ampliar as alternativas.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"explore","pos":"verb","ipa":"/ɪkˈsplɔːr/","gloss":"explorar"},{"surface":"other","pos":"pronoun","ipa":"/ˈʌðər/","gloss":"outro"},{"surface":"options","pos":"noun","ipa":"/ˈɑːpʃənz/","gloss":"opções"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-02-10', 'lesson-negotiation-b2-02', 10, 'sentence', 'I am afraid I have to disagree on that.', 'Infelizmente preciso discordar nesse ponto.', '/aɪ æm əˈfreɪd aɪ hæv tuː ˌdɪsəˈɡriː ɑːn ðæt/', '"I am afraid" aqui é cortesia, não medo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"afraid","pos":"adjective","ipa":"/əˈfreɪd/","gloss":"com medo"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"disagree","pos":"verb","ipa":"/ˌdɪsəˈɡriː/","gloss":"discordar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-negotiation-b2-03', 'course-negotiation-b2', 3, 'Propor e contrapropor', 'Apresentar uma oferta e responder com outra.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-negotiation-b2-03-01', 'lesson-negotiation-b2-03', 1, 'sentence', 'Here is what we are proposing.', 'Aqui está o que estamos propondo.', '/hɪr ɪz wʌt wiː ɑːr prəˈpoʊzɪŋ/', 'Abre uma proposta de forma direta e neutra.', '[]'::jsonb, '[{"surface":"Here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"proposing","pos":"verb","ipa":"/prəˈpoʊzɪŋ/","gloss":"propondo"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-02', 'lesson-negotiation-b2-03', 2, 'sentence', 'We would be willing to offer a longer contract.', 'Estaríamos dispostos a oferecer um contrato mais longo.', '/wiː wʊd biː ˈwɪlɪŋ tuː ˈɔːfər ə ˈlɔːŋɡər ˈkɑːntrækt/', '"Be willing to" mostra flexibilidade.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"willing","pos":"adjective","ipa":"/ˈwɪlɪŋ/","gloss":"disposto"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"offer","pos":"noun","ipa":"/ˈɔːfər/","gloss":"oferta"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"longer","pos":"adverb","ipa":"/ˈlɔːŋɡər/","gloss":"mais (tempo)"},{"surface":"contract","pos":"noun","ipa":"/ˈkɑːntrækt/","gloss":"contrato"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-03', 'lesson-negotiation-b2-03', 3, 'sentence', 'Would you consider a smaller order to start?', 'Vocês considerariam um pedido menor para começar?', '/wʊd juː kənˈsɪdər ə ˈsmɔːlər ˈɔːrdər tuː stɑːrt/', '"Would you consider" = pergunta educada de contraproposta.', '[]'::jsonb, '[{"surface":"Would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"consider","pos":"verb","ipa":"/kənˈsɪdər/","gloss":"considerar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"smaller","pos":"adjective","ipa":"/ˈsmɔːlər/","gloss":"menor"},{"surface":"order","pos":"verb","ipa":"/ˈɔːrdər/","gloss":"pedir (comida)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"start","pos":"verb","ipa":"/stɑːrt/","gloss":"começar"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-04', 'lesson-negotiation-b2-03', 4, 'sentence', 'How would you feel about a trial period?', 'O que você acharia de um período de teste?', '/haʊ wʊd juː fiːl əˈbaʊt ə ˈtraɪəl ˈpɪriəd/', 'Sondar a reação antes de propor de vez.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"feel","pos":"verb","ipa":"/fiːl/","gloss":"sentir"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"trial","pos":"noun","ipa":"/ˈtraɪəl/","gloss":"teste, experimental"},{"surface":"period","pos":"noun","ipa":"/ˈpɪriəd/","gloss":"período"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-05', 'lesson-negotiation-b2-03', 5, 'sentence', 'That is a little higher than we expected.', 'Isso está um pouco acima do que esperávamos.', '/ðæt ɪz ə ˈlɪtəl ˈhaɪər ðæn wiː ɪkˈspɛktɪd/', 'Recusa o valor sem dizer "no".', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"little","pos":"adjective","ipa":"/ˈlɪtəl/","gloss":"pouco, pequeno"},{"surface":"higher","pos":"adjective","ipa":"/ˈhaɪər/","gloss":"mais alto, maior"},{"surface":"than","pos":"conjunction","ipa":"/ðæn/","gloss":"do que"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"expected","pos":"verb","ipa":"/ɪkˈspɛktɪd/","gloss":"esperado"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-06', 'lesson-negotiation-b2-03', 6, 'sentence', 'We are looking for something more flexible.', 'Estamos buscando algo mais flexível.', '/wiː ɑːr ˈlʊkɪŋ fɔːr ˈsʌmθɪŋ mɔːr ˈflɛksəbəl/', 'Indica a direção desejada sem fechar a porta.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"something","pos":"pronoun","ipa":"/ˈsʌmθɪŋ/","gloss":"alguma coisa"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"flexible","pos":"adjective","ipa":"/ˈflɛksəbəl/","gloss":"flexível"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-07', 'lesson-negotiation-b2-03', 7, 'sentence', 'What would it take to move forward today?', 'O que seria preciso para avançarmos hoje?', '/wʌt wʊd ɪt teɪk tuː muːv ˈfɔːrwərd təˈdeɪ/', 'Pergunta direta que revela o que o outro lado quer.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"move","pos":"verb","ipa":"/muːv/","gloss":"mover, passar"},{"surface":"forward","pos":"adverb","ipa":"/ˈfɔːrwərd/","gloss":"adiante (look forward)"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-08', 'lesson-negotiation-b2-03', 8, 'sentence', 'If we agree to this, we need something in return.', 'Se concordarmos com isso, precisamos de algo em troca.', '/ɪf wiː əˈɡriː tuː ðɪs wiː niːd ˈsʌmθɪŋ ɪn rɪˈtɜːrn/', '"In return" = em troca; base de toda concessão.', '[]'::jsonb, '[{"surface":"If","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"something","pos":"pronoun","ipa":"/ˈsʌmθɪŋ/","gloss":"alguma coisa"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"return","pos":"adjective","ipa":"/rɪˈtɜːrn/","gloss":"de volta"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-09', 'lesson-negotiation-b2-03', 9, 'sentence', 'Let me put another option on the table.', 'Deixa eu colocar outra opção na mesa.', '/lɛt miː pʊt əˈnʌðər ˈɑːpʃən ɑːn ðə ˈteɪbəl/', '"Put on the table" = apresentar para discussão.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"another","pos":"determiner","ipa":"/əˈnʌðər/","gloss":"outro, mais um"},{"surface":"option","pos":"noun","ipa":"/ˈɑːpʃən/","gloss":"opção"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"table","pos":"noun","ipa":"/ˈteɪbəl/","gloss":"mesa"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-03-10', 'lesson-negotiation-b2-03', 10, 'sentence', 'We can meet you halfway on the delivery date.', 'Podemos chegar a um meio-termo na data de entrega.', '/wiː kæn miːt juː ˌhæfˈweɪ ɑːn ðə dɪˈlɪvəri deɪt/', '"Meet halfway" = ceder metade do caminho.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"halfway","pos":"adverb","ipa":"/ˌhæfˈweɪ/","gloss":"no meio do caminho"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"delivery","pos":"noun","ipa":"/dɪˈlɪvəri/","gloss":"entrega"},{"surface":"date","pos":"noun","ipa":"/deɪt/","gloss":"data"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-negotiation-b2-04', 'course-negotiation-b2', 4, 'Preço e condições', 'Falar de valor, desconto, prazo de pagamento e garantia.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-negotiation-b2-04-01', 'lesson-negotiation-b2-04', 1, 'sentence', 'Our rates are competitive for this market.', 'Nossos preços são competitivos para este mercado.', '/aʊər reɪts ɑːr kəmˈpɛtətɪv fɔːr ðɪs ˈmɑːrkɪt/', '"Competitive" = em linha ou abaixo da concorrência.', '[]'::jsonb, '[{"surface":"Our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"rates","pos":"noun","ipa":"/reɪts/","gloss":"preços, taxas"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"competitive","pos":"adjective","ipa":"/kəmˈpɛtətɪv/","gloss":"competitivo"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"market","pos":"noun","ipa":"/ˈmɑːrkɪt/","gloss":"mercado, feira"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-02', 'lesson-negotiation-b2-04', 2, 'sentence', 'Is there any room for a discount?', 'Há alguma margem para desconto?', '/ɪz ðɛr ˈɛni ruːm fɔːr ə ˈdɪskaʊnt/', '"Room" = margem, espaço para negociar.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"discount","pos":"noun","ipa":"/ˈdɪskaʊnt/","gloss":"desconto"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-03', 'lesson-negotiation-b2-04', 3, 'sentence', 'We can offer ten percent off for bulk orders.', 'Podemos dar dez por cento de desconto em pedidos grandes.', '/wiː kæn ˈɔːfər tɛn pərˈsɛnt ɔːf fɔːr bʌlk ˈɔːrdərz/', '"Bulk order" = pedido em grande quantidade.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"offer","pos":"noun","ipa":"/ˈɔːfər/","gloss":"oferta"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"percent","pos":"noun","ipa":"/pərˈsɛnt/","gloss":"por cento"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"bulk","pos":"noun","ipa":"/bʌlk/","gloss":"grande quantidade"},{"surface":"orders","pos":"noun","ipa":"/ˈɔːrdərz/","gloss":"pedidos"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-04', 'lesson-negotiation-b2-04', 4, 'sentence', 'What are your payment terms?', 'Quais são as suas condições de pagamento?', '/wʌt ɑːr jʊr ˈpeɪmənt tɜːrmz/', '"Terms" = condições, no plural.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"payment","pos":"noun","ipa":"/ˈpeɪmənt/","gloss":"pagamento"},{"surface":"terms","pos":"noun","ipa":"/tɜːrmz/","gloss":"condições, termos"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-05', 'lesson-negotiation-b2-04', 5, 'sentence', 'Payment is due within thirty days.', 'O pagamento vence em trinta dias.', '/ˈpeɪmənt ɪz duː wɪˈðɪn ˈθɜːrti deɪz/', '"Due within" = com vencimento em até.', '[]'::jsonb, '[{"surface":"Payment","pos":"noun","ipa":"/ˈpeɪmənt/","gloss":"pagamento"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"due","pos":"adjective","ipa":"/duː/","gloss":"devido (due to)"},{"surface":"within","pos":"preposition","ipa":"/wɪˈðɪn/","gloss":"dentro de"},{"surface":"thirty","pos":"numeral","ipa":"/ˈθɜːrti/","gloss":"trinta"},{"surface":"days","pos":"noun","ipa":"/deɪz/","gloss":"dias"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-06', 'lesson-negotiation-b2-04', 6, 'sentence', 'Does the price include delivery?', 'O preço inclui a entrega?', '/dʌz ðə praɪs ɪnˈkluːd dɪˈlɪvəri/', 'Pergunta de conferência que evita surpresa depois.', '[]'::jsonb, '[{"surface":"Does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"price","pos":"noun","ipa":"/praɪs/","gloss":"preço"},{"surface":"include","pos":"verb","ipa":"/ɪnˈkluːd/","gloss":"incluir"},{"surface":"delivery","pos":"noun","ipa":"/dɪˈlɪvəri/","gloss":"entrega"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-07', 'lesson-negotiation-b2-04', 7, 'sentence', 'There is a one-year warranty on all parts.', 'Há garantia de um ano em todas as peças.', '/ðɛr ɪz ə ˌwʌn ˈjɪr ˈwɔːrənti ɑːn ɔːl pɑːrts/', '"Warranty" = garantia do produto.', '[]'::jsonb, '[{"surface":"There","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"one-year","pos":"adjective","ipa":"/ˌwʌn ˈjɪr/","gloss":"de um ano"},{"surface":"warranty","pos":"noun","ipa":"/ˈwɔːrənti/","gloss":"garantia"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"parts","pos":"noun","ipa":"/pɑːrts/","gloss":"peças, partes"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-08', 'lesson-negotiation-b2-04', 8, 'sentence', 'We would need a deposit up front.', 'Precisaríamos de um sinal adiantado.', '/wiː wʊd niːd ə dɪˈpɑːzɪt ʌp frʌnt/', '"Up front" = adiantado, no início.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"deposit","pos":"noun","ipa":"/dɪˈpɑːzɪt/","gloss":"depósito, caução"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"front","pos":"noun","ipa":"/frʌnt/","gloss":"frente"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-09', 'lesson-negotiation-b2-04', 9, 'sentence', 'That figure is not within our budget.', 'Esse valor não cabe no nosso orçamento.', '/ðæt ˈfɪɡjər ɪz nɑːt wɪˈðɪn aʊər ˈbʌdʒɪt/', '"Within budget" = dentro do orçamento.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"figure","pos":"noun","ipa":"/ˈfɪɡjər/","gloss":"valor, número"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"within","pos":"preposition","ipa":"/wɪˈðɪn/","gloss":"dentro de"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"budget","pos":"noun","ipa":"/ˈbʌdʒɪt/","gloss":"orçamento"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-04-10', 'lesson-negotiation-b2-04', 10, 'sentence', 'Could you send us a revised quote?', 'Vocês poderiam nos enviar uma cotação revisada?', '/kʊd juː sɛnd ʌs ə rɪˈvaɪzd kwoʊt/', '"Quote" = cotação, orçamento formal.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"send","pos":"verb","ipa":"/sɛnd/","gloss":"enviar, mandar"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"revised","pos":"adjective","ipa":"/rɪˈvaɪzd/","gloss":"revisado"},{"surface":"quote","pos":"noun","ipa":"/kwoʊt/","gloss":"cotação, orçamento"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-negotiation-b2-05', 'course-negotiation-b2', 5, 'Objeções e concessões', 'Resistir, ceder e condicionar, mantendo a relação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-negotiation-b2-05-01', 'lesson-negotiation-b2-05', 1, 'sentence', 'I understand your position, but we cannot go that far.', 'Entendo sua posição, mas não podemos ir tão longe.', '/aɪ ˌʌndərˈstænd jʊr pəˈzɪʃən bʌt wiː ˈkænɑːt ɡoʊ ðæt fɑːr/', 'Reconhece e limita na mesma frase.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"position","pos":"noun","ipa":"/pəˈzɪʃən/","gloss":"cargo, vaga"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"cannot","pos":"verb","ipa":"/ˈkænɑːt/","gloss":"não posso, não consigo"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"far","pos":"adjective","ipa":"/fɑːr/","gloss":"longe"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-02', 'lesson-negotiation-b2-05', 2, 'sentence', 'That is a deal breaker for us.', 'Isso é um impeditivo para nós.', '/ðæt ɪz ə diːl ˈbreɪkər fɔːr ʌs/', '"Deal breaker" = condição que inviabiliza o negócio.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"deal","pos":"noun","ipa":"/diːl/","gloss":"negócio, coisa"},{"surface":"breaker","pos":"noun","ipa":"/ˈbreɪkər/","gloss":"o que quebra, impeditivo"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-03', 'lesson-negotiation-b2-05', 3, 'sentence', 'We could make an exception this once.', 'Poderíamos abrir uma exceção desta vez.', '/wiː kʊd meɪk ən ɪkˈsɛpʃən ðɪs wʌns/', '"Make an exception" = abrir uma exceção.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"exception","pos":"noun","ipa":"/ɪkˈsɛpʃən/","gloss":"exceção"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"once","pos":"adverb","ipa":"/wʌns/","gloss":"uma vez"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-04', 'lesson-negotiation-b2-05', 4, 'sentence', 'I am prepared to compromise on the timeline.', 'Estou disposto a ceder no cronograma.', '/aɪ æm prɪˈpɛrd tuː ˈkɑːmprəmaɪz ɑːn ðə ˈtaɪmlaɪn/', '"Compromise on" = ceder em um ponto.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"prepared","pos":"adjective","ipa":"/prɪˈpɛrd/","gloss":"disposto, preparado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"compromise","pos":"verb","ipa":"/ˈkɑːmprəmaɪz/","gloss":"ceder, fazer concessão"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"timeline","pos":"noun","ipa":"/ˈtaɪmlaɪn/","gloss":"cronograma, linha do tempo"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-05', 'lesson-negotiation-b2-05', 5, 'sentence', 'We are not in a position to agree to that.', 'Não estamos em condição de aceitar isso.', '/wiː ɑːr nɑːt ɪn ə pəˈzɪʃən tuː əˈɡriː tuː ðæt/', 'Recusa formal que evita culpar a pessoa.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"position","pos":"noun","ipa":"/pəˈzɪʃən/","gloss":"cargo, vaga"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-06', 'lesson-negotiation-b2-05', 6, 'sentence', 'Provided that you sign today, we can do it.', 'Desde que vocês assinem hoje, conseguimos fazer.', '/prəˈvaɪdɪd ðæt juː saɪn təˈdeɪ wiː kæn duː ɪt/', '"Provided that" = desde que; condição firme.', '[]'::jsonb, '[{"surface":"Provided","pos":"conjunction","ipa":"/prəˈvaɪdɪd/","gloss":"desde que"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"sign","pos":"verb","ipa":"/saɪn/","gloss":"assinar"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-07', 'lesson-negotiation-b2-05', 7, 'sentence', 'Let us find some common ground.', 'Vamos encontrar um ponto em comum.', '/lɛt ʌs faɪnd sʌm ˈkɑːmən ɡraʊnd/', '"Common ground" = terreno comum.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"},{"surface":"find","pos":"verb","ipa":"/faɪnd/","gloss":"encontrar"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"common","pos":"adjective","ipa":"/ˈkɑːmən/","gloss":"comum"},{"surface":"ground","pos":"noun","ipa":"/ɡraʊnd/","gloss":"chão, terreno"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-08', 'lesson-negotiation-b2-05', 8, 'sentence', 'We are open to suggestions on this point.', 'Estamos abertos a sugestões neste ponto.', '/wiː ɑːr ˈoʊpən tuː səɡˈdʒɛstʃənz ɑːn ðɪs pɔɪnt/', 'Convida o outro lado a propor.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"suggestions","pos":"noun","ipa":"/səɡˈdʒɛstʃənz/","gloss":"sugestões"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-09', 'lesson-negotiation-b2-05', 9, 'sentence', 'I wish I could help, but my hands are tied.', 'Eu queria poder ajudar, mas estou de mãos atadas.', '/aɪ wɪʃ aɪ kʊd hɛlp bʌt maɪ hændz ɑːr taɪd/', '"My hands are tied" = não tenho autonomia para decidir.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"wish","pos":"verb","ipa":"/wɪʃ/","gloss":"desejar"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"hands","pos":"noun","ipa":"/hændz/","gloss":"mãos"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"tied","pos":"verb","ipa":"/taɪd/","gloss":"amarrou, deu (o nó)"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-05-10', 'lesson-negotiation-b2-05', 10, 'sentence', 'That is as far as we can go.', 'Esse é o nosso limite.', '/ðæt ɪz æz fɑːr æz wiː kæn ɡoʊ/', 'Fecha uma negociação sem espaço para ceder mais.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"as","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"far","pos":"adjective","ipa":"/fɑːr/","gloss":"longe"},{"surface":"as","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-negotiation-b2-06', 'course-negotiation-b2', 6, 'Fechar o acordo', 'Confirmar o que foi combinado e definir os próximos passos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-negotiation-b2-06-01', 'lesson-negotiation-b2-06', 1, 'sentence', 'So, do we have a deal?', 'Então, estamos combinados?', '/soʊ duː wiː hæv ə diːl/', '"Do we have a deal?" propõe fechar na hora.', '[]'::jsonb, '[{"surface":"So","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"deal","pos":"noun","ipa":"/diːl/","gloss":"negócio, coisa"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-02', 'lesson-negotiation-b2-06', 2, 'sentence', 'I think we are all on the same page now.', 'Acho que agora estamos todos alinhados.', '/aɪ θɪŋk wiː ɑːr ɔːl ɑːn ðə seɪm peɪdʒ naʊ/', '"On the same page" = alinhados.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"same","pos":"adjective","ipa":"/seɪm/","gloss":"mesmo"},{"surface":"page","pos":"noun","ipa":"/peɪdʒ/","gloss":"página"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-03', 'lesson-negotiation-b2-06', 3, 'sentence', 'Let me confirm what we have agreed.', 'Deixa eu confirmar o que combinamos.', '/lɛt miː kənˈfɜːrm wʌt wiː hæv əˈɡriːd/', 'Recapitular evita mal-entendidos.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"confirm","pos":"verb","ipa":"/kənˈfɜːrm/","gloss":"confirmar"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"agreed","pos":"verb","ipa":"/əˈɡriːd/","gloss":"combinamos, concordamos"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-04', 'lesson-negotiation-b2-06', 4, 'sentence', 'We will draw up the contract this week.', 'Vamos redigir o contrato esta semana.', '/wiː wɪl drɔː ʌp ðə ˈkɑːntrækt ðɪs wiːk/', '"Draw up" = redigir um documento formal.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"draw","pos":"verb","ipa":"/drɔː/","gloss":"redigir, desenhar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"contract","pos":"noun","ipa":"/ˈkɑːntrækt/","gloss":"contrato"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-05', 'lesson-negotiation-b2-06', 5, 'sentence', 'Please review the terms before you sign.', 'Revise as condições antes de assinar, por favor.', '/pliːz rɪˈvjuː ðə tɜːrmz bɪˈfɔːr juː saɪn/', '"Sign" = assinar; "review" = revisar.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"review","pos":"noun","ipa":"/rɪˈvjuː/","gloss":"avaliação"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"terms","pos":"noun","ipa":"/tɜːrmz/","gloss":"condições, termos"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"sign","pos":"verb","ipa":"/saɪn/","gloss":"assinar"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-06', 'lesson-negotiation-b2-06', 6, 'sentence', 'I will follow up with a summary in writing.', 'Vou enviar um resumo por escrito em seguida.', '/aɪ wɪl ˈfɑːloʊ ʌp wɪð ə ˈsʌməri ɪn ˈraɪtɪŋ/', '"Follow up" = dar continuidade depois.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"follow","pos":"verb","ipa":"/ˈfɑːloʊ/","gloss":"seguir"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"summary","pos":"noun","ipa":"/ˈsʌməri/","gloss":"resumo"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"writing","pos":"noun","ipa":"/ˈraɪtɪŋ/","gloss":"escrita"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-07', 'lesson-negotiation-b2-06', 7, 'sentence', 'We are happy to move ahead on these terms.', 'Teremos prazer em seguir adiante nestas condições.', '/wiː ɑːr ˈhæpi tuː muːv əˈhɛd ɑːn ðiːz tɜːrmz/', 'Aceita formalmente a proposta.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"happy","pos":"adjective","ipa":"/ˈhæpi/","gloss":"feliz"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"move","pos":"verb","ipa":"/muːv/","gloss":"mover, passar"},{"surface":"ahead","pos":"adverb","ipa":"/əˈhɛd/","gloss":"à frente, adiante"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"these","pos":"determiner","ipa":"/ðiːz/","gloss":"estes, estas"},{"surface":"terms","pos":"noun","ipa":"/tɜːrmz/","gloss":"condições, termos"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-08', 'lesson-negotiation-b2-06', 8, 'sentence', 'Congratulations, this is a win for both sides.', 'Parabéns, é bom para os dois lados.', '/kənˌɡrætʃəˈleɪʃənz ðɪs ɪz ə wɪn fɔːr boʊθ saɪdz/', '"Win-win" é a ideia de um acordo bom para todos.', '[]'::jsonb, '[{"surface":"Congratulations","pos":"noun","ipa":"/kənˌɡrætʃəˈleɪʃənz/","gloss":"parabéns"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"win","pos":"noun","ipa":"/wɪn/","gloss":"vitória, conquista"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"both","pos":"determiner","ipa":"/boʊθ/","gloss":"ambos"},{"surface":"sides","pos":"noun","ipa":"/saɪdz/","gloss":"lados"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-09', 'lesson-negotiation-b2-06', 9, 'sentence', 'Who will be the point of contact?', 'Quem será o ponto de contato?', '/huː wɪl biː ðə pɔɪnt ʌv ˈkɑːntækt/', '"Point of contact" = responsável pela comunicação.', '[]'::jsonb, '[{"surface":"Who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"contact","pos":"verb","ipa":"/ˈkɑːntækt/","gloss":"contatar"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-06-10', 'lesson-negotiation-b2-06', 10, 'sentence', 'Let us schedule a check-in for next month.', 'Vamos marcar um alinhamento para o mês que vem.', '/lɛt ʌs ˈskɛdʒuːl ə ˈtʃɛk ɪn fɔːr nɛkst mʌnθ/', '"Check-in" = encontro de acompanhamento.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"},{"surface":"schedule","pos":"noun","ipa":"/ˈskɛdʒuːl/","gloss":"horário, agenda"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"check-in","pos":"noun","ipa":"/ˈtʃɛk ɪn/","gloss":"alinhamento, encontro de acompanhamento"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-negotiation-b2-07', 'course-negotiation-b2', 7, 'Apresentar resultados', 'Falar de números, tendências e comparações.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-negotiation-b2-07-01', 'lesson-negotiation-b2-07', 1, 'sentence', 'Sales rose by twelve percent last quarter.', 'As vendas subiram doze por cento no último trimestre.', '/seɪlz roʊz baɪ twɛlv pərˈsɛnt læst ˈkwɔːrtər/', '"Rise by" indica o tamanho da variação.', '[]'::jsonb, '[{"surface":"Sales","pos":"noun","ipa":"/seɪlz/","gloss":"vendas"},{"surface":"rose","pos":"verb","ipa":"/roʊz/","gloss":"subiu"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"twelve","pos":"numeral","ipa":"/twɛlv/","gloss":"doze"},{"surface":"percent","pos":"noun","ipa":"/pərˈsɛnt/","gloss":"por cento"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"quarter","pos":"noun","ipa":"/ˈkwɔːrtər/","gloss":"quarto (15 minutos)"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-02', 'lesson-negotiation-b2-07', 2, 'sentence', 'Revenue has remained steady this year.', 'A receita se manteve estável neste ano.', '/ˈrɛvənuː hæz rɪˈmeɪnd ˈstɛdi ðɪs jɪr/', '"Remain steady" = ficar estável.', '[]'::jsonb, '[{"surface":"Revenue","pos":"noun","ipa":"/ˈrɛvənuː/","gloss":"receita"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"remained","pos":"verb","ipa":"/rɪˈmeɪnd/","gloss":"permaneceu"},{"surface":"steady","pos":"adjective","ipa":"/ˈstɛdi/","gloss":"estável"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-03', 'lesson-negotiation-b2-07', 3, 'sentence', 'Costs dropped sharply after the change.', 'Os custos caíram bruscamente depois da mudança.', '/kɔːsts drɑːpt ˈʃɑːrpli ˈæftər ðə tʃeɪndʒ/', '"Sharply" = de forma brusca.', '[]'::jsonb, '[{"surface":"Costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"},{"surface":"dropped","pos":"verb","ipa":"/drɑːpt/","gloss":"caiu"},{"surface":"sharply","pos":"adverb","ipa":"/ˈʃɑːrpli/","gloss":"bruscamente"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-04', 'lesson-negotiation-b2-07', 4, 'sentence', 'We are slightly ahead of our target.', 'Estamos um pouco à frente da meta.', '/wiː ɑːr ˈslaɪtli əˈhɛd ʌv aʊər ˈtɑːrɡɪt/', '"Ahead of target" = acima da meta.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"slightly","pos":"adverb","ipa":"/ˈslaɪtli/","gloss":"ligeiramente"},{"surface":"ahead","pos":"adverb","ipa":"/əˈhɛd/","gloss":"à frente, adiante"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"target","pos":"noun","ipa":"/ˈtɑːrɡɪt/","gloss":"meta, alvo"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-05', 'lesson-negotiation-b2-07', 5, 'sentence', 'The figures speak for themselves.', 'Os números falam por si.', '/ðə ˈfɪɡjərz spiːk fɔːr ðəmˈsɛlvz/', 'Expressão para dizer que os dados são convincentes.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"figures","pos":"noun","ipa":"/ˈfɪɡjərz/","gloss":"números, dados"},{"surface":"speak","pos":"verb","ipa":"/spiːk/","gloss":"falar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"themselves","pos":"pronoun","ipa":"/ðəmˈsɛlvz/","gloss":"eles mesmos"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-06', 'lesson-negotiation-b2-07', 6, 'sentence', 'Compared to last year, profits are up.', 'Em comparação com o ano passado, os lucros subiram.', '/kəmˈpɛrd tuː læst jɪr ˈprɑːfɪts ɑːr ʌp/', '"Compared to" abre uma comparação.', '[]'::jsonb, '[{"surface":"Compared","pos":"verb","ipa":"/kəmˈpɛrd/","gloss":"comparado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"},{"surface":"profits","pos":"noun","ipa":"/ˈprɑːfɪts/","gloss":"lucros"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-07', 'lesson-negotiation-b2-07', 7, 'sentence', 'This trend is expected to continue.', 'Espera-se que essa tendência continue.', '/ðɪs trɛnd ɪz ɪkˈspɛktɪd tuː kənˈtɪnjuː/', '"Expected to" = a previsão é que.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"trend","pos":"noun","ipa":"/trɛnd/","gloss":"tendência"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"expected","pos":"verb","ipa":"/ɪkˈspɛktɪd/","gloss":"esperado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"continue","pos":"verb","ipa":"/kənˈtɪnjuː/","gloss":"continuar"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-08', 'lesson-negotiation-b2-07', 8, 'sentence', 'The main driver of growth was online sales.', 'O principal motor do crescimento foi a venda online.', '/ðə meɪn ˈdraɪvər ʌv ɡroʊθ wɑːz ˌɑːnˈlaɪn seɪlz/', '"Driver" = fator que impulsiona.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"main","pos":"adjective","ipa":"/meɪn/","gloss":"principal"},{"surface":"driver","pos":"noun","ipa":"/ˈdraɪvər/","gloss":"motorista"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"growth","pos":"noun","ipa":"/ɡroʊθ/","gloss":"crescimento"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"online","pos":"adverb","ipa":"/ˌɑːnˈlaɪn/","gloss":"na internet"},{"surface":"sales","pos":"noun","ipa":"/seɪlz/","gloss":"vendas"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-09', 'lesson-negotiation-b2-07', 9, 'sentence', 'As you can see on this slide, the gap is closing.', 'Como vocês podem ver neste slide, a diferença está diminuindo.', '/æz juː kæn siː ɑːn ðɪs slaɪd ðə ɡæp ɪz ˈkloʊzɪŋ/', '"Gap" = diferença, lacuna.', '[]'::jsonb, '[{"surface":"As","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"slide","pos":"noun","ipa":"/slaɪd/","gloss":"slide"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"gap","pos":"noun","ipa":"/ɡæp/","gloss":"diferença, lacuna"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"closing","pos":"verb","ipa":"/ˈkloʊzɪŋ/","gloss":"fechando"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-07-10', 'lesson-negotiation-b2-07', 10, 'sentence', 'Let me highlight the key takeaway.', 'Deixa eu destacar o ponto principal.', '/lɛt miː ˈhaɪlaɪt ðə kiː ˈteɪkəweɪ/', '"Key takeaway" = lição ou conclusão central.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"highlight","pos":"verb","ipa":"/ˈhaɪlaɪt/","gloss":"destacar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"key","pos":"noun","ipa":"/kiː/","gloss":"chave"},{"surface":"takeaway","pos":"noun","ipa":"/ˈteɪkəweɪ/","gloss":"mensagem principal"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-negotiation-b2-08', 'course-negotiation-b2', 8, 'Conflitos e prazos', 'Atrasos, falhas de entrega e conversas difíceis.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-negotiation-b2-08-01', 'lesson-negotiation-b2-08', 1, 'sentence', 'I am afraid we will miss the deadline.', 'Receio que a gente perca o prazo.', '/aɪ æm əˈfreɪd wiː wɪl mɪs ðə ˈdɛdlaɪn/', 'Dá a má notícia com tom cuidadoso.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"afraid","pos":"adjective","ipa":"/əˈfreɪd/","gloss":"com medo"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"miss","pos":"verb","ipa":"/mɪs/","gloss":"errar, perder; sentir falta"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"deadline","pos":"noun","ipa":"/ˈdɛdlaɪn/","gloss":"prazo"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-02', 'lesson-negotiation-b2-08', 2, 'sentence', 'The delay was due to circumstances beyond our control.', 'O atraso foi causado por fatores fora do nosso controle.', '/ðə dɪˈleɪ wɑːz duː tuː ˈsɜːrkəmstænsɪz biˈɑːnd aʊər kənˈtroʊl/', '"Beyond our control" = fora do nosso alcance.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"delay","pos":"noun","ipa":"/dɪˈleɪ/","gloss":"atraso"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"due","pos":"adjective","ipa":"/duː/","gloss":"devido (due to)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"circumstances","pos":"noun","ipa":"/ˈsɜːrkəmstænsɪz/","gloss":"circunstâncias"},{"surface":"beyond","pos":"preposition","ipa":"/biˈɑːnd/","gloss":"além de, fora de"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"control","pos":"noun","ipa":"/kənˈtroʊl/","gloss":"controle"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-03', 'lesson-negotiation-b2-08', 3, 'sentence', 'We take full responsibility for the error.', 'Assumimos toda a responsabilidade pelo erro.', '/wiː teɪk fʊl rɪˌspɑːnsəˈbɪləti fɔːr ðə ˈɛrər/', 'Assumir sem rodeios gera confiança.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"full","pos":"adjective","ipa":"/fʊl/","gloss":"cheio"},{"surface":"responsibility","pos":"noun","ipa":"/rɪˌspɑːnsəˈbɪləti/","gloss":"responsabilidade"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"error","pos":"noun","ipa":"/ˈɛrər/","gloss":"erro"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-04', 'lesson-negotiation-b2-08', 4, 'sentence', 'How can we put this right?', 'Como podemos corrigir isso?', '/haʊ kæn wiː pʊt ðɪs raɪt/', '"Put right" = corrigir, resolver.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-05', 'lesson-negotiation-b2-08', 5, 'sentence', 'We need to escalate this to management.', 'Precisamos levar isso à gerência.', '/wiː niːd tuː ˈɛskəleɪt ðɪs tuː ˈmænɪdʒmənt/', '"Escalate" = subir o problema para um nível acima.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"escalate","pos":"verb","ipa":"/ˈɛskəleɪt/","gloss":"escalar, levar a um nível acima"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"management","pos":"noun","ipa":"/ˈmænɪdʒmənt/","gloss":"gerência, gestão"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-06', 'lesson-negotiation-b2-08', 6, 'sentence', 'I would like to clear up a misunderstanding.', 'Gostaria de esclarecer um mal-entendido.', '/aɪ wʊd laɪk tuː klɪr ʌp ə ˌmɪsʌndərˈstændɪŋ/', '"Clear up" = esclarecer.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"clear","pos":"adjective","ipa":"/klɪr/","gloss":"claro"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"misunderstanding","pos":"noun","ipa":"/ˌmɪsʌndərˈstændɪŋ/","gloss":"mal-entendido"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-07', 'lesson-negotiation-b2-08', 7, 'sentence', 'Let us not jump to conclusions.', 'Vamos não tirar conclusões precipitadas.', '/lɛt ʌs nɑːt dʒʌmp tuː kənˈkluːʒənz/', '"Jump to conclusions" = concluir cedo demais.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"jump","pos":"verb","ipa":"/dʒʌmp/","gloss":"pular"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"conclusions","pos":"noun","ipa":"/kənˈkluːʒənz/","gloss":"conclusões"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-08', 'lesson-negotiation-b2-08', 8, 'sentence', 'Can we agree on a realistic new date?', 'Podemos combinar uma nova data realista?', '/kæn wiː əˈɡriː ɑːn ə ˌriːəˈlɪstɪk nuː deɪt/', 'Busca solução em vez de culpa.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"realistic","pos":"adjective","ipa":"/ˌriːəˈlɪstɪk/","gloss":"realista"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"date","pos":"noun","ipa":"/deɪt/","gloss":"data"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-09', 'lesson-negotiation-b2-08', 9, 'sentence', 'I understand your frustration, and I am sorry.', 'Entendo sua frustração e peço desculpas.', '/aɪ ˌʌndərˈstænd jʊr frʌˈstreɪʃən ænd aɪ æm ˈsɑːri/', 'Reconhece a emoção antes da solução.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"frustration","pos":"noun","ipa":"/frʌˈstreɪʃən/","gloss":"frustração"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"}]'::jsonb, NULL, NULL),
  ('unit-negotiation-b2-08-10', 'lesson-negotiation-b2-08', 10, 'sentence', 'We will keep you updated every step of the way.', 'Vamos manter você informado a cada etapa.', '/wiː wɪl kiːp juː ʌpˈdeɪtɪd ˈɛvri stɛp ʌv ðə weɪ/', '"Every step of the way" = durante todo o caminho.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"updated","pos":"verb","ipa":"/ʌpˈdeɪtɪd/","gloss":"atualizado"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"step","pos":"verb","ipa":"/stɛp/","gloss":"dar um passo, passar"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
