-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-connected-speech-b2', 'connected-speech-b2', 'Fala Conectada', 'Shoulda, gonna, whaddya, kinda e a ligação entre palavras: o inglês falado como ele soa, não como se escreve.', 'Na fala rápida as palavras se juntam e se encurtam: "should have" vira "shoulda", "what do you" vira "whaddya", "pick it up" soa como uma palavra só. Cada frase mostra a forma reduzida, a forma completa e quando usar. O áudio é sintetizado a partir do texto escrito; escute com atenção e compare com a fala real de séries e vídeos.', 'B2', 'street-slang', 28, 'fluencia', 7, false, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-connected-b2-01', 'course-connected-speech-b2', 1, 'Should have, could have, would have', 'Shoulda, coulda, woulda, musta e mighta.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-connected-b2-01-01', 'lesson-connected-b2-01', 1, 'sentence', 'I shoulda called you yesterday.', 'Eu devia ter te ligado ontem.', '/aɪ ˈʃʊdə kɔːld juː ˈjɛstərdeɪ/', '"Shoulda" = should have; só na fala e em mensagens informais.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"shoulda","pos":"verb","ipa":"/ˈʃʊdə/","gloss":"devia ter (should have)"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-02', 'lesson-connected-b2-01', 2, 'sentence', 'She coulda won if she had trained more.', 'Ela poderia ter ganhado se tivesse treinado mais.', '/ʃiː ˈkʊdə wʌn ɪf ʃiː hæd treɪnd mɔːr/', '"Coulda" = could have.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"coulda","pos":"verb","ipa":"/ˈkʊdə/","gloss":"podia ter (could have)"},{"surface":"won","pos":"verb","ipa":"/wʌn/","gloss":"ganhou"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"trained","pos":"verb","ipa":"/treɪnd/","gloss":"treinou"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-03', 'lesson-connected-b2-01', 3, 'sentence', 'We woulda come, but the car broke down.', 'A gente teria ido, mas o carro quebrou.', '/wiː ˈwʊdə kʌm bʌt ðə kɑːr broʊk daʊn/', '"Woulda" = would have.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"woulda","pos":"verb","ipa":"/ˈwʊdə/","gloss":"teria (would have)"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"broke","pos":"verb","ipa":"/broʊk/","gloss":"quebrou"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-04', 'lesson-connected-b2-01', 4, 'sentence', 'He musta forgotten the meeting.', 'Ele deve ter esquecido a reunião.', '/hiː ˈmʌstə fərˈɡɑːtən ðə ˈmiːtɪŋ/', '"Musta" = must have, para dedução no passado.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"musta","pos":"verb","ipa":"/ˈmʌstə/","gloss":"deve ter (must have)"},{"surface":"forgotten","pos":"verb","ipa":"/fərˈɡɑːtən/","gloss":"esquecido"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-05', 'lesson-connected-b2-01', 5, 'sentence', 'They mighta left already.', 'Eles podem já ter saído.', '/ðeɪ ˈmaɪtə lɛft ɔːlˈrɛdi/', '"Mighta" = might have.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"mighta","pos":"verb","ipa":"/ˈmaɪtə/","gloss":"pode ter (might have)"},{"surface":"left","pos":"adverb","ipa":"/lɛft/","gloss":"à esquerda"},{"surface":"already","pos":"adverb","ipa":"/ɔːlˈrɛdi/","gloss":"já"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-06', 'lesson-connected-b2-01', 6, 'sentence', 'You shoulda seen his face.', 'Você devia ter visto a cara dele.', '/juː ˈʃʊdə siːn hɪz feɪs/', 'Frase comum para contar algo engraçado.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"shoulda","pos":"verb","ipa":"/ˈʃʊdə/","gloss":"devia ter (should have)"},{"surface":"seen","pos":"verb","ipa":"/siːn/","gloss":"visto"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"face","pos":"noun","ipa":"/feɪs/","gloss":"rosto"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-07', 'lesson-connected-b2-01', 7, 'sentence', 'I coulda sworn I locked the door.', 'Eu podia jurar que tranquei a porta.', '/aɪ ˈkʊdə swɔːrn aɪ lɑːkt ðə dɔːr/', '"Coulda sworn" é expressão fixa.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"coulda","pos":"verb","ipa":"/ˈkʊdə/","gloss":"podia ter (could have)"},{"surface":"sworn","pos":"verb","ipa":"/swɔːrn/","gloss":"jurado"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"locked","pos":"verb","ipa":"/lɑːkt/","gloss":"trancou, tranquei"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"door","pos":"noun","ipa":"/dɔːr/","gloss":"porta"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-08', 'lesson-connected-b2-01', 8, 'sentence', 'It woulda been great to see you.', 'Teria sido ótimo te ver.', '/ɪt ˈwʊdə bɪn ɡreɪt tuː siː juː/', '"Woulda been" = would have been.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"woulda","pos":"verb","ipa":"/ˈwʊdə/","gloss":"teria (would have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-09', 'lesson-connected-b2-01', 9, 'sentence', 'Whoever did this shoulda known better.', 'Quem fez isso devia ter tido mais juízo.', '/huːˈɛvər dɪd ðɪs ˈʃʊdə noʊn ˈbɛtər/', '"Shoulda known better" = should have known better: devia ter percebido que aquilo era uma má ideia.', '[]'::jsonb, '[{"surface":"Whoever","pos":"pronoun","ipa":"/huːˈɛvər/","gloss":"quem quer que"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"shoulda","pos":"verb","ipa":"/ˈʃʊdə/","gloss":"devia ter (should have)"},{"surface":"known","pos":"verb","ipa":"/noʊn/","gloss":"sabido, conhecido"},{"surface":"better","pos":"adjective","ipa":"/ˈbɛtər/","gloss":"melhor"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-01-10', 'lesson-connected-b2-01', 10, 'sentence', 'We shoulda taken the train instead.', 'A gente devia ter pegado o trem.', '/wiː ˈʃʊdə ˈteɪkən ðə treɪn ɪnˈstɛd/', '"Shoulda taken": o particípio continua completo.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"shoulda","pos":"verb","ipa":"/ˈʃʊdə/","gloss":"devia ter (should have)"},{"surface":"taken","pos":"verb","ipa":"/ˈteɪkən/","gloss":"pegado, levado"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"train","pos":"noun","ipa":"/treɪn/","gloss":"trem"},{"surface":"instead","pos":"adverb","ipa":"/ɪnˈstɛd/","gloss":"em vez disso"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-connected-b2-02', 'course-connected-speech-b2', 2, 'Gonna, wanna, gotta, hafta', 'Going to, want to, got to e have to na fala.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-connected-b2-02-01', 'lesson-connected-b2-02', 1, 'sentence', 'I''m gonna be late tonight.', 'Eu vou me atrasar hoje à noite.', '/aɪm ˈɡʌnə biː leɪt təˈnaɪt/', '"Gonna" = going to; o "I''m" fica antes.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-02', 'lesson-connected-b2-02', 2, 'sentence', 'What are you gonna do about it?', 'O que você vai fazer a respeito?', '/wʌt ɑːr juː ˈɡʌnə duː əˈbaʊt ɪt/', '"Gonna" em pergunta.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-03', 'lesson-connected-b2-02', 3, 'sentence', 'I wanna go home.', 'Quero ir para casa.', '/aɪ ˈwɑːnə ɡoʊ hoʊm/', '"Wanna" = want to.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"wanna","pos":"verb","ipa":"/ˈwɑːnə/","gloss":"quer (want to)"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-04', 'lesson-connected-b2-02', 4, 'sentence', 'Do you wanna grab lunch?', 'Quer almoçar?', '/duː juː ˈwɑːnə ɡræb lʌntʃ/', '"Wanna" também em pergunta.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"wanna","pos":"verb","ipa":"/ˈwɑːnə/","gloss":"quer (want to)"},{"surface":"grab","pos":"verb","ipa":"/ɡræb/","gloss":"pegar, comer algo rápido"},{"surface":"lunch","pos":"noun","ipa":"/lʌntʃ/","gloss":"almoço"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-05', 'lesson-connected-b2-02', 5, 'sentence', 'I gotta finish this report.', 'Tenho que terminar este relatório.', '/aɪ ˈɡɑːtə ˈfɪnɪʃ ðɪs rɪˈpɔːrt/', '"Gotta" = have got to.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"gotta","pos":"verb","ipa":"/ˈɡɑːtə/","gloss":"tenho que (got to)"},{"surface":"finish","pos":"verb","ipa":"/ˈfɪnɪʃ/","gloss":"terminar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"report","pos":"verb","ipa":"/rɪˈpɔːrt/","gloss":"registrar, relatar"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-06', 'lesson-connected-b2-02', 6, 'sentence', 'You gotta be kidding me.', 'Você só pode estar brincando.', '/juː ˈɡɑːtə biː ˈkɪdɪŋ miː/', 'Expressão de surpresa; "gotta be" = só pode ser.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"gotta","pos":"verb","ipa":"/ˈɡɑːtə/","gloss":"tenho que (got to)"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"kidding","pos":"verb","ipa":"/ˈkɪdɪŋ/","gloss":"brincando"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-07', 'lesson-connected-b2-02', 7, 'sentence', 'We hafta leave in ten minutes.', 'A gente tem que sair em dez minutos.', '/wiː ˈhæftə liːv ɪn tɛn ˈmɪnɪts/', '"Hafta" = have to.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"hafta","pos":"verb","ipa":"/ˈhæftə/","gloss":"ter que (have to)"},{"surface":"leave","pos":"verb","ipa":"/liːv/","gloss":"deixar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"minutes","pos":"noun","ipa":"/ˈmɪnɪts/","gloss":"minutos"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-08', 'lesson-connected-b2-02', 8, 'sentence', 'She''s gonna love it.', 'Ela vai adorar.', '/ʃiːz ˈɡʌnə lʌv ɪt/', '"She''s gonna" = she is going to.', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"love","pos":"verb","ipa":"/lʌv/","gloss":"amar, adorar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-09', 'lesson-connected-b2-02', 9, 'sentence', 'They don''t wanna wait.', 'Eles não querem esperar.', '/ðeɪ doʊnt ˈwɑːnə weɪt/', '"Don''t wanna" = do not want to.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"wanna","pos":"verb","ipa":"/ˈwɑːnə/","gloss":"quer (want to)"},{"surface":"wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-02-10', 'lesson-connected-b2-02', 10, 'sentence', 'He''s not gonna say yes.', 'Ele não vai dizer sim.', '/hiːz nɑːt ˈɡʌnə seɪ jɛs/', 'Negativa: o "not" fica depois do "is".', '[]'::jsonb, '[{"surface":"He''s","pos":"pronoun","ipa":"/hiːz/","gloss":"ele é, ele está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"},{"surface":"yes","pos":"interjection","ipa":"/jɛs/","gloss":"sim"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-connected-b2-03', 'course-connected-speech-b2', 3, 'Perguntas e pedidos rápidos', 'Whaddya, lemme, gimme, dunno, didja.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-connected-b2-03-01', 'lesson-connected-b2-03', 1, 'sentence', 'Whaddya want for dinner?', 'O que você quer para o jantar?', '/ˈwʌdjə wɑːnt fɔːr ˈdɪnər/', '"Whaddya" = what do you.', '[]'::jsonb, '[{"surface":"Whaddya","pos":"pronoun","ipa":"/ˈwʌdjə/","gloss":"o que você (what do you)"},{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"dinner","pos":"noun","ipa":"/ˈdɪnər/","gloss":"jantar"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-02', 'lesson-connected-b2-03', 2, 'sentence', 'Whaddya think about this plan?', 'O que você acha desse plano?', '/ˈwʌdjə θɪŋk əˈbaʊt ðɪs plæn/', '"Whaddya think" = what do you think.', '[]'::jsonb, '[{"surface":"Whaddya","pos":"pronoun","ipa":"/ˈwʌdjə/","gloss":"o que você (what do you)"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"plan","pos":"noun","ipa":"/plæn/","gloss":"plano"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-03', 'lesson-connected-b2-03', 3, 'sentence', 'Lemme check my calendar.', 'Deixa eu ver minha agenda.', '/ˈlɛmi tʃɛk maɪ ˈkælɪndər/', '"Lemme" = let me.', '[]'::jsonb, '[{"surface":"Lemme","pos":"verb","ipa":"/ˈlɛmi/","gloss":"deixa eu (let me)"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"calendar","pos":"noun","ipa":"/ˈkælɪndər/","gloss":"agenda, calendário"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-04', 'lesson-connected-b2-03', 4, 'sentence', 'Gimme a second, please.', 'Me dá um segundo, por favor.', '/ˈɡɪmi ə ˈsɛkənd pliːz/', '"Gimme" = give me.', '[]'::jsonb, '[{"surface":"Gimme","pos":"verb","ipa":"/ˈɡɪmi/","gloss":"me dá (give me)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"second","pos":"adjective","ipa":"/ˈsɛkənd/","gloss":"segundo"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-05', 'lesson-connected-b2-03', 5, 'sentence', 'I dunno what to say.', 'Não sei o que dizer.', '/aɪ dəˈnoʊ wʌt tuː seɪ/', '"Dunno" = do not know.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"dunno","pos":"verb","ipa":"/dəˈnoʊ/","gloss":"não sei (don''t know)"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-06', 'lesson-connected-b2-03', 6, 'sentence', 'Didja see the news today?', 'Você viu as notícias hoje?', '/ˈdɪdʒə siː ðə nuːz təˈdeɪ/', '"Didja" = did you.', '[]'::jsonb, '[{"surface":"Didja","pos":"verb","ipa":"/ˈdɪdʒə/","gloss":"você (did you)"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"news","pos":"noun","ipa":"/nuːz/","gloss":"notícia(s)"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-07', 'lesson-connected-b2-03', 7, 'sentence', 'Dontcha think it''s too late?', 'Você não acha que já é tarde?', '/ˈdoʊntʃə θɪŋk ɪts tuː leɪt/', '"Dontcha" = don''t you; forma completa: "Do you not think it is too late?". Pode pedir confirmação ou expressar preocupação.', '[]'::jsonb, '[{"surface":"Dontcha","pos":"verb","ipa":"/ˈdoʊntʃə/","gloss":"você não (don''t you)"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"it''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-08', 'lesson-connected-b2-03', 8, 'sentence', 'Wanna come with us?', 'Quer vir com a gente?', '/ˈwɑːnə kʌm wɪð ʌs/', 'Na fala, o "do you" some: "wanna come?".', '[]'::jsonb, '[{"surface":"Wanna","pos":"verb","ipa":"/ˈwɑːnə/","gloss":"quer (want to)"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-09', 'lesson-connected-b2-03', 9, 'sentence', 'Gotcha, I''ll handle it.', 'Entendi, deixa comigo.', '/ˈɡɑːtʃə aɪl ˈhændəl ɪt/', '"Gotcha" = got you, entendi.', '[]'::jsonb, '[{"surface":"Gotcha","pos":"verb","ipa":"/ˈɡɑːtʃə/","gloss":"entendi, pode deixar (got you)"},{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"handle","pos":"verb","ipa":"/ˈhændəl/","gloss":"cuidar de, lidar com"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-03-10', 'lesson-connected-b2-03', 10, 'sentence', 'Lemme know if you need anything.', 'Me avisa se precisar de algo.', '/ˈlɛmi noʊ ɪf juː niːd ˈɛniθɪŋ/', 'Combinação muito usada em mensagens.', '[]'::jsonb, '[{"surface":"Lemme","pos":"verb","ipa":"/ˈlɛmi/","gloss":"deixa eu (let me)"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-connected-b2-04', 'course-connected-speech-b2', 4, 'Kinda, sorta e companhia', 'Kind of, sort of, a lot of, out of na fala.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-connected-b2-04-01', 'lesson-connected-b2-04', 1, 'sentence', 'It''s kinda cold in here.', 'Está meio frio aqui.', '/ɪts ˈkaɪndə koʊld ɪn hɪr/', '"Kinda" = kind of, "meio".', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"kinda","pos":"adverb","ipa":"/ˈkaɪndə/","gloss":"meio, um pouco (kind of)"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-02', 'lesson-connected-b2-04', 2, 'sentence', 'I''m sorta tired today.', 'Estou meio cansado hoje.', '/aɪm ˈsɔːrtə ˈtaɪərd təˈdeɪ/', '"Sorta" = sort of.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"sorta","pos":"adverb","ipa":"/ˈsɔːrtə/","gloss":"meio (sort of)"},{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-03', 'lesson-connected-b2-04', 3, 'sentence', 'There''s a lotta traffic downtown.', 'Tem muito trânsito no centro.', '/ðɛrz ə ˈlɑːtə ˈtræfɪk ˌdaʊnˈtaʊn/', '"Lotta" = a lot of.', '[]'::jsonb, '[{"surface":"There''s","pos":"pronoun","ipa":"/ðɛrz/","gloss":"há, tem (there is)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lotta","pos":"noun","ipa":"/ˈlɑːtə/","gloss":"um monte de (a lot of)"},{"surface":"traffic","pos":"noun","ipa":"/ˈtræfɪk/","gloss":"trânsito"},{"surface":"downtown","pos":"adverb","ipa":"/ˌdaʊnˈtaʊn/","gloss":"para o centro"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-04', 'lesson-connected-b2-04', 4, 'sentence', 'We''re outta milk again.', 'Acabou o leite de novo.', '/wɪr ˈaʊtə mɪlk əˈɡɛn/', '"Outta" = out of.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"outta","pos":"preposition","ipa":"/ˈaʊtə/","gloss":"sem, fora de (out of)"},{"surface":"milk","pos":"noun","ipa":"/mɪlk/","gloss":"leite"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-05', 'lesson-connected-b2-04', 5, 'sentence', 'That movie was kinda boring.', 'Aquele filme foi meio chato.', '/ðæt ˈmuːvi wɑːz ˈkaɪndə ˈbɔːrɪŋ/', '"Kinda" suaviza o adjetivo.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"movie","pos":"noun","ipa":"/ˈmuːvi/","gloss":"filme"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"kinda","pos":"adverb","ipa":"/ˈkaɪndə/","gloss":"meio, um pouco (kind of)"},{"surface":"boring","pos":"adjective","ipa":"/ˈbɔːrɪŋ/","gloss":"chato, entediante"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-06', 'lesson-connected-b2-04', 6, 'sentence', 'He''s sorta my boss, sorta my friend.', 'Ele é meio meu chefe, meio meu amigo.', '/hiːz ˈsɔːrtə maɪ bɔːs ˈsɔːrtə maɪ frɛnd/', '"Sorta" repetido mostra ambiguidade.', '[]'::jsonb, '[{"surface":"He''s","pos":"pronoun","ipa":"/hiːz/","gloss":"ele é, ele está"},{"surface":"sorta","pos":"adverb","ipa":"/ˈsɔːrtə/","gloss":"meio (sort of)"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"boss","pos":"noun","ipa":"/bɔːs/","gloss":"chefe"},{"surface":"sorta","pos":"adverb","ipa":"/ˈsɔːrtə/","gloss":"meio (sort of)"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"friend","pos":"noun","ipa":"/frɛnd/","gloss":"amigo, amiga"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-07', 'lesson-connected-b2-04', 7, 'sentence', 'I''ve got lotsa work today.', 'Tenho muito trabalho hoje.', '/aɪv ɡɑːt ˈlɑːtsə wɜːrk təˈdeɪ/', '"Lotsa" = lots of.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"lotsa","pos":"noun","ipa":"/ˈlɑːtsə/","gloss":"um monte de (lots of)"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-08', 'lesson-connected-b2-04', 8, 'sentence', 'Get outta here!', 'Sai fora! / Não acredito!', '/ɡɛt ˈaʊtə hɪr/', '"Get outta here" pode ser surpresa amigável.', '[]'::jsonb, '[{"surface":"Get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"outta","pos":"preposition","ipa":"/ˈaʊtə/","gloss":"sem, fora de (out of)"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-09', 'lesson-connected-b2-04', 9, 'sentence', 'I''m tryna sleep, so please be quiet.', 'Estou tentando dormir, então fique quieto.', '/aɪm ˈtraɪnə sliːp soʊ pliːz biː ˈkwaɪət/', '"Tryna" = trying to.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"tryna","pos":"verb","ipa":"/ˈtraɪnə/","gloss":"tentando (trying to)"},{"surface":"sleep","pos":"verb","ipa":"/sliːp/","gloss":"dormir"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"quiet","pos":"adjective","ipa":"/ˈkwaɪət/","gloss":"quieto"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-04-10', 'lesson-connected-b2-04', 10, 'sentence', 'It''s kinda funny when you think about it.', 'É meio engraçado quando você pensa nisso.', '/ɪts ˈkaɪndə ˈfʌni wɛn juː θɪŋk əˈbaʊt ɪt/', 'Comentário leve e informal.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"kinda","pos":"adverb","ipa":"/ˈkaɪndə/","gloss":"meio, um pouco (kind of)"},{"surface":"funny","pos":"adjective","ipa":"/ˈfʌni/","gloss":"engraçado"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-connected-b2-05', 'course-connected-speech-b2', 5, 'Ligação entre palavras', 'A consoante final se liga à vogal seguinte.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-connected-b2-05-01', 'lesson-connected-b2-05', 1, 'sentence', 'Pick it up and put it on the table.', 'Pegue e ponha na mesa.', '/pɪk ɪt ʌp ænd pʊt ɪt ɑːn ðə ˈteɪbəl/', 'Em "pick it up", o /k/ final de "pick" se liga ao /ɪ/ de "it", e o /t/ de "it" se liga ao /ʌ/ de "up". No inglês americano, esse /t/ pode soar como [ɾ].', '[]'::jsonb, '[{"surface":"Pick","pos":"verb","ipa":"/pɪk/","gloss":"pegar (pick up)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"table","pos":"noun","ipa":"/ˈteɪbəl/","gloss":"mesa"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-02', 'lesson-connected-b2-05', 2, 'sentence', 'Turn it off before you leave.', 'Desligue antes de sair.', '/tɜːrn ɪt ɔːf bɪˈfɔːr juː liːv/', 'Em "turn it off", o /n/ de "turn" se liga ao /ɪ/ de "it", e o /t/ de "it" à vogal inicial de "off".', '[]'::jsonb, '[{"surface":"Turn","pos":"verb","ipa":"/tɜːrn/","gloss":"ligar (turn on)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"leave","pos":"verb","ipa":"/liːv/","gloss":"deixar"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-03', 'lesson-connected-b2-05', 3, 'sentence', 'Can I have an apple?', 'Posso pegar uma maçã?', '/kæn aɪ hæv ən ˈæpəl/', 'Em "have an apple", o /v/ de "have" se liga à vogal de "an", e o /n/ de "an" ao /æ/ de "apple".', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"apple","pos":"noun","ipa":"/ˈæpəl/","gloss":"maçã"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-04', 'lesson-connected-b2-05', 4, 'sentence', 'Check it out, it''s really good.', 'Dá uma olhada, é muito bom.', '/tʃɛk ɪt aʊt ɪts ˈriːəli ɡʊd/', 'Em "check it out", o /k/ de "check" se liga ao /ɪ/ de "it", e o /t/ de "it" ao /aʊ/ de "out".', '[]'::jsonb, '[{"surface":"Check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"it''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-05', 'lesson-connected-b2-05', 5, 'sentence', 'Come on in and sit down.', 'Entra e senta.', '/kʌm ɑːn ɪn ænd sɪt daʊn/', '"Come on in" liga as três palavras.', '[]'::jsonb, '[{"surface":"Come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"sit","pos":"verb","ipa":"/sɪt/","gloss":"sentar"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-06', 'lesson-connected-b2-05', 6, 'sentence', 'Not at all.', 'De nada. / Nem um pouco.', '/nɑːt æt ɔːl/', 'Os sons /t/ de "not" e "at" se ligam às vogais seguintes em "not at all". No inglês americano, podem soar como [ɾ].', '[]'::jsonb, '[{"surface":"Not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-07', 'lesson-connected-b2-05', 7, 'sentence', 'What a nice idea.', 'Que boa ideia.', '/wʌt ə naɪs aɪˈdiːə/', 'Em "what a", o /t/ final se liga à vogal fraca /ə/ do artigo. No inglês americano, esse /t/ pode soar como [ɾ].', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"idea","pos":"noun","ipa":"/aɪˈdiːə/","gloss":"ideia"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-08', 'lesson-connected-b2-05', 8, 'sentence', 'Look at it carefully.', 'Olhe com cuidado.', '/lʊk æt ɪt ˈkɛrfəli/', 'Em "look at it", o /k/ de "look" se liga à vogal de "at", e o /t/ de "at" ao /ɪ/ de "it".', '[]'::jsonb, '[{"surface":"Look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"carefully","pos":"adverb","ipa":"/ˈkɛrfəli/","gloss":"com cuidado"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-09', 'lesson-connected-b2-05', 9, 'sentence', 'Wake up early tomorrow.', 'Acorde cedo amanhã.', '/weɪk ʌp ˈɜːrli təˈmɑːroʊ/', 'Em "wake up", o /k/ final de "wake" se liga ao /ʌ/ de "up", sem uma pausa entre as palavras.', '[]'::jsonb, '[{"surface":"Wake","pos":"verb","ipa":"/weɪk/","gloss":"acordar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-05-10', 'lesson-connected-b2-05', 10, 'sentence', 'Put on a warm jacket.', 'Vista um casaco quente.', '/pʊt ɑːn ə wɔːrm ˈdʒækɪt/', 'Em "put on a", o /t/ de "put" se liga à vogal de "on", e o /n/ de "on" ao /ə/ do artigo.', '[]'::jsonb, '[{"surface":"Put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"warm","pos":"verb","ipa":"/wɔːrm/","gloss":"esquentar; morno"},{"surface":"jacket","pos":"noun","ipa":"/ˈdʒækɪt/","gloss":"jaqueta"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-connected-b2-06', 'course-connected-speech-b2', 6, 'Cuz, ya, em e y''all', 'Formas fracas de because, you, them e you all.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-connected-b2-06-01', 'lesson-connected-b2-06', 1, 'sentence', 'I stayed home cuz I was sick.', 'Fiquei em casa porque estava doente.', '/aɪ steɪd hoʊm kəz aɪ wɑːz sɪk/', '"Cuz" = because, só na fala e em mensagens.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"stayed","pos":"verb","ipa":"/steɪd/","gloss":"ficou"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"cuz","pos":"conjunction","ipa":"/kəz/","gloss":"porque (because)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"sick","pos":"adjective","ipa":"/sɪk/","gloss":"doente, enjoado"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-02', 'lesson-connected-b2-06', 2, 'sentence', 'See ya tomorrow, okay?', 'Te vejo amanhã, tá?', '/siː jə təˈmɑːroʊ oʊˈkeɪ/', '"Ya" = you em fala rápida.', '[]'::jsonb, '[{"surface":"See","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"ya","pos":"pronoun","ipa":"/jə/","gloss":"você (you)"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"},{"surface":"okay","pos":"adjective","ipa":"/oʊˈkeɪ/","gloss":"tá, ok"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-03', 'lesson-connected-b2-06', 3, 'sentence', 'How are ya doing?', 'Como você está?', '/haʊ ɑːr jə ˈduːɪŋ/', '"Ya" no lugar de "you".', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"ya","pos":"pronoun","ipa":"/jə/","gloss":"você (you)"},{"surface":"doing","pos":"verb","ipa":"/ˈduːɪŋ/","gloss":"fazendo, fazer"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-04', 'lesson-connected-b2-06', 4, 'sentence', 'Y''all want some coffee?', 'Vocês querem café?', '/jɔːl wɑːnt sʌm ˈkɔːfi/', '"Y''all" = you all, comum no sul dos EUA.', '[]'::jsonb, '[{"surface":"Y''all","pos":"pronoun","ipa":"/jɔːl/","gloss":"vocês (you all)"},{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-05', 'lesson-connected-b2-06', 5, 'sentence', 'Did ya hear that?', 'Você ouviu isso?', '/dɪd jə hɪr ðæt/', '"Did ya" soa quase como "didja".', '[]'::jsonb, '[{"surface":"Did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"ya","pos":"pronoun","ipa":"/jə/","gloss":"você (you)"},{"surface":"hear","pos":"verb","ipa":"/hɪr/","gloss":"ouvir"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-06', 'lesson-connected-b2-06', 6, 'sentence', 'I told ya so.', 'Eu te avisei.', '/aɪ toʊld jə soʊ/', 'Expressão de "eu disse".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"ya","pos":"pronoun","ipa":"/jə/","gloss":"você (you)"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-07', 'lesson-connected-b2-06', 7, 'sentence', 'Can ya help me with this?', 'Você pode me ajudar com isso?', '/kæn jə hɛlp miː wɪð ðɪs/', '"Ya" é a forma fraca /jə/ de "you". Sem ênfase, "can" pode soar como /kən/: "can ya" /kən jə/.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"ya","pos":"pronoun","ipa":"/jə/","gloss":"você (you)"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-08', 'lesson-connected-b2-06', 8, 'sentence', 'I''ll tell em the good news.', 'Vou contar a boa notícia a eles.', '/aɪl tɛl əm ðə ɡʊd nuːz/', '"Em" = them, forma fraca.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"em","pos":"pronoun","ipa":"/əm/","gloss":"eles, elas (them)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"news","pos":"noun","ipa":"/nuːz/","gloss":"notícia(s)"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-09', 'lesson-connected-b2-06', 9, 'sentence', 'Let em know I''m on my way.', 'Avisa a eles que estou a caminho.', '/lɛt əm noʊ aɪm ɑːn maɪ weɪ/', '"Let em" = let them.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"em","pos":"pronoun","ipa":"/əm/","gloss":"eles, elas (them)"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-06-10', 'lesson-connected-b2-06', 10, 'sentence', 'Thank ya so much for everything.', 'Muito obrigado por tudo.', '/θæŋk jə soʊ mʌtʃ fɔːr ˈɛvriθɪŋ/', '"Thank ya" = thank you, informal e amigável.', '[]'::jsonb, '[{"surface":"Thank","pos":"verb","ipa":"/θæŋk/","gloss":"agradecer"},{"surface":"ya","pos":"pronoun","ipa":"/jə/","gloss":"você (you)"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"everything","pos":"pronoun","ipa":"/ˈɛvriθɪŋ/","gloss":"tudo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-connected-b2-07', 'course-connected-speech-b2', 7, 'Contrações duplas', 'Wouldn''t''ve, who''d''ve, what''d e where''d.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-connected-b2-07-01', 'lesson-connected-b2-07', 1, 'sentence', 'I wouldn''t''ve said that.', 'Eu não teria dito isso.', '/aɪ ˈwʊdntəv sɛd ðæt/', '"Wouldn''t''ve" = would not have.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"wouldn''t''ve","pos":"verb","ipa":"/ˈwʊdntəv/","gloss":"não teria (would not have)"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-02', 'lesson-connected-b2-07', 2, 'sentence', 'She shouldn''t''ve gone alone.', 'Ela não devia ter ido sozinha.', '/ʃiː ˈʃʊdntəv ɡɔːn əˈloʊn/', '"Shouldn''t''ve" = should not have.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"shouldn''t''ve","pos":"verb","ipa":"/ˈʃʊdntəv/","gloss":"não devia ter (should not have)"},{"surface":"gone","pos":"verb","ipa":"/ɡɔːn/","gloss":"ido (particípio de go)"},{"surface":"alone","pos":"adverb","ipa":"/əˈloʊn/","gloss":"sozinho"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-03', 'lesson-connected-b2-07', 3, 'sentence', 'It couldn''t''ve been easier.', 'Não poderia ter sido mais fácil.', '/ɪt ˈkʊdntəv bɪn ˈiːziər/', '"Couldn''t''ve" = could not have.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"couldn''t''ve","pos":"verb","ipa":"/ˈkʊdntəv/","gloss":"não poderia ter (could not have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"easier","pos":"adjective","ipa":"/ˈiːziər/","gloss":"mais fácil"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-04', 'lesson-connected-b2-07', 4, 'sentence', 'Who''d''ve thought?', 'Quem diria?', '/ˈhuːdəv θɔːt/', '"Who''d''ve" = who would have; expressão de surpresa.', '[]'::jsonb, '[{"surface":"Who''d''ve","pos":"pronoun","ipa":"/ˈhuːdəv/","gloss":"quem teria (who would have)"},{"surface":"thought","pos":"verb","ipa":"/θɔːt/","gloss":"pensou, pensado"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-05', 'lesson-connected-b2-07', 5, 'sentence', 'I''d''ve called if I''d known.', 'Eu teria ligado se soubesse.', '/ˈaɪdəv kɔːld ɪf aɪd noʊn/', '"I''d''ve" = I would have; "I''d known" = I had known.', '[]'::jsonb, '[{"surface":"I''d''ve","pos":"verb","ipa":"/ˈaɪdəv/","gloss":"eu teria (I would have)"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"known","pos":"verb","ipa":"/noʊn/","gloss":"sabido, conhecido"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-06', 'lesson-connected-b2-07', 6, 'sentence', 'They''d''ve loved it.', 'Eles teriam adorado.', '/ˈðeɪdəv lʌvd ɪt/', '"They''d''ve" = they would have.', '[]'::jsonb, '[{"surface":"They''d''ve","pos":"verb","ipa":"/ˈðeɪdəv/","gloss":"eles teriam (they would have)"},{"surface":"loved","pos":"verb","ipa":"/lʌvd/","gloss":"amou, adorou"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-07', 'lesson-connected-b2-07', 7, 'sentence', 'We''d''ve been late anyway.', 'A gente teria se atrasado de qualquer jeito.', '/ˈwiːdəv bɪn leɪt ˈɛniweɪ/', '"We''d''ve" = we would have.', '[]'::jsonb, '[{"surface":"We''d''ve","pos":"verb","ipa":"/ˈwiːdəv/","gloss":"nós teríamos (we would have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"anyway","pos":"adverb","ipa":"/ˈɛniweɪ/","gloss":"enfim, de qualquer forma"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-08', 'lesson-connected-b2-07', 8, 'sentence', 'That''ll be fine.', 'Isso vai ficar bom.', '/ˈðætəl biː faɪn/', '"That''ll" = that will.', '[]'::jsonb, '[{"surface":"That''ll","pos":"pronoun","ipa":"/ˈðætəl/","gloss":"isso vai (that will)"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"fine","pos":"adjective","ipa":"/faɪn/","gloss":"bom, tudo bem"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-09', 'lesson-connected-b2-07', 9, 'sentence', 'What''d you say?', 'O que você disse?', '/ˈwʌtəd juː seɪ/', '"What''d" = what did.', '[]'::jsonb, '[{"surface":"What''d","pos":"pronoun","ipa":"/ˈwʌtəd/","gloss":"o que (what did)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-07-10', 'lesson-connected-b2-07', 10, 'sentence', 'Where''d you put my keys?', 'Onde você pôs minhas chaves?', '/ˈwɛrd juː pʊt maɪ kiːz/', '"Where''d" = where did.', '[]'::jsonb, '[{"surface":"Where''d","pos":"adverb","ipa":"/ˈwɛrd/","gloss":"onde (where did)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-connected-b2-08', 'course-connected-speech-b2', 8, 'Tudo junto', 'Reduções misturadas como na conversa real.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-connected-b2-08-01', 'lesson-connected-b2-08', 1, 'sentence', 'I dunno, I kinda wanna stay home tonight.', 'Não sei, meio que quero ficar em casa hoje à noite.', '/aɪ dəˈnoʊ aɪ ˈkaɪndə ˈwɑːnə steɪ hoʊm təˈnaɪt/', 'Três reduções: dunno, kinda, wanna.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"dunno","pos":"verb","ipa":"/dəˈnoʊ/","gloss":"não sei (don''t know)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"kinda","pos":"adverb","ipa":"/ˈkaɪndə/","gloss":"meio, um pouco (kind of)"},{"surface":"wanna","pos":"verb","ipa":"/ˈwɑːnə/","gloss":"quer (want to)"},{"surface":"stay","pos":"verb","ipa":"/steɪ/","gloss":"ficar"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-02', 'lesson-connected-b2-08', 2, 'sentence', 'Lemme guess, you shoulda called, right?', 'Deixa eu adivinhar, você devia ter ligado, né?', '/ˈlɛmi ɡɛs juː ˈʃʊdə kɔːld raɪt/', 'Lemme e shoulda na mesma frase.', '[]'::jsonb, '[{"surface":"Lemme","pos":"verb","ipa":"/ˈlɛmi/","gloss":"deixa eu (let me)"},{"surface":"guess","pos":"verb","ipa":"/ɡɛs/","gloss":"adivinhar, achar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"shoulda","pos":"verb","ipa":"/ˈʃʊdə/","gloss":"devia ter (should have)"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-03', 'lesson-connected-b2-08', 3, 'sentence', 'Whaddya mean you''re not gonna come?', 'Como assim você não vai vir?', '/ˈwʌdjə miːn jʊr nɑːt ˈɡʌnə kʌm/', '"Whaddya mean" = what do you mean.', '[]'::jsonb, '[{"surface":"Whaddya","pos":"pronoun","ipa":"/ˈwʌdjə/","gloss":"o que você (what do you)"},{"surface":"mean","pos":"verb","ipa":"/miːn/","gloss":"significar, querer dizer"},{"surface":"you''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-04', 'lesson-connected-b2-08', 4, 'sentence', 'We''re outta time, so gimme the short version.', 'Estamos sem tempo, então me dá a versão curta.', '/wɪr ˈaʊtə taɪm soʊ ˈɡɪmi ðə ʃɔːrt ˈvɜːrʒən/', 'Outta e gimme.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"outta","pos":"preposition","ipa":"/ˈaʊtə/","gloss":"sem, fora de (out of)"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"gimme","pos":"verb","ipa":"/ˈɡɪmi/","gloss":"me dá (give me)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"short","pos":"adjective","ipa":"/ʃɔːrt/","gloss":"curto"},{"surface":"version","pos":"noun","ipa":"/ˈvɜːrʒən/","gloss":"versão"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-05', 'lesson-connected-b2-08', 5, 'sentence', 'I gotta go, but I''ll text ya later.', 'Preciso ir, mas te mando mensagem depois.', '/aɪ ˈɡɑːtə ɡoʊ bʌt aɪl tɛkst jə ˈleɪtər/', 'Gotta e ya.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"gotta","pos":"verb","ipa":"/ˈɡɑːtə/","gloss":"tenho que (got to)"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"text","pos":"verb","ipa":"/tɛkst/","gloss":"mandar mensagem"},{"surface":"ya","pos":"pronoun","ipa":"/jə/","gloss":"você (you)"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-06', 'lesson-connected-b2-08', 6, 'sentence', 'She coulda told me, but she didn''t wanna worry me.', 'Ela podia ter me contado, mas não quis me preocupar.', '/ʃiː ˈkʊdə toʊld miː bʌt ʃiː ˈdɪdənt ˈwɑːnə ˈwɜːri miː/', 'Coulda e wanna.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"coulda","pos":"verb","ipa":"/ˈkʊdə/","gloss":"podia ter (could have)"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"wanna","pos":"verb","ipa":"/ˈwɑːnə/","gloss":"quer (want to)"},{"surface":"worry","pos":"verb","ipa":"/ˈwɜːri/","gloss":"se preocupar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-07', 'lesson-connected-b2-08', 7, 'sentence', 'Didja hear? They''re gonna close the office.', 'Ficou sabendo? Vão fechar o escritório.', '/ˈdɪdʒə hɪr ðɛr ˈɡʌnə kloʊz ðə ˈɔːfɪs/', 'Didja e gonna.', '[]'::jsonb, '[{"surface":"Didja","pos":"verb","ipa":"/ˈdɪdʒə/","gloss":"você (did you)"},{"surface":"hear","pos":"verb","ipa":"/hɪr/","gloss":"ouvir"},{"surface":"They''re","pos":"pronoun","ipa":"/ðɛr/","gloss":"eles são, eles estão"},{"surface":"gonna","pos":"verb","ipa":"/ˈɡʌnə/","gloss":"vou, vai (going to)"},{"surface":"close","pos":"verb","ipa":"/kloʊz/","gloss":"fechar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"office","pos":"noun","ipa":"/ˈɔːfɪs/","gloss":"escritório, balcão"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-08', 'lesson-connected-b2-08', 8, 'sentence', 'It''s kinda funny how you shoulda known.', 'É meio engraçado pensar que você devia ter sabido.', '/ɪts ˈkaɪndə ˈfʌni haʊ juː ˈʃʊdə noʊn/', 'Kinda = kind of; shoulda known = should have known, sobre algo que a pessoa devia ter sabido antes.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"kinda","pos":"adverb","ipa":"/ˈkaɪndə/","gloss":"meio, um pouco (kind of)"},{"surface":"funny","pos":"adjective","ipa":"/ˈfʌni/","gloss":"engraçado"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"shoulda","pos":"verb","ipa":"/ˈʃʊdə/","gloss":"devia ter (should have)"},{"surface":"known","pos":"verb","ipa":"/noʊn/","gloss":"sabido, conhecido"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-09', 'lesson-connected-b2-08', 9, 'sentence', 'Y''all gotta try the cake, it''s so good.', 'Vocês precisam provar o bolo, está ótimo.', '/jɔːl ˈɡɑːtə traɪ ðə keɪk ɪts soʊ ɡʊd/', 'Y''all e gotta.', '[]'::jsonb, '[{"surface":"Y''all","pos":"pronoun","ipa":"/jɔːl/","gloss":"vocês (you all)"},{"surface":"gotta","pos":"verb","ipa":"/ˈɡɑːtə/","gloss":"tenho que (got to)"},{"surface":"try","pos":"verb","ipa":"/traɪ/","gloss":"experimentar, tentar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"cake","pos":"noun","ipa":"/keɪk/","gloss":"bolo"},{"surface":"it''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"}]'::jsonb, NULL, NULL),
  ('unit-connected-b2-08-10', 'lesson-connected-b2-08', 10, 'sentence', 'I woulda stayed, but I hafta wake up early.', 'Eu teria ficado, mas preciso acordar cedo.', '/aɪ ˈwʊdə steɪd bʌt aɪ ˈhæftə weɪk ʌp ˈɜːrli/', 'Woulda e hafta.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"woulda","pos":"verb","ipa":"/ˈwʊdə/","gloss":"teria (would have)"},{"surface":"stayed","pos":"verb","ipa":"/steɪd/","gloss":"ficou"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"hafta","pos":"verb","ipa":"/ˈhæftə/","gloss":"ter que (have to)"},{"surface":"wake","pos":"verb","ipa":"/weɪk/","gloss":"acordar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
