-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-subtext-b2', 'reading-between-the-lines-b2', 'Entrelinhas: Ironia e Subentendidos', 'O que o falante realmente quer dizer: ironia, sarcasmo, pedidos indiretos e recusas educadas.', 'Em inglês, muita coisa importante não está nas palavras: "not bad" pode ser um grande elogio, "interesting" pode ser uma crítica e "it is a bit cold in here" pode ser um pedido para fechar a janela. Cada frase traz o sentido literal e o sentido real.', 'B2', 'social', 25, 'fluencia', 5, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-subtext-b2-01', 'course-subtext-b2', 1, 'Dizer menos do que se pensa', 'Understatement: "not bad" costuma significar "muito bom".')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-subtext-b2-01-01', 'lesson-subtext-b2-01', 1, 'sentence', 'That is not bad at all.', 'Isso não está nada mal.', '/ðæt ɪz nɑːt bæd æt ɔːl/', 'Understatement: costuma ser um elogio de verdade.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"bad","pos":"adjective","ipa":"/bæd/","gloss":"ruim"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-02', 'lesson-subtext-b2-01', 2, 'sentence', 'It was a bit of a disaster, really.', 'Foi meio que um desastre, na verdade.', '/ɪt wɑːz ə bɪt ʌv ə dɪˈzæstər ˈriːəli/', '"A bit of" suaviza algo bem ruim.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"disaster","pos":"noun","ipa":"/dɪˈzæstər/","gloss":"desastre"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-03', 'lesson-subtext-b2-01', 3, 'sentence', 'He is not exactly a beginner.', 'Ele não é exatamente um iniciante.', '/hiː ɪz nɑːt ɪɡˈzæktli ə bɪˈɡɪnər/', 'Quer dizer: é muito experiente.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"exactly","pos":"adverb","ipa":"/ɪɡˈzæktli/","gloss":"exatamente"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"beginner","pos":"noun","ipa":"/bɪˈɡɪnər/","gloss":"iniciante"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-04', 'lesson-subtext-b2-01', 4, 'sentence', 'We had a slight problem with the budget.', 'Tivemos um probleminha com o orçamento.', '/wiː hæd ə slaɪt ˈprɑːbləm wɪð ðə ˈbʌdʒɪt/', '"Slight" pode esconder um problema grande.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"slight","pos":"adjective","ipa":"/slaɪt/","gloss":"pequeno, leve"},{"surface":"problem","pos":"noun","ipa":"/ˈprɑːbləm/","gloss":"problema"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"budget","pos":"noun","ipa":"/ˈbʌdʒɪt/","gloss":"orçamento"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-05', 'lesson-subtext-b2-01', 5, 'sentence', 'She is quite good, to be honest.', 'Ela é bem boa, para ser sincero.', '/ʃiː ɪz kwaɪt ɡʊd tuː biː ˈɑːnɪst/', '"Quite" em inglês britânico pode ser mais forte que "pretty".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"quite","pos":"adverb","ipa":"/kwaɪt/","gloss":"bem, bastante"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"honest","pos":"adjective","ipa":"/ˈɑːnɪst/","gloss":"sincero, honesto"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-06', 'lesson-subtext-b2-01', 6, 'sentence', 'It could be worse.', 'Poderia ser pior.', '/ɪt kʊd biː wɜːrs/', 'Consolo; reconhece que não está bom.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"worse","pos":"adjective","ipa":"/wɜːrs/","gloss":"pior"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-07', 'lesson-subtext-b2-01', 7, 'sentence', 'That went reasonably well.', 'Foi razoavelmente bem.', '/ðæt wɛnt ˈriːzənəbli wɛl/', 'Tom morno; pode significar "bom, mas não ótimo".', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"reasonably","pos":"adverb","ipa":"/ˈriːzənəbli/","gloss":"razoavelmente"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-08', 'lesson-subtext-b2-01', 8, 'sentence', 'I am not a big fan of crowds.', 'Não sou muito fã de multidões.', '/aɪ æm nɑːt ə bɪɡ fæn ʌv kraʊdz/', 'Quer dizer: detesto.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"big","pos":"adjective","ipa":"/bɪɡ/","gloss":"grande"},{"surface":"fan","pos":"noun","ipa":"/fæn/","gloss":"fã"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"crowds","pos":"noun","ipa":"/kraʊdz/","gloss":"multidões"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-09', 'lesson-subtext-b2-01', 9, 'sentence', 'It was not the best weekend ever.', 'Não foi o melhor fim de semana de todos.', '/ɪt wɑːz nɑːt ðə bɛst ˈwiːkɛnd ˈɛvər/', 'Pode significar que foi péssimo.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"best","pos":"adjective","ipa":"/bɛst/","gloss":"melhor"},{"surface":"weekend","pos":"noun","ipa":"/ˈwiːkɛnd/","gloss":"fim de semana"},{"surface":"ever","pos":"adverb","ipa":"/ˈɛvər/","gloss":"alguma vez, já"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-01-10', 'lesson-subtext-b2-01', 10, 'sentence', 'That is one way of looking at it.', 'É uma forma de ver as coisas.', '/ðæt ɪz wʌn weɪ ʌv ˈlʊkɪŋ æt ɪt/', 'Educadamente: não concordo.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-subtext-b2-02', 'course-subtext-b2', 2, 'Sarcasmo', 'Dizer o contrário do que se sente, com tom e contexto.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-subtext-b2-02-01', 'lesson-subtext-b2-02', 1, 'sentence', 'Oh great, another meeting.', 'Ah, ótimo, mais uma reunião.', '/oʊ ɡreɪt əˈnʌðər ˈmiːtɪŋ/', 'Sarcasmo: a pessoa está irritada com a reunião.', '[]'::jsonb, '[{"surface":"Oh","pos":"interjection","ipa":"/oʊ/","gloss":"ah, oh"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"another","pos":"determiner","ipa":"/əˈnʌðər/","gloss":"outro, mais um"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-02', 'lesson-subtext-b2-02', 2, 'sentence', 'Thanks a lot, that was really helpful.', 'Valeu mesmo, ajudou muito.', '/θæŋks ə lɑːt ðæt wɑːz ˈriːəli ˈhɛlpfəl/', 'Dito com ironia = não ajudou nada.', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lot","pos":"noun","ipa":"/lɑːt/","gloss":"muito (a lot)"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"helpful","pos":"adjective","ipa":"/ˈhɛlpfəl/","gloss":"útil"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-03', 'lesson-subtext-b2-02', 3, 'sentence', 'Nice weather we are having.', 'Que tempo bom estamos tendo.', '/naɪs ˈwɛðər wiː ɑːr ˈhævɪŋ/', 'Dito debaixo de chuva forte.', '[]'::jsonb, '[{"surface":"Nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"having","pos":"verb","ipa":"/ˈhævɪŋ/","gloss":"receber, ter"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-04', 'lesson-subtext-b2-02', 4, 'sentence', 'Well, that went perfectly.', 'Bom, deu tudo certo.', '/wɛl ðæt wɛnt ˈpɜːrfɪktli/', 'Quando algo deu errado, é sarcasmo.', '[]'::jsonb, '[{"surface":"Well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"perfectly","pos":"adverb","ipa":"/ˈpɜːrfɪktli/","gloss":"perfeitamente"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-05', 'lesson-subtext-b2-02', 5, 'sentence', 'Sure, because that always works.', 'Claro, porque isso sempre funciona.', '/ʃʊr bɪˈkɔːz ðæt ˈɔːlweɪz wɜːrks/', 'Ironia: não funciona.', '[]'::jsonb, '[{"surface":"Sure","pos":"adjective","ipa":"/ʃʊr/","gloss":"claro; certo"},{"surface":"because","pos":"conjunction","ipa":"/bɪˈkɔːz/","gloss":"porque"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"always","pos":"adverb","ipa":"/ˈɔːlweɪz/","gloss":"sempre"},{"surface":"works","pos":"verb","ipa":"/wɜːrks/","gloss":"funciona, serve"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-06', 'lesson-subtext-b2-02', 6, 'sentence', 'I just love waiting in line.', 'Eu simplesmente adoro esperar na fila.', '/aɪ dʒʌst lʌv ˈweɪtɪŋ ɪn laɪn/', 'Sarcasmo comum com "just love".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"love","pos":"verb","ipa":"/lʌv/","gloss":"amar, adorar"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"line","pos":"noun","ipa":"/laɪn/","gloss":"linha"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-07', 'lesson-subtext-b2-02', 7, 'sentence', 'What a surprise, he is late again.', 'Que surpresa, ele atrasou de novo.', '/wʌt ə sərˈpraɪz hiː ɪz leɪt əˈɡɛn/', 'Não é surpresa nenhuma.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"surprise","pos":"noun","ipa":"/sərˈpraɪz/","gloss":"surpresa"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-08', 'lesson-subtext-b2-02', 8, 'sentence', 'Good luck with that.', 'Boa sorte com isso.', '/ɡʊd lʌk wɪð ðæt/', 'Pode ser torcida sincera ou "vai precisar".', '[]'::jsonb, '[{"surface":"Good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"luck","pos":"noun","ipa":"/lʌk/","gloss":"sorte"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-09', 'lesson-subtext-b2-02', 9, 'sentence', 'Yeah, right, as if that would happen.', 'Sei, como se isso fosse acontecer.', '/jɛ raɪt æz ɪf ðæt wʊd ˈhæpən/', '"Yeah, right" = não acredito.', '[]'::jsonb, '[{"surface":"Yeah","pos":"interjection","ipa":"/jɛ/","gloss":"é, sim"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"as","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"happen","pos":"verb","ipa":"/ˈhæpən/","gloss":"acontecer"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-02-10', 'lesson-subtext-b2-02', 10, 'sentence', 'Wow, you are a real genius.', 'Uau, você é um gênio mesmo.', '/waʊ juː ɑːr ə ˈriːəl ˈdʒiːnjəs/', 'Sarcástico quando alguém fez uma bobagem.', '[]'::jsonb, '[{"surface":"Wow","pos":"interjection","ipa":"/waʊ/","gloss":"uau"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"real","pos":"adjective","ipa":"/ˈriːəl/","gloss":"real"},{"surface":"genius","pos":"noun","ipa":"/ˈdʒiːnjəs/","gloss":"gênio"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-subtext-b2-03', 'course-subtext-b2', 3, 'Pedidos indiretos', 'Pedir sem pedir: o contexto faz o resto.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-subtext-b2-03-01', 'lesson-subtext-b2-03', 1, 'sentence', 'It is a bit cold in here.', 'Está um pouco frio aqui.', '/ɪt ɪz ə bɪt koʊld ɪn hɪr/', 'Pedido indireto: feche a janela ou desligue o ar.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-02', 'lesson-subtext-b2-03', 2, 'sentence', 'I wonder if you could give me a hand.', 'Será que você poderia me dar uma mão.', '/aɪ ˈwʌndər ɪf juː kʊd ɡɪv miː ə hænd/', '"I wonder if" torna o pedido mais cortês.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"wonder","pos":"verb","ipa":"/ˈwʌndər/","gloss":"perguntar-se"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"hand","pos":"noun","ipa":"/hænd/","gloss":"mão, ajuda"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-03', 'lesson-subtext-b2-03', 3, 'sentence', 'Is that your coat on the chair?', 'Esse casaco na cadeira é seu?', '/ɪz ðæt jʊr koʊt ɑːn ðə tʃɛr/', 'Quer dizer: tire-o dali, preciso sentar.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"coat","pos":"noun","ipa":"/koʊt/","gloss":"casaco"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"chair","pos":"noun","ipa":"/tʃɛr/","gloss":"cadeira"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-04', 'lesson-subtext-b2-03', 4, 'sentence', 'We are running a bit low on coffee.', 'O café está acabando.', '/wiː ɑːr ˈrʌnɪŋ ə bɪt loʊ ɑːn ˈkɔːfi/', 'Sugestão para alguém comprar mais.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"running","pos":"verb","ipa":"/ˈrʌnɪŋ/","gloss":"ficando (running late)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"low","pos":"adjective","ipa":"/loʊ/","gloss":"baixo, acabando"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-05', 'lesson-subtext-b2-03', 5, 'sentence', 'Would you mind keeping it down?', 'Você se importaria de falar mais baixo?', '/wʊd juː maɪnd ˈkiːpɪŋ ɪt daʊn/', '"Would you mind" é cortês, mas firme.', '[]'::jsonb, '[{"surface":"Would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"mind","pos":"verb","ipa":"/maɪnd/","gloss":"se importar"},{"surface":"keeping","pos":"verb","ipa":"/ˈkiːpɪŋ/","gloss":"mantendo"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-06', 'lesson-subtext-b2-03', 6, 'sentence', 'I do not suppose you have a pen.', 'Imagino que você não tenha uma caneta.', '/aɪ duː nɑːt səˈpoʊz juː hæv ə pɛn/', 'Pedido muito educado, esperando um sim.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"suppose","pos":"verb","ipa":"/səˈpoʊz/","gloss":"supor"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"pen","pos":"noun","ipa":"/pɛn/","gloss":"caneta"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-07', 'lesson-subtext-b2-03', 7, 'sentence', 'It would be great if the report were ready.', 'Seria ótimo se o relatório estivesse pronto.', '/ɪt wʊd biː ɡreɪt ɪf ðə rɪˈpɔːrt wɜːr ˈrɛdi/', 'Do chefe, quer dizer: preciso dele pronto.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"report","pos":"verb","ipa":"/rɪˈpɔːrt/","gloss":"registrar, relatar"},{"surface":"were","pos":"verb","ipa":"/wɜːr/","gloss":"eram, estavam"},{"surface":"ready","pos":"adjective","ipa":"/ˈrɛdi/","gloss":"pronto"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-08', 'lesson-subtext-b2-03', 8, 'sentence', 'Some people are still waiting for their food.', 'Algumas pessoas ainda esperam pela comida.', '/sʌm ˈpiːpəl ɑːr stɪl ˈweɪtɪŋ fɔːr ðɛr fuːd/', 'Reclamação indireta para o garçom.', '[]'::jsonb, '[{"surface":"Some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"people","pos":"noun","ipa":"/ˈpiːpəl/","gloss":"pessoas"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"still","pos":"adverb","ipa":"/stɪl/","gloss":"ainda"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"their","pos":"determiner","ipa":"/ðɛr/","gloss":"deles, delas"},{"surface":"food","pos":"noun","ipa":"/fuːd/","gloss":"comida"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-09', 'lesson-subtext-b2-03', 9, 'sentence', 'Are you using this chair?', 'Você está usando esta cadeira?', '/ɑːr juː ˈjuːzɪŋ ðɪs tʃɛr/', 'Pedido para levar a cadeira.', '[]'::jsonb, '[{"surface":"Are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"using","pos":"verb","ipa":"/ˈjuːzɪŋ/","gloss":"usando"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"chair","pos":"noun","ipa":"/tʃɛr/","gloss":"cadeira"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-03-10', 'lesson-subtext-b2-03', 10, 'sentence', 'I could really use a coffee right now.', 'Eu bem que precisava de um café agora.', '/aɪ kʊd ˈriːəli juːz ə ˈkɔːfi raɪt naʊ/', 'Pedido indireto para quem vai buscar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"use","pos":"verb","ipa":"/juːz/","gloss":"usar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-subtext-b2-04', 'course-subtext-b2', 4, 'Recusas educadas', 'Dizer não sem usar a palavra "no".')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-subtext-b2-04-01', 'lesson-subtext-b2-04', 1, 'sentence', 'I would love to, but I have other plans.', 'Eu adoraria, mas tenho outros planos.', '/aɪ wʊd lʌv tuː bʌt aɪ hæv ˈʌðər plænz/', 'Recusa polida; "I would love to, but" é padrão.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"love","pos":"verb","ipa":"/lʌv/","gloss":"amar, adorar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"other","pos":"pronoun","ipa":"/ˈʌðər/","gloss":"outro"},{"surface":"plans","pos":"noun","ipa":"/plænz/","gloss":"planos"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-02', 'lesson-subtext-b2-04', 2, 'sentence', 'Let me think about it and get back to you.', 'Deixa eu pensar e te retorno.', '/lɛt miː θɪŋk əˈbaʊt ɪt ænd ɡɛt bæk tuː juː/', 'Muitas vezes é um "não" suave.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-03', 'lesson-subtext-b2-04', 3, 'sentence', 'That might be difficult.', 'Isso pode ser difícil.', '/ðæt maɪt biː ˈdɪfɪkəlt/', 'Recusa indireta de quem não vai fazer.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"might","pos":"modal verb","ipa":"/maɪt/","gloss":"talvez, poderia"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"difficult","pos":"adjective","ipa":"/ˈdɪfɪkəlt/","gloss":"difícil"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-04', 'lesson-subtext-b2-04', 4, 'sentence', 'I will see what I can do.', 'Vou ver o que posso fazer.', '/aɪ wɪl siː wʌt aɪ kæn duː/', 'Sem promessa; pode ser um "não".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-05', 'lesson-subtext-b2-04', 5, 'sentence', 'It is not really my thing.', 'Não é bem a minha praia.', '/ɪt ɪz nɑːt ˈriːəli maɪ θɪŋ/', 'Recusa a um convite sem ofender.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"thing","pos":"noun","ipa":"/θɪŋ/","gloss":"coisa"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-06', 'lesson-subtext-b2-04', 6, 'sentence', 'Maybe another time.', 'Quem sabe outra hora.', '/ˈmeɪbi əˈnʌðər taɪm/', 'Pode ser um adiamento educado de um "não".', '[]'::jsonb, '[{"surface":"Maybe","pos":"adverb","ipa":"/ˈmeɪbi/","gloss":"talvez"},{"surface":"another","pos":"determiner","ipa":"/əˈnʌðər/","gloss":"outro, mais um"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-07', 'lesson-subtext-b2-04', 7, 'sentence', 'I am afraid that is not possible.', 'Infelizmente isso não é possível.', '/aɪ æm əˈfreɪd ðæt ɪz nɑːt ˈpɑːsəbəl/', 'Recusa formal e definitiva.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"afraid","pos":"adjective","ipa":"/əˈfreɪd/","gloss":"com medo"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"possible","pos":"adjective","ipa":"/ˈpɑːsəbəl/","gloss":"possível"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-08', 'lesson-subtext-b2-04', 8, 'sentence', 'Thanks for asking, but I will pass.', 'Obrigado por perguntar, mas vou passar.', '/θæŋks fɔːr ˈæskɪŋ bʌt aɪ wɪl pæs/', '"Pass" = recusar uma oferta.', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"asking","pos":"verb","ipa":"/ˈæskɪŋ/","gloss":"pedindo, perguntando"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"pass","pos":"noun","ipa":"/pæs/","gloss":"cartão, passe"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-09', 'lesson-subtext-b2-04', 9, 'sentence', 'We will keep your details on file.', 'Vamos manter seus dados arquivados.', '/wiː wɪl kiːp jʊr ˈdiːteɪlz ɑːn faɪl/', 'Dito a candidato = provavelmente não será contratado.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"details","pos":"noun","ipa":"/ˈdiːteɪlz/","gloss":"detalhes"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"file","pos":"noun","ipa":"/faɪl/","gloss":"arquivo"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-04-10', 'lesson-subtext-b2-04', 10, 'sentence', 'I do not think that is a good idea.', 'Não acho que seja uma boa ideia.', '/aɪ duː nɑːt θɪŋk ðæt ɪz ə ɡʊd aɪˈdiːə/', 'Recusa mais direta, ainda cortês.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"idea","pos":"noun","ipa":"/aɪˈdiːə/","gloss":"ideia"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-subtext-b2-05', 'course-subtext-b2', 5, 'Elogio com ressalva', 'Quando o elogio vem com um "mas" escondido.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-subtext-b2-05-01', 'lesson-subtext-b2-05', 1, 'sentence', 'It is quite an interesting choice.', 'É uma escolha bem interessante.', '/ɪt ɪz kwaɪt ən ˈɪntrəstɪŋ tʃɔɪs/', '"Interesting" costuma ser crítica educada.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"quite","pos":"adverb","ipa":"/kwaɪt/","gloss":"bem, bastante"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"interesting","pos":"adjective","ipa":"/ˈɪntrəstɪŋ/","gloss":"interessante"},{"surface":"choice","pos":"noun","ipa":"/tʃɔɪs/","gloss":"escolha"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-02', 'lesson-subtext-b2-05', 2, 'sentence', 'You have really tried hard with this.', 'Você realmente se esforçou nisso.', '/juː hæv ˈriːəli traɪd hɑːrd wɪð ðɪs/', 'Elogia o esforço, não o resultado.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"tried","pos":"verb","ipa":"/traɪd/","gloss":"tentou, experimentou"},{"surface":"hard","pos":"adjective","ipa":"/hɑːrd/","gloss":"duro, difícil"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-03', 'lesson-subtext-b2-05', 3, 'sentence', 'That color is very brave.', 'Essa cor é muito corajosa.', '/ðæt ˈkʌlər ɪz ˈvɛri breɪv/', '"Brave" = estranha, ousada demais.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"color","pos":"noun","ipa":"/ˈkʌlər/","gloss":"cor"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"very","pos":"adverb","ipa":"/ˈvɛri/","gloss":"muito"},{"surface":"brave","pos":"adjective","ipa":"/breɪv/","gloss":"corajoso"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-04', 'lesson-subtext-b2-05', 4, 'sentence', 'It is not what I expected.', 'Não é o que eu esperava.', '/ɪt ɪz nɑːt wʌt aɪ ɪkˈspɛktɪd/', 'Decepção dita com cuidado.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"expected","pos":"verb","ipa":"/ɪkˈspɛktɪd/","gloss":"esperado"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-05', 'lesson-subtext-b2-05', 5, 'sentence', 'It has got a lot of potential.', 'Tem muito potencial.', '/ɪt hæz ɡɑːt ə lɑːt ʌv pəˈtɛnʃəl/', 'Ainda não está bom.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lot","pos":"noun","ipa":"/lɑːt/","gloss":"muito (a lot)"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"potential","pos":"noun","ipa":"/pəˈtɛnʃəl/","gloss":"potencial"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-06', 'lesson-subtext-b2-05', 6, 'sentence', 'You look so much better than last time.', 'Você está muito melhor que da última vez.', '/juː lʊk soʊ mʌtʃ ˈbɛtər ðæn læst taɪm/', 'Insinua que antes estava mal.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"better","pos":"adjective","ipa":"/ˈbɛtər/","gloss":"melhor"},{"surface":"than","pos":"conjunction","ipa":"/ðæn/","gloss":"do que"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-07', 'lesson-subtext-b2-05', 7, 'sentence', 'It is not bad for a first try.', 'Não está mal para uma primeira tentativa.', '/ɪt ɪz nɑːt bæd fɔːr ə fɜːrst traɪ/', 'Elogio com condescendência.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"bad","pos":"adjective","ipa":"/bæd/","gloss":"ruim"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"try","pos":"verb","ipa":"/traɪ/","gloss":"experimentar, tentar"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-08', 'lesson-subtext-b2-05', 8, 'sentence', 'Well, it is certainly different.', 'Bom, é certamente diferente.', '/wɛl ɪt ɪz ˈsɜːrtənli ˈdɪfərənt/', '"Different" pode ser educadamente negativo.', '[]'::jsonb, '[{"surface":"Well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"certainly","pos":"adverb","ipa":"/ˈsɜːrtənli/","gloss":"certamente"},{"surface":"different","pos":"adjective","ipa":"/ˈdɪfərənt/","gloss":"diferente"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-09', 'lesson-subtext-b2-05', 9, 'sentence', 'I am sure you did your best.', 'Tenho certeza de que você fez o melhor que pôde.', '/aɪ æm ʃʊr juː dɪd jʊr bɛst/', 'Costuma indicar que o resultado ficou aquém.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"sure","pos":"adjective","ipa":"/ʃʊr/","gloss":"claro; certo"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"best","pos":"adjective","ipa":"/bɛst/","gloss":"melhor"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-05-10', 'lesson-subtext-b2-05', 10, 'sentence', 'Interesting idea, but we need to think about costs.', 'Ideia interessante, mas precisamos pensar nos custos.', '/ˈɪntrəstɪŋ aɪˈdiːə bʌt wiː niːd tuː θɪŋk əˈbaʊt kɔːsts/', 'Elogio + "mas" = não vai ser aprovada.', '[]'::jsonb, '[{"surface":"Interesting","pos":"adjective","ipa":"/ˈɪntrəstɪŋ/","gloss":"interessante"},{"surface":"idea","pos":"noun","ipa":"/aɪˈdiːə/","gloss":"ideia"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-subtext-b2-06', 'course-subtext-b2', 6, 'Perguntas retóricas', 'Perguntas que não esperam resposta.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-subtext-b2-06-01', 'lesson-subtext-b2-06', 1, 'sentence', 'Who does he think he is?', 'Quem ele pensa que é?', '/huː dʌz hiː θɪŋk hiː ɪz/', 'Indignação; ninguém responde.', '[]'::jsonb, '[{"surface":"Who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-02', 'lesson-subtext-b2-06', 2, 'sentence', 'What is the point of arguing?', 'Qual é o sentido de discutir?', '/wʌt ɪz ðə pɔɪnt ʌv ˈɑːrɡjuːɪŋ/', 'Quer dizer: não adianta discutir.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"arguing","pos":"verb","ipa":"/ˈɑːrɡjuːɪŋ/","gloss":"discutindo"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-03', 'lesson-subtext-b2-06', 3, 'sentence', 'Do I look like I am made of money?', 'Parece que eu sou feito de dinheiro?', '/duː aɪ lʊk laɪk aɪ æm meɪd ʌv ˈmʌni/', 'Quer dizer: não posso pagar por isso.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"money","pos":"noun","ipa":"/ˈmʌni/","gloss":"dinheiro"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-04', 'lesson-subtext-b2-06', 4, 'sentence', 'How many times do I have to tell you?', 'Quantas vezes eu tenho que te dizer?', '/haʊ ˈmɛni taɪmz duː aɪ hæv tuː tɛl juː/', 'Irritação, não pergunta de verdade.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"many","pos":"determiner","ipa":"/ˈmɛni/","gloss":"muitos (how many)"},{"surface":"times","pos":"noun","ipa":"/taɪmz/","gloss":"vezes"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-05', 'lesson-subtext-b2-06', 5, 'sentence', 'Is it too much to ask for some quiet?', 'É pedir demais um pouco de silêncio?', '/ɪz ɪt tuː mʌtʃ tuː æsk fɔːr sʌm ˈkwaɪət/', 'Reclamação em forma de pergunta.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"ask","pos":"verb","ipa":"/æsk/","gloss":"perguntar, pedir"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"quiet","pos":"adjective","ipa":"/ˈkwaɪət/","gloss":"quieto"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-06', 'lesson-subtext-b2-06', 6, 'sentence', 'Why bother?', 'Para quê se dar ao trabalho?', '/waɪ ˈbɑːðər/', 'Quer dizer: não vale a pena.', '[]'::jsonb, '[{"surface":"Why","pos":"adverb","ipa":"/waɪ/","gloss":"por que"},{"surface":"bother","pos":"verb","ipa":"/ˈbɑːðər/","gloss":"incomodar"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-07', 'lesson-subtext-b2-06', 7, 'sentence', 'Who knows?', 'Quem sabe?', '/huː noʊz/', 'Quer dizer: ninguém sabe.', '[]'::jsonb, '[{"surface":"Who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"knows","pos":"verb","ipa":"/noʊz/","gloss":"sabe"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-08', 'lesson-subtext-b2-06', 8, 'sentence', 'What difference does it make?', 'Que diferença faz?', '/wʌt ˈdɪfrəns dʌz ɪt meɪk/', 'Quer dizer: não faz diferença.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"difference","pos":"noun","ipa":"/ˈdɪfrəns/","gloss":"diferença"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-09', 'lesson-subtext-b2-06', 9, 'sentence', 'Can you believe this weather?', 'Dá para acreditar nesse tempo?', '/kæn juː bɪˈliːv ðɪs ˈwɛðər/', 'Puxa assunto; espera concordância.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"believe","pos":"verb","ipa":"/bɪˈliːv/","gloss":"acreditar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-06-10', 'lesson-subtext-b2-06', 10, 'sentence', 'Am I the only one who finds this odd?', 'Sou o único que acha isso estranho?', '/æm aɪ ðə ˈoʊnli wʌn huː faɪndz ðɪs ɑːd/', 'Busca apoio; a pessoa acha estranho.', '[]'::jsonb, '[{"surface":"Am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"only","pos":"adverb","ipa":"/ˈoʊnli/","gloss":"só, apenas"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"finds","pos":"verb","ipa":"/faɪndz/","gloss":"encontra"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"odd","pos":"adjective","ipa":"/ɑːd/","gloss":"estranho"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-subtext-b2-07', 'course-subtext-b2', 7, 'Eufemismos', 'Palavras mais suaves para assuntos delicados.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-subtext-b2-07-01', 'lesson-subtext-b2-07', 1, 'sentence', 'He passed away last spring.', 'Ele faleceu na primavera passada.', '/hiː pæst əˈweɪ læst sprɪŋ/', '"Pass away" = morrer, de forma delicada.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"passed","pos":"verb","ipa":"/pæst/","gloss":"passou"},{"surface":"away","pos":"adverb","ipa":"/əˈweɪ/","gloss":"embora; (right away) já"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"spring","pos":"noun","ipa":"/sprɪŋ/","gloss":"primavera"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-02', 'lesson-subtext-b2-07', 2, 'sentence', 'She is between jobs at the moment.', 'Ela está entre empregos no momento.', '/ʃiː ɪz bɪˈtwiːn dʒɑːbz æt ðə ˈmoʊmənt/', 'Eufemismo para "desempregada".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"between","pos":"preposition","ipa":"/bɪˈtwiːn/","gloss":"entre"},{"surface":"jobs","pos":"noun","ipa":"/dʒɑːbz/","gloss":"empregos"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"moment","pos":"noun","ipa":"/ˈmoʊmənt/","gloss":"momento"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-03', 'lesson-subtext-b2-07', 3, 'sentence', 'We had to let him go.', 'Tivemos que dispensá-lo.', '/wiː hæd tuː lɛt hɪm ɡoʊ/', '"Let go" = demitir, sem usar a palavra.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-04', 'lesson-subtext-b2-07', 4, 'sentence', 'The company is downsizing.', 'A empresa está reduzindo o quadro.', '/ðə ˈkʌmpəni ɪz ˈdaʊnsaɪzɪŋ/', 'Eufemismo para "demitir".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"downsizing","pos":"verb","ipa":"/ˈdaʊnsaɪzɪŋ/","gloss":"reduzindo o quadro"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-05', 'lesson-subtext-b2-07', 5, 'sentence', 'He is a bit economical with the truth.', 'Ele é econômico com a verdade.', '/hiː ɪz ə bɪt ˌɛkəˈnɑːmɪkəl wɪð ðə truːθ/', 'Eufemismo para "mente".', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"economical","pos":"adjective","ipa":"/ˌɛkəˈnɑːmɪkəl/","gloss":"econômico"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"truth","pos":"noun","ipa":"/truːθ/","gloss":"verdade"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-06', 'lesson-subtext-b2-07', 6, 'sentence', 'Our house is cozy.', 'Nossa casa é aconchegante.', '/aʊər haʊs ɪz ˈkoʊzi/', 'Pode significar "pequena".', '[]'::jsonb, '[{"surface":"Our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"house","pos":"noun","ipa":"/haʊs/","gloss":"casa"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"cozy","pos":"adjective","ipa":"/ˈkoʊzi/","gloss":"aconchegante"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-07', 'lesson-subtext-b2-07', 7, 'sentence', 'She is a little under the weather.', 'Ela está meio indisposta.', '/ʃiː ɪz ə ˈlɪtəl ˈʌndər ðə ˈwɛðər/', 'Eufemismo para "doente".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"little","pos":"adjective","ipa":"/ˈlɪtəl/","gloss":"pouco, pequeno"},{"surface":"under","pos":"preposition","ipa":"/ˈʌndər/","gloss":"no nome de, sob"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-08', 'lesson-subtext-b2-07', 8, 'sentence', 'They are going through a rough patch.', 'Eles estão passando por uma fase difícil.', '/ðeɪ ɑːr ˈɡoʊɪŋ θruː ə rʌf pætʃ/', '"Rough patch" = fase ruim.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"rough","pos":"adjective","ipa":"/rʌf/","gloss":"difícil, áspero"},{"surface":"patch","pos":"verb","ipa":"/pætʃ/","gloss":"remendar, consertar"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-09', 'lesson-subtext-b2-07', 9, 'sentence', 'He has a few issues to work through.', 'Ele tem alguns problemas para resolver.', '/hiː hæz ə fjuː ˈɪʃuːz tuː wɜːrk θruː/', '"Issues" suaviza algo sério.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"few","pos":"determiner","ipa":"/fjuː/","gloss":"poucos"},{"surface":"issues","pos":"noun","ipa":"/ˈɪʃuːz/","gloss":"problemas, questões"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-07-10', 'lesson-subtext-b2-07', 10, 'sentence', 'The restroom is just down the hall.', 'O banheiro é logo no fim do corredor.', '/ðə ˈrɛstruːm ɪz dʒʌst daʊn ðə hɔːl/', '"Restroom" é eufemismo para "banheiro".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"restroom","pos":"noun","ipa":"/ˈrɛstruːm/","gloss":"banheiro"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"hall","pos":"noun","ipa":"/hɔːl/","gloss":"corredor"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-subtext-b2-08', 'course-subtext-b2', 8, 'Exagero e humor', 'Hipérbole: dizer demais para enfatizar.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-subtext-b2-08-01', 'lesson-subtext-b2-08', 1, 'sentence', 'I have told you a million times.', 'Eu já te falei um milhão de vezes.', '/aɪ hæv toʊld juː ə ˈmɪljən taɪmz/', 'Exagero comum; não é literal.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"million","pos":"numeral","ipa":"/ˈmɪljən/","gloss":"milhão"},{"surface":"times","pos":"noun","ipa":"/taɪmz/","gloss":"vezes"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-02', 'lesson-subtext-b2-08', 2, 'sentence', 'I am starving, I could eat a horse.', 'Estou morrendo de fome, comeria um cavalo.', '/aɪ æm ˈstɑːrvɪŋ aɪ kʊd iːt ə hɔːrs/', 'Hipérbole famosa para fome.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"starving","pos":"adjective","ipa":"/ˈstɑːrvɪŋ/","gloss":"morrendo de fome"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"eat","pos":"verb","ipa":"/iːt/","gloss":"comer"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"horse","pos":"noun","ipa":"/hɔːrs/","gloss":"cavalo"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-03', 'lesson-subtext-b2-08', 3, 'sentence', 'This bag weighs a ton.', 'Esta bolsa pesa uma tonelada.', '/ðɪs bæɡ weɪz ə tʌn/', 'Exagero para "muito pesada".', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"bag","pos":"noun","ipa":"/bæɡ/","gloss":"mala, bolsa"},{"surface":"weighs","pos":"verb","ipa":"/weɪz/","gloss":"pesa"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"ton","pos":"noun","ipa":"/tʌn/","gloss":"tonelada"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-04', 'lesson-subtext-b2-08', 4, 'sentence', 'I have been waiting here forever.', 'Estou esperando aqui há uma eternidade.', '/aɪ hæv bɪn ˈweɪtɪŋ hɪr fərˈɛvər/', '"Forever" = muito tempo, não literal.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"forever","pos":"adverb","ipa":"/fərˈɛvər/","gloss":"para sempre"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-05', 'lesson-subtext-b2-08', 5, 'sentence', 'She is as old as the hills.', 'Ela é velha como as colinas.', '/ʃiː ɪz æz oʊld æz ðə hɪlz/', 'Exagero humorístico para "bem velha".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"as","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"old","pos":"adjective","ipa":"/oʊld/","gloss":"velho; de idade"},{"surface":"as","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"hills","pos":"noun","ipa":"/hɪlz/","gloss":"colinas"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-06', 'lesson-subtext-b2-08', 6, 'sentence', 'It was the worst day of my life.', 'Foi o pior dia da minha vida.', '/ɪt wɑːz ðə wɜːrst deɪ ʌv maɪ laɪf/', 'Costuma ser exagero emocional.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"worst","pos":"adjective","ipa":"/wɜːrst/","gloss":"pior"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"life","pos":"noun","ipa":"/laɪf/","gloss":"vida"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-07', 'lesson-subtext-b2-08', 7, 'sentence', 'I almost died laughing.', 'Quase morri de rir.', '/aɪ ˈɔːlmoʊst daɪd ˈlæfɪŋ/', 'Hipérbole para "ri muito".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"almost","pos":"adverb","ipa":"/ˈɔːlmoʊst/","gloss":"quase"},{"surface":"died","pos":"verb","ipa":"/daɪd/","gloss":"morreu"},{"surface":"laughing","pos":"verb","ipa":"/ˈlæfɪŋ/","gloss":"rindo"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-08', 'lesson-subtext-b2-08', 8, 'sentence', 'He is a walking encyclopedia.', 'Ele é uma enciclopédia ambulante.', '/hiː ɪz ə ˈwɔːkɪŋ ɪnˌsaɪkləˈpiːdiə/', 'Metáfora para "sabe tudo".', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"walking","pos":"noun","ipa":"/ˈwɔːkɪŋ/","gloss":"caminhada"},{"surface":"encyclopedia","pos":"noun","ipa":"/ɪnˌsaɪkləˈpiːdiə/","gloss":"enciclopédia"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-09', 'lesson-subtext-b2-08', 9, 'sentence', 'My phone is dead again.', 'Meu celular morreu de novo.', '/maɪ foʊn ɪz dɛd əˈɡɛn/', 'Linguagem figurada para "sem bateria".', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"phone","pos":"noun","ipa":"/foʊn/","gloss":"celular, telefone"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"dead","pos":"adjective","ipa":"/dɛd/","gloss":"morto; sem bateria"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"}]'::jsonb, NULL, NULL),
  ('unit-subtext-b2-08-10', 'lesson-subtext-b2-08', 10, 'sentence', 'That joke was so bad it was good.', 'Aquela piada era tão ruim que era boa.', '/ðæt dʒoʊk wɑːz soʊ bæd ɪt wɑːz ɡʊd/', 'Humor autoconsciente.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"joke","pos":"noun","ipa":"/dʒoʊk/","gloss":"piada"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"bad","pos":"adjective","ipa":"/bæd/","gloss":"ruim"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
