-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-phrasal-adv-b2', 'advanced-phrasal-verbs-b2', 'Phrasal Verbs Avançados', 'Figure out, put up with, turn down: os phrasal verbs que aparecem em séries, reuniões e conversas reais.', 'Dez grupos de phrasal verbs para quem já domina os básicos. Cada frase mostra o sentido na situação e avisa se o verbo é separável ou não, que é o ponto em que mais se erra.', 'B2', 'grammar', 24, 'gramatica', 2, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-01', 'course-phrasal-adv-b2', 1, 'Falar e agir', 'Bring up, carry out, cut down e outros de conversa e ação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-01-01', 'lesson-phrasal-b2-01', 1, 'sentence', 'She brought up the issue at lunch.', 'Ela tocou no assunto durante o almoço.', '/ʃiː brɔːt ʌp ðə ˈɪʃuː æt lʌntʃ/', '"Bring up" = mencionar um assunto; separável: "bring it up".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"issue","pos":"noun","ipa":"/ˈɪʃuː/","gloss":"assunto, problema"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"lunch","pos":"noun","ipa":"/lʌntʃ/","gloss":"almoço"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-02', 'lesson-phrasal-b2-01', 2, 'sentence', 'The team carried out a detailed survey.', 'A equipe realizou uma pesquisa detalhada.', '/ðə tiːm ˈkærid aʊt ə ˈdiːteɪld ˈsɜːrveɪ/', '"Carry out" = executar, realizar; separável.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"},{"surface":"carried","pos":"verb","ipa":"/ˈkærid/","gloss":"levou, carregou"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"detailed","pos":"adjective","ipa":"/ˈdiːteɪld/","gloss":"detalhado"},{"surface":"survey","pos":"noun","ipa":"/ˈsɜːrveɪ/","gloss":"pesquisa, levantamento"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-03', 'lesson-phrasal-b2-01', 3, 'sentence', 'I am trying to cut down on sugar.', 'Estou tentando reduzir o açúcar.', '/aɪ æm ˈtraɪɪŋ tuː kʌt daʊn ɑːn ˈʃʊɡər/', '"Cut down on" = reduzir o consumo; inseparável.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"trying","pos":"verb","ipa":"/ˈtraɪɪŋ/","gloss":"tentando"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"cut","pos":"verb","ipa":"/kʌt/","gloss":"cortar"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"sugar","pos":"noun","ipa":"/ˈʃʊɡər/","gloss":"açúcar"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-04', 'lesson-phrasal-b2-01', 4, 'sentence', 'Can you point out the mistake for me?', 'Você pode apontar o erro para mim?', '/kæn juː pɔɪnt aʊt ðə mɪˈsteɪk fɔːr miː/', '"Point out" = apontar, destacar; separável.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"mistake","pos":"noun","ipa":"/mɪˈsteɪk/","gloss":"erro"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-05', 'lesson-phrasal-b2-01', 5, 'sentence', 'He always shows off in front of his friends.', 'Ele sempre se exibe na frente dos amigos.', '/hiː ˈɔːlweɪz ʃoʊz ɔːf ɪn frʌnt ʌv hɪz frɛndz/', '"Show off" = se exibir, se gabar.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"always","pos":"adverb","ipa":"/ˈɔːlweɪz/","gloss":"sempre"},{"surface":"shows","pos":"verb","ipa":"/ʃoʊz/","gloss":"mostra"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"front","pos":"noun","ipa":"/frʌnt/","gloss":"frente"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"friends","pos":"noun","ipa":"/frɛndz/","gloss":"amigos"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-06', 'lesson-phrasal-b2-01', 6, 'sentence', 'Please fill me in on what I missed.', 'Me atualiza sobre o que eu perdi, por favor.', '/pliːz fɪl miː ɪn ɑːn wʌt aɪ mɪst/', '"Fill in" = informar, atualizar; separável.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"fill","pos":"verb","ipa":"/fɪl/","gloss":"preencher; obturar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"missed","pos":"verb","ipa":"/mɪst/","gloss":"perdi"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-07', 'lesson-phrasal-b2-01', 7, 'sentence', 'They set up a meeting for Monday.', 'Eles marcaram uma reunião para segunda.', '/ðeɪ sɛt ʌp ə ˈmiːtɪŋ fɔːr ˈmʌndeɪ/', '"Set up" = organizar, marcar; separável.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"Monday","pos":"proper noun","ipa":"/ˈmʌndeɪ/","gloss":"segunda-feira"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-08', 'lesson-phrasal-b2-01', 8, 'sentence', 'We need to stand up for our rights.', 'Precisamos defender nossos direitos.', '/wiː niːd tuː stænd ʌp fɔːr aʊər raɪts/', '"Stand up for" = defender; inseparável.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"stand","pos":"verb","ipa":"/stænd/","gloss":"ficar de pé; suportar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"rights","pos":"noun","ipa":"/raɪts/","gloss":"direitos"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-09', 'lesson-phrasal-b2-01', 9, 'sentence', 'She talked me into joining the gym.', 'Ela me convenceu a entrar na academia.', '/ʃiː tɔːkt miː ˈɪntuː ˈdʒɔɪnɪŋ ðə dʒɪm/', '"Talk into" = convencer a fazer; separável.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"talked","pos":"verb","ipa":"/tɔːkt/","gloss":"conversou"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"into","pos":"preposition","ipa":"/ˈɪntuː/","gloss":"para dentro de"},{"surface":"joining","pos":"verb","ipa":"/ˈdʒɔɪnɪŋ/","gloss":"entrando, participando"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"gym","pos":"noun","ipa":"/dʒɪm/","gloss":"academia"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-01-10', 'lesson-phrasal-b2-01', 10, 'sentence', 'Do not let them talk you out of it.', 'Não deixe que eles te convençam do contrário.', '/duː nɑːt lɛt ðɛm tɔːk juː aʊt ʌv ɪt/', '"Talk out of" = dissuadir.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"them","pos":"pronoun","ipa":"/ðɛm/","gloss":"eles, os"},{"surface":"talk","pos":"verb","ipa":"/tɔːk/","gloss":"falar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-02', 'course-phrasal-adv-b2', 2, 'Resolver e entender', 'Figure out, work out, sort out e companhia.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-02-01', 'lesson-phrasal-b2-02', 1, 'sentence', 'I cannot figure out how this machine works.', 'Não consigo descobrir como esta máquina funciona.', '/aɪ ˈkænɑːt ˈfɪɡjər aʊt haʊ ðɪs məˈʃiːn wɜːrks/', '"Figure out" = entender, descobrir; separável.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"cannot","pos":"verb","ipa":"/ˈkænɑːt/","gloss":"não posso, não consigo"},{"surface":"figure","pos":"noun","ipa":"/ˈfɪɡjər/","gloss":"valor, número"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"machine","pos":"noun","ipa":"/məˈʃiːn/","gloss":"máquina"},{"surface":"works","pos":"verb","ipa":"/wɜːrks/","gloss":"funciona, serve"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-02', 'lesson-phrasal-b2-02', 2, 'sentence', 'We will work out the details tomorrow.', 'Vamos acertar os detalhes amanhã.', '/wiː wɪl wɜːrk aʊt ðə ˈdiːteɪlz təˈmɑːroʊ/', '"Work out" = resolver, acertar; separável.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"details","pos":"noun","ipa":"/ˈdiːteɪlz/","gloss":"detalhes"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-03', 'lesson-phrasal-b2-02', 3, 'sentence', 'It took a week to sort out the paperwork.', 'Levou uma semana para resolver a papelada.', '/ɪt tʊk ə wiːk tuː sɔːrt aʊt ðə ˈpeɪpərwɜːrk/', '"Sort out" = organizar, resolver; separável.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"took","pos":"verb","ipa":"/tʊk/","gloss":"pegou, levou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"sort","pos":"verb","ipa":"/sɔːrt/","gloss":"organizar, resolver"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"paperwork","pos":"noun","ipa":"/ˈpeɪpərwɜːrk/","gloss":"papelada"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-04', 'lesson-phrasal-b2-02', 4, 'sentence', 'Let me think this over before I decide.', 'Deixa eu pensar nisso antes de decidir.', '/lɛt miː θɪŋk ðɪs ˈoʊvər bɪˈfɔːr aɪ dɪˈsaɪd/', '"Think over" = ponderar; separável.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"por cima; superado"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"decide","pos":"verb","ipa":"/dɪˈsaɪd/","gloss":"decidir"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-05', 'lesson-phrasal-b2-02', 5, 'sentence', 'The police are looking into the case.', 'A polícia está investigando o caso.', '/ðə pəˈliːs ɑːr ˈlʊkɪŋ ˈɪntuː ðə keɪs/', '"Look into" = investigar; inseparável.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"police","pos":"noun","ipa":"/pəˈliːs/","gloss":"polícia"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"into","pos":"preposition","ipa":"/ˈɪntuː/","gloss":"para dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"case","pos":"noun","ipa":"/keɪs/","gloss":"capa, caso"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-06', 'lesson-phrasal-b2-02', 6, 'sentence', 'I came across an old photo of us.', 'Encontrei por acaso uma foto antiga nossa.', '/aɪ keɪm əˈkrɔːs ən oʊld ˈfoʊtoʊ ʌv ʌs/', '"Come across" = achar sem procurar; inseparável.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"came","pos":"verb","ipa":"/keɪm/","gloss":"veio"},{"surface":"across","pos":"preposition","ipa":"/əˈkrɔːs/","gloss":"do outro lado de, atravessando"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"old","pos":"adjective","ipa":"/oʊld/","gloss":"velho; de idade"},{"surface":"photo","pos":"noun","ipa":"/ˈfoʊtoʊ/","gloss":"foto"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-07', 'lesson-phrasal-b2-02', 7, 'sentence', 'Can you make out what the sign says?', 'Você consegue ler o que diz a placa?', '/kæn juː meɪk aʊt wʌt ðə saɪn sɛz/', '"Make out" = distinguir, conseguir ler ou ouvir.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"sign","pos":"verb","ipa":"/saɪn/","gloss":"assinar"},{"surface":"says","pos":"verb","ipa":"/sɛz/","gloss":"diz"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-08', 'lesson-phrasal-b2-02', 8, 'sentence', 'He finally found out the truth.', 'Ele finalmente descobriu a verdade.', '/hiː ˈfaɪnəli faʊnd aʊt ðə truːθ/', '"Find out" = descobrir uma informação.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"finally","pos":"adverb","ipa":"/ˈfaɪnəli/","gloss":"finalmente"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"truth","pos":"noun","ipa":"/truːθ/","gloss":"verdade"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-09', 'lesson-phrasal-b2-02', 9, 'sentence', 'She gave away the secret by accident.', 'Ela entregou o segredo sem querer.', '/ʃiː ɡeɪv əˈweɪ ðə ˈsiːkrɪt baɪ ˈæksɪdənt/', '"Give away" = revelar, entregar; separável.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"gave","pos":"verb","ipa":"/ɡeɪv/","gloss":"deu"},{"surface":"away","pos":"adverb","ipa":"/əˈweɪ/","gloss":"embora; (right away) já"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"secret","pos":"noun","ipa":"/ˈsiːkrɪt/","gloss":"segredo"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"accident","pos":"noun","ipa":"/ˈæksɪdənt/","gloss":"acidente"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-02-10', 'lesson-phrasal-b2-02', 10, 'sentence', 'It turned out to be a great idea.', 'Acabou sendo uma ótima ideia.', '/ɪt tɜːrnd aʊt tuː biː ə ɡreɪt aɪˈdiːə/', '"Turn out" = acabar sendo, revelar-se.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"turned","pos":"verb","ipa":"/tɜːrnd/","gloss":"virou, ficou"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"idea","pos":"noun","ipa":"/aɪˈdiːə/","gloss":"ideia"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-03', 'course-phrasal-adv-b2', 3, 'Criar e superar', 'Come up with, go through, get over e outros de desafio.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-03-01', 'lesson-phrasal-b2-03', 1, 'sentence', 'She came up with a clever solution.', 'Ela teve uma solução inteligente.', '/ʃiː keɪm ʌp wɪð ə ˈklɛvər səˈluːʃən/', '"Come up with" = ter uma ideia; inseparável.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"came","pos":"verb","ipa":"/keɪm/","gloss":"veio"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"clever","pos":"adjective","ipa":"/ˈklɛvər/","gloss":"inteligente, esperto"},{"surface":"solution","pos":"noun","ipa":"/səˈluːʃən/","gloss":"solução"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-02', 'lesson-phrasal-b2-03', 2, 'sentence', 'They went through a difficult time.', 'Eles passaram por um período difícil.', '/ðeɪ wɛnt θruː ə ˈdɪfɪkəlt taɪm/', '"Go through" = passar por, enfrentar.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"difficult","pos":"adjective","ipa":"/ˈdɪfɪkəlt/","gloss":"difícil"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-03', 'lesson-phrasal-b2-03', 3, 'sentence', 'It took him months to get over the loss.', 'Ele levou meses para superar a perda.', '/ɪt tʊk hɪm mʌnθs tuː ɡɛt ˈoʊvər ðə lɔːs/', '"Get over" = superar, recuperar-se.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"took","pos":"verb","ipa":"/tʊk/","gloss":"pegou, levou"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"months","pos":"noun","ipa":"/mʌnθs/","gloss":"meses"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"por cima; superado"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"loss","pos":"noun","ipa":"/lɔːs/","gloss":"perda"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-04', 'lesson-phrasal-b2-03', 4, 'sentence', 'I am going to take up painting this year.', 'Vou começar a pintar este ano.', '/aɪ æm ˈɡoʊɪŋ tuː teɪk ʌp ˈpeɪntɪŋ ðɪs jɪr/', '"Take up" = começar um hobby; separável.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"painting","pos":"noun","ipa":"/ˈpeɪntɪŋ/","gloss":"pintura"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-05', 'lesson-phrasal-b2-03', 5, 'sentence', 'We managed to get through the exam.', 'Conseguimos passar pela prova.', '/wiː ˈmænɪdʒd tuː ɡɛt θruː ðə ɪɡˈzæm/', '"Get through" = conseguir terminar, atravessar.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"managed","pos":"verb","ipa":"/ˈmænɪdʒd/","gloss":"conseguiu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"exam","pos":"noun","ipa":"/ɪɡˈzæm/","gloss":"prova"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-06', 'lesson-phrasal-b2-03', 6, 'sentence', 'Do not give up on your dreams.', 'Não desista dos seus sonhos.', '/duː nɑːt ɡɪv ʌp ɑːn jʊr driːmz/', '"Give up on" = desistir de algo ou alguém.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"dreams","pos":"noun","ipa":"/driːmz/","gloss":"sonhos"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-07', 'lesson-phrasal-b2-03', 7, 'sentence', 'He bounced back after the failure.', 'Ele se recuperou depois do fracasso.', '/hiː baʊnst bæk ˈæftər ðə ˈfeɪljər/', '"Bounce back" = se recuperar rápido.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"bounced","pos":"verb","ipa":"/baʊnst/","gloss":"voltou, quicou"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"failure","pos":"noun","ipa":"/ˈfeɪljər/","gloss":"fracasso"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-08', 'lesson-phrasal-b2-03', 8, 'sentence', 'Hang in there, it will get better.', 'Aguente firme, vai melhorar.', '/hæŋ ɪn ðɛr ɪt wɪl ɡɛt ˈbɛtər/', '"Hang in there" = aguentar firme.', '[]'::jsonb, '[{"surface":"Hang","pos":"verb","ipa":"/hæŋ/","gloss":"pendurar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"better","pos":"adjective","ipa":"/ˈbɛtər/","gloss":"melhor"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-09', 'lesson-phrasal-b2-03', 9, 'sentence', 'She pulled through the surgery well.', 'Ela superou bem a cirurgia.', '/ʃiː pʊld θruː ðə ˈsɜːrdʒəri wɛl/', '"Pull through" = sobreviver, superar uma crise.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"pulled","pos":"verb","ipa":"/pʊld/","gloss":"puxou"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"surgery","pos":"noun","ipa":"/ˈsɜːrdʒəri/","gloss":"cirurgia"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-03-10', 'lesson-phrasal-b2-03', 10, 'sentence', 'We have to deal with this problem now.', 'Precisamos lidar com este problema agora.', '/wiː hæv tuː diːl wɪð ðɪs ˈprɑːbləm naʊ/', '"Deal with" = lidar com; inseparável.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"deal","pos":"noun","ipa":"/diːl/","gloss":"negócio, coisa"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"problem","pos":"noun","ipa":"/ˈprɑːbləm/","gloss":"problema"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-04', 'course-phrasal-adv-b2', 4, 'Aguentar e respeitar', 'Put up with, look up to e outras atitudes com as pessoas.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-04-01', 'lesson-phrasal-b2-04', 1, 'sentence', 'I cannot put up with this noise any longer.', 'Não aguento mais esse barulho.', '/aɪ ˈkænɑːt pʊt ʌp wɪð ðɪs nɔɪz ˈɛni ˈlɔːŋɡər/', '"Put up with" = tolerar; inseparável.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"cannot","pos":"verb","ipa":"/ˈkænɑːt/","gloss":"não posso, não consigo"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"noise","pos":"noun","ipa":"/nɔɪz/","gloss":"barulho"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"longer","pos":"adverb","ipa":"/ˈlɔːŋɡər/","gloss":"mais (tempo)"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-02', 'lesson-phrasal-b2-04', 2, 'sentence', 'Many kids look up to their older siblings.', 'Muitas crianças admiram seus irmãos mais velhos.', '/ˈmɛni kɪdz lʊk ʌp tuː ðɛr ˈoʊldər ˈsɪblɪŋz/', '"Look up to" = admirar.', '[]'::jsonb, '[{"surface":"Many","pos":"determiner","ipa":"/ˈmɛni/","gloss":"muitos (how many)"},{"surface":"kids","pos":"noun","ipa":"/kɪdz/","gloss":"crianças, filhos"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"their","pos":"determiner","ipa":"/ðɛr/","gloss":"deles, delas"},{"surface":"older","pos":"adjective","ipa":"/ˈoʊldər/","gloss":"mais velho"},{"surface":"siblings","pos":"noun","ipa":"/ˈsɪblɪŋz/","gloss":"irmãos (irmãos e irmãs)"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-03', 'lesson-phrasal-b2-04', 3, 'sentence', 'Do not look down on people who work hard.', 'Não olhe de cima quem trabalha duro.', '/duː nɑːt lʊk daʊn ɑːn ˈpiːpəl huː wɜːrk hɑːrd/', '"Look down on" = desprezar.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"people","pos":"noun","ipa":"/ˈpiːpəl/","gloss":"pessoas"},{"surface":"who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"hard","pos":"adjective","ipa":"/hɑːrd/","gloss":"duro, difícil"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-04', 'lesson-phrasal-b2-04', 4, 'sentence', 'She gets along well with her coworkers.', 'Ela se dá bem com os colegas de trabalho.', '/ʃiː ɡɛts əˈlɔːŋ wɛl wɪð hɜːr ˈkoʊwɜːrkərz/', '"Get along with" = se dar bem com.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"gets","pos":"verb","ipa":"/ɡɛts/","gloss":"fica"},{"surface":"along","pos":"particle","ipa":"/əˈlɔːŋ/","gloss":"junto (get along = dar-se bem)"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"coworkers","pos":"noun","ipa":"/ˈkoʊwɜːrkərz/","gloss":"colegas de trabalho"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-05', 'lesson-phrasal-b2-04', 5, 'sentence', 'They fell out over money last year.', 'Eles brigaram por causa de dinheiro no ano passado.', '/ðeɪ fɛl aʊt ˈoʊvər ˈmʌni læst jɪr/', '"Fall out" = brigar, romper.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"fell","pos":"verb","ipa":"/fɛl/","gloss":"caiu"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"por cima; superado"},{"surface":"money","pos":"noun","ipa":"/ˈmʌni/","gloss":"dinheiro"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-06', 'lesson-phrasal-b2-04', 6, 'sentence', 'We made up after a long talk.', 'Fizemos as pazes depois de uma longa conversa.', '/wiː meɪd ʌp ˈæftər ə lɔːŋ tɔːk/', '"Make up" = fazer as pazes.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"talk","pos":"verb","ipa":"/tɔːk/","gloss":"falar"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-07', 'lesson-phrasal-b2-04', 7, 'sentence', 'He takes after his father in many ways.', 'Ele puxou ao pai em muitos aspectos.', '/hiː teɪks ˈæftər hɪz ˈfɑːðər ɪn ˈmɛni weɪz/', '"Take after" = parecer-se com um familiar.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"takes","pos":"verb","ipa":"/teɪks/","gloss":"pega, leva; decola"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"father","pos":"noun","ipa":"/ˈfɑːðər/","gloss":"pai"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"many","pos":"determiner","ipa":"/ˈmɛni/","gloss":"muitos (how many)"},{"surface":"ways","pos":"noun","ipa":"/weɪz/","gloss":"jeitos, aspectos"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-08', 'lesson-phrasal-b2-04', 8, 'sentence', 'I was brought up by my grandparents.', 'Fui criado pelos meus avós.', '/aɪ wɑːz brɔːt ʌp baɪ maɪ ˈɡrænpɛrənts/', '"Bring up" na passiva = ser criado.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"grandparents","pos":"noun","ipa":"/ˈɡrænpɛrənts/","gloss":"avós"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-09', 'lesson-phrasal-b2-04', 9, 'sentence', 'Can I count on you to be there?', 'Posso contar com você para estar lá?', '/kæn aɪ kaʊnt ɑːn juː tuː biː ðɛr/', '"Count on" = contar com, confiar.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"count","pos":"verb","ipa":"/kaʊnt/","gloss":"contar, confiar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-04-10', 'lesson-phrasal-b2-04', 10, 'sentence', 'She let me down when I needed her.', 'Ela me decepcionou quando eu precisei.', '/ʃiː lɛt miː daʊn wɛn aɪ ˈniːdɪd hɜːr/', '"Let down" = decepcionar; separável.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"needed","pos":"verb","ipa":"/ˈniːdɪd/","gloss":"precisou"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-05', 'course-phrasal-adv-b2', 5, 'Apoiar e perceber', 'Back up, step up, pick up on e verbos de percepção.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-05-01', 'lesson-phrasal-b2-05', 1, 'sentence', 'Please back up your files before the update.', 'Faça backup dos seus arquivos antes da atualização.', '/pliːz bæk ʌp jʊr faɪlz bɪˈfɔːr ðə ʌpˈdeɪt/', '"Back up" = fazer cópia de segurança; separável.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"files","pos":"noun","ipa":"/faɪlz/","gloss":"arquivos"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"update","pos":"verb","ipa":"/ʌpˈdeɪt/","gloss":"atualizar"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-02', 'lesson-phrasal-b2-05', 2, 'sentence', 'He backed me up in front of the boss.', 'Ele me apoiou diante do chefe.', '/hiː bækt miː ʌp ɪn frʌnt ʌv ðə bɔːs/', '"Back up" = dar apoio a alguém.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"backed","pos":"verb","ipa":"/bækt/","gloss":"apoiado"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"front","pos":"noun","ipa":"/frʌnt/","gloss":"frente"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"boss","pos":"noun","ipa":"/bɔːs/","gloss":"chefe"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-03', 'lesson-phrasal-b2-05', 3, 'sentence', 'Someone has to step up and take charge.', 'Alguém tem que dar um passo à frente e assumir.', '/ˈsʌmwʌn hæz tuː stɛp ʌp ænd teɪk tʃɑːrdʒ/', '"Step up" = assumir responsabilidade.', '[]'::jsonb, '[{"surface":"Someone","pos":"pronoun","ipa":"/ˈsʌmwʌn/","gloss":"alguém"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"step","pos":"verb","ipa":"/stɛp/","gloss":"dar um passo, passar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"charge","pos":"noun","ipa":"/tʃɑːrdʒ/","gloss":"cobrança"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-04', 'lesson-phrasal-b2-05', 4, 'sentence', 'She picked up on his nervous tone.', 'Ela percebeu o tom nervoso dele.', '/ʃiː pɪkt ʌp ɑːn hɪz ˈnɜːrvəs toʊn/', '"Pick up on" = notar algo sutil.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"picked","pos":"verb","ipa":"/pɪkt/","gloss":"pegou, escolheu"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"nervous","pos":"adjective","ipa":"/ˈnɜːrvəs/","gloss":"nervoso, ansioso"},{"surface":"tone","pos":"noun","ipa":"/toʊn/","gloss":"tom"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-05', 'lesson-phrasal-b2-05', 5, 'sentence', 'You will pick up the language quickly there.', 'Você vai pegar o idioma rápido lá.', '/juː wɪl pɪk ʌp ðə ˈlæŋɡwɪdʒ ˈkwɪkli ðɛr/', '"Pick up" = aprender sem esforço formal.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"pick","pos":"verb","ipa":"/pɪk/","gloss":"pegar (pick up)"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"language","pos":"noun","ipa":"/ˈlæŋɡwɪdʒ/","gloss":"língua, idioma"},{"surface":"quickly","pos":"adverb","ipa":"/ˈkwɪkli/","gloss":"rapidamente"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-06', 'lesson-phrasal-b2-05', 6, 'sentence', 'I caught on to the joke a bit late.', 'Entendi a piada um pouco tarde.', '/aɪ kɔːt ɑːn tuː ðə dʒoʊk ə bɪt leɪt/', '"Catch on" = entender, pegar o jeito.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"caught","pos":"verb","ipa":"/kɔːt/","gloss":"pegou, pegado"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"joke","pos":"noun","ipa":"/dʒoʊk/","gloss":"piada"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-07', 'lesson-phrasal-b2-05', 7, 'sentence', 'Keep an eye out for the delivery.', 'Fique de olho na entrega.', '/kiːp ən aɪ aʊt fɔːr ðə dɪˈlɪvəri/', '"Keep an eye out for" = ficar atento a.', '[]'::jsonb, '[{"surface":"Keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"eye","pos":"noun","ipa":"/aɪ/","gloss":"olho"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"delivery","pos":"noun","ipa":"/dɪˈlɪvəri/","gloss":"entrega"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-08', 'lesson-phrasal-b2-05', 8, 'sentence', 'Watch out for icy roads tonight.', 'Cuidado com estradas com gelo hoje à noite.', '/wɑːtʃ aʊt fɔːr ˈaɪsi roʊdz təˈnaɪt/', '"Watch out for" = tomar cuidado com.', '[]'::jsonb, '[{"surface":"Watch","pos":"noun","ipa":"/wɑːtʃ/","gloss":"relógio de pulso"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"icy","pos":"adjective","ipa":"/ˈaɪsi/","gloss":"com gelo, gelado"},{"surface":"roads","pos":"noun","ipa":"/roʊdz/","gloss":"estradas"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-09', 'lesson-phrasal-b2-05', 9, 'sentence', 'Look out, there is a car coming!', 'Cuidado, vem um carro!', '/lʊk aʊt ðɛr ɪz ə kɑːr ˈkʌmɪŋ/', '"Look out" = cuidado, aviso imediato.', '[]'::jsonb, '[{"surface":"Look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"coming","pos":"verb","ipa":"/ˈkʌmɪŋ/","gloss":"vindo"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-05-10', 'lesson-phrasal-b2-05', 10, 'sentence', 'He has been going on about it all day.', 'Ele passou o dia inteiro falando disso.', '/hiː hæz bɪn ˈɡoʊɪŋ ɑːn əˈbaʊt ɪt ɔːl deɪ/', '"Go on about" = falar sem parar sobre.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-06', 'course-phrasal-adv-b2', 6, 'Quebrar e gastar', 'Fall apart, break down, wear out: o que se desfaz.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-06-01', 'lesson-phrasal-b2-06', 1, 'sentence', 'The old sofa is falling apart.', 'O sofá velho está se desmanchando.', '/ðə oʊld ˈsoʊfə ɪz ˈfɔːlɪŋ əˈpɑːrt/', '"Fall apart" = se desfazer.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"old","pos":"adjective","ipa":"/oʊld/","gloss":"velho; de idade"},{"surface":"sofa","pos":"noun","ipa":"/ˈsoʊfə/","gloss":"sofá"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"falling","pos":"verb","ipa":"/ˈfɔːlɪŋ/","gloss":"caindo"},{"surface":"apart","pos":"adverb","ipa":"/əˈpɑːrt/","gloss":"separado, à parte"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-02', 'lesson-phrasal-b2-06', 2, 'sentence', 'Our car broke down on the highway.', 'Nosso carro quebrou na rodovia.', '/aʊər kɑːr broʊk daʊn ɑːn ðə ˈhaɪweɪ/', '"Break down" = quebrar, parar de funcionar.', '[]'::jsonb, '[{"surface":"Our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"broke","pos":"verb","ipa":"/broʊk/","gloss":"quebrou"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"highway","pos":"noun","ipa":"/ˈhaɪweɪ/","gloss":"rodovia"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-03', 'lesson-phrasal-b2-06', 3, 'sentence', 'These shoes have worn out already.', 'Estes sapatos já se gastaram.', '/ðiːz ʃuːz hæv wɔːrn aʊt ɔːlˈrɛdi/', '"Wear out" = gastar com o uso.', '[]'::jsonb, '[{"surface":"These","pos":"determiner","ipa":"/ðiːz/","gloss":"estes, estas"},{"surface":"shoes","pos":"noun","ipa":"/ʃuːz/","gloss":"sapatos"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"worn","pos":"verb","ipa":"/wɔːrn/","gloss":"gasto"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"already","pos":"adverb","ipa":"/ɔːlˈrɛdi/","gloss":"já"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-04', 'lesson-phrasal-b2-06', 4, 'sentence', 'She broke down in tears at the news.', 'Ela desabou em lágrimas com a notícia.', '/ʃiː broʊk daʊn ɪn tɪrz æt ðə nuːz/', '"Break down" = desabar emocionalmente.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"broke","pos":"verb","ipa":"/broʊk/","gloss":"quebrou"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"tears","pos":"noun","ipa":"/tɪrz/","gloss":"lágrimas"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"news","pos":"noun","ipa":"/nuːz/","gloss":"notícia(s)"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-05', 'lesson-phrasal-b2-06', 5, 'sentence', 'The deal fell through at the last minute.', 'O negócio deu errado na última hora.', '/ðə diːl fɛl θruː æt ðə læst ˈmɪnɪt/', '"Fall through" = fracassar, não se concretizar.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"deal","pos":"noun","ipa":"/diːl/","gloss":"negócio, coisa"},{"surface":"fell","pos":"verb","ipa":"/fɛl/","gloss":"caiu"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"minute","pos":"noun","ipa":"/ˈmɪnɪt/","gloss":"minuto"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-06', 'lesson-phrasal-b2-06', 6, 'sentence', 'A fire broke out in the building.', 'Um incêndio começou no prédio.', '/ə ˈfaɪər broʊk aʊt ɪn ðə ˈbɪldɪŋ/', '"Break out" = começar de repente (fogo, guerra).', '[]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"fire","pos":"noun","ipa":"/ˈfaɪər/","gloss":"fogo, incêndio"},{"surface":"broke","pos":"verb","ipa":"/broʊk/","gloss":"quebrou"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"building","pos":"noun","ipa":"/ˈbɪldɪŋ/","gloss":"prédio"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-07', 'lesson-phrasal-b2-06', 7, 'sentence', 'Prices have been going up for months.', 'Os preços vêm subindo há meses.', '/ˈpraɪsɪz hæv bɪn ˈɡoʊɪŋ ʌp fɔːr mʌnθs/', '"Go up" = subir.', '[]'::jsonb, '[{"surface":"Prices","pos":"noun","ipa":"/ˈpraɪsɪz/","gloss":"preços"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"months","pos":"noun","ipa":"/mʌnθs/","gloss":"meses"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-08', 'lesson-phrasal-b2-06', 8, 'sentence', 'The meeting dragged on for hours.', 'A reunião se arrastou por horas.', '/ðə ˈmiːtɪŋ dræɡd ɑːn fɔːr aʊərz/', '"Drag on" = se arrastar, durar demais.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"dragged","pos":"verb","ipa":"/dræɡd/","gloss":"se arrastou"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"hours","pos":"noun","ipa":"/aʊərz/","gloss":"horas"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-09', 'lesson-phrasal-b2-06', 9, 'sentence', 'Our plans fell apart after the storm.', 'Nossos planos desmoronaram depois da tempestade.', '/aʊər plænz fɛl əˈpɑːrt ˈæftər ðə stɔːrm/', '"Fall apart" também vale para planos.', '[]'::jsonb, '[{"surface":"Our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"plans","pos":"noun","ipa":"/plænz/","gloss":"planos"},{"surface":"fell","pos":"verb","ipa":"/fɛl/","gloss":"caiu"},{"surface":"apart","pos":"adverb","ipa":"/əˈpɑːrt/","gloss":"separado, à parte"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"storm","pos":"noun","ipa":"/stɔːrm/","gloss":"tempestade"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-06-10', 'lesson-phrasal-b2-06', 10, 'sentence', 'I ran out of patience with him.', 'Perdi a paciência com ele.', '/aɪ ræn aʊt ʌv ˈpeɪʃəns wɪð hɪm/', '"Run out of" = ficar sem.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"ran","pos":"verb","ipa":"/ræn/","gloss":"correu"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"patience","pos":"noun","ipa":"/ˈpeɪʃəns/","gloss":"paciência"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-07', 'course-phrasal-adv-b2', 7, 'Segurar e entregar', 'Hold off, hold back, hand in e verbos de adiar e entregar.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-07-01', 'lesson-phrasal-b2-07', 1, 'sentence', 'Let us hold off on the decision until Monday.', 'Vamos adiar a decisão até segunda.', '/lɛt ʌs hoʊld ɔːf ɑːn ðə dɪˈsɪʒən ənˈtɪl ˈmʌndeɪ/', '"Hold off" = adiar, esperar.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"},{"surface":"hold","pos":"verb","ipa":"/hoʊld/","gloss":"aguardar (na linha), segurar"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"decision","pos":"noun","ipa":"/dɪˈsɪʒən/","gloss":"decisão"},{"surface":"until","pos":"conjunction","ipa":"/ənˈtɪl/","gloss":"até"},{"surface":"Monday","pos":"proper noun","ipa":"/ˈmʌndeɪ/","gloss":"segunda-feira"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-02', 'lesson-phrasal-b2-07', 2, 'sentence', 'She held back her tears during the speech.', 'Ela segurou as lágrimas durante o discurso.', '/ʃiː hɛld bæk hɜːr tɪrz ˈdʊrɪŋ ðə spiːtʃ/', '"Hold back" = conter.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"held","pos":"verb","ipa":"/hɛld/","gloss":"segurou, realizou"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"tears","pos":"noun","ipa":"/tɪrz/","gloss":"lágrimas"},{"surface":"during","pos":"preposition","ipa":"/ˈdʊrɪŋ/","gloss":"durante"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"speech","pos":"noun","ipa":"/spiːtʃ/","gloss":"discurso"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-03', 'lesson-phrasal-b2-07', 3, 'sentence', 'Please hand in your homework by Friday.', 'Entregue sua lição até sexta, por favor.', '/pliːz hænd ɪn jʊr ˈhoʊmwɜːrk baɪ ˈfraɪdeɪ/', '"Hand in" = entregar (trabalho); separável.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"hand","pos":"noun","ipa":"/hænd/","gloss":"mão, ajuda"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"homework","pos":"noun","ipa":"/ˈhoʊmwɜːrk/","gloss":"lição de casa"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"Friday","pos":"proper noun","ipa":"/ˈfraɪdeɪ/","gloss":"sexta-feira"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-04', 'lesson-phrasal-b2-07', 4, 'sentence', 'He handed out flyers on the street.', 'Ele distribuiu panfletos na rua.', '/hiː ˈhændɪd aʊt ˈflaɪərz ɑːn ðə striːt/', '"Hand out" = distribuir.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"handed","pos":"verb","ipa":"/ˈhændɪd/","gloss":"entregou"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"flyers","pos":"noun","ipa":"/ˈflaɪərz/","gloss":"panfletos"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"street","pos":"noun","ipa":"/striːt/","gloss":"rua"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-05', 'lesson-phrasal-b2-07', 5, 'sentence', 'They put off the trip because of the weather.', 'Eles adiaram a viagem por causa do tempo.', '/ðeɪ pʊt ɔːf ðə trɪp bɪˈkɔːz ʌv ðə ˈwɛðər/', '"Put off" = adiar; separável.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"trip","pos":"noun","ipa":"/trɪp/","gloss":"viagem"},{"surface":"because","pos":"conjunction","ipa":"/bɪˈkɔːz/","gloss":"porque"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-06', 'lesson-phrasal-b2-07', 6, 'sentence', 'The meeting has been pushed back to Thursday.', 'A reunião foi remarcada para quinta.', '/ðə ˈmiːtɪŋ hæz bɪn pʊʃt bæk tuː ˈθɜːrzdeɪ/', '"Push back" = adiar, empurrar para depois.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"pushed","pos":"verb","ipa":"/pʊʃt/","gloss":"empurrou"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"Thursday","pos":"proper noun","ipa":"/ˈθɜːrzdeɪ/","gloss":"quinta-feira"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-07', 'lesson-phrasal-b2-07', 7, 'sentence', 'I will drop by your office after lunch.', 'Passo no seu escritório depois do almoço.', '/aɪ wɪl drɑːp baɪ jʊr ˈɔːfɪs ˈæftər lʌntʃ/', '"Drop by" = dar uma passada.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"drop","pos":"verb","ipa":"/drɑːp/","gloss":"deixar (drop off)"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"office","pos":"noun","ipa":"/ˈɔːfɪs/","gloss":"escritório, balcão"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"lunch","pos":"noun","ipa":"/lʌntʃ/","gloss":"almoço"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-08', 'lesson-phrasal-b2-07', 8, 'sentence', 'Can you drop off the keys at the front desk?', 'Você pode deixar as chaves na recepção?', '/kæn juː drɑːp ɔːf ðə kiːz æt ðə frʌnt dɛsk/', '"Drop off" = deixar algo em um lugar.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"drop","pos":"verb","ipa":"/drɑːp/","gloss":"deixar (drop off)"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"front","pos":"noun","ipa":"/frʌnt/","gloss":"frente"},{"surface":"desk","pos":"noun","ipa":"/dɛsk/","gloss":"escrivaninha"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-09', 'lesson-phrasal-b2-07', 9, 'sentence', 'We should hold on until we get more data.', 'Devemos esperar até ter mais dados.', '/wiː ʃʊd hoʊld ɑːn ənˈtɪl wiː ɡɛt mɔːr ˈdeɪtə/', '"Hold on" = esperar, aguardar.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"hold","pos":"verb","ipa":"/hoʊld/","gloss":"aguardar (na linha), segurar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"until","pos":"conjunction","ipa":"/ənˈtɪl/","gloss":"até"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"data","pos":"noun","ipa":"/ˈdeɪtə/","gloss":"dados"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-07-10', 'lesson-phrasal-b2-07', 10, 'sentence', 'She handed down the job to her cousin.', 'Ela passou o trabalho adiante para a prima.', '/ʃiː ˈhændɪd daʊn ðə dʒɑːb tuː hɜːr ˈkʌzən/', '"Hand down" = passar adiante, herdar.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"handed","pos":"verb","ipa":"/ˈhændɪd/","gloss":"entregou"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"trabalho"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"cousin","pos":"noun","ipa":"/ˈkʌzən/","gloss":"primo, prima"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-08', 'course-phrasal-adv-b2', 8, 'Recusar e cancelar', 'Turn down, call off, rule out e quem diz não.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-08-01', 'lesson-phrasal-b2-08', 1, 'sentence', 'She turned down the job offer.', 'Ela recusou a oferta de emprego.', '/ʃiː tɜːrnd daʊn ðə dʒɑːb ˈɔːfər/', '"Turn down" = recusar; separável.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"turned","pos":"verb","ipa":"/tɜːrnd/","gloss":"virou, ficou"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"trabalho"},{"surface":"offer","pos":"noun","ipa":"/ˈɔːfər/","gloss":"oferta"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-02', 'lesson-phrasal-b2-08', 2, 'sentence', 'They called off the wedding at the last minute.', 'Eles cancelaram o casamento na última hora.', '/ðeɪ kɔːld ɔːf ðə ˈwɛdɪŋ æt ðə læst ˈmɪnɪt/', '"Call off" = cancelar; separável.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"wedding","pos":"noun","ipa":"/ˈwɛdɪŋ/","gloss":"casamento"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"minute","pos":"noun","ipa":"/ˈmɪnɪt/","gloss":"minuto"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-03', 'lesson-phrasal-b2-08', 3, 'sentence', 'Doctors have ruled out any serious illness.', 'Os médicos descartaram qualquer doença grave.', '/ˈdɑːktərz hæv ruːld aʊt ˈɛni ˈsɪriəs ˈɪlnəs/', '"Rule out" = descartar; separável.', '[]'::jsonb, '[{"surface":"Doctors","pos":"noun","ipa":"/ˈdɑːktərz/","gloss":"médicos"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"ruled","pos":"verb","ipa":"/ruːld/","gloss":"descartou"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"serious","pos":"adjective","ipa":"/ˈsɪriəs/","gloss":"sério"},{"surface":"illness","pos":"noun","ipa":"/ˈɪlnəs/","gloss":"doença"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-04', 'lesson-phrasal-b2-08', 4, 'sentence', 'He backed out of the deal.', 'Ele desistiu do negócio.', '/hiː bækt aʊt ʌv ðə diːl/', '"Back out" = desistir de um compromisso.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"backed","pos":"verb","ipa":"/bækt/","gloss":"apoiado"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"deal","pos":"noun","ipa":"/diːl/","gloss":"negócio, coisa"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-05', 'lesson-phrasal-b2-08', 5, 'sentence', 'I will opt out of the newsletter.', 'Vou sair da lista da newsletter.', '/aɪ wɪl ɑːpt aʊt ʌv ðə ˈnuːzlɛtər/', '"Opt out" = escolher não participar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"opt","pos":"verb","ipa":"/ɑːpt/","gloss":"optar"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"newsletter","pos":"noun","ipa":"/ˈnuːzlɛtər/","gloss":"boletim por e-mail"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-06', 'lesson-phrasal-b2-08', 6, 'sentence', 'The company has phased out that product.', 'A empresa foi retirando esse produto aos poucos.', '/ðə ˈkʌmpəni hæz feɪzd aʊt ðæt ˈprɑːdʌkt/', '"Phase out" = eliminar gradualmente.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"phased","pos":"verb","ipa":"/feɪzd/","gloss":"retirado aos poucos"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"product","pos":"noun","ipa":"/ˈprɑːdʌkt/","gloss":"produto"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-07', 'lesson-phrasal-b2-08', 7, 'sentence', 'Let me cross that off the list.', 'Deixa eu riscar isso da lista.', '/lɛt miː krɔːs ðæt ɔːf ðə lɪst/', '"Cross off" = riscar.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"cross","pos":"verb","ipa":"/krɔːs/","gloss":"riscar, cruzar"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"list","pos":"noun","ipa":"/lɪst/","gloss":"lista"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-08', 'lesson-phrasal-b2-08', 8, 'sentence', 'They shut down the factory last year.', 'Eles fecharam a fábrica no ano passado.', '/ðeɪ ʃʌt daʊn ðə ˈfæktəri læst jɪr/', '"Shut down" = encerrar as atividades.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"shut","pos":"verb","ipa":"/ʃʌt/","gloss":"fechar"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"factory","pos":"noun","ipa":"/ˈfæktəri/","gloss":"fábrica"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-09', 'lesson-phrasal-b2-08', 9, 'sentence', 'The board voted down the proposal.', 'A diretoria rejeitou a proposta na votação.', '/ðə bɔːrd ˈvoʊtɪd daʊn ðə prəˈpoʊzəl/', '"Vote down" = rejeitar por voto.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"board","pos":"noun","ipa":"/bɔːrd/","gloss":"diretoria, conselho"},{"surface":"voted","pos":"verb","ipa":"/ˈvoʊtɪd/","gloss":"votou"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"proposal","pos":"noun","ipa":"/prəˈpoʊzəl/","gloss":"proposta"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-08-10', 'lesson-phrasal-b2-08', 10, 'sentence', 'I had to say no and walk away.', 'Tive que dizer não e ir embora.', '/aɪ hæd tuː seɪ noʊ ænd wɔːk əˈweɪ/', '"Walk away" = abandonar uma situação.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"},{"surface":"no","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"},{"surface":"away","pos":"adverb","ipa":"/əˈweɪ/","gloss":"embora; (right away) já"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-09', 'course-phrasal-adv-b2', 9, 'Acompanhar e atrasar', 'Catch up, keep up with, fall behind e ritmo.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-09-01', 'lesson-phrasal-b2-09', 1, 'sentence', 'I need to catch up on my emails.', 'Preciso colocar meus e-mails em dia.', '/aɪ niːd tuː kætʃ ʌp ɑːn maɪ ˈiːmeɪlz/', '"Catch up on" = colocar em dia.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"catch","pos":"verb","ipa":"/kætʃ/","gloss":"pegar, apanhar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"emails","pos":"noun","ipa":"/ˈiːmeɪlz/","gloss":"e-mails"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-02', 'lesson-phrasal-b2-09', 2, 'sentence', 'She walks so fast that I cannot keep up.', 'Ela anda tão rápido que não consigo acompanhar.', '/ʃiː wɔːks soʊ fæst ðæt aɪ ˈkænɑːt kiːp ʌp/', '"Keep up" = acompanhar o ritmo.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"walks","pos":"verb","ipa":"/wɔːks/","gloss":"anda"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"fast","pos":"adverb","ipa":"/fæst/","gloss":"rápido"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"cannot","pos":"verb","ipa":"/ˈkænɑːt/","gloss":"não posso, não consigo"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-03', 'lesson-phrasal-b2-09', 3, 'sentence', 'He fell behind with the rent.', 'Ele atrasou o aluguel.', '/hiː fɛl bɪˈhaɪnd wɪð ðə rɛnt/', '"Fall behind" = ficar para trás, atrasar.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"fell","pos":"verb","ipa":"/fɛl/","gloss":"caiu"},{"surface":"behind","pos":"preposition","ipa":"/bɪˈhaɪnd/","gloss":"atrás"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"rent","pos":"verb","ipa":"/rɛnt/","gloss":"alugar"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-04', 'lesson-phrasal-b2-09', 4, 'sentence', 'We are catching up with our competitors.', 'Estamos alcançando nossos concorrentes.', '/wiː ɑːr ˈkætʃɪŋ ʌp wɪð aʊər kəmˈpɛtɪtərz/', '"Catch up with" = alcançar.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"catching","pos":"verb","ipa":"/ˈkætʃɪŋ/","gloss":"pegando; catching up = pôr o papo em dia"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"competitors","pos":"noun","ipa":"/kəmˈpɛtɪtərz/","gloss":"concorrentes"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-05', 'lesson-phrasal-b2-09', 5, 'sentence', 'It is hard to keep up with the news.', 'É difícil acompanhar as notícias.', '/ɪt ɪz hɑːrd tuː kiːp ʌp wɪð ðə nuːz/', '"Keep up with" = manter-se atualizado.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"hard","pos":"adjective","ipa":"/hɑːrd/","gloss":"duro, difícil"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"news","pos":"noun","ipa":"/nuːz/","gloss":"notícia(s)"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-06', 'lesson-phrasal-b2-09', 6, 'sentence', 'Slow down, you are going too fast.', 'Devagar, você está indo rápido demais.', '/sloʊ daʊn juː ɑːr ˈɡoʊɪŋ tuː fæst/', '"Slow down" = diminuir o ritmo.', '[]'::jsonb, '[{"surface":"Slow","pos":"adjective","ipa":"/sloʊ/","gloss":"lento"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"fast","pos":"adverb","ipa":"/fæst/","gloss":"rápido"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-07', 'lesson-phrasal-b2-09', 7, 'sentence', 'Speed up or we will miss the train.', 'Acelere ou perdemos o trem.', '/spiːd ʌp ɔːr wiː wɪl mɪs ðə treɪn/', '"Speed up" = acelerar.', '[]'::jsonb, '[{"surface":"Speed","pos":"verb","ipa":"/spiːd/","gloss":"acelerar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"or","pos":"conjunction","ipa":"/ɔːr/","gloss":"ou"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"miss","pos":"verb","ipa":"/mɪs/","gloss":"errar, perder; sentir falta"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"train","pos":"noun","ipa":"/treɪn/","gloss":"trem"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-08', 'lesson-phrasal-b2-09', 8, 'sentence', 'Let us wrap up the meeting by five.', 'Vamos encerrar a reunião até as cinco.', '/lɛt ʌs ræp ʌp ðə ˈmiːtɪŋ baɪ faɪv/', '"Wrap up" = concluir.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"},{"surface":"wrap","pos":"verb","ipa":"/ræp/","gloss":"encerrar, embrulhar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-09', 'lesson-phrasal-b2-09', 9, 'sentence', 'She wound up in a different city.', 'Ela acabou parando em outra cidade.', '/ʃiː waʊnd ʌp ɪn ə ˈdɪfərənt ˈsɪti/', '"Wind up" = acabar em, terminar.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"wound","pos":"verb","ipa":"/waʊnd/","gloss":"acabou (wind up)"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"different","pos":"adjective","ipa":"/ˈdɪfərənt/","gloss":"diferente"},{"surface":"city","pos":"noun","ipa":"/ˈsɪti/","gloss":"cidade"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-09-10', 'lesson-phrasal-b2-09', 10, 'sentence', 'Things are picking up at work.', 'As coisas estão melhorando no trabalho.', '/θɪŋz ɑːr ˈpɪkɪŋ ʌp æt wɜːrk/', '"Pick up" = melhorar, ganhar ritmo.', '[]'::jsonb, '[{"surface":"Things","pos":"noun","ipa":"/θɪŋz/","gloss":"coisas"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"picking","pos":"verb","ipa":"/ˈpɪkɪŋ/","gloss":"pegando; melhorando"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-phrasal-b2-10', 'course-phrasal-adv-b2', 10, 'Encontrar e se destacar', 'Run into, stand out, show up e situações sociais.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-phrasal-b2-10-01', 'lesson-phrasal-b2-10', 1, 'sentence', 'I ran into an old friend at the airport.', 'Encontrei um velho amigo por acaso no aeroporto.', '/aɪ ræn ˈɪntuː ən oʊld frɛnd æt ðə ˈɛrpɔːrt/', '"Run into" = encontrar por acaso.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"ran","pos":"verb","ipa":"/ræn/","gloss":"correu"},{"surface":"into","pos":"preposition","ipa":"/ˈɪntuː/","gloss":"para dentro de"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"old","pos":"adjective","ipa":"/oʊld/","gloss":"velho; de idade"},{"surface":"friend","pos":"noun","ipa":"/frɛnd/","gloss":"amigo, amiga"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"airport","pos":"noun","ipa":"/ˈɛrpɔːrt/","gloss":"aeroporto"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-02', 'lesson-phrasal-b2-10', 2, 'sentence', 'Her design really stands out.', 'O design dela se destaca de verdade.', '/hɜːr dɪˈzaɪn ˈriːəli stændz aʊt/', '"Stand out" = se destacar.', '[]'::jsonb, '[{"surface":"Her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"design","pos":"noun","ipa":"/dɪˈzaɪn/","gloss":"design"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"stands","pos":"verb","ipa":"/stændz/","gloss":"fica de pé, se destaca"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-03', 'lesson-phrasal-b2-10', 3, 'sentence', 'He did not show up for the interview.', 'Ele não apareceu para a entrevista.', '/hiː dɪd nɑːt ʃoʊ ʌp fɔːr ðə ˈɪntərvjuː/', '"Show up" = aparecer, comparecer.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"show","pos":"verb","ipa":"/ʃoʊ/","gloss":"aparecer (show up)"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"interview","pos":"noun","ipa":"/ˈɪntərvjuː/","gloss":"entrevista"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-04', 'lesson-phrasal-b2-10', 4, 'sentence', 'They split up after five years.', 'Eles se separaram depois de cinco anos.', '/ðeɪ splɪt ʌp ˈæftər faɪv jɪrz/', '"Split up" = terminar um relacionamento.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"split","pos":"verb","ipa":"/splɪt/","gloss":"dividir"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-05', 'lesson-phrasal-b2-10', 5, 'sentence', 'We should get together this weekend.', 'A gente devia se encontrar neste fim de semana.', '/wiː ʃʊd ɡɛt təˈɡɛðər ðɪs ˈwiːkɛnd/', '"Get together" = se reunir.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"together","pos":"adverb","ipa":"/təˈɡɛðər/","gloss":"juntos"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"weekend","pos":"noun","ipa":"/ˈwiːkɛnd/","gloss":"fim de semana"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-06', 'lesson-phrasal-b2-10', 6, 'sentence', 'I will see you off at the station.', 'Vou me despedir de você na estação.', '/aɪ wɪl siː juː ɔːf æt ðə ˈsteɪʃən/', '"See off" = ir se despedir.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"station","pos":"noun","ipa":"/ˈsteɪʃən/","gloss":"estação"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-07', 'lesson-phrasal-b2-10', 7, 'sentence', 'She took me in when I had nowhere to go.', 'Ela me acolheu quando eu não tinha para onde ir.', '/ʃiː tʊk miː ɪn wɛn aɪ hæd ˈnoʊwɛr tuː ɡoʊ/', '"Take in" = acolher.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"took","pos":"verb","ipa":"/tʊk/","gloss":"pegou, levou"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"nowhere","pos":"adverb","ipa":"/ˈnoʊwɛr/","gloss":"lugar nenhum"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-08', 'lesson-phrasal-b2-10', 8, 'sentence', 'They threw a party to cheer him up.', 'Eles fizeram uma festa para animá-lo.', '/ðeɪ θruː ə ˈpɑːrti tuː tʃɪr hɪm ʌp/', '"Cheer up" = animar; separável.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"threw","pos":"verb","ipa":"/θruː/","gloss":"deu (festa), jogou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"party","pos":"noun","ipa":"/ˈpɑːrti/","gloss":"festa"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"cheer","pos":"verb","ipa":"/tʃɪr/","gloss":"animar"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-09', 'lesson-phrasal-b2-10', 9, 'sentence', 'Do not leave me out of the plans.', 'Não me deixe fora dos planos.', '/duː nɑːt liːv miː aʊt ʌv ðə plænz/', '"Leave out" = excluir, deixar de fora.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"leave","pos":"verb","ipa":"/liːv/","gloss":"deixar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"plans","pos":"noun","ipa":"/plænz/","gloss":"planos"}]'::jsonb, NULL, NULL),
  ('unit-phrasal-b2-10-10', 'lesson-phrasal-b2-10', 10, 'sentence', 'It is time to move on and start over.', 'É hora de seguir em frente e recomeçar.', '/ɪt ɪz taɪm tuː muːv ɑːn ænd stɑːrt ˈoʊvər/', '"Move on" = seguir em frente; "start over" = recomeçar.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"move","pos":"verb","ipa":"/muːv/","gloss":"mover, passar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"start","pos":"verb","ipa":"/stɑːrt/","gloss":"começar"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"por cima; superado"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
