-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-first-sentences-a1', 'first-sentences-a1', 'Primeiras Frases', 'Do zero às primeiras frases: apresentar-se, perguntar, negar, pedir, falar da rotina, do que gosta e do passado.', 'Monte frases completas desde a primeira aula: verbo "to be", perguntas e negativas, "there is", possessivos, presente simples, "can", imperativo, "like + -ing" e o passado com "was/were". Cada frase vem com a explicação da estrutura.', 'A1', 'grammar', 10, 'fundamentos', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-first-sentences-a1-08', 'course-first-sentences-a1', 8, 'Can: habilidade e pedidos', 'Dizer o que você sabe fazer e pedir com educação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-first-sentences-a1-08-01', 'lesson-first-sentences-a1-08', 1, 'sentence', 'I can swim.', 'Eu sei nadar.', '/aɪ kæn swɪm/', '"Can" + verbo base = conseguir, saber fazer. Nunca "can to swim".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"swim","pos":"verb","ipa":"/swɪm/","gloss":"nadar"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-02', 'lesson-first-sentences-a1-08', 2, 'sentence', 'She can''t drive.', 'Ela não sabe dirigir.', '/ʃiː kænt draɪv/', 'Negativa: "can''t" (cannot). O verbo continua na base.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"drive","pos":"verb","ipa":"/draɪv/","gloss":"dirigir"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-03', 'lesson-first-sentences-a1-08', 3, 'sentence', 'Can you speak slowly?', 'Você pode falar devagar?', '/kæn juː spiːk ˈsloʊli/', 'Pergunta: "can" antes do sujeito. Também serve para pedir.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"speak","pos":"verb","ipa":"/spiːk/","gloss":"falar"},{"surface":"slowly","pos":"adverb","ipa":"/ˈsloʊli/","gloss":"devagar"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-04', 'lesson-first-sentences-a1-08', 4, 'sentence', 'Can I sit here?', 'Posso sentar aqui?', '/kæn aɪ sɪt hɪr/', '"Can I…?" pede permissão de forma simples.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"sit","pos":"verb","ipa":"/sɪt/","gloss":"sentar"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-05', 'lesson-first-sentences-a1-08', 5, 'sentence', 'Could you help me, please?', 'Você poderia me ajudar, por favor?', '/kʊd juː hɛlp miː pliːz/', '"Could" é a versão mais educada de "can" para pedidos.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-06', 'lesson-first-sentences-a1-08', 6, 'sentence', 'I can call you later.', 'Posso te ligar depois.', '/aɪ kæn kɔːl juː ˈleɪtər/', '"Can" também oferece algo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-07', 'lesson-first-sentences-a1-08', 7, 'sentence', 'We can''t hear you.', 'Não conseguimos te ouvir.', '/wiː kænt hɪr juː/', '"Can''t" + verbo de percepção: hear, see.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"hear","pos":"verb","ipa":"/hɪr/","gloss":"ouvir"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-08', 'lesson-first-sentences-a1-08', 8, 'sentence', 'Can he come tomorrow?', 'Ele pode vir amanhã?', '/kæn hiː kʌm təˈmɑːroʊ/', '"Can" não muda com he/she/it: nada de "cans".', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-09', 'lesson-first-sentences-a1-08', 9, 'sentence', 'Yes, you can.', 'Sim, pode.', '/jɛs juː kæn/', 'Resposta curta: sujeito + "can".', '[]'::jsonb, '[{"surface":"Yes","pos":"interjection","ipa":"/jɛs/","gloss":"sim"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-08-10', 'lesson-first-sentences-a1-08', 10, 'sentence', 'I can play the guitar a little.', 'Eu sei tocar um pouco de violão.', '/aɪ kæn pleɪ ðə ɡɪˈtɑːr ə ˈlɪtəl/', '"A little" = um pouco. Instrumento com "the".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"play","pos":"verb","ipa":"/pleɪ/","gloss":"jogar, tocar, brincar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"guitar","pos":"noun","ipa":"/ɡɪˈtɑːr/","gloss":"violão, guitarra"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"little","pos":"adjective","ipa":"/ˈlɪtəl/","gloss":"pouco, pequeno"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-first-sentences-a1-09', 'course-first-sentences-a1', 9, 'Imperativo: instruções e avisos', 'Dar ordens, instruções e avisos com educação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-first-sentences-a1-09-01', 'lesson-first-sentences-a1-09', 1, 'sentence', 'Open the window, please.', 'Abra a janela, por favor.', '/ˈoʊpən ðə ˈwɪndoʊ pliːz/', 'Imperativo = verbo base, sem sujeito. "Please" deixa educado.', '[]'::jsonb, '[{"surface":"Open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"window","pos":"noun","ipa":"/ˈwɪndoʊ/","gloss":"janela"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-02', 'lesson-first-sentences-a1-09', 2, 'sentence', 'Don''t touch that.', 'Não toque nisso.', '/doʊnt tʌtʃ ðæt/', 'Imperativo negativo: "don''t" + verbo base.', '[]'::jsonb, '[{"surface":"Don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"touch","pos":"verb","ipa":"/tʌtʃ/","gloss":"tocar, encostar"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-03', 'lesson-first-sentences-a1-09', 3, 'sentence', 'Turn right at the light.', 'Vire à direita no semáforo.', '/tɜːrn raɪt æt ðə laɪt/', '"The light" = o semáforo (traffic light).', '[]'::jsonb, '[{"surface":"Turn","pos":"verb","ipa":"/tɜːrn/","gloss":"ligar (turn on)"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"light","pos":"adjective","ipa":"/laɪt/","gloss":"claro"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-04', 'lesson-first-sentences-a1-09', 4, 'sentence', 'Wait here, please.', 'Espere aqui, por favor.', '/weɪt hɪr pliːz/', 'Frase comum em filas e recepções.', '[]'::jsonb, '[{"surface":"Wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-05', 'lesson-first-sentences-a1-09', 5, 'sentence', 'Be careful!', 'Cuidado!', '/biː ˈkɛrfəl/', 'Imperativo de "to be": "be" + adjetivo.', '[]'::jsonb, '[{"surface":"Be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"careful","pos":"adjective","ipa":"/ˈkɛrfəl/","gloss":"cuidadoso"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-06', 'lesson-first-sentences-a1-09', 6, 'sentence', 'Don''t be late.', 'Não se atrase.', '/doʊnt biː leɪt/', 'Negativo com "be": "don''t be".', '[]'::jsonb, '[{"surface":"Don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-07', 'lesson-first-sentences-a1-09', 7, 'sentence', 'Take a seat.', 'Sente-se.', '/teɪk ə siːt/', 'Forma educada de convidar alguém a sentar.', '[]'::jsonb, '[{"surface":"Take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"seat","pos":"noun","ipa":"/siːt/","gloss":"assento"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-08', 'lesson-first-sentences-a1-09', 8, 'sentence', 'Call me when you get home.', 'Me liga quando chegar em casa.', '/kɔːl miː wɛn juː ɡɛt hoʊm/', '"Get home" = chegar em casa, sem "to".', '[]'::jsonb, '[{"surface":"Call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-09', 'lesson-first-sentences-a1-09', 9, 'sentence', 'Please sign here.', 'Por favor, assine aqui.', '/pliːz saɪn hɪr/', '"Sign" = assinar; o "g" é mudo: /saɪn/.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"sign","pos":"verb","ipa":"/saɪn/","gloss":"assinar"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-09-10', 'lesson-first-sentences-a1-09', 10, 'sentence', 'Let''s take a break.', 'Vamos fazer uma pausa.', '/lɛts teɪk ə breɪk/', '"Let''s" + verbo = vamos (sugestão que inclui você).', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"break","pos":"noun","ipa":"/breɪk/","gloss":"pausa, intervalo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-first-sentences-a1-10', 'course-first-sentences-a1', 10, 'Gostos: like, love e hate', 'Falar do que você gosta e do que não gosta.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-first-sentences-a1-10-01', 'lesson-first-sentences-a1-10', 1, 'sentence', 'I like music.', 'Eu gosto de música.', '/aɪ laɪk ˈmjuːzɪk/', '"Like" + substantivo, sem "of": nunca "like of music".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"music","pos":"noun","ipa":"/ˈmjuːzɪk/","gloss":"música"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-02', 'lesson-first-sentences-a1-10', 2, 'sentence', 'I love cooking.', 'Eu adoro cozinhar.', '/aɪ lʌv ˈkʊkɪŋ/', '"Love/like/hate" + verbo com "-ing" para atividades.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"love","pos":"verb","ipa":"/lʌv/","gloss":"amar, adorar"},{"surface":"cooking","pos":"verb","ipa":"/ˈkʊkɪŋ/","gloss":"cozinhar (atividade)"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-03', 'lesson-first-sentences-a1-10', 3, 'sentence', 'She doesn''t like waiting.', 'Ela não gosta de esperar.', '/ʃiː ˈdʌzənt laɪk ˈweɪtɪŋ/', 'Negativa com "doesn''t" + "like" + "-ing".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"doesn''t","pos":"verb","ipa":"/ˈdʌzənt/","gloss":"não (does not)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-04', 'lesson-first-sentences-a1-10', 4, 'sentence', 'Do you like dogs?', 'Você gosta de cachorros?', '/duː juː laɪk dɔːɡz/', 'Coisas em geral vão no plural: "dogs", "movies".', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"dogs","pos":"noun","ipa":"/dɔːɡz/","gloss":"cachorros"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-05', 'lesson-first-sentences-a1-10', 5, 'sentence', 'He hates getting up early.', 'Ele odeia acordar cedo.', '/hiː heɪts ˈɡɛtɪŋ ʌp ˈɜːrli/', '"Hate" = odiar. "Get up" = levantar-se.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"hates","pos":"verb","ipa":"/heɪts/","gloss":"odeia"},{"surface":"getting","pos":"verb","ipa":"/ˈɡɛtɪŋ/","gloss":"ficando; getting up = levantar-se"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-06', 'lesson-first-sentences-a1-10', 6, 'sentence', 'I''d like a coffee.', 'Eu queria um café.', '/aɪd laɪk ə ˈkɔːfi/', '"I''d like" (I would like) = eu gostaria. Diferente de "I like" (gosto).', '[]'::jsonb, '[{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-07', 'lesson-first-sentences-a1-10', 7, 'sentence', 'What do you like doing on weekends?', 'O que você gosta de fazer nos fins de semana?', '/wʌt duː juː laɪk ˈduːɪŋ ɑːn ˈwiːkɛndz/', 'Pergunta sobre hobbies.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"doing","pos":"verb","ipa":"/ˈduːɪŋ/","gloss":"fazendo, fazer"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"weekends","pos":"noun","ipa":"/ˈwiːkɛndz/","gloss":"fins de semana"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-08', 'lesson-first-sentences-a1-10', 8, 'sentence', 'I really like this song.', 'Eu gosto muito desta música.', '/aɪ ˈriːəli laɪk ðɪs sɔːŋ/', '"Really" antes do verbo reforça. "Song" = canção.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"song","pos":"noun","ipa":"/sɔːŋ/","gloss":"canção, música"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-09', 'lesson-first-sentences-a1-10', 9, 'sentence', 'I don''t mind.', 'Tanto faz para mim.', '/aɪ doʊnt maɪnd/', '"I don''t mind" = não me importo, tanto faz.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"mind","pos":"verb","ipa":"/maɪnd/","gloss":"se importar"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-10-10', 'lesson-first-sentences-a1-10', 10, 'sentence', 'My favorite food is pizza.', 'Minha comida favorita é pizza.', '/maɪ ˈfeɪvərɪt fuːd ɪz ˈpiːtsə/', 'EUA: "favorite"; Reino Unido: "favourite".', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"favorite","pos":"adjective","ipa":"/ˈfeɪvərɪt/","gloss":"favorito"},{"surface":"food","pos":"noun","ipa":"/fuːd/","gloss":"comida"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"pizza","pos":"noun","ipa":"/ˈpiːtsə/","gloss":"pizza"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-first-sentences-a1-11', 'course-first-sentences-a1', 11, 'Passado com was e were', 'Dizer onde estava e como foi.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-first-sentences-a1-11-01', 'lesson-first-sentences-a1-11', 1, 'sentence', 'I was at home yesterday.', 'Eu estava em casa ontem.', '/aɪ wɑːz æt hoʊm ˈjɛstərdeɪ/', 'Passado de "to be": "was" com I/he/she/it.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-02', 'lesson-first-sentences-a1-11', 2, 'sentence', 'We were very tired.', 'Nós estávamos muito cansados.', '/wiː wɜːr ˈvɛri ˈtaɪərd/', '"Were" com you/we/they.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"were","pos":"verb","ipa":"/wɜːr/","gloss":"eram, estavam"},{"surface":"very","pos":"adverb","ipa":"/ˈvɛri/","gloss":"muito"},{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-03', 'lesson-first-sentences-a1-11', 3, 'sentence', 'Was it expensive?', 'Foi caro?', '/wɑːz ɪt ɪkˈspɛnsɪv/', 'Pergunta: "was/were" antes do sujeito.', '[]'::jsonb, '[{"surface":"Was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"expensive","pos":"adjective","ipa":"/ɪkˈspɛnsɪv/","gloss":"caro"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-04', 'lesson-first-sentences-a1-11', 4, 'sentence', 'The movie wasn''t good.', 'O filme não foi bom.', '/ðə ˈmuːvi ˈwʌzənt ɡʊd/', 'Negativa: "wasn''t" (was not).', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"movie","pos":"noun","ipa":"/ˈmuːvi/","gloss":"filme"},{"surface":"wasn''t","pos":"verb","ipa":"/ˈwʌzənt/","gloss":"não era, não estava (was not)"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-05', 'lesson-first-sentences-a1-11', 5, 'sentence', 'Where were you last night?', 'Onde você estava ontem à noite?', '/wɛr wɜːr juː læst naɪt/', '"Last night" = ontem à noite.', '[]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"were","pos":"verb","ipa":"/wɜːr/","gloss":"eram, estavam"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-06', 'lesson-first-sentences-a1-11', 6, 'sentence', 'It was a great trip.', 'Foi uma viagem ótima.', '/ɪt wɑːz ə ɡreɪt trɪp/', '"It was" para avaliar algo que passou.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"trip","pos":"noun","ipa":"/trɪp/","gloss":"viagem"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-07', 'lesson-first-sentences-a1-11', 7, 'sentence', 'They weren''t at the party.', 'Eles não estavam na festa.', '/ðeɪ wɜːrnt æt ðə ˈpɑːrti/', '"Weren''t" = were not.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"weren''t","pos":"verb","ipa":"/wɜːrnt/","gloss":"não eram, não estavam (were not)"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"party","pos":"noun","ipa":"/ˈpɑːrti/","gloss":"festa"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-08', 'lesson-first-sentences-a1-11', 8, 'sentence', 'How was your weekend?', 'Como foi seu fim de semana?', '/haʊ wɑːz jʊr ˈwiːkɛnd/', 'Pergunta clássica de segunda-feira.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"weekend","pos":"noun","ipa":"/ˈwiːkɛnd/","gloss":"fim de semana"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-09', 'lesson-first-sentences-a1-11', 9, 'sentence', 'There were many people.', 'Tinha muita gente.', '/ðɛr wɜːr ˈmɛni ˈpiːpəl/', 'Passado de "there are": "there were".', '[]'::jsonb, '[{"surface":"There","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"were","pos":"verb","ipa":"/wɜːr/","gloss":"eram, estavam"},{"surface":"many","pos":"determiner","ipa":"/ˈmɛni/","gloss":"muitos (how many)"},{"surface":"people","pos":"noun","ipa":"/ˈpiːpəl/","gloss":"pessoas"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-11-10', 'lesson-first-sentences-a1-11', 10, 'sentence', 'I was born in Brazil.', 'Eu nasci no Brasil.', '/aɪ wɑːz bɔːrn ɪn brəˈzɪl/', '"Be born" é passivo: sempre "I was born", nunca "I born".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"born","pos":"verb","ipa":"/bɔːrn/","gloss":"nascido (be born = nascer)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"Brazil","pos":"proper noun","ipa":"/brəˈzɪl/","gloss":"Brasil"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-first-sentences-a1-12', 'course-first-sentences-a1', 12, 'Revisão: primeiras conversas', 'Uma frase de cada estrutura do curso.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-first-sentences-a1-12-01', 'lesson-first-sentences-a1-12', 1, 'sentence', 'Hi, I''m Ana. I''m from Brazil.', 'Oi, eu sou a Ana. Sou do Brasil.', '/haɪ aɪm ˈænə aɪm frʌm brəˈzɪl/', 'Revisão de "to be": apresentação completa em duas frases.', '[]'::jsonb, '[{"surface":"Hi","pos":"interjection","ipa":"/haɪ/","gloss":"oi"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"Ana","pos":"proper noun","ipa":"/ˈænə/","gloss":"Ana"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"Brazil","pos":"proper noun","ipa":"/brəˈzɪl/","gloss":"Brasil"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-02', 'lesson-first-sentences-a1-12', 2, 'sentence', 'Are you a student?', 'Você é estudante?', '/ɑːr juː ə ˈstuːdənt/', 'Revisão de pergunta com "to be".', '[]'::jsonb, '[{"surface":"Are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"student","pos":"noun","ipa":"/ˈstuːdənt/","gloss":"estudante"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-03', 'lesson-first-sentences-a1-12', 3, 'sentence', 'I''m not busy now.', 'Não estou ocupado agora.', '/aɪm nɑːt ˈbɪzi naʊ/', 'Revisão da negativa com "to be".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"busy","pos":"adjective","ipa":"/ˈbɪzi/","gloss":"ocupado"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-04', 'lesson-first-sentences-a1-12', 4, 'sentence', 'Is there a bus stop near here?', 'Tem ponto de ônibus aqui perto?', '/ɪz ðɛr ə bʌs stɑːp nɪr hɪr/', 'Revisão de "there is".', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"},{"surface":"stop","pos":"verb","ipa":"/stɑːp/","gloss":"parar"},{"surface":"near","pos":"preposition","ipa":"/nɪr/","gloss":"perto de"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-05', 'lesson-first-sentences-a1-12', 5, 'sentence', 'This is my wife, Julia.', 'Esta é minha esposa, Julia.', '/ðɪs ɪz maɪ waɪf ˈdʒuːliə/', 'Revisão de possessivos e "this is" para apresentar.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"wife","pos":"noun","ipa":"/waɪf/","gloss":"esposa"},{"surface":"Julia","pos":"proper noun","ipa":"/ˈdʒuːliə/","gloss":"Julia"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-06', 'lesson-first-sentences-a1-12', 6, 'sentence', 'She works from home.', 'Ela trabalha de casa.', '/ʃiː wɜːrks frʌm hoʊm/', 'Revisão do "-s" de he/she/it.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"works","pos":"verb","ipa":"/wɜːrks/","gloss":"funciona, serve"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-07', 'lesson-first-sentences-a1-12', 7, 'sentence', 'Do you have a pen? I don''t have one.', 'Você tem caneta? Eu não tenho.', '/duː juː hæv ə pɛn aɪ doʊnt hæv wʌn/', 'Revisão de "do" em pergunta e "don''t" na negativa. "One" evita repetir "pen".', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"pen","pos":"noun","ipa":"/pɛn/","gloss":"caneta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-08', 'lesson-first-sentences-a1-12', 8, 'sentence', 'Can you repeat that, please?', 'Pode repetir, por favor?', '/kæn juː rɪˈpiːt ðæt pliːz/', 'Revisão de "can" para pedidos: frase essencial para quem está aprendendo.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"repeat","pos":"verb","ipa":"/rɪˈpiːt/","gloss":"repetir"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-09', 'lesson-first-sentences-a1-12', 9, 'sentence', 'I like walking in the park.', 'Gosto de caminhar no parque.', '/aɪ laɪk ˈwɔːkɪŋ ɪn ðə pɑːrk/', 'Revisão de "like" + "-ing".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"walking","pos":"noun","ipa":"/ˈwɔːkɪŋ/","gloss":"caminhada"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"park","pos":"verb","ipa":"/pɑːrk/","gloss":"estacionar"}]'::jsonb, NULL, NULL),
  ('unit-first-sentences-a1-12-10', 'lesson-first-sentences-a1-12', 10, 'sentence', 'It was nice to meet you.', 'Foi um prazer te conhecer.', '/ɪt wɑːz naɪs tuː miːt juː/', 'Revisão de "was": despedida depois de conhecer alguém.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
