-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-essential-verbs-a1', 'essential-verbs', 'Verbos Essenciais', 'Os verbos mais usados em frases separadas por tempo: presente, passado, futuro e present perfect.', 'Cada verbo aparece em quatro frases reais, uma por tempo verbal, com a explicação gramatical de cada forma. No fim de cada módulo, você revisa as três formas (base, passado e particípio).', 'A1', 'grammar', 12, 'fundamentos', 3, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-25', 'course-essential-verbs-a1', 25, 'move e like', 'Mudar/mover e gostar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-25-01', 'lesson-essential-verbs-a1-25', 1, 'sentence', 'We move to a new apartment next month.', 'A gente se muda para um apartamento novo mês que vem.', '/wiː muːv tuː ə nuː əˈpɑːrtmənt nɛkst mʌnθ/', 'Presente com sentido de futuro já marcado. "Move" = mudar de casa, mover.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"move","pos":"verb","ipa":"/muːv/","gloss":"mover, passar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"apartment","pos":"noun","ipa":"/əˈpɑːrtmənt/","gloss":"apartamento"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-25-02', 'lesson-essential-verbs-a1-25', 2, 'sentence', 'They moved to Canada last year.', 'Eles se mudaram para o Canadá no ano passado.', '/ðeɪ muːvd tuː ˈkænədə læst jɪr/', 'Passado regular: "moved" (/d/).', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"moved","pos":"verb","ipa":"/muːvd/","gloss":"mudou-se, moveu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"Canada","pos":"proper noun","ipa":"/ˈkænədə/","gloss":"Canadá"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-25-03', 'lesson-essential-verbs-a1-25', 3, 'sentence', 'I''ll move the car.', 'Vou tirar o carro.', '/aɪl muːv ðə kɑːr/', 'Futuro com "will" para decisão na hora.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"move","pos":"verb","ipa":"/muːv/","gloss":"mover, passar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-25-04', 'lesson-essential-verbs-a1-25', 4, 'sentence', 'She has moved three times.', 'Ela já se mudou três vezes.', '/ʃiː hæz muːvd θriː taɪmz/', 'Present perfect + número de vezes, sem data.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"moved","pos":"verb","ipa":"/muːvd/","gloss":"mudou-se, moveu"},{"surface":"three","pos":"numeral","ipa":"/θriː/","gloss":"três"},{"surface":"times","pos":"noun","ipa":"/taɪmz/","gloss":"vezes"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-25-05', 'lesson-essential-verbs-a1-25', 5, 'sentence', 'I like this song.', 'Gosto desta música.', '/aɪ laɪk ðɪs sɔːŋ/', '"Like" + substantivo, sem "of".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"song","pos":"noun","ipa":"/sɔːŋ/","gloss":"canção, música"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-25-06', 'lesson-essential-verbs-a1-25', 6, 'sentence', 'He liked the gift.', 'Ele gostou do presente.', '/hiː laɪkt ðə ɡɪft/', 'Passado regular: "liked" (/t/).', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"liked","pos":"verb","ipa":"/laɪkt/","gloss":"gostou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"gift","pos":"noun","ipa":"/ɡɪft/","gloss":"presente"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-25-07', 'lesson-essential-verbs-a1-25', 7, 'sentence', 'You''ll like this place.', 'Você vai gostar deste lugar.', '/juːl laɪk ðɪs pleɪs/', 'Futuro com "will" para previsão.', '[]'::jsonb, '[{"surface":"You''ll","pos":"pronoun","ipa":"/juːl/","gloss":"você vai (you will)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"place","pos":"noun","ipa":"/pleɪs/","gloss":"lugar"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-25-08', 'lesson-essential-verbs-a1-25', 8, 'sentence', 'I''ve always liked Italian food.', 'Sempre gostei de comida italiana.', '/aɪv ˈɔːlweɪz laɪkt ɪˈtæliən fuːd/', 'Present perfect + "always": gosto que vem de longe e continua.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"always","pos":"adverb","ipa":"/ˈɔːlweɪz/","gloss":"sempre"},{"surface":"liked","pos":"verb","ipa":"/laɪkt/","gloss":"gostou"},{"surface":"Italian","pos":"adjective","ipa":"/ɪˈtæliən/","gloss":"italiano"},{"surface":"food","pos":"noun","ipa":"/fuːd/","gloss":"comida"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-26', 'course-essential-verbs-a1', 26, 'live e believe', 'Morar/viver e acreditar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-26-01', 'lesson-essential-verbs-a1-26', 1, 'sentence', 'I live near the beach.', 'Moro perto da praia.', '/aɪ lɪv nɪr ðə biːtʃ/', '"Live" = morar. "Near" = perto de, sem "of".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"live","pos":"verb","ipa":"/lɪv/","gloss":"morar, viver"},{"surface":"near","pos":"preposition","ipa":"/nɪr/","gloss":"perto de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"beach","pos":"noun","ipa":"/biːtʃ/","gloss":"praia"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-26-02', 'lesson-essential-verbs-a1-26', 2, 'sentence', 'We lived in Rio for two years.', 'Moramos no Rio por dois anos.', '/wiː lɪvd ɪn ˈriːoʊ fɔːr tuː jɪrz/', 'Passado com "for" + período já terminado.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"lived","pos":"verb","ipa":"/lɪvd/","gloss":"morou, viveu"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"Rio","pos":"proper noun","ipa":"/ˈriːoʊ/","gloss":"Rio"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-26-03', 'lesson-essential-verbs-a1-26', 3, 'sentence', 'They will live abroad for a while.', 'Eles vão morar fora por um tempo.', '/ðeɪ wɪl lɪv əˈbrɔːd fɔːr ə waɪl/', '"Abroad" = no exterior. "For a while" = por um tempo.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"live","pos":"verb","ipa":"/lɪv/","gloss":"morar, viver"},{"surface":"abroad","pos":"adverb","ipa":"/əˈbrɔːd/","gloss":"no exterior"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"while","pos":"noun","ipa":"/waɪl/","gloss":"tempo (a while = um tempo)"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-26-04', 'lesson-essential-verbs-a1-26', 4, 'sentence', 'I''ve lived here since 2020.', 'Moro aqui desde 2020.', '/aɪv lɪvd hɪr sɪns/', 'Present perfect + "since": ainda mora aqui.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"lived","pos":"verb","ipa":"/lɪvd/","gloss":"morou, viveu"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"since","pos":"preposition","ipa":"/sɪns/","gloss":"desde"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-26-05', 'lesson-essential-verbs-a1-26', 5, 'sentence', 'I don''t believe you.', 'Não acredito em você.', '/aɪ doʊnt bɪˈliːv juː/', '"Believe" + pessoa, sem preposição.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"believe","pos":"verb","ipa":"/bɪˈliːv/","gloss":"acreditar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-26-06', 'lesson-essential-verbs-a1-26', 6, 'sentence', 'Nobody believed his story.', 'Ninguém acreditou na história dele.', '/ˈnoʊbɑːdi bɪˈliːvd hɪz ˈstɔːri/', 'Passado regular: "believed".', '[]'::jsonb, '[{"surface":"Nobody","pos":"pronoun","ipa":"/ˈnoʊbɑːdi/","gloss":"ninguém"},{"surface":"believed","pos":"verb","ipa":"/bɪˈliːvd/","gloss":"acreditou"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"story","pos":"noun","ipa":"/ˈstɔːri/","gloss":"história"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-26-07', 'lesson-essential-verbs-a1-26', 7, 'sentence', 'You won''t believe what happened.', 'Você não vai acreditar no que aconteceu.', '/juː woʊnt bɪˈliːv wʌt ˈhæpənd/', 'Abertura clássica de fofoca: "won''t believe".', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"won''t","pos":"modal verb","ipa":"/woʊnt/","gloss":"não vai (will not)"},{"surface":"believe","pos":"verb","ipa":"/bɪˈliːv/","gloss":"acreditar"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"happened","pos":"verb","ipa":"/ˈhæpənd/","gloss":"aconteceu"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-26-08', 'lesson-essential-verbs-a1-26', 8, 'sentence', 'I''ve never believed in luck.', 'Nunca acreditei em sorte.', '/aɪv ˈnɛvər bɪˈliːvd ɪn lʌk/', '"Believe in" = acreditar em (ideia, existência).', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"believed","pos":"verb","ipa":"/bɪˈliːvd/","gloss":"acreditou"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"luck","pos":"noun","ipa":"/lʌk/","gloss":"sorte"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-27', 'course-essential-verbs-a1', 27, 'hold e bring', 'Segurar/realizar e trazer nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-27-01', 'lesson-essential-verbs-a1-27', 1, 'sentence', 'Hold my bag, please.', 'Segura minha bolsa, por favor.', '/hoʊld maɪ bæɡ pliːz/', 'Imperativo de "hold" (segurar).', '[]'::jsonb, '[{"surface":"Hold","pos":"verb","ipa":"/hoʊld/","gloss":"aguardar (na linha), segurar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"bag","pos":"noun","ipa":"/bæɡ/","gloss":"mala, bolsa"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-27-02', 'lesson-essential-verbs-a1-27', 2, 'sentence', 'She held the baby in her arms.', 'Ela segurou o bebê nos braços.', '/ʃiː hɛld ðə ˈbeɪbi ɪn hɜːr ɑːrmz/', 'Passado irregular: "held".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"held","pos":"verb","ipa":"/hɛld/","gloss":"segurou, realizou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"baby","pos":"noun","ipa":"/ˈbeɪbi/","gloss":"bebê"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"arms","pos":"noun","ipa":"/ɑːrmz/","gloss":"braços"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-27-03', 'lesson-essential-verbs-a1-27', 3, 'sentence', 'We will hold the meeting online.', 'Vamos fazer a reunião online.', '/wiː wɪl hoʊld ðə ˈmiːtɪŋ ˌɑːnˈlaɪn/', '"Hold a meeting" = realizar uma reunião.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"hold","pos":"verb","ipa":"/hoʊld/","gloss":"aguardar (na linha), segurar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"online","pos":"adverb","ipa":"/ˌɑːnˈlaɪn/","gloss":"na internet"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-27-04', 'lesson-essential-verbs-a1-27', 4, 'sentence', 'The police have held two men.', 'A polícia deteve dois homens.', '/ðə pəˈliːs hæv hɛld tuː mɛn/', 'Particípio "held". "Police" sempre pede verbo no plural.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"police","pos":"noun","ipa":"/pəˈliːs/","gloss":"polícia"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"held","pos":"verb","ipa":"/hɛld/","gloss":"segurou, realizou"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"men","pos":"noun","ipa":"/mɛn/","gloss":"homens"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-27-05', 'lesson-essential-verbs-a1-27', 5, 'sentence', 'Bring your passport.', 'Traga seu passaporte.', '/brɪŋ jʊr ˈpæspɔːrt/', '"Bring" = trazer (para cá); "take" = levar (para lá).', '[]'::jsonb, '[{"surface":"Bring","pos":"verb","ipa":"/brɪŋ/","gloss":"trazer"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"passport","pos":"noun","ipa":"/ˈpæspɔːrt/","gloss":"passaporte"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-27-06', 'lesson-essential-verbs-a1-27', 6, 'sentence', 'He brought flowers to the party.', 'Ele levou flores para a festa.', '/hiː brɔːt ˈflaʊərz tuː ðə ˈpɑːrti/', 'Passado irregular: "brought" /brɔːt/.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"},{"surface":"flowers","pos":"noun","ipa":"/ˈflaʊərz/","gloss":"flores"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"party","pos":"noun","ipa":"/ˈpɑːrti/","gloss":"festa"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-27-07', 'lesson-essential-verbs-a1-27', 7, 'sentence', 'I''ll bring dessert.', 'Eu levo a sobremesa.', '/aɪl brɪŋ dɪˈzɜːrt/', 'Oferta com "will". "Dessert" = sobremesa (um "s"); "desert" = deserto.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"bring","pos":"verb","ipa":"/brɪŋ/","gloss":"trazer"},{"surface":"dessert","pos":"noun","ipa":"/dɪˈzɜːrt/","gloss":"sobremesa"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-27-08', 'lesson-essential-verbs-a1-27', 8, 'sentence', 'Have you brought your laptop?', 'Você trouxe seu notebook?', '/hæv juː brɔːt jʊr ˈlæptɑːp/', 'Present perfect: "have brought".', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"laptop","pos":"noun","ipa":"/ˈlæptɑːp/","gloss":"notebook (computador)"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-28', 'course-essential-verbs-a1', 28, 'happen e write', 'Acontecer e escrever nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-28-01', 'lesson-essential-verbs-a1-28', 1, 'sentence', 'What happens next?', 'O que acontece depois?', '/wʌt ˈhæpənz nɛkst/', '"Happen" com he/she/it: "happens". Não usa objeto.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"happens","pos":"verb","ipa":"/ˈhæpənz/","gloss":"acontece"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-28-02', 'lesson-essential-verbs-a1-28', 2, 'sentence', 'What happened?', 'O que aconteceu?', '/wʌt ˈhæpənd/', 'Passado regular: "happened". Pergunta essencial.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"happened","pos":"verb","ipa":"/ˈhæpənd/","gloss":"aconteceu"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-28-03', 'lesson-essential-verbs-a1-28', 3, 'sentence', 'It will happen again.', 'Vai acontecer de novo.', '/ɪt wɪl ˈhæpən əˈɡɛn/', 'Futuro com "will" para previsão.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"happen","pos":"verb","ipa":"/ˈhæpən/","gloss":"acontecer"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-28-04', 'lesson-essential-verbs-a1-28', 4, 'sentence', 'This has never happened before.', 'Isso nunca aconteceu antes.', '/ðɪs hæz ˈnɛvər ˈhæpənd bɪˈfɔːr/', 'Present perfect + "never" + "before".', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"happened","pos":"verb","ipa":"/ˈhæpənd/","gloss":"aconteceu"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-28-05', 'lesson-essential-verbs-a1-28', 5, 'sentence', 'I write in my journal every night.', 'Escrevo no meu diário toda noite.', '/aɪ raɪt ɪn maɪ ˈdʒɜːrnəl ˈɛvri naɪt/', 'Presente para hábito. "Journal" = diário.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"write","pos":"verb","ipa":"/raɪt/","gloss":"escrever"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"journal","pos":"noun","ipa":"/ˈdʒɜːrnəl/","gloss":"diário"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-28-06', 'lesson-essential-verbs-a1-28', 6, 'sentence', 'She wrote a letter to her grandmother.', 'Ela escreveu uma carta para a avó.', '/ʃiː roʊt ə ˈlɛtər tuː hɜːr ˈɡrænmʌðər/', 'Passado irregular: "wrote".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"wrote","pos":"verb","ipa":"/roʊt/","gloss":"escreveu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"letter","pos":"noun","ipa":"/ˈlɛtər/","gloss":"carta, letra"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"grandmother","pos":"noun","ipa":"/ˈɡrænmʌðər/","gloss":"avó"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-28-07', 'lesson-essential-verbs-a1-28', 7, 'sentence', 'I''ll write it down.', 'Vou anotar.', '/aɪl raɪt ɪt daʊn/', '"Write down" = anotar. Objeto no meio: "write it down".', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"write","pos":"verb","ipa":"/raɪt/","gloss":"escrever"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-28-08', 'lesson-essential-verbs-a1-28', 8, 'sentence', 'He has written three books.', 'Ele escreveu três livros.', '/hiː hæz ˈrɪtən θriː bʊks/', 'Particípio irregular: "written" (dois "t").', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"written","pos":"verb","ipa":"/ˈrɪtən/","gloss":"escrito"},{"surface":"three","pos":"numeral","ipa":"/θriː/","gloss":"três"},{"surface":"books","pos":"noun","ipa":"/bʊks/","gloss":"livros"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-29', 'course-essential-verbs-a1', 29, 'sit e stand', 'Sentar e ficar de pé/aguentar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-29-01', 'lesson-essential-verbs-a1-29', 1, 'sentence', 'Please sit down.', 'Por favor, sente-se.', '/pliːz sɪt daʊn/', '"Sit down" = sentar-se.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"sit","pos":"verb","ipa":"/sɪt/","gloss":"sentar"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-29-02', 'lesson-essential-verbs-a1-29', 2, 'sentence', 'We sat by the window.', 'Sentamos perto da janela.', '/wiː sæt baɪ ðə ˈwɪndoʊ/', 'Passado irregular: "sat". "By" = ao lado de.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"sat","pos":"verb","ipa":"/sæt/","gloss":"sentou"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"window","pos":"noun","ipa":"/ˈwɪndoʊ/","gloss":"janela"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-29-03', 'lesson-essential-verbs-a1-29', 3, 'sentence', 'I''ll sit in the back.', 'Vou sentar atrás.', '/aɪl sɪt ɪn ðə bæk/', '"In the back" = na parte de trás.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"sit","pos":"verb","ipa":"/sɪt/","gloss":"sentar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-29-04', 'lesson-essential-verbs-a1-29', 4, 'sentence', 'I''ve sat here all day.', 'Fiquei sentado aqui o dia todo.', '/aɪv sæt hɪr ɔːl deɪ/', 'Particípio igual ao passado: "sat".', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"sat","pos":"verb","ipa":"/sæt/","gloss":"sentou"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-29-05', 'lesson-essential-verbs-a1-29', 5, 'sentence', 'Stand in line, please.', 'Fique na fila, por favor.', '/stænd ɪn laɪn pliːz/', '"Stand in line" = ficar na fila.', '[]'::jsonb, '[{"surface":"Stand","pos":"verb","ipa":"/stænd/","gloss":"ficar de pé; suportar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"line","pos":"noun","ipa":"/laɪn/","gloss":"linha"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-29-06', 'lesson-essential-verbs-a1-29', 6, 'sentence', 'He stood up to speak.', 'Ele se levantou para falar.', '/hiː stʊd ʌp tuː spiːk/', 'Passado irregular: "stood". "Stand up" = levantar-se.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"stood","pos":"verb","ipa":"/stʊd/","gloss":"ficou de pé"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"speak","pos":"verb","ipa":"/spiːk/","gloss":"falar"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-29-07', 'lesson-essential-verbs-a1-29', 7, 'sentence', 'I can''t stand the noise.', 'Não suporto o barulho.', '/aɪ kænt stænd ðə nɔɪz/', '"Can''t stand" = não suportar. Sentido diferente de "ficar de pé".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"stand","pos":"verb","ipa":"/stænd/","gloss":"ficar de pé; suportar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"noise","pos":"noun","ipa":"/nɔɪz/","gloss":"barulho"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-29-08', 'lesson-essential-verbs-a1-29', 8, 'sentence', 'The building has stood here for a century.', 'O prédio está aqui há um século.', '/ðə ˈbɪldɪŋ hæz stʊd hɪr fɔːr ə ˈsɛntʃəri/', 'Particípio "stood". Present perfect + "for" = há.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"building","pos":"noun","ipa":"/ˈbɪldɪŋ/","gloss":"prédio"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"stood","pos":"verb","ipa":"/stʊd/","gloss":"ficou de pé"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"century","pos":"noun","ipa":"/ˈsɛntʃəri/","gloss":"século"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-30', 'course-essential-verbs-a1', 30, 'Revisão: módulo 5', 'Base, passado e particípio dos 10 verbos do módulo 5.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-30-01', 'lesson-essential-verbs-a1-30', 1, 'verb_forms', 'move moved moved', 'mudar, mover', '/muːv muːvd muːvd/', 'Regular: "-d" soa /d/.', '[]'::jsonb, '[{"surface":"move","pos":"verb","ipa":"/muːv/","gloss":"mover, passar"},{"surface":"moved","pos":"verb","ipa":"/muːvd/","gloss":"mudou-se, moveu"},{"surface":"moved","pos":"verb","ipa":"/muːvd/","gloss":"mudou-se, moveu"}]'::jsonb, 'They moved to Canada last year.', 'Eles se mudaram para o Canadá no ano passado.'),
  ('unit-essential-verbs-a1-30-02', 'lesson-essential-verbs-a1-30', 2, 'verb_forms', 'like liked liked', 'gostar', '/laɪk laɪkt laɪkt/', 'Regular: "-d" soa /t/.', '[]'::jsonb, '[{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"liked","pos":"verb","ipa":"/laɪkt/","gloss":"gostou"},{"surface":"liked","pos":"verb","ipa":"/laɪkt/","gloss":"gostou"}]'::jsonb, 'He liked the gift.', 'Ele gostou do presente.'),
  ('unit-essential-verbs-a1-30-03', 'lesson-essential-verbs-a1-30', 3, 'verb_forms', 'live lived lived', 'morar, viver', '/lɪv lɪvd lɪvd/', 'Regular: "-d" soa /d/.', '[]'::jsonb, '[{"surface":"live","pos":"verb","ipa":"/lɪv/","gloss":"morar, viver"},{"surface":"lived","pos":"verb","ipa":"/lɪvd/","gloss":"morou, viveu"},{"surface":"lived","pos":"verb","ipa":"/lɪvd/","gloss":"morou, viveu"}]'::jsonb, 'We lived in Rio for two years.', 'Moramos no Rio por dois anos.'),
  ('unit-essential-verbs-a1-30-04', 'lesson-essential-verbs-a1-30', 4, 'verb_forms', 'believe believed believed', 'acreditar', '/bɪˈliːv bɪˈliːvd bɪˈliːvd/', 'Regular.', '[]'::jsonb, '[{"surface":"believe","pos":"verb","ipa":"/bɪˈliːv/","gloss":"acreditar"},{"surface":"believed","pos":"verb","ipa":"/bɪˈliːvd/","gloss":"acreditou"},{"surface":"believed","pos":"verb","ipa":"/bɪˈliːvd/","gloss":"acreditou"}]'::jsonb, 'Nobody believed his story.', 'Ninguém acreditou na história dele.'),
  ('unit-essential-verbs-a1-30-05', 'lesson-essential-verbs-a1-30', 5, 'verb_forms', 'hold held held', 'segurar, realizar', '/hoʊld hɛld hɛld/', 'Base "hold" · passado e particípio "held".', '[]'::jsonb, '[{"surface":"hold","pos":"verb","ipa":"/hoʊld/","gloss":"aguardar (na linha), segurar"},{"surface":"held","pos":"verb","ipa":"/hɛld/","gloss":"segurou, realizou"},{"surface":"held","pos":"verb","ipa":"/hɛld/","gloss":"segurou, realizou"}]'::jsonb, 'She held the baby in her arms.', 'Ela segurou o bebê nos braços.'),
  ('unit-essential-verbs-a1-30-06', 'lesson-essential-verbs-a1-30', 6, 'verb_forms', 'bring brought brought', 'trazer', '/brɪŋ brɔːt brɔːt/', 'Base "bring" · passado e particípio "brought".', '[]'::jsonb, '[{"surface":"bring","pos":"verb","ipa":"/brɪŋ/","gloss":"trazer"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"}]'::jsonb, 'He brought flowers to the party.', 'Ele levou flores para a festa.'),
  ('unit-essential-verbs-a1-30-07', 'lesson-essential-verbs-a1-30', 7, 'verb_forms', 'happen happened happened', 'acontecer', '/ˈhæpən ˈhæpənd ˈhæpənd/', 'Regular.', '[]'::jsonb, '[{"surface":"happen","pos":"verb","ipa":"/ˈhæpən/","gloss":"acontecer"},{"surface":"happened","pos":"verb","ipa":"/ˈhæpənd/","gloss":"aconteceu"},{"surface":"happened","pos":"verb","ipa":"/ˈhæpənd/","gloss":"aconteceu"}]'::jsonb, 'What happened?', 'O que aconteceu?'),
  ('unit-essential-verbs-a1-30-08', 'lesson-essential-verbs-a1-30', 8, 'verb_forms', 'write wrote written', 'escrever', '/raɪt roʊt ˈrɪtən/', 'Base "write" · passado "wrote" · particípio "written".', '[]'::jsonb, '[{"surface":"write","pos":"verb","ipa":"/raɪt/","gloss":"escrever"},{"surface":"wrote","pos":"verb","ipa":"/roʊt/","gloss":"escreveu"},{"surface":"written","pos":"verb","ipa":"/ˈrɪtən/","gloss":"escrito"}]'::jsonb, 'She wrote a letter to her grandmother.', 'Ela escreveu uma carta para a avó.'),
  ('unit-essential-verbs-a1-30-09', 'lesson-essential-verbs-a1-30', 9, 'verb_forms', 'sit sat sat', 'sentar', '/sɪt sæt sæt/', 'Base "sit" · passado e particípio "sat".', '[]'::jsonb, '[{"surface":"sit","pos":"verb","ipa":"/sɪt/","gloss":"sentar"},{"surface":"sat","pos":"verb","ipa":"/sæt/","gloss":"sentou"},{"surface":"sat","pos":"verb","ipa":"/sæt/","gloss":"sentou"}]'::jsonb, 'We sat by the window.', 'Sentamos perto da janela.'),
  ('unit-essential-verbs-a1-30-10', 'lesson-essential-verbs-a1-30', 10, 'verb_forms', 'stand stood stood', 'ficar de pé, aguentar', '/stænd stʊd stʊd/', 'Base "stand" · passado e particípio "stood".', '[]'::jsonb, '[{"surface":"stand","pos":"verb","ipa":"/stænd/","gloss":"ficar de pé; suportar"},{"surface":"stood","pos":"verb","ipa":"/stʊd/","gloss":"ficou de pé"},{"surface":"stood","pos":"verb","ipa":"/stʊd/","gloss":"ficou de pé"}]'::jsonb, 'He stood up to speak.', 'Ele se levantou para falar.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
