-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-travel-a2', 'travel-no-stress-a2', 'Viagem sem Aperto', 'Aeroporto, avião, imigração, hotel, transporte, restaurante, farmácia e emergências: as frases que você realmente precisa na viagem.', 'Situações de viagem com o que você diz e o que ouve do outro lado: despachar mala, passar pela segurança e pela imigração, falar com a tripulação, resolver bagagem extraviada, pedir no restaurante e no café, comprar remédio, pedir direções e lidar com emergências.', 'A2', 'travel', 2, 'viagem', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-12', 'course-travel-a2', 12, 'Segurança e embarque', 'Raio-x, líquidos, portão e chamada de embarque.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-12-01', 'lesson-travel-a2-12', 1, 'sentence', 'Please put your bag on the belt.', 'Por favor, coloque sua bolsa na esteira.', '/pliːz pʊt jʊr bæɡ ɑːn ðə bɛlt/', 'Fala do agente de segurança. "Belt" = esteira (também é cinto).', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Please"},{"start":7,"end":10,"role":"predicate_verb","surface":"put"},{"start":11,"end":19,"role":"direct_object","surface":"your bag"},{"start":20,"end":32,"role":"adverbial","surface":"on the belt."}]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"bag","pos":"noun","ipa":"/bæɡ/","gloss":"mala, bolsa"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"belt","pos":"noun","ipa":"/bɛlt/","gloss":"esteira; cinto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-02', 'lesson-travel-a2-12', 2, 'sentence', 'Take your laptop out of the bag.', 'Tire o notebook da bolsa.', '/teɪk jʊr ˈlæptɑːp aʊt ʌv ðə bæɡ/', '"Take out of" = tirar de dentro. O computador portátil é "laptop" (notebook é caderno).', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Take"},{"start":5,"end":16,"role":"direct_object","surface":"your laptop"},{"start":17,"end":32,"role":"adverbial","surface":"out of the bag."}]'::jsonb, '[{"surface":"Take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"laptop","pos":"noun","ipa":"/ˈlæptɑːp/","gloss":"notebook (computador)"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bag","pos":"noun","ipa":"/bæɡ/","gloss":"mala, bolsa"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-03', 'lesson-travel-a2-12', 3, 'sentence', 'Do I need to take off my shoes?', 'Preciso tirar os sapatos?', '/duː aɪ niːd tuː teɪk ɔːf maɪ ʃuːz/', '"Take off" = tirar (roupa, sapato). O contrário é "put on".', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":4,"role":"subject","surface":"I"},{"start":5,"end":9,"role":"predicate_verb","surface":"need"},{"start":10,"end":31,"role":"direct_object","surface":"to take off my shoes?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"shoes","pos":"noun","ipa":"/ʃuːz/","gloss":"sapatos"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-04', 'lesson-travel-a2-12', 4, 'sentence', 'Any liquids in your bag?', 'Algum líquido na bolsa?', '/ˈɛni ˈlɪkwɪdz ɪn jʊr bæɡ/', 'Pergunta curta do agente (forma reduzida de "Do you have any liquids…?").', '[{"start":0,"end":11,"role":"direct_object","surface":"Any liquids"},{"start":12,"end":24,"role":"adverbial","surface":"in your bag?"}]'::jsonb, '[{"surface":"Any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"liquids","pos":"noun","ipa":"/ˈlɪkwɪdz/","gloss":"líquidos"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"bag","pos":"noun","ipa":"/bæɡ/","gloss":"mala, bolsa"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-05', 'lesson-travel-a2-12', 5, 'sentence', 'Step through, please.', 'Passe, por favor.', '/stɛp θruː pliːz/', 'Ordem para atravessar o detector de metais. "Step" = dar um passo.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Step"},{"start":5,"end":13,"role":"adverbial","surface":"through,"},{"start":14,"end":21,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"Step","pos":"verb","ipa":"/stɛp/","gloss":"dar um passo, passar"},{"surface":"through","pos":"adverb","ipa":"/θruː/","gloss":"através"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-06', 'lesson-travel-a2-12', 6, 'sentence', 'The gate has changed.', 'O portão mudou.', '/ðə ɡeɪt hæz tʃeɪndʒd/', 'Present perfect para uma mudança com efeito agora. Confira o painel: "departures board".', '[{"start":0,"end":8,"role":"subject","surface":"The gate"},{"start":9,"end":21,"role":"predicate_verb","surface":"has changed."}]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"gate","pos":"noun","ipa":"/ɡeɪt/","gloss":"portão"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"changed","pos":"verb","ipa":"/tʃeɪndʒd/","gloss":"mudou, mudado"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-07', 'lesson-travel-a2-12', 7, 'sentence', 'We are now boarding group two.', 'Estamos embarcando agora o grupo dois.', '/wiː ɑːr naʊ ˈbɔːrdɪŋ ɡruːp tuː/', 'Aviso do portão. Seu grupo está no cartão de embarque.', '[{"start":0,"end":2,"role":"subject","surface":"We"},{"start":3,"end":19,"role":"predicate_verb","surface":"are now boarding"},{"start":20,"end":30,"role":"direct_object","surface":"group two."}]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"},{"surface":"boarding","pos":"noun","ipa":"/ˈbɔːrdɪŋ/","gloss":"embarque"},{"surface":"group","pos":"noun","ipa":"/ɡruːp/","gloss":"grupo"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-08', 'lesson-travel-a2-12', 8, 'sentence', 'May I see your boarding pass?', 'Posso ver seu cartão de embarque?', '/meɪ aɪ siː jʊr ˈbɔːrdɪŋ pæs/', '"May I" é pedido de permissão bem formal, típico de funcionário.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"May"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"see"},{"start":10,"end":29,"role":"direct_object","surface":"your boarding pass?"}]'::jsonb, '[{"surface":"May","pos":"modal verb","ipa":"/meɪ/","gloss":"poder (permissão formal)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"boarding","pos":"noun","ipa":"/ˈbɔːrdɪŋ/","gloss":"embarque"},{"surface":"pass","pos":"noun","ipa":"/pæs/","gloss":"cartão, passe"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-09', 'lesson-travel-a2-12', 9, 'sentence', 'This is the final call for flight two ten.', 'Esta é a última chamada para o voo duzentos e dez.', '/ðɪs ɪz ðə ˈfaɪnəl kɔːl fɔːr flaɪt tuː tɛn/', '"Final call" = última chamada. Números de voo costumam ser lidos em grupos: "two ten".', '[{"start":0,"end":4,"role":"subject","surface":"This"},{"start":5,"end":7,"role":"predicate_verb","surface":"is"},{"start":8,"end":22,"role":"predicate_adj","surface":"the final call"},{"start":23,"end":42,"role":"adverbial","surface":"for flight two ten."}]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"final","pos":"adjective","ipa":"/ˈfaɪnəl/","gloss":"final, último"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"flight","pos":"noun","ipa":"/flaɪt/","gloss":"voo"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-12-10', 'lesson-travel-a2-12', 10, 'sentence', 'Is this the line for Lisbon?', 'Esta é a fila para Lisboa?', '/ɪz ðɪs ðə laɪn fɔːr ˈlɪzbən/', '"Line" (EUA) ou "queue" (Reino Unido) = fila.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":7,"role":"subject","surface":"this"},{"start":8,"end":16,"role":"predicate_adj","surface":"the line"},{"start":17,"end":28,"role":"adverbial","surface":"for Lisbon?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"line","pos":"noun","ipa":"/laɪn/","gloss":"linha"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"Lisbon","pos":"proper noun","ipa":"/ˈlɪzbən/","gloss":"Lisboa"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-13', 'course-travel-a2', 13, 'No avião', 'Assento, bagagem de mão, comida e pedidos à tripulação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-13-01', 'lesson-travel-a2-13', 1, 'sentence', 'I think you''re in my seat.', 'Acho que você está no meu assento.', '/aɪ θɪŋk jʊr ɪn maɪ siːt/', '"I think" deixa a frase educada; mostre o cartão de embarque.', '[{"start":0,"end":7,"role":"discourse_marker","surface":"I think"},{"start":8,"end":14,"role":"subject","surface":"you''re"},{"start":15,"end":26,"role":"adverbial","surface":"in my seat."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"you''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"seat","pos":"noun","ipa":"/siːt/","gloss":"assento"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-02', 'lesson-travel-a2-13', 2, 'sentence', 'Can you help me with my bag?', 'Pode me ajudar com a minha mala?', '/kæn juː hɛlp miː wɪð maɪ bæɡ/', '"Help me with" + objeto = ajudar com. Útil para colocar a mala no compartimento.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"help"},{"start":13,"end":15,"role":"direct_object","surface":"me"},{"start":16,"end":28,"role":"adverbial","surface":"with my bag?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"bag","pos":"noun","ipa":"/bæɡ/","gloss":"mala, bolsa"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-03', 'lesson-travel-a2-13', 3, 'sentence', 'Please fasten your seat belt.', 'Por favor, aperte o cinto de segurança.', '/pliːz ˈfæsən jʊr siːt bɛlt/', '"Fasten" = afivelar; o "t" é mudo: /ˈfæsən/.', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Please"},{"start":7,"end":13,"role":"predicate_verb","surface":"fasten"},{"start":14,"end":29,"role":"direct_object","surface":"your seat belt."}]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"fasten","pos":"verb","ipa":"/ˈfæsən/","gloss":"afivelar, apertar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"seat","pos":"noun","ipa":"/siːt/","gloss":"assento"},{"surface":"belt","pos":"noun","ipa":"/bɛlt/","gloss":"esteira; cinto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-04', 'lesson-travel-a2-13', 4, 'sentence', 'Chicken or pasta?', 'Frango ou massa?', '/ˈtʃɪkən ɔːr ˈpɑːstə/', 'Pergunta típica do serviço de bordo. Responda só com a opção: "Pasta, please".', '[{"start":0,"end":7,"role":"direct_object","surface":"Chicken"},{"start":8,"end":10,"role":"discourse_marker","surface":"or"},{"start":11,"end":17,"role":"direct_object","surface":"pasta?"}]'::jsonb, '[{"surface":"Chicken","pos":"noun","ipa":"/ˈtʃɪkən/","gloss":"frango"},{"surface":"or","pos":"conjunction","ipa":"/ɔːr/","gloss":"ou"},{"surface":"pasta","pos":"noun","ipa":"/ˈpɑːstə/","gloss":"massa"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-05', 'lesson-travel-a2-13', 5, 'sentence', 'Could I have a blanket?', 'Poderia me dar um cobertor?', '/kʊd aɪ hæv ə ˈblæŋkɪt/', '"Could I have" é o pedido educado padrão. "Pillow" = travesseiro.', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Could"},{"start":6,"end":7,"role":"subject","surface":"I"},{"start":8,"end":12,"role":"predicate_verb","surface":"have"},{"start":13,"end":23,"role":"direct_object","surface":"a blanket?"}]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"blanket","pos":"noun","ipa":"/ˈblæŋkɪt/","gloss":"cobertor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-06', 'lesson-travel-a2-13', 6, 'sentence', 'May I switch seats?', 'Posso trocar de assento?', '/meɪ aɪ swɪtʃ siːts/', '"Switch seats" = trocar de lugar. "Seats" fica no plural.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"May"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":12,"role":"predicate_verb","surface":"switch"},{"start":13,"end":19,"role":"direct_object","surface":"seats?"}]'::jsonb, '[{"surface":"May","pos":"modal verb","ipa":"/meɪ/","gloss":"poder (permissão formal)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"switch","pos":"verb","ipa":"/swɪtʃ/","gloss":"trocar"},{"surface":"seats","pos":"noun","ipa":"/siːts/","gloss":"assentos"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-07', 'lesson-travel-a2-13', 7, 'sentence', 'Excuse me, can I get out?', 'Com licença, posso passar?', '/ɪkˈskjuːz miː kæn aɪ ɡɛt aʊt/', 'Para sair do assento da janela. "Get out" = sair.', '[{"start":0,"end":10,"role":"discourse_marker","surface":"Excuse me,"},{"start":11,"end":14,"role":"predicate_verb","surface":"can"},{"start":15,"end":16,"role":"subject","surface":"I"},{"start":17,"end":25,"role":"predicate_verb","surface":"get out?"}]'::jsonb, '[{"surface":"Excuse","pos":"verb","ipa":"/ɪkˈskjuːz/","gloss":"desculpar (excuse me = com licença)"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-08', 'lesson-travel-a2-13', 8, 'sentence', 'How long is the flight?', 'Quanto tempo dura o voo?', '/haʊ lɔːŋ ɪz ðə flaɪt/', '"How long" pergunta duração. Resposta: "About nine hours".', '[{"start":0,"end":8,"role":"adverbial","surface":"How long"},{"start":9,"end":11,"role":"predicate_verb","surface":"is"},{"start":12,"end":23,"role":"subject","surface":"the flight?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"flight","pos":"noun","ipa":"/flaɪt/","gloss":"voo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-09', 'lesson-travel-a2-13', 9, 'sentence', 'We are starting our descent.', 'Estamos iniciando a descida.', '/wiː ɑːr ˈstɑːrtɪŋ aʊər dɪˈsɛnt/', 'Aviso do piloto. "Descent" = descida; "landing" = pouso.', '[{"start":0,"end":2,"role":"subject","surface":"We"},{"start":3,"end":15,"role":"predicate_verb","surface":"are starting"},{"start":16,"end":28,"role":"direct_object","surface":"our descent."}]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"starting","pos":"verb","ipa":"/ˈstɑːrtɪŋ/","gloss":"começando"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"descent","pos":"noun","ipa":"/dɪˈsɛnt/","gloss":"descida"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-13-10', 'lesson-travel-a2-13', 10, 'sentence', 'Please keep your seat belt on.', 'Por favor, mantenha o cinto afivelado.', '/pliːz kiːp jʊr siːt bɛlt ɑːn/', '"Keep on" = manter (ligado, colocado). O objeto fica no meio: "keep it on".', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Please"},{"start":7,"end":11,"role":"predicate_verb","surface":"keep"},{"start":12,"end":26,"role":"direct_object","surface":"your seat belt"},{"start":27,"end":30,"role":"adverbial","surface":"on."}]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"seat","pos":"noun","ipa":"/siːt/","gloss":"assento"},{"surface":"belt","pos":"noun","ipa":"/bɛlt/","gloss":"esteira; cinto"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-14', 'course-travel-a2', 14, 'Imigração e alfândega', 'Motivo da viagem, hospedagem e declarar itens.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-14-01', 'lesson-travel-a2-14', 1, 'sentence', 'What is the purpose of your visit?', 'Qual o motivo da sua visita?', '/wʌt ɪz ðə ˈpɜːrpəs ʌv jʊr ˈvɪzɪt/', 'Pergunta clássica do oficial. Respostas: tourism, business, visiting family.', '[{"start":0,"end":4,"role":"predicate_adj","surface":"What"},{"start":5,"end":7,"role":"predicate_verb","surface":"is"},{"start":8,"end":34,"role":"subject","surface":"the purpose of your visit?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"purpose","pos":"noun","ipa":"/ˈpɜːrpəs/","gloss":"propósito, motivo"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"visit","pos":"noun","ipa":"/ˈvɪzɪt/","gloss":"visita"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-02', 'lesson-travel-a2-14', 2, 'sentence', 'I''m here on vacation.', 'Estou aqui de férias.', '/aɪm hɪr ɑːn veɪˈkeɪʃən/', '"On vacation" (EUA) ou "on holiday" (Reino Unido) = de férias.', '[{"start":0,"end":3,"role":"subject","surface":"I''m"},{"start":4,"end":8,"role":"adverbial","surface":"here"},{"start":9,"end":21,"role":"adverbial","surface":"on vacation."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"vacation","pos":"noun","ipa":"/veɪˈkeɪʃən/","gloss":"férias"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-03', 'lesson-travel-a2-14', 3, 'sentence', 'How long will you stay?', 'Quanto tempo vai ficar?', '/haʊ lɔːŋ wɪl juː steɪ/', 'Futuro com "will". Responda com o período: "Two weeks".', '[{"start":0,"end":8,"role":"adverbial","surface":"How long"},{"start":9,"end":13,"role":"predicate_verb","surface":"will"},{"start":14,"end":17,"role":"subject","surface":"you"},{"start":18,"end":23,"role":"predicate_verb","surface":"stay?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"stay","pos":"verb","ipa":"/steɪ/","gloss":"ficar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-04', 'lesson-travel-a2-14', 4, 'sentence', 'I''m staying for two weeks.', 'Vou ficar duas semanas.', '/aɪm ˈsteɪɪŋ fɔːr tuː wiːks/', 'Presente contínuo para plano já decidido. "For" + período.', '[{"start":0,"end":11,"role":"predicate_verb","surface":"I''m staying"},{"start":12,"end":26,"role":"adverbial","surface":"for two weeks."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"staying","pos":"verb","ipa":"/ˈsteɪɪŋ/","gloss":"ficando, hospedado"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"weeks","pos":"noun","ipa":"/wiːks/","gloss":"semanas"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-05', 'lesson-travel-a2-14', 5, 'sentence', 'Where are you staying?', 'Onde você vai ficar hospedado?', '/wɛr ɑːr juː ˈsteɪɪŋ/', 'Tenha o endereço do hotel à mão.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":9,"role":"predicate_verb","surface":"are"},{"start":10,"end":13,"role":"subject","surface":"you"},{"start":14,"end":22,"role":"predicate_verb","surface":"staying?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"staying","pos":"verb","ipa":"/ˈsteɪɪŋ/","gloss":"ficando, hospedado"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-06', 'lesson-travel-a2-14', 6, 'sentence', 'I''m staying at a hotel downtown.', 'Vou ficar num hotel no centro.', '/aɪm ˈsteɪɪŋ æt ə hoʊˈtɛl ˌdaʊnˈtaʊn/', '"Downtown" (EUA) = centro da cidade; no Reino Unido, "city centre".', '[{"start":0,"end":11,"role":"predicate_verb","surface":"I''m staying"},{"start":12,"end":22,"role":"adverbial","surface":"at a hotel"},{"start":23,"end":32,"role":"adverbial","surface":"downtown."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"staying","pos":"verb","ipa":"/ˈsteɪɪŋ/","gloss":"ficando, hospedado"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"hotel","pos":"noun","ipa":"/hoʊˈtɛl/","gloss":"hotel"},{"surface":"downtown","pos":"adverb","ipa":"/ˌdaʊnˈtaʊn/","gloss":"para o centro"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-07', 'lesson-travel-a2-14', 7, 'sentence', 'Do you have anything to declare?', 'Tem algo a declarar?', '/duː juː hæv ˈɛniθɪŋ tuː dɪˈklɛr/', 'Pergunta da alfândega. "Declare" = declarar mercadorias.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":6,"role":"subject","surface":"you"},{"start":7,"end":11,"role":"predicate_verb","surface":"have"},{"start":12,"end":32,"role":"direct_object","surface":"anything to declare?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"declare","pos":"verb","ipa":"/dɪˈklɛr/","gloss":"declarar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-08', 'lesson-travel-a2-14', 8, 'sentence', 'No, nothing to declare.', 'Não, nada a declarar.', '/noʊ ˈnʌθɪŋ tuː dɪˈklɛr/', '"Nothing" já é negativo: não use "not" junto.', '[{"start":0,"end":3,"role":"discourse_marker","surface":"No,"},{"start":4,"end":11,"role":"direct_object","surface":"nothing"},{"start":12,"end":23,"role":"predicate_verb","surface":"to declare."}]'::jsonb, '[{"surface":"No","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"nothing","pos":"pronoun","ipa":"/ˈnʌθɪŋ/","gloss":"nada"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"declare","pos":"verb","ipa":"/dɪˈklɛr/","gloss":"declarar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-09', 'lesson-travel-a2-14', 9, 'sentence', 'Is this your first time here?', 'É a sua primeira vez aqui?', '/ɪz ðɪs jʊr fɜːrst taɪm hɪr/', '"First time" = primeira vez. Pergunta simpática, às vezes para puxar conversa.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":7,"role":"subject","surface":"this"},{"start":8,"end":23,"role":"predicate_adj","surface":"your first time"},{"start":24,"end":29,"role":"adverbial","surface":"here?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-14-10', 'lesson-travel-a2-14', 10, 'sentence', 'Can I see your return ticket?', 'Posso ver sua passagem de volta?', '/kæn aɪ siː jʊr rɪˈtɜːrn ˈtɪkɪt/', '"Return ticket" = passagem de volta; "round trip" = ida e volta (EUA).', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"see"},{"start":10,"end":29,"role":"direct_object","surface":"your return ticket?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"return","pos":"adjective","ipa":"/rɪˈtɜːrn/","gloss":"de volta"},{"surface":"ticket","pos":"noun","ipa":"/ˈtɪkɪt/","gloss":"passagem, bilhete"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-15', 'course-travel-a2', 15, 'Bagagem extraviada e atrasos', 'Registrar mala perdida, conexão perdida e remarcação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-15-01', 'lesson-travel-a2-15', 1, 'sentence', 'My suitcase didn''t arrive.', 'Minha mala não chegou.', '/maɪ ˈsuːtkeɪs ˈdɪdənt əˈraɪv/', 'Passado negativo: "didn''t" + verbo base (arrive, não arrived).', '[{"start":0,"end":11,"role":"subject","surface":"My suitcase"},{"start":12,"end":26,"role":"predicate_verb","surface":"didn''t arrive."}]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"suitcase","pos":"noun","ipa":"/ˈsuːtkeɪs/","gloss":"mala"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"arrive","pos":"verb","ipa":"/əˈraɪv/","gloss":"chegar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-02', 'lesson-travel-a2-15', 2, 'sentence', 'Where is the lost baggage office?', 'Onde fica o balcão de bagagem extraviada?', '/wɛr ɪz ðə lɔːst ˈbæɡɪdʒ ˈɔːfɪs/', '"Lost baggage" ou "baggage services" = setor de bagagem perdida.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":8,"role":"predicate_verb","surface":"is"},{"start":9,"end":33,"role":"subject","surface":"the lost baggage office?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"},{"surface":"baggage","pos":"noun","ipa":"/ˈbæɡɪdʒ/","gloss":"bagagem"},{"surface":"office","pos":"noun","ipa":"/ˈɔːfɪs/","gloss":"escritório, balcão"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-03', 'lesson-travel-a2-15', 3, 'sentence', 'It''s a black suitcase with a red tag.', 'É uma mala preta com uma etiqueta vermelha.', '/ɪts ə blæk ˈsuːtkeɪs wɪð ə rɛd tæɡ/', 'Descreva cor, tamanho e marca. "Tag" = etiqueta.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"It''s"},{"start":5,"end":21,"role":"predicate_adj","surface":"a black suitcase"},{"start":22,"end":37,"role":"adverbial","surface":"with a red tag."}]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"black","pos":"adjective","ipa":"/blæk/","gloss":"preto"},{"surface":"suitcase","pos":"noun","ipa":"/ˈsuːtkeɪs/","gloss":"mala"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"red","pos":"adjective","ipa":"/rɛd/","gloss":"vermelho"},{"surface":"tag","pos":"noun","ipa":"/tæɡ/","gloss":"etiqueta"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-04', 'lesson-travel-a2-15', 4, 'sentence', 'Here is my baggage claim tag.', 'Aqui está o comprovante da minha bagagem.', '/hɪr ɪz maɪ ˈbæɡɪdʒ kleɪm tæɡ/', 'O "baggage claim tag" é o adesivo que você recebeu no check-in.', '[{"start":0,"end":4,"role":"adverbial","surface":"Here"},{"start":5,"end":7,"role":"predicate_verb","surface":"is"},{"start":8,"end":29,"role":"subject","surface":"my baggage claim tag."}]'::jsonb, '[{"surface":"Here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"baggage","pos":"noun","ipa":"/ˈbæɡɪdʒ/","gloss":"bagagem"},{"surface":"claim","pos":"noun","ipa":"/kleɪm/","gloss":"retirada; reclamação"},{"surface":"tag","pos":"noun","ipa":"/tæɡ/","gloss":"etiqueta"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-05', 'lesson-travel-a2-15', 5, 'sentence', 'Can you deliver it to my hotel?', 'Podem entregar no meu hotel?', '/kæn juː dɪˈlɪvər ɪt tuː maɪ hoʊˈtɛl/', '"Deliver" = entregar. Pergunte sempre: a companhia costuma levar sem custo.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":15,"role":"predicate_verb","surface":"deliver"},{"start":16,"end":18,"role":"direct_object","surface":"it"},{"start":19,"end":31,"role":"adverbial","surface":"to my hotel?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"deliver","pos":"verb","ipa":"/dɪˈlɪvər/","gloss":"entregar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"hotel","pos":"noun","ipa":"/hoʊˈtɛl/","gloss":"hotel"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-06', 'lesson-travel-a2-15', 6, 'sentence', 'My flight was canceled.', 'Meu voo foi cancelado.', '/maɪ flaɪt wɑːz ˈkænsəld/', 'Voz passiva no passado: "was" + particípio. Britânico: "cancelled".', '[{"start":0,"end":9,"role":"subject","surface":"My flight"},{"start":10,"end":23,"role":"predicate_verb","surface":"was canceled."}]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"flight","pos":"noun","ipa":"/flaɪt/","gloss":"voo"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"canceled","pos":"verb","ipa":"/ˈkænsəld/","gloss":"cancelado"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-07', 'lesson-travel-a2-15', 7, 'sentence', 'Can you rebook me on the next flight?', 'Pode me remarcar no próximo voo?', '/kæn juː ˌriːˈbʊk miː ɑːn ðə nɛkst flaɪt/', '"Rebook" = remarcar. "The next flight" = o próximo voo.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":14,"role":"predicate_verb","surface":"rebook"},{"start":15,"end":17,"role":"direct_object","surface":"me"},{"start":18,"end":37,"role":"adverbial","surface":"on the next flight?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"rebook","pos":"verb","ipa":"/ˌriːˈbʊk/","gloss":"remarcar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"flight","pos":"noun","ipa":"/flaɪt/","gloss":"voo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-08', 'lesson-travel-a2-15', 8, 'sentence', 'Will the airline pay for the hotel?', 'A companhia aérea paga o hotel?', '/wɪl ðə ˈɛrlaɪn peɪ fɔːr ðə hoʊˈtɛl/', '"Airline" = companhia aérea. Pergunte por "vouchers" de hotel e comida.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Will"},{"start":5,"end":16,"role":"subject","surface":"the airline"},{"start":17,"end":20,"role":"predicate_verb","surface":"pay"},{"start":21,"end":35,"role":"adverbial","surface":"for the hotel?"}]'::jsonb, '[{"surface":"Will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"airline","pos":"noun","ipa":"/ˈɛrlaɪn/","gloss":"companhia aérea"},{"surface":"pay","pos":"verb","ipa":"/peɪ/","gloss":"pagar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"hotel","pos":"noun","ipa":"/hoʊˈtɛl/","gloss":"hotel"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-09', 'lesson-travel-a2-15', 9, 'sentence', 'How long is the delay?', 'Qual é o tamanho do atraso?', '/haʊ lɔːŋ ɪz ðə dɪˈleɪ/', '"Delay" = atraso (substantivo). "Delayed" = atrasado.', '[{"start":0,"end":8,"role":"adverbial","surface":"How long"},{"start":9,"end":11,"role":"predicate_verb","surface":"is"},{"start":12,"end":22,"role":"subject","surface":"the delay?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"delay","pos":"noun","ipa":"/dɪˈleɪ/","gloss":"atraso"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-15-10', 'lesson-travel-a2-15', 10, 'sentence', 'Can I get a meal voucher?', 'Posso receber um vale-refeição?', '/kæn aɪ ɡɛt ə miːl ˈvaʊtʃər/', '"Voucher" = vale. Muitas companhias dão em atrasos longos.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"get"},{"start":10,"end":25,"role":"direct_object","surface":"a meal voucher?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"meal","pos":"noun","ipa":"/miːl/","gloss":"refeição"},{"surface":"voucher","pos":"noun","ipa":"/ˈvaʊtʃər/","gloss":"vale"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
