-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-idioms-b2', 'idioms-fluency-b2', 'Expressões Idiomáticas e Fluência', 'Idioms que nativos usam de verdade e os recursos que deixam sua fala natural: marcadores, opiniões suaves e histórias.', 'Expressões idiomáticas de trabalho, sentimentos, dinheiro e tempo, e as ferramentas de fluência que separam o B1 do B2: marcadores de conversa ("actually", "I mean"), como suavizar opiniões e como contar uma história. Cada nota traz o registro e o sentido literal × o real.', 'B2', 'social', 11, 'fluencia', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-07', 'course-idioms-b2', 7, 'Idioms de relacionamentos', 'Falar de amizade, família e casal do jeito nativo.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-07-01', 'lesson-idioms-b2-07', 1, 'sentence', 'We hit it off right away.', 'A gente se deu bem logo de cara.', '/wiː hɪt ɪt ɔːf raɪt əˈweɪ/', 'Informal. "Hit it off" = ter afinidade imediata com alguém. Não tem sentido de bater.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"hit","pos":"verb","ipa":"/hɪt/","gloss":"bater, pegar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"logo, imediatamente (right away)"},{"surface":"away","pos":"adverb","ipa":"/əˈweɪ/","gloss":"embora; (right away) já"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-02', 'lesson-idioms-b2-07', 2, 'sentence', 'They''re always at each other''s throats.', 'Eles vivem brigando.', '/ðɛr ˈɔːlweɪz æt iːtʃ ˈʌðərz θroʊts/', 'Informal. Literal: "na garganta um do outro". Real: brigam o tempo todo.', '[]'::jsonb, '[{"surface":"They''re","pos":"pronoun","ipa":"/ðɛr/","gloss":"eles são, eles estão"},{"surface":"always","pos":"adverb","ipa":"/ˈɔːlweɪz/","gloss":"sempre"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"each","pos":"determiner","ipa":"/iːtʃ/","gloss":"cada"},{"surface":"other''s","pos":"pronoun","ipa":"/ˈʌðərz/","gloss":"do outro"},{"surface":"throats","pos":"noun","ipa":"/θroʊts/","gloss":"gargantas"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-03', 'lesson-idioms-b2-07', 3, 'sentence', 'She''s been a rock for me.', 'Ela tem sido meu porto seguro.', '/ʃiːz bɪn ə rɑːk fɔːr miː/', 'Neutro. Literal: "uma rocha". Real: pessoa firme em quem dá para confiar.', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"rock","pos":"noun","ipa":"/rɑːk/","gloss":"rocha; apoio firme"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-04', 'lesson-idioms-b2-07', 4, 'sentence', 'We''ve grown apart over the years.', 'Nós nos afastamos ao longo dos anos.', '/wiːv ɡroʊn əˈpɑːrt ˈoʊvər ðə jɪrz/', 'Neutro. "Grow apart" = ir se distanciando aos poucos, sem briga.', '[]'::jsonb, '[{"surface":"We''ve","pos":"pronoun","ipa":"/wiːv/","gloss":"nós temos (we have)"},{"surface":"grown","pos":"verb","ipa":"/ɡroʊn/","gloss":"crescido"},{"surface":"apart","pos":"adverb","ipa":"/əˈpɑːrt/","gloss":"separado, à parte"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"ao longo de; por cima de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-05', 'lesson-idioms-b2-07', 5, 'sentence', 'He''s a fair-weather friend.', 'Ele só é amigo nas horas boas.', '/hiːz ə ˈfɛrwɛðər frɛnd/', 'Neutro, crítico. Literal: "amigo de tempo bom". Some quando o clima fica difícil.', '[]'::jsonb, '[{"surface":"He''s","pos":"pronoun","ipa":"/hiːz/","gloss":"ele é, ele está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"fair-weather","pos":"adjective","ipa":"/ˈfɛrwɛðər/","gloss":"só das horas boas"},{"surface":"friend","pos":"noun","ipa":"/frɛnd/","gloss":"amigo, amiga"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-06', 'lesson-idioms-b2-07', 6, 'sentence', 'I need to patch things up with my brother.', 'Preciso fazer as pazes com meu irmão.', '/aɪ niːd tuː pætʃ θɪŋz ʌp wɪð maɪ ˈbrʌðər/', 'Informal. Literal: "remendar as coisas". Real: consertar a relação depois de uma briga.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"patch","pos":"verb","ipa":"/pætʃ/","gloss":"remendar, consertar"},{"surface":"things","pos":"noun","ipa":"/θɪŋz/","gloss":"coisas"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"brother","pos":"noun","ipa":"/ˈbrʌðər/","gloss":"irmão"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-07', 'lesson-idioms-b2-07', 7, 'sentence', 'They tied the knot last June.', 'Eles se casaram em junho do ano passado.', '/ðeɪ taɪd ðə nɑːt læst dʒuːn/', 'Informal. Literal: "deram o nó". Real: casaram. Em texto formal use "got married".', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"tied","pos":"verb","ipa":"/taɪd/","gloss":"amarrou, deu (o nó)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"knot","pos":"noun","ipa":"/nɑːt/","gloss":"nó"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último; passado (last June)"},{"surface":"June","pos":"proper noun","ipa":"/dʒuːn/","gloss":"junho"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-08', 'lesson-idioms-b2-07', 8, 'sentence', 'She gave me the cold shoulder all week.', 'Ela me tratou com frieza a semana toda.', '/ʃiː ɡeɪv miː ðə koʊld ˈʃoʊldər ɔːl wiːk/', 'Neutro. "Give someone the cold shoulder" = ignorar de propósito, ser fria.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"gave","pos":"verb","ipa":"/ɡeɪv/","gloss":"deu"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"cold","pos":"adjective","ipa":"/koʊld/","gloss":"frio"},{"surface":"shoulder","pos":"noun","ipa":"/ˈʃoʊldər/","gloss":"ombro"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-09', 'lesson-idioms-b2-07', 9, 'sentence', 'We see eye to eye on most things.', 'A gente concorda na maioria das coisas.', '/wiː siː aɪ tuː aɪ ɑːn moʊst θɪŋz/', 'Neutro. Literal: "ver olho no olho". Real: pensar parecido.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"eye","pos":"noun","ipa":"/aɪ/","gloss":"olho"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"eye","pos":"noun","ipa":"/aɪ/","gloss":"olho"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"most","pos":"determiner","ipa":"/moʊst/","gloss":"o máximo, a maioria"},{"surface":"things","pos":"noun","ipa":"/θɪŋz/","gloss":"coisas"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-07-10', 'lesson-idioms-b2-07', 10, 'sentence', 'Blood is thicker than water.', 'Os laços de família falam mais alto.', '/blʌd ɪz ˈθɪkər ðæn ˈwɔːtər/', 'Neutro. Provérbio: o vínculo de família pesa mais que outros vínculos.', '[]'::jsonb, '[{"surface":"Blood","pos":"noun","ipa":"/blʌd/","gloss":"sangue"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"thicker","pos":"adjective","ipa":"/ˈθɪkər/","gloss":"mais grosso, mais forte"},{"surface":"than","pos":"conjunction","ipa":"/ðæn/","gloss":"do que"},{"surface":"water","pos":"noun","ipa":"/ˈwɔːtər/","gloss":"água"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-08', 'course-idioms-b2', 8, 'Idioms de problemas e soluções', 'Expressões para contar o que deu errado e como resolver.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-08-01', 'lesson-idioms-b2-08', 1, 'sentence', 'We hit a snag with the payment.', 'Esbarramos num problema com o pagamento.', '/wiː hɪt ə snæɡ wɪð ðə ˈpeɪmənt/', 'Neutro, comum no trabalho. "Snag" = empecilho inesperado. "Hit a snag" = esbarrar num problema.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"hit","pos":"verb","ipa":"/hɪt/","gloss":"bater, pegar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"snag","pos":"noun","ipa":"/snæɡ/","gloss":"empecilho, obstáculo"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"payment","pos":"noun","ipa":"/ˈpeɪmənt/","gloss":"pagamento"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-02', 'lesson-idioms-b2-08', 2, 'sentence', 'Let''s not beat around the bush.', 'Vamos direto ao ponto.', '/lɛts nɑːt biːt əˈraʊnd ðə bʊʃ/', 'Informal. Literal: "bater ao redor do arbusto". Real: rodear sem dizer o que importa.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"beat","pos":"verb","ipa":"/biːt/","gloss":"bater; rodear (beat around the bush)"},{"surface":"around","pos":"adverb","ipa":"/əˈraʊnd/","gloss":"ao redor, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bush","pos":"noun","ipa":"/bʊʃ/","gloss":"arbusto, moita"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-03', 'lesson-idioms-b2-08', 3, 'sentence', 'It''s back to square one.', 'Voltamos à estaca zero.', '/ɪts bæk tuː skwɛr wʌn/', 'Neutro. "Square one" = a casa de partida. Tudo o que foi feito se perdeu.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"square","pos":"noun","ipa":"/skwɛr/","gloss":"quadrado; casa (square one = estaca zero)"},{"surface":"one","pos":"numeral","ipa":"/wʌn/","gloss":"um, uma"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-04', 'lesson-idioms-b2-08', 4, 'sentence', 'That''s a blessing in disguise.', 'No fim, isso foi até uma coisa boa.', '/ðæts ə ˈblɛsɪŋ ɪn dɪsˈɡaɪz/', 'Neutro. Literal: "bênção disfarçada". Real: algo ruim que acaba trazendo um benefício.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"blessing","pos":"noun","ipa":"/ˈblɛsɪŋ/","gloss":"bênção"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"disguise","pos":"noun","ipa":"/dɪsˈɡaɪz/","gloss":"disfarce"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-05', 'lesson-idioms-b2-08', 5, 'sentence', 'We''re in the same boat.', 'Estamos no mesmo barco.', '/wɪr ɪn ðə seɪm boʊt/', 'Neutro. Igual ao português: a mesma situação difícil.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"same","pos":"adjective","ipa":"/seɪm/","gloss":"mesmo"},{"surface":"boat","pos":"noun","ipa":"/boʊt/","gloss":"barco"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-06', 'lesson-idioms-b2-08', 6, 'sentence', 'It''s just the tip of the iceberg.', 'Isso é só a ponta do iceberg.', '/ɪts dʒʌst ðə tɪp ʌv ðə ˈaɪsbɜːrɡ/', 'Neutro. Igual ao português: o problema é bem maior do que aparece.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"tip","pos":"noun","ipa":"/tɪp/","gloss":"ponta, topo"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"iceberg","pos":"noun","ipa":"/ˈaɪsbɜːrɡ/","gloss":"iceberg"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-07', 'lesson-idioms-b2-08', 7, 'sentence', 'I''ll sleep on it.', 'Vou pensar com calma e te respondo amanhã.', '/aɪl sliːp ɑːn ɪt/', 'Informal. Literal: "dormir sobre isso". Real: adiar a decisão para o dia seguinte.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"sleep","pos":"verb","ipa":"/sliːp/","gloss":"dormir"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-08', 'lesson-idioms-b2-08', 8, 'sentence', 'She nipped the problem in the bud.', 'Ela cortou o problema pela raiz.', '/ʃiː nɪpt ðə ˈprɑːbləm ɪn ðə bʌd/', 'Informal. "Bud" = broto. Real: resolver antes de crescer.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"nipped","pos":"verb","ipa":"/nɪpt/","gloss":"cortou, beliscou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"problem","pos":"noun","ipa":"/ˈprɑːbləm/","gloss":"problema"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bud","pos":"noun","ipa":"/bʌd/","gloss":"broto"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-09', 'lesson-idioms-b2-08', 9, 'sentence', 'Let''s kill two birds with one stone.', 'Vamos matar dois coelhos com uma cajadada só.', '/lɛts kɪl tuː bɜːrdz wɪð wʌn stoʊn/', 'Informal. Em inglês são "dois pássaros", em português "dois coelhos". Resolver duas coisas de uma vez.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"kill","pos":"verb","ipa":"/kɪl/","gloss":"matar"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"birds","pos":"noun","ipa":"/bɜːrdz/","gloss":"pássaros"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"one","pos":"numeral","ipa":"/wʌn/","gloss":"um, uma"},{"surface":"stone","pos":"noun","ipa":"/stoʊn/","gloss":"pedra"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-08-10', 'lesson-idioms-b2-08', 10, 'sentence', 'Don''t jump the gun.', 'Não se precipite.', '/doʊnt dʒʌmp ðə ɡʌn/', 'Informal. Literal: "pular o tiro" (largar antes do sinal). Real: agir antes da hora.', '[]'::jsonb, '[{"surface":"Don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"jump","pos":"verb","ipa":"/dʒʌmp/","gloss":"pular"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"gun","pos":"noun","ipa":"/ɡʌn/","gloss":"arma; tiro de largada"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-09', 'course-idioms-b2', 9, 'Idioms de opinião e discordância', 'Concordar, discordar e duvidar com expressões naturais.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-09-01', 'lesson-idioms-b2-09', 1, 'sentence', 'I couldn''t agree more.', 'Concordo plenamente.', '/aɪ ˈkʊdənt əˈɡriː mɔːr/', 'Neutro. Literal: "não poderia concordar mais". Real: concordo totalmente.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"couldn''t","pos":"verb","ipa":"/ˈkʊdənt/","gloss":"não podia (could not)"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-02', 'lesson-idioms-b2-09', 2, 'sentence', 'That''s easier said than done.', 'É mais fácil falar do que fazer.', '/ðæts ˈiːziər sɛd ðæn dʌn/', 'Neutro. Igual ao provérbio em português.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"easier","pos":"adjective","ipa":"/ˈiːziər/","gloss":"mais fácil"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"},{"surface":"than","pos":"conjunction","ipa":"/ðæn/","gloss":"do que"},{"surface":"done","pos":"adjective","ipa":"/dʌn/","gloss":"pronto, feito"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-03', 'lesson-idioms-b2-09', 3, 'sentence', 'I beg to differ.', 'Com todo o respeito, discordo.', '/aɪ bɛɡ tuː ˈdɪfər/', 'Formal. Literal: "peço para diferir". Educado, mas firme. Soa antiquado em conversa casual.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"beg","pos":"verb","ipa":"/bɛɡ/","gloss":"pedir, implorar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"differ","pos":"verb","ipa":"/ˈdɪfər/","gloss":"divergir, discordar"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-04', 'lesson-idioms-b2-09', 4, 'sentence', 'You''re missing the point.', 'Você não está entendendo o ponto principal.', '/jʊr ˈmɪsɪŋ ðə pɔɪnt/', 'Neutro. "Miss the point" = não captar o que realmente importa. Pode soar ríspido.', '[]'::jsonb, '[{"surface":"You''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"missing","pos":"verb","ipa":"/ˈmɪsɪŋ/","gloss":"perdendo, deixando de captar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-05', 'lesson-idioms-b2-09', 5, 'sentence', 'Let''s agree to disagree.', 'Vamos concordar em discordar.', '/lɛts əˈɡriː tuː ˌdɪsəˈɡriː/', 'Neutro. Real: encerrar a discussão aceitando que cada um pensa diferente.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"disagree","pos":"verb","ipa":"/ˌdɪsəˈɡriː/","gloss":"discordar"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-06', 'lesson-idioms-b2-09', 6, 'sentence', 'That''s a matter of opinion.', 'Isso é questão de opinião.', '/ðæts ə ˈmætər ʌv əˈpɪnjən/', 'Neutro. Quando algo não é fato, é ponto de vista.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"matter","pos":"noun","ipa":"/ˈmætər/","gloss":"questão, assunto"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"opinion","pos":"noun","ipa":"/əˈpɪnjən/","gloss":"opinião"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-07', 'lesson-idioms-b2-09', 7, 'sentence', 'He''s barking up the wrong tree.', 'Ele está no caminho errado.', '/hiːz ˈbɑːrkɪŋ ʌp ðə rɔːŋ triː/', 'Informal. Literal: "latindo para a árvore errada". Real: procurar ou acusar a pessoa ou o lugar errado.', '[]'::jsonb, '[{"surface":"He''s","pos":"pronoun","ipa":"/hiːz/","gloss":"ele é, ele está"},{"surface":"barking","pos":"verb","ipa":"/ˈbɑːrkɪŋ/","gloss":"latindo"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"wrong","pos":"adjective","ipa":"/rɔːŋ/","gloss":"errado"},{"surface":"tree","pos":"noun","ipa":"/triː/","gloss":"árvore"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-08', 'lesson-idioms-b2-09', 8, 'sentence', 'I''m on the fence about it.', 'Estou em dúvida sobre isso.', '/aɪm ɑːn ðə fɛns əˈbaʊt ɪt/', 'Informal. Literal: "em cima da cerca". Real: indeciso entre duas opções, como "ficar em cima do muro".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"fence","pos":"noun","ipa":"/fɛns/","gloss":"cerca, muro"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-09', 'lesson-idioms-b2-09', 9, 'sentence', 'In my book, honesty comes first.', 'Para mim, a honestidade vem em primeiro lugar.', '/ɪn maɪ bʊk ˈɑːnəsti kʌmz fɜːrst/', 'Informal. Literal: "no meu livro". Real: na minha visão, para mim.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"book","pos":"noun","ipa":"/bʊk/","gloss":"livro (in my book = na minha visão)"},{"surface":"honesty","pos":"noun","ipa":"/ˈɑːnəsti/","gloss":"honestidade"},{"surface":"comes","pos":"verb","ipa":"/kʌmz/","gloss":"vem (he/she/it)"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-09-10', 'lesson-idioms-b2-09', 10, 'sentence', 'I take everything he says with a grain of salt.', 'Eu levo tudo o que ele diz com um pé atrás.', '/aɪ teɪk ˈɛvriθɪŋ hiː sɛz wɪð ə ɡreɪn ʌv sɔːlt/', 'Neutro. Literal: "com um grão de sal". Real: com desconfiança, sem aceitar tudo como verdade.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"everything","pos":"pronoun","ipa":"/ˈɛvriθɪŋ/","gloss":"tudo"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"says","pos":"verb","ipa":"/sɛz/","gloss":"diz"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"grain","pos":"noun","ipa":"/ɡreɪn/","gloss":"grão"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"salt","pos":"noun","ipa":"/sɔːlt/","gloss":"sal"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-10', 'course-idioms-b2', 10, 'Idioms de esforço e ritmo', 'Falar de trabalho puxado, cansaço, persistência e energia.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-10-01', 'lesson-idioms-b2-10', 1, 'sentence', 'I''m swamped at work.', 'Estou atolado de trabalho.', '/aɪm swɑːmpt æt wɜːrk/', 'Informal. "Swamped" = coberto de pântano. Real: com trabalho demais para dar conta.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"swamped","pos":"adjective","ipa":"/swɑːmpt/","gloss":"atolado"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-02', 'lesson-idioms-b2-10', 2, 'sentence', 'She''s burning the candle at both ends.', 'Ela está se esgotando de tanto trabalhar.', '/ʃiːz ˈbɜːrnɪŋ ðə ˈkændəl æt boʊθ ɛndz/', 'Informal. Literal: "queimando a vela pelas duas pontas". Real: trabalhar e dormir pouco, sem descanso.', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"burning","pos":"verb","ipa":"/ˈbɜːrnɪŋ/","gloss":"queimando"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"candle","pos":"noun","ipa":"/ˈkændəl/","gloss":"vela"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"both","pos":"determiner","ipa":"/boʊθ/","gloss":"ambos"},{"surface":"ends","pos":"noun","ipa":"/ɛndz/","gloss":"pontas, extremidades"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-03', 'lesson-idioms-b2-10', 3, 'sentence', 'Let''s take it one step at a time.', 'Vamos um passo de cada vez.', '/lɛts teɪk ɪt wʌn stɛp æt ə taɪm/', 'Neutro. Igual ao português: sem pressa, uma etapa por vez.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"one","pos":"numeral","ipa":"/wʌn/","gloss":"um, uma"},{"surface":"step","pos":"noun","ipa":"/stɛp/","gloss":"passo"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-04', 'lesson-idioms-b2-10', 4, 'sentence', 'I''m running on empty.', 'Estou sem energia nenhuma.', '/aɪm ˈrʌnɪŋ ɑːn ˈɛmpti/', 'Informal. Literal: "rodando no vazio" (como um carro sem combustível). Real: exausto.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"running","pos":"verb","ipa":"/ˈrʌnɪŋ/","gloss":"rodando, funcionando"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"empty","pos":"adjective","ipa":"/ˈɛmpti/","gloss":"vazio"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-05', 'lesson-idioms-b2-10', 5, 'sentence', 'He gave it his all.', 'Ele deu o máximo de si.', '/hiː ɡeɪv ɪt hɪz ɔːl/', 'Neutro. "Give it your all" = esforçar-se ao máximo, mesmo que não dê certo.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"gave","pos":"verb","ipa":"/ɡeɪv/","gloss":"deu"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-06', 'lesson-idioms-b2-10', 6, 'sentence', 'Don''t give up. Hang in there.', 'Não desista. Aguenta firme.', '/doʊnt ɡɪv ʌp hæŋ ɪn ðɛr/', 'Informal. Literal: "fique pendurado aí". Real: persistir numa fase difícil.', '[]'::jsonb, '[{"surface":"Don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"Hang","pos":"verb","ipa":"/hæŋ/","gloss":"pendurar; aguentar (hang in there)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-07', 'lesson-idioms-b2-10', 7, 'sentence', 'We''re going the extra mile for this client.', 'Estamos fazendo além do esperado por esse cliente.', '/wɪr ˈɡoʊɪŋ ðə ˈɛkstrə maɪl fɔːr ðɪs ˈklaɪənt/', 'Neutro. Literal: "andar a milha extra". Real: fazer mais do que o necessário.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"extra","pos":"adjective","ipa":"/ˈɛkstrə/","gloss":"a mais, extra"},{"surface":"mile","pos":"noun","ipa":"/maɪl/","gloss":"milha"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"client","pos":"noun","ipa":"/ˈklaɪənt/","gloss":"cliente"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-08', 'lesson-idioms-b2-10', 8, 'sentence', 'That was a walk in the park.', 'Isso foi moleza.', '/ðæt wɑːz ə wɔːk ɪn ðə pɑːrk/', 'Informal. Literal: "um passeio no parque". Real: muito fácil.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"park","pos":"noun","ipa":"/pɑːrk/","gloss":"parque"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-09', 'lesson-idioms-b2-10', 9, 'sentence', 'Let''s pick up the pace.', 'Vamos acelerar o ritmo.', '/lɛts pɪk ʌp ðə peɪs/', 'Neutro. "Pick up the pace" = andar ou trabalhar mais rápido.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"pick","pos":"verb","ipa":"/pɪk/","gloss":"pegar (pick up)"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"pace","pos":"noun","ipa":"/peɪs/","gloss":"ritmo, passo"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-10-10', 'lesson-idioms-b2-10', 10, 'sentence', 'I need to recharge my batteries.', 'Preciso recarregar as baterias.', '/aɪ niːd tuː riːˈtʃɑːrdʒ maɪ ˈbætəriz/', 'Neutro. Igual ao português: descansar para recuperar a energia.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"recharge","pos":"verb","ipa":"/riːˈtʃɑːrdʒ/","gloss":"recarregar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"batteries","pos":"noun","ipa":"/ˈbætəriz/","gloss":"baterias, pilhas"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
