-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-stories-b1', 'short-stories-b1', 'Histórias em Trechos', 'Dez contos curtos, trecho por trecho: você ouve, escreve e acompanha a história até o fim.', 'Cada capítulo é um conto original dividido em oito trechos. Você pratica compreensão de uma narrativa contínua, tempos do passado, conectores e diálogo. A nota de cada trecho explica a estrutura ou a expressão usada.', 'B1', 'stories', 17, 'fluencia', 2, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-01', 'course-stories-b1', 1, 'A chave errada', 'Um recomeço numa cidade nova.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-01-01', 'lesson-stories-b1-01', 1, 'story', 'Lucas moved to a new city in the middle of winter.', 'Lucas se mudou para uma cidade nova no meio do inverno.', '/ˈluːkəs muːvd tuː ə nuː ˈsɪti ɪn ðə ˈmɪdəl ʌv ˈwɪntər/', '"Move to" = mudar-se para. "In the middle of" = no meio de.', '[]'::jsonb, '[{"surface":"Lucas","pos":"proper noun","ipa":"/ˈluːkəs/","gloss":"Lucas"},{"surface":"moved","pos":"verb","ipa":"/muːvd/","gloss":"mudou-se, moveu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"city","pos":"noun","ipa":"/ˈsɪti/","gloss":"cidade"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"middle","pos":"adjective","ipa":"/ˈmɪdəl/","gloss":"do meio"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"winter","pos":"noun","ipa":"/ˈwɪntər/","gloss":"inverno"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-01-02', 'lesson-stories-b1-01', 2, 'story', 'On his first night, he came home late and very tired.', 'Na primeira noite, ele chegou em casa tarde e muito cansado.', '/ɑːn hɪz fɜːrst naɪt hiː keɪm hoʊm leɪt ænd ˈvɛri ˈtaɪərd/', '"Come home", sem "to": "came home".', '[]'::jsonb, '[{"surface":"On","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"came","pos":"verb","ipa":"/keɪm/","gloss":"veio"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"very","pos":"adverb","ipa":"/ˈvɛri/","gloss":"muito"},{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-01-03', 'lesson-stories-b1-01', 3, 'story', 'He tried his key, but the door wouldn''t open.', 'Ele tentou a chave, mas a porta não abria.', '/hiː traɪd hɪz kiː bʌt ðə dɔːr ˈwʊdənt ˈoʊpən/', '"Wouldn''t" = recusa de um objeto: a porta "não queria" abrir.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"tried","pos":"verb","ipa":"/traɪd/","gloss":"tentou, experimentou"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"key","pos":"noun","ipa":"/kiː/","gloss":"chave"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"door","pos":"noun","ipa":"/dɔːr/","gloss":"porta"},{"surface":"wouldn''t","pos":"verb","ipa":"/ˈwʊdənt/","gloss":"não faria (would not)"},{"surface":"open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-01-04', 'lesson-stories-b1-01', 4, 'story', 'He tried again and again. Nothing happened.', 'Tentou de novo e de novo. Nada aconteceu.', '/hiː traɪd əˈɡɛn ænd əˈɡɛn ˈnʌθɪŋ ˈhæpənd/', '"Again and again" = repetidas vezes.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"tried","pos":"verb","ipa":"/traɪd/","gloss":"tentou, experimentou"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"},{"surface":"Nothing","pos":"pronoun","ipa":"/ˈnʌθɪŋ/","gloss":"nada"},{"surface":"happened","pos":"verb","ipa":"/ˈhæpənd/","gloss":"aconteceu"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-01-05', 'lesson-stories-b1-01', 5, 'story', 'Suddenly, a light came on inside the apartment.', 'De repente, uma luz acendeu dentro do apartamento.', '/ˈsʌdənli ə laɪt keɪm ɑːn ˌɪnˈsaɪd ðə əˈpɑːrtmənt/', '"Come on" (luz) = acender.', '[]'::jsonb, '[{"surface":"Suddenly","pos":"adverb","ipa":"/ˈsʌdənli/","gloss":"de repente"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"light","pos":"adjective","ipa":"/laɪt/","gloss":"claro"},{"surface":"came","pos":"verb","ipa":"/keɪm/","gloss":"veio"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"inside","pos":"adverb","ipa":"/ˌɪnˈsaɪd/","gloss":"dentro"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"apartment","pos":"noun","ipa":"/əˈpɑːrtmənt/","gloss":"apartamento"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-01-06', 'lesson-stories-b1-01', 6, 'story', 'An old woman opened the door and looked at him.', 'Uma senhora abriu a porta e olhou para ele.', '/ən oʊld ˈwʊmən ˈoʊpənd ðə dɔːr ænd lʊkt æt hɪm/', '"Look at" = olhar para.', '[]'::jsonb, '[{"surface":"An","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"old","pos":"adjective","ipa":"/oʊld/","gloss":"velho; de idade"},{"surface":"woman","pos":"noun","ipa":"/ˈwʊmən/","gloss":"mulher"},{"surface":"opened","pos":"verb","ipa":"/ˈoʊpənd/","gloss":"abriu"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"door","pos":"noun","ipa":"/dɔːr/","gloss":"porta"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"looked","pos":"verb","ipa":"/lʊkt/","gloss":"olhou, pareceu"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-01-07', 'lesson-stories-b1-01', 7, 'story', 'She smiled and said that he lived upstairs.', 'Ela sorriu e disse que ele morava no andar de cima.', '/ʃiː smaɪld ænd sɛd ðæt hiː lɪvd ˌʌpˈstɛrz/', 'Discurso indireto: "you live" vira "he lived". "Upstairs" = no andar de cima.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"smiled","pos":"verb","ipa":"/smaɪld/","gloss":"sorriu"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"lived","pos":"verb","ipa":"/lɪvd/","gloss":"morou, viveu"},{"surface":"upstairs","pos":"adverb","ipa":"/ˌʌpˈstɛrz/","gloss":"no andar de cima"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-01-08', 'lesson-stories-b1-01', 8, 'story', 'That was how Lucas met his first friend in the city.', 'Foi assim que Lucas conheceu seu primeiro amigo na cidade.', '/ðæt wɑːz haʊ ˈluːkəs mɛt hɪz fɜːrst frɛnd ɪn ðə ˈsɪti/', '"That was how" = foi assim que. "Meet" = conhecer (passado: met).', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"Lucas","pos":"proper noun","ipa":"/ˈluːkəs/","gloss":"Lucas"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"friend","pos":"noun","ipa":"/frɛnd/","gloss":"amigo, amiga"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"city","pos":"noun","ipa":"/ˈsɪti/","gloss":"cidade"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-02', 'course-stories-b1', 2, 'O último ônibus', 'Uma noite de chuva e uma escolha.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-02-01', 'lesson-stories-b1-02', 1, 'story', 'It was raining hard when Maya left the office.', 'Chovia forte quando Maya saiu do escritório.', '/ɪt wɑːz ˈreɪnɪŋ hɑːrd wɛn ˈmaɪə lɛft ðə ˈɔːfɪs/', 'Passado contínuo para o cenário: "it was raining".', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"raining","pos":"verb","ipa":"/ˈreɪnɪŋ/","gloss":"chovendo"},{"surface":"hard","pos":"adjective","ipa":"/hɑːrd/","gloss":"duro, difícil"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"Maya","pos":"proper noun","ipa":"/ˈmaɪə/","gloss":"Maya"},{"surface":"left","pos":"adverb","ipa":"/lɛft/","gloss":"à esquerda"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"office","pos":"noun","ipa":"/ˈɔːfɪs/","gloss":"escritório, balcão"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-02-02', 'lesson-stories-b1-02', 2, 'story', 'She ran to the bus stop, but the last bus was pulling away.', 'Ela correu até o ponto, mas o último ônibus estava saindo.', '/ʃiː ræn tuː ðə bʌs stɑːp bʌt ðə læst bʌs wɑːz ˈpʊlɪŋ əˈweɪ/', '"Pull away" = arrancar, sair (veículo).', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"ran","pos":"verb","ipa":"/ræn/","gloss":"correu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"},{"surface":"stop","pos":"verb","ipa":"/stɑːp/","gloss":"parar"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"pulling","pos":"verb","ipa":"/ˈpʊlɪŋ/","gloss":"puxando, saindo"},{"surface":"away","pos":"adverb","ipa":"/əˈweɪ/","gloss":"embora; (right away) já"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-02-03', 'lesson-stories-b1-02', 3, 'story', 'She waved her arms, but the driver did not see her.', 'Ela acenou com os braços, mas o motorista não a viu.', '/ʃiː weɪvd hɜːr ɑːrmz bʌt ðə ˈdraɪvər dɪd nɑːt siː hɜːr/', '"Wave" = acenar.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"waved","pos":"verb","ipa":"/weɪvd/","gloss":"acenou"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"arms","pos":"noun","ipa":"/ɑːrmz/","gloss":"braços"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"driver","pos":"noun","ipa":"/ˈdraɪvər/","gloss":"motorista"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-02-04', 'lesson-stories-b1-02', 4, 'story', 'Her phone battery was almost dead.', 'A bateria do celular estava quase no fim.', '/hɜːr foʊn ˈbætəri wɑːz ˈɔːlmoʊst dɛd/', '"Almost dead" = quase sem bateria.', '[]'::jsonb, '[{"surface":"Her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"phone","pos":"noun","ipa":"/foʊn/","gloss":"celular, telefone"},{"surface":"battery","pos":"noun","ipa":"/ˈbætəri/","gloss":"bateria"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"almost","pos":"adverb","ipa":"/ˈɔːlmoʊst/","gloss":"quase"},{"surface":"dead","pos":"adjective","ipa":"/dɛd/","gloss":"morto; sem bateria"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-02-05', 'lesson-stories-b1-02', 5, 'story', 'A taxi would cost too much, so she decided to walk.', 'Um táxi custaria caro demais, então ela decidiu andar.', '/ə ˈtæksi wʊd kɔːst tuː mʌtʃ soʊ ʃiː dɪˈsaɪdɪd tuː wɔːk/', '"Would cost" = hipótese. "Decide to" + verbo.', '[]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"taxi","pos":"noun","ipa":"/ˈtæksi/","gloss":"táxi"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"cost","pos":"verb","ipa":"/kɔːst/","gloss":"custar"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"decided","pos":"verb","ipa":"/dɪˈsaɪdɪd/","gloss":"decidiu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-02-06', 'lesson-stories-b1-02', 6, 'story', 'After ten minutes, a car stopped next to her.', 'Depois de dez minutos, um carro parou ao lado dela.', '/ˈæftər tɛn ˈmɪnɪts ə kɑːr stɑːpt nɛkst tuː hɜːr/', '"Next to" = ao lado de.', '[]'::jsonb, '[{"surface":"After","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"minutes","pos":"noun","ipa":"/ˈmɪnɪts/","gloss":"minutos"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"stopped","pos":"verb","ipa":"/stɑːpt/","gloss":"parou"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-02-07', 'lesson-stories-b1-02', 7, 'story', 'It was her manager, driving home the same way.', 'Era a gerente dela, voltando para casa pelo mesmo caminho.', '/ɪt wɑːz hɜːr ˈmænɪdʒər ˈdraɪvɪŋ hoʊm ðə seɪm weɪ/', '"The same way" = pelo mesmo caminho.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"manager","pos":"noun","ipa":"/ˈmænɪdʒər/","gloss":"gerente"},{"surface":"driving","pos":"verb","ipa":"/ˈdraɪvɪŋ/","gloss":"dirigindo"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"same","pos":"adjective","ipa":"/seɪm/","gloss":"mesmo"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-02-08', 'lesson-stories-b1-02', 8, 'story', 'She smiled and told Maya to get in.', 'Ela sorriu e disse para Maya entrar.', '/ʃiː smaɪld ænd toʊld ˈmaɪə tuː ɡɛt ɪn/', '"Tell someone to" + verbo = mandar, pedir. "Get in" = entrar no carro.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"smiled","pos":"verb","ipa":"/smaɪld/","gloss":"sorriu"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"Maya","pos":"proper noun","ipa":"/ˈmaɪə/","gloss":"Maya"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-03', 'course-stories-b1', 3, 'O bolo de aniversário', 'Uma surpresa que quase deu errado.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-03-01', 'lesson-stories-b1-03', 1, 'story', 'Tom wanted to bake a cake for his sister''s birthday.', 'Tom queria fazer um bolo para o aniversário da irmã.', '/tɑːm ˈwɑːntɪd tuː beɪk ə keɪk fɔːr hɪz ˈsɪstərz ˈbɜːrθdeɪ/', '"Bake" = assar. "Sister''s" = da irmã (posse com ''s).', '[]'::jsonb, '[{"surface":"Tom","pos":"proper noun","ipa":"/tɑːm/","gloss":"Tom"},{"surface":"wanted","pos":"verb","ipa":"/ˈwɑːntɪd/","gloss":"quis, queria"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"bake","pos":"verb","ipa":"/beɪk/","gloss":"assar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"cake","pos":"noun","ipa":"/keɪk/","gloss":"bolo"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"sister''s","pos":"noun","ipa":"/ˈsɪstərz/","gloss":"da irmã"},{"surface":"birthday","pos":"noun","ipa":"/ˈbɜːrθdeɪ/","gloss":"aniversário"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-03-02', 'lesson-stories-b1-03', 2, 'story', 'He had never baked anything before.', 'Ele nunca tinha assado nada antes.', '/hiː hæd ˈnɛvər beɪkt ˈɛniθɪŋ bɪˈfɔːr/', 'Past perfect: "had never baked" = antes daquele momento.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"baked","pos":"verb","ipa":"/beɪkt/","gloss":"assou"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-03-03', 'lesson-stories-b1-03', 3, 'story', 'He followed a recipe he found online.', 'Ele seguiu uma receita que achou na internet.', '/hiː ˈfɑːloʊd ə ˈrɛsəpi hiː faʊnd ˌɑːnˈlaɪn/', '"Recipe" = receita. "That" foi omitido: "a recipe (that) he found".', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"followed","pos":"verb","ipa":"/ˈfɑːloʊd/","gloss":"seguiu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"recipe","pos":"noun","ipa":"/ˈrɛsəpi/","gloss":"receita"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"},{"surface":"online","pos":"adverb","ipa":"/ˌɑːnˈlaɪn/","gloss":"na internet"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-03-04', 'lesson-stories-b1-03', 4, 'story', 'But he used salt instead of sugar.', 'Mas usou sal em vez de açúcar.', '/bʌt hiː juːzd sɔːlt ɪnˈstɛd ʌv ˈʃʊɡər/', '"Instead of" = em vez de.', '[]'::jsonb, '[{"surface":"But","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"used","pos":"verb","ipa":"/juːzd/","gloss":"usou, usado"},{"surface":"salt","pos":"noun","ipa":"/sɔːlt/","gloss":"sal"},{"surface":"instead","pos":"adverb","ipa":"/ɪnˈstɛd/","gloss":"em vez disso"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"sugar","pos":"noun","ipa":"/ˈʃʊɡər/","gloss":"açúcar"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-03-05', 'lesson-stories-b1-03', 5, 'story', 'When his sister tasted it, she made a funny face.', 'Quando a irmã provou, fez uma careta engraçada.', '/wɛn hɪz ˈsɪstər ˈteɪstɪd ɪt ʃiː meɪd ə ˈfʌni feɪs/', '"Taste" = provar. "Make a face" = fazer careta.', '[]'::jsonb, '[{"surface":"When","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"sister","pos":"noun","ipa":"/ˈsɪstər/","gloss":"irmã"},{"surface":"tasted","pos":"verb","ipa":"/ˈteɪstɪd/","gloss":"provou"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"funny","pos":"adjective","ipa":"/ˈfʌni/","gloss":"engraçado"},{"surface":"face","pos":"noun","ipa":"/feɪs/","gloss":"rosto"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-03-06', 'lesson-stories-b1-03', 6, 'story', 'Everyone laughed, including Tom.', 'Todo mundo riu, incluindo o Tom.', '/ˈɛvriwʌn læft ɪnˈkluːdɪŋ tɑːm/', '"Including" = incluindo.', '[]'::jsonb, '[{"surface":"Everyone","pos":"pronoun","ipa":"/ˈɛvriwʌn/","gloss":"todo mundo, pessoal"},{"surface":"laughed","pos":"verb","ipa":"/læft/","gloss":"riu"},{"surface":"including","pos":"preposition","ipa":"/ɪnˈkluːdɪŋ/","gloss":"incluindo"},{"surface":"Tom","pos":"proper noun","ipa":"/tɑːm/","gloss":"Tom"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-03-07', 'lesson-stories-b1-03', 7, 'story', 'They ordered a pizza and put a candle on it.', 'Eles pediram uma pizza e colocaram uma vela nela.', '/ðeɪ ˈɔːrdərd ə ˈpiːtsə ænd pʊt ə ˈkændəl ɑːn ɪt/', '"Order" = pedir (comida).', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"ordered","pos":"verb","ipa":"/ˈɔːrdərd/","gloss":"pediu, pedido"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"pizza","pos":"noun","ipa":"/ˈpiːtsə/","gloss":"pizza"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"candle","pos":"noun","ipa":"/ˈkændəl/","gloss":"vela"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-03-08', 'lesson-stories-b1-03', 8, 'story', 'His sister said it was the best birthday ever.', 'A irmã disse que foi o melhor aniversário de todos.', '/hɪz ˈsɪstər sɛd ɪt wɑːz ðə bɛst ˈbɜːrθdeɪ ˈɛvər/', '"Ever" depois do superlativo = de todos os tempos.', '[]'::jsonb, '[{"surface":"His","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"sister","pos":"noun","ipa":"/ˈsɪstər/","gloss":"irmã"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"best","pos":"adjective","ipa":"/bɛst/","gloss":"melhor"},{"surface":"birthday","pos":"noun","ipa":"/ˈbɜːrθdeɪ/","gloss":"aniversário"},{"surface":"ever","pos":"adverb","ipa":"/ˈɛvər/","gloss":"alguma vez, já"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-04', 'course-stories-b1', 4, 'Perdido na estação', 'Um turista, um mapa e um desconhecido.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-04-01', 'lesson-stories-b1-04', 1, 'story', 'Pedro arrived in Tokyo with a paper map and no internet.', 'Pedro chegou a Tóquio com um mapa de papel e sem internet.', '/ˈpeɪdroʊ əˈraɪvd ɪn ˈtoʊkioʊ wɪð ə ˈpeɪpər mæp ænd noʊ ˈɪntərnɛt/', '"Arrive in" + cidade; "arrive at" + lugar específico.', '[]'::jsonb, '[{"surface":"Pedro","pos":"proper noun","ipa":"/ˈpeɪdroʊ/","gloss":"Pedro"},{"surface":"arrived","pos":"verb","ipa":"/əˈraɪvd/","gloss":"chegou"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"Tokyo","pos":"proper noun","ipa":"/ˈtoʊkioʊ/","gloss":"Tóquio"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"paper","pos":"noun","ipa":"/ˈpeɪpər/","gloss":"papel"},{"surface":"map","pos":"noun","ipa":"/mæp/","gloss":"mapa"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"no","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"internet","pos":"noun","ipa":"/ˈɪntərnɛt/","gloss":"internet"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-04-02', 'lesson-stories-b1-04', 2, 'story', 'The station was huge and full of people.', 'A estação era enorme e cheia de gente.', '/ðə ˈsteɪʃən wɑːz hjuːdʒ ænd fʊl ʌv ˈpiːpəl/', '"Full of" = cheio de.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"station","pos":"noun","ipa":"/ˈsteɪʃən/","gloss":"estação"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"huge","pos":"adjective","ipa":"/hjuːdʒ/","gloss":"enorme"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"full","pos":"adjective","ipa":"/fʊl/","gloss":"cheio"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"people","pos":"noun","ipa":"/ˈpiːpəl/","gloss":"pessoas"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-04-03', 'lesson-stories-b1-04', 3, 'story', 'Every sign seemed to point in a different direction.', 'Cada placa parecia apontar para um lado diferente.', '/ˈɛvri saɪn siːmd tuː pɔɪnt ɪn ə ˈdɪfərənt dəˈrɛkʃən/', '"Seem to" + verbo = parecer.', '[]'::jsonb, '[{"surface":"Every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"sign","pos":"verb","ipa":"/saɪn/","gloss":"assinar"},{"surface":"seemed","pos":"verb","ipa":"/siːmd/","gloss":"pareceu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"different","pos":"adjective","ipa":"/ˈdɪfərənt/","gloss":"diferente"},{"surface":"direction","pos":"noun","ipa":"/dəˈrɛkʃən/","gloss":"direção"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-04-04', 'lesson-stories-b1-04', 4, 'story', 'He stood still, trying to understand the map.', 'Ele ficou parado, tentando entender o mapa.', '/hiː stʊd stɪl ˈtraɪɪŋ tuː ˌʌndərˈstænd ðə mæp/', '"Stand still" = ficar parado. "Trying to" = tentando.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"stood","pos":"verb","ipa":"/stʊd/","gloss":"ficou de pé"},{"surface":"still","pos":"adverb","ipa":"/stɪl/","gloss":"ainda"},{"surface":"trying","pos":"verb","ipa":"/ˈtraɪɪŋ/","gloss":"tentando"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"map","pos":"noun","ipa":"/mæp/","gloss":"mapa"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-04-05', 'lesson-stories-b1-04', 5, 'story', 'A young man asked if he needed help.', 'Um rapaz perguntou se ele precisava de ajuda.', '/ə jʌŋ mæn æskt ɪf hiː ˈniːdɪd hɛlp/', 'Discurso indireto: "asked if he needed".', '[]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"young","pos":"adjective","ipa":"/jʌŋ/","gloss":"jovem"},{"surface":"man","pos":"noun","ipa":"/mæn/","gloss":"homem"},{"surface":"asked","pos":"verb","ipa":"/æskt/","gloss":"perguntou, pediu"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"needed","pos":"verb","ipa":"/ˈniːdɪd/","gloss":"precisou"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-04-06', 'lesson-stories-b1-04', 6, 'story', 'They did not share a language, so they used gestures.', 'Eles não falavam a mesma língua, então usaram gestos.', '/ðeɪ dɪd nɑːt ʃɛr ə ˈlæŋɡwɪdʒ soʊ ðeɪ juːzd ˈdʒɛstʃərz/', '"Share a language" = ter uma língua em comum.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"share","pos":"verb","ipa":"/ʃɛr/","gloss":"compartilhar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"language","pos":"noun","ipa":"/ˈlæŋɡwɪdʒ/","gloss":"língua, idioma"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"they","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"used","pos":"verb","ipa":"/juːzd/","gloss":"usou, usado"},{"surface":"gestures","pos":"noun","ipa":"/ˈdʒɛstʃərz/","gloss":"gestos"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-04-07', 'lesson-stories-b1-04', 7, 'story', 'The man walked with him all the way to the right platform.', 'O rapaz caminhou com ele até a plataforma certa.', '/ðə mæn wɔːkt wɪð hɪm ɔːl ðə weɪ tuː ðə raɪt ˈplætfɔːrm/', '"All the way to" = até, o caminho todo.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"man","pos":"noun","ipa":"/mæn/","gloss":"homem"},{"surface":"walked","pos":"verb","ipa":"/wɔːkt/","gloss":"caminhou"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"platform","pos":"noun","ipa":"/ˈplætfɔːrm/","gloss":"plataforma"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-04-08', 'lesson-stories-b1-04', 8, 'story', 'Pedro never learned his name, but he never forgot him.', 'Pedro nunca soube o nome dele, mas nunca o esqueceu.', '/ˈpeɪdroʊ ˈnɛvər lɜːrnd hɪz neɪm bʌt hiː ˈnɛvər fərˈɡɑːt hɪm/', '"Learn someone''s name" = ficar sabendo o nome.', '[]'::jsonb, '[{"surface":"Pedro","pos":"proper noun","ipa":"/ˈpeɪdroʊ/","gloss":"Pedro"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"learned","pos":"verb","ipa":"/lɜːrnd/","gloss":"aprendeu"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"name","pos":"noun","ipa":"/neɪm/","gloss":"nome"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"forgot","pos":"verb","ipa":"/fərˈɡɑːt/","gloss":"esqueceu"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-05', 'course-stories-b1', 5, 'A entrevista', 'Nervos, café e uma resposta honesta.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-05-01', 'lesson-stories-b1-05', 1, 'story', 'Ana woke up early on the day of her interview.', 'Ana acordou cedo no dia da entrevista.', '/ˈænə woʊk ʌp ˈɜːrli ɑːn ðə deɪ ʌv hɜːr ˈɪntərvjuː/', '"Wake up", passado "woke up".', '[]'::jsonb, '[{"surface":"Ana","pos":"proper noun","ipa":"/ˈænə/","gloss":"Ana"},{"surface":"woke","pos":"verb","ipa":"/woʊk/","gloss":"acordou"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"interview","pos":"noun","ipa":"/ˈɪntərvjuː/","gloss":"entrevista"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-05-02', 'lesson-stories-b1-05', 2, 'story', 'She was so nervous that she could not eat breakfast.', 'Estava tão nervosa que não conseguiu tomar café.', '/ʃiː wɑːz soʊ ˈnɜːrvəs ðæt ʃiː kʊd nɑːt iːt ˈbrɛkfəst/', '"So + adjetivo + that" = tão… que.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"nervous","pos":"adjective","ipa":"/ˈnɜːrvəs/","gloss":"nervoso, ansioso"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"eat","pos":"verb","ipa":"/iːt/","gloss":"comer"},{"surface":"breakfast","pos":"noun","ipa":"/ˈbrɛkfəst/","gloss":"café da manhã"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-05-03', 'lesson-stories-b1-05', 3, 'story', 'On the way, she spilled coffee on her shirt.', 'No caminho, derrubou café na camisa.', '/ɑːn ðə weɪ ʃiː spɪld ˈkɔːfi ɑːn hɜːr ʃɜːrt/', '"Spill" = derramar. "On the way" = no caminho.', '[]'::jsonb, '[{"surface":"On","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"spilled","pos":"verb","ipa":"/spɪld/","gloss":"derramou"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"shirt","pos":"noun","ipa":"/ʃɜːrt/","gloss":"camisa"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-05-04', 'lesson-stories-b1-05', 4, 'story', 'There was no time to go back and change.', 'Não havia tempo para voltar e trocar de roupa.', '/ðɛr wɑːz noʊ taɪm tuː ɡoʊ bæk ænd tʃeɪndʒ/', '"Change" sozinho pode significar trocar de roupa.', '[]'::jsonb, '[{"surface":"There","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"no","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-05-05', 'lesson-stories-b1-05', 5, 'story', 'The interviewer noticed the stain and smiled.', 'O entrevistador notou a mancha e sorriu.', '/ðə ˈɪntərvjuːər ˈnoʊtɪst ðə steɪn ænd smaɪld/', '"Notice" = notar. "Stain" = mancha.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"interviewer","pos":"noun","ipa":"/ˈɪntərvjuːər/","gloss":"entrevistador"},{"surface":"noticed","pos":"verb","ipa":"/ˈnoʊtɪst/","gloss":"notou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"stain","pos":"noun","ipa":"/steɪn/","gloss":"mancha"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"smiled","pos":"verb","ipa":"/smaɪld/","gloss":"sorriu"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-05-06', 'lesson-stories-b1-05', 6, 'story', 'Ana decided to tell the truth about her morning.', 'Ana decidiu contar a verdade sobre a manhã.', '/ˈænə dɪˈsaɪdɪd tuː tɛl ðə truːθ əˈbaʊt hɜːr ˈmɔːrnɪŋ/', '"Tell the truth" = dizer a verdade.', '[]'::jsonb, '[{"surface":"Ana","pos":"proper noun","ipa":"/ˈænə/","gloss":"Ana"},{"surface":"decided","pos":"verb","ipa":"/dɪˈsaɪdɪd/","gloss":"decidiu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"truth","pos":"noun","ipa":"/truːθ/","gloss":"verdade"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"morning","pos":"noun","ipa":"/ˈmɔːrnɪŋ/","gloss":"manhã"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-05-07', 'lesson-stories-b1-05', 7, 'story', 'They both laughed, and the rest of the interview felt easy.', 'Os dois riram, e o resto da entrevista pareceu fácil.', '/ðeɪ boʊθ læft ænd ðə rɛst ʌv ðə ˈɪntərvjuː fɛlt ˈiːzi/', '"Feel" + adjetivo = parecer, dar a sensação de.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"both","pos":"determiner","ipa":"/boʊθ/","gloss":"ambos"},{"surface":"laughed","pos":"verb","ipa":"/læft/","gloss":"riu"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"rest","pos":"verb","ipa":"/rɛst/","gloss":"descansar"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"interview","pos":"noun","ipa":"/ˈɪntərvjuː/","gloss":"entrevista"},{"surface":"felt","pos":"verb","ipa":"/fɛlt/","gloss":"sentiu"},{"surface":"easy","pos":"adjective","ipa":"/ˈiːzi/","gloss":"fácil, tranquilo"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-05-08', 'lesson-stories-b1-05', 8, 'story', 'A week later, she got the job.', 'Uma semana depois, ela conseguiu o emprego.', '/ə wiːk ˈleɪtər ʃiː ɡɑːt ðə dʒɑːb/', '"A week later" = uma semana depois. "Get the job" = conseguir a vaga.', '[]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"trabalho"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-06', 'course-stories-b1', 6, 'O cachorro do vizinho', 'Um visitante inesperado.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-06-01', 'lesson-stories-b1-06', 1, 'story', 'Every morning, a small brown dog sat outside my door.', 'Toda manhã, um cachorrinho marrom sentava na frente da minha porta.', '/ˈɛvri ˈmɔːrnɪŋ ə smɔːl braʊn dɔːɡ sæt ˌaʊtˈsaɪd maɪ dɔːr/', 'Passado simples para hábito passado: "sat".', '[]'::jsonb, '[{"surface":"Every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"morning","pos":"noun","ipa":"/ˈmɔːrnɪŋ/","gloss":"manhã"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"small","pos":"adjective","ipa":"/smɔːl/","gloss":"pequeno"},{"surface":"brown","pos":"adjective","ipa":"/braʊn/","gloss":"marrom"},{"surface":"dog","pos":"noun","ipa":"/dɔːɡ/","gloss":"cachorro"},{"surface":"sat","pos":"verb","ipa":"/sæt/","gloss":"sentou"},{"surface":"outside","pos":"adverb","ipa":"/ˌaʊtˈsaɪd/","gloss":"lá fora"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"door","pos":"noun","ipa":"/dɔːr/","gloss":"porta"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-06-02', 'lesson-stories-b1-06', 2, 'story', 'At first, I did not know who he belonged to.', 'No início, eu não sabia de quem ele era.', '/æt fɜːrst aɪ dɪd nɑːt noʊ huː hiː bɪˈlɔːŋd tuː/', '"Belong to" = pertencer a. Preposição no fim da pergunta indireta.', '[]'::jsonb, '[{"surface":"At","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"belonged","pos":"verb","ipa":"/bɪˈlɔːŋd/","gloss":"pertencia"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-06-03', 'lesson-stories-b1-06', 3, 'story', 'I started giving him a little water.', 'Comecei a dar um pouco de água para ele.', '/aɪ ˈstɑːrtɪd ˈɡɪvɪŋ hɪm ə ˈlɪtəl ˈwɔːtər/', '"Start" + -ing = começar a.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"started","pos":"verb","ipa":"/ˈstɑːrtɪd/","gloss":"começado"},{"surface":"giving","pos":"verb","ipa":"/ˈɡɪvɪŋ/","gloss":"dando"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"little","pos":"adjective","ipa":"/ˈlɪtəl/","gloss":"pouco, pequeno"},{"surface":"water","pos":"noun","ipa":"/ˈwɔːtər/","gloss":"água"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-06-04', 'lesson-stories-b1-06', 4, 'story', 'Soon he was waiting for me every day.', 'Logo ele estava me esperando todo dia.', '/suːn hiː wɑːz ˈweɪtɪŋ fɔːr miː ˈɛvri deɪ/', '"Wait for" = esperar por.', '[]'::jsonb, '[{"surface":"Soon","pos":"adverb","ipa":"/suːn/","gloss":"logo"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-06-05', 'lesson-stories-b1-06', 5, 'story', 'One day, he did not come.', 'Um dia, ele não veio.', '/wʌn deɪ hiː dɪd nɑːt kʌm/', 'Frase curta para criar tensão na narrativa.', '[]'::jsonb, '[{"surface":"One","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-06-06', 'lesson-stories-b1-06', 6, 'story', 'I felt worried and knocked on my neighbor''s door.', 'Fiquei preocupado e bati na porta do vizinho.', '/aɪ fɛlt ˈwɜːrid ænd nɑːkt ɑːn maɪ ˈneɪbərz dɔːr/', '"Knock on" = bater (na porta).', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"felt","pos":"verb","ipa":"/fɛlt/","gloss":"sentiu"},{"surface":"worried","pos":"adjective","ipa":"/ˈwɜːrid/","gloss":"preocupado"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"knocked","pos":"verb","ipa":"/nɑːkt/","gloss":"bateu (na porta)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"neighbor''s","pos":"noun","ipa":"/ˈneɪbərz/","gloss":"do vizinho"},{"surface":"door","pos":"noun","ipa":"/dɔːr/","gloss":"porta"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-06-07', 'lesson-stories-b1-06', 7, 'story', 'She told me the dog was sick, but getting better.', 'Ela me contou que o cachorro estava doente, mas melhorando.', '/ʃiː toʊld miː ðə dɔːɡ wɑːz sɪk bʌt ˈɡɛtɪŋ ˈbɛtər/', '"Get better" = melhorar.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"dog","pos":"noun","ipa":"/dɔːɡ/","gloss":"cachorro"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"sick","pos":"adjective","ipa":"/sɪk/","gloss":"doente, enjoado"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"getting","pos":"verb","ipa":"/ˈɡɛtɪŋ/","gloss":"ficando; getting up = levantar-se"},{"surface":"better","pos":"adjective","ipa":"/ˈbɛtər/","gloss":"melhor"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-06-08', 'lesson-stories-b1-06', 8, 'story', 'Now we walk him together every Sunday.', 'Agora passeamos com ele juntos todo domingo.', '/naʊ wiː wɔːk hɪm təˈɡɛðər ˈɛvri ˈsʌndeɪ/', '"Walk a dog" = passear com o cachorro.', '[]'::jsonb, '[{"surface":"Now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"together","pos":"adverb","ipa":"/təˈɡɛðər/","gloss":"juntos"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"Sunday","pos":"proper noun","ipa":"/ˈsʌndeɪ/","gloss":"domingo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-07', 'course-stories-b1', 7, 'A carta antiga', 'Uma descoberta no sótão.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-07-01', 'lesson-stories-b1-07', 1, 'story', 'While cleaning the attic, Sara found an old box.', 'Enquanto limpava o sótão, Sara achou uma caixa velha.', '/waɪl ˈkliːnɪŋ ðə ˈætɪk ˈsɛrə faʊnd ən oʊld bɑːks/', '"While" + -ing = enquanto fazia algo.', '[]'::jsonb, '[{"surface":"While","pos":"noun","ipa":"/waɪl/","gloss":"tempo (a while = um tempo)"},{"surface":"cleaning","pos":"verb","ipa":"/ˈkliːnɪŋ/","gloss":"limpando"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"attic","pos":"noun","ipa":"/ˈætɪk/","gloss":"sótão"},{"surface":"Sara","pos":"proper noun","ipa":"/ˈsɛrə/","gloss":"Sara"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"old","pos":"adjective","ipa":"/oʊld/","gloss":"velho; de idade"},{"surface":"box","pos":"noun","ipa":"/bɑːks/","gloss":"caixa"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-07-02', 'lesson-stories-b1-07', 2, 'story', 'Inside, there was a letter written by her grandfather.', 'Dentro, havia uma carta escrita pelo avô dela.', '/ˌɪnˈsaɪd ðɛr wɑːz ə ˈlɛtər ˈrɪtən baɪ hɜːr ˈɡrænfɑːðər/', '"Written by" = particípio como adjetivo.', '[]'::jsonb, '[{"surface":"Inside","pos":"adverb","ipa":"/ˌɪnˈsaɪd/","gloss":"dentro"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"letter","pos":"noun","ipa":"/ˈlɛtər/","gloss":"carta, letra"},{"surface":"written","pos":"verb","ipa":"/ˈrɪtən/","gloss":"escrito"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"grandfather","pos":"noun","ipa":"/ˈɡrænfɑːðər/","gloss":"avô"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-07-03', 'lesson-stories-b1-07', 3, 'story', 'It was dated fifty years ago.', 'Estava datada de cinquenta anos atrás.', '/ɪt wɑːz ˈdeɪtɪd ˈfɪfti jɪrz əˈɡoʊ/', '"Ago" = atrás, sempre depois do período.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"dated","pos":"adjective","ipa":"/ˈdeɪtɪd/","gloss":"datado"},{"surface":"fifty","pos":"numeral","ipa":"/ˈfɪfti/","gloss":"cinquenta"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"},{"surface":"ago","pos":"adverb","ipa":"/əˈɡoʊ/","gloss":"atrás (tempo)"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-07-04', 'lesson-stories-b1-07', 4, 'story', 'He had written it to a friend he never saw again.', 'Ele tinha escrito para um amigo que nunca mais viu.', '/hiː hæd ˈrɪtən ɪt tuː ə frɛnd hiː ˈnɛvər sɔː əˈɡɛn/', 'Past perfect: "had written" antes do resto da história.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"written","pos":"verb","ipa":"/ˈrɪtən/","gloss":"escrito"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"friend","pos":"noun","ipa":"/frɛnd/","gloss":"amigo, amiga"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"saw","pos":"verb","ipa":"/sɔː/","gloss":"viu"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-07-05', 'lesson-stories-b1-07', 5, 'story', 'The letter was never sent.', 'A carta nunca foi enviada.', '/ðə ˈlɛtər wɑːz ˈnɛvər sɛnt/', 'Voz passiva no passado: "was never sent".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"letter","pos":"noun","ipa":"/ˈlɛtər/","gloss":"carta, letra"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"sent","pos":"verb","ipa":"/sɛnt/","gloss":"enviou"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-07-06', 'lesson-stories-b1-07', 6, 'story', 'Sara searched online and found the friend''s family.', 'Sara pesquisou na internet e achou a família do amigo.', '/ˈsɛrə sɜːrtʃt ˌɑːnˈlaɪn ænd faʊnd ðə frɛndz ˈfæməli/', '"Search" = pesquisar.', '[]'::jsonb, '[{"surface":"Sara","pos":"proper noun","ipa":"/ˈsɛrə/","gloss":"Sara"},{"surface":"searched","pos":"verb","ipa":"/sɜːrtʃt/","gloss":"pesquisou"},{"surface":"online","pos":"adverb","ipa":"/ˌɑːnˈlaɪn/","gloss":"na internet"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"found","pos":"verb","ipa":"/faʊnd/","gloss":"achou, encontrado"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"friend''s","pos":"noun","ipa":"/frɛndz/","gloss":"do amigo"},{"surface":"family","pos":"noun","ipa":"/ˈfæməli/","gloss":"família"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-07-07', 'lesson-stories-b1-07', 7, 'story', 'She mailed the letter with a short note of her own.', 'Ela mandou a carta pelo correio com um bilhete dela.', '/ʃiː meɪld ðə ˈlɛtər wɪð ə ʃɔːrt noʊt ʌv hɜːr oʊn/', '"Of her own" = dela mesma.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"mailed","pos":"verb","ipa":"/meɪld/","gloss":"enviou pelo correio"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"letter","pos":"noun","ipa":"/ˈlɛtər/","gloss":"carta, letra"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"short","pos":"adjective","ipa":"/ʃɔːrt/","gloss":"curto"},{"surface":"note","pos":"noun","ipa":"/noʊt/","gloss":"bilhete, nota"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"own","pos":"verb","ipa":"/oʊn/","gloss":"ser dono, responsável"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-07-08', 'lesson-stories-b1-07', 8, 'story', 'A month later, she received a reply full of old photos.', 'Um mês depois, recebeu uma resposta cheia de fotos antigas.', '/ə mʌnθ ˈleɪtər ʃiː rɪˈsiːvd ə rɪˈplaɪ fʊl ʌv oʊld ˈfoʊtoʊz/', '"Reply" = resposta.', '[]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"mais tarde"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"received","pos":"verb","ipa":"/rɪˈsiːvd/","gloss":"recebeu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"reply","pos":"noun","ipa":"/rɪˈplaɪ/","gloss":"resposta"},{"surface":"full","pos":"adjective","ipa":"/fʊl/","gloss":"cheio"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"old","pos":"adjective","ipa":"/oʊld/","gloss":"velho; de idade"},{"surface":"photos","pos":"noun","ipa":"/ˈfoʊtoʊz/","gloss":"fotos"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-08', 'course-stories-b1', 8, 'A trilha', 'Uma caminhada que mudou de plano.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-08-01', 'lesson-stories-b1-08', 1, 'story', 'We planned to reach the top of the mountain by noon.', 'Planejamos chegar ao topo da montanha até o meio-dia.', '/wiː plænd tuː riːtʃ ðə tɑːp ʌv ðə ˈmaʊntən baɪ nuːn/', '"By" + horário = até, no máximo.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"planned","pos":"verb","ipa":"/plænd/","gloss":"planejou"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"reach","pos":"verb","ipa":"/riːtʃ/","gloss":"alcançar, chegar a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"top","pos":"adjective","ipa":"/tɑːp/","gloss":"principal, máximo"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"mountain","pos":"noun","ipa":"/ˈmaʊntən/","gloss":"montanha"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"noon","pos":"noun","ipa":"/nuːn/","gloss":"meio-dia"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-08-02', 'lesson-stories-b1-08', 2, 'story', 'The path was steep and full of rocks.', 'A trilha era íngreme e cheia de pedras.', '/ðə pæθ wɑːz stiːp ænd fʊl ʌv rɑːks/', '"Steep" = íngreme.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"path","pos":"noun","ipa":"/pæθ/","gloss":"trilha, caminho"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"steep","pos":"adjective","ipa":"/stiːp/","gloss":"íngreme"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"full","pos":"adjective","ipa":"/fʊl/","gloss":"cheio"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"rocks","pos":"noun","ipa":"/rɑːks/","gloss":"pedras"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-08-03', 'lesson-stories-b1-08', 3, 'story', 'Halfway up, the weather changed quickly.', 'No meio da subida, o tempo mudou rápido.', '/ˌhæfˈweɪ ʌp ðə ˈwɛðər tʃeɪndʒd ˈkwɪkli/', '"Halfway up" = no meio da subida.', '[]'::jsonb, '[{"surface":"Halfway","pos":"adverb","ipa":"/ˌhæfˈweɪ/","gloss":"no meio do caminho"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"},{"surface":"changed","pos":"verb","ipa":"/tʃeɪndʒd/","gloss":"mudou, mudado"},{"surface":"quickly","pos":"adverb","ipa":"/ˈkwɪkli/","gloss":"rapidamente"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-08-04', 'lesson-stories-b1-08', 4, 'story', 'Dark clouds covered the sky, and it got cold.', 'Nuvens escuras cobriram o céu, e esfriou.', '/dɑːrk klaʊdz ˈkʌvərd ðə skaɪ ænd ɪt ɡɑːt koʊld/', '"Get cold" = esfriar.', '[]'::jsonb, '[{"surface":"Dark","pos":"adjective","ipa":"/dɑːrk/","gloss":"escuro"},{"surface":"clouds","pos":"noun","ipa":"/klaʊdz/","gloss":"nuvens"},{"surface":"covered","pos":"verb","ipa":"/ˈkʌvərd/","gloss":"cobriu"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"sky","pos":"noun","ipa":"/skaɪ/","gloss":"céu"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-08-05', 'lesson-stories-b1-08', 5, 'story', 'We had to make a choice: continue or turn back.', 'Tivemos que escolher: continuar ou voltar.', '/wiː hæd tuː meɪk ə tʃɔɪs kənˈtɪnjuː ɔːr tɜːrn bæk/', '"Turn back" = voltar, dar meia-volta.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"choice","pos":"noun","ipa":"/tʃɔɪs/","gloss":"escolha"},{"surface":"continue","pos":"verb","ipa":"/kənˈtɪnjuː/","gloss":"continuar"},{"surface":"or","pos":"conjunction","ipa":"/ɔːr/","gloss":"ou"},{"surface":"turn","pos":"verb","ipa":"/tɜːrn/","gloss":"ligar (turn on)"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-08-06', 'lesson-stories-b1-08', 6, 'story', 'We decided that the top could wait for another day.', 'Decidimos que o topo podia esperar outro dia.', '/wiː dɪˈsaɪdɪd ðæt ðə tɑːp kʊd weɪt fɔːr əˈnʌðər deɪ/', '"Could wait" = podia esperar.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"decided","pos":"verb","ipa":"/dɪˈsaɪdɪd/","gloss":"decidiu"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"top","pos":"adjective","ipa":"/tɑːp/","gloss":"principal, máximo"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"another","pos":"determiner","ipa":"/əˈnʌðər/","gloss":"outro, mais um"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-08-07', 'lesson-stories-b1-08', 7, 'story', 'On the way down, we saw a family of deer.', 'Na descida, vimos uma família de cervos.', '/ɑːn ðə weɪ daʊn wiː sɔː ə ˈfæməli ʌv dɪr/', '"Deer" é igual no singular e no plural.', '[]'::jsonb, '[{"surface":"On","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"saw","pos":"verb","ipa":"/sɔː/","gloss":"viu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"family","pos":"noun","ipa":"/ˈfæməli/","gloss":"família"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"deer","pos":"noun","ipa":"/dɪr/","gloss":"cervo"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-08-08', 'lesson-stories-b1-08', 8, 'story', 'It wasn''t the trip we planned, but it was a good one.', 'Não foi a viagem que planejamos, mas foi boa.', '/ɪt ˈwʌzənt ðə trɪp wiː plænd bʌt ɪt wɑːz ə ɡʊd wʌn/', '"A good one" evita repetir "trip".', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"wasn''t","pos":"verb","ipa":"/ˈwʌzənt/","gloss":"não era, não estava (was not)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"trip","pos":"noun","ipa":"/trɪp/","gloss":"viagem"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"planned","pos":"verb","ipa":"/plænd/","gloss":"planejou"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-09', 'course-stories-b1', 9, 'O erro no restaurante', 'Um pedido trocado.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-09-01', 'lesson-stories-b1-09', 1, 'story', 'Leo invited his parents to a fancy restaurant.', 'Leo convidou os pais para um restaurante chique.', '/ˈliːoʊ ɪnˈvaɪtɪd hɪz ˈpɛrənts tuː ə ˈfænsi ˈrɛstərɑːnt/', '"Fancy" = chique, sofisticado.', '[]'::jsonb, '[{"surface":"Leo","pos":"proper noun","ipa":"/ˈliːoʊ/","gloss":"Leo"},{"surface":"invited","pos":"verb","ipa":"/ɪnˈvaɪtɪd/","gloss":"convidado"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"parents","pos":"noun","ipa":"/ˈpɛrənts/","gloss":"pais (pai e mãe)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"fancy","pos":"adjective","ipa":"/ˈfænsi/","gloss":"chique"},{"surface":"restaurant","pos":"noun","ipa":"/ˈrɛstərɑːnt/","gloss":"restaurante"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-09-02', 'lesson-stories-b1-09', 2, 'story', 'He ordered fish, but the waiter brought him soup.', 'Ele pediu peixe, mas o garçom trouxe sopa.', '/hiː ˈɔːrdərd fɪʃ bʌt ðə ˈweɪtər brɔːt hɪm suːp/', '"Bring", passado "brought".', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"ordered","pos":"verb","ipa":"/ˈɔːrdərd/","gloss":"pediu, pedido"},{"surface":"fish","pos":"noun","ipa":"/fɪʃ/","gloss":"peixe"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"waiter","pos":"noun","ipa":"/ˈweɪtər/","gloss":"garçom"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"soup","pos":"noun","ipa":"/suːp/","gloss":"sopa"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-09-03', 'lesson-stories-b1-09', 3, 'story', 'He was too shy to say anything.', 'Estava tímido demais para dizer algo.', '/hiː wɑːz tuː ʃaɪ tuː seɪ ˈɛniθɪŋ/', '"Too + adjetivo + to" = demais para.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"shy","pos":"adjective","ipa":"/ʃaɪ/","gloss":"tímido"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-09-04', 'lesson-stories-b1-09', 4, 'story', 'His mother saw his face and called the waiter.', 'A mãe viu a cara dele e chamou o garçom.', '/hɪz ˈmʌðər sɔː hɪz feɪs ænd kɔːld ðə ˈweɪtər/', '"Call the waiter" = chamar o garçom.', '[]'::jsonb, '[{"surface":"His","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"mother","pos":"noun","ipa":"/ˈmʌðər/","gloss":"mãe"},{"surface":"saw","pos":"verb","ipa":"/sɔː/","gloss":"viu"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"face","pos":"noun","ipa":"/feɪs/","gloss":"rosto"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"called","pos":"verb","ipa":"/kɔːld/","gloss":"ligou, chamou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"waiter","pos":"noun","ipa":"/ˈweɪtər/","gloss":"garçom"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-09-05', 'lesson-stories-b1-09', 5, 'story', 'She politely told him that there had been a mistake.', 'Ela disse educadamente que tinha havido um engano.', '/ʃiː pəˈlaɪtli toʊld hɪm ðæt ðɛr hæd bɪn ə mɪˈsteɪk/', 'Discurso indireto: "there has been" vira "there had been". Forma educada de reclamar.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"politely","pos":"adverb","ipa":"/pəˈlaɪtli/","gloss":"educadamente"},{"surface":"told","pos":"verb","ipa":"/toʊld/","gloss":"contou, disse"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"mistake","pos":"noun","ipa":"/mɪˈsteɪk/","gloss":"erro"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-09-06', 'lesson-stories-b1-09', 6, 'story', 'The waiter apologized and brought the fish right away.', 'O garçom pediu desculpas e trouxe o peixe na hora.', '/ðə ˈweɪtər əˈpɑːlədʒaɪzd ænd brɔːt ðə fɪʃ raɪt əˈweɪ/', '"Apologize" = pedir desculpas. "Right away" = imediatamente.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"waiter","pos":"noun","ipa":"/ˈweɪtər/","gloss":"garçom"},{"surface":"apologized","pos":"verb","ipa":"/əˈpɑːlədʒaɪzd/","gloss":"pediu desculpas"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"fish","pos":"noun","ipa":"/fɪʃ/","gloss":"peixe"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"away","pos":"adverb","ipa":"/əˈweɪ/","gloss":"embora; (right away) já"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-09-07', 'lesson-stories-b1-09', 7, 'story', 'He also brought a free dessert for the table.', 'Também trouxe uma sobremesa grátis para a mesa.', '/hiː ˈɔːlsoʊ brɔːt ə friː dɪˈzɜːrt fɔːr ðə ˈteɪbəl/', '"Free" = grátis.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"also","pos":"adverb","ipa":"/ˈɔːlsoʊ/","gloss":"também"},{"surface":"brought","pos":"verb","ipa":"/brɔːt/","gloss":"trouxe, levou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"free","pos":"adjective","ipa":"/friː/","gloss":"livre, disponível"},{"surface":"dessert","pos":"noun","ipa":"/dɪˈzɜːrt/","gloss":"sobremesa"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"table","pos":"noun","ipa":"/ˈteɪbəl/","gloss":"mesa"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-09-08', 'lesson-stories-b1-09', 8, 'story', 'Leo learned that asking politely is not rude.', 'Leo aprendeu que pedir com educação não é falta de educação.', '/ˈliːoʊ lɜːrnd ðæt ˈæskɪŋ pəˈlaɪtli ɪz nɑːt ruːd/', '"Politely" = educadamente. "Rude" = grosseiro.', '[]'::jsonb, '[{"surface":"Leo","pos":"proper noun","ipa":"/ˈliːoʊ/","gloss":"Leo"},{"surface":"learned","pos":"verb","ipa":"/lɜːrnd/","gloss":"aprendeu"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"asking","pos":"verb","ipa":"/ˈæskɪŋ/","gloss":"pedindo, perguntando"},{"surface":"politely","pos":"adverb","ipa":"/pəˈlaɪtli/","gloss":"educadamente"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"rude","pos":"adjective","ipa":"/ruːd/","gloss":"grosso, mal-educado"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-stories-b1-10', 'course-stories-b1', 10, 'Um ano depois', 'Olhando para trás.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-stories-b1-10-01', 'lesson-stories-b1-10', 1, 'story', 'One year ago, I could barely order a coffee in English.', 'Um ano atrás, eu mal conseguia pedir um café em inglês.', '/wʌn jɪr əˈɡoʊ aɪ kʊd ˈbɛrli ˈɔːrdər ə ˈkɔːfi ɪn ˈɪŋɡlɪʃ/', '"Barely" = mal, quase não.', '[]'::jsonb, '[{"surface":"One","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"},{"surface":"ago","pos":"adverb","ipa":"/əˈɡoʊ/","gloss":"atrás (tempo)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"barely","pos":"adverb","ipa":"/ˈbɛrli/","gloss":"mal, quase não"},{"surface":"order","pos":"verb","ipa":"/ˈɔːrdər/","gloss":"pedir (comida)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"English","pos":"proper noun","ipa":"/ˈɪŋɡlɪʃ/","gloss":"inglês"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-10-02', 'lesson-stories-b1-10', 2, 'story', 'I was afraid of making mistakes.', 'Eu tinha medo de errar.', '/aɪ wɑːz əˈfreɪd ʌv ˈmeɪkɪŋ mɪˈsteɪks/', '"Afraid of" + -ing.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"afraid","pos":"adjective","ipa":"/əˈfreɪd/","gloss":"com medo"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"making","pos":"verb","ipa":"/ˈmeɪkɪŋ/","gloss":"fazendo"},{"surface":"mistakes","pos":"noun","ipa":"/mɪˈsteɪks/","gloss":"erros"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-10-03', 'lesson-stories-b1-10', 3, 'story', 'So I started practicing a little every day.', 'Então comecei a praticar um pouco todo dia.', '/soʊ aɪ ˈstɑːrtɪd ˈpræktɪsɪŋ ə ˈlɪtəl ˈɛvri deɪ/', '"A little every day" = um pouco todo dia.', '[]'::jsonb, '[{"surface":"So","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"started","pos":"verb","ipa":"/ˈstɑːrtɪd/","gloss":"começado"},{"surface":"practicing","pos":"verb","ipa":"/ˈpræktɪsɪŋ/","gloss":"praticando"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"little","pos":"adjective","ipa":"/ˈlɪtəl/","gloss":"pouco, pequeno"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-10-04', 'lesson-stories-b1-10', 4, 'story', 'Some days were hard, and I wanted to give up.', 'Alguns dias foram difíceis, e eu quis desistir.', '/sʌm deɪz wɜːr hɑːrd ænd aɪ ˈwɑːntɪd tuː ɡɪv ʌp/', '"Give up" = desistir.', '[]'::jsonb, '[{"surface":"Some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"days","pos":"noun","ipa":"/deɪz/","gloss":"dias"},{"surface":"were","pos":"verb","ipa":"/wɜːr/","gloss":"eram, estavam"},{"surface":"hard","pos":"adjective","ipa":"/hɑːrd/","gloss":"duro, difícil"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"wanted","pos":"verb","ipa":"/ˈwɑːntɪd/","gloss":"quis, queria"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-10-05', 'lesson-stories-b1-10', 5, 'story', 'But slowly, the words started to feel familiar.', 'Mas, aos poucos, as palavras começaram a soar familiares.', '/bʌt ˈsloʊli ðə wɜːrdz ˈstɑːrtɪd tuː fiːl fəˈmɪljər/', '"Slowly" = aos poucos.', '[]'::jsonb, '[{"surface":"But","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"slowly","pos":"adverb","ipa":"/ˈsloʊli/","gloss":"devagar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"words","pos":"noun","ipa":"/wɜːrdz/","gloss":"palavras"},{"surface":"started","pos":"verb","ipa":"/ˈstɑːrtɪd/","gloss":"começado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"feel","pos":"verb","ipa":"/fiːl/","gloss":"sentir"},{"surface":"familiar","pos":"adjective","ipa":"/fəˈmɪljər/","gloss":"familiar"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-10-06', 'lesson-stories-b1-10', 6, 'story', 'Last week, I had a whole conversation with a stranger.', 'Semana passada, tive uma conversa inteira com um desconhecido.', '/læst wiːk aɪ hæd ə hoʊl ˌkɑːnvərˈseɪʃən wɪð ə ˈstreɪndʒər/', '"Whole" = inteiro. "Stranger" = desconhecido.', '[]'::jsonb, '[{"surface":"Last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"whole","pos":"adjective","ipa":"/hoʊl/","gloss":"inteiro"},{"surface":"conversation","pos":"noun","ipa":"/ˌkɑːnvərˈseɪʃən/","gloss":"conversa"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"stranger","pos":"noun","ipa":"/ˈstreɪndʒər/","gloss":"desconhecido"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-10-07', 'lesson-stories-b1-10', 7, 'story', 'I made mistakes, and nobody cared.', 'Errei, e ninguém ligou.', '/aɪ meɪd mɪˈsteɪks ænd ˈnoʊbɑːdi kɛrd/', '"Nobody cared" = ninguém se importou.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"},{"surface":"mistakes","pos":"noun","ipa":"/mɪˈsteɪks/","gloss":"erros"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"nobody","pos":"pronoun","ipa":"/ˈnoʊbɑːdi/","gloss":"ninguém"},{"surface":"cared","pos":"verb","ipa":"/kɛrd/","gloss":"se importou"}]'::jsonb, NULL, NULL),
  ('unit-stories-b1-10-08', 'lesson-stories-b1-10', 8, 'story', 'I''m still learning, but now I''m not afraid.', 'Ainda estou aprendendo, mas agora não tenho medo.', '/aɪm stɪl ˈlɜːrnɪŋ bʌt naʊ aɪm nɑːt əˈfreɪd/', '"Still" = ainda. Fecha o curso com o presente.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"still","pos":"adverb","ipa":"/stɪl/","gloss":"ainda"},{"surface":"learning","pos":"verb","ipa":"/ˈlɜːrnɪŋ/","gloss":"aprendendo"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"afraid","pos":"adjective","ipa":"/əˈfreɪd/","gloss":"com medo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
