-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-social-a2', 'social-life-a2', 'Vida Social', 'Conhecer gente, convidar, puxar conversa, elogiar, dar opinião e pedir desculpas com naturalidade.', 'As conversas que fazem amizade: apresentar-se e lembrar nomes, convidar e recusar sem ser grosso, conversa fiada, elogios, opiniões e como resolver mal-entendidos. Cada frase explica o registro e a estrutura.', 'A2', 'social', 7, 'dia-a-dia', 5, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-social-a2-01', 'course-social-a2', 1, 'Conhecendo pessoas', 'Apresentar-se, lembrar nomes e continuar a conversa.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-social-a2-01-01', 'lesson-social-a2-01', 1, 'sentence', 'Hi, I don''t think we''ve met.', 'Oi, acho que ainda não nos conhecemos.', '/haɪ aɪ doʊnt θɪŋk wiːv mɛt/', 'Neutro. Present perfect: "we''ve met" = já nos conhecemos.', '[]'::jsonb, '[{"surface":"Hi","pos":"interjection","ipa":"/haɪ/","gloss":"oi"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"we''ve","pos":"pronoun","ipa":"/wiːv/","gloss":"nós temos (we have)"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-02', 'lesson-social-a2-01', 2, 'sentence', 'I''m Ana, a friend of Mark''s.', 'Sou a Ana, amiga do Mark.', '/aɪm ˈænə ə frɛnd ʌv mɑːrks/', '"A friend of + nome''s" = amigo de alguém.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"Ana","pos":"proper noun","ipa":"/ˈænə/","gloss":"Ana"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"friend","pos":"noun","ipa":"/frɛnd/","gloss":"amigo, amiga"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"Mark''s","pos":"proper noun","ipa":"/mɑːrks/","gloss":"do Mark"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-03', 'lesson-social-a2-01', 3, 'sentence', 'Sorry, what was your name again?', 'Desculpa, qual era o seu nome mesmo?', '/ˈsɑːri wʌt wɑːz jʊr neɪm əˈɡɛn/', 'Neutro. "Again" no fim = mesmo, de novo. Passado "was" suaviza.', '[]'::jsonb, '[{"surface":"Sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"name","pos":"noun","ipa":"/neɪm/","gloss":"nome"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-04', 'lesson-social-a2-01', 4, 'sentence', 'How do you know each other?', 'De onde vocês se conhecem?', '/haʊ duː juː noʊ iːtʃ ˈʌðər/', '"Each other" = um ao outro.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"each","pos":"determiner","ipa":"/iːtʃ/","gloss":"cada"},{"surface":"other","pos":"pronoun","ipa":"/ˈʌðər/","gloss":"outro"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-05', 'lesson-social-a2-01', 5, 'sentence', 'We went to school together.', 'Estudamos juntos.', '/wiː wɛnt tuː skuːl təˈɡɛðər/', 'Passado: "went to school together".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"school","pos":"noun","ipa":"/skuːl/","gloss":"escola"},{"surface":"together","pos":"adverb","ipa":"/təˈɡɛðər/","gloss":"juntos"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-06', 'lesson-social-a2-01', 6, 'sentence', 'What brings you here?', 'O que te traz aqui?', '/wʌt brɪŋz juː hɪr/', 'Neutro. Pergunta aberta para puxar assunto.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"brings","pos":"verb","ipa":"/brɪŋz/","gloss":"traz"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-07', 'lesson-social-a2-01', 7, 'sentence', 'Have we met before?', 'Já nos vimos antes?', '/hæv wiː mɛt bɪˈfɔːr/', 'Present perfect em pergunta sobre experiência.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-08', 'lesson-social-a2-01', 8, 'sentence', 'I have heard a lot about you.', 'Ouvi falar muito de você.', '/aɪ hæv hɜːrd ə lɑːt əˈbaʊt juː/', 'Neutro e simpático; "a lot about" = muito sobre.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"heard","pos":"verb","ipa":"/hɜːrd/","gloss":"ouviu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lot","pos":"noun","ipa":"/lɑːt/","gloss":"muito (a lot)"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-09', 'lesson-social-a2-01', 9, 'sentence', 'Let me introduce you to my wife.', 'Deixa eu te apresentar à minha esposa.', '/lɛt miː ˌɪntrəˈduːs juː tuː maɪ waɪf/', '"Introduce to" = apresentar a.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"introduce","pos":"verb","ipa":"/ˌɪntrəˈduːs/","gloss":"apresentar (pessoas)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"wife","pos":"noun","ipa":"/waɪf/","gloss":"esposa"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-01-10', 'lesson-social-a2-01', 10, 'sentence', 'Great to finally meet you.', 'Que bom finalmente te conhecer.', '/ɡreɪt tuː ˈfaɪnəli miːt juː/', '"Finally" = finalmente.', '[]'::jsonb, '[{"surface":"Great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"finally","pos":"adverb","ipa":"/ˈfaɪnəli/","gloss":"finalmente"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-social-a2-02', 'course-social-a2', 2, 'Convites', 'Convidar, aceitar e recusar com educação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-social-a2-02-01', 'lesson-social-a2-02', 1, 'sentence', 'Would you like to come to my party?', 'Você gostaria de vir à minha festa?', '/wʊd juː laɪk tuː kʌm tuː maɪ ˈpɑːrti/', 'Convite educado: "Would you like to" + verbo.', '[]'::jsonb, '[{"surface":"Would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"party","pos":"noun","ipa":"/ˈpɑːrti/","gloss":"festa"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-02', 'lesson-social-a2-02', 2, 'sentence', 'We''re having a barbecue on Saturday.', 'Vamos fazer um churrasco no sábado.', '/wɪr ˈhævɪŋ ə ˈbɑːrbɪkjuː ɑːn ˈsætərdeɪ/', 'Presente contínuo para evento marcado.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"having","pos":"verb","ipa":"/ˈhævɪŋ/","gloss":"receber, ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"barbecue","pos":"noun","ipa":"/ˈbɑːrbɪkjuː/","gloss":"churrasco"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"Saturday","pos":"proper noun","ipa":"/ˈsætərdeɪ/","gloss":"sábado"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-03', 'lesson-social-a2-02', 3, 'sentence', 'I''d love to!', 'Eu adoraria!', '/aɪd lʌv tuː/', 'Resposta animada: "I''d love to" (to sem verbo depois).', '[]'::jsonb, '[{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"love","pos":"verb","ipa":"/lʌv/","gloss":"amar, adorar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-04', 'lesson-social-a2-02', 4, 'sentence', 'Sorry, I can''t make it.', 'Desculpa, não vou conseguir ir.', '/ˈsɑːri aɪ kænt meɪk ɪt/', '"Make it" = conseguir ir, chegar.', '[]'::jsonb, '[{"surface":"Sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-05', 'lesson-social-a2-02', 5, 'sentence', 'Maybe another time?', 'Quem sabe outra vez?', '/ˈmeɪbi əˈnʌðər taɪm/', 'Recusa suave que deixa a porta aberta.', '[]'::jsonb, '[{"surface":"Maybe","pos":"adverb","ipa":"/ˈmeɪbi/","gloss":"talvez"},{"surface":"another","pos":"determiner","ipa":"/əˈnʌðər/","gloss":"outro, mais um"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-06', 'lesson-social-a2-02', 6, 'sentence', 'Can I bring a friend?', 'Posso levar um amigo?', '/kæn aɪ brɪŋ ə frɛnd/', '"Bring" = levar junto.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"bring","pos":"verb","ipa":"/brɪŋ/","gloss":"trazer"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"friend","pos":"noun","ipa":"/frɛnd/","gloss":"amigo, amiga"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-07', 'lesson-social-a2-02', 7, 'sentence', 'Should I bring anything?', 'Devo levar alguma coisa?', '/ʃʊd aɪ brɪŋ ˈɛniθɪŋ/', 'Pergunta educada do convidado.', '[]'::jsonb, '[{"surface":"Should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"bring","pos":"verb","ipa":"/brɪŋ/","gloss":"trazer"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-08', 'lesson-social-a2-02', 8, 'sentence', 'What''s the dress code?', 'Qual é o traje?', '/wʌts ðə drɛs koʊd/', '"Dress code" = código de vestimenta.', '[]'::jsonb, '[{"surface":"What''s","pos":"pronoun","ipa":"/wʌts/","gloss":"qual é"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"dress","pos":"noun","ipa":"/drɛs/","gloss":"vestido"},{"surface":"code","pos":"noun","ipa":"/koʊd/","gloss":"código"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-09', 'lesson-social-a2-02', 9, 'sentence', 'Thanks for inviting me.', 'Obrigado pelo convite.', '/θæŋks fɔːr ɪnˈvaɪtɪŋ miː/', '"Thanks for" + verbo com "-ing".', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"inviting","pos":"verb","ipa":"/ɪnˈvaɪtɪŋ/","gloss":"convidar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-02-10', 'lesson-social-a2-02', 10, 'sentence', 'Let me check and I''ll let you know.', 'Deixa eu ver e te aviso.', '/lɛt miː tʃɛk ænd aɪl lɛt juː noʊ/', 'Resposta para ganhar tempo.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-social-a2-03', 'course-social-a2', 3, 'Puxando conversa', 'Conversa fiada que quebra o gelo.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-social-a2-03-01', 'lesson-social-a2-03', 1, 'sentence', 'Nice weather today, huh?', 'Que tempo bom hoje, né?', '/naɪs ˈwɛðər təˈdeɪ hʌ/', 'Informal. "Huh?" no fim = né?', '[]'::jsonb, '[{"surface":"Nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"},{"surface":"huh","pos":"interjection","ipa":"/hʌ/","gloss":"né?"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-02', 'lesson-social-a2-03', 2, 'sentence', 'Have you been here before?', 'Você já veio aqui antes?', '/hæv juː bɪn hɪr bɪˈfɔːr/', 'Present perfect para experiência.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-03', 'lesson-social-a2-03', 3, 'sentence', 'How do you like the city so far?', 'O que está achando da cidade até agora?', '/haʊ duː juː laɪk ðə ˈsɪti soʊ fɑːr/', '"How do you like" = o que você acha. "So far" = até agora.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"city","pos":"noun","ipa":"/ˈsɪti/","gloss":"cidade"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"far","pos":"adjective","ipa":"/fɑːr/","gloss":"longe"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-04', 'lesson-social-a2-03', 4, 'sentence', 'What do you do for fun?', 'O que você faz para se divertir?', '/wʌt duː juː duː fɔːr fʌn/', '"For fun" = por diversão.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"fun","pos":"noun","ipa":"/fʌn/","gloss":"diversão"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-05', 'lesson-social-a2-03', 5, 'sentence', 'Are you into sports?', 'Você curte esporte?', '/ɑːr juː ˈɪntuː spɔːrts/', 'Informal. "Be into" = gostar muito de.', '[]'::jsonb, '[{"surface":"Are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"into","pos":"preposition","ipa":"/ˈɪntuː/","gloss":"para dentro de"},{"surface":"sports","pos":"noun","ipa":"/spɔːrts/","gloss":"esportes"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-06', 'lesson-social-a2-03', 6, 'sentence', 'I''ve heard great things about this place.', 'Ouvi coisas ótimas sobre este lugar.', '/aɪv hɜːrd ɡreɪt θɪŋz əˈbaʊt ðɪs pleɪs/', 'Present perfect sem data.', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"heard","pos":"verb","ipa":"/hɜːrd/","gloss":"ouviu"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"things","pos":"noun","ipa":"/θɪŋz/","gloss":"coisas"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"place","pos":"noun","ipa":"/pleɪs/","gloss":"lugar"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-07', 'lesson-social-a2-03', 7, 'sentence', 'That sounds interesting.', 'Isso parece interessante.', '/ðæt saʊndz ˈɪntrəstɪŋ/', '"Sound" + adjetivo = parecer (pelo que se ouve).', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"sounds","pos":"verb","ipa":"/saʊndz/","gloss":"soa, parece"},{"surface":"interesting","pos":"adjective","ipa":"/ˈɪntrəstɪŋ/","gloss":"interessante"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-08', 'lesson-social-a2-03', 8, 'sentence', 'Tell me more.', 'Me conta mais.', '/tɛl miː mɔːr/', 'Mostra interesse e mantém a conversa.', '[]'::jsonb, '[{"surface":"Tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-09', 'lesson-social-a2-03', 9, 'sentence', 'Oh really? Me too!', 'Sério? Eu também!', '/oʊ ˈriːəli miː tuː/', '"Me too" para concordar com afirmativa.', '[]'::jsonb, '[{"surface":"Oh","pos":"interjection","ipa":"/oʊ/","gloss":"ah, oh"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"Me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-03-10', 'lesson-social-a2-03', 10, 'sentence', 'Anyway, it was nice talking to you.', 'Bom, foi bom conversar com você.', '/ˈɛniweɪ ɪt wɑːz naɪs ˈtɔːkɪŋ tuː juː/', '"Anyway" encerra ou muda de assunto.', '[]'::jsonb, '[{"surface":"Anyway","pos":"adverb","ipa":"/ˈɛniweɪ/","gloss":"enfim, de qualquer forma"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"talking","pos":"verb","ipa":"/ˈtɔːkɪŋ/","gloss":"conversar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-social-a2-04', 'course-social-a2', 4, 'Elogios e agradecimentos', 'Elogiar sem exagero e agradecer do jeito certo.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-social-a2-04-01', 'lesson-social-a2-04', 1, 'sentence', 'I love your shoes!', 'Amei seus sapatos!', '/aɪ lʌv jʊr ʃuːz/', 'Informal. Elogio comum e espontâneo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"love","pos":"verb","ipa":"/lʌv/","gloss":"amar, adorar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"shoes","pos":"noun","ipa":"/ʃuːz/","gloss":"sapatos"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-02', 'lesson-social-a2-04', 2, 'sentence', 'You look great in that color.', 'Essa cor fica ótima em você.', '/juː lʊk ɡreɪt ɪn ðæt ˈkʌlər/', '"Look great in" + cor/roupa.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"color","pos":"noun","ipa":"/ˈkʌlər/","gloss":"cor"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-03', 'lesson-social-a2-04', 3, 'sentence', 'Your English is really good.', 'Seu inglês é muito bom.', '/jʊr ˈɪŋɡlɪʃ ɪz ˈriːəli ɡʊd/', '"Really" reforça o adjetivo.', '[]'::jsonb, '[{"surface":"Your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"English","pos":"proper noun","ipa":"/ˈɪŋɡlɪʃ/","gloss":"inglês"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-04', 'lesson-social-a2-04', 4, 'sentence', 'This is delicious, did you make it?', 'Está delicioso, foi você que fez?', '/ðɪs ɪz dɪˈlɪʃəs dɪd juː meɪk ɪt/', 'Elogio + pergunta mantém a conversa.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"delicious","pos":"adjective","ipa":"/dɪˈlɪʃəs/","gloss":"delicioso"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-05', 'lesson-social-a2-04', 5, 'sentence', 'Thanks, that means a lot.', 'Obrigado, isso significa muito.', '/θæŋks ðæt miːnz ə lɑːt/', '"That means a lot" = fico muito grato.', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"means","pos":"verb","ipa":"/miːnz/","gloss":"significa"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"lot","pos":"noun","ipa":"/lɑːt/","gloss":"muito (a lot)"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-06', 'lesson-social-a2-04', 6, 'sentence', 'You''re too kind.', 'Você é muito gentil.', '/jʊr tuː kaɪnd/', 'Resposta modesta a um elogio.', '[]'::jsonb, '[{"surface":"You''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"kind","pos":"adjective","ipa":"/kaɪnd/","gloss":"gentil"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-07', 'lesson-social-a2-04', 7, 'sentence', 'Thank you so much for your help.', 'Muito obrigado pela sua ajuda.', '/θæŋk juː soʊ mʌtʃ fɔːr jʊr hɛlp/', '"So much" reforça o agradecimento.', '[]'::jsonb, '[{"surface":"Thank","pos":"verb","ipa":"/θæŋk/","gloss":"agradecer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-08', 'lesson-social-a2-04', 8, 'sentence', 'I really appreciate it.', 'Agradeço muito.', '/aɪ ˈriːəli əˈpriːʃieɪt ɪt/', '"Appreciate" = agradecer, valorizar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"appreciate","pos":"verb","ipa":"/əˈpriːʃieɪt/","gloss":"agradecer, valorizar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-09', 'lesson-social-a2-04', 9, 'sentence', 'You''re welcome.', 'De nada.', '/jʊr ˈwɛlkəm/', 'Resposta padrão a "thank you".', '[]'::jsonb, '[{"surface":"You''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"welcome","pos":"adjective","ipa":"/ˈwɛlkəm/","gloss":"bem-vindo"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-04-10', 'lesson-social-a2-04', 10, 'sentence', 'My pleasure.', 'Foi um prazer.', '/maɪ ˈplɛʒər/', 'Resposta mais calorosa que "you''re welcome".', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"pleasure","pos":"noun","ipa":"/ˈplɛʒər/","gloss":"prazer"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-social-a2-05', 'course-social-a2', 5, 'Dando opinião', 'Dizer o que você acha, concordar e discordar.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-social-a2-05-01', 'lesson-social-a2-05', 1, 'sentence', 'In my opinion, it was too long.', 'Na minha opinião, foi longo demais.', '/ɪn maɪ əˈpɪnjən ɪt wɑːz tuː lɔːŋ/', '"In my opinion" abre uma opinião.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"opinion","pos":"noun","ipa":"/əˈpɪnjən/","gloss":"opinião"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-02', 'lesson-social-a2-05', 2, 'sentence', 'I think you are right.', 'Acho que você tem razão.', '/aɪ θɪŋk juː ɑːr raɪt/', 'Em inglês "ter razão" é "be right".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-03', 'lesson-social-a2-05', 3, 'sentence', 'I totally agree.', 'Concordo totalmente.', '/aɪ ˈtoʊtəli əˈɡriː/', '"Agree" já é verbo: nunca "I am agree".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"totally","pos":"adverb","ipa":"/ˈtoʊtəli/","gloss":"totalmente"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-04', 'lesson-social-a2-05', 4, 'sentence', 'I''m not sure I agree.', 'Não sei se concordo.', '/aɪm nɑːt ʃʊr aɪ əˈɡriː/', 'Discordância suave.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"sure","pos":"adjective","ipa":"/ʃʊr/","gloss":"claro; certo"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-05', 'lesson-social-a2-05', 5, 'sentence', 'It depends.', 'Depende.', '/ɪt dɪˈpɛndz/', '"It depends on" + algo.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"depends","pos":"verb","ipa":"/dɪˈpɛndz/","gloss":"depende"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-06', 'lesson-social-a2-05', 6, 'sentence', 'What do you think?', 'O que você acha?', '/wʌt duː juː θɪŋk/', 'Devolve a pergunta e inclui o outro.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-07', 'lesson-social-a2-05', 7, 'sentence', 'I see what you mean.', 'Entendo o que você quer dizer.', '/aɪ siː wʌt juː miːn/', '"Mean" = querer dizer.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"mean","pos":"verb","ipa":"/miːn/","gloss":"significar, querer dizer"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-08', 'lesson-social-a2-05', 8, 'sentence', 'That''s a good point.', 'Bem lembrado.', '/ðæts ə ɡʊd pɔɪnt/', 'Reconhece o argumento do outro.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-09', 'lesson-social-a2-05', 9, 'sentence', 'To be honest, I prefer the first one.', 'Para ser sincero, prefiro o primeiro.', '/tuː biː ˈɑːnɪst aɪ prɪˈfɜːr ðə fɜːrst wʌn/', '"To be honest" suaviza uma opinião direta.', '[]'::jsonb, '[{"surface":"To","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"honest","pos":"adjective","ipa":"/ˈɑːnɪst/","gloss":"sincero, honesto"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"prefer","pos":"verb","ipa":"/prɪˈfɜːr/","gloss":"preferir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-05-10', 'lesson-social-a2-05', 10, 'sentence', 'I don''t have a strong opinion.', 'Não tenho uma opinião forte.', '/aɪ doʊnt hæv ə strɔːŋ əˈpɪnjən/', 'Jeito neutro de não entrar na discussão.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"strong","pos":"adjective","ipa":"/strɔːŋ/","gloss":"forte"},{"surface":"opinion","pos":"noun","ipa":"/əˈpɪnjən/","gloss":"opinião"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-social-a2-06', 'course-social-a2', 6, 'Desculpas e mal-entendidos', 'Pedir desculpas, esclarecer e fazer as pazes.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-social-a2-06-01', 'lesson-social-a2-06', 1, 'sentence', 'I''m sorry, I didn''t mean to hurt you.', 'Desculpa, não quis te magoar.', '/aɪm ˈsɑːri aɪ ˈdɪdənt miːn tuː hɜːrt juː/', '"Didn''t mean to" = não tive a intenção de.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"mean","pos":"verb","ipa":"/miːn/","gloss":"significar, querer dizer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"hurt","pos":"verb","ipa":"/hɜːrt/","gloss":"doer, machucar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-02', 'lesson-social-a2-06', 2, 'sentence', 'It was my fault.', 'A culpa foi minha.', '/ɪt wɑːz maɪ fɔːlt/', '"Fault" = culpa.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"fault","pos":"noun","ipa":"/fɔːlt/","gloss":"culpa"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-03', 'lesson-social-a2-06', 3, 'sentence', 'I think you misunderstood me.', 'Acho que você me entendeu mal.', '/aɪ θɪŋk juː ˌmɪsʌndərˈstʊd miː/', '"Misunderstand" = entender errado.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"misunderstood","pos":"verb","ipa":"/ˌmɪsʌndərˈstʊd/","gloss":"entendeu mal"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-04', 'lesson-social-a2-06', 4, 'sentence', 'Let me explain.', 'Deixa eu explicar.', '/lɛt miː ɪkˈspleɪn/', 'Abre o esclarecimento.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"explain","pos":"verb","ipa":"/ɪkˈspleɪn/","gloss":"explicar"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-05', 'lesson-social-a2-06', 5, 'sentence', 'That''s not what I said.', 'Não foi isso que eu disse.', '/ðæts nɑːt wʌt aɪ sɛd/', '"What I said" = o que eu disse.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-06', 'lesson-social-a2-06', 6, 'sentence', 'No hard feelings.', 'Sem ressentimentos.', '/noʊ hɑːrd ˈfiːlɪŋz/', 'Informal. Encerra o conflito.', '[]'::jsonb, '[{"surface":"No","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"hard","pos":"adjective","ipa":"/hɑːrd/","gloss":"duro, difícil"},{"surface":"feelings","pos":"noun","ipa":"/ˈfiːlɪŋz/","gloss":"sentimentos"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-07', 'lesson-social-a2-06', 7, 'sentence', 'Apology accepted.', 'Desculpas aceitas.', '/əˈpɑːlədʒi əkˈsɛptɪd/', 'Resposta direta a um pedido de desculpas.', '[]'::jsonb, '[{"surface":"Apology","pos":"noun","ipa":"/əˈpɑːlədʒi/","gloss":"pedido de desculpas"},{"surface":"accepted","pos":"verb","ipa":"/əkˈsɛptɪd/","gloss":"aceito"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-08', 'lesson-social-a2-06', 8, 'sentence', 'Let''s forget about it.', 'Vamos esquecer isso.', '/lɛts fərˈɡɛt əˈbaʊt ɪt/', '"Forget about" = esquecer (assunto).', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"forget","pos":"verb","ipa":"/fərˈɡɛt/","gloss":"esquecer"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-09', 'lesson-social-a2-06', 9, 'sentence', 'I owe you an apology.', 'Te devo desculpas.', '/aɪ oʊ juː ən əˈpɑːlədʒi/', '"Owe" = dever (algo a alguém).', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"owe","pos":"verb","ipa":"/oʊ/","gloss":"dever"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"apology","pos":"noun","ipa":"/əˈpɑːlədʒi/","gloss":"pedido de desculpas"}]'::jsonb, NULL, NULL),
  ('unit-social-a2-06-10', 'lesson-social-a2-06', 10, 'sentence', 'We''re good.', 'Está tudo bem entre a gente.', '/wɪr ɡʊd/', 'Informal. Confirma que o conflito acabou.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
