-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-1000-words-a1', '1000-essential-words', '1000 Palavras Essenciais', 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.', 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.', 'A1', 'grammar', 11, 'fundamentos', 2, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-14', 'course-1000-words-a1', 14, 'Cidade e lugares', 'Onde as coisas ficam e como falar da sua cidade.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-14-01', 'lesson-1000-words-a1-14', 1, 'word', 'street', 'rua', '/striːt/', 'Rua usa "on": "on Main Street". Endereço completo usa "at".', '[]'::jsonb, '[{"surface":"street","pos":"noun","ipa":"/striːt/","gloss":"rua"}]'::jsonb, 'I live on this street.', 'Moro nesta rua.'),
  ('unit-1000-words-a1-14-02', 'lesson-1000-words-a1-14', 2, 'word', 'square', 'praça', '/skwɛr/', NULL, '[]'::jsonb, '[{"surface":"square","pos":"noun","ipa":"/skwɛr/","gloss":"praça"}]'::jsonb, 'Meet me in the main square.', 'Me encontra na praça principal.'),
  ('unit-1000-words-a1-14-03', 'lesson-1000-words-a1-14', 3, 'word', 'park', 'parque', '/pɑːrk/', NULL, '[]'::jsonb, '[{"surface":"park","pos":"noun","ipa":"/pɑːrk/","gloss":"parque"}]'::jsonb, 'Let''s go to the park.', 'Vamos ao parque.'),
  ('unit-1000-words-a1-14-04', 'lesson-1000-words-a1-14', 4, 'word', 'museum', 'museu', '/mjuːˈziːəm/', NULL, '[]'::jsonb, '[{"surface":"museum","pos":"noun","ipa":"/mjuːˈziːəm/","gloss":"museu"}]'::jsonb, 'The museum is closed on Mondays.', 'O museu fecha às segundas.'),
  ('unit-1000-words-a1-14-05', 'lesson-1000-words-a1-14', 5, 'word', 'library', 'biblioteca', '/ˈlaɪbrɛri/', 'Falso cognato: "library" = biblioteca; livraria é "bookstore".', '[]'::jsonb, '[{"surface":"library","pos":"noun","ipa":"/ˈlaɪbrɛri/","gloss":"biblioteca"}]'::jsonb, 'I study at the library.', 'Estudo na biblioteca.'),
  ('unit-1000-words-a1-14-06', 'lesson-1000-words-a1-14', 6, 'word', 'church', 'igreja', '/tʃɜːrtʃ/', NULL, '[]'::jsonb, '[{"surface":"church","pos":"noun","ipa":"/tʃɜːrtʃ/","gloss":"igreja"}]'::jsonb, 'The old church is beautiful.', 'A igreja antiga é linda.'),
  ('unit-1000-words-a1-14-07', 'lesson-1000-words-a1-14', 7, 'word', 'school', 'escola', '/skuːl/', '"Go to school" sem artigo quando é para estudar.', '[]'::jsonb, '[{"surface":"school","pos":"noun","ipa":"/skuːl/","gloss":"escola"}]'::jsonb, 'My kids walk to school.', 'Meus filhos vão a pé para a escola.'),
  ('unit-1000-words-a1-14-08', 'lesson-1000-words-a1-14', 8, 'word', 'market', 'mercado, feira', '/ˈmɑːrkɪt/', NULL, '[]'::jsonb, '[{"surface":"market","pos":"noun","ipa":"/ˈmɑːrkɪt/","gloss":"mercado, feira"}]'::jsonb, 'I buy fruit at the market.', 'Compro fruta na feira.'),
  ('unit-1000-words-a1-14-09', 'lesson-1000-words-a1-14', 9, 'word', 'supermarket', 'supermercado', '/ˈsuːpərmɑːrkɪt/', NULL, '[]'::jsonb, '[{"surface":"supermarket","pos":"noun","ipa":"/ˈsuːpərmɑːrkɪt/","gloss":"supermercado"}]'::jsonb, 'The supermarket opens at eight.', 'O supermercado abre às oito.'),
  ('unit-1000-words-a1-14-10', 'lesson-1000-words-a1-14', 10, 'word', 'mall', 'shopping', '/mɔːl/', '"Shopping" em inglês é o ato de fazer compras, não o lugar.', '[]'::jsonb, '[{"surface":"mall","pos":"noun","ipa":"/mɔːl/","gloss":"shopping"}]'::jsonb, 'Let''s meet at the mall.', 'Vamos nos encontrar no shopping.'),
  ('unit-1000-words-a1-14-11', 'lesson-1000-words-a1-14', 11, 'word', 'restaurant', 'restaurante', '/ˈrɛstərɑːnt/', NULL, '[]'::jsonb, '[{"surface":"restaurant","pos":"noun","ipa":"/ˈrɛstərɑːnt/","gloss":"restaurante"}]'::jsonb, 'This restaurant is always full.', 'Este restaurante está sempre cheio.'),
  ('unit-1000-words-a1-14-12', 'lesson-1000-words-a1-14', 12, 'word', 'bakery', 'padaria', '/ˈbeɪkəri/', NULL, '[]'::jsonb, '[{"surface":"bakery","pos":"noun","ipa":"/ˈbeɪkəri/","gloss":"padaria"}]'::jsonb, 'The bakery has fresh bread.', 'A padaria tem pão fresco.'),
  ('unit-1000-words-a1-14-13', 'lesson-1000-words-a1-14', 13, 'word', 'post office', 'correio', '/poʊst ˈɔːfɪs/', NULL, '[]'::jsonb, '[{"surface":"post","pos":"noun","ipa":"/poʊst/","gloss":"correio"},{"surface":"office","pos":"noun","ipa":"/ˈɔːfɪs/","gloss":"escritório, balcão"}]'::jsonb, 'Where is the post office?', 'Onde fica o correio?'),
  ('unit-1000-words-a1-14-14', 'lesson-1000-words-a1-14', 14, 'word', 'bridge', 'ponte', '/brɪdʒ/', NULL, '[]'::jsonb, '[{"surface":"bridge","pos":"noun","ipa":"/brɪdʒ/","gloss":"ponte"}]'::jsonb, 'Cross the bridge and turn left.', 'Atravesse a ponte e vire à esquerda.'),
  ('unit-1000-words-a1-14-15', 'lesson-1000-words-a1-14', 15, 'word', 'downtown', 'centro', '/ˌdaʊnˈtaʊn/', 'Nos EUA, "downtown" sem preposição: "go downtown".', '[]'::jsonb, '[{"surface":"downtown","pos":"noun","ipa":"/ˌdaʊnˈtaʊn/","gloss":"centro da cidade"}]'::jsonb, 'The hotel is downtown.', 'O hotel fica no centro.'),
  ('unit-1000-words-a1-14-16', 'lesson-1000-words-a1-14', 16, 'word', 'neighborhood', 'bairro', '/ˈneɪbərhʊd/', 'Reino Unido: "neighbourhood".', '[]'::jsonb, '[{"surface":"neighborhood","pos":"noun","ipa":"/ˈneɪbərhʊd/","gloss":"bairro"}]'::jsonb, 'It is a quiet neighborhood.', 'É um bairro tranquilo.'),
  ('unit-1000-words-a1-14-17', 'lesson-1000-words-a1-14', 17, 'word', 'sidewalk', 'calçada', '/ˈsaɪdwɔːk/', 'Reino Unido: "pavement".', '[]'::jsonb, '[{"surface":"sidewalk","pos":"noun","ipa":"/ˈsaɪdwɔːk/","gloss":"calçada"}]'::jsonb, 'Walk on the sidewalk.', 'Ande na calçada.'),
  ('unit-1000-words-a1-14-18', 'lesson-1000-words-a1-14', 18, 'word', 'corner', 'esquina', '/ˈkɔːrnər/', '"On the corner" = na esquina.', '[]'::jsonb, '[{"surface":"corner","pos":"noun","ipa":"/ˈkɔːrnər/","gloss":"esquina"}]'::jsonb, 'The bank is on the corner.', 'O banco fica na esquina.'),
  ('unit-1000-words-a1-14-19', 'lesson-1000-words-a1-14', 19, 'word', 'town', 'cidade pequena', '/taʊn/', '"Town" é menor que "city".', '[]'::jsonb, '[{"surface":"town","pos":"noun","ipa":"/taʊn/","gloss":"cidade pequena"}]'::jsonb, 'I grew up in a small town.', 'Cresci numa cidade pequena.'),
  ('unit-1000-words-a1-14-20', 'lesson-1000-words-a1-14', 20, 'word', 'city', 'cidade', '/ˈsɪti/', NULL, '[]'::jsonb, '[{"surface":"city","pos":"noun","ipa":"/ˈsɪti/","gloss":"cidade"}]'::jsonb, 'New York is a big city.', 'Nova York é uma cidade grande.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-15', 'course-1000-words-a1', 15, 'Transporte', 'Como se locomover e o vocabulário de quem viaja.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-15-01', 'lesson-1000-words-a1-15', 1, 'word', 'car', 'carro', '/kɑːr/', '"By car", "by bus", "by train": meio de transporte com "by". A pé é "on foot".', '[]'::jsonb, '[{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"}]'::jsonb, 'I go to work by car.', 'Vou para o trabalho de carro.'),
  ('unit-1000-words-a1-15-02', 'lesson-1000-words-a1-15', 2, 'word', 'bus', 'ônibus', '/bʌs/', NULL, '[]'::jsonb, '[{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"}]'::jsonb, 'The bus is late again.', 'O ônibus atrasou de novo.'),
  ('unit-1000-words-a1-15-03', 'lesson-1000-words-a1-15', 3, 'word', 'subway', 'metrô', '/ˈsʌbweɪ/', 'EUA: "subway"; Londres: "the Underground" ou "the Tube".', '[]'::jsonb, '[{"surface":"subway","pos":"noun","ipa":"/ˈsʌbweɪ/","gloss":"metrô"}]'::jsonb, 'Take the subway to downtown.', 'Pegue o metrô até o centro.'),
  ('unit-1000-words-a1-15-04', 'lesson-1000-words-a1-15', 4, 'word', 'train', 'trem', '/treɪn/', NULL, '[]'::jsonb, '[{"surface":"train","pos":"noun","ipa":"/treɪn/","gloss":"trem"}]'::jsonb, 'The train leaves at noon.', 'O trem sai ao meio-dia.'),
  ('unit-1000-words-a1-15-05', 'lesson-1000-words-a1-15', 5, 'word', 'plane', 'avião', '/pleɪn/', NULL, '[]'::jsonb, '[{"surface":"plane","pos":"noun","ipa":"/pleɪn/","gloss":"avião"}]'::jsonb, 'The plane is full.', 'O avião está lotado.'),
  ('unit-1000-words-a1-15-06', 'lesson-1000-words-a1-15', 6, 'word', 'bike', 'bicicleta', '/baɪk/', 'Bicicleta e moto usam "ride", não "drive".', '[]'::jsonb, '[{"surface":"bike","pos":"noun","ipa":"/baɪk/","gloss":"bicicleta"}]'::jsonb, 'I ride my bike to work.', 'Vou de bicicleta para o trabalho.'),
  ('unit-1000-words-a1-15-07', 'lesson-1000-words-a1-15', 7, 'word', 'motorcycle', 'moto', '/ˈmoʊtərsaɪkəl/', NULL, '[]'::jsonb, '[{"surface":"motorcycle","pos":"noun","ipa":"/ˈmoʊtərsaɪkəl/","gloss":"moto"}]'::jsonb, 'He has a red motorcycle.', 'Ele tem uma moto vermelha.'),
  ('unit-1000-words-a1-15-08', 'lesson-1000-words-a1-15', 8, 'word', 'taxi', 'táxi', '/ˈtæksi/', NULL, '[]'::jsonb, '[{"surface":"taxi","pos":"noun","ipa":"/ˈtæksi/","gloss":"táxi"}]'::jsonb, 'Let''s take a taxi.', 'Vamos pegar um táxi.'),
  ('unit-1000-words-a1-15-09', 'lesson-1000-words-a1-15', 9, 'word', 'truck', 'caminhão', '/trʌk/', NULL, '[]'::jsonb, '[{"surface":"truck","pos":"noun","ipa":"/trʌk/","gloss":"caminhão"}]'::jsonb, 'A truck is blocking the road.', 'Um caminhão está bloqueando a rua.'),
  ('unit-1000-words-a1-15-10', 'lesson-1000-words-a1-15', 10, 'word', 'ship', 'navio', '/ʃɪp/', NULL, '[]'::jsonb, '[{"surface":"ship","pos":"noun","ipa":"/ʃɪp/","gloss":"navio"}]'::jsonb, 'The ship arrives tomorrow.', 'O navio chega amanhã.'),
  ('unit-1000-words-a1-15-11', 'lesson-1000-words-a1-15', 11, 'word', 'station', 'estação', '/ˈsteɪʃən/', NULL, '[]'::jsonb, '[{"surface":"station","pos":"noun","ipa":"/ˈsteɪʃən/","gloss":"estação"}]'::jsonb, 'Meet me at the station.', 'Me encontra na estação.'),
  ('unit-1000-words-a1-15-12', 'lesson-1000-words-a1-15', 12, 'word', 'stop', 'parada, ponto', '/stɑːp/', NULL, '[]'::jsonb, '[{"surface":"stop","pos":"noun","ipa":"/stɑːp/","gloss":"parada, ponto"}]'::jsonb, 'Get off at the next stop.', 'Desça na próxima parada.'),
  ('unit-1000-words-a1-15-13', 'lesson-1000-words-a1-15', 13, 'word', 'ticket', 'passagem, bilhete', '/ˈtɪkɪt/', NULL, '[]'::jsonb, '[{"surface":"ticket","pos":"noun","ipa":"/ˈtɪkɪt/","gloss":"passagem, bilhete"}]'::jsonb, 'Buy your ticket online.', 'Compre sua passagem pela internet.'),
  ('unit-1000-words-a1-15-14', 'lesson-1000-words-a1-15', 14, 'word', 'seat', 'assento', '/siːt/', NULL, '[]'::jsonb, '[{"surface":"seat","pos":"noun","ipa":"/siːt/","gloss":"assento"}]'::jsonb, 'Is this seat free?', 'Este assento está livre?'),
  ('unit-1000-words-a1-15-15', 'lesson-1000-words-a1-15', 15, 'word', 'driver', 'motorista', '/ˈdraɪvər/', NULL, '[]'::jsonb, '[{"surface":"driver","pos":"noun","ipa":"/ˈdraɪvər/","gloss":"motorista"}]'::jsonb, 'The driver was very kind.', 'O motorista foi muito gentil.'),
  ('unit-1000-words-a1-15-16', 'lesson-1000-words-a1-15', 16, 'word', 'passenger', 'passageiro', '/ˈpæsɪndʒər/', NULL, '[]'::jsonb, '[{"surface":"passenger","pos":"noun","ipa":"/ˈpæsɪndʒər/","gloss":"passageiro"}]'::jsonb, 'All passengers must wear a seat belt.', 'Todos os passageiros devem usar cinto.'),
  ('unit-1000-words-a1-15-17', 'lesson-1000-words-a1-15', 17, 'word', 'highway', 'rodovia', '/ˈhaɪweɪ/', NULL, '[]'::jsonb, '[{"surface":"highway","pos":"noun","ipa":"/ˈhaɪweɪ/","gloss":"rodovia"}]'::jsonb, 'Take the highway to the airport.', 'Pegue a rodovia até o aeroporto.'),
  ('unit-1000-words-a1-15-18', 'lesson-1000-words-a1-15', 18, 'word', 'fare', 'tarifa', '/fɛr/', '"Fare" = preço da passagem; "fair" = justo (mesmo som).', '[]'::jsonb, '[{"surface":"fare","pos":"noun","ipa":"/fɛr/","gloss":"tarifa, passagem"}]'::jsonb, 'The bus fare is two dollars.', 'A passagem de ônibus custa dois dólares.'),
  ('unit-1000-words-a1-15-19', 'lesson-1000-words-a1-15', 19, 'word', 'ride', 'carona, corrida', '/raɪd/', '"Give someone a ride" = dar carona.', '[]'::jsonb, '[{"surface":"ride","pos":"noun","ipa":"/raɪd/","gloss":"carona, corrida"}]'::jsonb, 'Can you give me a ride?', 'Você me dá uma carona?'),
  ('unit-1000-words-a1-15-20', 'lesson-1000-words-a1-15', 20, 'word', 'walk', 'andar a pé', '/wɔːk/', NULL, '[]'::jsonb, '[{"surface":"walk","pos":"verb","ipa":"/wɔːk/","gloss":"andar, caminhar"}]'::jsonb, 'It''s close, we can walk.', 'É perto, dá para ir a pé.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-16', 'course-1000-words-a1', 16, 'Clima e natureza', 'Falar do tempo, das estações e da paisagem.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-16-01', 'lesson-1000-words-a1-16', 1, 'word', 'weather', 'tempo, clima', '/ˈwɛðər/', '"Weather" = tempo do dia; "climate" = clima da região. Incontável.', '[]'::jsonb, '[{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"}]'::jsonb, 'How''s the weather today?', 'Como está o tempo hoje?'),
  ('unit-1000-words-a1-16-02', 'lesson-1000-words-a1-16', 2, 'word', 'sun', 'sol', '/sʌn/', NULL, '[]'::jsonb, '[{"surface":"sun","pos":"noun","ipa":"/sʌn/","gloss":"sol"}]'::jsonb, 'The sun is strong today.', 'O sol está forte hoje.'),
  ('unit-1000-words-a1-16-03', 'lesson-1000-words-a1-16', 3, 'word', 'sunny', 'ensolarado', '/ˈsʌni/', 'Clima usa "it''s" + adjetivo: sunny, cloudy, windy, rainy.', '[]'::jsonb, '[{"surface":"sunny","pos":"adjective","ipa":"/ˈsʌni/","gloss":"ensolarado"}]'::jsonb, 'It''s sunny outside.', 'Está ensolarado lá fora.'),
  ('unit-1000-words-a1-16-04', 'lesson-1000-words-a1-16', 4, 'word', 'cloudy', 'nublado', '/ˈklaʊdi/', NULL, '[]'::jsonb, '[{"surface":"cloudy","pos":"adjective","ipa":"/ˈklaʊdi/","gloss":"nublado"}]'::jsonb, 'It''s cloudy, take an umbrella.', 'Está nublado, leve um guarda-chuva.'),
  ('unit-1000-words-a1-16-05', 'lesson-1000-words-a1-16', 5, 'word', 'rainy', 'chuvoso', '/ˈreɪni/', NULL, '[]'::jsonb, '[{"surface":"rainy","pos":"adjective","ipa":"/ˈreɪni/","gloss":"chuvoso"}]'::jsonb, 'It was a rainy day.', 'Foi um dia chuvoso.'),
  ('unit-1000-words-a1-16-06', 'lesson-1000-words-a1-16', 6, 'word', 'windy', 'ventando', '/ˈwɪndi/', NULL, '[]'::jsonb, '[{"surface":"windy","pos":"adjective","ipa":"/ˈwɪndi/","gloss":"ventando"}]'::jsonb, 'It''s very windy at the beach.', 'Está ventando muito na praia.'),
  ('unit-1000-words-a1-16-07', 'lesson-1000-words-a1-16', 7, 'word', 'storm', 'tempestade', '/stɔːrm/', NULL, '[]'::jsonb, '[{"surface":"storm","pos":"noun","ipa":"/stɔːrm/","gloss":"tempestade"}]'::jsonb, 'A storm is coming.', 'Vem uma tempestade aí.'),
  ('unit-1000-words-a1-16-08', 'lesson-1000-words-a1-16', 8, 'word', 'snow', 'neve', '/snoʊ/', NULL, '[]'::jsonb, '[{"surface":"snow","pos":"verb","ipa":"/snoʊ/","gloss":"nevar; neve"}]'::jsonb, 'There is snow on the mountains.', 'Tem neve nas montanhas.'),
  ('unit-1000-words-a1-16-09', 'lesson-1000-words-a1-16', 9, 'word', 'hot', 'quente', '/hɑːt/', NULL, '[]'::jsonb, '[{"surface":"hot","pos":"adjective","ipa":"/hɑːt/","gloss":"quente"}]'::jsonb, 'It''s too hot today.', 'Está quente demais hoje.'),
  ('unit-1000-words-a1-16-10', 'lesson-1000-words-a1-16', 10, 'word', 'warm', 'agradável, morno', '/wɔːrm/', '"Warm" é um calor gostoso; "hot" é calor forte.', '[]'::jsonb, '[{"surface":"warm","pos":"adjective","ipa":"/wɔːrm/","gloss":"quente, morno"}]'::jsonb, 'It''s warm in the afternoon.', 'Fica agradável à tarde.'),
  ('unit-1000-words-a1-16-11', 'lesson-1000-words-a1-16', 11, 'word', 'cool', 'fresco', '/kuːl/', 'Também é gíria: "cool" = legal.', '[]'::jsonb, '[{"surface":"cool","pos":"adjective","ipa":"/kuːl/","gloss":"fresco; legal"}]'::jsonb, 'The nights are cool here.', 'As noites são frescas aqui.'),
  ('unit-1000-words-a1-16-12', 'lesson-1000-words-a1-16', 12, 'word', 'cold', 'frio', '/koʊld/', NULL, '[]'::jsonb, '[{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"}]'::jsonb, 'It''s cold, wear a coat.', 'Está frio, use um casaco.'),
  ('unit-1000-words-a1-16-13', 'lesson-1000-words-a1-16', 13, 'word', 'degrees', 'graus', '/dɪˈɡriːz/', 'Nos EUA a temperatura é em Fahrenheit: 86°F ≈ 30°C.', '[]'::jsonb, '[{"surface":"degrees","pos":"noun","ipa":"/dɪˈɡriːz/","gloss":"graus"}]'::jsonb, 'It''s thirty degrees today.', 'Está trinta graus hoje.'),
  ('unit-1000-words-a1-16-14', 'lesson-1000-words-a1-16', 14, 'word', 'forecast', 'previsão do tempo', '/ˈfɔːrkæst/', NULL, '[]'::jsonb, '[{"surface":"forecast","pos":"noun","ipa":"/ˈfɔːrkæst/","gloss":"previsão do tempo"}]'::jsonb, 'The forecast says rain.', 'A previsão diz chuva.'),
  ('unit-1000-words-a1-16-15', 'lesson-1000-words-a1-16', 15, 'word', 'summer', 'verão', '/ˈsʌmər/', 'Estações sem artigo: "in summer" ou "in the summer".', '[]'::jsonb, '[{"surface":"summer","pos":"noun","ipa":"/ˈsʌmər/","gloss":"verão"}]'::jsonb, 'We go to the beach every summer.', 'Vamos à praia todo verão.'),
  ('unit-1000-words-a1-16-16', 'lesson-1000-words-a1-16', 16, 'word', 'winter', 'inverno', '/ˈwɪntər/', NULL, '[]'::jsonb, '[{"surface":"winter","pos":"noun","ipa":"/ˈwɪntər/","gloss":"inverno"}]'::jsonb, 'Winter is very cold there.', 'O inverno é muito frio lá.'),
  ('unit-1000-words-a1-16-17', 'lesson-1000-words-a1-16', 17, 'word', 'fall', 'outono', '/fɔːl/', 'EUA: "fall"; Reino Unido: "autumn".', '[]'::jsonb, '[{"surface":"fall","pos":"noun","ipa":"/fɔːl/","gloss":"outono"}]'::jsonb, 'The leaves change color in fall.', 'As folhas mudam de cor no outono.'),
  ('unit-1000-words-a1-16-18', 'lesson-1000-words-a1-16', 18, 'word', 'sky', 'céu', '/skaɪ/', NULL, '[]'::jsonb, '[{"surface":"sky","pos":"noun","ipa":"/skaɪ/","gloss":"céu"}]'::jsonb, 'The sky is clear tonight.', 'O céu está limpo hoje à noite.'),
  ('unit-1000-words-a1-16-19', 'lesson-1000-words-a1-16', 19, 'word', 'river', 'rio', '/ˈrɪvər/', NULL, '[]'::jsonb, '[{"surface":"river","pos":"noun","ipa":"/ˈrɪvər/","gloss":"rio"}]'::jsonb, 'We swam in the river.', 'Nadamos no rio.'),
  ('unit-1000-words-a1-16-20', 'lesson-1000-words-a1-16', 20, 'word', 'mountain', 'montanha', '/ˈmaʊntən/', NULL, '[]'::jsonb, '[{"surface":"mountain","pos":"noun","ipa":"/ˈmaʊntən/","gloss":"montanha"}]'::jsonb, 'We climbed the mountain.', 'Subimos a montanha.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
