-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-1000-words-a1', '1000-essential-words', '1000 Palavras Essenciais', 'As palavras mais usadas do inglês, por tema, com significado e frase de exemplo.', 'Vocabulário essencial organizado por temas do dia a dia. Você ouve, escreve a palavra e vê como ela aparece numa frase real.', 'A1', 'grammar', 11, 'fundamentos', 2, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-20', 'course-1000-words-a1', 20, 'Trabalho e profissões', 'Profissões e o vocabulário básico do emprego.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-20-01', 'lesson-1000-words-a1-20', 1, 'word', 'job', 'emprego', '/dʒɑːb/', '"Job" é contável (a job); "work" é incontável (a atividade).', '[]'::jsonb, '[{"surface":"job","pos":"noun","ipa":"/dʒɑːb/","gloss":"emprego, trabalho"}]'::jsonb, 'I have a new job.', 'Tenho um emprego novo.'),
  ('unit-1000-words-a1-20-02', 'lesson-1000-words-a1-20', 2, 'word', 'work', 'trabalho', '/wɜːrk/', NULL, '[]'::jsonb, '[{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, 'I have a lot of work today.', 'Tenho muito trabalho hoje.'),
  ('unit-1000-words-a1-20-03', 'lesson-1000-words-a1-20', 3, 'word', 'teacher', 'professor', '/ˈtiːtʃər/', 'Profissão sempre com "a/an": "she is a teacher".', '[]'::jsonb, '[{"surface":"teacher","pos":"noun","ipa":"/ˈtiːtʃər/","gloss":"professor, professora"}]'::jsonb, 'My mother is a teacher.', 'Minha mãe é professora.'),
  ('unit-1000-words-a1-20-04', 'lesson-1000-words-a1-20', 4, 'word', 'doctor', 'médico', '/ˈdɑːktər/', NULL, '[]'::jsonb, '[{"surface":"doctor","pos":"noun","ipa":"/ˈdɑːktər/","gloss":"médico"}]'::jsonb, 'You should see a doctor.', 'Você deveria ir ao médico.'),
  ('unit-1000-words-a1-20-05', 'lesson-1000-words-a1-20', 5, 'word', 'nurse', 'enfermeiro', '/nɜːrs/', NULL, '[]'::jsonb, '[{"surface":"nurse","pos":"noun","ipa":"/nɜːrs/","gloss":"enfermeiro"}]'::jsonb, 'The nurse was very kind.', 'A enfermeira foi muito gentil.'),
  ('unit-1000-words-a1-20-06', 'lesson-1000-words-a1-20', 6, 'word', 'lawyer', 'advogado', '/ˈlɔːjər/', NULL, '[]'::jsonb, '[{"surface":"lawyer","pos":"noun","ipa":"/ˈlɔːjər/","gloss":"advogado"}]'::jsonb, 'I need to talk to a lawyer.', 'Preciso falar com um advogado.'),
  ('unit-1000-words-a1-20-07', 'lesson-1000-words-a1-20', 7, 'word', 'engineer', 'engenheiro', '/ˌɛndʒɪˈnɪr/', '"Work as" + profissão.', '[]'::jsonb, '[{"surface":"engineer","pos":"noun","ipa":"/ˌɛndʒɪˈnɪr/","gloss":"engenheiro"}]'::jsonb, 'He works as an engineer.', 'Ele trabalha como engenheiro.'),
  ('unit-1000-words-a1-20-08', 'lesson-1000-words-a1-20', 8, 'word', 'cook', 'cozinheiro', '/kʊk/', '"Cook" é a pessoa; "cooker" é o fogão (Reino Unido).', '[]'::jsonb, '[{"surface":"cook","pos":"noun","ipa":"/kʊk/","gloss":"cozinheiro"}]'::jsonb, 'My dad is a great cook.', 'Meu pai cozinha muito bem.'),
  ('unit-1000-words-a1-20-09', 'lesson-1000-words-a1-20', 9, 'word', 'waiter', 'garçom', '/ˈweɪtər/', 'Garçonete: "waitress". Neutro: "server".', '[]'::jsonb, '[{"surface":"waiter","pos":"noun","ipa":"/ˈweɪtər/","gloss":"garçom"}]'::jsonb, 'The waiter brought the menu.', 'O garçom trouxe o cardápio.'),
  ('unit-1000-words-a1-20-10', 'lesson-1000-words-a1-20', 10, 'word', 'salesperson', 'vendedor', '/ˈseɪlzpɜːrsən/', NULL, '[]'::jsonb, '[{"surface":"salesperson","pos":"noun","ipa":"/ˈseɪlzpɜːrsən/","gloss":"vendedor"}]'::jsonb, 'Ask the salesperson for help.', 'Peça ajuda ao vendedor.'),
  ('unit-1000-words-a1-20-11', 'lesson-1000-words-a1-20', 11, 'word', 'driver', 'motorista', '/ˈdraɪvər/', NULL, '[]'::jsonb, '[{"surface":"driver","pos":"noun","ipa":"/ˈdraɪvər/","gloss":"motorista"}]'::jsonb, 'He is a truck driver.', 'Ele é caminhoneiro.'),
  ('unit-1000-words-a1-20-12', 'lesson-1000-words-a1-20', 12, 'word', 'manager', 'gerente', '/ˈmænɪdʒər/', NULL, '[]'::jsonb, '[{"surface":"manager","pos":"noun","ipa":"/ˈmænɪdʒər/","gloss":"gerente"}]'::jsonb, 'I want to speak to the manager.', 'Quero falar com o gerente.'),
  ('unit-1000-words-a1-20-13', 'lesson-1000-words-a1-20', 13, 'word', 'boss', 'chefe', '/bɔːs/', NULL, '[]'::jsonb, '[{"surface":"boss","pos":"noun","ipa":"/bɔːs/","gloss":"chefe"}]'::jsonb, 'My boss is on vacation.', 'Meu chefe está de férias.'),
  ('unit-1000-words-a1-20-14', 'lesson-1000-words-a1-20', 14, 'word', 'employee', 'funcionário', '/ɪmˈplɔɪiː/', NULL, '[]'::jsonb, '[{"surface":"employee","pos":"noun","ipa":"/ɪmˈplɔɪiː/","gloss":"funcionário"}]'::jsonb, 'The company has fifty employees.', 'A empresa tem cinquenta funcionários.'),
  ('unit-1000-words-a1-20-15', 'lesson-1000-words-a1-20', 15, 'word', 'salary', 'salário', '/ˈsæləri/', NULL, '[]'::jsonb, '[{"surface":"salary","pos":"noun","ipa":"/ˈsæləri/","gloss":"salário"}]'::jsonb, 'The salary is good.', 'O salário é bom.'),
  ('unit-1000-words-a1-20-16', 'lesson-1000-words-a1-20', 16, 'word', 'office', 'escritório', '/ˈɔːfɪs/', NULL, '[]'::jsonb, '[{"surface":"office","pos":"noun","ipa":"/ˈɔːfɪs/","gloss":"escritório"}]'::jsonb, 'I work in an office.', 'Trabalho num escritório.'),
  ('unit-1000-words-a1-20-17', 'lesson-1000-words-a1-20', 17, 'word', 'interview', 'entrevista', '/ˈɪntərvjuː/', NULL, '[]'::jsonb, '[{"surface":"interview","pos":"noun","ipa":"/ˈɪntərvjuː/","gloss":"entrevista"}]'::jsonb, 'I have a job interview tomorrow.', 'Tenho uma entrevista de emprego amanhã.'),
  ('unit-1000-words-a1-20-18', 'lesson-1000-words-a1-20', 18, 'word', 'meeting', 'reunião', '/ˈmiːtɪŋ/', NULL, '[]'::jsonb, '[{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"}]'::jsonb, 'The meeting starts at ten.', 'A reunião começa às dez.'),
  ('unit-1000-words-a1-20-19', 'lesson-1000-words-a1-20', 19, 'word', 'retired', 'aposentado', '/rɪˈtaɪərd/', NULL, '[]'::jsonb, '[{"surface":"retired","pos":"adjective","ipa":"/rɪˈtaɪərd/","gloss":"aposentado"}]'::jsonb, 'My grandfather is retired.', 'Meu avô é aposentado.'),
  ('unit-1000-words-a1-20-20', 'lesson-1000-words-a1-20', 20, 'word', 'unemployed', 'desempregado', '/ˌʌnɪmˈplɔɪd/', NULL, '[]'::jsonb, '[{"surface":"unemployed","pos":"adjective","ipa":"/ˌʌnɪmˈplɔɪd/","gloss":"desempregado"}]'::jsonb, 'He has been unemployed for months.', 'Ele está desempregado há meses.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-21', 'course-1000-words-a1', 21, 'Escola e estudo', 'Aulas, provas, matérias e material escolar.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-21-01', 'lesson-1000-words-a1-21', 1, 'word', 'school', 'escola', '/skuːl/', NULL, '[]'::jsonb, '[{"surface":"school","pos":"noun","ipa":"/skuːl/","gloss":"escola"}]'::jsonb, 'The kids are at school.', 'As crianças estão na escola.'),
  ('unit-1000-words-a1-21-02', 'lesson-1000-words-a1-21', 2, 'word', 'university', 'universidade', '/ˌjuːnɪˈvɜːrsəti/', 'Começa com som de "iu": "a university" (não "an").', '[]'::jsonb, '[{"surface":"university","pos":"noun","ipa":"/ˌjuːnɪˈvɜːrsəti/","gloss":"universidade"}]'::jsonb, 'She studies at the university.', 'Ela estuda na universidade.'),
  ('unit-1000-words-a1-21-03', 'lesson-1000-words-a1-21', 3, 'word', 'class', 'aula, turma', '/klæs/', NULL, '[]'::jsonb, '[{"surface":"class","pos":"noun","ipa":"/klæs/","gloss":"aula, turma"}]'::jsonb, 'I have class at eight.', 'Tenho aula às oito.'),
  ('unit-1000-words-a1-21-04', 'lesson-1000-words-a1-21', 4, 'word', 'lesson', 'aula, lição', '/ˈlɛsən/', NULL, '[]'::jsonb, '[{"surface":"lesson","pos":"noun","ipa":"/ˈlɛsən/","gloss":"aula, lição"}]'::jsonb, 'Today''s lesson is about verbs.', 'A aula de hoje é sobre verbos.'),
  ('unit-1000-words-a1-21-05', 'lesson-1000-words-a1-21', 5, 'word', 'student', 'aluno', '/ˈstuːdənt/', NULL, '[]'::jsonb, '[{"surface":"student","pos":"noun","ipa":"/ˈstuːdənt/","gloss":"estudante"}]'::jsonb, 'There are twenty students in the class.', 'Tem vinte alunos na turma.'),
  ('unit-1000-words-a1-21-06', 'lesson-1000-words-a1-21', 6, 'word', 'teacher', 'professor', '/ˈtiːtʃər/', NULL, '[]'::jsonb, '[{"surface":"teacher","pos":"noun","ipa":"/ˈtiːtʃər/","gloss":"professor, professora"}]'::jsonb, 'Ask the teacher.', 'Pergunte ao professor.'),
  ('unit-1000-words-a1-21-07', 'lesson-1000-words-a1-21', 7, 'word', 'classroom', 'sala de aula', '/ˈklæsruːm/', NULL, '[]'::jsonb, '[{"surface":"classroom","pos":"noun","ipa":"/ˈklæsruːm/","gloss":"sala de aula"}]'::jsonb, 'The classroom is on the second floor.', 'A sala de aula fica no segundo andar.'),
  ('unit-1000-words-a1-21-08', 'lesson-1000-words-a1-21', 8, 'word', 'book', 'livro', '/bʊk/', NULL, '[]'::jsonb, '[{"surface":"book","pos":"verb","ipa":"/bʊk/","gloss":"reservar; livro"}]'::jsonb, 'Open your books, please.', 'Abram os livros, por favor.'),
  ('unit-1000-words-a1-21-09', 'lesson-1000-words-a1-21', 9, 'word', 'notebook', 'caderno', '/ˈnoʊtbʊk/', NULL, '[]'::jsonb, '[{"surface":"notebook","pos":"noun","ipa":"/ˈnoʊtbʊk/","gloss":"caderno"}]'::jsonb, 'Write it in your notebook.', 'Escreva no caderno.'),
  ('unit-1000-words-a1-21-10', 'lesson-1000-words-a1-21', 10, 'word', 'pencil', 'lápis', '/ˈpɛnsəl/', NULL, '[]'::jsonb, '[{"surface":"pencil","pos":"noun","ipa":"/ˈpɛnsəl/","gloss":"lápis"}]'::jsonb, 'Can I borrow a pencil?', 'Posso pegar um lápis emprestado?'),
  ('unit-1000-words-a1-21-11', 'lesson-1000-words-a1-21', 11, 'word', 'exam', 'prova', '/ɪɡˈzæm/', '"Take an exam" = fazer prova.', '[]'::jsonb, '[{"surface":"exam","pos":"noun","ipa":"/ɪɡˈzæm/","gloss":"prova"}]'::jsonb, 'I have an exam on Friday.', 'Tenho prova na sexta.'),
  ('unit-1000-words-a1-21-12', 'lesson-1000-words-a1-21', 12, 'word', 'pass', 'passar', '/pæs/', 'Falso amigo: "pass an exam" = ser aprovado, não "fazer" a prova.', '[]'::jsonb, '[{"surface":"pass","pos":"verb","ipa":"/pæs/","gloss":"passar (em prova)"}]'::jsonb, 'I passed the exam!', 'Passei na prova!'),
  ('unit-1000-words-a1-21-13', 'lesson-1000-words-a1-21', 13, 'word', 'fail', 'reprovar', '/feɪl/', NULL, '[]'::jsonb, '[{"surface":"fail","pos":"verb","ipa":"/feɪl/","gloss":"reprovar, falhar"}]'::jsonb, 'He failed math.', 'Ele reprovou em matemática.'),
  ('unit-1000-words-a1-21-14', 'lesson-1000-words-a1-21', 14, 'word', 'grade', 'nota', '/ɡreɪd/', 'Nos EUA "grade" também é série escolar: "fifth grade".', '[]'::jsonb, '[{"surface":"grade","pos":"noun","ipa":"/ɡreɪd/","gloss":"nota; série"}]'::jsonb, 'I got a good grade.', 'Tirei uma nota boa.'),
  ('unit-1000-words-a1-21-15', 'lesson-1000-words-a1-21', 15, 'word', 'homework', 'lição de casa', '/ˈhoʊmwɜːrk/', 'Incontável: "homework" sem plural.', '[]'::jsonb, '[{"surface":"homework","pos":"noun","ipa":"/ˈhoʊmwɜːrk/","gloss":"lição de casa"}]'::jsonb, 'Did you do your homework?', 'Você fez a lição?'),
  ('unit-1000-words-a1-21-16', 'lesson-1000-words-a1-21', 16, 'word', 'subject', 'matéria', '/ˈsʌbdʒɪkt/', NULL, '[]'::jsonb, '[{"surface":"subject","pos":"noun","ipa":"/ˈsʌbdʒɪkt/","gloss":"matéria"}]'::jsonb, 'What is your favorite subject?', 'Qual é sua matéria favorita?'),
  ('unit-1000-words-a1-21-17', 'lesson-1000-words-a1-21', 17, 'word', 'math', 'matemática', '/mæθ/', 'Reino Unido: "maths".', '[]'::jsonb, '[{"surface":"math","pos":"noun","ipa":"/mæθ/","gloss":"matemática"}]'::jsonb, 'Math is my favorite subject.', 'Matemática é minha matéria favorita.'),
  ('unit-1000-words-a1-21-18', 'lesson-1000-words-a1-21', 18, 'word', 'history', 'história', '/ˈhɪstəri/', '"History" = a matéria/o passado; "story" = um conto.', '[]'::jsonb, '[{"surface":"history","pos":"noun","ipa":"/ˈhɪstəri/","gloss":"história"}]'::jsonb, 'I love history.', 'Adoro história.'),
  ('unit-1000-words-a1-21-19', 'lesson-1000-words-a1-21', 19, 'word', 'degree', 'diploma, graduação', '/dɪˈɡriː/', NULL, '[]'::jsonb, '[{"surface":"degree","pos":"noun","ipa":"/dɪˈɡriː/","gloss":"diploma, graduação"}]'::jsonb, 'She has a degree in law.', 'Ela é formada em direito.'),
  ('unit-1000-words-a1-21-20', 'lesson-1000-words-a1-21', 20, 'word', 'study', 'estudar', '/ˈstʌdi/', NULL, '[]'::jsonb, '[{"surface":"study","pos":"verb","ipa":"/ˈstʌdi/","gloss":"estudar"}]'::jsonb, 'I study every night.', 'Estudo toda noite.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-1000-words-a1-22', 'course-1000-words-a1', 22, 'Esportes e lazer', 'O que você faz no tempo livre.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-1000-words-a1-22-01', 'lesson-1000-words-a1-22', 1, 'word', 'soccer', 'futebol', '/ˈsɑːkər/', 'EUA: "soccer"; Reino Unido: "football". Nos EUA "football" é o futebol americano.', '[]'::jsonb, '[{"surface":"soccer","pos":"noun","ipa":"/ˈsɑːkər/","gloss":"futebol"}]'::jsonb, 'We play soccer on Sundays.', 'Jogamos futebol aos domingos.'),
  ('unit-1000-words-a1-22-02', 'lesson-1000-words-a1-22', 2, 'word', 'basketball', 'basquete', '/ˈbæskɪtbɔːl/', NULL, '[]'::jsonb, '[{"surface":"basketball","pos":"noun","ipa":"/ˈbæskɪtbɔːl/","gloss":"basquete"}]'::jsonb, 'He plays basketball at school.', 'Ele joga basquete na escola.'),
  ('unit-1000-words-a1-22-03', 'lesson-1000-words-a1-22', 3, 'word', 'volleyball', 'vôlei', '/ˈvɑːlibɔːl/', NULL, '[]'::jsonb, '[{"surface":"volleyball","pos":"noun","ipa":"/ˈvɑːlibɔːl/","gloss":"vôlei"}]'::jsonb, 'Beach volleyball is fun.', 'Vôlei de praia é divertido.'),
  ('unit-1000-words-a1-22-04', 'lesson-1000-words-a1-22', 4, 'word', 'tennis', 'tênis', '/ˈtɛnɪs/', 'Aqui "tennis" é o esporte; o calçado é "sneakers".', '[]'::jsonb, '[{"surface":"tennis","pos":"noun","ipa":"/ˈtɛnɪs/","gloss":"tênis (esporte)"}]'::jsonb, 'Do you play tennis?', 'Você joga tênis?'),
  ('unit-1000-words-a1-22-05', 'lesson-1000-words-a1-22', 5, 'word', 'swimming', 'natação', '/ˈswɪmɪŋ/', 'Esportes com "-ing" usam "go": "go swimming", "go running".', '[]'::jsonb, '[{"surface":"swimming","pos":"noun","ipa":"/ˈswɪmɪŋ/","gloss":"natação"}]'::jsonb, 'Swimming is good exercise.', 'Natação é um bom exercício.'),
  ('unit-1000-words-a1-22-06', 'lesson-1000-words-a1-22', 6, 'word', 'running', 'corrida', '/ˈrʌnɪŋ/', NULL, '[]'::jsonb, '[{"surface":"running","pos":"noun","ipa":"/ˈrʌnɪŋ/","gloss":"corrida"}]'::jsonb, 'I go running every morning.', 'Vou correr toda manhã.'),
  ('unit-1000-words-a1-22-07', 'lesson-1000-words-a1-22', 7, 'word', 'yoga', 'ioga', '/ˈjoʊɡə/', 'Atividades sem bola usam "do": "do yoga".', '[]'::jsonb, '[{"surface":"yoga","pos":"noun","ipa":"/ˈjoʊɡə/","gloss":"ioga"}]'::jsonb, 'She does yoga twice a week.', 'Ela faz ioga duas vezes por semana.'),
  ('unit-1000-words-a1-22-08', 'lesson-1000-words-a1-22', 8, 'word', 'gym', 'academia', '/dʒɪm/', NULL, '[]'::jsonb, '[{"surface":"gym","pos":"noun","ipa":"/dʒɪm/","gloss":"academia"}]'::jsonb, 'I go to the gym after work.', 'Vou à academia depois do trabalho.'),
  ('unit-1000-words-a1-22-09', 'lesson-1000-words-a1-22', 9, 'word', 'team', 'time', '/tiːm/', '"Support a team" = torcer por um time.', '[]'::jsonb, '[{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time"}]'::jsonb, 'Which team do you support?', 'Para qual time você torce?'),
  ('unit-1000-words-a1-22-10', 'lesson-1000-words-a1-22', 10, 'word', 'match', 'partida', '/mætʃ/', NULL, '[]'::jsonb, '[{"surface":"match","pos":"noun","ipa":"/mætʃ/","gloss":"partida"}]'::jsonb, 'The match starts at four.', 'A partida começa às quatro.'),
  ('unit-1000-words-a1-22-11', 'lesson-1000-words-a1-22', 11, 'word', 'win', 'ganhar', '/wɪn/', 'Passado irregular: "won" /wʌn/.', '[]'::jsonb, '[{"surface":"win","pos":"verb","ipa":"/wɪn/","gloss":"ganhar, vencer"}]'::jsonb, 'Our team won!', 'Nosso time ganhou!'),
  ('unit-1000-words-a1-22-12', 'lesson-1000-words-a1-22', 12, 'word', 'lose', 'perder', '/luːz/', '"Lose" /luːz/ (perder) × "loose" /luːs/ (solto).', '[]'::jsonb, '[{"surface":"lose","pos":"verb","ipa":"/luːz/","gloss":"perder"}]'::jsonb, 'Don''t lose hope.', 'Não perca a esperança.'),
  ('unit-1000-words-a1-22-13', 'lesson-1000-words-a1-22', 13, 'word', 'hobby', 'passatempo', '/ˈhɑːbi/', NULL, '[]'::jsonb, '[{"surface":"hobby","pos":"noun","ipa":"/ˈhɑːbi/","gloss":"hobby, passatempo"}]'::jsonb, 'Cooking is my hobby.', 'Cozinhar é meu passatempo.'),
  ('unit-1000-words-a1-22-14', 'lesson-1000-words-a1-22', 14, 'word', 'movie', 'filme', '/ˈmuːvi/', 'EUA: "movie"; Reino Unido: "film".', '[]'::jsonb, '[{"surface":"movie","pos":"noun","ipa":"/ˈmuːvi/","gloss":"filme"}]'::jsonb, 'Let''s watch a movie tonight.', 'Vamos ver um filme hoje à noite.'),
  ('unit-1000-words-a1-22-15', 'lesson-1000-words-a1-22', 15, 'word', 'concert', 'show', '/ˈkɑːnsərt/', '"Show" de música é "concert"; "show" em inglês é mais programa de TV ou espetáculo.', '[]'::jsonb, '[{"surface":"concert","pos":"noun","ipa":"/ˈkɑːnsərt/","gloss":"show"}]'::jsonb, 'We went to a concert.', 'Fomos a um show.'),
  ('unit-1000-words-a1-22-16', 'lesson-1000-words-a1-22', 16, 'word', 'camping', 'acampamento', '/ˈkæmpɪŋ/', NULL, '[]'::jsonb, '[{"surface":"camping","pos":"noun","ipa":"/ˈkæmpɪŋ/","gloss":"acampamento"}]'::jsonb, 'We go camping every summer.', 'Acampamos todo verão.'),
  ('unit-1000-words-a1-22-17', 'lesson-1000-words-a1-22', 17, 'word', 'hiking', 'trilha', '/ˈhaɪkɪŋ/', NULL, '[]'::jsonb, '[{"surface":"hiking","pos":"noun","ipa":"/ˈhaɪkɪŋ/","gloss":"trilha, caminhada"}]'::jsonb, 'I love hiking in the mountains.', 'Adoro fazer trilha nas montanhas.'),
  ('unit-1000-words-a1-22-18', 'lesson-1000-words-a1-22', 18, 'word', 'painting', 'pintura', '/ˈpeɪntɪŋ/', NULL, '[]'::jsonb, '[{"surface":"painting","pos":"noun","ipa":"/ˈpeɪntɪŋ/","gloss":"pintura"}]'::jsonb, 'Painting helps me relax.', 'Pintar me ajuda a relaxar.'),
  ('unit-1000-words-a1-22-19', 'lesson-1000-words-a1-22', 19, 'word', 'reading', 'leitura', '/ˈriːdɪŋ/', NULL, '[]'::jsonb, '[{"surface":"reading","pos":"noun","ipa":"/ˈriːdɪŋ/","gloss":"leitura"}]'::jsonb, 'Reading is my favorite hobby.', 'Ler é meu passatempo favorito.'),
  ('unit-1000-words-a1-22-20', 'lesson-1000-words-a1-22', 20, 'word', 'music', 'música', '/ˈmjuːzɪk/', '"Listen to" sempre com "to".', '[]'::jsonb, '[{"surface":"music","pos":"noun","ipa":"/ˈmjuːzɪk/","gloss":"música"}]'::jsonb, 'I listen to music every day.', 'Escuto música todo dia.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
