-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-travel-a2', 'travel-no-stress-a2', 'Viagem sem Aperto', 'Aeroporto, avião, imigração, hotel, transporte, carro, compras, restaurante, farmácia e emergências: as frases que você realmente precisa na viagem.', 'Situações de viagem com o que você diz e o que ouve do outro lado: aeroporto e imigração, táxi, trem e carro alugado, hotel, compras, restaurante e café, farmácia, direções e emergências.', 'A2', 'travel', 2, 'viagem', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-16', 'course-travel-a2', 16, 'Táxi e aplicativo', 'Combinar o ponto de encontro, falar com o motorista e pagar.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-16-01', 'lesson-travel-a2-16', 1, 'sentence', 'I''m waiting at the main entrance.', 'Estou esperando na entrada principal.', '/aɪm ˈweɪtɪŋ æt ðə meɪn ˈɛntrəns/', 'Diga onde está para o motorista do aplicativo. "Main entrance" = entrada principal.', '[{"start":0,"end":11,"role":"predicate_verb","surface":"I''m waiting"},{"start":12,"end":33,"role":"adverbial","surface":"at the main entrance."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"main","pos":"adjective","ipa":"/meɪn/","gloss":"principal"},{"surface":"entrance","pos":"noun","ipa":"/ˈɛntrəns/","gloss":"entrada"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-02', 'lesson-travel-a2-16', 2, 'sentence', 'Are you here for Ana?', 'Você veio buscar a Ana?', '/ɑːr juː hɪr fɔːr ˈænə/', 'Confirme o nome antes de entrar no carro.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Are"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"adverbial","surface":"here"},{"start":13,"end":21,"role":"adverbial","surface":"for Ana?"}]'::jsonb, '[{"surface":"Are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"Ana","pos":"proper noun","ipa":"/ˈænə/","gloss":"Ana"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-03', 'lesson-travel-a2-16', 3, 'sentence', 'Can you open the trunk?', 'Pode abrir o porta-malas?', '/kæn juː ˈoʊpən ðə trʌŋk/', '"Trunk" (EUA) ou "boot" (Reino Unido) = porta-malas.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"open"},{"start":13,"end":23,"role":"direct_object","surface":"the trunk?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"trunk","pos":"noun","ipa":"/trʌŋk/","gloss":"porta-malas"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-04', 'lesson-travel-a2-16', 4, 'sentence', 'To this address, please.', 'Para este endereço, por favor.', '/tuː ðɪs ˈædrɛs pliːz/', 'Mostre o endereço no celular; evita erro de pronúncia.', '[{"start":0,"end":16,"role":"adverbial","surface":"To this address,"},{"start":17,"end":24,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"To","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"address","pos":"noun","ipa":"/ˈædrɛs/","gloss":"endereço"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-05', 'lesson-travel-a2-16', 5, 'sentence', 'How much is it to the airport?', 'Quanto custa até o aeroporto?', '/haʊ mʌtʃ ɪz ɪt tuː ðə ˈɛrpɔːrt/', 'Pergunte o preço antes em táxi sem taxímetro. "Meter" = taxímetro.', '[{"start":0,"end":8,"role":"predicate_adj","surface":"How much"},{"start":9,"end":11,"role":"predicate_verb","surface":"is"},{"start":12,"end":14,"role":"subject","surface":"it"},{"start":15,"end":30,"role":"adverbial","surface":"to the airport?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"airport","pos":"noun","ipa":"/ˈɛrpɔːrt/","gloss":"aeroporto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-06', 'lesson-travel-a2-16', 6, 'sentence', 'I''m in a hurry.', 'Estou com pressa.', '/aɪm ɪn ə ˈhɜːri/', '"In a hurry" = com pressa. Use com educação.', '[{"start":0,"end":3,"role":"subject","surface":"I''m"},{"start":4,"end":15,"role":"predicate_adj","surface":"in a hurry."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"hurry","pos":"noun","ipa":"/ˈhɜːri/","gloss":"pressa"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-07', 'lesson-travel-a2-16', 7, 'sentence', 'Can you stop here for a minute?', 'Pode parar aqui um minuto?', '/kæn juː stɑːp hɪr fɔːr ə ˈmɪnɪt/', '"For a minute" = por um instante.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"stop"},{"start":13,"end":17,"role":"adverbial","surface":"here"},{"start":18,"end":31,"role":"adverbial","surface":"for a minute?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"stop","pos":"verb","ipa":"/stɑːp/","gloss":"parar"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"minute","pos":"noun","ipa":"/ˈmɪnɪt/","gloss":"minuto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-08', 'lesson-travel-a2-16', 8, 'sentence', 'Is there traffic?', 'Está com trânsito?', '/ɪz ðɛr ˈtræfɪk/', '"Traffic" é incontável: não diga "a traffic".', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":17,"role":"subject","surface":"traffic?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"traffic","pos":"noun","ipa":"/ˈtræfɪk/","gloss":"trânsito"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-09', 'lesson-travel-a2-16', 9, 'sentence', 'Can I pay by card?', 'Posso pagar no cartão?', '/kæn aɪ peɪ baɪ kɑːrd/', '"By card" / "in cash". Pergunte antes de entrar em táxis comuns.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"pay"},{"start":10,"end":18,"role":"adverbial","surface":"by card?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"pay","pos":"verb","ipa":"/peɪ/","gloss":"pagar"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"card","pos":"noun","ipa":"/kɑːrd/","gloss":"cartão"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-16-10', 'lesson-travel-a2-16', 10, 'sentence', 'I left my phone in the car.', 'Esqueci meu celular no carro.', '/aɪ lɛft maɪ foʊn ɪn ðə kɑːr/', '"Left" = passado de "leave" (deixar, esquecer em algum lugar).', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"left"},{"start":7,"end":15,"role":"direct_object","surface":"my phone"},{"start":16,"end":27,"role":"adverbial","surface":"in the car."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"left","pos":"adverb","ipa":"/lɛft/","gloss":"à esquerda"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"phone","pos":"noun","ipa":"/foʊn/","gloss":"celular, telefone"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-17', 'course-travel-a2', 17, 'Trem e ônibus entre cidades', 'Comprar passagem, achar a plataforma e lidar com atrasos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-17-01', 'lesson-travel-a2-17', 1, 'sentence', 'A round trip ticket to Boston, please.', 'Uma passagem de ida e volta para Boston, por favor.', '/ə raʊnd trɪp ˈtɪkɪt tuː ˈbɔːstən pliːz/', '"Round trip" (EUA) = ida e volta; "one-way" = só ida.', '[{"start":0,"end":19,"role":"direct_object","surface":"A round trip ticket"},{"start":20,"end":30,"role":"adverbial","surface":"to Boston,"},{"start":31,"end":38,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"round","pos":"adjective","ipa":"/raʊnd/","gloss":"redondo; ida e volta"},{"surface":"trip","pos":"noun","ipa":"/trɪp/","gloss":"viagem"},{"surface":"ticket","pos":"noun","ipa":"/ˈtɪkɪt/","gloss":"passagem, bilhete"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"Boston","pos":"proper noun","ipa":"/ˈbɔːstən/","gloss":"Boston"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-02', 'lesson-travel-a2-17', 2, 'sentence', 'What time does the next train leave?', 'Que horas sai o próximo trem?', '/wʌt taɪm dʌz ðə nɛkst treɪn liːv/', 'Perguntas no presente simples para horários fixos: "does the train leave".', '[{"start":0,"end":9,"role":"adverbial","surface":"What time"},{"start":10,"end":14,"role":"predicate_verb","surface":"does"},{"start":15,"end":29,"role":"subject","surface":"the next train"},{"start":30,"end":36,"role":"predicate_verb","surface":"leave?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"train","pos":"noun","ipa":"/treɪn/","gloss":"trem"},{"surface":"leave","pos":"verb","ipa":"/liːv/","gloss":"deixar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-03', 'lesson-travel-a2-17', 3, 'sentence', 'Which platform is it?', 'Qual é a plataforma?', '/wɪtʃ ˈplætfɔːrm ɪz ɪt/', '"Platform" = plataforma. Nos EUA também se ouve "track".', '[{"start":0,"end":14,"role":"predicate_adj","surface":"Which platform"},{"start":15,"end":17,"role":"predicate_verb","surface":"is"},{"start":18,"end":21,"role":"subject","surface":"it?"}]'::jsonb, '[{"surface":"Which","pos":"determiner","ipa":"/wɪtʃ/","gloss":"qual"},{"surface":"platform","pos":"noun","ipa":"/ˈplætfɔːrm/","gloss":"plataforma"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-04', 'lesson-travel-a2-17', 4, 'sentence', 'Is this seat taken?', 'Este lugar está ocupado?', '/ɪz ðɪs siːt ˈteɪkən/', '"Taken" = ocupado. Resposta: "No, go ahead" (pode sentar).', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":12,"role":"subject","surface":"this seat"},{"start":13,"end":19,"role":"predicate_adj","surface":"taken?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"seat","pos":"noun","ipa":"/siːt/","gloss":"assento"},{"surface":"taken","pos":"verb","ipa":"/ˈteɪkən/","gloss":"pegado, levado"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-05', 'lesson-travel-a2-17', 5, 'sentence', 'Do I need to change trains?', 'Preciso trocar de trem?', '/duː aɪ niːd tuː tʃeɪndʒ treɪnz/', '"Change trains" (no plural) = fazer baldeação.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":4,"role":"subject","surface":"I"},{"start":5,"end":9,"role":"predicate_verb","surface":"need"},{"start":10,"end":27,"role":"direct_object","surface":"to change trains?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"},{"surface":"trains","pos":"noun","ipa":"/treɪnz/","gloss":"trens"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-06', 'lesson-travel-a2-17', 6, 'sentence', 'The train is running late.', 'O trem está atrasado.', '/ðə treɪn ɪz ˈrʌnɪŋ leɪt/', '"Running late" = atrasado, ainda em movimento. Mais natural que "is delayed" na fala.', '[{"start":0,"end":9,"role":"subject","surface":"The train"},{"start":10,"end":20,"role":"predicate_verb","surface":"is running"},{"start":21,"end":26,"role":"adverbial","surface":"late."}]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"train","pos":"noun","ipa":"/treɪn/","gloss":"trem"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"running","pos":"verb","ipa":"/ˈrʌnɪŋ/","gloss":"ficando (running late)"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-07', 'lesson-travel-a2-17', 7, 'sentence', 'Where do I validate my ticket?', 'Onde eu valido minha passagem?', '/wɛr duː aɪ ˈvælɪdeɪt maɪ ˈtɪkɪt/', 'Em muitos países é preciso validar antes de embarcar.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":8,"role":"predicate_verb","surface":"do"},{"start":9,"end":10,"role":"subject","surface":"I"},{"start":11,"end":19,"role":"predicate_verb","surface":"validate"},{"start":20,"end":30,"role":"direct_object","surface":"my ticket?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"validate","pos":"verb","ipa":"/ˈvælɪdeɪt/","gloss":"validar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"ticket","pos":"noun","ipa":"/ˈtɪkɪt/","gloss":"passagem, bilhete"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-08', 'lesson-travel-a2-17', 8, 'sentence', 'Does this bus go to the city center?', 'Este ônibus vai para o centro?', '/dʌz ðɪs bʌs ɡoʊ tuː ðə ˈsɪti ˈsɛntər/', '"City center" (EUA: center; Reino Unido: centre).', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Does"},{"start":5,"end":13,"role":"subject","surface":"this bus"},{"start":14,"end":16,"role":"predicate_verb","surface":"go"},{"start":17,"end":36,"role":"adverbial","surface":"to the city center?"}]'::jsonb, '[{"surface":"Does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"city","pos":"noun","ipa":"/ˈsɪti/","gloss":"cidade"},{"surface":"center","pos":"noun","ipa":"/ˈsɛntər/","gloss":"centro"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-09', 'lesson-travel-a2-17', 9, 'sentence', 'How many stops is it?', 'Quantas paradas são?', '/haʊ ˈmɛni stɑːps ɪz ɪt/', '"Stops" = paradas. Útil para saber onde descer.', '[{"start":0,"end":14,"role":"predicate_adj","surface":"How many stops"},{"start":15,"end":17,"role":"predicate_verb","surface":"is"},{"start":18,"end":21,"role":"subject","surface":"it?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"many","pos":"determiner","ipa":"/ˈmɛni/","gloss":"muitos (how many)"},{"surface":"stops","pos":"noun","ipa":"/stɑːps/","gloss":"paradas"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-17-10', 'lesson-travel-a2-17', 10, 'sentence', 'Please tell me when to get off.', 'Por favor, me avise quando descer.', '/pliːz tɛl miː wɛn tuː ɡɛt ɔːf/', '"Get off" = descer (de ônibus, trem). "Get on" = subir.', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Please"},{"start":7,"end":11,"role":"predicate_verb","surface":"tell"},{"start":12,"end":14,"role":"indirect_object","surface":"me"},{"start":15,"end":31,"role":"direct_object","surface":"when to get off."}]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-18', 'course-travel-a2', 18, 'Alugando um carro', 'Reserva, seguro, combustível e devolução.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-18-01', 'lesson-travel-a2-18', 1, 'sentence', 'I have a car reservation.', 'Tenho uma reserva de carro.', '/aɪ hæv ə kɑːr ˌrɛzərˈveɪʃən/', 'Comece assim no balcão e mostre o código da reserva.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"have"},{"start":7,"end":25,"role":"direct_object","surface":"a car reservation."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"reservation","pos":"noun","ipa":"/ˌrɛzərˈveɪʃən/","gloss":"reserva"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-02', 'lesson-travel-a2-18', 2, 'sentence', 'Here''s my driver''s license.', 'Aqui está minha carteira de motorista.', '/hɪrz maɪ ˈdraɪvərz ˈlaɪsəns/', '"Driver''s license" (EUA); pode ser pedida a permissão internacional.', '[{"start":0,"end":6,"role":"predicate_verb","surface":"Here''s"},{"start":7,"end":27,"role":"subject","surface":"my driver''s license."}]'::jsonb, '[{"surface":"Here''s","pos":"adverb","ipa":"/hɪrz/","gloss":"aqui está (here is)"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"driver''s","pos":"noun","ipa":"/ˈdraɪvərz/","gloss":"de motorista"},{"surface":"license","pos":"noun","ipa":"/ˈlaɪsəns/","gloss":"carteira, licença"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-03', 'lesson-travel-a2-18', 3, 'sentence', 'Is insurance included?', 'O seguro está incluído?', '/ɪz ɪnˈʃʊrəns ɪnˈkluːdɪd/', '"Insurance" = seguro. Pergunte o que ele cobre: "What does it cover?".', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":12,"role":"subject","surface":"insurance"},{"start":13,"end":22,"role":"predicate_adj","surface":"included?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"insurance","pos":"noun","ipa":"/ɪnˈʃʊrəns/","gloss":"seguro"},{"surface":"included","pos":"adjective","ipa":"/ɪnˈkluːdɪd/","gloss":"incluído"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-04', 'lesson-travel-a2-18', 4, 'sentence', 'Is it automatic or manual?', 'É automático ou manual?', '/ɪz ɪt ˌɔːtəˈmætɪk ɔːr ˈmænjuəl/', 'Nos EUA quase todos são automáticos; na Europa, manual é comum.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":5,"role":"subject","surface":"it"},{"start":6,"end":26,"role":"predicate_adj","surface":"automatic or manual?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"automatic","pos":"adjective","ipa":"/ˌɔːtəˈmætɪk/","gloss":"automático"},{"surface":"or","pos":"conjunction","ipa":"/ɔːr/","gloss":"ou"},{"surface":"manual","pos":"adjective","ipa":"/ˈmænjuəl/","gloss":"manual"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-05', 'lesson-travel-a2-18', 5, 'sentence', 'Should I return it with a full tank?', 'Devo devolver com o tanque cheio?', '/ʃʊd aɪ rɪˈtɜːrn ɪt wɪð ə fʊl tæŋk/', '"Full tank" = tanque cheio. Se não, cobram combustível caro.', '[{"start":0,"end":6,"role":"predicate_verb","surface":"Should"},{"start":7,"end":8,"role":"subject","surface":"I"},{"start":9,"end":15,"role":"predicate_verb","surface":"return"},{"start":16,"end":18,"role":"direct_object","surface":"it"},{"start":19,"end":36,"role":"adverbial","surface":"with a full tank?"}]'::jsonb, '[{"surface":"Should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"return","pos":"adjective","ipa":"/rɪˈtɜːrn/","gloss":"de volta"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"full","pos":"adjective","ipa":"/fʊl/","gloss":"cheio"},{"surface":"tank","pos":"noun","ipa":"/tæŋk/","gloss":"tanque"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-06', 'lesson-travel-a2-18', 6, 'sentence', 'Where is the nearest gas station?', 'Onde fica o posto de gasolina mais próximo?', '/wɛr ɪz ðə ˈnɪrɪst ɡæs ˈsteɪʃən/', '"Gas station" (EUA) ou "petrol station" (Reino Unido).', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":8,"role":"predicate_verb","surface":"is"},{"start":9,"end":33,"role":"subject","surface":"the nearest gas station?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"nearest","pos":"adjective","ipa":"/ˈnɪrɪst/","gloss":"mais próximo"},{"surface":"gas","pos":"noun","ipa":"/ɡæs/","gloss":"gasolina"},{"surface":"station","pos":"noun","ipa":"/ˈsteɪʃən/","gloss":"estação"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-07', 'lesson-travel-a2-18', 7, 'sentence', 'There is a scratch on the door.', 'Tem um arranhão na porta.', '/ðɛr ɪz ə skrætʃ ɑːn ðə dɔːr/', 'Registre danos antes de sair com o carro. "Scratch" = arranhão; "dent" = amassado.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"There is"},{"start":9,"end":18,"role":"subject","surface":"a scratch"},{"start":19,"end":31,"role":"adverbial","surface":"on the door."}]'::jsonb, '[{"surface":"There","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"scratch","pos":"noun","ipa":"/skrætʃ/","gloss":"arranhão"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"door","pos":"noun","ipa":"/dɔːr/","gloss":"porta"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-08', 'lesson-travel-a2-18', 8, 'sentence', 'Can I add a second driver?', 'Posso incluir um segundo motorista?', '/kæn aɪ æd ə ˈsɛkənd ˈdraɪvər/', '"Add" = adicionar. Costuma ter custo extra.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"add"},{"start":10,"end":26,"role":"direct_object","surface":"a second driver?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"add","pos":"verb","ipa":"/æd/","gloss":"acrescentar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"second","pos":"adjective","ipa":"/ˈsɛkənd/","gloss":"segundo"},{"surface":"driver","pos":"noun","ipa":"/ˈdraɪvər/","gloss":"motorista"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-09', 'lesson-travel-a2-18', 9, 'sentence', 'The car broke down.', 'O carro quebrou.', '/ðə kɑːr broʊk daʊn/', '"Break down" = quebrar (máquina, carro). Passado: "broke down".', '[{"start":0,"end":7,"role":"subject","surface":"The car"},{"start":8,"end":19,"role":"predicate_verb","surface":"broke down."}]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"broke","pos":"verb","ipa":"/broʊk/","gloss":"quebrou"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-18-10', 'lesson-travel-a2-18', 10, 'sentence', 'Where do I park?', 'Onde eu estaciono?', '/wɛr duː aɪ pɑːrk/', '"Park" = estacionar; "parking lot" = estacionamento.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":8,"role":"predicate_verb","surface":"do"},{"start":9,"end":10,"role":"subject","surface":"I"},{"start":11,"end":16,"role":"predicate_verb","surface":"park?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"park","pos":"verb","ipa":"/pɑːrk/","gloss":"estacionar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-19', 'course-travel-a2', 19, 'Compras e souvenirs', 'Tamanho, provador, preço, desconto e troca.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-19-01', 'lesson-travel-a2-19', 1, 'sentence', 'I''m just looking, thanks.', 'Só estou olhando, obrigado.', '/aɪm dʒʌst ˈlʊkɪŋ θæŋks/', 'Resposta educada quando o vendedor oferece ajuda e você não precisa.', '[{"start":0,"end":17,"role":"predicate_verb","surface":"I''m just looking,"},{"start":18,"end":25,"role":"discourse_marker","surface":"thanks."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-02', 'lesson-travel-a2-19', 2, 'sentence', 'Do you have this in a medium?', 'Tem este no tamanho médio?', '/duː juː hæv ðɪs ɪn ə ˈmiːdiəm/', '"In a" + tamanho: small, medium, large.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":6,"role":"subject","surface":"you"},{"start":7,"end":11,"role":"predicate_verb","surface":"have"},{"start":12,"end":16,"role":"direct_object","surface":"this"},{"start":17,"end":29,"role":"adverbial","surface":"in a medium?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"medium","pos":"adjective","ipa":"/ˈmiːdiəm/","gloss":"médio; ao ponto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-03', 'lesson-travel-a2-19', 3, 'sentence', 'Can I try it on?', 'Posso experimentar?', '/kæn aɪ traɪ ɪt ɑːn/', '"Try on" = experimentar roupa. O objeto vai no meio: "try it on".', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"try"},{"start":10,"end":12,"role":"direct_object","surface":"it"},{"start":13,"end":16,"role":"predicate_verb","surface":"on?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"try","pos":"verb","ipa":"/traɪ/","gloss":"experimentar, tentar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-04', 'lesson-travel-a2-19', 4, 'sentence', 'Where are the fitting rooms?', 'Onde ficam os provadores?', '/wɛr ɑːr ðə ˈfɪtɪŋ ruːmz/', '"Fitting room" = provador.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":9,"role":"predicate_verb","surface":"are"},{"start":10,"end":28,"role":"subject","surface":"the fitting rooms?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"fitting","pos":"adjective","ipa":"/ˈfɪtɪŋ/","gloss":"de prova (fitting room = provador)"},{"surface":"rooms","pos":"noun","ipa":"/ruːmz/","gloss":"quartos"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-05', 'lesson-travel-a2-19', 5, 'sentence', 'It''s too small.', 'Está pequeno demais.', '/ɪts tuː smɔːl/', '"Too" + adjetivo = demais (sentido negativo). "Bigger" = maior.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"It''s"},{"start":5,"end":15,"role":"predicate_adj","surface":"too small."}]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"small","pos":"adjective","ipa":"/smɔːl/","gloss":"pequeno"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-06', 'lesson-travel-a2-19', 6, 'sentence', 'How much does this cost?', 'Quanto custa isto?', '/haʊ mʌtʃ dʌz ðɪs kɔːst/', '"Cost" no presente: "does this cost". Também: "How much is this?".', '[{"start":0,"end":8,"role":"predicate_adj","surface":"How much"},{"start":9,"end":13,"role":"predicate_verb","surface":"does"},{"start":14,"end":18,"role":"subject","surface":"this"},{"start":19,"end":24,"role":"predicate_verb","surface":"cost?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"cost","pos":"verb","ipa":"/kɔːst/","gloss":"custar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-07', 'lesson-travel-a2-19', 7, 'sentence', 'Is there a discount?', 'Tem desconto?', '/ɪz ðɛr ə ˈdɪskaʊnt/', '"Discount" = desconto. "On sale" = em promoção.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":20,"role":"subject","surface":"a discount?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"discount","pos":"noun","ipa":"/ˈdɪskaʊnt/","gloss":"desconto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-08', 'lesson-travel-a2-19', 8, 'sentence', 'I''ll take it.', 'Vou levar.', '/aɪl teɪk ɪt/', 'Frase curta para fechar a compra.', '[{"start":0,"end":9,"role":"predicate_verb","surface":"I''ll take"},{"start":10,"end":13,"role":"direct_object","surface":"it."}]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-09', 'lesson-travel-a2-19', 9, 'sentence', 'Can I get a receipt?', 'Pode me dar o recibo?', '/kæn aɪ ɡɛt ə rɪˈsiːt/', '"Receipt" = recibo; o "p" é mudo: /rɪˈsiːt/.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"get"},{"start":10,"end":20,"role":"direct_object","surface":"a receipt?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"receipt","pos":"noun","ipa":"/rɪˈsiːt/","gloss":"recibo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-19-10', 'lesson-travel-a2-19', 10, 'sentence', 'Can I return it if it does not fit?', 'Posso devolver se não servir?', '/kæn aɪ rɪˈtɜːrn ɪt ɪf ɪt dʌz nɑːt fɪt/', '"Fit" = servir (tamanho). Pergunte sobre a "return policy".', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":12,"role":"predicate_verb","surface":"return"},{"start":13,"end":15,"role":"direct_object","surface":"it"},{"start":16,"end":35,"role":"adverbial","surface":"if it does not fit?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"return","pos":"adjective","ipa":"/rɪˈtɜːrn/","gloss":"de volta"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"fit","pos":"verb","ipa":"/fɪt/","gloss":"servir (tamanho)"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
