-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-travel-a2', 'travel-no-stress-a2', 'Viagem sem Aperto', 'Aeroporto, avião, imigração, hotel e Airbnb, transporte, carro, compras, restaurante, farmácia e emergências: as frases que você realmente precisa na viagem.', 'Situações de viagem com o que você diz e o que ouve do outro lado: aeroporto e imigração, táxi, trem e carro alugado, hotel e Airbnb, compras, restaurante e café, farmácia, direções e emergências.', 'A2', 'travel', 2, 'viagem', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-20', 'course-travel-a2', 20, 'Hotel: chegada e check-in', 'Chegar cedo, documentos, cartão-chave e horários.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-20-01', 'lesson-travel-a2-20', 1, 'sentence', 'Can I check in early?', 'Posso fazer o check-in mais cedo?', '/kæn aɪ tʃɛk ɪn ˈɜːrli/', '"Early check-in" nem sempre é grátis. Se não der, peça para guardar a mala.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":14,"role":"predicate_verb","surface":"check in"},{"start":15,"end":21,"role":"adverbial","surface":"early?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-02', 'lesson-travel-a2-20', 2, 'sentence', 'Your room is not ready yet.', 'Seu quarto ainda não está pronto.', '/jʊr ruːm ɪz nɑːt ˈrɛdi jɛt/', 'Fala da recepção. "Yet" no fim de negativas = ainda.', '[{"start":0,"end":9,"role":"subject","surface":"Your room"},{"start":10,"end":16,"role":"predicate_verb","surface":"is not"},{"start":17,"end":22,"role":"predicate_adj","surface":"ready"},{"start":23,"end":27,"role":"adverbial","surface":"yet."}]'::jsonb, '[{"surface":"Your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"ready","pos":"adjective","ipa":"/ˈrɛdi/","gloss":"pronto"},{"surface":"yet","pos":"adverb","ipa":"/jɛt/","gloss":"ainda"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-03', 'lesson-travel-a2-20', 3, 'sentence', 'May I see your ID?', 'Posso ver seu documento?', '/meɪ aɪ siː jʊr ˌaɪˈdiː/', '"ID" = documento de identidade. Para estrangeiros, geralmente o passaporte.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"May"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"see"},{"start":10,"end":18,"role":"direct_object","surface":"your ID?"}]'::jsonb, '[{"surface":"May","pos":"modal verb","ipa":"/meɪ/","gloss":"poder (permissão formal)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"ID","pos":"noun","ipa":"/ˌaɪˈdiː/","gloss":"documento de identidade"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-04', 'lesson-travel-a2-20', 4, 'sentence', 'We need a card for incidentals.', 'Precisamos de um cartão para despesas extras.', '/wiː niːd ə kɑːrd fɔːr ˌɪnsɪˈdɛntəlz/', 'Os hotéis bloqueiam um valor no cartão para gastos extras ("incidentals").', '[{"start":0,"end":2,"role":"subject","surface":"We"},{"start":3,"end":7,"role":"predicate_verb","surface":"need"},{"start":8,"end":14,"role":"direct_object","surface":"a card"},{"start":15,"end":31,"role":"adverbial","surface":"for incidentals."}]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"card","pos":"noun","ipa":"/kɑːrd/","gloss":"cartão"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"incidentals","pos":"noun","ipa":"/ˌɪnsɪˈdɛntəlz/","gloss":"despesas extras"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-05', 'lesson-travel-a2-20', 5, 'sentence', 'Here is your key card.', 'Aqui está seu cartão-chave.', '/hɪr ɪz jʊr kiː kɑːrd/', '"Key card" = cartão que abre a porta.', '[{"start":0,"end":4,"role":"adverbial","surface":"Here"},{"start":5,"end":7,"role":"predicate_verb","surface":"is"},{"start":8,"end":22,"role":"subject","surface":"your key card."}]'::jsonb, '[{"surface":"Here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"key","pos":"noun","ipa":"/kiː/","gloss":"chave"},{"surface":"card","pos":"noun","ipa":"/kɑːrd/","gloss":"cartão"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-06', 'lesson-travel-a2-20', 6, 'sentence', 'What floor is my room on?', 'Em que andar fica meu quarto?', '/wʌt flɔːr ɪz maɪ ruːm ɑːn/', 'A preposição vai para o fim: "What floor is it on?".', '[{"start":0,"end":10,"role":"adverbial","surface":"What floor"},{"start":11,"end":13,"role":"predicate_verb","surface":"is"},{"start":14,"end":21,"role":"subject","surface":"my room"},{"start":22,"end":25,"role":"adverbial","surface":"on?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"floor","pos":"noun","ipa":"/flɔːr/","gloss":"andar; chão"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-07', 'lesson-travel-a2-20', 7, 'sentence', 'What time is breakfast served?', 'Que horas é servido o café da manhã?', '/wʌt taɪm ɪz ˈbrɛkfəst sɜːrvd/', 'Voz passiva: "is served". Resposta típica: "From seven to ten".', '[{"start":0,"end":9,"role":"adverbial","surface":"What time"},{"start":10,"end":12,"role":"predicate_verb","surface":"is"},{"start":13,"end":22,"role":"subject","surface":"breakfast"},{"start":23,"end":30,"role":"predicate_verb","surface":"served?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"breakfast","pos":"noun","ipa":"/ˈbrɛkfəst/","gloss":"café da manhã"},{"surface":"served","pos":"verb","ipa":"/sɜːrvd/","gloss":"servido"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-08', 'lesson-travel-a2-20', 8, 'sentence', 'Is there a gym?', 'Tem academia?', '/ɪz ðɛr ə dʒɪm/', '"Gym" = academia. Outros serviços: pool (piscina), spa, laundry (lavanderia).', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":15,"role":"subject","surface":"a gym?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"gym","pos":"noun","ipa":"/dʒɪm/","gloss":"academia"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-09', 'lesson-travel-a2-20', 9, 'sentence', 'Could I have a room with a view?', 'Poderia me dar um quarto com vista?', '/kʊd aɪ hæv ə ruːm wɪð ə vjuː/', '"With a view" = com vista. Pedir com educação aumenta a chance.', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Could"},{"start":6,"end":7,"role":"subject","surface":"I"},{"start":8,"end":12,"role":"predicate_verb","surface":"have"},{"start":13,"end":19,"role":"direct_object","surface":"a room"},{"start":20,"end":32,"role":"adverbial","surface":"with a view?"}]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"view","pos":"noun","ipa":"/vjuː/","gloss":"vista"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-20-10', 'lesson-travel-a2-20', 10, 'sentence', 'Enjoy your stay.', 'Aproveite a estadia.', '/ɪnˈdʒɔɪ jʊr steɪ/', 'Frase padrão da recepção. Responda "Thank you".', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Enjoy"},{"start":6,"end":16,"role":"direct_object","surface":"your stay."}]'::jsonb, '[{"surface":"Enjoy","pos":"verb","ipa":"/ɪnˈdʒɔɪ/","gloss":"aproveitar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"stay","pos":"verb","ipa":"/steɪ/","gloss":"ficar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-21', 'course-travel-a2', 21, 'Hotel: serviços e problemas', 'Limpeza, itens extras, chuveiro, cartão que não abre.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-21-01', 'lesson-travel-a2-21', 1, 'sentence', 'My key card doesn''t work.', 'Meu cartão-chave não funciona.', '/maɪ kiː kɑːrd ˈdʌzənt wɜːrk/', 'Problema comum: o cartão desmagnetiza perto do celular.', '[{"start":0,"end":11,"role":"subject","surface":"My key card"},{"start":12,"end":25,"role":"predicate_verb","surface":"doesn''t work."}]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"key","pos":"noun","ipa":"/kiː/","gloss":"chave"},{"surface":"card","pos":"noun","ipa":"/kɑːrd/","gloss":"cartão"},{"surface":"doesn''t","pos":"verb","ipa":"/ˈdʌzənt/","gloss":"não (does not)"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-02', 'lesson-travel-a2-21', 2, 'sentence', 'There''s no hot water.', 'Não tem água quente.', '/ðɛrz noʊ hɑːt ˈwɔːtər/', '"There''s no" = não tem. "Hot water" = água quente.', '[{"start":0,"end":7,"role":"predicate_verb","surface":"There''s"},{"start":8,"end":21,"role":"subject","surface":"no hot water."}]'::jsonb, '[{"surface":"There''s","pos":"pronoun","ipa":"/ðɛrz/","gloss":"há, tem (there is)"},{"surface":"no","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"hot","pos":"adjective","ipa":"/hɑːt/","gloss":"quente"},{"surface":"water","pos":"noun","ipa":"/ˈwɔːtər/","gloss":"água"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-03', 'lesson-travel-a2-21', 3, 'sentence', 'The shower is leaking.', 'O chuveiro está vazando.', '/ðə ˈʃaʊər ɪz ˈliːkɪŋ/', '"Leak" = vazar. Presente contínuo para o que acontece agora.', '[{"start":0,"end":10,"role":"subject","surface":"The shower"},{"start":11,"end":22,"role":"predicate_verb","surface":"is leaking."}]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"shower","pos":"noun","ipa":"/ˈʃaʊər/","gloss":"banho de chuveiro"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"leaking","pos":"verb","ipa":"/ˈliːkɪŋ/","gloss":"vazando"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-04', 'lesson-travel-a2-21', 4, 'sentence', 'Could you send someone to fix it?', 'Poderia mandar alguém consertar?', '/kʊd juː sɛnd ˈsʌmwʌn tuː fɪks ɪt/', '"Fix" = consertar. Pedido educado com "could you".', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Could"},{"start":6,"end":9,"role":"subject","surface":"you"},{"start":10,"end":14,"role":"predicate_verb","surface":"send"},{"start":15,"end":22,"role":"direct_object","surface":"someone"},{"start":23,"end":33,"role":"adverbial","surface":"to fix it?"}]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"send","pos":"verb","ipa":"/sɛnd/","gloss":"enviar, mandar"},{"surface":"someone","pos":"pronoun","ipa":"/ˈsʌmwʌn/","gloss":"alguém"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"fix","pos":"verb","ipa":"/fɪks/","gloss":"consertar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-05', 'lesson-travel-a2-21', 5, 'sentence', 'Please clean my room today.', 'Por favor, limpe meu quarto hoje.', '/pliːz kliːn maɪ ruːm təˈdeɪ/', 'Em alguns hotéis a limpeza precisa ser pedida. "Housekeeping" = governança.', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Please"},{"start":7,"end":12,"role":"predicate_verb","surface":"clean"},{"start":13,"end":20,"role":"direct_object","surface":"my room"},{"start":21,"end":27,"role":"adverbial","surface":"today."}]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"clean","pos":"verb","ipa":"/kliːn/","gloss":"limpar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"},{"surface":"today","pos":"adverb","ipa":"/təˈdeɪ/","gloss":"hoje"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-06', 'lesson-travel-a2-21', 6, 'sentence', 'Can I get another pillow?', 'Posso receber outro travesseiro?', '/kæn aɪ ɡɛt əˈnʌðər ˈpɪloʊ/', '"Another" = mais um. "Pillow" = travesseiro.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"get"},{"start":10,"end":25,"role":"direct_object","surface":"another pillow?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"another","pos":"determiner","ipa":"/əˈnʌðər/","gloss":"outro, mais um"},{"surface":"pillow","pos":"noun","ipa":"/ˈpɪloʊ/","gloss":"travesseiro"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-07', 'lesson-travel-a2-21', 7, 'sentence', 'Is there a safe in the room?', 'Tem cofre no quarto?', '/ɪz ðɛr ə seɪf ɪn ðə ruːm/', '"Safe" como substantivo = cofre (como adjetivo = seguro).', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":15,"role":"subject","surface":"a safe"},{"start":16,"end":28,"role":"adverbial","surface":"in the room?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"safe","pos":"adjective","ipa":"/seɪf/","gloss":"seguro"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-08', 'lesson-travel-a2-21', 8, 'sentence', 'Can you wake me up at six?', 'Pode me acordar às seis?', '/kæn juː weɪk miː ʌp æt sɪks/', '"Wake up" = acordar. Pedido de "wake-up call" na recepção.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"wake"},{"start":13,"end":15,"role":"direct_object","surface":"me"},{"start":16,"end":18,"role":"predicate_verb","surface":"up"},{"start":19,"end":26,"role":"adverbial","surface":"at six?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"wake","pos":"verb","ipa":"/weɪk/","gloss":"acordar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"six","pos":"numeral","ipa":"/sɪks/","gloss":"seis"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-09', 'lesson-travel-a2-21', 9, 'sentence', 'Do you have laundry service?', 'Vocês têm serviço de lavanderia?', '/duː juː hæv ˈlɔːndri ˈsɜːrvɪs/', '"Laundry" = lavanderia, roupa para lavar.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":6,"role":"subject","surface":"you"},{"start":7,"end":11,"role":"predicate_verb","surface":"have"},{"start":12,"end":28,"role":"direct_object","surface":"laundry service?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"laundry","pos":"noun","ipa":"/ˈlɔːndri/","gloss":"lavanderia"},{"surface":"service","pos":"noun","ipa":"/ˈsɜːrvɪs/","gloss":"serviço"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-21-10', 'lesson-travel-a2-21', 10, 'sentence', 'Please do not disturb.', 'Por favor, não perturbe.', '/pliːz duː nɑːt dɪˈstɜːrb/', 'Texto da plaquinha da porta. "Disturb" = incomodar.', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Please"},{"start":7,"end":22,"role":"predicate_verb","surface":"do not disturb."}]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"disturb","pos":"verb","ipa":"/dɪˈstɜːrb/","gloss":"perturbar, incomodar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-22', 'course-travel-a2', 22, 'Hotel: check-out e conta', 'Sair, conferir cobranças, guardar mala e pedir táxi.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-22-01', 'lesson-travel-a2-22', 1, 'sentence', 'I''d like to check out.', 'Eu gostaria de fazer o check-out.', '/aɪd laɪk tuː tʃɛk aʊt/', '"Check out" = sair do hotel e fechar a conta.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"I''d like"},{"start":9,"end":22,"role":"direct_object","surface":"to check out."}]'::jsonb, '[{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-02', 'lesson-travel-a2-22', 2, 'sentence', 'Can I have a late checkout?', 'Posso sair mais tarde?', '/kæn aɪ hæv ə leɪt ˈtʃɛkaʊt/', '"Late checkout" = sair depois do horário. Às vezes tem custo.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":10,"role":"predicate_verb","surface":"have"},{"start":11,"end":27,"role":"direct_object","surface":"a late checkout?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"checkout","pos":"noun","ipa":"/ˈtʃɛkaʊt/","gloss":"saída do hotel"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-03', 'lesson-travel-a2-22', 3, 'sentence', 'Did you take anything from the minibar?', 'Pegou algo do frigobar?', '/dɪd juː teɪk ˈɛniθɪŋ frʌm ðə ˈmɪnibɑːr/', 'Pergunta da recepção. "Minibar" = frigobar.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Did"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"take"},{"start":13,"end":21,"role":"direct_object","surface":"anything"},{"start":22,"end":39,"role":"adverbial","surface":"from the minibar?"}]'::jsonb, '[{"surface":"Did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"minibar","pos":"noun","ipa":"/ˈmɪnibɑːr/","gloss":"frigobar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-04', 'lesson-travel-a2-22', 4, 'sentence', 'What''s this charge for?', 'Esta cobrança é de quê?', '/wʌts ðɪs tʃɑːrdʒ fɔːr/', '"Charge" = cobrança. A preposição "for" vai para o fim.', '[{"start":0,"end":6,"role":"predicate_verb","surface":"What''s"},{"start":7,"end":18,"role":"subject","surface":"this charge"},{"start":19,"end":23,"role":"adverbial","surface":"for?"}]'::jsonb, '[{"surface":"What''s","pos":"pronoun","ipa":"/wʌts/","gloss":"qual é"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"charge","pos":"noun","ipa":"/tʃɑːrdʒ/","gloss":"cobrança"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-05', 'lesson-travel-a2-22', 5, 'sentence', 'I didn''t use the minibar.', 'Eu não usei o frigobar.', '/aɪ ˈdɪdənt juːz ðə ˈmɪnibɑːr/', 'Passado negativo: "didn''t" + verbo base.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":12,"role":"predicate_verb","surface":"didn''t use"},{"start":13,"end":25,"role":"direct_object","surface":"the minibar."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"use","pos":"verb","ipa":"/juːz/","gloss":"usar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"minibar","pos":"noun","ipa":"/ˈmɪnibɑːr/","gloss":"frigobar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-06', 'lesson-travel-a2-22', 6, 'sentence', 'Can you store my luggage until four?', 'Pode guardar minha bagagem até as quatro?', '/kæn juː stɔːr maɪ ˈlʌɡɪdʒ ənˈtɪl fɔːr/', '"Store" = guardar. "Until" = até (tempo).', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":13,"role":"predicate_verb","surface":"store"},{"start":14,"end":24,"role":"direct_object","surface":"my luggage"},{"start":25,"end":36,"role":"adverbial","surface":"until four?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"store","pos":"noun","ipa":"/stɔːr/","gloss":"loja, mercado"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"luggage","pos":"noun","ipa":"/ˈlʌɡɪdʒ/","gloss":"bagagem"},{"surface":"until","pos":"conjunction","ipa":"/ənˈtɪl/","gloss":"até"},{"surface":"four","pos":"numeral","ipa":"/fɔːr/","gloss":"quatro"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-07', 'lesson-travel-a2-22', 7, 'sentence', 'Could you call a taxi for me?', 'Poderia chamar um táxi para mim?', '/kʊd juː kɔːl ə ˈtæksi fɔːr miː/', '"For me" = para mim.', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Could"},{"start":6,"end":9,"role":"subject","surface":"you"},{"start":10,"end":14,"role":"predicate_verb","surface":"call"},{"start":15,"end":21,"role":"direct_object","surface":"a taxi"},{"start":22,"end":29,"role":"adverbial","surface":"for me?"}]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"taxi","pos":"noun","ipa":"/ˈtæksi/","gloss":"táxi"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-08', 'lesson-travel-a2-22', 8, 'sentence', 'Can you email me the invoice?', 'Pode me mandar a nota fiscal por e-mail?', '/kæn juː ˈiːmeɪl miː ðə ˈɪnvɔɪs/', '"Email" também é verbo: "email me". "Invoice" = fatura, nota fiscal.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":13,"role":"predicate_verb","surface":"email"},{"start":14,"end":16,"role":"indirect_object","surface":"me"},{"start":17,"end":29,"role":"direct_object","surface":"the invoice?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"email","pos":"noun","ipa":"/ˈiːmeɪl/","gloss":"e-mail"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"invoice","pos":"noun","ipa":"/ˈɪnvɔɪs/","gloss":"fatura, nota fiscal"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-09', 'lesson-travel-a2-22', 9, 'sentence', 'I left something in the room.', 'Deixei uma coisa no quarto.', '/aɪ lɛft ˈsʌmθɪŋ ɪn ðə ruːm/', '"Left" = passado de "leave" (deixar/esquecer).', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"left"},{"start":7,"end":16,"role":"direct_object","surface":"something"},{"start":17,"end":29,"role":"adverbial","surface":"in the room."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"left","pos":"adverb","ipa":"/lɛft/","gloss":"à esquerda"},{"surface":"something","pos":"pronoun","ipa":"/ˈsʌmθɪŋ/","gloss":"alguma coisa"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-22-10', 'lesson-travel-a2-22', 10, 'sentence', 'How was your stay?', 'Como foi a estadia?', '/haʊ wɑːz jʊr steɪ/', 'Pergunta simpática da recepção. Responda "It was great, thanks".', '[{"start":0,"end":3,"role":"adverbial","surface":"How"},{"start":4,"end":7,"role":"predicate_verb","surface":"was"},{"start":8,"end":18,"role":"subject","surface":"your stay?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"stay","pos":"verb","ipa":"/steɪ/","gloss":"ficar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-23', 'course-travel-a2', 23, 'Airbnb e anfitrião', 'Combinar chegada, chaves, regras da casa e problemas.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-23-01', 'lesson-travel-a2-23', 1, 'sentence', 'What time can we arrive?', 'A que horas podemos chegar?', '/wʌt taɪm kæn wiː əˈraɪv/', 'Combine o horário com o anfitrião ("host") antes da viagem.', '[{"start":0,"end":9,"role":"adverbial","surface":"What time"},{"start":10,"end":13,"role":"predicate_verb","surface":"can"},{"start":14,"end":16,"role":"subject","surface":"we"},{"start":17,"end":24,"role":"predicate_verb","surface":"arrive?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"arrive","pos":"verb","ipa":"/əˈraɪv/","gloss":"chegar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-02', 'lesson-travel-a2-23', 2, 'sentence', 'Where can I pick up the keys?', 'Onde posso pegar as chaves?', '/wɛr kæn aɪ pɪk ʌp ðə kiːz/', '"Pick up" = buscar, pegar. Muitas casas usam cofre de chave ("lockbox").', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":9,"role":"predicate_verb","surface":"can"},{"start":10,"end":11,"role":"subject","surface":"I"},{"start":12,"end":19,"role":"predicate_verb","surface":"pick up"},{"start":20,"end":29,"role":"direct_object","surface":"the keys?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"pick","pos":"verb","ipa":"/pɪk/","gloss":"pegar (pick up)"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-03', 'lesson-travel-a2-23', 3, 'sentence', 'What''s the door code?', 'Qual é o código da porta?', '/wʌts ðə dɔːr koʊd/', '"Code" = código, senha numérica.', '[{"start":0,"end":6,"role":"predicate_verb","surface":"What''s"},{"start":7,"end":21,"role":"subject","surface":"the door code?"}]'::jsonb, '[{"surface":"What''s","pos":"pronoun","ipa":"/wʌts/","gloss":"qual é"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"door","pos":"noun","ipa":"/dɔːr/","gloss":"porta"},{"surface":"code","pos":"noun","ipa":"/koʊd/","gloss":"código"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-04', 'lesson-travel-a2-23', 4, 'sentence', 'Are there any house rules?', 'Tem alguma regra da casa?', '/ɑːr ðɛr ˈɛni haʊs ruːlz/', '"House rules": horário de silêncio, lixo, visitas.', '[{"start":0,"end":9,"role":"predicate_verb","surface":"Are there"},{"start":10,"end":26,"role":"subject","surface":"any house rules?"}]'::jsonb, '[{"surface":"Are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"house","pos":"noun","ipa":"/haʊs/","gloss":"casa"},{"surface":"rules","pos":"noun","ipa":"/ruːlz/","gloss":"regras"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-05', 'lesson-travel-a2-23', 5, 'sentence', 'Is there parking nearby?', 'Tem estacionamento perto?', '/ɪz ðɛr ˈpɑːrkɪŋ ˌnɪrˈbaɪ/', '"Nearby" = por perto.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":16,"role":"subject","surface":"parking"},{"start":17,"end":24,"role":"adverbial","surface":"nearby?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"parking","pos":"noun","ipa":"/ˈpɑːrkɪŋ/","gloss":"estacionamento"},{"surface":"nearby","pos":"adverb","ipa":"/ˌnɪrˈbaɪ/","gloss":"por perto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-06', 'lesson-travel-a2-23', 6, 'sentence', 'The heating isn''t working.', 'O aquecedor não está funcionando.', '/ðə ˈhiːtɪŋ ˈɪzənt ˈwɜːrkɪŋ/', '"Heating" = aquecimento. Com "air conditioning" a frase é igual.', '[{"start":0,"end":11,"role":"subject","surface":"The heating"},{"start":12,"end":26,"role":"predicate_verb","surface":"isn''t working."}]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"heating","pos":"noun","ipa":"/ˈhiːtɪŋ/","gloss":"aquecimento"},{"surface":"isn''t","pos":"auxiliary verb","ipa":"/ˈɪzənt/","gloss":"não é, não está"},{"surface":"working","pos":"verb","ipa":"/ˈwɜːrkɪŋ/","gloss":"funcionando; trabalhando"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-07', 'lesson-travel-a2-23', 7, 'sentence', 'Where do I put the trash?', 'Onde eu coloco o lixo?', '/wɛr duː aɪ pʊt ðə træʃ/', '"Trash" (EUA) ou "rubbish" (Reino Unido). "Recycling" = reciclável.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":8,"role":"predicate_verb","surface":"do"},{"start":9,"end":10,"role":"subject","surface":"I"},{"start":11,"end":14,"role":"predicate_verb","surface":"put"},{"start":15,"end":25,"role":"direct_object","surface":"the trash?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"trash","pos":"noun","ipa":"/træʃ/","gloss":"lixo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-08', 'lesson-travel-a2-23', 8, 'sentence', 'Can we use the washing machine?', 'Podemos usar a máquina de lavar?', '/kæn wiː juːz ðə ˈwɑːʃɪŋ məˈʃiːn/', '"Washing machine" = máquina de lavar; "dryer" = secadora.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":6,"role":"subject","surface":"we"},{"start":7,"end":10,"role":"predicate_verb","surface":"use"},{"start":11,"end":31,"role":"direct_object","surface":"the washing machine?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"use","pos":"verb","ipa":"/juːz/","gloss":"usar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"washing","pos":"noun","ipa":"/ˈwɑːʃɪŋ/","gloss":"lavagem"},{"surface":"machine","pos":"noun","ipa":"/məˈʃiːn/","gloss":"máquina"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-09', 'lesson-travel-a2-23', 9, 'sentence', 'We will leave the keys on the table.', 'Vamos deixar as chaves na mesa.', '/wiː wɪl liːv ðə kiːz ɑːn ðə ˈteɪbəl/', 'Mensagem ao anfitrião na saída. Futuro com "will".', '[{"start":0,"end":2,"role":"subject","surface":"We"},{"start":3,"end":13,"role":"predicate_verb","surface":"will leave"},{"start":14,"end":22,"role":"direct_object","surface":"the keys"},{"start":23,"end":36,"role":"adverbial","surface":"on the table."}]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"leave","pos":"verb","ipa":"/liːv/","gloss":"deixar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"table","pos":"noun","ipa":"/ˈteɪbəl/","gloss":"mesa"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-23-10', 'lesson-travel-a2-23', 10, 'sentence', 'Thanks for having us.', 'Obrigado por nos receber.', '/θæŋks fɔːr ˈhævɪŋ ʌs/', '"Thanks for having us" = obrigado pela hospitalidade. Muito natural.', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Thanks"},{"start":7,"end":21,"role":"adverbial","surface":"for having us."}]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"having","pos":"verb","ipa":"/ˈhævɪŋ/","gloss":"receber, ter"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
