-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-travel-a2', 'travel-no-stress-a2', 'Viagem sem Aperto', 'Do aeroporto à praia: avião, imigração, hotel e Airbnb, transporte, compras, restaurante, passeios, farmácia e emergências.', 'A viagem inteira em situações reais, com o que você diz e o que ouve do outro lado: aeroporto e imigração, táxi, trem e carro alugado, hotel e Airbnb, compras, restaurante, café e bar, passeios e praia, farmácia, direções e emergências. Termina com um capítulo de revisão.', 'A2', 'travel', 2, 'viagem', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-24', 'course-travel-a2', 24, 'Bar e balada', 'Pedir bebidas, pagar a rodada e conversar na noite.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-24-01', 'lesson-travel-a2-24', 1, 'sentence', 'What do you have on tap?', 'Que chopes vocês têm?', '/wʌt duː juː hæv ɑːn tæp/', '"On tap" = da torneira, chope. "Bottled" = de garrafa.', '[{"start":0,"end":4,"role":"direct_object","surface":"What"},{"start":5,"end":7,"role":"predicate_verb","surface":"do"},{"start":8,"end":11,"role":"subject","surface":"you"},{"start":12,"end":16,"role":"predicate_verb","surface":"have"},{"start":17,"end":24,"role":"adverbial","surface":"on tap?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"tap","pos":"noun","ipa":"/tæp/","gloss":"torneira; chope"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-02', 'lesson-travel-a2-24', 2, 'sentence', 'I''ll have a glass of red wine.', 'Vou querer uma taça de vinho tinto.', '/aɪl hæv ə ɡlæs ʌv rɛd waɪn/', '"Red wine" = vinho tinto; "white wine" = branco. O adjetivo vem antes.', '[{"start":0,"end":9,"role":"predicate_verb","surface":"I''ll have"},{"start":10,"end":17,"role":"direct_object","surface":"a glass"},{"start":18,"end":30,"role":"adverbial","surface":"of red wine."}]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"glass","pos":"noun","ipa":"/ɡlæs/","gloss":"taça, copo"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"red","pos":"adjective","ipa":"/rɛd/","gloss":"vermelho"},{"surface":"wine","pos":"noun","ipa":"/waɪn/","gloss":"vinho"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-03', 'lesson-travel-a2-24', 3, 'sentence', 'Can I see your ID?', 'Posso ver seu documento?', '/kæn aɪ siː jʊr ˌaɪˈdiː/', 'Nos EUA pedem documento para vender álcool (idade mínima 21).', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"see"},{"start":10,"end":18,"role":"direct_object","surface":"your ID?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"ID","pos":"noun","ipa":"/ˌaɪˈdiː/","gloss":"documento de identidade"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-04', 'lesson-travel-a2-24', 4, 'sentence', 'This round''s on me.', 'Esta rodada é por minha conta.', '/ðɪs raʊndz ɑːn miː/', '"Round" = rodada de bebidas. "On me" = eu pago.', '[{"start":0,"end":12,"role":"subject","surface":"This round''s"},{"start":13,"end":19,"role":"predicate_adj","surface":"on me."}]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"round''s","pos":"noun","ipa":"/raʊndz/","gloss":"rodada é (round is)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-05', 'lesson-travel-a2-24', 5, 'sentence', 'Can I start a tab?', 'Posso abrir uma comanda?', '/kæn aɪ stɑːrt ə tæb/', '"Tab" = conta aberta no bar. "Close the tab" = fechar a conta.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":11,"role":"predicate_verb","surface":"start"},{"start":12,"end":18,"role":"direct_object","surface":"a tab?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"start","pos":"verb","ipa":"/stɑːrt/","gloss":"começar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"tab","pos":"noun","ipa":"/tæb/","gloss":"comanda, conta aberta"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-06', 'lesson-travel-a2-24', 6, 'sentence', 'Is there a cover charge?', 'Tem entrada paga?', '/ɪz ðɛr ə ˈkʌvər tʃɑːrdʒ/', '"Cover charge" = valor cobrado na entrada da casa.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":24,"role":"subject","surface":"a cover charge?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"cover","pos":"noun","ipa":"/ˈkʌvər/","gloss":"entrada (cover charge)"},{"surface":"charge","pos":"noun","ipa":"/tʃɑːrdʒ/","gloss":"cobrança"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-07', 'lesson-travel-a2-24', 7, 'sentence', 'What time does it close?', 'Que horas fecha?', '/wʌt taɪm dʌz ɪt kloʊz/', 'Presente simples para horários fixos.', '[{"start":0,"end":9,"role":"adverbial","surface":"What time"},{"start":10,"end":14,"role":"predicate_verb","surface":"does"},{"start":15,"end":17,"role":"subject","surface":"it"},{"start":18,"end":24,"role":"predicate_verb","surface":"close?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"close","pos":"verb","ipa":"/kloʊz/","gloss":"fechar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-08', 'lesson-travel-a2-24', 8, 'sentence', 'Do you want to dance?', 'Quer dançar?', '/duː juː wɑːnt tuː dæns/', '"Want to" + verbo. Na fala rápida vira "wanna".', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":6,"role":"subject","surface":"you"},{"start":7,"end":11,"role":"predicate_verb","surface":"want"},{"start":12,"end":21,"role":"direct_object","surface":"to dance?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"dance","pos":"verb","ipa":"/dæns/","gloss":"dançar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-09', 'lesson-travel-a2-24', 9, 'sentence', 'Where are you from?', 'De onde você é?', '/wɛr ɑːr juː frʌm/', 'A pergunta mais comum para puxar conversa. Resposta: "I''m from Brazil".', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":9,"role":"predicate_verb","surface":"are"},{"start":10,"end":13,"role":"subject","surface":"you"},{"start":14,"end":19,"role":"adverbial","surface":"from?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-24-10', 'lesson-travel-a2-24', 10, 'sentence', 'I''m not drinking tonight, thanks.', 'Hoje não vou beber, obrigado.', '/aɪm nɑːt ˈdrɪŋkɪŋ təˈnaɪt θæŋks/', 'Presente contínuo para decisão da noite. Recusa educada e clara.', '[{"start":0,"end":16,"role":"predicate_verb","surface":"I''m not drinking"},{"start":17,"end":25,"role":"adverbial","surface":"tonight,"},{"start":26,"end":33,"role":"discourse_marker","surface":"thanks."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"drinking","pos":"verb","ipa":"/ˈdrɪŋkɪŋ/","gloss":"bebendo"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"},{"surface":"thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-25', 'course-travel-a2', 25, 'Passeios e ingressos', 'Comprar ingresso, horários, tours e fotos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-25-01', 'lesson-travel-a2-25', 1, 'sentence', 'Two tickets for the museum, please.', 'Dois ingressos para o museu, por favor.', '/tuː ˈtɪkɪts fɔːr ðə mjuˈziːəm pliːz/', '"Ticket" serve para ingresso e passagem.', '[{"start":0,"end":11,"role":"direct_object","surface":"Two tickets"},{"start":12,"end":27,"role":"adverbial","surface":"for the museum,"},{"start":28,"end":35,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"Two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"tickets","pos":"noun","ipa":"/ˈtɪkɪts/","gloss":"ingressos"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"museum","pos":"noun","ipa":"/mjuˈziːəm/","gloss":"museu"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-02', 'lesson-travel-a2-25', 2, 'sentence', 'Is there a student discount?', 'Tem desconto para estudante?', '/ɪz ðɛr ə ˈstuːdənt ˈdɪskaʊnt/', 'Leve a carteirinha: "student ID".', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":28,"role":"subject","surface":"a student discount?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"student","pos":"noun","ipa":"/ˈstuːdənt/","gloss":"estudante"},{"surface":"discount","pos":"noun","ipa":"/ˈdɪskaʊnt/","gloss":"desconto"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-03', 'lesson-travel-a2-25', 3, 'sentence', 'What time does the tour start?', 'Que horas começa o passeio?', '/wʌt taɪm dʌz ðə tʊr stɑːrt/', '"Tour" = passeio guiado. "Guide" = guia.', '[{"start":0,"end":9,"role":"adverbial","surface":"What time"},{"start":10,"end":14,"role":"predicate_verb","surface":"does"},{"start":15,"end":23,"role":"subject","surface":"the tour"},{"start":24,"end":30,"role":"predicate_verb","surface":"start?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"tour","pos":"noun","ipa":"/tʊr/","gloss":"passeio guiado"},{"surface":"start","pos":"verb","ipa":"/stɑːrt/","gloss":"começar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-04', 'lesson-travel-a2-25', 4, 'sentence', 'Is there a tour in Portuguese?', 'Tem passeio em português?', '/ɪz ðɛr ə tʊr ɪn ˌpɔːrtʃəˈɡiːz/', '"In" + idioma: in English, in Portuguese, in Spanish.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":15,"role":"subject","surface":"a tour"},{"start":16,"end":30,"role":"adverbial","surface":"in Portuguese?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"tour","pos":"noun","ipa":"/tʊr/","gloss":"passeio guiado"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"Portuguese","pos":"proper noun","ipa":"/ˌpɔːrtʃəˈɡiːz/","gloss":"português"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-05', 'lesson-travel-a2-25', 5, 'sentence', 'Do I need to book in advance?', 'Preciso reservar com antecedência?', '/duː aɪ niːd tuː bʊk ɪn ədˈvæns/', '"In advance" = com antecedência. "Book" = reservar.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":4,"role":"subject","surface":"I"},{"start":5,"end":9,"role":"predicate_verb","surface":"need"},{"start":10,"end":17,"role":"direct_object","surface":"to book"},{"start":18,"end":29,"role":"adverbial","surface":"in advance?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"book","pos":"verb","ipa":"/bʊk/","gloss":"reservar; livro"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"advance","pos":"noun","ipa":"/ədˈvæns/","gloss":"antecedência"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-06', 'lesson-travel-a2-25', 6, 'sentence', 'Can I take pictures here?', 'Posso tirar fotos aqui?', '/kæn aɪ teɪk ˈpɪktʃərz hɪr/', '"Take pictures" = tirar fotos (nunca "make pictures").', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":10,"role":"predicate_verb","surface":"take"},{"start":11,"end":19,"role":"direct_object","surface":"pictures"},{"start":20,"end":25,"role":"adverbial","surface":"here?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"pictures","pos":"noun","ipa":"/ˈpɪktʃərz/","gloss":"fotos"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-07', 'lesson-travel-a2-25', 7, 'sentence', 'Could you take a picture of us?', 'Poderia tirar uma foto nossa?', '/kʊd juː teɪk ə ˈpɪktʃər ʌv ʌs/', '"Of us" = de nós. Pedido clássico para turistas.', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Could"},{"start":6,"end":9,"role":"subject","surface":"you"},{"start":10,"end":14,"role":"predicate_verb","surface":"take"},{"start":15,"end":24,"role":"direct_object","surface":"a picture"},{"start":25,"end":31,"role":"adverbial","surface":"of us?"}]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"picture","pos":"noun","ipa":"/ˈpɪktʃər/","gloss":"foto"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-08', 'lesson-travel-a2-25', 8, 'sentence', 'How long does the tour take?', 'Quanto tempo dura o passeio?', '/haʊ lɔːŋ dʌz ðə tʊr teɪk/', '"Take" + tempo = durar, levar.', '[{"start":0,"end":8,"role":"adverbial","surface":"How long"},{"start":9,"end":13,"role":"predicate_verb","surface":"does"},{"start":14,"end":22,"role":"subject","surface":"the tour"},{"start":23,"end":28,"role":"predicate_verb","surface":"take?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"tour","pos":"noun","ipa":"/tʊr/","gloss":"passeio guiado"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-09', 'lesson-travel-a2-25', 9, 'sentence', 'Where does the tour meet?', 'Onde é o ponto de encontro do passeio?', '/wɛr dʌz ðə tʊr miːt/', '"Meet" = encontrar-se, reunir-se.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":10,"role":"predicate_verb","surface":"does"},{"start":11,"end":19,"role":"subject","surface":"the tour"},{"start":20,"end":25,"role":"predicate_verb","surface":"meet?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"tour","pos":"noun","ipa":"/tʊr/","gloss":"passeio guiado"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-25-10', 'lesson-travel-a2-25', 10, 'sentence', 'Is it open on Mondays?', 'Abre às segundas?', '/ɪz ɪt ˈoʊpən ɑːn ˈmʌndeɪz/', '"On" + dia da semana; no plural indica "todas as segundas".', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":5,"role":"subject","surface":"it"},{"start":6,"end":10,"role":"predicate_adj","surface":"open"},{"start":11,"end":22,"role":"adverbial","surface":"on Mondays?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"Mondays","pos":"proper noun","ipa":"/ˈmʌndeɪz/","gloss":"segundas-feiras"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-26', 'course-travel-a2', 26, 'Praia e piscina', 'Alugar guarda-sol, segurança no mar e piscina do hotel.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-26-01', 'lesson-travel-a2-26', 1, 'sentence', 'How much is it to rent an umbrella?', 'Quanto custa alugar um guarda-sol?', '/haʊ mʌtʃ ɪz ɪt tuː rɛnt ən ʌmˈbrɛlə/', '"Rent" = alugar. "Beach umbrella" = guarda-sol.', '[{"start":0,"end":8,"role":"predicate_adj","surface":"How much"},{"start":9,"end":11,"role":"predicate_verb","surface":"is"},{"start":12,"end":14,"role":"subject","surface":"it"},{"start":15,"end":35,"role":"adverbial","surface":"to rent an umbrella?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"rent","pos":"verb","ipa":"/rɛnt/","gloss":"alugar"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"umbrella","pos":"noun","ipa":"/ʌmˈbrɛlə/","gloss":"guarda-chuva"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-02', 'lesson-travel-a2-26', 2, 'sentence', 'Is it safe to swim here?', 'É seguro nadar aqui?', '/ɪz ɪt seɪf tuː swɪm hɪr/', 'Pergunte antes de entrar no mar. "Lifeguard" = salva-vidas.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":5,"role":"subject","surface":"it"},{"start":6,"end":10,"role":"predicate_adj","surface":"safe"},{"start":11,"end":24,"role":"adverbial","surface":"to swim here?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"safe","pos":"adjective","ipa":"/seɪf/","gloss":"seguro"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"swim","pos":"verb","ipa":"/swɪm/","gloss":"nadar"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-03', 'lesson-travel-a2-26', 3, 'sentence', 'The water is too cold.', 'A água está fria demais.', '/ðə ˈwɔːtər ɪz tuː koʊld/', '"Too" + adjetivo = demais.', '[{"start":0,"end":9,"role":"subject","surface":"The water"},{"start":10,"end":12,"role":"predicate_verb","surface":"is"},{"start":13,"end":22,"role":"predicate_adj","surface":"too cold."}]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"water","pos":"noun","ipa":"/ˈwɔːtər/","gloss":"água"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-04', 'lesson-travel-a2-26', 4, 'sentence', 'Watch out for the waves.', 'Cuidado com as ondas.', '/wɑːtʃ aʊt fɔːr ðə weɪvz/', '"Watch out for" = tome cuidado com.', '[{"start":0,"end":9,"role":"predicate_verb","surface":"Watch out"},{"start":10,"end":24,"role":"adverbial","surface":"for the waves."}]'::jsonb, '[{"surface":"Watch","pos":"noun","ipa":"/wɑːtʃ/","gloss":"relógio de pulso"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"waves","pos":"noun","ipa":"/weɪvz/","gloss":"ondas"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-05', 'lesson-travel-a2-26', 5, 'sentence', 'Don''t forget your sunscreen.', 'Não esqueça o protetor solar.', '/doʊnt fərˈɡɛt jʊr ˈsʌnskriːn/', 'Imperativo negativo: "don''t" + verbo base.', '[{"start":0,"end":12,"role":"predicate_verb","surface":"Don''t forget"},{"start":13,"end":28,"role":"direct_object","surface":"your sunscreen."}]'::jsonb, '[{"surface":"Don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"forget","pos":"verb","ipa":"/fərˈɡɛt/","gloss":"esquecer"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"sunscreen","pos":"noun","ipa":"/ˈsʌnskriːn/","gloss":"protetor solar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-06', 'lesson-travel-a2-26', 6, 'sentence', 'What time does the pool close?', 'Que horas fecha a piscina?', '/wʌt taɪm dʌz ðə puːl kloʊz/', '"Pool" = piscina.', '[{"start":0,"end":9,"role":"adverbial","surface":"What time"},{"start":10,"end":14,"role":"predicate_verb","surface":"does"},{"start":15,"end":23,"role":"subject","surface":"the pool"},{"start":24,"end":30,"role":"predicate_verb","surface":"close?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"pool","pos":"noun","ipa":"/puːl/","gloss":"piscina"},{"surface":"close","pos":"verb","ipa":"/kloʊz/","gloss":"fechar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-07', 'lesson-travel-a2-26', 7, 'sentence', 'Can I get a pool towel?', 'Pode me dar uma toalha de piscina?', '/kæn aɪ ɡɛt ə puːl ˈtaʊəl/', 'Muitos hotéis têm toalhas próprias para a piscina.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"get"},{"start":10,"end":23,"role":"direct_object","surface":"a pool towel?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"pool","pos":"noun","ipa":"/puːl/","gloss":"piscina"},{"surface":"towel","pos":"noun","ipa":"/ˈtaʊəl/","gloss":"toalha"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-08', 'lesson-travel-a2-26', 8, 'sentence', 'I got sunburned.', 'Eu me queimei de sol.', '/aɪ ɡɑːt ˈsʌnbɜːrnd/', '"Get" + particípio = ficar: "got sunburned" = ficou queimado de sol.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":16,"role":"predicate_verb","surface":"got sunburned."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"sunburned","pos":"adjective","ipa":"/ˈsʌnbɜːrnd/","gloss":"queimado de sol"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-09', 'lesson-travel-a2-26', 9, 'sentence', 'Where are the showers?', 'Onde ficam as duchas?', '/wɛr ɑːr ðə ˈʃaʊərz/', '"Showers" = chuveiros, duchas.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":9,"role":"predicate_verb","surface":"are"},{"start":10,"end":22,"role":"subject","surface":"the showers?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"showers","pos":"noun","ipa":"/ˈʃaʊərz/","gloss":"duchas"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-26-10', 'lesson-travel-a2-26', 10, 'sentence', 'Let''s watch the sunset.', 'Vamos ver o pôr do sol.', '/lɛts wɑːtʃ ðə ˈsʌnsɛt/', '"Let''s" + verbo = vamos. "Sunset" = pôr do sol; "sunrise" = nascer.', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Let''s"},{"start":6,"end":11,"role":"predicate_verb","surface":"watch"},{"start":12,"end":23,"role":"direct_object","surface":"the sunset."}]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"watch","pos":"noun","ipa":"/wɑːtʃ/","gloss":"relógio de pulso"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"sunset","pos":"noun","ipa":"/ˈsʌnsɛt/","gloss":"pôr do sol"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-27', 'course-travel-a2', 27, 'Revisão: a viagem inteira', 'Uma frase-chave de cada situação da viagem.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-27-01', 'lesson-travel-a2-27', 1, 'sentence', 'I''d like to check in, please.', 'Eu queria fazer o check-in, por favor.', '/aɪd laɪk tuː tʃɛk ɪn pliːz/', 'Revisão do aeroporto: "I''d like to" é o pedido educado para quase tudo.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"I''d like"},{"start":9,"end":21,"role":"direct_object","surface":"to check in,"},{"start":22,"end":29,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-02', 'lesson-travel-a2-27', 2, 'sentence', 'What is the purpose of your visit?', 'Qual o motivo da sua visita?', '/wʌt ɪz ðə ˈpɜːrpəs ʌv jʊr ˈvɪzɪt/', 'Revisão da imigração: responda "tourism" ou "business".', '[{"start":0,"end":4,"role":"predicate_adj","surface":"What"},{"start":5,"end":7,"role":"predicate_verb","surface":"is"},{"start":8,"end":34,"role":"subject","surface":"the purpose of your visit?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"purpose","pos":"noun","ipa":"/ˈpɜːrpəs/","gloss":"propósito, motivo"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"visit","pos":"noun","ipa":"/ˈvɪzɪt/","gloss":"visita"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-03', 'lesson-travel-a2-27', 3, 'sentence', 'My suitcase didn''t arrive.', 'Minha mala não chegou.', '/maɪ ˈsuːtkeɪs ˈdɪdənt əˈraɪv/', 'Revisão de bagagem: passado negativo com "didn''t" + verbo base.', '[{"start":0,"end":11,"role":"subject","surface":"My suitcase"},{"start":12,"end":26,"role":"predicate_verb","surface":"didn''t arrive."}]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"suitcase","pos":"noun","ipa":"/ˈsuːtkeɪs/","gloss":"mala"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"arrive","pos":"verb","ipa":"/əˈraɪv/","gloss":"chegar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-04', 'lesson-travel-a2-27', 4, 'sentence', 'Can I check in early?', 'Posso fazer o check-in mais cedo?', '/kæn aɪ tʃɛk ɪn ˈɜːrli/', 'Revisão do hotel: "check in" (verbo) × "check-in" (substantivo, com hífen).', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":14,"role":"predicate_verb","surface":"check in"},{"start":15,"end":21,"role":"adverbial","surface":"early?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-05', 'lesson-travel-a2-27', 5, 'sentence', 'Excuse me, how do I get to the station?', 'Com licença, como chego à estação?', '/ɪkˈskjuːz miː haʊ duː aɪ ɡɛt tuː ðə ˈsteɪʃən/', 'Revisão de direções: "How do I get to" + lugar.', '[{"start":0,"end":10,"role":"discourse_marker","surface":"Excuse me,"},{"start":11,"end":14,"role":"adverbial","surface":"how"},{"start":15,"end":17,"role":"predicate_verb","surface":"do"},{"start":18,"end":19,"role":"subject","surface":"I"},{"start":20,"end":23,"role":"predicate_verb","surface":"get"},{"start":24,"end":39,"role":"adverbial","surface":"to the station?"}]'::jsonb, '[{"surface":"Excuse","pos":"verb","ipa":"/ɪkˈskjuːz/","gloss":"desculpar (excuse me = com licença)"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"station","pos":"noun","ipa":"/ˈsteɪʃən/","gloss":"estação"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-06', 'lesson-travel-a2-27', 6, 'sentence', 'I''ll have the chicken, please.', 'Vou querer o frango, por favor.', '/aɪl hæv ðə ˈtʃɪkən pliːz/', 'Revisão do restaurante: "I''ll have" para pedir.', '[{"start":0,"end":9,"role":"predicate_verb","surface":"I''ll have"},{"start":10,"end":22,"role":"direct_object","surface":"the chicken,"},{"start":23,"end":30,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"chicken","pos":"noun","ipa":"/ˈtʃɪkən/","gloss":"frango"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-07', 'lesson-travel-a2-27', 7, 'sentence', 'Can we have the check, please?', 'Pode trazer a conta, por favor?', '/kæn wiː hæv ðə tʃɛk pliːz/', 'Revisão da conta: "check" (EUA) ou "bill" (Reino Unido).', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":6,"role":"subject","surface":"we"},{"start":7,"end":11,"role":"predicate_verb","surface":"have"},{"start":12,"end":22,"role":"direct_object","surface":"the check,"},{"start":23,"end":30,"role":"discourse_marker","surface":"please?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-08', 'lesson-travel-a2-27', 8, 'sentence', 'I need something for a headache.', 'Preciso de algo para dor de cabeça.', '/aɪ niːd ˈsʌmθɪŋ fɔːr ə ˈhɛdeɪk/', 'Revisão da farmácia: "something for" + sintoma.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"need"},{"start":7,"end":16,"role":"direct_object","surface":"something"},{"start":17,"end":32,"role":"adverbial","surface":"for a headache."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"something","pos":"pronoun","ipa":"/ˈsʌmθɪŋ/","gloss":"alguma coisa"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"headache","pos":"noun","ipa":"/ˈhɛdeɪk/","gloss":"dor de cabeça"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-09', 'lesson-travel-a2-27', 9, 'sentence', 'Can I try it on?', 'Posso experimentar?', '/kæn aɪ traɪ ɪt ɑːn/', 'Revisão de compras: "try on" com o objeto no meio.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"try"},{"start":10,"end":12,"role":"direct_object","surface":"it"},{"start":13,"end":16,"role":"predicate_verb","surface":"on?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"try","pos":"verb","ipa":"/traɪ/","gloss":"experimentar, tentar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-27-10', 'lesson-travel-a2-27', 10, 'sentence', 'Help! Call an ambulance!', 'Socorro! Chame uma ambulância!', '/hɛlp kɔːl ən ˈæmbjələns/', 'Revisão de emergência: memorize esta frase antes de viajar.', '[{"start":0,"end":5,"role":"discourse_marker","surface":"Help!"},{"start":6,"end":10,"role":"predicate_verb","surface":"Call"},{"start":11,"end":24,"role":"direct_object","surface":"an ambulance!"}]'::jsonb, '[{"surface":"Help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"Call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"ambulance","pos":"noun","ipa":"/ˈæmbjələns/","gloss":"ambulância"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
