-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-travel-a2', 'travel-no-stress-a2', 'Viagem sem Aperto', 'Aeroporto, hotel, transporte, restaurante, farmácia e emergências: as frases que você realmente precisa na viagem.', 'Situações de viagem com o que você diz e o que ouve do outro lado: despachar mala, resolver problema no quarto, pegar metrô, pedir no restaurante e no café, comprar remédio, pedir direções e lidar com emergências.', 'A2', 'travel', 2, 'viagem', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-08', 'course-travel-a2', 8, 'Café e padaria', 'Pedir café, tamanhos, leite e algo para comer.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-08-01', 'lesson-travel-a2-08', 1, 'sentence', 'Can I get a large coffee?', 'Pode me ver um café grande?', '/kæn aɪ ɡɛt ə lɑːrdʒ ˈkɔːfi/', '"Can I get" é o jeito mais comum de pedir no balcão nos EUA. Tamanhos: small, medium, large.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"get"},{"start":10,"end":25,"role":"direct_object","surface":"a large coffee?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"large","pos":"adjective","ipa":"/lɑːrdʒ/","gloss":"grande"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-02', 'lesson-travel-a2-08', 2, 'sentence', 'For here or to go?', 'Para comer aqui ou para levar?', '/fɔːr hɪr ɔːr tuː ɡoʊ/', 'Pergunta do atendente. Responda "For here" (aqui) ou "To go" (para levar).', '[{"start":0,"end":8,"role":"adverbial","surface":"For here"},{"start":9,"end":11,"role":"discourse_marker","surface":"or"},{"start":12,"end":18,"role":"adverbial","surface":"to go?"}]'::jsonb, '[{"surface":"For","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"or","pos":"conjunction","ipa":"/ɔːr/","gloss":"ou"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-03', 'lesson-travel-a2-08', 3, 'sentence', 'With milk, please.', 'Com leite, por favor.', '/wɪð mɪlk pliːz/', '"With" = com; "without" = sem. Vale para açúcar: "no sugar" = sem açúcar.', '[{"start":0,"end":10,"role":"adverbial","surface":"With milk,"},{"start":11,"end":18,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"With","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"milk","pos":"noun","ipa":"/mɪlk/","gloss":"leite"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-04', 'lesson-travel-a2-08', 4, 'sentence', 'Do you have oat milk?', 'Vocês têm leite de aveia?', '/duː juː hæv oʊt mɪlk/', 'Leites vegetais: oat (aveia), almond (amêndoa), soy (soja).', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":6,"role":"subject","surface":"you"},{"start":7,"end":11,"role":"predicate_verb","surface":"have"},{"start":12,"end":21,"role":"direct_object","surface":"oat milk?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"oat","pos":"noun","ipa":"/oʊt/","gloss":"aveia"},{"surface":"milk","pos":"noun","ipa":"/mɪlk/","gloss":"leite"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-05', 'lesson-travel-a2-08', 5, 'sentence', 'What''s the name for the order?', 'Qual o nome para o pedido?', '/wʌts ðə neɪm fɔːr ðə ˈɔːrdər/', 'Em cafés dos EUA escrevem seu nome no copo. Soletre se precisar.', '[{"start":0,"end":6,"role":"predicate_verb","surface":"What''s"},{"start":7,"end":15,"role":"subject","surface":"the name"},{"start":16,"end":30,"role":"adverbial","surface":"for the order?"}]'::jsonb, '[{"surface":"What''s","pos":"pronoun","ipa":"/wʌts/","gloss":"qual é"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"name","pos":"noun","ipa":"/neɪm/","gloss":"nome"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"order","pos":"verb","ipa":"/ˈɔːrdər/","gloss":"pedir (comida)"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-06', 'lesson-travel-a2-08', 6, 'sentence', 'I''ll have a croissant too.', 'Vou querer um croissant também.', '/aɪl hæv ə krəˈsɑːnt tuː/', '"Too" no fim da frase = também.', '[{"start":0,"end":9,"role":"predicate_verb","surface":"I''ll have"},{"start":10,"end":21,"role":"direct_object","surface":"a croissant"},{"start":22,"end":26,"role":"adverbial","surface":"too."}]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"croissant","pos":"noun","ipa":"/krəˈsɑːnt/","gloss":"croissant"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-07', 'lesson-travel-a2-08', 7, 'sentence', 'Is it fresh?', 'Está fresquinho?', '/ɪz ɪt frɛʃ/', '"Fresh" = fresco, feito hoje. Pergunta comum na padaria.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":5,"role":"subject","surface":"it"},{"start":6,"end":12,"role":"predicate_adj","surface":"fresh?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"fresh","pos":"adjective","ipa":"/frɛʃ/","gloss":"fresco"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-08', 'lesson-travel-a2-08', 8, 'sentence', 'Can you heat it up?', 'Pode esquentar?', '/kæn juː hiːt ɪt ʌp/', '"Heat up" = esquentar (phrasal verb). O objeto vai no meio: "heat it up".', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"heat"},{"start":13,"end":15,"role":"direct_object","surface":"it"},{"start":16,"end":19,"role":"predicate_verb","surface":"up?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"heat","pos":"verb","ipa":"/hiːt/","gloss":"aquecer"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-09', 'lesson-travel-a2-08', 9, 'sentence', 'Is there wifi here?', 'Tem wi-fi aqui?', '/ɪz ðɛr ˈwaɪfaɪ hɪr/', 'Pronúncia americana: /ˈwaɪfaɪ/. Pergunte a senha: "What''s the password?".', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":13,"role":"subject","surface":"wifi"},{"start":14,"end":19,"role":"adverbial","surface":"here?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"wifi","pos":"noun","ipa":"/ˈwaɪfaɪ/","gloss":"wi-fi"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-08-10', 'lesson-travel-a2-08', 10, 'sentence', 'What''s the wifi password?', 'Qual a senha do wi-fi?', '/wʌts ðə ˈwaɪfaɪ ˈpæswɜːrd/', '"Password" = senha. Resposta costuma vir no recibo.', '[{"start":0,"end":6,"role":"predicate_verb","surface":"What''s"},{"start":7,"end":25,"role":"subject","surface":"the wifi password?"}]'::jsonb, '[{"surface":"What''s","pos":"pronoun","ipa":"/wʌts/","gloss":"qual é"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"wifi","pos":"noun","ipa":"/ˈwaɪfaɪ/","gloss":"wi-fi"},{"surface":"password","pos":"noun","ipa":"/ˈpæswɜːrd/","gloss":"senha"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-09', 'course-travel-a2', 9, 'Na farmácia', 'Explicar sintomas e pedir remédio sem receita.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-09-01', 'lesson-travel-a2-09', 1, 'sentence', 'I need something for a headache.', 'Preciso de algo para dor de cabeça.', '/aɪ niːd ˈsʌmθɪŋ fɔːr ə ˈhɛdeɪk/', '"Something for" + problema = remédio para. Outras dores: stomachache, toothache, backache.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"need"},{"start":7,"end":16,"role":"direct_object","surface":"something"},{"start":17,"end":32,"role":"adverbial","surface":"for a headache."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"something","pos":"pronoun","ipa":"/ˈsʌmθɪŋ/","gloss":"alguma coisa"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"headache","pos":"noun","ipa":"/ˈhɛdeɪk/","gloss":"dor de cabeça"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-02', 'lesson-travel-a2-09', 2, 'sentence', 'I have a sore throat.', 'Estou com dor de garganta.', '/aɪ hæv ə sɔːr θroʊt/', 'Sintomas usam "have": I have a fever, I have a cough.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"have"},{"start":7,"end":21,"role":"direct_object","surface":"a sore throat."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"sore","pos":"adjective","ipa":"/sɔːr/","gloss":"dolorido"},{"surface":"throat","pos":"noun","ipa":"/θroʊt/","gloss":"garganta"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-03', 'lesson-travel-a2-09', 3, 'sentence', 'I''ve had a fever since yesterday.', 'Estou com febre desde ontem.', '/aɪv hæd ə ˈfiːvər sɪns ˈjɛstərdeɪ/', 'Present perfect + "since" para algo que começou no passado e continua.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"I''ve had"},{"start":9,"end":16,"role":"direct_object","surface":"a fever"},{"start":17,"end":33,"role":"adverbial","surface":"since yesterday."}]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"fever","pos":"noun","ipa":"/ˈfiːvər/","gloss":"febre"},{"surface":"since","pos":"preposition","ipa":"/sɪns/","gloss":"desde"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-04', 'lesson-travel-a2-09', 4, 'sentence', 'Do I need a prescription?', 'Preciso de receita?', '/duː aɪ niːd ə prɪˈskrɪpʃən/', '"Prescription" = receita médica. Sem receita: "over the counter".', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":4,"role":"subject","surface":"I"},{"start":5,"end":9,"role":"predicate_verb","surface":"need"},{"start":10,"end":25,"role":"direct_object","surface":"a prescription?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"prescription","pos":"noun","ipa":"/prɪˈskrɪpʃən/","gloss":"receita médica"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-05', 'lesson-travel-a2-09', 5, 'sentence', 'How often should I take it?', 'De quanto em quanto tempo devo tomar?', '/haʊ ˈɔːfən ʃʊd aɪ teɪk ɪt/', '"Take" é o verbo para tomar remédio. "How often" = com que frequência.', '[{"start":0,"end":9,"role":"adverbial","surface":"How often"},{"start":10,"end":16,"role":"predicate_verb","surface":"should"},{"start":17,"end":18,"role":"subject","surface":"I"},{"start":19,"end":23,"role":"predicate_verb","surface":"take"},{"start":24,"end":27,"role":"direct_object","surface":"it?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"often","pos":"adverb","ipa":"/ˈɔːfən/","gloss":"frequentemente"},{"surface":"should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-06', 'lesson-travel-a2-09', 6, 'sentence', 'Take two pills every six hours.', 'Tome dois comprimidos a cada seis horas.', '/teɪk tuː pɪlz ˈɛvri sɪks aʊərz/', 'Fala do farmacêutico. "Every" + número de horas = a cada.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Take"},{"start":5,"end":14,"role":"direct_object","surface":"two pills"},{"start":15,"end":31,"role":"adverbial","surface":"every six hours."}]'::jsonb, '[{"surface":"Take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"pills","pos":"noun","ipa":"/pɪlz/","gloss":"comprimidos"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"six","pos":"numeral","ipa":"/sɪks/","gloss":"seis"},{"surface":"hours","pos":"noun","ipa":"/aʊərz/","gloss":"horas"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-07', 'lesson-travel-a2-09', 7, 'sentence', 'Is it safe for children?', 'É seguro para crianças?', '/ɪz ɪt seɪf fɔːr ˈtʃɪldrən/', '"Safe" = seguro (sem perigo). "Children" é o plural irregular de "child".', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":5,"role":"subject","surface":"it"},{"start":6,"end":10,"role":"predicate_adj","surface":"safe"},{"start":11,"end":24,"role":"adverbial","surface":"for children?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"safe","pos":"adjective","ipa":"/seɪf/","gloss":"seguro"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"children","pos":"noun","ipa":"/ˈtʃɪldrən/","gloss":"crianças, filhos"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-08', 'lesson-travel-a2-09', 8, 'sentence', 'I''m allergic to penicillin.', 'Tenho alergia a penicilina.', '/aɪm əˈlɜːrdʒɪk tuː ˌpɛnɪˈsɪlɪn/', 'Informação de segurança: diga antes de aceitar qualquer remédio.', '[{"start":0,"end":3,"role":"subject","surface":"I''m"},{"start":4,"end":12,"role":"predicate_adj","surface":"allergic"},{"start":13,"end":27,"role":"adverbial","surface":"to penicillin."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"allergic","pos":"adjective","ipa":"/əˈlɜːrdʒɪk/","gloss":"alérgico"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"penicillin","pos":"noun","ipa":"/ˌpɛnɪˈsɪlɪn/","gloss":"penicilina"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-09', 'lesson-travel-a2-09', 9, 'sentence', 'Does it make you sleepy?', 'Dá sono?', '/dʌz ɪt meɪk juː ˈsliːpi/', '"Make you" + adjetivo = deixar você. "Drowsy" é o termo da bula.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Does"},{"start":5,"end":7,"role":"subject","surface":"it"},{"start":8,"end":12,"role":"predicate_verb","surface":"make"},{"start":13,"end":16,"role":"direct_object","surface":"you"},{"start":17,"end":24,"role":"predicate_adj","surface":"sleepy?"}]'::jsonb, '[{"surface":"Does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"sleepy","pos":"adjective","ipa":"/ˈsliːpi/","gloss":"com sono"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-09-10', 'lesson-travel-a2-09', 10, 'sentence', 'Where can I find sunscreen?', 'Onde encontro protetor solar?', '/wɛr kæn aɪ faɪnd ˈsʌnskriːn/', '"Where can I find" é útil em qualquer loja. "Aisle" = corredor.', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":9,"role":"predicate_verb","surface":"can"},{"start":10,"end":11,"role":"subject","surface":"I"},{"start":12,"end":16,"role":"predicate_verb","surface":"find"},{"start":17,"end":27,"role":"direct_object","surface":"sunscreen?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"find","pos":"verb","ipa":"/faɪnd/","gloss":"encontrar"},{"surface":"sunscreen","pos":"noun","ipa":"/ˈsʌnskriːn/","gloss":"protetor solar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-10', 'course-travel-a2', 10, 'Pedindo direções', 'Perguntar o caminho e entender a resposta.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-10-01', 'lesson-travel-a2-10', 1, 'sentence', 'Excuse me, how do I get to the station?', 'Com licença, como chego à estação?', '/ɪkˈskjuːz miː haʊ duː aɪ ɡɛt tuː ðə ˈsteɪʃən/', '"How do I get to" = como chego a. Começar com "Excuse me" é o jeito educado de abordar alguém.', '[{"start":0,"end":10,"role":"discourse_marker","surface":"Excuse me,"},{"start":11,"end":14,"role":"adverbial","surface":"how"},{"start":15,"end":17,"role":"predicate_verb","surface":"do"},{"start":18,"end":19,"role":"subject","surface":"I"},{"start":20,"end":23,"role":"predicate_verb","surface":"get"},{"start":24,"end":39,"role":"adverbial","surface":"to the station?"}]'::jsonb, '[{"surface":"Excuse","pos":"verb","ipa":"/ɪkˈskjuːz/","gloss":"desculpar (excuse me = com licença)"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"station","pos":"noun","ipa":"/ˈsteɪʃən/","gloss":"estação"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-02', 'lesson-travel-a2-10', 2, 'sentence', 'Is it far from here?', 'É longe daqui?', '/ɪz ɪt fɑːr frʌm hɪr/', '"Far" = longe; "close" ou "near" = perto.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":5,"role":"subject","surface":"it"},{"start":6,"end":9,"role":"predicate_adj","surface":"far"},{"start":10,"end":20,"role":"adverbial","surface":"from here?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"far","pos":"adjective","ipa":"/fɑːr/","gloss":"longe"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-03', 'lesson-travel-a2-10', 3, 'sentence', 'It''s a ten minute walk.', 'São dez minutos a pé.', '/ɪts ə tɛn ˈmɪnɪt wɔːk/', '"Ten minute" fica no singular porque funciona como adjetivo de "walk".', '[{"start":0,"end":4,"role":"predicate_verb","surface":"It''s"},{"start":5,"end":23,"role":"predicate_adj","surface":"a ten minute walk."}]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"minute","pos":"noun","ipa":"/ˈmɪnɪt/","gloss":"minuto"},{"surface":"walk","pos":"noun","ipa":"/wɔːk/","gloss":"caminhada; andar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-04', 'lesson-travel-a2-10', 4, 'sentence', 'Go straight and turn left.', 'Siga reto e vire à esquerda.', '/ɡoʊ streɪt ænd tɜːrn lɛft/', 'Imperativo para direções: go straight (siga reto), turn left/right (vire).', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Go"},{"start":3,"end":11,"role":"adverbial","surface":"straight"},{"start":12,"end":15,"role":"discourse_marker","surface":"and"},{"start":16,"end":20,"role":"predicate_verb","surface":"turn"},{"start":21,"end":26,"role":"adverbial","surface":"left."}]'::jsonb, '[{"surface":"Go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"straight","pos":"adverb","ipa":"/streɪt/","gloss":"reto, em frente"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"turn","pos":"verb","ipa":"/tɜːrn/","gloss":"ligar (turn on)"},{"surface":"left","pos":"adverb","ipa":"/lɛft/","gloss":"à esquerda"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-05', 'lesson-travel-a2-10', 5, 'sentence', 'It''s on the corner.', 'Fica na esquina.', '/ɪts ɑːn ðə ˈkɔːrnər/', '"On the corner" = na esquina. "Across the street" = do outro lado da rua.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"It''s"},{"start":5,"end":19,"role":"adverbial","surface":"on the corner."}]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"corner","pos":"noun","ipa":"/ˈkɔːrnər/","gloss":"esquina"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-06', 'lesson-travel-a2-10', 6, 'sentence', 'Take the second right.', 'Pegue a segunda à direita.', '/teɪk ðə ˈsɛkənd raɪt/', '"Take the first/second right" = entre na primeira/segunda rua à direita.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Take"},{"start":5,"end":22,"role":"direct_object","surface":"the second right."}]'::jsonb, '[{"surface":"Take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"second","pos":"adjective","ipa":"/ˈsɛkənd/","gloss":"segundo"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-07', 'lesson-travel-a2-10', 7, 'sentence', 'You can''t miss it.', 'Não tem como errar.', '/juː kænt mɪs ɪt/', 'Frase comum no fim de uma explicação: o lugar é fácil de achar.', '[{"start":0,"end":3,"role":"subject","surface":"You"},{"start":4,"end":14,"role":"predicate_verb","surface":"can''t miss"},{"start":15,"end":18,"role":"direct_object","surface":"it."}]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"miss","pos":"verb","ipa":"/mɪs/","gloss":"errar, perder; sentir falta"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-08', 'lesson-travel-a2-10', 8, 'sentence', 'Can you show me on the map?', 'Pode me mostrar no mapa?', '/kæn juː ʃoʊ miː ɑːn ðə mæp/', '"Show me" = me mostrar. Útil quando a explicação fica confusa.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"show"},{"start":13,"end":15,"role":"indirect_object","surface":"me"},{"start":16,"end":27,"role":"adverbial","surface":"on the map?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"show","pos":"verb","ipa":"/ʃoʊ/","gloss":"aparecer (show up)"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"map","pos":"noun","ipa":"/mæp/","gloss":"mapa"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-09', 'lesson-travel-a2-10', 9, 'sentence', 'Sorry, I''m not from here.', 'Desculpe, não sou daqui.', '/ˈsɑːri aɪm nɑːt frʌm hɪr/', 'Resposta que você pode ouvir (ou dar) quando a pessoa não sabe o caminho.', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Sorry,"},{"start":7,"end":10,"role":"subject","surface":"I''m"},{"start":11,"end":25,"role":"adverbial","surface":"not from here."}]'::jsonb, '[{"surface":"Sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-10-10', 'lesson-travel-a2-10', 10, 'sentence', 'I think I''m lost.', 'Acho que estou perdido.', '/aɪ θɪŋk aɪm lɔːst/', '"Lost" = perdido. "I think" suaviza e pede ajuda sem dramatizar.', '[{"start":0,"end":7,"role":"discourse_marker","surface":"I think"},{"start":8,"end":11,"role":"subject","surface":"I''m"},{"start":12,"end":17,"role":"predicate_adj","surface":"lost."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-11', 'course-travel-a2', 11, 'Emergências', 'Pedir ajuda, ligar para emergência e registrar ocorrência.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-11-01', 'lesson-travel-a2-11', 1, 'sentence', 'Help! Call an ambulance!', 'Socorro! Chame uma ambulância!', '/hɛlp kɔːl ən ˈæmbjələns/', 'Nos EUA o número de emergência é 911; na Europa, 112.', '[{"start":0,"end":5,"role":"discourse_marker","surface":"Help!"},{"start":6,"end":10,"role":"predicate_verb","surface":"Call"},{"start":11,"end":24,"role":"direct_object","surface":"an ambulance!"}]'::jsonb, '[{"surface":"Help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"Call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"ambulance","pos":"noun","ipa":"/ˈæmbjələns/","gloss":"ambulância"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-02', 'lesson-travel-a2-11', 2, 'sentence', 'Someone stole my wallet.', 'Alguém roubou minha carteira.', '/ˈsʌmwʌn stoʊl maɪ ˈwɑːlɪt/', '"Stole" é o passado irregular de "steal" (roubar).', '[{"start":0,"end":7,"role":"subject","surface":"Someone"},{"start":8,"end":13,"role":"predicate_verb","surface":"stole"},{"start":14,"end":24,"role":"direct_object","surface":"my wallet."}]'::jsonb, '[{"surface":"Someone","pos":"pronoun","ipa":"/ˈsʌmwʌn/","gloss":"alguém"},{"surface":"stole","pos":"verb","ipa":"/stoʊl/","gloss":"roubou"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"wallet","pos":"noun","ipa":"/ˈwɑːlɪt/","gloss":"carteira"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-03', 'lesson-travel-a2-11', 3, 'sentence', 'I need to report a theft.', 'Preciso registrar um roubo.', '/aɪ niːd tuː rɪˈpɔːrt ə θɛft/', '"Report" = registrar ocorrência. "Theft" = furto, roubo.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"need"},{"start":7,"end":25,"role":"direct_object","surface":"to report a theft."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"report","pos":"verb","ipa":"/rɪˈpɔːrt/","gloss":"registrar, relatar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"theft","pos":"noun","ipa":"/θɛft/","gloss":"furto, roubo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-04', 'lesson-travel-a2-11', 4, 'sentence', 'Where is the nearest hospital?', 'Onde fica o hospital mais próximo?', '/wɛr ɪz ðə ˈnɪrɪst ˈhɑːspɪtəl/', '"The nearest" = o mais próximo (superlativo de "near").', '[{"start":0,"end":5,"role":"adverbial","surface":"Where"},{"start":6,"end":8,"role":"predicate_verb","surface":"is"},{"start":9,"end":30,"role":"subject","surface":"the nearest hospital?"}]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"nearest","pos":"adjective","ipa":"/ˈnɪrɪst/","gloss":"mais próximo"},{"surface":"hospital","pos":"noun","ipa":"/ˈhɑːspɪtəl/","gloss":"hospital"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-05', 'lesson-travel-a2-11', 5, 'sentence', 'I lost my passport.', 'Perdi meu passaporte.', '/aɪ lɔːst maɪ ˈpæspɔːrt/', '"Lost" = passado de "lose" (perder). Procure a embaixada: "embassy".', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"lost"},{"start":7,"end":19,"role":"direct_object","surface":"my passport."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"lost","pos":"adjective","ipa":"/lɔːst/","gloss":"perdido; perdeu"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"passport","pos":"noun","ipa":"/ˈpæspɔːrt/","gloss":"passaporte"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-06', 'lesson-travel-a2-11', 6, 'sentence', 'Can you call the police?', 'Pode chamar a polícia?', '/kæn juː kɔːl ðə pəˈliːs/', '"Police" é sempre plural no verbo: "the police are coming".', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"call"},{"start":13,"end":24,"role":"direct_object","surface":"the police?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"police","pos":"noun","ipa":"/pəˈliːs/","gloss":"polícia"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-07', 'lesson-travel-a2-11', 7, 'sentence', 'My friend isn''t breathing.', 'Meu amigo não está respirando.', '/maɪ frɛnd ˈɪzənt ˈbriːðɪŋ/', 'Presente contínuo para o que está acontecendo agora. Fale devagar e claro.', '[{"start":0,"end":9,"role":"subject","surface":"My friend"},{"start":10,"end":26,"role":"predicate_verb","surface":"isn''t breathing."}]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"friend","pos":"noun","ipa":"/frɛnd/","gloss":"amigo, amiga"},{"surface":"isn''t","pos":"auxiliary verb","ipa":"/ˈɪzənt/","gloss":"não é, não está"},{"surface":"breathing","pos":"verb","ipa":"/ˈbriːðɪŋ/","gloss":"respirando"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-08', 'lesson-travel-a2-11', 8, 'sentence', 'I don''t speak English well.', 'Eu não falo inglês bem.', '/aɪ doʊnt spiːk ˈɪŋɡlɪʃ wɛl/', 'Diga isso logo no começo: a pessoa vai falar mais devagar.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":13,"role":"predicate_verb","surface":"don''t speak"},{"start":14,"end":21,"role":"direct_object","surface":"English"},{"start":22,"end":27,"role":"adverbial","surface":"well."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"speak","pos":"verb","ipa":"/spiːk/","gloss":"falar"},{"surface":"English","pos":"proper noun","ipa":"/ˈɪŋɡlɪʃ/","gloss":"inglês"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-09', 'lesson-travel-a2-11', 9, 'sentence', 'Please speak slowly.', 'Por favor, fale devagar.', '/pliːz spiːk ˈsloʊli/', '"Slowly" = devagar (advérbio de "slow").', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Please"},{"start":7,"end":12,"role":"predicate_verb","surface":"speak"},{"start":13,"end":20,"role":"adverbial","surface":"slowly."}]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"speak","pos":"verb","ipa":"/spiːk/","gloss":"falar"},{"surface":"slowly","pos":"adverb","ipa":"/ˈsloʊli/","gloss":"devagar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-11-10', 'lesson-travel-a2-11', 10, 'sentence', 'I need to contact my embassy.', 'Preciso falar com minha embaixada.', '/aɪ niːd tuː ˈkɑːntækt maɪ ˈɛmbəsi/', '"Contact" = entrar em contato. A embaixada ajuda com passaporte perdido.', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":6,"role":"predicate_verb","surface":"need"},{"start":7,"end":29,"role":"direct_object","surface":"to contact my embassy."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"contact","pos":"verb","ipa":"/ˈkɑːntækt/","gloss":"contatar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"embassy","pos":"noun","ipa":"/ˈɛmbəsi/","gloss":"embaixada"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
