-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-health-a2', 'health-a2', 'Saúde e Bem-estar', 'Marcar consulta, explicar sintomas, entender a receita, ir ao dentista, cuidar do corpo e lidar com o hospital.', 'O inglês que você precisa quando o assunto é saúde: marcar horário, descrever o que sente, entender o que o médico diz, dentista, academia e seguro saúde. Cada frase explica a estrutura ou a expressão usada.', 'A2', 'survival', 6, 'dia-a-dia', 4, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-health-a2-01', 'course-health-a2', 1, 'Marcando consulta', 'Ligar, pedir horário e confirmar.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-health-a2-01-01', 'lesson-health-a2-01', 1, 'sentence', 'I''d like to make an appointment.', 'Eu gostaria de marcar uma consulta.', '/aɪd laɪk tuː meɪk ən əˈpɔɪntmənt/', '"Make an appointment" = marcar horário (médico, dentista, cabeleireiro).', '[]'::jsonb, '[{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"appointment","pos":"noun","ipa":"/əˈpɔɪntmənt/","gloss":"consulta, horário marcado"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-02', 'lesson-health-a2-01', 2, 'sentence', 'Is the doctor available tomorrow?', 'O médico tem horário amanhã?', '/ɪz ðə ˈdɑːktər əˈveɪləbəl təˈmɑːroʊ/', '"Available" = disponível.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"doctor","pos":"noun","ipa":"/ˈdɑːktər/","gloss":"médico"},{"surface":"available","pos":"adjective","ipa":"/əˈveɪləbəl/","gloss":"disponível"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-03', 'lesson-health-a2-01', 3, 'sentence', 'What''s the earliest appointment?', 'Qual é o horário mais cedo?', '/wʌts ðə ˈɜːrliɪst əˈpɔɪntmənt/', 'Superlativo: "early" → "earliest".', '[]'::jsonb, '[{"surface":"What''s","pos":"pronoun","ipa":"/wʌts/","gloss":"qual é"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"earliest","pos":"adjective","ipa":"/ˈɜːrliɪst/","gloss":"mais cedo"},{"surface":"appointment","pos":"noun","ipa":"/əˈpɔɪntmənt/","gloss":"consulta, horário marcado"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-04', 'lesson-health-a2-01', 4, 'sentence', 'Is this your first visit?', 'É a sua primeira consulta?', '/ɪz ðɪs jʊr fɜːrst ˈvɪzɪt/', '"Visit" = consulta, visita.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"visit","pos":"noun","ipa":"/ˈvɪzɪt/","gloss":"visita"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-05', 'lesson-health-a2-01', 5, 'sentence', 'Do you have health insurance?', 'Você tem plano de saúde?', '/duː juː hæv hɛlθ ɪnˈʃʊrəns/', '"Health insurance" = plano/seguro saúde.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"health","pos":"noun","ipa":"/hɛlθ/","gloss":"saúde"},{"surface":"insurance","pos":"noun","ipa":"/ɪnˈʃʊrəns/","gloss":"seguro"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-06', 'lesson-health-a2-01', 6, 'sentence', 'Please arrive fifteen minutes early.', 'Por favor, chegue quinze minutos antes.', '/pliːz əˈraɪv ˌfɪfˈtiːn ˈmɪnɪts ˈɜːrli/', 'Instrução comum da recepção.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"arrive","pos":"verb","ipa":"/əˈraɪv/","gloss":"chegar"},{"surface":"fifteen","pos":"numeral","ipa":"/ˌfɪfˈtiːn/","gloss":"quinze"},{"surface":"minutes","pos":"noun","ipa":"/ˈmɪnɪts/","gloss":"minutos"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-07', 'lesson-health-a2-01', 7, 'sentence', 'I need to reschedule my appointment.', 'Preciso remarcar minha consulta.', '/aɪ niːd tuː ˌriːˈskɛdʒuːl maɪ əˈpɔɪntmənt/', '"Reschedule" = remarcar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"reschedule","pos":"verb","ipa":"/ˌriːˈskɛdʒuːl/","gloss":"remarcar"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"appointment","pos":"noun","ipa":"/əˈpɔɪntmənt/","gloss":"consulta, horário marcado"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-08', 'lesson-health-a2-01', 8, 'sentence', 'Can I cancel for Friday?', 'Posso cancelar a de sexta?', '/kæn aɪ ˈkænsəl fɔːr ˈfraɪdeɪ/', '"For Friday" = a marcada para sexta.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"cancel","pos":"verb","ipa":"/ˈkænsəl/","gloss":"cancelar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"Friday","pos":"proper noun","ipa":"/ˈfraɪdeɪ/","gloss":"sexta-feira"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-09', 'lesson-health-a2-01', 9, 'sentence', 'Please fill out this form.', 'Por favor, preencha este formulário.', '/pliːz fɪl aʊt ðɪs fɔːrm/', '"Fill out" = preencher (EUA); Reino Unido: "fill in".', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"fill","pos":"verb","ipa":"/fɪl/","gloss":"preencher; obturar"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"form","pos":"noun","ipa":"/fɔːrm/","gloss":"formulário"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-01-10', 'lesson-health-a2-01', 10, 'sentence', 'The doctor will see you now.', 'O médico vai te atender agora.', '/ðə ˈdɑːktər wɪl siː juː naʊ/', '"See" = atender (paciente).', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"doctor","pos":"noun","ipa":"/ˈdɑːktər/","gloss":"médico"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-health-a2-02', 'course-health-a2', 2, 'No médico: sintomas', 'Descrever o que você sente e há quanto tempo.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-health-a2-02-01', 'lesson-health-a2-02', 1, 'sentence', 'What seems to be the problem?', 'Qual parece ser o problema?', '/wʌt siːmz tuː biː ðə ˈprɑːbləm/', 'Pergunta de abertura do médico.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"seems","pos":"verb","ipa":"/siːmz/","gloss":"parece"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"problem","pos":"noun","ipa":"/ˈprɑːbləm/","gloss":"problema"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-02', 'lesson-health-a2-02', 2, 'sentence', 'I''ve had a headache for three days.', 'Estou com dor de cabeça há três dias.', '/aɪv hæd ə ˈhɛdeɪk fɔːr θriː deɪz/', 'Present perfect + "for" = há (ainda sente).', '[]'::jsonb, '[{"surface":"I''ve","pos":"pronoun","ipa":"/aɪv/","gloss":"eu tenho (I have)"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"headache","pos":"noun","ipa":"/ˈhɛdeɪk/","gloss":"dor de cabeça"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"three","pos":"numeral","ipa":"/θriː/","gloss":"três"},{"surface":"days","pos":"noun","ipa":"/deɪz/","gloss":"dias"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-03', 'lesson-health-a2-02', 3, 'sentence', 'My back hurts when I sit.', 'Minhas costas doem quando sento.', '/maɪ bæk hɜːrts wɛn aɪ sɪt/', '"Hurt" = doer. "My back hurts" (costas no singular).', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"hurts","pos":"verb","ipa":"/hɜːrts/","gloss":"dói"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"sit","pos":"verb","ipa":"/sɪt/","gloss":"sentar"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-04', 'lesson-health-a2-02', 4, 'sentence', 'I feel dizzy.', 'Estou tonto.', '/aɪ fiːl ˈdɪzi/', '"Dizzy" = tonto.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"feel","pos":"verb","ipa":"/fiːl/","gloss":"sentir"},{"surface":"dizzy","pos":"adjective","ipa":"/ˈdɪzi/","gloss":"tonto"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-05', 'lesson-health-a2-02', 5, 'sentence', 'I can''t sleep at night.', 'Não consigo dormir à noite.', '/aɪ kænt sliːp æt naɪt/', '"Can''t" = não consigo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"sleep","pos":"verb","ipa":"/sliːp/","gloss":"dormir"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-06', 'lesson-health-a2-02', 6, 'sentence', 'I have a runny nose and a cough.', 'Estou com o nariz escorrendo e tosse.', '/aɪ hæv ə ˈrʌni noʊz ænd ə kɔːf/', '"Runny nose" = coriza. "Cough" = tosse, /kɔːf/.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"runny","pos":"adjective","ipa":"/ˈrʌni/","gloss":"escorrendo"},{"surface":"nose","pos":"noun","ipa":"/noʊz/","gloss":"nariz"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"cough","pos":"noun","ipa":"/kɔːf/","gloss":"tosse"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-07', 'lesson-health-a2-02', 7, 'sentence', 'I think it''s an allergy.', 'Acho que é alergia.', '/aɪ θɪŋk ɪts ən ˈælərdʒi/', '"Allergy" = alergia; força no começo: AL-ler-gy.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"it''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"an","pos":"determiner","ipa":"/ən/","gloss":"um, uma"},{"surface":"allergy","pos":"noun","ipa":"/ˈælərdʒi/","gloss":"alergia"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-08', 'lesson-health-a2-02', 8, 'sentence', 'Does it hurt here?', 'Dói aqui?', '/dʌz ɪt hɜːrt hɪr/', 'Pergunta do médico durante o exame.', '[]'::jsonb, '[{"surface":"Does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"hurt","pos":"verb","ipa":"/hɜːrt/","gloss":"doer, machucar"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-09', 'lesson-health-a2-02', 9, 'sentence', 'I''m allergic to some medicines.', 'Tenho alergia a alguns remédios.', '/aɪm əˈlɜːrdʒɪk tuː sʌm ˈmɛdɪsənz/', 'Diga sempre antes de receber receita.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"allergic","pos":"adjective","ipa":"/əˈlɜːrdʒɪk/","gloss":"alérgico"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"medicines","pos":"noun","ipa":"/ˈmɛdɪsənz/","gloss":"remédios"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-02-10', 'lesson-health-a2-02', 10, 'sentence', 'I''m pregnant.', 'Estou grávida.', '/aɪm ˈprɛɡnənt/', 'Falso cognato: grávida é "pregnant", não "embarrassed".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"pregnant","pos":"adjective","ipa":"/ˈprɛɡnənt/","gloss":"grávida"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-health-a2-03', 'course-health-a2', 3, 'Exames, receita e tratamento', 'Entender o que o médico manda fazer.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-health-a2-03-01', 'lesson-health-a2-03', 1, 'sentence', 'I''m going to prescribe some medicine.', 'Vou receitar um remédio.', '/aɪm ˈɡoʊɪŋ tuː prɪˈskraɪb sʌm ˈmɛdɪsən/', '"Prescribe" = receitar. "Prescription" = receita.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"going","pos":"verb","ipa":"/ˈɡoʊɪŋ/","gloss":"indo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"prescribe","pos":"verb","ipa":"/prɪˈskraɪb/","gloss":"receitar"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"medicine","pos":"noun","ipa":"/ˈmɛdɪsən/","gloss":"remédio"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-02', 'lesson-health-a2-03', 2, 'sentence', 'Take one pill twice a day.', 'Tome um comprimido duas vezes ao dia.', '/teɪk wʌn pɪl twaɪs ə deɪ/', '"Twice a day" = duas vezes ao dia.', '[]'::jsonb, '[{"surface":"Take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"pill","pos":"noun","ipa":"/pɪl/","gloss":"comprimido"},{"surface":"twice","pos":"adverb","ipa":"/twaɪs/","gloss":"duas vezes"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-03', 'lesson-health-a2-03', 3, 'sentence', 'Take it with food.', 'Tome junto com comida.', '/teɪk ɪt wɪð fuːd/', 'Instrução comum de remédio.', '[]'::jsonb, '[{"surface":"Take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"food","pos":"noun","ipa":"/fuːd/","gloss":"comida"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-04', 'lesson-health-a2-03', 4, 'sentence', 'Avoid alcohol while taking this.', 'Evite álcool enquanto tomar isto.', '/əˈvɔɪd ˈælkəhɔːl waɪl ˈteɪkɪŋ ðɪs/', '"Avoid" + substantivo ou verbo com "-ing".', '[]'::jsonb, '[{"surface":"Avoid","pos":"verb","ipa":"/əˈvɔɪd/","gloss":"evitar"},{"surface":"alcohol","pos":"noun","ipa":"/ˈælkəhɔːl/","gloss":"álcool"},{"surface":"while","pos":"noun","ipa":"/waɪl/","gloss":"tempo (a while = um tempo)"},{"surface":"taking","pos":"verb","ipa":"/ˈteɪkɪŋ/","gloss":"dando, pegando"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-05', 'lesson-health-a2-03', 5, 'sentence', 'We need to run some tests.', 'Precisamos fazer alguns exames.', '/wiː niːd tuː rʌn sʌm tɛsts/', '"Run tests" = fazer exames.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"run","pos":"verb","ipa":"/rʌn/","gloss":"correr; administrar"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"tests","pos":"noun","ipa":"/tɛsts/","gloss":"exames"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-06', 'lesson-health-a2-03', 6, 'sentence', 'You need a blood test.', 'Você precisa de um exame de sangue.', '/juː niːd ə blʌd tɛst/', '"Blood test" = exame de sangue.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"blood","pos":"noun","ipa":"/blʌd/","gloss":"sangue"},{"surface":"test","pos":"noun","ipa":"/tɛst/","gloss":"exame, teste"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-07', 'lesson-health-a2-03', 7, 'sentence', 'The results will be ready on Monday.', 'Os resultados ficam prontos na segunda.', '/ðə rɪˈzʌlts wɪl biː ˈrɛdi ɑːn ˈmʌndeɪ/', 'Futuro com "will".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"results","pos":"noun","ipa":"/rɪˈzʌlts/","gloss":"resultados"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"ready","pos":"adjective","ipa":"/ˈrɛdi/","gloss":"pronto"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"Monday","pos":"proper noun","ipa":"/ˈmʌndeɪ/","gloss":"segunda-feira"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-08', 'lesson-health-a2-03', 8, 'sentence', 'You should rest for a few days.', 'Você deveria descansar alguns dias.', '/juː ʃʊd rɛst fɔːr ə fjuː deɪz/', '"Should" = recomendação.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"rest","pos":"verb","ipa":"/rɛst/","gloss":"descansar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"few","pos":"determiner","ipa":"/fjuː/","gloss":"poucos"},{"surface":"days","pos":"noun","ipa":"/deɪz/","gloss":"dias"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-09', 'lesson-health-a2-03', 9, 'sentence', 'Come back if it gets worse.', 'Volte se piorar.', '/kʌm bæk ɪf ɪt ɡɛts wɜːrs/', '"Get worse" = piorar; "get better" = melhorar.', '[]'::jsonb, '[{"surface":"Come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"gets","pos":"verb","ipa":"/ɡɛts/","gloss":"fica"},{"surface":"worse","pos":"adjective","ipa":"/wɜːrs/","gloss":"pior"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-03-10', 'lesson-health-a2-03', 10, 'sentence', 'Is it serious?', 'É grave?', '/ɪz ɪt ˈsɪriəs/', '"Serious" = grave (em saúde) ou sério.', '[]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"serious","pos":"adjective","ipa":"/ˈsɪriəs/","gloss":"sério"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-health-a2-04', 'course-health-a2', 4, 'No dentista', 'Dor de dente, limpeza e tratamento.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-health-a2-04-01', 'lesson-health-a2-04', 1, 'sentence', 'I have a toothache.', 'Estou com dor de dente.', '/aɪ hæv ə ˈtuːθeɪk/', '"Toothache" = dor de dente, uma palavra só.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"toothache","pos":"noun","ipa":"/ˈtuːθeɪk/","gloss":"dor de dente"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-02', 'lesson-health-a2-04', 2, 'sentence', 'My tooth is sensitive to cold.', 'Meu dente está sensível ao frio.', '/maɪ tuːθ ɪz ˈsɛnsətɪv tuː koʊld/', '"Sensitive" = sensível. Falso cognato de "sensible" (sensato).', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"tooth","pos":"noun","ipa":"/tuːθ/","gloss":"dente"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"sensitive","pos":"adjective","ipa":"/ˈsɛnsətɪv/","gloss":"sensível"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-03', 'lesson-health-a2-04', 3, 'sentence', 'I''d like a cleaning.', 'Eu gostaria de fazer uma limpeza.', '/aɪd laɪk ə ˈkliːnɪŋ/', '"Cleaning" = limpeza (profilaxia).', '[]'::jsonb, '[{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"cleaning","pos":"verb","ipa":"/ˈkliːnɪŋ/","gloss":"limpando"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-04', 'lesson-health-a2-04', 4, 'sentence', 'Open wide, please.', 'Abra bem, por favor.', '/ˈoʊpən waɪd pliːz/', 'Instrução do dentista.', '[]'::jsonb, '[{"surface":"Open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"wide","pos":"adverb","ipa":"/waɪd/","gloss":"bem aberto, largo"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-05', 'lesson-health-a2-04', 5, 'sentence', 'You have a cavity.', 'Você tem uma cárie.', '/juː hæv ə ˈkævəti/', '"Cavity" = cárie.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"cavity","pos":"noun","ipa":"/ˈkævəti/","gloss":"cárie"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-06', 'lesson-health-a2-04', 6, 'sentence', 'We need to fill it.', 'Precisamos obturar.', '/wiː niːd tuː fɪl ɪt/', '"Fill" = obturar; "filling" = obturação.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"fill","pos":"verb","ipa":"/fɪl/","gloss":"preencher; obturar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-07', 'lesson-health-a2-04', 7, 'sentence', 'Will it hurt?', 'Vai doer?', '/wɪl ɪt hɜːrt/', 'Pergunta com "will" antes do sujeito.', '[]'::jsonb, '[{"surface":"Will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"hurt","pos":"verb","ipa":"/hɜːrt/","gloss":"doer, machucar"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-08', 'lesson-health-a2-04', 8, 'sentence', 'You''ll feel a little pressure.', 'Você vai sentir uma leve pressão.', '/juːl fiːl ə ˈlɪtəl ˈprɛʃər/', 'Futuro com "will" contraído.', '[]'::jsonb, '[{"surface":"You''ll","pos":"pronoun","ipa":"/juːl/","gloss":"você vai (you will)"},{"surface":"feel","pos":"verb","ipa":"/fiːl/","gloss":"sentir"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"little","pos":"adjective","ipa":"/ˈlɪtəl/","gloss":"pouco, pequeno"},{"surface":"pressure","pos":"noun","ipa":"/ˈprɛʃər/","gloss":"pressão"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-09', 'lesson-health-a2-04', 9, 'sentence', 'Rinse your mouth, please.', 'Enxágue a boca, por favor.', '/rɪns jʊr maʊθ pliːz/', '"Rinse" = enxaguar.', '[]'::jsonb, '[{"surface":"Rinse","pos":"verb","ipa":"/rɪns/","gloss":"enxaguar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"mouth","pos":"noun","ipa":"/maʊθ/","gloss":"boca"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-04-10', 'lesson-health-a2-04', 10, 'sentence', 'Don''t eat for two hours.', 'Não coma por duas horas.', '/doʊnt iːt fɔːr tuː aʊərz/', 'Imperativo negativo + "for" + tempo.', '[]'::jsonb, '[{"surface":"Don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"eat","pos":"verb","ipa":"/iːt/","gloss":"comer"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"hours","pos":"noun","ipa":"/aʊərz/","gloss":"horas"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-health-a2-05', 'course-health-a2', 5, 'Academia e bem-estar', 'Exercício, sono e alimentação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-health-a2-05-01', 'lesson-health-a2-05', 1, 'sentence', 'I''m trying to get in shape.', 'Estou tentando entrar em forma.', '/aɪm ˈtraɪɪŋ tuː ɡɛt ɪn ʃeɪp/', '"Get in shape" = entrar em forma.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"trying","pos":"verb","ipa":"/ˈtraɪɪŋ/","gloss":"tentando"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"shape","pos":"noun","ipa":"/ʃeɪp/","gloss":"forma"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-02', 'lesson-health-a2-05', 2, 'sentence', 'I work out three times a week.', 'Treino três vezes por semana.', '/aɪ wɜːrk aʊt θriː taɪmz ə wiːk/', '"Work out" = malhar, treinar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"three","pos":"numeral","ipa":"/θriː/","gloss":"três"},{"surface":"times","pos":"noun","ipa":"/taɪmz/","gloss":"vezes"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-03', 'lesson-health-a2-05', 3, 'sentence', 'How much does a membership cost?', 'Quanto custa a mensalidade?', '/haʊ mʌtʃ dʌz ə ˈmɛmbərʃɪp kɔːst/', '"Membership" = matrícula, plano de academia.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"membership","pos":"noun","ipa":"/ˈmɛmbərʃɪp/","gloss":"matrícula, plano"},{"surface":"cost","pos":"verb","ipa":"/kɔːst/","gloss":"custar"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-04', 'lesson-health-a2-05', 4, 'sentence', 'Can you show me how to use this machine?', 'Pode me mostrar como usar esta máquina?', '/kæn juː ʃoʊ miː haʊ tuː juːz ðɪs məˈʃiːn/', '"How to" + verbo = como fazer.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"show","pos":"verb","ipa":"/ʃoʊ/","gloss":"aparecer (show up)"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"use","pos":"verb","ipa":"/juːz/","gloss":"usar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"machine","pos":"noun","ipa":"/məˈʃiːn/","gloss":"máquina"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-05', 'lesson-health-a2-05', 5, 'sentence', 'I''m sore from yesterday.', 'Estou dolorido de ontem.', '/aɪm sɔːr frʌm ˈjɛstərdeɪ/', '"Sore" = dolorido (músculo).', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"sore","pos":"adjective","ipa":"/sɔːr/","gloss":"dolorido"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-06', 'lesson-health-a2-05', 6, 'sentence', 'I need to drink more water.', 'Preciso beber mais água.', '/aɪ niːd tuː drɪŋk mɔːr ˈwɔːtər/', '"More" + substantivo.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"drink","pos":"verb","ipa":"/drɪŋk/","gloss":"beber"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"water","pos":"noun","ipa":"/ˈwɔːtər/","gloss":"água"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-07', 'lesson-health-a2-05', 7, 'sentence', 'I''m cutting down on sugar.', 'Estou diminuindo o açúcar.', '/aɪm ˈkʌtɪŋ daʊn ɑːn ˈʃʊɡər/', '"Cut down on" = diminuir o consumo de.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"cutting","pos":"verb","ipa":"/ˈkʌtɪŋ/","gloss":"cortando, diminuindo"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"sugar","pos":"noun","ipa":"/ˈʃʊɡər/","gloss":"açúcar"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-08', 'lesson-health-a2-05', 8, 'sentence', 'I sleep about seven hours a night.', 'Durmo umas sete horas por noite.', '/aɪ sliːp əˈbaʊt ˈsɛvən aʊərz ə naɪt/', '"About" = mais ou menos. "A night" = por noite.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"sleep","pos":"verb","ipa":"/sliːp/","gloss":"dormir"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"seven","pos":"numeral","ipa":"/ˈsɛvən/","gloss":"sete"},{"surface":"hours","pos":"noun","ipa":"/aʊərz/","gloss":"horas"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-09', 'lesson-health-a2-05', 9, 'sentence', 'Stretch before you run.', 'Alongue antes de correr.', '/strɛtʃ bɪˈfɔːr juː rʌn/', '"Stretch" = alongar.', '[]'::jsonb, '[{"surface":"Stretch","pos":"verb","ipa":"/strɛtʃ/","gloss":"alongar"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"run","pos":"verb","ipa":"/rʌn/","gloss":"correr; administrar"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-05-10', 'lesson-health-a2-05', 10, 'sentence', 'I feel much better now.', 'Me sinto muito melhor agora.', '/aɪ fiːl mʌtʃ ˈbɛtər naʊ/', '"Much" reforça comparativo: "much better".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"feel","pos":"verb","ipa":"/fiːl/","gloss":"sentir"},{"surface":"much","pos":"adverb","ipa":"/mʌtʃ/","gloss":"quanto (how much)"},{"surface":"better","pos":"adjective","ipa":"/ˈbɛtər/","gloss":"melhor"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-health-a2-06', 'course-health-a2', 6, 'Hospital e seguro saúde', 'Pronto-socorro, internação e cobertura.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-health-a2-06-01', 'lesson-health-a2-06', 1, 'sentence', 'Where is the emergency room?', 'Onde fica o pronto-socorro?', '/wɛr ɪz ðə ɪˈmɜːrdʒənsi ruːm/', '"Emergency room" (ER) = pronto-socorro.', '[]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"emergency","pos":"noun","ipa":"/ɪˈmɜːrdʒənsi/","gloss":"emergência"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-02', 'lesson-health-a2-06', 2, 'sentence', 'He needs to see a doctor right now.', 'Ele precisa ver um médico agora.', '/hiː niːdz tuː siː ə ˈdɑːktər raɪt naʊ/', '"Right now" = agora mesmo.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"needs","pos":"verb","ipa":"/niːdz/","gloss":"precisa"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"doctor","pos":"noun","ipa":"/ˈdɑːktər/","gloss":"médico"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-03', 'lesson-health-a2-06', 3, 'sentence', 'How long is the wait?', 'Quanto tempo de espera?', '/haʊ lɔːŋ ɪz ðə weɪt/', 'Pergunta comum no pronto-socorro.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-04', 'lesson-health-a2-06', 4, 'sentence', 'She was admitted last night.', 'Ela foi internada ontem à noite.', '/ʃiː wɑːz ədˈmɪtɪd læst naɪt/', '"Be admitted" = ser internado.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"admitted","pos":"verb","ipa":"/ədˈmɪtɪd/","gloss":"internado, admitido"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-05', 'lesson-health-a2-06', 5, 'sentence', 'Visiting hours are from two to eight.', 'O horário de visita é das duas às oito.', '/ˈvɪzɪtɪŋ aʊərz ɑːr frʌm tuː tuː eɪt/', '"From… to…" = de… a….', '[]'::jsonb, '[{"surface":"Visiting","pos":"adjective","ipa":"/ˈvɪzɪtɪŋ/","gloss":"de visita"},{"surface":"hours","pos":"noun","ipa":"/aʊərz/","gloss":"horas"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"eight","pos":"numeral","ipa":"/eɪt/","gloss":"oito"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-06', 'lesson-health-a2-06', 6, 'sentence', 'Does my insurance cover this?', 'Meu plano cobre isso?', '/dʌz maɪ ɪnˈʃʊrəns ˈkʌvər ðɪs/', '"Cover" = cobrir (seguro).', '[]'::jsonb, '[{"surface":"Does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"insurance","pos":"noun","ipa":"/ɪnˈʃʊrəns/","gloss":"seguro"},{"surface":"cover","pos":"noun","ipa":"/ˈkʌvər/","gloss":"entrada (cover charge)"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-07', 'lesson-health-a2-06', 7, 'sentence', 'Here is my insurance card.', 'Aqui está a carteirinha do plano.', '/hɪr ɪz maɪ ɪnˈʃʊrəns kɑːrd/', '"Insurance card" = carteirinha do plano.', '[]'::jsonb, '[{"surface":"Here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"insurance","pos":"noun","ipa":"/ɪnˈʃʊrəns/","gloss":"seguro"},{"surface":"card","pos":"noun","ipa":"/kɑːrd/","gloss":"cartão"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-08', 'lesson-health-a2-06', 8, 'sentence', 'Can I get a copy of my records?', 'Posso ter uma cópia do meu prontuário?', '/kæn aɪ ɡɛt ə ˈkɑːpi ʌv maɪ ˈrɛkərdz/', '"Medical records" = prontuário.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"copy","pos":"noun","ipa":"/ˈkɑːpi/","gloss":"cópia"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"records","pos":"noun","ipa":"/ˈrɛkərdz/","gloss":"registros, prontuário"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-09', 'lesson-health-a2-06', 9, 'sentence', 'When can he go home?', 'Quando ele pode ir para casa?', '/wɛn kæn hiː ɡoʊ hoʊm/', '"Go home" sem "to".', '[]'::jsonb, '[{"surface":"When","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"}]'::jsonb, NULL, NULL),
  ('unit-health-a2-06-10', 'lesson-health-a2-06', 10, 'sentence', 'Get well soon!', 'Melhoras!', '/ɡɛt wɛl suːn/', 'Expressão fixa para desejar recuperação.', '[]'::jsonb, '[{"surface":"Get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"},{"surface":"soon","pos":"adverb","ipa":"/suːn/","gloss":"logo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
