-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-work-b1', 'english-at-work-b1', 'Inglês no Trabalho', 'Reuniões, e-mails, apresentações, feedback, prazos, clientes, entrevista e liderança: o inglês de escritório e trabalho remoto.', 'Expressões usadas de verdade no trabalho: conduzir reuniões, escrever e-mails, apresentar resultados, dar feedback, negociar prazos, falar com clientes, fazer entrevista, networking, lidar com conflitos e liderar. Cada nota indica o registro (formal, neutro ou informal).', 'B1', 'business', 3, 'trabalho', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-10', 'course-work-b1', 10, 'Entrevista de emprego', 'Apresentar-se, falar de experiência e fazer perguntas.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-10-01', 'lesson-work-b1-10', 1, 'sentence', 'Tell me a little about yourself.', 'Fale um pouco sobre você.', '/tɛl miː ə ˈlɪtəl əˈbaʊt jərˈsɛlf/', 'Neutro. Primeira pergunta de quase toda entrevista.', '[]'::jsonb, '[{"surface":"Tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"little","pos":"adjective","ipa":"/ˈlɪtəl/","gloss":"pouco, pequeno"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"yourself","pos":"pronoun","ipa":"/jərˈsɛlf/","gloss":"você mesmo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-02', 'lesson-work-b1-10', 2, 'sentence', 'I have five years of experience in marketing.', 'Tenho cinco anos de experiência em marketing.', '/aɪ hæv faɪv jɪrz ʌv ɪkˈspɪriəns ɪn ˈmɑːrkɪtɪŋ/', 'Neutro. "Experience in" + área.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"experience","pos":"noun","ipa":"/ɪkˈspɪriəns/","gloss":"experiência"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"marketing","pos":"noun","ipa":"/ˈmɑːrkɪtɪŋ/","gloss":"marketing"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-03', 'lesson-work-b1-10', 3, 'sentence', 'I''m currently working as a designer.', 'Atualmente trabalho como designer.', '/aɪm ˈkɜːrəntli ˈwɜːrkɪŋ æz ə dɪˈzaɪnər/', 'Neutro. Falso cognato: "currently" = atualmente ("actually" = na verdade).', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"currently","pos":"adverb","ipa":"/ˈkɜːrəntli/","gloss":"atualmente"},{"surface":"working","pos":"verb","ipa":"/ˈwɜːrkɪŋ/","gloss":"funcionando; trabalhando"},{"surface":"as","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"designer","pos":"noun","ipa":"/dɪˈzaɪnər/","gloss":"designer"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-04', 'lesson-work-b1-10', 4, 'sentence', 'Why do you want to work here?', 'Por que você quer trabalhar aqui?', '/waɪ duː juː wɑːnt tuː wɜːrk hɪr/', 'Neutro. Prepare uma resposta sobre a empresa, não sobre salário.', '[]'::jsonb, '[{"surface":"Why","pos":"adverb","ipa":"/waɪ/","gloss":"por que"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"want","pos":"verb","ipa":"/wɑːnt/","gloss":"querer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-05', 'lesson-work-b1-10', 5, 'sentence', 'I''m good at solving problems.', 'Sou bom em resolver problemas.', '/aɪm ɡʊd æt ˈsɑːlvɪŋ ˈprɑːbləmz/', 'Neutro. "Good at" + verbo com "-ing".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"solving","pos":"verb","ipa":"/ˈsɑːlvɪŋ/","gloss":"resolver"},{"surface":"problems","pos":"noun","ipa":"/ˈprɑːbləmz/","gloss":"problemas"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-06', 'lesson-work-b1-10', 6, 'sentence', 'My biggest weakness is public speaking.', 'Meu maior ponto fraco é falar em público.', '/maɪ ˈbɪɡɪst ˈwiːknəs ɪz ˈpʌblɪk ˈspiːkɪŋ/', 'Neutro. "Weakness" = ponto fraco; "strength" = ponto forte.', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"biggest","pos":"adjective","ipa":"/ˈbɪɡɪst/","gloss":"maior"},{"surface":"weakness","pos":"noun","ipa":"/ˈwiːknəs/","gloss":"ponto fraco"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"public","pos":"adjective","ipa":"/ˈpʌblɪk/","gloss":"público"},{"surface":"speaking","pos":"verb","ipa":"/ˈspiːkɪŋ/","gloss":"falar"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-07', 'lesson-work-b1-10', 7, 'sentence', 'I led a team of six people.', 'Liderei uma equipe de seis pessoas.', '/aɪ lɛd ə tiːm ʌv sɪks ˈpiːpəl/', 'Neutro. "Led" = passado de "lead" (liderar).', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"led","pos":"verb","ipa":"/lɛd/","gloss":"liderou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"team","pos":"noun","ipa":"/tiːm/","gloss":"time, equipe"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"six","pos":"numeral","ipa":"/sɪks/","gloss":"seis"},{"surface":"people","pos":"noun","ipa":"/ˈpiːpəl/","gloss":"pessoas"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-08', 'lesson-work-b1-10', 8, 'sentence', 'Where do you see yourself in five years?', 'Onde você se vê daqui a cinco anos?', '/wɛr duː juː siː jərˈsɛlf ɪn faɪv jɪrz/', 'Neutro. "In five years" = daqui a cinco anos.', '[]'::jsonb, '[{"surface":"Where","pos":"adverb","ipa":"/wɛr/","gloss":"onde"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"yourself","pos":"pronoun","ipa":"/jərˈsɛlf/","gloss":"você mesmo"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-09', 'lesson-work-b1-10', 9, 'sentence', 'Do you have any questions for us?', 'Você tem alguma pergunta para nós?', '/duː juː hæv ˈɛni ˈkwɛstʃənz fɔːr ʌs/', 'Neutro. Sempre tenha uma pergunta pronta.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"questions","pos":"noun","ipa":"/ˈkwɛstʃənz/","gloss":"perguntas, dúvidas"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"us","pos":"pronoun","ipa":"/ʌs/","gloss":"nós, nos"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-10-10', 'lesson-work-b1-10', 10, 'sentence', 'What does a typical day look like?', 'Como é um dia típico?', '/wʌt dʌz ə ˈtɪpɪkəl deɪ lʊk laɪk/', 'Neutro. Boa pergunta para fazer ao entrevistador.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"typical","pos":"adjective","ipa":"/ˈtɪpɪkəl/","gloss":"típico"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-11', 'course-work-b1', 11, 'E-mails formais', 'Abrir, pedir, confirmar e encerrar e-mails profissionais.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-11-01', 'lesson-work-b1-11', 1, 'sentence', 'Dear Mr. Smith,', 'Prezado Sr. Smith,', '/dɪr ˈmɪstər smɪθ/', 'Formal. "Dear" + título + sobrenome. Com desconhecido: "Dear Sir or Madam".', '[]'::jsonb, '[{"surface":"Dear","pos":"adjective","ipa":"/dɪr/","gloss":"prezado, querido"},{"surface":"Mr","pos":"noun","ipa":"/ˈmɪstər/","gloss":"senhor (Sr.)"},{"surface":"Smith","pos":"proper noun","ipa":"/smɪθ/","gloss":"Smith"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-02', 'lesson-work-b1-11', 2, 'sentence', 'I hope this email finds you well.', 'Espero que esteja bem.', '/aɪ hoʊp ðɪs ˈiːmeɪl faɪndz juː wɛl/', 'Formal. Abertura educada de e-mail.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"hope","pos":"verb","ipa":"/hoʊp/","gloss":"esperar (ter esperança)"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"email","pos":"noun","ipa":"/ˈiːmeɪl/","gloss":"e-mail"},{"surface":"finds","pos":"verb","ipa":"/faɪndz/","gloss":"encontra"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-03', 'lesson-work-b1-11', 3, 'sentence', 'I am writing to request more information.', 'Escrevo para solicitar mais informações.', '/aɪ æm ˈraɪtɪŋ tuː rɪˈkwɛst mɔːr ˌɪnfərˈmeɪʃən/', 'Formal. "I am writing to" + motivo. "Information" não tem plural.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"writing","pos":"noun","ipa":"/ˈraɪtɪŋ/","gloss":"escrita"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"request","pos":"verb","ipa":"/rɪˈkwɛst/","gloss":"solicitar"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"information","pos":"noun","ipa":"/ˌɪnfərˈmeɪʃən/","gloss":"informação"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-04', 'lesson-work-b1-11', 4, 'sentence', 'Could you please confirm the date?', 'Poderia confirmar a data, por favor?', '/kʊd juː pliːz kənˈfɜːrm ðə deɪt/', 'Formal. "Could you please" + verbo.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"confirm","pos":"verb","ipa":"/kənˈfɜːrm/","gloss":"confirmar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"date","pos":"noun","ipa":"/deɪt/","gloss":"data"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-05', 'lesson-work-b1-11', 5, 'sentence', 'As discussed in our meeting,', 'Conforme conversamos na reunião,', '/æz dɪˈskʌst ɪn aʊər ˈmiːtɪŋ/', 'Formal. Retoma algo já combinado.', '[]'::jsonb, '[{"surface":"As","pos":"conjunction","ipa":"/æz/","gloss":"como"},{"surface":"discussed","pos":"verb","ipa":"/dɪˈskʌst/","gloss":"discutido, conversado"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-06', 'lesson-work-b1-11', 6, 'sentence', 'I would appreciate your help.', 'Agradeço desde já a sua ajuda.', '/aɪ wʊd əˈpriːʃieɪt jʊr hɛlp/', 'Formal. "I would appreciate" = eu agradeceria.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"appreciate","pos":"verb","ipa":"/əˈpriːʃieɪt/","gloss":"agradecer, valorizar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-07', 'lesson-work-b1-11', 7, 'sentence', 'Please do not hesitate to contact me.', 'Fique à vontade para me contatar.', '/pliːz duː nɑːt ˈhɛzɪteɪt tuː ˈkɑːntækt miː/', 'Formal. Literal: "não hesite em me contatar".', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"hesitate","pos":"verb","ipa":"/ˈhɛzɪteɪt/","gloss":"hesitar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"contact","pos":"verb","ipa":"/ˈkɑːntækt/","gloss":"contatar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-08', 'lesson-work-b1-11', 8, 'sentence', 'I look forward to hearing from you.', 'Aguardo seu retorno.', '/aɪ lʊk ˈfɔːrwərd tuː ˈhɪrɪŋ frʌm juː/', 'Formal. "Look forward to" + verbo com "-ing".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"forward","pos":"adverb","ipa":"/ˈfɔːrwərd/","gloss":"adiante (look forward)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"hearing","pos":"verb","ipa":"/ˈhɪrɪŋ/","gloss":"ouvir, ter notícias"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-09', 'lesson-work-b1-11', 9, 'sentence', 'Best regards,', 'Atenciosamente,', '/bɛst rɪˈɡɑːrdz/', 'Neutro. Fechamento mais comum. Mais formal: "Kind regards".', '[]'::jsonb, '[{"surface":"Best","pos":"adjective","ipa":"/bɛst/","gloss":"melhor"},{"surface":"regards","pos":"noun","ipa":"/rɪˈɡɑːrdz/","gloss":"cumprimentos"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-11-10', 'lesson-work-b1-11', 10, 'sentence', 'Apologies for the delay.', 'Desculpe a demora.', '/əˈpɑːlədʒiz fɔːr ðə dɪˈleɪ/', 'Formal. Mais formal que "Sorry for the late reply".', '[]'::jsonb, '[{"surface":"Apologies","pos":"noun","ipa":"/əˈpɑːlədʒiz/","gloss":"desculpas"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"delay","pos":"noun","ipa":"/dɪˈleɪ/","gloss":"atraso"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-12', 'course-work-b1', 12, 'Relatórios e números', 'Falar de metas, resultados, aumento e queda.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-12-01', 'lesson-work-b1-12', 1, 'sentence', 'We reached our goal this quarter.', 'Batemos a meta neste trimestre.', '/wiː riːtʃt aʊər ɡoʊl ðɪs ˈkwɔːrtər/', 'Neutro. "Reach a goal" = bater a meta. "Quarter" = trimestre.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"reached","pos":"verb","ipa":"/riːtʃt/","gloss":"alcançou"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"goal","pos":"noun","ipa":"/ɡoʊl/","gloss":"meta"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"quarter","pos":"noun","ipa":"/ˈkwɔːrtər/","gloss":"quarto (15 minutos)"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-02', 'lesson-work-b1-12', 2, 'sentence', 'Costs increased by five percent.', 'Os custos aumentaram cinco por cento.', '/kɔːsts ɪnˈkriːst baɪ faɪv pərˈsɛnt/', 'Neutro. "Increase by" = aumentar em.', '[]'::jsonb, '[{"surface":"Costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"},{"surface":"increased","pos":"verb","ipa":"/ɪnˈkriːst/","gloss":"aumentou"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"five","pos":"numeral","ipa":"/faɪv/","gloss":"cinco"},{"surface":"percent","pos":"noun","ipa":"/pərˈsɛnt/","gloss":"por cento"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-03', 'lesson-work-b1-12', 3, 'sentence', 'The numbers dropped in March.', 'Os números caíram em março.', '/ðə ˈnʌmbərz drɑːpt ɪn mɑːrtʃ/', 'Neutro. "Drop" = cair; mais informal que "decrease".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"numbers","pos":"noun","ipa":"/ˈnʌmbərz/","gloss":"números"},{"surface":"dropped","pos":"verb","ipa":"/drɑːpt/","gloss":"caiu"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"March","pos":"proper noun","ipa":"/mɑːrtʃ/","gloss":"março"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-04', 'lesson-work-b1-12', 4, 'sentence', 'We''re on track to finish in June.', 'Estamos no caminho para terminar em junho.', '/wɪr ɑːn træk tuː ˈfɪnɪʃ ɪn dʒuːn/', 'Neutro. "On track" = dentro do previsto.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"track","pos":"noun","ipa":"/træk/","gloss":"trilha, caminho"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"finish","pos":"verb","ipa":"/ˈfɪnɪʃ/","gloss":"terminar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"June","pos":"proper noun","ipa":"/dʒuːn/","gloss":"junho"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-05', 'lesson-work-b1-12', 5, 'sentence', 'We''re behind schedule.', 'Estamos atrasados em relação ao cronograma.', '/wɪr bɪˈhaɪnd ˈskɛdʒuːl/', 'Neutro. "Behind schedule" = atrasado; "ahead of schedule" = adiantado.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"behind","pos":"preposition","ipa":"/bɪˈhaɪnd/","gloss":"atrás"},{"surface":"schedule","pos":"noun","ipa":"/ˈskɛdʒuːl/","gloss":"horário, agenda"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-06', 'lesson-work-b1-12', 6, 'sentence', 'The budget is almost used up.', 'O orçamento está quase no fim.', '/ðə ˈbʌdʒɪt ɪz ˈɔːlmoʊst juːzd ʌp/', 'Neutro. "Budget" = orçamento. "Use up" = gastar tudo.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"budget","pos":"noun","ipa":"/ˈbʌdʒɪt/","gloss":"orçamento"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"almost","pos":"adverb","ipa":"/ˈɔːlmoʊst/","gloss":"quase"},{"surface":"used","pos":"verb","ipa":"/juːzd/","gloss":"usou, usado"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-07', 'lesson-work-b1-12', 7, 'sentence', 'Revenue doubled last year.', 'A receita dobrou no ano passado.', '/ˈrɛvənuː ˈdʌbəld læst jɪr/', 'Neutro. "Double" = dobrar; "triple" = triplicar.', '[]'::jsonb, '[{"surface":"Revenue","pos":"noun","ipa":"/ˈrɛvənuː/","gloss":"receita"},{"surface":"doubled","pos":"verb","ipa":"/ˈdʌbəld/","gloss":"dobrou"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"último"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-08', 'lesson-work-b1-12', 8, 'sentence', 'Let''s look at the data.', 'Vamos olhar os dados.', '/lɛts lʊk æt ðə ˈdeɪtə/', 'Neutro. "Data" costuma ir com verbo no singular no inglês do dia a dia.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"data","pos":"noun","ipa":"/ˈdeɪtə/","gloss":"dados"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-09', 'lesson-work-b1-12', 9, 'sentence', 'This is higher than expected.', 'Isso está acima do esperado.', '/ðɪs ɪz ˈhaɪər ðæn ɪkˈspɛktɪd/', 'Neutro. Comparativo + "than expected".', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"higher","pos":"adjective","ipa":"/ˈhaɪər/","gloss":"mais alto, maior"},{"surface":"than","pos":"conjunction","ipa":"/ðæn/","gloss":"do que"},{"surface":"expected","pos":"verb","ipa":"/ɪkˈspɛktɪd/","gloss":"esperado"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-12-10', 'lesson-work-b1-12', 10, 'sentence', 'I''ll send you the report by Friday.', 'Te mando o relatório até sexta.', '/aɪl sɛnd juː ðə rɪˈpɔːrt baɪ ˈfraɪdeɪ/', 'Neutro. "By Friday" = até sexta (no máximo).', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"send","pos":"verb","ipa":"/sɛnd/","gloss":"enviar, mandar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"report","pos":"verb","ipa":"/rɪˈpɔːrt/","gloss":"registrar, relatar"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"Friday","pos":"proper noun","ipa":"/ˈfraɪdeɪ/","gloss":"sexta-feira"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-13', 'course-work-b1', 13, 'Networking e eventos', 'Conhecer pessoas, trocar contatos e manter a conversa.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-13-01', 'lesson-work-b1-13', 1, 'sentence', 'Nice to meet you, I work in sales.', 'Prazer, trabalho com vendas.', '/naɪs tuː miːt juː aɪ wɜːrk ɪn seɪlz/', 'Neutro. "Work in" + área.', '[]'::jsonb, '[{"surface":"Nice","pos":"adjective","ipa":"/naɪs/","gloss":"prazer; legal"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"meet","pos":"verb","ipa":"/miːt/","gloss":"encontrar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"sales","pos":"noun","ipa":"/seɪlz/","gloss":"vendas"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-02', 'lesson-work-b1-13', 2, 'sentence', 'What do you do at your company?', 'O que você faz na sua empresa?', '/wʌt duː juː duː æt jʊr ˈkʌmpəni/', 'Neutro. Pergunta sobre função.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-03', 'lesson-work-b1-13', 3, 'sentence', 'How did you get into this field?', 'Como você entrou nessa área?', '/haʊ dɪd juː ɡɛt ˈɪntuː ðɪs fiːld/', 'Neutro. "Field" = área de atuação. "Get into" = entrar em.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"into","pos":"preposition","ipa":"/ˈɪntuː/","gloss":"para dentro de"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"field","pos":"noun","ipa":"/fiːld/","gloss":"área, campo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-04', 'lesson-work-b1-13', 4, 'sentence', 'Here''s my card.', 'Aqui está meu cartão.', '/hɪrz maɪ kɑːrd/', 'Neutro. "Business card" = cartão de visita.', '[]'::jsonb, '[{"surface":"Here''s","pos":"adverb","ipa":"/hɪrz/","gloss":"aqui está (here is)"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"card","pos":"noun","ipa":"/kɑːrd/","gloss":"cartão"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-05', 'lesson-work-b1-13', 5, 'sentence', 'Let''s connect on LinkedIn.', 'Vamos nos conectar no LinkedIn.', '/lɛts kəˈnɛkt ɑːn ˈlɪŋktɪn/', 'Neutro. "Connect" = adicionar como contato.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"connect","pos":"verb","ipa":"/kəˈnɛkt/","gloss":"conectar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"LinkedIn","pos":"proper noun","ipa":"/ˈlɪŋktɪn/","gloss":"LinkedIn"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-06', 'lesson-work-b1-13', 6, 'sentence', 'It was great talking to you.', 'Foi ótimo conversar com você.', '/ɪt wɑːz ɡreɪt ˈtɔːkɪŋ tuː juː/', 'Neutro. Encerra a conversa com simpatia.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"talking","pos":"verb","ipa":"/ˈtɔːkɪŋ/","gloss":"conversar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-07', 'lesson-work-b1-13', 7, 'sentence', 'I would love to hear more about your project.', 'Adoraria saber mais sobre seu projeto.', '/aɪ wʊd lʌv tuː hɪr mɔːr əˈbaʊt jʊr ˈprɑːdʒɛkt/', 'Neutro. Mostra interesse real.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"love","pos":"verb","ipa":"/lʌv/","gloss":"amar, adorar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"hear","pos":"verb","ipa":"/hɪr/","gloss":"ouvir"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"project","pos":"noun","ipa":"/ˈprɑːdʒɛkt/","gloss":"projeto"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-08', 'lesson-work-b1-13', 8, 'sentence', 'Do you know anyone who works there?', 'Você conhece alguém que trabalha lá?', '/duː juː noʊ ˈɛniwʌn huː wɜːrks ðɛr/', 'Neutro. "Anyone who" + verbo.', '[]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"anyone","pos":"pronoun","ipa":"/ˈɛniwʌn/","gloss":"alguém, ninguém"},{"surface":"who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"works","pos":"verb","ipa":"/wɜːrks/","gloss":"funciona, serve"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-09', 'lesson-work-b1-13', 9, 'sentence', 'I''ll follow up next week.', 'Entro em contato semana que vem.', '/aɪl ˈfɑːloʊ ʌp nɛkst wiːk/', 'Neutro. "Follow up" = retomar o contato.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"follow","pos":"verb","ipa":"/ˈfɑːloʊ/","gloss":"seguir"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-13-10', 'lesson-work-b1-13', 10, 'sentence', 'Can I introduce you to my colleague?', 'Posso te apresentar ao meu colega?', '/kæn aɪ ˌɪntrəˈduːs juː tuː maɪ ˈkɑːliːɡ/', 'Neutro. "Introduce" = apresentar pessoas (não "present").', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"introduce","pos":"verb","ipa":"/ˌɪntrəˈduːs/","gloss":"apresentar (pessoas)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"colleague","pos":"noun","ipa":"/ˈkɑːliːɡ/","gloss":"colega de trabalho"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-14', 'course-work-b1', 14, 'Conflitos e problemas', 'Falar de erros, desacordos e soluções com maturidade.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-14-01', 'lesson-work-b1-14', 1, 'sentence', 'I think there has been a misunderstanding.', 'Acho que houve um mal-entendido.', '/aɪ θɪŋk ðɛr hæz bɪn ə ˌmɪsʌndərˈstændɪŋ/', 'Neutro. Abre a conversa sem culpar ninguém.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"misunderstanding","pos":"noun","ipa":"/ˌmɪsʌndərˈstændɪŋ/","gloss":"mal-entendido"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-02', 'lesson-work-b1-14', 2, 'sentence', 'That was my mistake.', 'Esse erro foi meu.', '/ðæt wɑːz maɪ mɪˈsteɪk/', 'Neutro. Assumir o erro cedo gera confiança.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"mistake","pos":"noun","ipa":"/mɪˈsteɪk/","gloss":"erro"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-03', 'lesson-work-b1-14', 3, 'sentence', 'Let''s focus on the solution.', 'Vamos focar na solução.', '/lɛts ˈfoʊkəs ɑːn ðə səˈluːʃən/', 'Neutro. "Focus on" = focar em.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"focus","pos":"verb","ipa":"/ˈfoʊkəs/","gloss":"focar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"solution","pos":"noun","ipa":"/səˈluːʃən/","gloss":"solução"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-04', 'lesson-work-b1-14', 4, 'sentence', 'I understand your concern.', 'Entendo sua preocupação.', '/aɪ ˌʌndərˈstænd jʊr kənˈsɜːrn/', 'Neutro. "Concern" = preocupação.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"understand","pos":"verb","ipa":"/ˌʌndərˈstænd/","gloss":"entender"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"concern","pos":"noun","ipa":"/kənˈsɜːrn/","gloss":"preocupação"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-05', 'lesson-work-b1-14', 5, 'sentence', 'I don''t agree, and here is why.', 'Não concordo, e explico o porquê.', '/aɪ doʊnt əˈɡriː ænd hɪr ɪz waɪ/', 'Neutro. Discordar com argumento, não com emoção.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"don''t","pos":"auxiliary verb","ipa":"/doʊnt/","gloss":"não"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"and","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"why","pos":"adverb","ipa":"/waɪ/","gloss":"por que"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-06', 'lesson-work-b1-14', 6, 'sentence', 'Can we talk about this in private?', 'Podemos falar sobre isso em particular?', '/kæn wiː tɔːk əˈbaʊt ðɪs ɪn ˈpraɪvət/', 'Neutro. "In private" = em particular.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"talk","pos":"verb","ipa":"/tɔːk/","gloss":"falar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"private","pos":"adjective","ipa":"/ˈpraɪvət/","gloss":"particular, privado"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-07', 'lesson-work-b1-14', 7, 'sentence', 'It won''t happen again.', 'Não vai acontecer de novo.', '/ɪt woʊnt ˈhæpən əˈɡɛn/', 'Neutro. Compromisso depois de um erro.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"won''t","pos":"modal verb","ipa":"/woʊnt/","gloss":"não vai (will not)"},{"surface":"happen","pos":"verb","ipa":"/ˈhæpən/","gloss":"acontecer"},{"surface":"again","pos":"adverb","ipa":"/əˈɡɛn/","gloss":"de novo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-08', 'lesson-work-b1-14', 8, 'sentence', 'Let''s find a middle ground.', 'Vamos encontrar um meio-termo.', '/lɛts faɪnd ə ˈmɪdəl ɡraʊnd/', 'Neutro. "Middle ground" = meio-termo.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"find","pos":"verb","ipa":"/faɪnd/","gloss":"encontrar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"middle","pos":"adjective","ipa":"/ˈmɪdəl/","gloss":"do meio"},{"surface":"ground","pos":"noun","ipa":"/ɡraʊnd/","gloss":"chão, terreno"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-09', 'lesson-work-b1-14', 9, 'sentence', 'I felt left out of the decision.', 'Me senti excluído da decisão.', '/aɪ fɛlt lɛft aʊt ʌv ðə dɪˈsɪʒən/', 'Neutro. "Left out" = deixado de fora. Fala do sentimento sem acusar.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"felt","pos":"verb","ipa":"/fɛlt/","gloss":"sentiu"},{"surface":"left","pos":"adverb","ipa":"/lɛft/","gloss":"à esquerda"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"decision","pos":"noun","ipa":"/dɪˈsɪʒən/","gloss":"decisão"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-14-10', 'lesson-work-b1-14', 10, 'sentence', 'Thanks for being honest with me.', 'Obrigado por ser sincero comigo.', '/θæŋks fɔːr ˈbiːɪŋ ˈɑːnɪst wɪð miː/', 'Neutro. "Honest" = sincero; o "h" é mudo.', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"being","pos":"verb","ipa":"/ˈbiːɪŋ/","gloss":"sendo"},{"surface":"honest","pos":"adjective","ipa":"/ˈɑːnɪst/","gloss":"sincero, honesto"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-15', 'course-work-b1', 15, 'Liderança e metas', 'Definir prioridades, motivar e acompanhar a equipe.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-15-01', 'lesson-work-b1-15', 1, 'sentence', 'Let''s set clear goals for this month.', 'Vamos definir metas claras para este mês.', '/lɛts sɛt klɪr ɡoʊlz fɔːr ðɪs mʌnθ/', 'Neutro. "Set goals" = definir metas.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"set","pos":"verb","ipa":"/sɛt/","gloss":"definir"},{"surface":"clear","pos":"adjective","ipa":"/klɪr/","gloss":"claro"},{"surface":"goals","pos":"noun","ipa":"/ɡoʊlz/","gloss":"metas"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-02', 'lesson-work-b1-15', 2, 'sentence', 'What are our priorities?', 'Quais são nossas prioridades?', '/wʌt ɑːr aʊər praɪˈɔːrətiz/', 'Neutro. Pergunta de alinhamento.', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"priorities","pos":"noun","ipa":"/praɪˈɔːrətiz/","gloss":"prioridades"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-03', 'lesson-work-b1-15', 3, 'sentence', 'This is our top priority.', 'Esta é nossa prioridade número um.', '/ðɪs ɪz aʊər tɑːp praɪˈɔːrəti/', 'Neutro. "Top priority" = prioridade máxima.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"top","pos":"adjective","ipa":"/tɑːp/","gloss":"principal, máximo"},{"surface":"priority","pos":"noun","ipa":"/praɪˈɔːrəti/","gloss":"prioridade"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-04', 'lesson-work-b1-15', 4, 'sentence', 'Who will own this task?', 'Quem vai ser dono desta tarefa?', '/huː wɪl oʊn ðɪs tæsk/', 'Informal. "Own" = ser responsável do começo ao fim.', '[]'::jsonb, '[{"surface":"Who","pos":"pronoun","ipa":"/huː/","gloss":"quem"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"own","pos":"verb","ipa":"/oʊn/","gloss":"ser dono, responsável"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"task","pos":"noun","ipa":"/tæsk/","gloss":"tarefa"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-05', 'lesson-work-b1-15', 5, 'sentence', 'I trust you to make the call.', 'Confio em você para decidir.', '/aɪ trʌst juː tuː meɪk ðə kɔːl/', 'Informal. "Make the call" = tomar a decisão.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"trust","pos":"verb","ipa":"/trʌst/","gloss":"confiar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-06', 'lesson-work-b1-15', 6, 'sentence', 'Let''s check in every Monday.', 'Vamos nos alinhar toda segunda.', '/lɛts tʃɛk ɪn ˈɛvri ˈmʌndeɪ/', 'Neutro. "Check in" = conversar rápido para acompanhar.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"Monday","pos":"proper noun","ipa":"/ˈmʌndeɪ/","gloss":"segunda-feira"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-07', 'lesson-work-b1-15', 7, 'sentence', 'How can I support you?', 'Como posso te apoiar?', '/haʊ kæn aɪ səˈpɔːrt juː/', 'Neutro. Pergunta de líder que funciona.', '[]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"support","pos":"verb","ipa":"/səˈpɔːrt/","gloss":"apoiar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-08', 'lesson-work-b1-15', 8, 'sentence', 'Great teamwork, everyone.', 'Ótimo trabalho em equipe, pessoal.', '/ɡreɪt ˈtiːmwɜːrk ˈɛvriwʌn/', 'Neutro. "Teamwork" = trabalho em equipe.', '[]'::jsonb, '[{"surface":"Great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"teamwork","pos":"noun","ipa":"/ˈtiːmwɜːrk/","gloss":"trabalho em equipe"},{"surface":"everyone","pos":"pronoun","ipa":"/ˈɛvriwʌn/","gloss":"todo mundo, pessoal"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-09', 'lesson-work-b1-15', 9, 'sentence', 'We need to raise the bar.', 'Precisamos elevar o padrão.', '/wiː niːd tuː reɪz ðə bɑːr/', 'Informal. Literal: "levantar a barra". Real: aumentar a exigência.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"raise","pos":"verb","ipa":"/reɪz/","gloss":"elevar, aumentar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bar","pos":"noun","ipa":"/bɑːr/","gloss":"barra; padrão"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-15-10', 'lesson-work-b1-15', 10, 'sentence', 'Let''s celebrate this win.', 'Vamos comemorar esta conquista.', '/lɛts ˈsɛləbreɪt ðɪs wɪn/', 'Neutro. "Win" = vitória, conquista.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"celebrate","pos":"verb","ipa":"/ˈsɛləbreɪt/","gloss":"comemorar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"win","pos":"noun","ipa":"/wɪn/","gloss":"vitória, conquista"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-work-b1-16', 'course-work-b1', 16, 'Revisão: um dia de trabalho', 'Uma frase de cada capítulo do curso.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-work-b1-16-01', 'lesson-work-b1-16', 1, 'sentence', 'Let''s get started.', 'Vamos começar.', '/lɛts ɡɛt ˈstɑːrtɪd/', 'Revisão de reuniões.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"started","pos":"verb","ipa":"/ˈstɑːrtɪd/","gloss":"começado"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-02', 'lesson-work-b1-16', 2, 'sentence', 'Please find the file attached.', 'Segue o arquivo em anexo.', '/pliːz faɪnd ðə faɪl əˈtætʃt/', 'Revisão de e-mails.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"find","pos":"verb","ipa":"/faɪnd/","gloss":"encontrar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"file","pos":"noun","ipa":"/faɪl/","gloss":"arquivo"},{"surface":"attached","pos":"adjective","ipa":"/əˈtætʃt/","gloss":"anexado"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-03', 'lesson-work-b1-16', 3, 'sentence', 'I''ll keep you posted.', 'Vou te mantendo informado.', '/aɪl kiːp juː ˈpoʊstɪd/', 'Revisão de trabalho remoto.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"posted","pos":"adjective","ipa":"/ˈpoʊstɪd/","gloss":"informado (keep posted)"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-04', 'lesson-work-b1-16', 4, 'sentence', 'Let''s move on to the next point.', 'Vamos passar para o próximo ponto.', '/lɛts muːv ɑːn tuː ðə nɛkst pɔɪnt/', 'Revisão de apresentações.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"move","pos":"verb","ipa":"/muːv/","gloss":"mover, passar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-05', 'lesson-work-b1-16', 5, 'sentence', 'Thanks for the feedback.', 'Obrigado pelo retorno.', '/θæŋks fɔːr ðə ˈfiːdbæk/', 'Revisão de feedback.', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"feedback","pos":"noun","ipa":"/ˈfiːdbæk/","gloss":"retorno, feedback"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-06', 'lesson-work-b1-16', 6, 'sentence', 'Can we extend the deadline?', 'Podemos estender o prazo?', '/kæn wiː ɪkˈstɛnd ðə ˈdɛdlaɪn/', 'Revisão de negociação.', '[]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"extend","pos":"verb","ipa":"/ɪkˈstɛnd/","gloss":"estender, prorrogar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"deadline","pos":"noun","ipa":"/ˈdɛdlaɪn/","gloss":"prazo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-07', 'lesson-work-b1-16', 7, 'sentence', 'Could you hold for a moment?', 'Pode aguardar um instante?', '/kʊd juː hoʊld fɔːr ə ˈmoʊmənt/', 'Revisão de ligações.', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"hold","pos":"verb","ipa":"/hoʊld/","gloss":"aguardar (na linha), segurar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"moment","pos":"noun","ipa":"/ˈmoʊmənt/","gloss":"momento"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-08', 'lesson-work-b1-16', 8, 'sentence', 'Tell me a little about yourself.', 'Fale um pouco sobre você.', '/tɛl miː ə ˈlɪtəl əˈbaʊt jərˈsɛlf/', 'Revisão de entrevista.', '[]'::jsonb, '[{"surface":"Tell","pos":"verb","ipa":"/tɛl/","gloss":"contar, dizer"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"little","pos":"adjective","ipa":"/ˈlɪtəl/","gloss":"pouco, pequeno"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"yourself","pos":"pronoun","ipa":"/jərˈsɛlf/","gloss":"você mesmo"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-09', 'lesson-work-b1-16', 9, 'sentence', 'I look forward to hearing from you.', 'Aguardo seu retorno.', '/aɪ lʊk ˈfɔːrwərd tuː ˈhɪrɪŋ frʌm juː/', 'Revisão de e-mails formais.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"forward","pos":"adverb","ipa":"/ˈfɔːrwərd/","gloss":"adiante (look forward)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"hearing","pos":"verb","ipa":"/ˈhɪrɪŋ/","gloss":"ouvir, ter notícias"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-work-b1-16-10', 'lesson-work-b1-16', 10, 'sentence', 'Let''s focus on the solution.', 'Vamos focar na solução.', '/lɛts ˈfoʊkəs ɑːn ðə səˈluːʃən/', 'Revisão de conflitos.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"focus","pos":"verb","ipa":"/ˈfoʊkəs/","gloss":"focar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"solution","pos":"noun","ipa":"/səˈluːʃən/","gloss":"solução"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
