-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-register-c1', 'register-and-precision-c1', 'Registro e Precisão', 'Formal ou informal? Cauteloso ou direto? Escolher a palavra e o tom certos em textos e reuniões.', 'No C1 o desafio deixa de ser a gramática e passa a ser a escolha: o registro certo para cada situação, a cautela de quem escreve com rigor, a precisão de quem analisa. Cada frase mostra a versão neutra e a versão mais refinada.', 'C1', 'writing', 26, 'fluencia', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-register-c1-01', 'course-register-c1', 1, 'Formal ou informal', 'A mesma ideia em dois registros.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-register-c1-01-01', 'lesson-register-c1-01', 1, 'sentence', 'Could you please let me know whether you are available?', 'Poderia me informar se está disponível?', '/kʊd juː pliːz lɛt miː noʊ ˈwɛðər juː ɑːr əˈveɪləbəl/', 'Formal; a versão informal seria "Are you free?".', '[]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"whether","pos":"conjunction","ipa":"/ˈwɛðər/","gloss":"se (dúvida)"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"available","pos":"adjective","ipa":"/əˈveɪləbəl/","gloss":"disponível"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-02', 'lesson-register-c1-01', 2, 'sentence', 'I would be grateful if you could send the documents.', 'Eu agradeceria se você pudesse enviar os documentos.', '/aɪ wʊd biː ˈɡreɪtfəl ɪf juː kʊd sɛnd ðə ˈdɑːkjəmənts/', 'Pedido formal por escrito.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"grateful","pos":"adjective","ipa":"/ˈɡreɪtfəl/","gloss":"grato"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"send","pos":"verb","ipa":"/sɛnd/","gloss":"enviar, mandar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"documents","pos":"noun","ipa":"/ˈdɑːkjəmənts/","gloss":"documentos"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-03', 'lesson-register-c1-01', 3, 'sentence', 'We regret to inform you that the position has been filled.', 'Lamentamos informar que a vaga foi preenchida.', '/wiː rɪˈɡrɛt tuː ɪnˈfɔːrm juː ðæt ðə pəˈzɪʃən hæz bɪn fɪld/', 'Fórmula fixa de recusa formal.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"regret","pos":"verb","ipa":"/rɪˈɡrɛt/","gloss":"lamentar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"inform","pos":"verb","ipa":"/ɪnˈfɔːrm/","gloss":"informar"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"position","pos":"noun","ipa":"/pəˈzɪʃən/","gloss":"cargo, vaga"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"filled","pos":"verb","ipa":"/fɪld/","gloss":"encheu, preencheu"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-04', 'lesson-register-c1-01', 4, 'sentence', 'Sorry, but I cannot make it.', 'Desculpe, mas não vou conseguir ir.', '/ˈsɑːri bʌt aɪ ˈkænɑːt meɪk ɪt/', 'Informal; a versão formal seria "Unfortunately, I am unable to attend".', '[]'::jsonb, '[{"surface":"Sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"cannot","pos":"verb","ipa":"/ˈkænɑːt/","gloss":"não posso, não consigo"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-05', 'lesson-register-c1-01', 5, 'sentence', 'Unfortunately, I am unable to attend the meeting.', 'Infelizmente não poderei comparecer à reunião.', '/ʌnˈfɔːrtʃənətli aɪ æm ʌnˈeɪbəl tuː əˈtɛnd ðə ˈmiːtɪŋ/', 'Formal; evita contrações e "can".', '[]'::jsonb, '[{"surface":"Unfortunately","pos":"adverb","ipa":"/ʌnˈfɔːrtʃənətli/","gloss":"infelizmente"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"unable","pos":"adjective","ipa":"/ʌnˈeɪbəl/","gloss":"incapaz, sem poder"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"attend","pos":"verb","ipa":"/əˈtɛnd/","gloss":"comparecer"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-06', 'lesson-register-c1-01', 6, 'sentence', 'Thanks a bunch for your help.', 'Valeu demais pela ajuda.', '/θæŋks ə bʌntʃ fɔːr jʊr hɛlp/', 'Muito informal; só entre amigos ou colegas próximos.', '[]'::jsonb, '[{"surface":"Thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bunch","pos":"noun","ipa":"/bʌntʃ/","gloss":"monte"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-07', 'lesson-register-c1-01', 7, 'sentence', 'I am writing to enquire about your services.', 'Escrevo para obter informações sobre seus serviços.', '/aɪ æm ˈraɪtɪŋ tuː ɪnˈkwaɪər əˈbaʊt jʊr ˈsɜːrvɪsɪz/', 'Abertura típica de carta ou e-mail formal.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"writing","pos":"noun","ipa":"/ˈraɪtɪŋ/","gloss":"escrita"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"enquire","pos":"verb","ipa":"/ɪnˈkwaɪər/","gloss":"pedir informações"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"services","pos":"noun","ipa":"/ˈsɜːrvɪsɪz/","gloss":"serviços"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-08', 'lesson-register-c1-01', 8, 'sentence', 'Let me know if you need anything else.', 'Me avisa se precisar de mais alguma coisa.', '/lɛt miː noʊ ɪf juː niːd ˈɛniθɪŋ ɛls/', 'Neutro-informal, comum entre colegas.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"},{"surface":"else","pos":"adverb","ipa":"/ɛls/","gloss":"mais, outro"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-09', 'lesson-register-c1-01', 9, 'sentence', 'Please do not hesitate to contact me.', 'Não hesite em entrar em contato comigo.', '/pliːz duː nɑːt ˈhɛzɪteɪt tuː ˈkɑːntækt miː/', 'Fechamento formal muito usado.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"hesitate","pos":"verb","ipa":"/ˈhɛzɪteɪt/","gloss":"hesitar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"contact","pos":"verb","ipa":"/ˈkɑːntækt/","gloss":"contatar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-01-10', 'lesson-register-c1-01', 10, 'sentence', 'Cheers, talk soon.', 'Valeu, falamos em breve.', '/tʃɪrz tɔːk suːn/', 'Informal britânico; "cheers" também agradece e se despede.', '[]'::jsonb, '[{"surface":"Cheers","pos":"interjection","ipa":"/tʃɪrz/","gloss":"valeu, saúde"},{"surface":"talk","pos":"verb","ipa":"/tɔːk/","gloss":"falar"},{"surface":"soon","pos":"adverb","ipa":"/suːn/","gloss":"logo"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-register-c1-02', 'course-register-c1', 2, 'Cautela acadêmica', 'Hedging: afirmar sem exagerar a certeza.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-register-c1-02-01', 'lesson-register-c1-02', 1, 'sentence', 'The results appear to support this hypothesis.', 'Os resultados parecem sustentar esta hipótese.', '/ðə rɪˈzʌlts əˈpɪr tuː səˈpɔːrt ðɪs haɪˈpɑːθəsɪs/', '"Appear to" modera a certeza.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"results","pos":"noun","ipa":"/rɪˈzʌlts/","gloss":"resultados"},{"surface":"appear","pos":"verb","ipa":"/əˈpɪr/","gloss":"aparecer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"support","pos":"verb","ipa":"/səˈpɔːrt/","gloss":"apoiar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"hypothesis","pos":"noun","ipa":"/haɪˈpɑːθəsɪs/","gloss":"hipótese"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-02', 'lesson-register-c1-02', 2, 'sentence', 'This may suggest a link between the two factors.', 'Isso pode sugerir uma ligação entre os dois fatores.', '/ðɪs meɪ səɡˈdʒɛst ə lɪŋk bɪˈtwiːn ðə tuː ˈfæktərz/', '"May suggest" evita afirmar demais.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"may","pos":"modal verb","ipa":"/meɪ/","gloss":"poder (permissão formal)"},{"surface":"suggest","pos":"verb","ipa":"/səɡˈdʒɛst/","gloss":"sugerir"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"link","pos":"noun","ipa":"/lɪŋk/","gloss":"link"},{"surface":"between","pos":"preposition","ipa":"/bɪˈtwiːn/","gloss":"entre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"factors","pos":"noun","ipa":"/ˈfæktərz/","gloss":"fatores"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-03', 'lesson-register-c1-02', 3, 'sentence', 'It is likely that demand will continue to grow.', 'É provável que a demanda continue a crescer.', '/ɪt ɪz ˈlaɪkli ðæt dɪˈmænd wɪl kənˈtɪnjuː tuː ɡroʊ/', '"It is likely that" indica probabilidade.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"likely","pos":"adjective","ipa":"/ˈlaɪkli/","gloss":"provável"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"demand","pos":"noun","ipa":"/dɪˈmænd/","gloss":"demanda"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"continue","pos":"verb","ipa":"/kənˈtɪnjuː/","gloss":"continuar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"grow","pos":"verb","ipa":"/ɡroʊ/","gloss":"crescer"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-04', 'lesson-register-c1-02', 4, 'sentence', 'These findings tend to be consistent across studies.', 'Estes resultados tendem a ser consistentes entre os estudos.', '/ðiːz ˈfaɪndɪŋz tɛnd tuː biː kənˈsɪstənt əˈkrɔːs ˈstʌdiz/', '"Tend to" = em geral, mas não sempre.', '[]'::jsonb, '[{"surface":"These","pos":"determiner","ipa":"/ðiːz/","gloss":"estes, estas"},{"surface":"findings","pos":"noun","ipa":"/ˈfaɪndɪŋz/","gloss":"resultados, descobertas"},{"surface":"tend","pos":"verb","ipa":"/tɛnd/","gloss":"tender"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"consistent","pos":"adjective","ipa":"/kənˈsɪstənt/","gloss":"consistente"},{"surface":"across","pos":"preposition","ipa":"/əˈkrɔːs/","gloss":"do outro lado de, atravessando"},{"surface":"studies","pos":"verb","ipa":"/ˈstʌdiz/","gloss":"estuda"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-05', 'lesson-register-c1-02', 5, 'sentence', 'To some extent, the plan has succeeded.', 'Até certo ponto, o plano deu certo.', '/tuː sʌm ɪkˈstɛnt ðə plæn hæz səkˈsiːdɪd/', '"To some extent" limita a afirmação.', '[]'::jsonb, '[{"surface":"To","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"extent","pos":"noun","ipa":"/ɪkˈstɛnt/","gloss":"medida, extensão"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"plan","pos":"noun","ipa":"/plæn/","gloss":"plano"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"succeeded","pos":"verb","ipa":"/səkˈsiːdɪd/","gloss":"deu certo, teve sucesso"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-06', 'lesson-register-c1-02', 6, 'sentence', 'The data seem to indicate a decline.', 'Os dados parecem indicar uma queda.', '/ðə ˈdeɪtə siːm tuː ˈɪndɪkeɪt ə dɪˈklaɪn/', 'Verbo modal de cautela, não de certeza.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"data","pos":"noun","ipa":"/ˈdeɪtə/","gloss":"dados"},{"surface":"seem","pos":"verb","ipa":"/siːm/","gloss":"parecer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"indicate","pos":"verb","ipa":"/ˈɪndɪkeɪt/","gloss":"indicar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"decline","pos":"noun","ipa":"/dɪˈklaɪn/","gloss":"queda, declínio; recusar"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-07', 'lesson-register-c1-02', 7, 'sentence', 'It would be premature to draw firm conclusions.', 'Seria prematuro tirar conclusões firmes.', '/ɪt wʊd biː ˌpriːməˈtʃʊr tuː drɔː fɜːrm kənˈkluːʒənz/', '"Premature" = antes da hora.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"premature","pos":"adjective","ipa":"/ˌpriːməˈtʃʊr/","gloss":"prematuro"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"draw","pos":"verb","ipa":"/drɔː/","gloss":"redigir, desenhar"},{"surface":"firm","pos":"adjective","ipa":"/fɜːrm/","gloss":"firme; empresa"},{"surface":"conclusions","pos":"noun","ipa":"/kənˈkluːʒənz/","gloss":"conclusões"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-08', 'lesson-register-c1-02', 8, 'sentence', 'This is, in all probability, a temporary effect.', 'Isto é, com toda probabilidade, um efeito temporário.', '/ðɪs ɪz ɪn ɔːl ˌprɑːbəˈbɪləti ə ˈtɛmpərɛri ɪˈfɛkt/', '"In all probability" = muito provavelmente.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"probability","pos":"noun","ipa":"/ˌprɑːbəˈbɪləti/","gloss":"probabilidade"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"temporary","pos":"adjective","ipa":"/ˈtɛmpərɛri/","gloss":"temporário"},{"surface":"effect","pos":"noun","ipa":"/ɪˈfɛkt/","gloss":"efeito"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-09', 'lesson-register-c1-02', 9, 'sentence', 'Further research is needed to confirm this.', 'É preciso mais pesquisa para confirmar isso.', '/ˈfɜːrðər ˈriːsɜːrtʃ ɪz ˈniːdɪd tuː kənˈfɜːrm ðɪs/', 'Fecha um argumento reconhecendo o limite.', '[]'::jsonb, '[{"surface":"Further","pos":"adjective","ipa":"/ˈfɜːrðər/","gloss":"adicional, mais"},{"surface":"research","pos":"noun","ipa":"/ˈriːsɜːrtʃ/","gloss":"pesquisa"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"needed","pos":"verb","ipa":"/ˈniːdɪd/","gloss":"precisou"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"confirm","pos":"verb","ipa":"/kənˈfɜːrm/","gloss":"confirmar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-02-10', 'lesson-register-c1-02', 10, 'sentence', 'One could argue that the opposite is true.', 'Pode-se argumentar que o oposto é verdade.', '/wʌn kʊd ˈɑːrɡjuː ðæt ðə ˈɑːpəzɪt ɪz truː/', '"One could argue" = construção impessoal e cautelosa.', '[]'::jsonb, '[{"surface":"One","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"argue","pos":"verb","ipa":"/ˈɑːrɡjuː/","gloss":"defender, sustentar"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"opposite","pos":"preposition","ipa":"/ˈɑːpəzɪt/","gloss":"em frente a, do outro lado"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"true","pos":"adjective","ipa":"/truː/","gloss":"verdadeiro"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-register-c1-03', 'course-register-c1', 3, 'Nominalização', 'Trocar verbos por substantivos para escrever de forma mais densa.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-register-c1-03-01', 'lesson-register-c1-03', 1, 'sentence', 'The increase in prices surprised everyone.', 'O aumento nos preços surpreendeu a todos.', '/ðə ˈɪnkriːs ɪn ˈpraɪsɪz sərˈpraɪzd ˈɛvriwʌn/', 'Em vez de "prices increased", usa-se o substantivo.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"increase","pos":"noun","ipa":"/ˈɪnkriːs/","gloss":"aumento"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"prices","pos":"noun","ipa":"/ˈpraɪsɪz/","gloss":"preços"},{"surface":"surprised","pos":"adjective","ipa":"/sərˈpraɪzd/","gloss":"surpreso"},{"surface":"everyone","pos":"pronoun","ipa":"/ˈɛvriwʌn/","gloss":"todo mundo, pessoal"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-02', 'lesson-register-c1-03', 2, 'sentence', 'Their rapid expansion led to staffing problems.', 'A expansão rápida deles levou a problemas de pessoal.', '/ðɛr ˈræpɪd ɪkˈspænʃən lɛd tuː ˈstæfɪŋ ˈprɑːbləmz/', 'Nominalização torna a frase mais compacta.', '[]'::jsonb, '[{"surface":"Their","pos":"determiner","ipa":"/ðɛr/","gloss":"deles, delas"},{"surface":"rapid","pos":"adjective","ipa":"/ˈræpɪd/","gloss":"rápido"},{"surface":"expansion","pos":"noun","ipa":"/ɪkˈspænʃən/","gloss":"expansão"},{"surface":"led","pos":"verb","ipa":"/lɛd/","gloss":"liderou"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"staffing","pos":"noun","ipa":"/ˈstæfɪŋ/","gloss":"quadro de pessoal"},{"surface":"problems","pos":"noun","ipa":"/ˈprɑːbləmz/","gloss":"problemas"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-03', 'lesson-register-c1-03', 3, 'sentence', 'The failure to act proved costly.', 'A falta de ação saiu cara.', '/ðə ˈfeɪljər tuː ækt pruːvd ˈkɔːstli/', '"The failure to" + verbo = a omissão de.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"failure","pos":"noun","ipa":"/ˈfeɪljər/","gloss":"fracasso"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"act","pos":"verb","ipa":"/ækt/","gloss":"agir"},{"surface":"proved","pos":"verb","ipa":"/pruːvd/","gloss":"mostrou-se, provou"},{"surface":"costly","pos":"adjective","ipa":"/ˈkɔːstli/","gloss":"caro, custoso"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-04', 'lesson-register-c1-03', 4, 'sentence', 'A reduction in costs is expected next year.', 'Espera-se uma redução nos custos no próximo ano.', '/ə rɪˈdʌkʃən ɪn kɔːsts ɪz ɪkˈspɛktɪd nɛkst jɪr/', 'Formal e impessoal.', '[]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"reduction","pos":"noun","ipa":"/rɪˈdʌkʃən/","gloss":"redução"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"expected","pos":"verb","ipa":"/ɪkˈspɛktɪd/","gloss":"esperado"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"year","pos":"noun","ipa":"/jɪr/","gloss":"ano"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-05', 'lesson-register-c1-03', 5, 'sentence', 'The decision to relocate was widely criticized.', 'A decisão de se mudar foi muito criticada.', '/ðə dɪˈsɪʒən tuː ˌriːˈloʊkeɪt wɑːz ˈwaɪdli ˈkrɪtɪsaɪzd/', '"The decision to" + verbo = a decisão de.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"decision","pos":"noun","ipa":"/dɪˈsɪʒən/","gloss":"decisão"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"relocate","pos":"verb","ipa":"/ˌriːˈloʊkeɪt/","gloss":"mudar-se (de cidade)"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"widely","pos":"adverb","ipa":"/ˈwaɪdli/","gloss":"amplamente"},{"surface":"criticized","pos":"verb","ipa":"/ˈkrɪtɪsaɪzd/","gloss":"criticado"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-06', 'lesson-register-c1-03', 6, 'sentence', 'Growing awareness of the issue has changed attitudes.', 'A crescente conscientização do problema mudou atitudes.', '/ˈɡroʊɪŋ əˈwɛrnəs ʌv ðə ˈɪʃuː hæz tʃeɪndʒd ˈætɪtuːdz/', '"Awareness of" = conscientização sobre.', '[]'::jsonb, '[{"surface":"Growing","pos":"adjective","ipa":"/ˈɡroʊɪŋ/","gloss":"crescente"},{"surface":"awareness","pos":"noun","ipa":"/əˈwɛrnəs/","gloss":"conscientização"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"issue","pos":"noun","ipa":"/ˈɪʃuː/","gloss":"assunto, problema"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"changed","pos":"verb","ipa":"/tʃeɪndʒd/","gloss":"mudou, mudado"},{"surface":"attitudes","pos":"noun","ipa":"/ˈætɪtuːdz/","gloss":"atitudes"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-07', 'lesson-register-c1-03', 7, 'sentence', 'His reluctance to speak was understandable.', 'A relutância dele em falar era compreensível.', '/hɪz rɪˈlʌktəns tuː spiːk wɑːz ˌʌndərˈstændəbəl/', 'Substantivo no lugar de "he was reluctant".', '[]'::jsonb, '[{"surface":"His","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"reluctance","pos":"noun","ipa":"/rɪˈlʌktəns/","gloss":"relutância"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"speak","pos":"verb","ipa":"/spiːk/","gloss":"falar"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"understandable","pos":"adjective","ipa":"/ˌʌndərˈstændəbəl/","gloss":"compreensível"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-08', 'lesson-register-c1-03', 8, 'sentence', 'There has been a steady decline in quality.', 'Houve um declínio constante na qualidade.', '/ðɛr hæz bɪn ə ˈstɛdi dɪˈklaɪn ɪn ˈkwɑːləti/', '"There has been" apresenta uma mudança.', '[]'::jsonb, '[{"surface":"There","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"steady","pos":"adjective","ipa":"/ˈstɛdi/","gloss":"estável"},{"surface":"decline","pos":"noun","ipa":"/dɪˈklaɪn/","gloss":"queda, declínio; recusar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"quality","pos":"noun","ipa":"/ˈkwɑːləti/","gloss":"qualidade"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-09', 'lesson-register-c1-03', 9, 'sentence', 'The introduction of new rules caused confusion.', 'A introdução de novas regras causou confusão.', '/ðə ˌɪntrəˈdʌkʃən ʌv nuː ruːlz kɔːzd kənˈfjuːʒən/', 'Em vez de "they introduced new rules".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"introduction","pos":"noun","ipa":"/ˌɪntrəˈdʌkʃən/","gloss":"introdução"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"rules","pos":"noun","ipa":"/ruːlz/","gloss":"regras"},{"surface":"caused","pos":"verb","ipa":"/kɔːzd/","gloss":"causou"},{"surface":"confusion","pos":"noun","ipa":"/kənˈfjuːʒən/","gloss":"confusão"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-03-10', 'lesson-register-c1-03', 10, 'sentence', 'Careful consideration is required before any change.', 'É necessária uma consideração cuidadosa antes de qualquer mudança.', '/ˈkɛrfəl kənˌsɪdəˈreɪʃən ɪz rɪˈkwaɪərd bɪˈfɔːr ˈɛni tʃeɪndʒ/', 'Impessoal; típico de regulamentos.', '[]'::jsonb, '[{"surface":"Careful","pos":"adjective","ipa":"/ˈkɛrfəl/","gloss":"cuidadoso"},{"surface":"consideration","pos":"noun","ipa":"/kənˌsɪdəˈreɪʃən/","gloss":"consideração"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"required","pos":"verb","ipa":"/rɪˈkwaɪərd/","gloss":"exigido, necessário"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-register-c1-04', 'course-register-c1', 4, 'Conectores avançados', 'Contraste, concessão e consequência em frases mais longas.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-register-c1-04-01', 'lesson-register-c1-04', 1, 'sentence', 'The plan is sound; nevertheless, it carries some risk.', 'O plano é sólido; no entanto, tem algum risco.', '/ðə plæn ɪz saʊnd ˌnɛvərðəˈlɛs ɪt ˈkæriz sʌm rɪsk/', '"Nevertheless" = ainda assim; mais formal que "but".', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"plan","pos":"noun","ipa":"/plæn/","gloss":"plano"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"sound","pos":"adjective","ipa":"/saʊnd/","gloss":"sólido, bem fundamentado"},{"surface":"nevertheless","pos":"adverb","ipa":"/ˌnɛvərðəˈlɛs/","gloss":"no entanto"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"carries","pos":"verb","ipa":"/ˈkæriz/","gloss":"carrega, traz"},{"surface":"some","pos":"determiner","ipa":"/sʌm/","gloss":"algumas"},{"surface":"risk","pos":"noun","ipa":"/rɪsk/","gloss":"risco"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-02', 'lesson-register-c1-04', 2, 'sentence', 'Sales rose, whereas profits fell.', 'As vendas subiram, enquanto os lucros caíram.', '/seɪlz roʊz wɛrˈæz ˈprɑːfɪts fɛl/', '"Whereas" contrasta duas situações.', '[]'::jsonb, '[{"surface":"Sales","pos":"noun","ipa":"/seɪlz/","gloss":"vendas"},{"surface":"rose","pos":"verb","ipa":"/roʊz/","gloss":"subiu"},{"surface":"whereas","pos":"conjunction","ipa":"/wɛrˈæz/","gloss":"enquanto (contraste)"},{"surface":"profits","pos":"noun","ipa":"/ˈprɑːfɪts/","gloss":"lucros"},{"surface":"fell","pos":"verb","ipa":"/fɛl/","gloss":"caiu"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-03', 'lesson-register-c1-04', 3, 'sentence', 'The room was small, albeit comfortable.', 'O quarto era pequeno, embora confortável.', '/ðə ruːm wɑːz smɔːl ɔːlˈbiːɪt ˈkʌmftərbəl/', '"Albeit" = embora; liga uma única palavra ou trecho.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"room","pos":"noun","ipa":"/ruːm/","gloss":"quarto"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"small","pos":"adjective","ipa":"/smɔːl/","gloss":"pequeno"},{"surface":"albeit","pos":"conjunction","ipa":"/ɔːlˈbiːɪt/","gloss":"embora"},{"surface":"comfortable","pos":"adjective","ipa":"/ˈkʌmftərbəl/","gloss":"confortável"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-04', 'lesson-register-c1-04', 4, 'sentence', 'Notwithstanding the delays, the project was completed.', 'Apesar dos atrasos, o projeto foi concluído.', '/ˌnɑːtwɪθˈstændɪŋ ðə dɪˈleɪz ðə ˈprɑːdʒɛkt wɑːz kəmˈpliːtɪd/', '"Notwithstanding" = apesar de; muito formal.', '[]'::jsonb, '[{"surface":"Notwithstanding","pos":"preposition","ipa":"/ˌnɑːtwɪθˈstændɪŋ/","gloss":"apesar de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"delays","pos":"noun","ipa":"/dɪˈleɪz/","gloss":"atrasos"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"project","pos":"noun","ipa":"/ˈprɑːdʒɛkt/","gloss":"projeto"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"completed","pos":"verb","ipa":"/kəmˈpliːtɪd/","gloss":"concluído"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-05', 'lesson-register-c1-04', 5, 'sentence', 'Consequently, the company changed its strategy.', 'Consequentemente, a empresa mudou sua estratégia.', '/ˈkɑːnsəkwɛntli ðə ˈkʌmpəni tʃeɪndʒd ɪts ˈstrætədʒi/', '"Consequently" indica resultado.', '[]'::jsonb, '[{"surface":"Consequently","pos":"adverb","ipa":"/ˈkɑːnsəkwɛntli/","gloss":"consequentemente"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"company","pos":"noun","ipa":"/ˈkʌmpəni/","gloss":"empresa"},{"surface":"changed","pos":"verb","ipa":"/tʃeɪndʒd/","gloss":"mudou, mudado"},{"surface":"its","pos":"determiner","ipa":"/ɪts/","gloss":"seu, sua (de coisa)"},{"surface":"strategy","pos":"noun","ipa":"/ˈstrætədʒi/","gloss":"estratégia"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-06', 'lesson-register-c1-04', 6, 'sentence', 'Provided that costs stay low, we will proceed.', 'Desde que os custos fiquem baixos, seguiremos adiante.', '/prəˈvaɪdɪd ðæt kɔːsts steɪ loʊ wiː wɪl prəˈsiːd/', '"Provided that" = condição firme.', '[]'::jsonb, '[{"surface":"Provided","pos":"conjunction","ipa":"/prəˈvaɪdɪd/","gloss":"desde que"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"},{"surface":"stay","pos":"verb","ipa":"/steɪ/","gloss":"ficar"},{"surface":"low","pos":"adjective","ipa":"/loʊ/","gloss":"baixo, acabando"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"proceed","pos":"verb","ipa":"/prəˈsiːd/","gloss":"prosseguir"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-07', 'lesson-register-c1-04', 7, 'sentence', 'On the one hand it is cheap; on the other, it is slow.', 'Por um lado é barato; por outro, é lento.', '/ɑːn ðə wʌn hænd ɪt ɪz tʃiːp ɑːn ðə ˈʌðər ɪt ɪz sloʊ/', 'Estrutura para comparar vantagens e desvantagens.', '[]'::jsonb, '[{"surface":"On","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"hand","pos":"noun","ipa":"/hænd/","gloss":"mão, ajuda"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"cheap","pos":"adjective","ipa":"/tʃiːp/","gloss":"barato"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"other","pos":"pronoun","ipa":"/ˈʌðər/","gloss":"outro"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"slow","pos":"adjective","ipa":"/sloʊ/","gloss":"lento"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-08', 'lesson-register-c1-04', 8, 'sentence', 'Even though it was late, we kept working.', 'Mesmo sendo tarde, continuamos trabalhando.', '/ˈiːvən ðoʊ ɪt wɑːz leɪt wiː kɛpt ˈwɜːrkɪŋ/', '"Even though" reforça a concessão.', '[]'::jsonb, '[{"surface":"Even","pos":"adverb","ipa":"/ˈiːvən/","gloss":"até, mesmo"},{"surface":"though","pos":"conjunction","ipa":"/ðoʊ/","gloss":"embora"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"kept","pos":"verb","ipa":"/kɛpt/","gloss":"guardou, manteve"},{"surface":"working","pos":"verb","ipa":"/ˈwɜːrkɪŋ/","gloss":"funcionando; trabalhando"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-09', 'lesson-register-c1-04', 9, 'sentence', 'In spite of the rain, the match went ahead.', 'Apesar da chuva, a partida continuou.', '/ɪn spaɪt ʌv ðə reɪn ðə mætʃ wɛnt əˈhɛd/', '"In spite of" + substantivo.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"spite","pos":"noun","ipa":"/spaɪt/","gloss":"despeito (in spite of = apesar de)"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"rain","pos":"verb","ipa":"/reɪn/","gloss":"chover; chuva"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"match","pos":"noun","ipa":"/mætʃ/","gloss":"partida"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"ahead","pos":"adverb","ipa":"/əˈhɛd/","gloss":"à frente, adiante"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-04-10', 'lesson-register-c1-04', 10, 'sentence', 'Hence, further action is required.', 'Portanto, é necessária mais ação.', '/hɛns ˈfɜːrðər ˈækʃən ɪz rɪˈkwaɪərd/', '"Hence" = por isso; formal e curto.', '[]'::jsonb, '[{"surface":"Hence","pos":"adverb","ipa":"/hɛns/","gloss":"por isso, portanto"},{"surface":"further","pos":"adjective","ipa":"/ˈfɜːrðər/","gloss":"adicional, mais"},{"surface":"action","pos":"noun","ipa":"/ˈækʃən/","gloss":"ação"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"required","pos":"verb","ipa":"/rɪˈkwaɪərd/","gloss":"exigido, necessário"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-register-c1-05', 'course-register-c1', 5, 'Verbos formais', 'Escolhas mais precisas que os verbos do dia a dia.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-register-c1-05-01', 'lesson-register-c1-05', 1, 'sentence', 'You are required to submit the form by Friday.', 'Você deve enviar o formulário até sexta.', '/juː ɑːr rɪˈkwaɪərd tuː səbˈmɪt ðə fɔːrm baɪ ˈfraɪdeɪ/', '"Required to" é mais formal que "have to".', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"required","pos":"verb","ipa":"/rɪˈkwaɪərd/","gloss":"exigido, necessário"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"submit","pos":"verb","ipa":"/səbˈmɪt/","gloss":"enviar, submeter"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"form","pos":"noun","ipa":"/fɔːrm/","gloss":"formulário"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"Friday","pos":"proper noun","ipa":"/ˈfraɪdeɪ/","gloss":"sexta-feira"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-02', 'lesson-register-c1-05', 2, 'sentence', 'We aim to obtain approval within a week.', 'Pretendemos obter a aprovação em uma semana.', '/wiː eɪm tuː əbˈteɪn əˈpruːvəl wɪˈðɪn ə wiːk/', '"Obtain" = conseguir; formal.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"aim","pos":"verb","ipa":"/eɪm/","gloss":"pretender, ter como meta"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"obtain","pos":"verb","ipa":"/əbˈteɪn/","gloss":"obter"},{"surface":"approval","pos":"noun","ipa":"/əˈpruːvəl/","gloss":"aprovação"},{"surface":"within","pos":"preposition","ipa":"/wɪˈðɪn/","gloss":"dentro de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-03', 'lesson-register-c1-05', 3, 'sentence', 'The committee will determine the outcome.', 'O comitê determinará o resultado.', '/ðə kəˈmɪti wɪl dɪˈtɜːrmɪn ðə ˈaʊtkʌm/', '"Determine" = decidir, estabelecer.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"committee","pos":"noun","ipa":"/kəˈmɪti/","gloss":"comitê"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"determine","pos":"verb","ipa":"/dɪˈtɜːrmɪn/","gloss":"determinar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"outcome","pos":"noun","ipa":"/ˈaʊtkʌm/","gloss":"resultado"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-04', 'lesson-register-c1-05', 4, 'sentence', 'Participants must refrain from using their phones.', 'Os participantes devem abster-se de usar o celular.', '/pɑːrˈtɪsɪpənts mʌst rɪˈfreɪn frʌm ˈjuːzɪŋ ðɛr foʊnz/', '"Refrain from" = abster-se.', '[]'::jsonb, '[{"surface":"Participants","pos":"noun","ipa":"/pɑːrˈtɪsɪpənts/","gloss":"participantes"},{"surface":"must","pos":"verb","ipa":"/mʌst/","gloss":"dever, ter que"},{"surface":"refrain","pos":"verb","ipa":"/rɪˈfreɪn/","gloss":"abster-se"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"using","pos":"verb","ipa":"/ˈjuːzɪŋ/","gloss":"usando"},{"surface":"their","pos":"determiner","ipa":"/ðɛr/","gloss":"deles, delas"},{"surface":"phones","pos":"noun","ipa":"/foʊnz/","gloss":"celulares"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-05', 'lesson-register-c1-05', 5, 'sentence', 'The new policy will come into effect in May.', 'A nova política entrará em vigor em maio.', '/ðə nuː ˈpɑːləsi wɪl kʌm ˈɪntuː ɪˈfɛkt ɪn meɪ/', '"Come into effect" = entrar em vigor.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"policy","pos":"noun","ipa":"/ˈpɑːləsi/","gloss":"política, regra"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"into","pos":"preposition","ipa":"/ˈɪntuː/","gloss":"para dentro de"},{"surface":"effect","pos":"noun","ipa":"/ɪˈfɛkt/","gloss":"efeito"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"May","pos":"modal verb","ipa":"/meɪ/","gloss":"poder (permissão formal)"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-06', 'lesson-register-c1-05', 6, 'sentence', 'We were unable to locate the missing file.', 'Não conseguimos localizar o arquivo perdido.', '/wiː wɜːr ʌnˈeɪbəl tuː ˈloʊkeɪt ðə ˈmɪsɪŋ faɪl/', '"Locate" = encontrar; formal.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"were","pos":"verb","ipa":"/wɜːr/","gloss":"eram, estavam"},{"surface":"unable","pos":"adjective","ipa":"/ʌnˈeɪbəl/","gloss":"incapaz, sem poder"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"locate","pos":"verb","ipa":"/ˈloʊkeɪt/","gloss":"localizar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"missing","pos":"verb","ipa":"/ˈmɪsɪŋ/","gloss":"perdendo, deixando de captar"},{"surface":"file","pos":"noun","ipa":"/faɪl/","gloss":"arquivo"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-07', 'lesson-register-c1-05', 7, 'sentence', 'He declined to comment on the matter.', 'Ele se recusou a comentar o assunto.', '/hiː dɪˈklaɪnd tuː ˈkɑːmɛnt ɑːn ðə ˈmætər/', '"Decline to" = recusar-se cortesmente.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"declined","pos":"verb","ipa":"/dɪˈklaɪnd/","gloss":"recusado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"comment","pos":"verb","ipa":"/ˈkɑːmɛnt/","gloss":"comentar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"matter","pos":"noun","ipa":"/ˈmætər/","gloss":"questão, assunto"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-08', 'lesson-register-c1-05', 8, 'sentence', 'The firm intends to acquire a smaller rival.', 'A empresa pretende adquirir uma rival menor.', '/ðə fɜːrm ɪnˈtɛndz tuː əˈkwaɪər ə ˈsmɔːlər ˈraɪvəl/', '"Acquire" = adquirir.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"firm","pos":"adjective","ipa":"/fɜːrm/","gloss":"firme; empresa"},{"surface":"intends","pos":"verb","ipa":"/ɪnˈtɛndz/","gloss":"pretende"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"acquire","pos":"verb","ipa":"/əˈkwaɪər/","gloss":"adquirir"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"smaller","pos":"adjective","ipa":"/ˈsmɔːlər/","gloss":"menor"},{"surface":"rival","pos":"noun","ipa":"/ˈraɪvəl/","gloss":"rival"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-09', 'lesson-register-c1-05', 9, 'sentence', 'Applicants should ensure that all details are correct.', 'Os candidatos devem garantir que todos os dados estejam corretos.', '/ˈæplɪkənts ʃʊd ɪnˈʃʊr ðæt ɔːl ˈdiːteɪlz ɑːr kəˈrɛkt/', '"Ensure that" = garantir.', '[]'::jsonb, '[{"surface":"Applicants","pos":"noun","ipa":"/ˈæplɪkənts/","gloss":"candidatos"},{"surface":"should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"ensure","pos":"verb","ipa":"/ɪnˈʃʊr/","gloss":"garantir"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"details","pos":"noun","ipa":"/ˈdiːteɪlz/","gloss":"detalhes"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"correct","pos":"verb","ipa":"/kəˈrɛkt/","gloss":"corrigir"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-05-10', 'lesson-register-c1-05', 10, 'sentence', 'The proposal was subsequently withdrawn.', 'A proposta foi retirada em seguida.', '/ðə prəˈpoʊzəl wɑːz ˈsʌbsɪkwəntli wɪðˈdrɔːn/', '"Subsequently" = depois, em seguida.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"proposal","pos":"noun","ipa":"/prəˈpoʊzəl/","gloss":"proposta"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"subsequently","pos":"adverb","ipa":"/ˈsʌbsɪkwəntli/","gloss":"em seguida, depois"},{"surface":"withdrawn","pos":"verb","ipa":"/wɪðˈdrɔːn/","gloss":"retirada"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-register-c1-06', 'course-register-c1', 6, 'Linguagem de análise', 'Explicar causas, efeitos e relações.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-register-c1-06-01', 'lesson-register-c1-06', 1, 'sentence', 'The delay was largely due to poor planning.', 'O atraso foi em grande parte devido ao mau planejamento.', '/ðə dɪˈleɪ wɑːz ˈlɑːrdʒli duː tuː pʊr ˈplænɪŋ/', '"Largely due to" atribui a causa principal.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"delay","pos":"noun","ipa":"/dɪˈleɪ/","gloss":"atraso"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"largely","pos":"adverb","ipa":"/ˈlɑːrdʒli/","gloss":"em grande parte"},{"surface":"due","pos":"adjective","ipa":"/duː/","gloss":"devido (due to)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"poor","pos":"adjective","ipa":"/pʊr/","gloss":"pobre"},{"surface":"planning","pos":"verb","ipa":"/ˈplænɪŋ/","gloss":"planejando"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-02', 'lesson-register-c1-06', 2, 'sentence', 'Several factors account for this trend.', 'Vários fatores explicam esta tendência.', '/ˈsɛvrəl ˈfæktərz əˈkaʊnt fɔːr ðɪs trɛnd/', '"Account for" = explicar, responder por.', '[]'::jsonb, '[{"surface":"Several","pos":"determiner","ipa":"/ˈsɛvrəl/","gloss":"vários"},{"surface":"factors","pos":"noun","ipa":"/ˈfæktərz/","gloss":"fatores"},{"surface":"account","pos":"noun","ipa":"/əˈkaʊnt/","gloss":"conta (cadastro)"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"trend","pos":"noun","ipa":"/trɛnd/","gloss":"tendência"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-03', 'lesson-register-c1-06', 3, 'sentence', 'Poor sleep can give rise to serious health problems.', 'Dormir mal pode dar origem a graves problemas de saúde.', '/pʊr sliːp kæn ɡɪv raɪz tuː ˈsɪriəs hɛlθ ˈprɑːbləmz/', '"Give rise to" = causar, gerar.', '[]'::jsonb, '[{"surface":"Poor","pos":"adjective","ipa":"/pʊr/","gloss":"pobre"},{"surface":"sleep","pos":"verb","ipa":"/sliːp/","gloss":"dormir"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"give","pos":"verb","ipa":"/ɡɪv/","gloss":"dar"},{"surface":"rise","pos":"verb","ipa":"/raɪz/","gloss":"subir"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"serious","pos":"adjective","ipa":"/ˈsɪriəs/","gloss":"sério"},{"surface":"health","pos":"noun","ipa":"/hɛlθ/","gloss":"saúde"},{"surface":"problems","pos":"noun","ipa":"/ˈprɑːbləmz/","gloss":"problemas"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-04', 'lesson-register-c1-06', 4, 'sentence', 'The conflict stems from a long history of mistrust.', 'O conflito vem de uma longa história de desconfiança.', '/ðə ˈkɑːnflɪkt stɛmz frʌm ə lɔːŋ ˈhɪstəri ʌv mɪsˈtrʌst/', '"Stem from" = ter origem em.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"conflict","pos":"noun","ipa":"/ˈkɑːnflɪkt/","gloss":"conflito"},{"surface":"stems","pos":"verb","ipa":"/stɛmz/","gloss":"vem, tem origem"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"history","pos":"noun","ipa":"/ˈhɪstəri/","gloss":"história"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"mistrust","pos":"noun","ipa":"/mɪsˈtrʌst/","gloss":"desconfiança"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-05', 'lesson-register-c1-06', 5, 'sentence', 'This is closely linked to income levels.', 'Isto está muito ligado aos níveis de renda.', '/ðɪs ɪz ˈkloʊsli lɪŋkt tuː ˈɪnkʌm ˈlɛvəlz/', '"Linked to" = relacionado a.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"closely","pos":"adverb","ipa":"/ˈkloʊsli/","gloss":"de perto"},{"surface":"linked","pos":"adjective","ipa":"/lɪŋkt/","gloss":"ligado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"income","pos":"noun","ipa":"/ˈɪnkʌm/","gloss":"renda"},{"surface":"levels","pos":"noun","ipa":"/ˈlɛvəlz/","gloss":"níveis"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-06', 'lesson-register-c1-06', 6, 'sentence', 'The two variables are strongly correlated.', 'As duas variáveis estão fortemente correlacionadas.', '/ðə tuː ˈvɛriəbəlz ɑːr ˈstrɔːŋli ˈkɔːrəleɪtɪd/', '"Correlated" = relacionadas estatisticamente.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"variables","pos":"noun","ipa":"/ˈvɛriəbəlz/","gloss":"variáveis"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"strongly","pos":"adverb","ipa":"/ˈstrɔːŋli/","gloss":"firmemente"},{"surface":"correlated","pos":"adjective","ipa":"/ˈkɔːrəleɪtɪd/","gloss":"correlacionado"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-07', 'lesson-register-c1-06', 7, 'sentence', 'It is worth noting that the sample was small.', 'Vale notar que a amostra era pequena.', '/ɪt ɪz wɜːrθ ˈnoʊtɪŋ ðæt ðə ˈsæmpəl wɑːz smɔːl/', '"It is worth noting" chama atenção a um detalhe.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"worth","pos":"adjective","ipa":"/wɜːrθ/","gloss":"que vale a pena"},{"surface":"noting","pos":"verb","ipa":"/ˈnoʊtɪŋ/","gloss":"notando"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"sample","pos":"noun","ipa":"/ˈsæmpəl/","gloss":"amostra"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"small","pos":"adjective","ipa":"/smɔːl/","gloss":"pequeno"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-08', 'lesson-register-c1-06', 8, 'sentence', 'This has far-reaching implications for policy.', 'Isto tem implicações de longo alcance para a política.', '/ðɪs hæz ˌfɑːr ˈriːtʃɪŋ ˌɪmplɪˈkeɪʃənz fɔːr ˈpɑːləsi/', '"Far-reaching" = de grande alcance.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"far-reaching","pos":"adjective","ipa":"/ˌfɑːr ˈriːtʃɪŋ/","gloss":"de grande alcance"},{"surface":"implications","pos":"noun","ipa":"/ˌɪmplɪˈkeɪʃənz/","gloss":"implicações"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"policy","pos":"noun","ipa":"/ˈpɑːləsi/","gloss":"política, regra"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-09', 'lesson-register-c1-06', 9, 'sentence', 'The study sheds light on a long-standing question.', 'O estudo lança luz sobre uma questão antiga.', '/ðə ˈstʌdi ʃɛdz laɪt ɑːn ə ˌlɔːŋ ˈstændɪŋ ˈkwɛstʃən/', '"Shed light on" = esclarecer.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"study","pos":"verb","ipa":"/ˈstʌdi/","gloss":"estudar"},{"surface":"sheds","pos":"verb","ipa":"/ʃɛdz/","gloss":"lança (luz)"},{"surface":"light","pos":"adjective","ipa":"/laɪt/","gloss":"claro"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"long-standing","pos":"adjective","ipa":"/ˌlɔːŋ ˈstændɪŋ/","gloss":"antigo, de longa data"},{"surface":"question","pos":"noun","ipa":"/ˈkwɛstʃən/","gloss":"pergunta"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-06-10', 'lesson-register-c1-06', 10, 'sentence', 'This outcome is attributable to several causes.', 'Este resultado é atribuível a várias causas.', '/ðɪs ˈaʊtkʌm ɪz əˈtrɪbjətəbəl tuː ˈsɛvrəl ˈkɔːzɪz/', '"Attributable to" = atribuível a.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"outcome","pos":"noun","ipa":"/ˈaʊtkʌm/","gloss":"resultado"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"attributable","pos":"adjective","ipa":"/əˈtrɪbjətəbəl/","gloss":"atribuível"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"several","pos":"determiner","ipa":"/ˈsɛvrəl/","gloss":"vários"},{"surface":"causes","pos":"noun","ipa":"/ˈkɔːzɪz/","gloss":"causas"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-register-c1-07', 'course-register-c1', 7, 'Graduar a intensidade', 'Dizer mais, ou menos, com precisão.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-register-c1-07-01', 'lesson-register-c1-07', 1, 'sentence', 'The change was barely noticeable.', 'A mudança mal era perceptível.', '/ðə tʃeɪndʒ wɑːz ˈbɛrli ˈnoʊtɪsəbəl/', '"Barely" = quase nada.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"barely","pos":"adverb","ipa":"/ˈbɛrli/","gloss":"mal, quase não"},{"surface":"noticeable","pos":"adjective","ipa":"/ˈnoʊtɪsəbəl/","gloss":"perceptível"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-02', 'lesson-register-c1-07', 2, 'sentence', 'Her performance was nothing short of remarkable.', 'O desempenho dela foi simplesmente notável.', '/hɜːr pərˈfɔːrməns wɑːz ˈnʌθɪŋ ʃɔːrt ʌv rɪˈmɑːrkəbəl/', '"Nothing short of" intensifica o elogio.', '[]'::jsonb, '[{"surface":"Her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"performance","pos":"noun","ipa":"/pərˈfɔːrməns/","gloss":"desempenho"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"nothing","pos":"pronoun","ipa":"/ˈnʌθɪŋ/","gloss":"nada"},{"surface":"short","pos":"adjective","ipa":"/ʃɔːrt/","gloss":"curto"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"remarkable","pos":"adjective","ipa":"/rɪˈmɑːrkəbəl/","gloss":"notável"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-03', 'lesson-register-c1-07', 3, 'sentence', 'The two options are virtually identical.', 'As duas opções são praticamente idênticas.', '/ðə tuː ˈɑːpʃənz ɑːr ˈvɜːrtʃuəli aɪˈdɛntɪkəl/', '"Virtually" = quase totalmente.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"options","pos":"noun","ipa":"/ˈɑːpʃənz/","gloss":"opções"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"virtually","pos":"adverb","ipa":"/ˈvɜːrtʃuəli/","gloss":"praticamente"},{"surface":"identical","pos":"adjective","ipa":"/aɪˈdɛntɪkəl/","gloss":"idêntico"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-04', 'lesson-register-c1-07', 4, 'sentence', 'There was a marked improvement in results.', 'Houve uma melhora acentuada nos resultados.', '/ðɛr wɑːz ə mɑːrkt ɪmˈpruːvmənt ɪn rɪˈzʌlts/', '"Marked" = evidente.', '[]'::jsonb, '[{"surface":"There","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"marked","pos":"adjective","ipa":"/mɑːrkt/","gloss":"acentuado, evidente"},{"surface":"improvement","pos":"noun","ipa":"/ɪmˈpruːvmənt/","gloss":"melhora"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"results","pos":"noun","ipa":"/rɪˈzʌlts/","gloss":"resultados"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-05', 'lesson-register-c1-07', 5, 'sentence', 'It is somewhat more complicated than that.', 'É um pouco mais complicado que isso.', '/ɪt ɪz ˈsʌmwɑːt mɔːr ˈkɑːmplɪkeɪtɪd ðæn ðæt/', '"Somewhat" modera de forma sutil.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"somewhat","pos":"adverb","ipa":"/ˈsʌmwɑːt/","gloss":"um tanto, um pouco"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"complicated","pos":"adjective","ipa":"/ˈkɑːmplɪkeɪtɪd/","gloss":"complicado"},{"surface":"than","pos":"conjunction","ipa":"/ðæn/","gloss":"do que"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-06', 'lesson-register-c1-07', 6, 'sentence', 'The risk is considerable but manageable.', 'O risco é considerável, mas controlável.', '/ðə rɪsk ɪz kənˈsɪdərəbəl bʌt ˈmænɪdʒəbəl/', '"Considerable" = significativo.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"risk","pos":"noun","ipa":"/rɪsk/","gloss":"risco"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"considerable","pos":"adjective","ipa":"/kənˈsɪdərəbəl/","gloss":"considerável"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"manageable","pos":"adjective","ipa":"/ˈmænɪdʒəbəl/","gloss":"controlável"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-07', 'lesson-register-c1-07', 7, 'sentence', 'Such cases are exceedingly rare.', 'Casos assim são extremamente raros.', '/sʌtʃ ˈkeɪsɪz ɑːr ɪkˈsiːdɪŋli rɛr/', '"Exceedingly" = extremamente; formal.', '[]'::jsonb, '[{"surface":"Such","pos":"determiner","ipa":"/sʌtʃ/","gloss":"tal, tão"},{"surface":"cases","pos":"noun","ipa":"/ˈkeɪsɪz/","gloss":"casos"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"exceedingly","pos":"adverb","ipa":"/ɪkˈsiːdɪŋli/","gloss":"extremamente"},{"surface":"rare","pos":"adjective","ipa":"/rɛr/","gloss":"mal passado; raro"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-08', 'lesson-register-c1-07', 8, 'sentence', 'Their influence is by no means negligible.', 'A influência deles de modo algum é desprezível.', '/ðɛr ˈɪnfluəns ɪz baɪ noʊ miːnz ˈnɛɡlɪdʒəbəl/', '"By no means" = de modo algum.', '[]'::jsonb, '[{"surface":"Their","pos":"determiner","ipa":"/ðɛr/","gloss":"deles, delas"},{"surface":"influence","pos":"noun","ipa":"/ˈɪnfluəns/","gloss":"influência"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"no","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"means","pos":"verb","ipa":"/miːnz/","gloss":"significa"},{"surface":"negligible","pos":"adjective","ipa":"/ˈnɛɡlɪdʒəbəl/","gloss":"desprezível"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-09', 'lesson-register-c1-07', 9, 'sentence', 'That is a gross exaggeration.', 'Isso é um exagero grosseiro.', '/ðæt ɪz ə ɡroʊs ɪɡˌzædʒəˈreɪʃən/', '"Gross" = flagrante, evidente.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"gross","pos":"adjective","ipa":"/ɡroʊs/","gloss":"grosseiro, flagrante"},{"surface":"exaggeration","pos":"noun","ipa":"/ɪɡˌzædʒəˈreɪʃən/","gloss":"exagero"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-07-10', 'lesson-register-c1-07', 10, 'sentence', 'We are only marginally behind our rivals.', 'Estamos só marginalmente atrás dos nossos rivais.', '/wiː ɑːr ˈoʊnli ˈmɑːrdʒɪnəli bɪˈhaɪnd aʊər ˈraɪvəlz/', '"Marginally" = por uma pequena diferença.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"only","pos":"adverb","ipa":"/ˈoʊnli/","gloss":"só, apenas"},{"surface":"marginally","pos":"adverb","ipa":"/ˈmɑːrdʒɪnəli/","gloss":"marginalmente"},{"surface":"behind","pos":"preposition","ipa":"/bɪˈhaɪnd/","gloss":"atrás"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"rivals","pos":"noun","ipa":"/ˈraɪvəlz/","gloss":"rivais"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-register-c1-08', 'course-register-c1', 8, 'Fechar relatórios', 'Resumir, recomendar e encerrar.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-register-c1-08-01', 'lesson-register-c1-08', 1, 'sentence', 'In summary, the project met its main objectives.', 'Em resumo, o projeto cumpriu seus principais objetivos.', '/ɪn ˈsʌməri ðə ˈprɑːdʒɛkt mɛt ɪts meɪn əbˈdʒɛktɪvz/', '"In summary" abre a conclusão.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"summary","pos":"noun","ipa":"/ˈsʌməri/","gloss":"resumo"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"project","pos":"noun","ipa":"/ˈprɑːdʒɛkt/","gloss":"projeto"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"its","pos":"determiner","ipa":"/ɪts/","gloss":"seu, sua (de coisa)"},{"surface":"main","pos":"adjective","ipa":"/meɪn/","gloss":"principal"},{"surface":"objectives","pos":"noun","ipa":"/əbˈdʒɛktɪvz/","gloss":"objetivos"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-02', 'lesson-register-c1-08', 2, 'sentence', 'On balance, the benefits outweigh the costs.', 'No geral, os benefícios superam os custos.', '/ɑːn ˈbæləns ðə ˈbɛnəfɪts ˌaʊtˈweɪ ðə kɔːsts/', '"On balance" = ponderando tudo.', '[]'::jsonb, '[{"surface":"On","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"balance","pos":"noun","ipa":"/ˈbæləns/","gloss":"equilíbrio, saldo"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"benefits","pos":"noun","ipa":"/ˈbɛnəfɪts/","gloss":"benefícios"},{"surface":"outweigh","pos":"verb","ipa":"/ˌaʊtˈweɪ/","gloss":"pesar mais que"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-03', 'lesson-register-c1-08', 3, 'sentence', 'We recommend that the policy be reviewed annually.', 'Recomendamos que a política seja revisada anualmente.', '/wiː ˌrɛkəˈmɛnd ðæt ðə ˈpɑːləsi biː rɪˈvjuːd ˈænjuəli/', 'Subjuntivo formal: "be reviewed", sem "is".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"recommend","pos":"verb","ipa":"/ˌrɛkəˈmɛnd/","gloss":"recomendar"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"policy","pos":"noun","ipa":"/ˈpɑːləsi/","gloss":"política, regra"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"reviewed","pos":"verb","ipa":"/rɪˈvjuːd/","gloss":"revisada"},{"surface":"annually","pos":"adverb","ipa":"/ˈænjuəli/","gloss":"anualmente"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-04', 'lesson-register-c1-08', 4, 'sentence', 'The findings are discussed in more detail below.', 'Os resultados são discutidos em mais detalhe abaixo.', '/ðə ˈfaɪndɪŋz ɑːr dɪˈskʌst ɪn mɔːr ˈdiːteɪl bɪˈloʊ/', 'Indica a organização do texto.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"findings","pos":"noun","ipa":"/ˈfaɪndɪŋz/","gloss":"resultados, descobertas"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"discussed","pos":"verb","ipa":"/dɪˈskʌst/","gloss":"discutido, conversado"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"detail","pos":"noun","ipa":"/ˈdiːteɪl/","gloss":"detalhe"},{"surface":"below","pos":"preposition","ipa":"/bɪˈloʊ/","gloss":"abaixo de"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-05', 'lesson-register-c1-08', 5, 'sentence', 'A number of limitations should be acknowledged.', 'Algumas limitações devem ser reconhecidas.', '/ə ˈnʌmbər ʌv ˌlɪmɪˈteɪʃənz ʃʊd biː əkˈnɑːlɪdʒd/', '"Acknowledge" = reconhecer; formal.', '[]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"number","pos":"noun","ipa":"/ˈnʌmbər/","gloss":"número"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"limitations","pos":"noun","ipa":"/ˌlɪmɪˈteɪʃənz/","gloss":"limitações"},{"surface":"should","pos":"modal verb","ipa":"/ʃʊd/","gloss":"deveria"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"acknowledged","pos":"verb","ipa":"/əkˈnɑːlɪdʒd/","gloss":"reconhecidas"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-06', 'lesson-register-c1-08', 6, 'sentence', 'Overall, the evidence is encouraging.', 'No geral, as evidências são encorajadoras.', '/ˌoʊvərˈɔːl ðə ˈɛvɪdəns ɪz ɪnˈkɜːrɪdʒɪŋ/', '"Overall" resume o conjunto.', '[]'::jsonb, '[{"surface":"Overall","pos":"adverb","ipa":"/ˌoʊvərˈɔːl/","gloss":"no geral"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"evidence","pos":"noun","ipa":"/ˈɛvɪdəns/","gloss":"evidência"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"encouraging","pos":"adjective","ipa":"/ɪnˈkɜːrɪdʒɪŋ/","gloss":"encorajador"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-07', 'lesson-register-c1-08', 7, 'sentence', 'It is therefore advisable to proceed with caution.', 'É portanto aconselhável proceder com cautela.', '/ɪt ɪz ˈðɛrfɔːr ədˈvaɪzəbəl tuː prəˈsiːd wɪð ˈkɔːʃən/', '"Advisable" = recomendável.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"therefore","pos":"adverb","ipa":"/ˈðɛrfɔːr/","gloss":"portanto"},{"surface":"advisable","pos":"adjective","ipa":"/ədˈvaɪzəbəl/","gloss":"recomendável"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"proceed","pos":"verb","ipa":"/prəˈsiːd/","gloss":"prosseguir"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"caution","pos":"noun","ipa":"/ˈkɔːʃən/","gloss":"cautela"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-08', 'lesson-register-c1-08', 8, 'sentence', 'The next steps are outlined in the appendix.', 'Os próximos passos estão descritos no apêndice.', '/ðə nɛkst stɛps ɑːr ˈaʊtlaɪnd ɪn ðə əˈpɛndɪks/', '"Outlined" = descrito em linhas gerais.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"steps","pos":"noun","ipa":"/stɛps/","gloss":"passos"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"outlined","pos":"verb","ipa":"/ˈaʊtlaɪnd/","gloss":"descrito em linhas gerais"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"appendix","pos":"noun","ipa":"/əˈpɛndɪks/","gloss":"apêndice"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-09', 'lesson-register-c1-08', 9, 'sentence', 'We would welcome any comments on this draft.', 'Teremos prazer em receber comentários sobre este rascunho.', '/wiː wʊd ˈwɛlkəm ˈɛni ˈkɑːmɛnts ɑːn ðɪs dræft/', 'Fechamento cortês de documento.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"welcome","pos":"adjective","ipa":"/ˈwɛlkəm/","gloss":"bem-vindo"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"comments","pos":"noun","ipa":"/ˈkɑːmɛnts/","gloss":"comentários"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"draft","pos":"noun","ipa":"/dræft/","gloss":"rascunho"}]'::jsonb, NULL, NULL),
  ('unit-register-c1-08-10', 'lesson-register-c1-08', 10, 'sentence', 'This concludes our report.', 'Isto conclui o nosso relatório.', '/ðɪs kənˈkluːdz aʊər rɪˈpɔːrt/', 'Encerramento formal curto.', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"concludes","pos":"verb","ipa":"/kənˈkluːdz/","gloss":"conclui"},{"surface":"our","pos":"determiner","ipa":"/aʊər/","gloss":"nosso"},{"surface":"report","pos":"verb","ipa":"/rɪˈpɔːrt/","gloss":"registrar, relatar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
