-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-travel-a2', 'travel-no-stress-a2', 'Viagem sem Aperto', 'Aeroporto, hotel, transporte e restaurante: as frases que você realmente precisa na viagem.', 'Situações de viagem com o que você diz e o que ouve do outro lado: despachar mala, resolver problema no quarto, pegar metrô, reservar mesa, pedir, avisar de alergia e pagar a conta.', 'A2', 'travel', 2, 'viagem', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-04', 'course-travel-a2', 4, 'Restaurante: reserva e mesa', 'Reservar, chegar, esperar e escolher onde sentar.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-04-01', 'lesson-travel-a2-04', 1, 'sentence', 'I''d like to make a reservation for tonight.', 'Eu gostaria de fazer uma reserva para hoje à noite.', '/aɪd laɪk tuː meɪk ə ˌrɛzərˈveɪʃən fɔːr təˈnaɪt/', '"Make a reservation" = fazer reserva. "I''d like to" é o jeito educado de pedir.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"I''d like"},{"start":9,"end":30,"role":"direct_object","surface":"to make a reservation"},{"start":31,"end":43,"role":"adverbial","surface":"for tonight."}]'::jsonb, '[{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"reservation","pos":"noun","ipa":"/ˌrɛzərˈveɪʃən/","gloss":"reserva"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-02', 'lesson-travel-a2-04', 2, 'sentence', 'A table for two, please.', 'Uma mesa para dois, por favor.', '/ə ˈteɪbəl fɔːr tuː pliːz/', 'Forma curta e natural ao chegar sem reserva. "For" + número de pessoas.', '[{"start":0,"end":7,"role":"direct_object","surface":"A table"},{"start":8,"end":16,"role":"adverbial","surface":"for two,"},{"start":17,"end":24,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"A","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"table","pos":"noun","ipa":"/ˈteɪbəl/","gloss":"mesa"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-03', 'lesson-travel-a2-04', 3, 'sentence', 'Do you have a reservation?', 'Você tem reserva?', '/duː juː hæv ə ˌrɛzərˈveɪʃən/', 'Você vai ouvir isso na entrada. Responda "Yes, under Silva" (em nome de Silva) ou "No, we don''t".', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":6,"role":"subject","surface":"you"},{"start":7,"end":11,"role":"predicate_verb","surface":"have"},{"start":12,"end":26,"role":"direct_object","surface":"a reservation?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"reservation","pos":"noun","ipa":"/ˌrɛzərˈveɪʃən/","gloss":"reserva"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-04', 'lesson-travel-a2-04', 4, 'sentence', 'The reservation is under Silva.', 'A reserva está no nome de Silva.', '/ðə ˌrɛzərˈveɪʃən ɪz ˈʌndər ˈsɪlvə/', '"Under" + nome = em nome de. Não se diz "in the name of" no dia a dia.', '[{"start":0,"end":15,"role":"subject","surface":"The reservation"},{"start":16,"end":18,"role":"predicate_verb","surface":"is"},{"start":19,"end":31,"role":"adverbial","surface":"under Silva."}]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"reservation","pos":"noun","ipa":"/ˌrɛzərˈveɪʃən/","gloss":"reserva"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"under","pos":"preposition","ipa":"/ˈʌndər/","gloss":"no nome de, sob"},{"surface":"Silva","pos":"proper noun","ipa":"/ˈsɪlvə/","gloss":"Silva (sobrenome)"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-05', 'lesson-travel-a2-04', 5, 'sentence', 'How long is the wait?', 'Quanto tempo de espera?', '/haʊ lɔːŋ ɪz ðə weɪt/', '"Wait" aqui é substantivo: a espera. Resposta típica: "About twenty minutes".', '[{"start":0,"end":8,"role":"adverbial","surface":"How long"},{"start":9,"end":11,"role":"predicate_verb","surface":"is"},{"start":12,"end":21,"role":"subject","surface":"the wait?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-06', 'lesson-travel-a2-04', 6, 'sentence', 'It''s about a twenty minute wait.', 'A espera é de uns vinte minutos.', '/ɪts əˈbaʊt ə ˈtwɛnti ˈmɪnɪt weɪt/', 'Fala do recepcionista. "About" = mais ou menos. "Twenty minute" fica no singular porque funciona como adjetivo.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"It''s"},{"start":5,"end":32,"role":"predicate_adj","surface":"about a twenty minute wait."}]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"twenty","pos":"numeral","ipa":"/ˈtwɛnti/","gloss":"vinte"},{"surface":"minute","pos":"noun","ipa":"/ˈmɪnɪt/","gloss":"minuto"},{"surface":"wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-07', 'lesson-travel-a2-04', 7, 'sentence', 'Can we sit outside?', 'Podemos sentar lá fora?', '/kæn wiː sɪt ˌaʊtˈsaɪd/', '"Outside" = área externa; "inside" = dentro. "Can we" pede permissão.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":6,"role":"subject","surface":"we"},{"start":7,"end":10,"role":"predicate_verb","surface":"sit"},{"start":11,"end":19,"role":"adverbial","surface":"outside?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"sit","pos":"verb","ipa":"/sɪt/","gloss":"sentar"},{"surface":"outside","pos":"adverb","ipa":"/ˌaʊtˈsaɪd/","gloss":"lá fora"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-08', 'lesson-travel-a2-04', 8, 'sentence', 'Is this table free?', 'Esta mesa está livre?', '/ɪz ðɪs ˈteɪbəl friː/', '"Free" aqui é "desocupada", não "grátis". Também se diz "Is this table taken?".', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":13,"role":"subject","surface":"this table"},{"start":14,"end":19,"role":"predicate_adj","surface":"free?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"table","pos":"noun","ipa":"/ˈteɪbəl/","gloss":"mesa"},{"surface":"free","pos":"adjective","ipa":"/friː/","gloss":"livre, disponível"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-09', 'lesson-travel-a2-04', 9, 'sentence', 'Right this way, please.', 'Por aqui, por favor.', '/raɪt ðɪs weɪ pliːz/', 'O garçom diz isso ao levar você até a mesa. "Right" só reforça: "bem por aqui".', '[{"start":0,"end":15,"role":"adverbial","surface":"Right this way,"},{"start":16,"end":23,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"Right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-10', 'lesson-travel-a2-04', 10, 'sentence', 'We''re still waiting for one more person.', 'Ainda estamos esperando mais uma pessoa.', '/wɪr stɪl ˈweɪtɪŋ fɔːr wʌn mɔːr ˈpɜːrsən/', '"Still" = ainda. Presente contínuo (are waiting) para algo acontecendo agora.', '[{"start":0,"end":5,"role":"subject","surface":"We''re"},{"start":6,"end":11,"role":"adverbial","surface":"still"},{"start":12,"end":19,"role":"predicate_verb","surface":"waiting"},{"start":20,"end":40,"role":"direct_object","surface":"for one more person."}]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"still","pos":"adverb","ipa":"/stɪl/","gloss":"ainda"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"person","pos":"noun","ipa":"/ˈpɜːrsən/","gloss":"pessoa"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-11', 'lesson-travel-a2-04', 11, 'sentence', 'Could we have a high chair?', 'Poderia nos trazer uma cadeirinha de bebê?', '/kʊd wiː hæv ə haɪ tʃɛr/', '"High chair" = cadeira alta para bebê. "Could we have" é mais educado que "can we have".', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Could"},{"start":6,"end":8,"role":"subject","surface":"we"},{"start":9,"end":13,"role":"predicate_verb","surface":"have"},{"start":14,"end":27,"role":"direct_object","surface":"a high chair?"}]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"high","pos":"adjective","ipa":"/haɪ/","gloss":"alto"},{"surface":"chair","pos":"noun","ipa":"/tʃɛr/","gloss":"cadeira"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-04-12', 'lesson-travel-a2-04', 12, 'sentence', 'Sorry, we''re fully booked tonight.', 'Desculpe, estamos lotados hoje à noite.', '/ˈsɑːri wɪr ˈfʊli bʊkt təˈnaɪt/', '"Fully booked" = sem mesas/vagas para reserva. Vale também para hotel.', '[{"start":0,"end":6,"role":"discourse_marker","surface":"Sorry,"},{"start":7,"end":12,"role":"subject","surface":"we''re"},{"start":13,"end":25,"role":"predicate_adj","surface":"fully booked"},{"start":26,"end":34,"role":"adverbial","surface":"tonight."}]'::jsonb, '[{"surface":"Sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"we''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"fully","pos":"adverb","ipa":"/ˈfʊli/","gloss":"totalmente"},{"surface":"booked","pos":"adjective","ipa":"/bʊkt/","gloss":"reservado, lotado"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-05', 'course-travel-a2', 5, 'Restaurante: fazendo o pedido', 'Cardápio, perguntas ao garçom, pedido e ponto da carne.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-05-01', 'lesson-travel-a2-05', 1, 'sentence', 'Can I see the menu, please?', 'Posso ver o cardápio, por favor?', '/kæn aɪ siː ðə ˈmɛnjuː pliːz/', '"Menu" = cardápio. Em bares também se ouve "drinks menu" para a carta de bebidas.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"see"},{"start":10,"end":19,"role":"direct_object","surface":"the menu,"},{"start":20,"end":27,"role":"discourse_marker","surface":"please?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"menu","pos":"noun","ipa":"/ˈmɛnjuː/","gloss":"cardápio"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-02', 'lesson-travel-a2-05', 2, 'sentence', 'Are you ready to order?', 'Estão prontos para pedir?', '/ɑːr juː ˈrɛdi tuː ˈɔːrdər/', 'Pergunta do garçom. Se não estiver: "We need a few more minutes".', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Are"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":23,"role":"predicate_adj","surface":"ready to order?"}]'::jsonb, '[{"surface":"Are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"ready","pos":"adjective","ipa":"/ˈrɛdi/","gloss":"pronto"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"order","pos":"verb","ipa":"/ˈɔːrdər/","gloss":"pedir (comida)"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-03', 'lesson-travel-a2-05', 3, 'sentence', 'We need a few more minutes.', 'Precisamos de mais alguns minutos.', '/wiː niːd ə fjuː mɔːr ˈmɪnɪts/', '"A few" = alguns (contável). Resposta educada para ganhar tempo.', '[{"start":0,"end":2,"role":"subject","surface":"We"},{"start":3,"end":7,"role":"predicate_verb","surface":"need"},{"start":8,"end":27,"role":"direct_object","surface":"a few more minutes."}]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"few","pos":"determiner","ipa":"/fjuː/","gloss":"poucos"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"minutes","pos":"noun","ipa":"/ˈmɪnɪts/","gloss":"minutos"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-04', 'lesson-travel-a2-05', 4, 'sentence', 'What do you recommend?', 'O que você recomenda?', '/wʌt duː juː ˌrɛkəˈmɛnd/', 'Ótima pergunta para descobrir o prato da casa. "Recommend" tem um só "c" e dois "m".', '[{"start":0,"end":4,"role":"direct_object","surface":"What"},{"start":5,"end":7,"role":"predicate_verb","surface":"do"},{"start":8,"end":11,"role":"subject","surface":"you"},{"start":12,"end":22,"role":"predicate_verb","surface":"recommend?"}]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"recommend","pos":"verb","ipa":"/ˌrɛkəˈmɛnd/","gloss":"recomendar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-05', 'lesson-travel-a2-05', 5, 'sentence', 'I''ll have the chicken, please.', 'Vou querer o frango, por favor.', '/aɪl hæv ðə ˈtʃɪkən pliːz/', '"I''ll have" = vou querer. É o jeito mais comum de pedir; "I want" soa rude.', '[{"start":0,"end":9,"role":"predicate_verb","surface":"I''ll have"},{"start":10,"end":22,"role":"direct_object","surface":"the chicken,"},{"start":23,"end":30,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"chicken","pos":"noun","ipa":"/ˈtʃɪkən/","gloss":"frango"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-06', 'lesson-travel-a2-05', 6, 'sentence', 'How would you like your steak?', 'Como você quer o ponto da carne?', '/haʊ wʊd juː laɪk jʊr steɪk/', 'Fala do garçom. Respostas: "rare" (mal passado), "medium" (ao ponto), "well done" (bem passado).', '[{"start":0,"end":3,"role":"adverbial","surface":"How"},{"start":4,"end":9,"role":"predicate_verb","surface":"would"},{"start":10,"end":13,"role":"subject","surface":"you"},{"start":14,"end":18,"role":"predicate_verb","surface":"like"},{"start":19,"end":30,"role":"direct_object","surface":"your steak?"}]'::jsonb, '[{"surface":"How","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"steak","pos":"noun","ipa":"/steɪk/","gloss":"bife"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-07', 'lesson-travel-a2-05', 7, 'sentence', 'Medium rare, please.', 'Ao ponto para mal, por favor.', '/ˈmiːdiəm rɛr pliːz/', '"Medium rare" = rosado por dentro. A escala: rare, medium rare, medium, medium well, well done.', '[{"start":0,"end":12,"role":"predicate_adj","surface":"Medium rare,"},{"start":13,"end":20,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"Medium","pos":"adjective","ipa":"/ˈmiːdiəm/","gloss":"médio; ao ponto"},{"surface":"rare","pos":"adjective","ipa":"/rɛr/","gloss":"mal passado; raro"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-08', 'lesson-travel-a2-05', 8, 'sentence', 'Does it come with fries?', 'Vem com batata frita?', '/dʌz ɪt kʌm wɪð fraɪz/', '"Come with" = acompanha. "Fries" é o termo americano; no Reino Unido, "chips".', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Does"},{"start":5,"end":7,"role":"subject","surface":"it"},{"start":8,"end":17,"role":"predicate_verb","surface":"come with"},{"start":18,"end":24,"role":"direct_object","surface":"fries?"}]'::jsonb, '[{"surface":"Does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"come","pos":"verb","ipa":"/kʌm/","gloss":"vir; vindo"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"fries","pos":"noun","ipa":"/fraɪz/","gloss":"batata frita"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-09', 'lesson-travel-a2-05', 9, 'sentence', 'Can I get a salad instead?', 'Posso trocar por uma salada?', '/kæn aɪ ɡɛt ə ˈsæləd ɪnˈstɛd/', '"Instead" = em vez disso, no lugar. "Can I get" é pedido informal comum nos EUA.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"get"},{"start":10,"end":17,"role":"direct_object","surface":"a salad"},{"start":18,"end":26,"role":"adverbial","surface":"instead?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"salad","pos":"noun","ipa":"/ˈsæləd/","gloss":"salada"},{"surface":"instead","pos":"adverb","ipa":"/ɪnˈstɛd/","gloss":"em vez disso"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-10', 'lesson-travel-a2-05', 10, 'sentence', 'Anything to drink?', 'Algo para beber?', '/ˈɛniθɪŋ tuː drɪŋk/', 'Pergunta curta do garçom (forma reduzida de "Would you like anything to drink?").', '[{"start":0,"end":8,"role":"direct_object","surface":"Anything"},{"start":9,"end":18,"role":"predicate_verb","surface":"to drink?"}]'::jsonb, '[{"surface":"Anything","pos":"pronoun","ipa":"/ˈɛniθɪŋ/","gloss":"algo, alguma coisa"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"drink","pos":"verb","ipa":"/drɪŋk/","gloss":"beber"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-11', 'lesson-travel-a2-05', 11, 'sentence', 'Just water, please.', 'Só água, por favor.', '/dʒʌst ˈwɔːtər pliːz/', 'Em muitos lugares a água da torneira é grátis: "tap water". Garrafa: "bottled water".', '[{"start":0,"end":4,"role":"adverbial","surface":"Just"},{"start":5,"end":11,"role":"direct_object","surface":"water,"},{"start":12,"end":19,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"Just","pos":"adverb","ipa":"/dʒʌst/","gloss":"só, apenas"},{"surface":"water","pos":"noun","ipa":"/ˈwɔːtər/","gloss":"água"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-05-12', 'lesson-travel-a2-05', 12, 'sentence', 'That''s all for now, thanks.', 'É só isso por enquanto, obrigado.', '/ðæts ɔːl fɔːr naʊ θæŋks/', '"For now" = por enquanto: deixa claro que talvez peça mais depois.', '[{"start":0,"end":6,"role":"predicate_verb","surface":"That''s"},{"start":7,"end":10,"role":"predicate_adj","surface":"all"},{"start":11,"end":19,"role":"adverbial","surface":"for now,"},{"start":20,"end":27,"role":"discourse_marker","surface":"thanks."}]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"now","pos":"adverb","ipa":"/naʊ/","gloss":"agora"},{"surface":"thanks","pos":"interjection","ipa":"/θæŋks/","gloss":"obrigado, valeu"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-06', 'course-travel-a2', 6, 'Restaurante: alergias e problemas', 'Restrições alimentares, pedidos especiais e reclamar com educação.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-06-01', 'lesson-travel-a2-06', 1, 'sentence', 'I''m allergic to peanuts.', 'Eu tenho alergia a amendoim.', '/aɪm əˈlɜːrdʒɪk tuː ˈpiːnʌts/', '"Allergic to" + alimento. Diga isso antes de pedir; é informação de segurança.', '[{"start":0,"end":3,"role":"subject","surface":"I''m"},{"start":4,"end":12,"role":"predicate_adj","surface":"allergic"},{"start":13,"end":24,"role":"adverbial","surface":"to peanuts."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"allergic","pos":"adjective","ipa":"/əˈlɜːrdʒɪk/","gloss":"alérgico"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"peanuts","pos":"noun","ipa":"/ˈpiːnʌts/","gloss":"amendoins"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-02', 'lesson-travel-a2-06', 2, 'sentence', 'Does this have any nuts in it?', 'Isso tem alguma castanha?', '/dʌz ðɪs hæv ˈɛni nʌts ɪn ɪt/', '"Nuts" cobre castanhas, nozes e amêndoas. "Any" em perguntas = algum.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Does"},{"start":5,"end":9,"role":"subject","surface":"this"},{"start":10,"end":14,"role":"predicate_verb","surface":"have"},{"start":15,"end":23,"role":"direct_object","surface":"any nuts"},{"start":24,"end":30,"role":"adverbial","surface":"in it?"}]'::jsonb, '[{"surface":"Does","pos":"auxiliary verb","ipa":"/dʌz/","gloss":"auxiliar de pergunta (3ª pessoa)"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"any","pos":"determiner","ipa":"/ˈɛni/","gloss":"algum, alguma"},{"surface":"nuts","pos":"noun","ipa":"/nʌts/","gloss":"castanhas, nozes"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-03', 'lesson-travel-a2-06', 3, 'sentence', 'I''m a vegetarian.', 'Eu sou vegetariano.', '/aɪm ə ˌvɛdʒəˈtɛriən/', 'Profissões e grupos usam "a/an": "I''m a vegetarian", "I''m a vegan".', '[{"start":0,"end":3,"role":"subject","surface":"I''m"},{"start":4,"end":17,"role":"predicate_adj","surface":"a vegetarian."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"vegetarian","pos":"noun","ipa":"/ˌvɛdʒəˈtɛriən/","gloss":"vegetariano"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-04', 'lesson-travel-a2-06', 4, 'sentence', 'Is there a vegan option?', 'Tem opção vegana?', '/ɪz ðɛr ə ˈviːɡən ˈɑːpʃən/', '"Is there" = existe, tem. Vegan = sem nenhum produto animal.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"Is there"},{"start":9,"end":24,"role":"subject","surface":"a vegan option?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"vegan","pos":"adjective","ipa":"/ˈviːɡən/","gloss":"vegano"},{"surface":"option","pos":"noun","ipa":"/ˈɑːpʃən/","gloss":"opção"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-05', 'lesson-travel-a2-06', 5, 'sentence', 'Can you make it without cheese?', 'Dá para fazer sem queijo?', '/kæn juː meɪk ɪt wɪˈðaʊt tʃiːz/', '"Without" = sem. "Make it" se refere ao prato já mencionado.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":7,"role":"subject","surface":"you"},{"start":8,"end":12,"role":"predicate_verb","surface":"make"},{"start":13,"end":15,"role":"direct_object","surface":"it"},{"start":16,"end":31,"role":"adverbial","surface":"without cheese?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"without","pos":"preposition","ipa":"/wɪˈðaʊt/","gloss":"sem"},{"surface":"cheese","pos":"noun","ipa":"/tʃiːz/","gloss":"queijo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-06', 'lesson-travel-a2-06', 6, 'sentence', 'I can''t eat gluten.', 'Eu não posso comer glúten.', '/aɪ kænt iːt ˈɡluːtən/', '"Can''t" = não posso. Mais claro para restrição médica do que "I don''t eat".', '[{"start":0,"end":1,"role":"subject","surface":"I"},{"start":2,"end":11,"role":"predicate_verb","surface":"can''t eat"},{"start":12,"end":19,"role":"direct_object","surface":"gluten."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"can''t","pos":"auxiliary verb","ipa":"/kænt/","gloss":"não poder"},{"surface":"eat","pos":"verb","ipa":"/iːt/","gloss":"comer"},{"surface":"gluten","pos":"noun","ipa":"/ˈɡluːtən/","gloss":"glúten"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-07', 'lesson-travel-a2-06', 7, 'sentence', 'Excuse me, this isn''t what I ordered.', 'Com licença, isso não é o que eu pedi.', '/ɪkˈskjuːz miː ðɪs ˈɪzənt wʌt aɪ ˈɔːrdərd/', '"Excuse me" chama a atenção com educação. "Ordered" = passado de "order" (pedir comida).', '[{"start":0,"end":10,"role":"discourse_marker","surface":"Excuse me,"},{"start":11,"end":15,"role":"subject","surface":"this"},{"start":16,"end":21,"role":"predicate_verb","surface":"isn''t"},{"start":22,"end":37,"role":"predicate_adj","surface":"what I ordered."}]'::jsonb, '[{"surface":"Excuse","pos":"verb","ipa":"/ɪkˈskjuːz/","gloss":"desculpar (excuse me = com licença)"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"isn''t","pos":"auxiliary verb","ipa":"/ˈɪzənt/","gloss":"não é, não está"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"ordered","pos":"verb","ipa":"/ˈɔːrdərd/","gloss":"pediu, pedido"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-08', 'lesson-travel-a2-06', 8, 'sentence', 'My food is cold.', 'Minha comida está fria.', '/maɪ fuːd ɪz koʊld/', 'Reclamação direta e educada; complete com "Could you warm it up?" (pode esquentar?).', '[{"start":0,"end":7,"role":"subject","surface":"My food"},{"start":8,"end":10,"role":"predicate_verb","surface":"is"},{"start":11,"end":16,"role":"predicate_adj","surface":"cold."}]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"food","pos":"noun","ipa":"/fuːd/","gloss":"comida"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-09', 'lesson-travel-a2-06', 9, 'sentence', 'Could you warm it up, please?', 'Você poderia esquentar, por favor?', '/kʊd juː wɔːrm ɪt ʌp pliːz/', '"Warm up" é phrasal verb: esquentar. O objeto "it" vai no meio: "warm it up".', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Could"},{"start":6,"end":9,"role":"subject","surface":"you"},{"start":10,"end":14,"role":"predicate_verb","surface":"warm"},{"start":15,"end":17,"role":"direct_object","surface":"it"},{"start":18,"end":21,"role":"predicate_verb","surface":"up,"},{"start":22,"end":29,"role":"discourse_marker","surface":"please?"}]'::jsonb, '[{"surface":"Could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"warm","pos":"verb","ipa":"/wɔːrm/","gloss":"esquentar; morno"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"(partícula: up)"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-10', 'lesson-travel-a2-06', 10, 'sentence', 'We''ve been waiting for a long time.', 'Estamos esperando faz muito tempo.', '/wiːv bɪn ˈweɪtɪŋ fɔːr ə lɔːŋ taɪm/', 'Present perfect contínuo: começou no passado e continua agora. Tom de reclamação educada.', '[{"start":0,"end":18,"role":"predicate_verb","surface":"We''ve been waiting"},{"start":19,"end":35,"role":"adverbial","surface":"for a long time."}]'::jsonb, '[{"surface":"We''ve","pos":"pronoun","ipa":"/wiːv/","gloss":"nós temos (we have)"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-11', 'lesson-travel-a2-06', 11, 'sentence', 'I''m sorry about that.', 'Peço desculpas por isso.', '/aɪm ˈsɑːri əˈbaʊt ðæt/', 'Resposta típica do garçom. "Sorry about" + problema.', '[{"start":0,"end":3,"role":"subject","surface":"I''m"},{"start":4,"end":9,"role":"predicate_adj","surface":"sorry"},{"start":10,"end":21,"role":"adverbial","surface":"about that."}]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"sorry","pos":"adjective","ipa":"/ˈsɑːri/","gloss":"desculpa"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-06-12', 'lesson-travel-a2-06', 12, 'sentence', 'I''ll bring you a new one right away.', 'Vou trazer outro para você agora mesmo.', '/aɪl brɪŋ juː ə nuː wʌn raɪt əˈweɪ/', 'Fala do garçom. "Right away" = imediatamente. "A new one" evita repetir o nome do prato.', '[{"start":0,"end":10,"role":"predicate_verb","surface":"I''ll bring"},{"start":11,"end":14,"role":"indirect_object","surface":"you"},{"start":15,"end":24,"role":"direct_object","surface":"a new one"},{"start":25,"end":36,"role":"adverbial","surface":"right away."}]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"bring","pos":"verb","ipa":"/brɪŋ/","gloss":"trazer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"right","pos":"adverb","ipa":"/raɪt/","gloss":"bem; né? (right?)"},{"surface":"away","pos":"adverb","ipa":"/əˈweɪ/","gloss":"embora; (right away) já"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-travel-a2-07', 'course-travel-a2', 7, 'Restaurante: conta e gorjeta', 'Pedir a conta, dividir, pagar com cartão e deixar gorjeta.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-travel-a2-07-01', 'lesson-travel-a2-07', 1, 'sentence', 'Can we have the check, please?', 'Pode trazer a conta, por favor?', '/kæn wiː hæv ðə tʃɛk pliːz/', '"Check" (EUA) ou "bill" (Reino Unido) = conta. Nunca "account".', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":6,"role":"subject","surface":"we"},{"start":7,"end":11,"role":"predicate_verb","surface":"have"},{"start":12,"end":22,"role":"direct_object","surface":"the check,"},{"start":23,"end":30,"role":"discourse_marker","surface":"please?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"check","pos":"verb","ipa":"/tʃɛk/","gloss":"fazer (check-in)"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-02', 'lesson-travel-a2-07', 2, 'sentence', 'Is service included?', 'O serviço está incluído?', '/ɪz ˈsɜːrvɪs ɪnˈkluːdɪd/', 'Em muitos países a gorjeta não vem na conta. "Included" = incluído.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Is"},{"start":3,"end":10,"role":"subject","surface":"service"},{"start":11,"end":20,"role":"predicate_adj","surface":"included?"}]'::jsonb, '[{"surface":"Is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"service","pos":"noun","ipa":"/ˈsɜːrvɪs/","gloss":"serviço"},{"surface":"included","pos":"adjective","ipa":"/ɪnˈkluːdɪd/","gloss":"incluído"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-03', 'lesson-travel-a2-07', 3, 'sentence', 'Can we split the bill?', 'Podemos dividir a conta?', '/kæn wiː splɪt ðə bɪl/', '"Split" = dividir. "Split it evenly" = dividir igualmente.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":6,"role":"subject","surface":"we"},{"start":7,"end":12,"role":"predicate_verb","surface":"split"},{"start":13,"end":22,"role":"direct_object","surface":"the bill?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"split","pos":"verb","ipa":"/splɪt/","gloss":"dividir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bill","pos":"noun","ipa":"/bɪl/","gloss":"conta"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-04', 'lesson-travel-a2-07', 4, 'sentence', 'Separate checks, please.', 'Contas separadas, por favor.', '/ˈsɛpərət tʃɛks pliːz/', 'Cada pessoa paga a sua parte. Diga isso antes de a conta chegar.', '[{"start":0,"end":16,"role":"direct_object","surface":"Separate checks,"},{"start":17,"end":24,"role":"discourse_marker","surface":"please."}]'::jsonb, '[{"surface":"Separate","pos":"adjective","ipa":"/ˈsɛpərət/","gloss":"separado"},{"surface":"checks","pos":"noun","ipa":"/tʃɛks/","gloss":"contas (EUA)"},{"surface":"please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-05', 'lesson-travel-a2-07', 5, 'sentence', 'Do you take credit cards?', 'Vocês aceitam cartão de crédito?', '/duː juː teɪk ˈkrɛdɪt kɑːrdz/', '"Take" = aceitar (forma de pagamento). "Cash only" = só dinheiro.', '[{"start":0,"end":2,"role":"predicate_verb","surface":"Do"},{"start":3,"end":6,"role":"subject","surface":"you"},{"start":7,"end":11,"role":"predicate_verb","surface":"take"},{"start":12,"end":25,"role":"direct_object","surface":"credit cards?"}]'::jsonb, '[{"surface":"Do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"credit","pos":"noun","ipa":"/ˈkrɛdɪt/","gloss":"crédito"},{"surface":"cards","pos":"noun","ipa":"/kɑːrdz/","gloss":"cartões"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-06', 'lesson-travel-a2-07', 6, 'sentence', 'I''ll pay by card.', 'Vou pagar no cartão.', '/aɪl peɪ baɪ kɑːrd/', '"By card" / "in cash" = no cartão / em dinheiro. Repare: by card, mas in cash.', '[{"start":0,"end":8,"role":"predicate_verb","surface":"I''ll pay"},{"start":9,"end":17,"role":"adverbial","surface":"by card."}]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"pay","pos":"verb","ipa":"/peɪ/","gloss":"pagar"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"card","pos":"noun","ipa":"/kɑːrd/","gloss":"cartão"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-07', 'lesson-travel-a2-07', 7, 'sentence', 'Would you like to add a tip?', 'Gostaria de adicionar gorjeta?', '/wʊd juː laɪk tuː æd ə tɪp/', 'Aparece na maquininha ou é dito pelo garçom. "Tip" = gorjeta.', '[{"start":0,"end":5,"role":"predicate_verb","surface":"Would"},{"start":6,"end":9,"role":"subject","surface":"you"},{"start":10,"end":14,"role":"predicate_verb","surface":"like"},{"start":15,"end":28,"role":"direct_object","surface":"to add a tip?"}]'::jsonb, '[{"surface":"Would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"add","pos":"verb","ipa":"/æd/","gloss":"acrescentar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"tip","pos":"noun","ipa":"/tɪp/","gloss":"gorjeta"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-08', 'lesson-travel-a2-07', 8, 'sentence', 'Keep the change.', 'Pode ficar com o troco.', '/kiːp ðə tʃeɪndʒ/', 'Forma simples de deixar gorjeta pagando em dinheiro. "Change" = troco.', '[{"start":0,"end":4,"role":"predicate_verb","surface":"Keep"},{"start":5,"end":16,"role":"direct_object","surface":"the change."}]'::jsonb, '[{"surface":"Keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-09', 'lesson-travel-a2-07', 9, 'sentence', 'I think there is a mistake on the bill.', 'Acho que tem um erro na conta.', '/aɪ θɪŋk ðɛr ɪz ə mɪˈsteɪk ɑːn ðə bɪl/', '"I think" suaviza a reclamação. "On the bill" = na conta (preposição "on").', '[{"start":0,"end":7,"role":"discourse_marker","surface":"I think"},{"start":8,"end":16,"role":"predicate_verb","surface":"there is"},{"start":17,"end":26,"role":"subject","surface":"a mistake"},{"start":27,"end":39,"role":"adverbial","surface":"on the bill."}]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"mistake","pos":"noun","ipa":"/mɪˈsteɪk/","gloss":"erro"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bill","pos":"noun","ipa":"/bɪl/","gloss":"conta"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-10', 'lesson-travel-a2-07', 10, 'sentence', 'We didn''t order this.', 'Nós não pedimos isso.', '/wiː ˈdɪdənt ˈɔːrdər ðɪs/', 'Passado negativo: "didn''t" + verbo na forma base (order, não ordered).', '[{"start":0,"end":2,"role":"subject","surface":"We"},{"start":3,"end":15,"role":"predicate_verb","surface":"didn''t order"},{"start":16,"end":21,"role":"direct_object","surface":"this."}]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"didn''t","pos":"auxiliary verb","ipa":"/ˈdɪdənt/","gloss":"não (passado)"},{"surface":"order","pos":"verb","ipa":"/ˈɔːrdər/","gloss":"pedir (comida)"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-11', 'lesson-travel-a2-07', 11, 'sentence', 'Can I get this to go?', 'Pode embalar para viagem?', '/kæn aɪ ɡɛt ðɪs tuː ɡoʊ/', '"To go" (EUA) = para levar; no Reino Unido, "to take away". Serve para sobras também.', '[{"start":0,"end":3,"role":"predicate_verb","surface":"Can"},{"start":4,"end":5,"role":"subject","surface":"I"},{"start":6,"end":9,"role":"predicate_verb","surface":"get"},{"start":10,"end":14,"role":"direct_object","surface":"this"},{"start":15,"end":21,"role":"adverbial","surface":"to go?"}]'::jsonb, '[{"surface":"Can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"}]'::jsonb, NULL, NULL),
  ('unit-travel-a2-07-12', 'lesson-travel-a2-07', 12, 'sentence', 'Everything was delicious, thank you.', 'Estava tudo delicioso, obrigado.', '/ˈɛvriθɪŋ wɑːz dɪˈlɪʃəs θæŋk juː/', 'Elogio ao sair. "Everything" pede verbo no singular: "everything was".', '[{"start":0,"end":10,"role":"subject","surface":"Everything"},{"start":11,"end":14,"role":"predicate_verb","surface":"was"},{"start":15,"end":25,"role":"predicate_adj","surface":"delicious,"},{"start":26,"end":36,"role":"discourse_marker","surface":"thank you."}]'::jsonb, '[{"surface":"Everything","pos":"pronoun","ipa":"/ˈɛvriθɪŋ/","gloss":"tudo"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"delicious","pos":"adjective","ipa":"/dɪˈlɪʃəs/","gloss":"delicioso"},{"surface":"thank","pos":"verb","ipa":"/θæŋk/","gloss":"agradecer"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
