-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-essential-verbs-a1', 'essential-verbs', 'Verbos Essenciais', 'Os verbos mais usados em frases separadas por tempo: presente, passado, futuro e present perfect.', 'Cada verbo aparece em quatro frases reais, uma por tempo verbal, com a explicação gramatical de cada forma. No fim, você revisa as três formas (base, passado e particípio).', 'A1', 'grammar', 12, 'fundamentos', 3, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

DELETE FROM public.course_units WHERE id IN ('unit-essential-verbs-a1-01-09', 'unit-essential-verbs-a1-01-10');

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-01', 'course-essential-verbs-a1', 1, 'be e have', 'Ser/estar e ter nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-01-01', 'lesson-essential-verbs-a1-01', 1, 'sentence', 'I am a teacher.', 'Eu sou professor.', '/aɪ æm ə ˈtiːtʃər/', 'Presente de "be": I am, you/we/they are, he/she/it is. O mesmo verbo serve para "ser" e "estar".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"am","pos":"auxiliary verb","ipa":"/æm/","gloss":"sou, estou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"teacher","pos":"noun","ipa":"/ˈtiːtʃər/","gloss":"professor, professora"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-01-02', 'lesson-essential-verbs-a1-01', 2, 'sentence', 'I was at home yesterday.', 'Eu estava em casa ontem.', '/aɪ wʌz æt hoʊm ˈjɛstərdeɪ/', 'Passado de "be": "was" (I/he/she/it) e "were" (you/we/they). "Yesterday" pede o passado simples.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wʌz/","gloss":"era, estava"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-01-03', 'lesson-essential-verbs-a1-01', 3, 'sentence', 'I will be there tomorrow.', 'Eu vou estar lá amanhã.', '/aɪ wɪl biː ðɛr təˈmɑːroʊ/', 'Futuro com "will" + verbo na forma base: "will be". "Will" não muda com a pessoa.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"tomorrow","pos":"adverb","ipa":"/təˈmɑːroʊ/","gloss":"amanhã"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-01-04', 'lesson-essential-verbs-a1-01', 4, 'sentence', 'I have been here before.', 'Eu já estive aqui antes.', '/aɪ hæv bɪn hɪr bɪˈfɔːr/', 'Present perfect: have/has + particípio ("been"). Fala de experiência sem data definida.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"before","pos":"adverb","ipa":"/bɪˈfɔːr/","gloss":"antes"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-01-05', 'lesson-essential-verbs-a1-01', 5, 'sentence', 'We have two cats.', 'Nós temos dois gatos.', '/wiː hæv tuː kæts/', 'Presente de "have": "have" (I/you/we/they) e "has" (he/she/it).', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"cats","pos":"noun","ipa":"/kæts/","gloss":"gatos"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-01-06', 'lesson-essential-verbs-a1-01', 6, 'sentence', 'She had a cold last week.', 'Ela teve um resfriado semana passada.', '/ʃiː hæd ə koʊld læst wiːk/', 'Passado de "have": "had", igual para todas as pessoas. "Last week" marca o passado.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"},{"surface":"last","pos":"adjective","ipa":"/læst/","gloss":"passado, último"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-01-07', 'lesson-essential-verbs-a1-01', 7, 'sentence', 'They will have a meeting at ten.', 'Eles vão ter uma reunião às dez.', '/ðeɪ wɪl hæv ə ˈmiːtɪŋ æt tɛn/', 'Futuro: "will have". Depois de "will" o verbo nunca leva -s: "she will have", não "will has".', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-01-08', 'lesson-essential-verbs-a1-01', 8, 'sentence', 'I have had this car for years.', 'Eu tenho este carro há anos.', '/aɪ hæv hæd ðɪs kɑːr fɔːr jɪrz/', 'Present perfect de "have": "have had". Com "for" + período, algo que começou no passado e continua até hoje.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-02', 'course-essential-verbs-a1', 2, 'do e say', 'Fazer (tarefas) e dizer nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-02-01', 'lesson-essential-verbs-a1-02', 1, 'sentence', 'I do my homework at night.', 'Eu faço minha lição à noite.', '/aɪ duː maɪ ˈhoʊmwɜːrk æt naɪt/', 'Presente de "do" (fazer tarefas e atividades). Com he/she/it: "does".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"homework","pos":"noun","ipa":"/ˈhoʊmwɜːrk/","gloss":"lição de casa"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-02-02', 'lesson-essential-verbs-a1-02', 2, 'sentence', 'He did the dishes after dinner.', 'Ele lavou a louça depois do jantar.', '/hiː dɪd ðə ˈdɪʃɪz ˈæftər ˈdɪnər/', 'Passado de "do": "did", igual para todas as pessoas. "Do the dishes" é expressão fixa: lavar a louça.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"dishes","pos":"noun","ipa":"/ˈdɪʃɪz/","gloss":"louça, pratos"},{"surface":"after","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"dinner","pos":"noun","ipa":"/ˈdɪnər/","gloss":"jantar"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-02-03', 'lesson-essential-verbs-a1-02', 3, 'sentence', 'I will do it later.', 'Eu vou fazer isso depois.', '/aɪ wɪl duː ɪt ˈleɪtər/', 'Futuro: "will do". "It" retoma algo que já foi mencionado.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"later","pos":"adverb","ipa":"/ˈleɪtər/","gloss":"depois, mais tarde"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-02-04', 'lesson-essential-verbs-a1-02', 4, 'sentence', 'We have done everything.', 'Nós já fizemos tudo.', '/wiː hæv dʌn ˈɛvriθɪŋ/', 'Present perfect: have + "done". "Done" é o particípio irregular de "do".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"done","pos":"verb","ipa":"/dʌn/","gloss":"feito (particípio de do)"},{"surface":"everything","pos":"pronoun","ipa":"/ˈɛvriθɪŋ/","gloss":"tudo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-02-05', 'lesson-essential-verbs-a1-02', 5, 'sentence', 'They always say hello.', 'Eles sempre dizem olá.', '/ðeɪ ˈɔːlweɪz seɪ həˈloʊ/', 'Presente de "say" (dizer). Advérbios de frequência como "always" vêm antes do verbo principal.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"always","pos":"adverb","ipa":"/ˈɔːlweɪz/","gloss":"sempre"},{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"},{"surface":"hello","pos":"interjection","ipa":"/həˈloʊ/","gloss":"olá"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-02-06', 'lesson-essential-verbs-a1-02', 6, 'sentence', 'She said no.', 'Ela disse não.', '/ʃiː sɛd noʊ/', 'Passado de "say": "said", pronunciado /sɛd/ (não "seid").', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"},{"surface":"no","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-02-07', 'lesson-essential-verbs-a1-02', 7, 'sentence', 'What will you say to him?', 'O que você vai dizer para ele?', '/wʌt wɪl juː seɪ tuː hɪm/', 'Futuro em pergunta: "will" vem antes do sujeito ("will you say").', '[]'::jsonb, '[{"surface":"What","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-02-08', 'lesson-essential-verbs-a1-02', 8, 'sentence', 'I have said it many times.', 'Eu já disse isso muitas vezes.', '/aɪ hæv sɛd ɪt ˈmɛni taɪmz/', 'Present perfect: "have said". "Many times" indica repetição sem data exata.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"many","pos":"determiner","ipa":"/ˈmɛni/","gloss":"muitos"},{"surface":"times","pos":"noun","ipa":"/taɪmz/","gloss":"vezes"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-03', 'course-essential-verbs-a1', 3, 'go e get', 'Ir e conseguir/ficar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-03-01', 'lesson-essential-verbs-a1-03', 1, 'sentence', 'I go to work by bus.', 'Eu vou para o trabalho de ônibus.', '/aɪ ɡoʊ tuː wɜːrk baɪ bʌs/', 'Presente de "go". Meio de transporte usa "by": by bus, by car. Com he/she/it: "goes".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"},{"surface":"by","pos":"preposition","ipa":"/baɪ/","gloss":"de (meio), por"},{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-03-02', 'lesson-essential-verbs-a1-03', 2, 'sentence', 'We went to the beach on Sunday.', 'Nós fomos à praia no domingo.', '/wiː wɛnt tuː ðə biːtʃ ɑːn ˈsʌndeɪ/', 'Passado irregular de "go": "went". Dias da semana usam "on".', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"beach","pos":"noun","ipa":"/biːtʃ/","gloss":"praia"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"Sunday","pos":"proper noun","ipa":"/ˈsʌndeɪ/","gloss":"domingo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-03-03', 'lesson-essential-verbs-a1-03', 3, 'sentence', 'I will go to bed early tonight.', 'Vou dormir cedo hoje à noite.', '/aɪ wɪl ɡoʊ tuː bɛd ˈɜːrli təˈnaɪt/', 'Futuro: "will go". "Go to bed" = ir dormir.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"bed","pos":"noun","ipa":"/bɛd/","gloss":"cama"},{"surface":"early","pos":"adverb","ipa":"/ˈɜːrli/","gloss":"cedo"},{"surface":"tonight","pos":"adverb","ipa":"/təˈnaɪt/","gloss":"hoje à noite"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-03-04', 'lesson-essential-verbs-a1-03', 4, 'sentence', 'She has gone to the store.', 'Ela foi ao mercado (e ainda não voltou).', '/ʃiː hæz ɡɔːn tuː ðə stɔːr/', '"Has gone": a pessoa foi e ainda está lá. Compare com "has been": foi e já voltou.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"gone","pos":"verb","ipa":"/ɡɔːn/","gloss":"ido (particípio de go)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"store","pos":"noun","ipa":"/stɔːr/","gloss":"loja, mercado"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-03-05', 'lesson-essential-verbs-a1-03', 5, 'sentence', 'I get up at seven.', 'Eu me levanto às sete.', '/aɪ ɡɛt ʌp æt ˈsɛvən/', '"Get up" é um phrasal verb: levantar-se da cama. "Get" muda de sentido com a partícula.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"up","pos":"particle","ipa":"/ʌp/","gloss":"para cima (partícula)"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"seven","pos":"numeral","ipa":"/ˈsɛvən/","gloss":"sete"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-03-06', 'lesson-essential-verbs-a1-03', 6, 'sentence', 'He got a new phone.', 'Ele ganhou um celular novo.', '/hiː ɡɑːt ə nuː foʊn/', 'Passado de "get": "got". "Get" + objeto = conseguir, receber, ganhar.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"phone","pos":"noun","ipa":"/foʊn/","gloss":"celular, telefone"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-03-07', 'lesson-essential-verbs-a1-03', 7, 'sentence', 'It will get cold at night.', 'Vai esfriar à noite.', '/ɪt wɪl ɡɛt koʊld æt naɪt/', '"Get" + adjetivo = ficar: get cold, get tired. Futuro com "will".', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-03-08', 'lesson-essential-verbs-a1-03', 8, 'sentence', 'Have you gotten my message?', 'Você recebeu minha mensagem?', '/hæv juː ˈɡɑːtən maɪ ˈmɛsɪdʒ/', 'Particípio americano: "gotten" (no britânico, "got"). Na pergunta do present perfect, "have" vem antes do sujeito.', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"gotten","pos":"verb","ipa":"/ˈɡɑːtən/","gloss":"conseguido, recebido"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"message","pos":"noun","ipa":"/ˈmɛsɪdʒ/","gloss":"mensagem"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-04', 'course-essential-verbs-a1', 4, 'make e know', 'Fazer (criar) e saber/conhecer nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-04-01', 'lesson-essential-verbs-a1-04', 1, 'sentence', 'My mother makes great coffee.', 'Minha mãe faz um café ótimo.', '/maɪ ˈmʌðər meɪks ɡreɪt ˈkɔːfi/', '"Make" = fazer no sentido de criar ou produzir; "do" = realizar tarefas. Com he/she/it: "makes".', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"mother","pos":"noun","ipa":"/ˈmʌðər/","gloss":"mãe"},{"surface":"makes","pos":"verb","ipa":"/meɪks/","gloss":"faz (he/she/it)"},{"surface":"great","pos":"adjective","ipa":"/ɡreɪt/","gloss":"ótimo"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-04-02', 'lesson-essential-verbs-a1-04', 2, 'sentence', 'I made a mistake.', 'Eu cometi um erro.', '/aɪ meɪd ə mɪˈsteɪk/', 'Passado de "make": "made". Diz-se "make a mistake", nunca "do a mistake".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"mistake","pos":"noun","ipa":"/mɪˈsteɪk/","gloss":"erro"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-04-03', 'lesson-essential-verbs-a1-04', 3, 'sentence', 'We will make dinner together.', 'Nós vamos fazer o jantar juntos.', '/wiː wɪl meɪk ˈdɪnər təˈɡɛðər/', 'Futuro: "will make". Refeições usam "make": make dinner, make lunch.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"dinner","pos":"noun","ipa":"/ˈdɪnər/","gloss":"jantar"},{"surface":"together","pos":"adverb","ipa":"/təˈɡɛðər/","gloss":"juntos"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-04-04', 'lesson-essential-verbs-a1-04', 4, 'sentence', 'They have made a decision.', 'Eles tomaram uma decisão.', '/ðeɪ hæv meɪd ə dɪˈsɪʒən/', 'Present perfect: "have made". "Make a decision" = tomar uma decisão.', '[]'::jsonb, '[{"surface":"They","pos":"pronoun","ipa":"/ðeɪ/","gloss":"eles, elas"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"decision","pos":"noun","ipa":"/dɪˈsɪʒən/","gloss":"decisão"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-04-05', 'lesson-essential-verbs-a1-04', 5, 'sentence', 'I know her sister.', 'Eu conheço a irmã dela.', '/aɪ noʊ hɜːr ˈsɪstər/', '"Know" = saber ou conhecer. O "k" é mudo: /noʊ/.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"sister","pos":"noun","ipa":"/ˈsɪstər/","gloss":"irmã"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-04-06', 'lesson-essential-verbs-a1-04', 6, 'sentence', 'I knew the answer.', 'Eu sabia a resposta.', '/aɪ nuː ðə ˈænsər/', 'Passado irregular de "know": "knew", com o mesmo som de "new".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"knew","pos":"verb","ipa":"/nuː/","gloss":"sabia, conheceu"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"answer","pos":"noun","ipa":"/ˈænsər/","gloss":"resposta"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-04-07', 'lesson-essential-verbs-a1-04', 7, 'sentence', 'You will know when you see it.', 'Você vai saber quando vir.', '/juː wɪl noʊ wɛn juː siː ɪt/', 'Futuro: "will know". Depois de "when", o inglês usa o presente ("see") mesmo falando do futuro.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-04-08', 'lesson-essential-verbs-a1-04', 8, 'sentence', 'I have known him for ten years.', 'Eu o conheço há dez anos.', '/aɪ hæv noʊn hɪm fɔːr tɛn jɪrz/', 'Present perfect + "for": conhecer desde o passado até hoje. Em português usamos presente + "há".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"known","pos":"verb","ipa":"/noʊn/","gloss":"sabido, conhecido"},{"surface":"him","pos":"pronoun","ipa":"/hɪm/","gloss":"ele, o, lhe"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"years","pos":"noun","ipa":"/jɪrz/","gloss":"anos"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-05', 'course-essential-verbs-a1', 5, 'think e take', 'Pensar/achar e pegar/levar nos quatro tempos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-05-01', 'lesson-essential-verbs-a1-05', 1, 'sentence', 'I think you''re right.', 'Eu acho que você está certo.', '/aɪ θɪŋk jʊr raɪt/', '"Think" = achar, pensar. O "that" é opcional: "I think (that) you''re right".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"you''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"right","pos":"adjective","ipa":"/raɪt/","gloss":"certo"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-05-02', 'lesson-essential-verbs-a1-05', 2, 'sentence', 'I thought about you yesterday.', 'Pensei em você ontem.', '/aɪ θɔːt əˈbaʊt juː ˈjɛstərdeɪ/', 'Passado de "think": "thought" /θɔːt/. "Think about" = pensar em.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"thought","pos":"verb","ipa":"/θɔːt/","gloss":"pensou, pensado"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre, em"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-05-03', 'lesson-essential-verbs-a1-05', 3, 'sentence', 'I will think about it.', 'Vou pensar no assunto.', '/aɪ wɪl θɪŋk əˈbaʊt ɪt/', 'Futuro: "will think". Frase comum para adiar uma decisão com educação.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre, em"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-05-04', 'lesson-essential-verbs-a1-05', 4, 'sentence', 'Have you thought about the trip?', 'Você já pensou na viagem?', '/hæv juː θɔːt əˈbaʊt ðə trɪp/', 'Present perfect: have + "thought" (o particípio é igual ao passado).', '[]'::jsonb, '[{"surface":"Have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"thought","pos":"verb","ipa":"/θɔːt/","gloss":"pensou, pensado"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre, em"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"trip","pos":"noun","ipa":"/trɪp/","gloss":"viagem"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-05-05', 'lesson-essential-verbs-a1-05', 5, 'sentence', 'I take a shower every morning.', 'Eu tomo banho toda manhã.', '/aɪ teɪk ə ˈʃaʊər ˈɛvri ˈmɔːrnɪŋ/', '"Take a shower" = tomar banho. "Every" + período indica hábito e pede o presente simples.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"shower","pos":"noun","ipa":"/ˈʃaʊər/","gloss":"banho de chuveiro"},{"surface":"every","pos":"determiner","ipa":"/ˈɛvri/","gloss":"todo, cada"},{"surface":"morning","pos":"noun","ipa":"/ˈmɔːrnɪŋ/","gloss":"manhã"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-05-06', 'lesson-essential-verbs-a1-05', 6, 'sentence', 'He took the wrong train.', 'Ele pegou o trem errado.', '/hiː tʊk ðə rɔːŋ treɪn/', 'Passado de "take": "took". "Take" = pegar (transporte), levar.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"took","pos":"verb","ipa":"/tʊk/","gloss":"pegou, levou"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"wrong","pos":"adjective","ipa":"/rɔːŋ/","gloss":"errado"},{"surface":"train","pos":"noun","ipa":"/treɪn/","gloss":"trem"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-05-07', 'lesson-essential-verbs-a1-05', 7, 'sentence', 'It will take two hours.', 'Vai levar duas horas.', '/ɪt wɪl teɪk tuː aʊərz/', '"Take" + tempo = demorar, levar. Futuro com "will".', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"two","pos":"numeral","ipa":"/tuː/","gloss":"dois"},{"surface":"hours","pos":"noun","ipa":"/aʊərz/","gloss":"horas"}]'::jsonb, NULL, NULL),
  ('unit-essential-verbs-a1-05-08', 'lesson-essential-verbs-a1-05', 8, 'sentence', 'Someone has taken my pen.', 'Alguém pegou minha caneta.', '/ˈsʌmwʌn hæz ˈteɪkən maɪ pɛn/', 'Present perfect: "has taken". Mostra o resultado agora: a caneta não está aqui.', '[]'::jsonb, '[{"surface":"Someone","pos":"pronoun","ipa":"/ˈsʌmwʌn/","gloss":"alguém"},{"surface":"has","pos":"verb","ipa":"/hæz/","gloss":"tem (he/she/it)"},{"surface":"taken","pos":"verb","ipa":"/ˈteɪkən/","gloss":"pegado, levado"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"pen","pos":"noun","ipa":"/pɛn/","gloss":"caneta"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-essential-verbs-a1-06', 'course-essential-verbs-a1', 6, 'Revisão: as três formas', 'Base, passado e particípio dos 10 verbos do módulo.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-essential-verbs-a1-06-01', 'lesson-essential-verbs-a1-06', 1, 'verb_forms', 'be was been', 'ser, estar', '/biː wʌz bɪn/', 'Base "be" · passado "was/were" · particípio "been". Irregular: o passado muda com a pessoa.', '[]'::jsonb, '[{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"was","pos":"verb","ipa":"/wʌz/","gloss":"era, estava"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"}]'::jsonb, 'I have been here before.', 'Eu já estive aqui antes.'),
  ('unit-essential-verbs-a1-06-02', 'lesson-essential-verbs-a1-06', 2, 'verb_forms', 'have had had', 'ter', '/hæv hæd hæd/', 'Base "have" · passado "had" · particípio "had". No presente, "has" com he/she/it.', '[]'::jsonb, '[{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"}]'::jsonb, 'I have had this car for years.', 'Eu tenho este carro há anos.'),
  ('unit-essential-verbs-a1-06-03', 'lesson-essential-verbs-a1-06', 3, 'verb_forms', 'do did done', 'fazer', '/duː dɪd dʌn/', 'Base "do" · passado "did" · particípio "done". "Did" também forma perguntas no passado.', '[]'::jsonb, '[{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"done","pos":"verb","ipa":"/dʌn/","gloss":"feito (particípio de do)"}]'::jsonb, 'We have done everything.', 'Nós já fizemos tudo.'),
  ('unit-essential-verbs-a1-06-04', 'lesson-essential-verbs-a1-06', 4, 'verb_forms', 'say said said', 'dizer', '/seɪ sɛd sɛd/', 'Base "say" · passado e particípio "said" /sɛd/.', '[]'::jsonb, '[{"surface":"say","pos":"verb","ipa":"/seɪ/","gloss":"dizer"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"},{"surface":"said","pos":"verb","ipa":"/sɛd/","gloss":"disse, dito"}]'::jsonb, 'She said no.', 'Ela disse não.'),
  ('unit-essential-verbs-a1-06-05', 'lesson-essential-verbs-a1-06', 5, 'verb_forms', 'go went gone', 'ir', '/ɡoʊ wɛnt ɡɔːn/', 'Base "go" · passado "went" · particípio "gone". "Went" não se parece com a base: decore.', '[]'::jsonb, '[{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"gone","pos":"verb","ipa":"/ɡɔːn/","gloss":"ido (particípio de go)"}]'::jsonb, 'We went to the beach on Sunday.', 'Nós fomos à praia no domingo.'),
  ('unit-essential-verbs-a1-06-06', 'lesson-essential-verbs-a1-06', 6, 'verb_forms', 'get got gotten', 'conseguir, ficar', '/ɡɛt ɡɑːt ˈɡɑːtən/', 'Base "get" · passado "got" · particípio "gotten" (EUA) ou "got" (Reino Unido).', '[]'::jsonb, '[{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"gotten","pos":"verb","ipa":"/ˈɡɑːtən/","gloss":"conseguido, recebido"}]'::jsonb, 'He got a new phone.', 'Ele ganhou um celular novo.'),
  ('unit-essential-verbs-a1-06-07', 'lesson-essential-verbs-a1-06', 7, 'verb_forms', 'make made made', 'fazer (criar)', '/meɪk meɪd meɪd/', 'Base "make" · passado e particípio "made".', '[]'::jsonb, '[{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"},{"surface":"made","pos":"verb","ipa":"/meɪd/","gloss":"fez, feito"}]'::jsonb, 'I made a mistake.', 'Eu cometi um erro.'),
  ('unit-essential-verbs-a1-06-08', 'lesson-essential-verbs-a1-06', 8, 'verb_forms', 'know knew known', 'saber, conhecer', '/noʊ nuː noʊn/', 'Base "know" · passado "knew" · particípio "known". O "k" é sempre mudo.', '[]'::jsonb, '[{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"knew","pos":"verb","ipa":"/nuː/","gloss":"sabia, conheceu"},{"surface":"known","pos":"verb","ipa":"/noʊn/","gloss":"sabido, conhecido"}]'::jsonb, 'I knew the answer.', 'Eu sabia a resposta.'),
  ('unit-essential-verbs-a1-06-09', 'lesson-essential-verbs-a1-06', 9, 'verb_forms', 'think thought thought', 'pensar, achar', '/θɪŋk θɔːt θɔːt/', 'Base "think" · passado e particípio "thought".', '[]'::jsonb, '[{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"thought","pos":"verb","ipa":"/θɔːt/","gloss":"pensou, pensado"},{"surface":"thought","pos":"verb","ipa":"/θɔːt/","gloss":"pensou, pensado"}]'::jsonb, 'I thought about you yesterday.', 'Pensei em você ontem.'),
  ('unit-essential-verbs-a1-06-10', 'lesson-essential-verbs-a1-06', 10, 'verb_forms', 'take took taken', 'pegar, levar', '/teɪk tʊk ˈteɪkən/', 'Base "take" · passado "took" · particípio "taken".', '[]'::jsonb, '[{"surface":"take","pos":"verb","ipa":"/teɪk/","gloss":"pegar, levar"},{"surface":"took","pos":"verb","ipa":"/tʊk/","gloss":"pegou, levou"},{"surface":"taken","pos":"verb","ipa":"/ˈteɪkən/","gloss":"pegado, levado"}]'::jsonb, 'He took the wrong train.', 'Ele pegou o trem errado.')
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
