-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-prepositions-b1', 'prepositions-connectors-b1', 'Preposições e Conectores', 'In, on, at, preposições que acompanham verbos e adjetivos, e os conectores que ligam ideias.', 'As preposições que mais confundem brasileiros (in/on/at de tempo e lugar, verbo + preposição, adjetivo + preposição) e os conectores de contraste, causa, consequência e sequência. Cada frase explica a regra e o erro típico.', 'B1', 'grammar', 10, 'gramatica', 3, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-prepositions-b1-01', 'course-prepositions-b1', 1, 'In, on e at: tempo', 'Hora, dia, mês, ano e partes do dia.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-prepositions-b1-01-01', 'lesson-prepositions-b1-01', 1, 'sentence', 'The meeting is at nine.', 'A reunião é às nove.', '/ðə ˈmiːtɪŋ ɪz æt naɪn/', '"At" + hora exata.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"nine","pos":"numeral","ipa":"/naɪn/","gloss":"nove"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-02', 'lesson-prepositions-b1-01', 2, 'sentence', 'I''ll see you on Monday.', 'Te vejo na segunda.', '/aɪl siː juː ɑːn ˈmʌndeɪ/', '"On" + dia da semana ou data.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"Monday","pos":"proper noun","ipa":"/ˈmʌndeɪ/","gloss":"segunda-feira"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-03', 'lesson-prepositions-b1-01', 3, 'sentence', 'My birthday is on May tenth.', 'Meu aniversário é no dia dez de maio.', '/maɪ ˈbɜːrθdeɪ ɪz ɑːn meɪ tɛnθ/', 'Data completa usa "on".', '[]'::jsonb, '[{"surface":"My","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"birthday","pos":"noun","ipa":"/ˈbɜːrθdeɪ/","gloss":"aniversário"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"May","pos":"modal verb","ipa":"/meɪ/","gloss":"poder (permissão formal)"},{"surface":"tenth","pos":"adjective","ipa":"/tɛnθ/","gloss":"décimo"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-04', 'lesson-prepositions-b1-01', 4, 'sentence', 'We moved here in March.', 'Nos mudamos para cá em março.', '/wiː muːvd hɪr ɪn mɑːrtʃ/', '"In" + mês.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"moved","pos":"verb","ipa":"/muːvd/","gloss":"mudou-se, moveu"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"March","pos":"proper noun","ipa":"/mɑːrtʃ/","gloss":"março"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-05', 'lesson-prepositions-b1-01', 5, 'sentence', 'She was born in nineteen ninety.', 'Ela nasceu em mil novecentos e noventa.', '/ʃiː wɑːz bɔːrn ɪn ˌnaɪnˈtiːn ˈnaɪnti/', '"In" + ano. Anos são lidos em pares: "nineteen ninety".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"born","pos":"verb","ipa":"/bɔːrn/","gloss":"nascido (be born = nascer)"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"nineteen","pos":"numeral","ipa":"/ˌnaɪnˈtiːn/","gloss":"dezenove"},{"surface":"ninety","pos":"numeral","ipa":"/ˈnaɪnti/","gloss":"noventa"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-06', 'lesson-prepositions-b1-01', 6, 'sentence', 'I study in the morning.', 'Estudo de manhã.', '/aɪ ˈstʌdi ɪn ðə ˈmɔːrnɪŋ/', '"In the morning/afternoon/evening".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"study","pos":"verb","ipa":"/ˈstʌdi/","gloss":"estudar"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"morning","pos":"noun","ipa":"/ˈmɔːrnɪŋ/","gloss":"manhã"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-07', 'lesson-prepositions-b1-01', 7, 'sentence', 'I never go out at night.', 'Nunca saio à noite.', '/aɪ ˈnɛvər ɡoʊ aʊt æt naɪt/', 'Exceção: "at night", não "in the night".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"},{"surface":"go","pos":"verb","ipa":"/ɡoʊ/","gloss":"ir"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"night","pos":"noun","ipa":"/naɪt/","gloss":"noite"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-08', 'lesson-prepositions-b1-01', 8, 'sentence', 'We''ll travel at Christmas.', 'Vamos viajar no Natal.', '/wiːl ˈtrævəl æt ˈkrɪsməs/', '"At" + feriado (o período); "on Christmas Day" = no dia.', '[]'::jsonb, '[{"surface":"We''ll","pos":"pronoun","ipa":"/wiːl/","gloss":"nós vamos (we will)"},{"surface":"travel","pos":"verb","ipa":"/ˈtrævəl/","gloss":"viajar"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"Christmas","pos":"proper noun","ipa":"/ˈkrɪsməs/","gloss":"Natal"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-09', 'lesson-prepositions-b1-01', 9, 'sentence', 'I will call you in ten minutes.', 'Te ligo daqui a dez minutos.', '/aɪ wɪl kɔːl juː ɪn tɛn ˈmɪnɪts/', '"In" + período = daqui a.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"will","pos":"modal verb","ipa":"/wɪl/","gloss":"marca de futuro"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"ten","pos":"numeral","ipa":"/tɛn/","gloss":"dez"},{"surface":"minutes","pos":"noun","ipa":"/ˈmɪnɪts/","gloss":"minutos"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-01-10', 'lesson-prepositions-b1-01', 10, 'sentence', 'See you next week.', 'Até semana que vem.', '/siː juː nɛkst wiːk/', 'Sem preposição antes de "next", "last", "this", "every".', '[]'::jsonb, '[{"surface":"See","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-prepositions-b1-02', 'course-prepositions-b1', 2, 'In, on e at: lugar', 'Cidade, rua, endereço, transporte e posição.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-prepositions-b1-02-01', 'lesson-prepositions-b1-02', 1, 'sentence', 'I live in Brazil.', 'Moro no Brasil.', '/aɪ lɪv ɪn brəˈzɪl/', '"In" + país ou cidade.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"live","pos":"verb","ipa":"/lɪv/","gloss":"morar, viver"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"Brazil","pos":"proper noun","ipa":"/brəˈzɪl/","gloss":"Brasil"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-02', 'lesson-prepositions-b1-02', 2, 'sentence', 'The store is on Main Street.', 'A loja fica na Main Street.', '/ðə stɔːr ɪz ɑːn meɪn striːt/', '"On" + nome de rua.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"store","pos":"noun","ipa":"/stɔːr/","gloss":"loja, mercado"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"Main","pos":"adjective","ipa":"/meɪn/","gloss":"principal"},{"surface":"Street","pos":"noun","ipa":"/striːt/","gloss":"rua"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-03', 'lesson-prepositions-b1-02', 3, 'sentence', 'She lives at twenty Oak Street.', 'Ela mora no número vinte da Oak Street.', '/ʃiː lɪvz æt ˈtwɛnti oʊk striːt/', '"At" + endereço com número.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"lives","pos":"verb","ipa":"/lɪvz/","gloss":"mora, vive"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"twenty","pos":"numeral","ipa":"/ˈtwɛnti/","gloss":"vinte"},{"surface":"Oak","pos":"proper noun","ipa":"/oʊk/","gloss":"Oak (carvalho)"},{"surface":"Street","pos":"noun","ipa":"/striːt/","gloss":"rua"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-04', 'lesson-prepositions-b1-02', 4, 'sentence', 'I''m at work.', 'Estou no trabalho.', '/aɪm æt wɜːrk/', '"At" para lugar como ponto: at work, at school, at home.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-05', 'lesson-prepositions-b1-02', 5, 'sentence', 'The keys are on the table.', 'As chaves estão em cima da mesa.', '/ðə kiːz ɑːr ɑːn ðə ˈteɪbəl/', '"On" = sobre uma superfície.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"keys","pos":"noun","ipa":"/kiːz/","gloss":"chaves"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"table","pos":"noun","ipa":"/ˈteɪbəl/","gloss":"mesa"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-06', 'lesson-prepositions-b1-02', 6, 'sentence', 'The milk is in the fridge.', 'O leite está na geladeira.', '/ðə mɪlk ɪz ɪn ðə frɪdʒ/', '"In" = dentro.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"milk","pos":"noun","ipa":"/mɪlk/","gloss":"leite"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"fridge","pos":"noun","ipa":"/frɪdʒ/","gloss":"geladeira"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-07', 'lesson-prepositions-b1-02', 7, 'sentence', 'I read it on the bus.', 'Li no ônibus.', '/aɪ riːd ɪt ɑːn ðə bʌs/', '"On" + ônibus, trem, avião; "in" + carro, táxi.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"read","pos":"verb","ipa":"/riːd/","gloss":"ler"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"bus","pos":"noun","ipa":"/bʌs/","gloss":"ônibus"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-08', 'lesson-prepositions-b1-02', 8, 'sentence', 'There is a picture on the wall.', 'Tem um quadro na parede.', '/ðɛr ɪz ə ˈpɪktʃər ɑːn ðə wɔːl/', 'Parede é superfície: "on the wall".', '[]'::jsonb, '[{"surface":"There","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"picture","pos":"noun","ipa":"/ˈpɪktʃər/","gloss":"foto"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"wall","pos":"noun","ipa":"/wɔːl/","gloss":"parede"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-09', 'lesson-prepositions-b1-02', 9, 'sentence', 'Wait for me at the entrance.', 'Me espera na entrada.', '/weɪt fɔːr miː æt ðə ˈɛntrəns/', '"At" para ponto de encontro.', '[]'::jsonb, '[{"surface":"Wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"entrance","pos":"noun","ipa":"/ˈɛntrəns/","gloss":"entrada"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-02-10', 'lesson-prepositions-b1-02', 10, 'sentence', 'He''s in the kitchen.', 'Ele está na cozinha.', '/hiːz ɪn ðə ˈkɪtʃən/', 'Cômodo = espaço fechado: "in".', '[]'::jsonb, '[{"surface":"He''s","pos":"pronoun","ipa":"/hiːz/","gloss":"ele é, ele está"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"kitchen","pos":"noun","ipa":"/ˈkɪtʃən/","gloss":"cozinha"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-prepositions-b1-03', 'course-prepositions-b1', 3, 'Verbo + preposição', 'Verbos que pedem uma preposição diferente do português.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-prepositions-b1-03-01', 'lesson-prepositions-b1-03', 1, 'sentence', 'It depends on the weather.', 'Depende do tempo.', '/ɪt dɪˈpɛndz ɑːn ðə ˈwɛðər/', '"Depend on", nunca "depend of".', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"depends","pos":"verb","ipa":"/dɪˈpɛndz/","gloss":"depende"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"weather","pos":"noun","ipa":"/ˈwɛðər/","gloss":"tempo, clima"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-02', 'lesson-prepositions-b1-03', 2, 'sentence', 'I''m listening to music.', 'Estou ouvindo música.', '/aɪm ˈlɪsənɪŋ tuː ˈmjuːzɪk/', '"Listen to" + algo.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"listening","pos":"verb","ipa":"/ˈlɪsənɪŋ/","gloss":"ouvindo"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"music","pos":"noun","ipa":"/ˈmjuːzɪk/","gloss":"música"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-03', 'lesson-prepositions-b1-03', 3, 'sentence', 'Wait for me!', 'Me espera!', '/weɪt fɔːr miː/', '"Wait for" + pessoa ou coisa.', '[]'::jsonb, '[{"surface":"Wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-04', 'lesson-prepositions-b1-03', 4, 'sentence', 'I agree with you.', 'Concordo com você.', '/aɪ əˈɡriː wɪð juː/', '"Agree with" + pessoa; "agree on" + assunto.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"agree","pos":"verb","ipa":"/əˈɡriː/","gloss":"concordar"},{"surface":"with","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-05', 'lesson-prepositions-b1-03', 5, 'sentence', 'She arrived in London yesterday.', 'Ela chegou a Londres ontem.', '/ʃiː əˈraɪvd ɪn ˈlʌndən ˈjɛstərdeɪ/', '"Arrive in" + cidade/país; "arrive at" + lugar específico.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"arrived","pos":"verb","ipa":"/əˈraɪvd/","gloss":"chegou"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"London","pos":"proper noun","ipa":"/ˈlʌndən/","gloss":"Londres"},{"surface":"yesterday","pos":"adverb","ipa":"/ˈjɛstərdeɪ/","gloss":"ontem"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-06', 'lesson-prepositions-b1-03', 6, 'sentence', 'Think about it.', 'Pensa nisso.', '/θɪŋk əˈbaʊt ɪt/', '"Think about" = pensar em.', '[]'::jsonb, '[{"surface":"Think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-07', 'lesson-prepositions-b1-03', 7, 'sentence', 'I dream of living abroad.', 'Sonho em morar fora.', '/aɪ driːm ʌv ˈlɪvɪŋ əˈbrɔːd/', '"Dream of/about" + verbo com "-ing".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"dream","pos":"verb","ipa":"/driːm/","gloss":"sonhar"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"living","pos":"adjective","ipa":"/ˈlɪvɪŋ/","gloss":"de estar"},{"surface":"abroad","pos":"adverb","ipa":"/əˈbrɔːd/","gloss":"no exterior"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-08', 'lesson-prepositions-b1-03', 8, 'sentence', 'He paid for dinner.', 'Ele pagou o jantar.', '/hiː peɪd fɔːr ˈdɪnər/', '"Pay for" + o que se compra.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"paid","pos":"verb","ipa":"/peɪd/","gloss":"pagou"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"dinner","pos":"noun","ipa":"/ˈdɪnər/","gloss":"jantar"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-09', 'lesson-prepositions-b1-03', 9, 'sentence', 'Please ask for help.', 'Por favor, peça ajuda.', '/pliːz æsk fɔːr hɛlp/', '"Ask for" = pedir algo.', '[]'::jsonb, '[{"surface":"Please","pos":"adverb","ipa":"/pliːz/","gloss":"por favor"},{"surface":"ask","pos":"verb","ipa":"/æsk/","gloss":"perguntar, pedir"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-03-10', 'lesson-prepositions-b1-03', 10, 'sentence', 'She is married to a doctor.', 'Ela é casada com um médico.', '/ʃiː ɪz ˈmærid tuː ə ˈdɑːktər/', '"Married to", nunca "married with".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"married","pos":"adjective","ipa":"/ˈmærid/","gloss":"casado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"doctor","pos":"noun","ipa":"/ˈdɑːktər/","gloss":"médico"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-prepositions-b1-04', 'course-prepositions-b1', 4, 'Adjetivo + preposição', 'Combinações fixas que caem em provas e conversas.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-prepositions-b1-04-01', 'lesson-prepositions-b1-04', 1, 'sentence', 'I''m interested in art.', 'Me interesso por arte.', '/aɪm ˈɪntrəstɪd ɪn ɑːrt/', '"Interested in", não "interested for".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"interested","pos":"adjective","ipa":"/ˈɪntrəstɪd/","gloss":"interessado"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"art","pos":"noun","ipa":"/ɑːrt/","gloss":"arte"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-02', 'lesson-prepositions-b1-04', 2, 'sentence', 'She''s good at math.', 'Ela é boa em matemática.', '/ʃiːz ɡʊd æt mæθ/', '"Good at", não "good in".', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"math","pos":"noun","ipa":"/mæθ/","gloss":"matemática"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-03', 'lesson-prepositions-b1-04', 3, 'sentence', 'I''m afraid of heights.', 'Tenho medo de altura.', '/aɪm əˈfreɪd ʌv haɪts/', '"Afraid of" = com medo de.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"afraid","pos":"adjective","ipa":"/əˈfreɪd/","gloss":"com medo"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"heights","pos":"noun","ipa":"/haɪts/","gloss":"alturas"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-04', 'lesson-prepositions-b1-04', 4, 'sentence', 'He''s proud of his work.', 'Ele tem orgulho do trabalho dele.', '/hiːz praʊd ʌv hɪz wɜːrk/', '"Proud of".', '[]'::jsonb, '[{"surface":"He''s","pos":"pronoun","ipa":"/hiːz/","gloss":"ele é, ele está"},{"surface":"proud","pos":"adjective","ipa":"/praʊd/","gloss":"orgulhoso"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"work","pos":"noun","ipa":"/wɜːrk/","gloss":"trabalho"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-05', 'lesson-prepositions-b1-04', 5, 'sentence', 'I''m tired of waiting.', 'Estou cansado de esperar.', '/aɪm ˈtaɪərd ʌv ˈweɪtɪŋ/', '"Tired of" + "-ing" = farto de.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-06', 'lesson-prepositions-b1-04', 6, 'sentence', 'We''re worried about you.', 'Estamos preocupados com você.', '/wɪr ˈwɜːrid əˈbaʊt juː/', '"Worried about".', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"worried","pos":"adjective","ipa":"/ˈwɜːrid/","gloss":"preocupado"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-07', 'lesson-prepositions-b1-04', 7, 'sentence', 'She''s married to my cousin.', 'Ela é casada com meu primo.', '/ʃiːz ˈmærid tuː maɪ ˈkʌzən/', 'Revisão: "married to".', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"married","pos":"adjective","ipa":"/ˈmærid/","gloss":"casado"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"cousin","pos":"noun","ipa":"/ˈkʌzən/","gloss":"primo, prima"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-08', 'lesson-prepositions-b1-04', 8, 'sentence', 'This is different from the original.', 'Isto é diferente do original.', '/ðɪs ɪz ˈdɪfərənt frʌm ðə əˈrɪdʒənəl/', '"Different from" (EUA também aceita "different than").', '[]'::jsonb, '[{"surface":"This","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"different","pos":"adjective","ipa":"/ˈdɪfərənt/","gloss":"diferente"},{"surface":"from","pos":"preposition","ipa":"/frʌm/","gloss":"de (origem)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"original","pos":"noun","ipa":"/əˈrɪdʒənəl/","gloss":"original"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-09', 'lesson-prepositions-b1-04', 9, 'sentence', 'I''m responsible for the budget.', 'Sou responsável pelo orçamento.', '/aɪm rɪˈspɑːnsəbəl fɔːr ðə ˈbʌdʒɪt/', '"Responsible for".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"responsible","pos":"adjective","ipa":"/rɪˈspɑːnsəbəl/","gloss":"responsável"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"budget","pos":"noun","ipa":"/ˈbʌdʒɪt/","gloss":"orçamento"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-04-10', 'lesson-prepositions-b1-04', 10, 'sentence', 'He''s famous for his music.', 'Ele é famoso pela música.', '/hiːz ˈfeɪməs fɔːr hɪz ˈmjuːzɪk/', '"Famous for".', '[]'::jsonb, '[{"surface":"He''s","pos":"pronoun","ipa":"/hiːz/","gloss":"ele é, ele está"},{"surface":"famous","pos":"adjective","ipa":"/ˈfeɪməs/","gloss":"famoso"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"his","pos":"determiner","ipa":"/hɪz/","gloss":"dele"},{"surface":"music","pos":"noun","ipa":"/ˈmjuːzɪk/","gloss":"música"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-prepositions-b1-05', 'course-prepositions-b1', 5, 'Conectores de contraste', 'But, however, although, despite, even though.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-prepositions-b1-05-01', 'lesson-prepositions-b1-05', 1, 'sentence', 'I like it, but it is too expensive.', 'Gosto, mas é caro demais.', '/aɪ laɪk ɪt bʌt ɪt ɪz tuː ɪkˈspɛnsɪv/', '"But" liga duas partes da mesma frase.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"too","pos":"adverb","ipa":"/tuː/","gloss":"demais"},{"surface":"expensive","pos":"adjective","ipa":"/ɪkˈspɛnsɪv/","gloss":"caro"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-02', 'lesson-prepositions-b1-05', 2, 'sentence', 'It was cold. However, we went to the beach.', 'Estava frio. Mesmo assim, fomos à praia.', '/ɪt wɑːz koʊld haʊˈɛvər wiː wɛnt tuː ðə biːtʃ/', '"However" começa uma nova frase e vem com vírgula.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"cold","pos":"noun","ipa":"/koʊld/","gloss":"resfriado; frio"},{"surface":"However","pos":"adverb","ipa":"/haʊˈɛvər/","gloss":"no entanto, mesmo assim"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"beach","pos":"noun","ipa":"/biːtʃ/","gloss":"praia"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-03', 'lesson-prepositions-b1-05', 3, 'sentence', 'Although it was late, we kept working.', 'Embora fosse tarde, continuamos trabalhando.', '/ɔːlˈðoʊ ɪt wɑːz leɪt wiː kɛpt ˈwɜːrkɪŋ/', '"Although" + frase completa (sujeito + verbo).', '[]'::jsonb, '[{"surface":"Although","pos":"conjunction","ipa":"/ɔːlˈðoʊ/","gloss":"embora"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"kept","pos":"verb","ipa":"/kɛpt/","gloss":"guardou, manteve"},{"surface":"working","pos":"verb","ipa":"/ˈwɜːrkɪŋ/","gloss":"funcionando; trabalhando"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-04', 'lesson-prepositions-b1-05', 4, 'sentence', 'Despite the rain, the game continued.', 'Apesar da chuva, o jogo continuou.', '/dɪˈspaɪt ðə reɪn ðə ɡeɪm kənˈtɪnjuːd/', '"Despite" + substantivo ou "-ing", sem "of".', '[]'::jsonb, '[{"surface":"Despite","pos":"preposition","ipa":"/dɪˈspaɪt/","gloss":"apesar de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"rain","pos":"verb","ipa":"/reɪn/","gloss":"chover; chuva"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"game","pos":"noun","ipa":"/ɡeɪm/","gloss":"jogo"},{"surface":"continued","pos":"verb","ipa":"/kənˈtɪnjuːd/","gloss":"continuou"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-05', 'lesson-prepositions-b1-05', 5, 'sentence', 'Even though I was tired, I finished it.', 'Mesmo cansado, eu terminei.', '/ˈiːvən ðoʊ aɪ wɑːz ˈtaɪərd aɪ ˈfɪnɪʃt ɪt/', '"Even though" = mais forte que "although".', '[]'::jsonb, '[{"surface":"Even","pos":"adverb","ipa":"/ˈiːvən/","gloss":"até, mesmo"},{"surface":"though","pos":"conjunction","ipa":"/ðoʊ/","gloss":"embora"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"tired","pos":"adjective","ipa":"/ˈtaɪərd/","gloss":"cansado"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"finished","pos":"verb","ipa":"/ˈfɪnɪʃt/","gloss":"terminou, terminado"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-06', 'lesson-prepositions-b1-05', 6, 'sentence', 'In spite of the traffic, we arrived on time.', 'Apesar do trânsito, chegamos na hora.', '/ɪn spaɪt ʌv ðə ˈtræfɪk wiː əˈraɪvd ɑːn taɪm/', '"In spite of" = "despite". "On time" = pontual.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"spite","pos":"noun","ipa":"/spaɪt/","gloss":"despeito (in spite of = apesar de)"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"traffic","pos":"noun","ipa":"/ˈtræfɪk/","gloss":"trânsito"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"arrived","pos":"verb","ipa":"/əˈraɪvd/","gloss":"chegou"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-07', 'lesson-prepositions-b1-05', 7, 'sentence', 'She is rich, yet she lives simply.', 'Ela é rica, mas vive com simplicidade.', '/ʃiː ɪz rɪtʃ jɛt ʃiː lɪvz ˈsɪmpli/', '"Yet" como conector = mas, ainda assim.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"rich","pos":"adjective","ipa":"/rɪtʃ/","gloss":"rico"},{"surface":"yet","pos":"adverb","ipa":"/jɛt/","gloss":"ainda"},{"surface":"she","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"lives","pos":"verb","ipa":"/lɪvz/","gloss":"mora, vive"},{"surface":"simply","pos":"adverb","ipa":"/ˈsɪmpli/","gloss":"com simplicidade"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-08', 'lesson-prepositions-b1-05', 8, 'sentence', 'On the other hand, it is cheaper.', 'Por outro lado, é mais barato.', '/ɑːn ðə ˈʌðər hænd ɪt ɪz ˈtʃiːpər/', 'Apresenta o outro lado de um argumento.', '[]'::jsonb, '[{"surface":"On","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"other","pos":"pronoun","ipa":"/ˈʌðər/","gloss":"outro"},{"surface":"hand","pos":"noun","ipa":"/hænd/","gloss":"mão, ajuda"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"cheaper","pos":"adjective","ipa":"/ˈtʃiːpər/","gloss":"mais barato"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-09', 'lesson-prepositions-b1-05', 9, 'sentence', 'Whereas I like tea, my wife likes coffee.', 'Enquanto eu gosto de chá, minha esposa gosta de café.', '/wɛrˈæz aɪ laɪk tiː maɪ waɪf laɪks ˈkɔːfi/', '"Whereas" = enquanto (contraste).', '[]'::jsonb, '[{"surface":"Whereas","pos":"conjunction","ipa":"/wɛrˈæz/","gloss":"enquanto (contraste)"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"like","pos":"verb","ipa":"/laɪk/","gloss":"gostar"},{"surface":"tea","pos":"noun","ipa":"/tiː/","gloss":"chá"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"wife","pos":"noun","ipa":"/waɪf/","gloss":"esposa"},{"surface":"likes","pos":"verb","ipa":"/laɪks/","gloss":"gosta"},{"surface":"coffee","pos":"noun","ipa":"/ˈkɔːfi/","gloss":"café"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-05-10', 'lesson-prepositions-b1-05', 10, 'sentence', 'It is small but cozy.', 'É pequeno, mas aconchegante.', '/ɪt ɪz smɔːl bʌt ˈkoʊzi/', '"Cozy" = aconchegante (Reino Unido: "cosy").', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"small","pos":"adjective","ipa":"/smɔːl/","gloss":"pequeno"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"cozy","pos":"adjective","ipa":"/ˈkoʊzi/","gloss":"aconchegante"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-prepositions-b1-06', 'course-prepositions-b1', 6, 'Causa, consequência e sequência', 'Because, so, therefore, due to, first, then, finally.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-prepositions-b1-06-01', 'lesson-prepositions-b1-06', 1, 'sentence', 'I stayed home because I was sick.', 'Fiquei em casa porque estava doente.', '/aɪ steɪd hoʊm bɪˈkɔːz aɪ wɑːz sɪk/', '"Because" + frase.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"stayed","pos":"verb","ipa":"/steɪd/","gloss":"ficou"},{"surface":"home","pos":"noun","ipa":"/hoʊm/","gloss":"casa, lar"},{"surface":"because","pos":"conjunction","ipa":"/bɪˈkɔːz/","gloss":"porque"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"sick","pos":"adjective","ipa":"/sɪk/","gloss":"doente, enjoado"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-02', 'lesson-prepositions-b1-06', 2, 'sentence', 'The flight was canceled because of the storm.', 'O voo foi cancelado por causa da tempestade.', '/ðə flaɪt wɑːz ˈkænsəld bɪˈkɔːz ʌv ðə stɔːrm/', '"Because of" + substantivo.', '[]'::jsonb, '[{"surface":"The","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"flight","pos":"noun","ipa":"/flaɪt/","gloss":"voo"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"canceled","pos":"verb","ipa":"/ˈkænsəld/","gloss":"cancelado"},{"surface":"because","pos":"conjunction","ipa":"/bɪˈkɔːz/","gloss":"porque"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"storm","pos":"noun","ipa":"/stɔːrm/","gloss":"tempestade"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-03', 'lesson-prepositions-b1-06', 3, 'sentence', 'It was raining, so we took a taxi.', 'Estava chovendo, então pegamos um táxi.', '/ɪt wɑːz ˈreɪnɪŋ soʊ wiː tʊk ə ˈtæksi/', '"So" = então (consequência).', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"raining","pos":"verb","ipa":"/ˈreɪnɪŋ/","gloss":"chovendo"},{"surface":"so","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"took","pos":"verb","ipa":"/tʊk/","gloss":"pegou, levou"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"taxi","pos":"noun","ipa":"/ˈtæksi/","gloss":"táxi"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-04', 'lesson-prepositions-b1-06', 4, 'sentence', 'Sales fell. Therefore, we cut costs.', 'As vendas caíram. Por isso, cortamos custos.', '/seɪlz fɛl ˈðɛrfɔːr wiː kʌt kɔːsts/', '"Therefore" = portanto; mais formal.', '[]'::jsonb, '[{"surface":"Sales","pos":"noun","ipa":"/seɪlz/","gloss":"vendas"},{"surface":"fell","pos":"verb","ipa":"/fɛl/","gloss":"caiu"},{"surface":"Therefore","pos":"adverb","ipa":"/ˈðɛrfɔːr/","gloss":"portanto"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"cut","pos":"verb","ipa":"/kʌt/","gloss":"cortar"},{"surface":"costs","pos":"verb","ipa":"/kɔːsts/","gloss":"custa"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-05', 'lesson-prepositions-b1-06', 5, 'sentence', 'Due to the delay, the meeting was moved.', 'Devido ao atraso, a reunião foi remarcada.', '/duː tuː ðə dɪˈleɪ ðə ˈmiːtɪŋ wɑːz muːvd/', '"Due to" + substantivo; formal.', '[]'::jsonb, '[{"surface":"Due","pos":"adjective","ipa":"/duː/","gloss":"devido (due to)"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"delay","pos":"noun","ipa":"/dɪˈleɪ/","gloss":"atraso"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"meeting","pos":"noun","ipa":"/ˈmiːtɪŋ/","gloss":"reunião"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"moved","pos":"verb","ipa":"/muːvd/","gloss":"mudou-se, moveu"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-06', 'lesson-prepositions-b1-06', 6, 'sentence', 'Since you are here, can you help me?', 'Já que você está aqui, pode me ajudar?', '/sɪns juː ɑːr hɪr kæn juː hɛlp miː/', '"Since" também é "já que".', '[]'::jsonb, '[{"surface":"Since","pos":"preposition","ipa":"/sɪns/","gloss":"desde"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"here","pos":"adverb","ipa":"/hɪr/","gloss":"aqui"},{"surface":"can","pos":"auxiliary verb","ipa":"/kæn/","gloss":"poder"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-07', 'lesson-prepositions-b1-06', 7, 'sentence', 'First, open the app.', 'Primeiro, abra o aplicativo.', '/fɜːrst ˈoʊpən ðə æp/', 'Sequência: first, then, after that, finally.', '[]'::jsonb, '[{"surface":"First","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"open","pos":"verb","ipa":"/ˈoʊpən/","gloss":"abrir"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"app","pos":"noun","ipa":"/æp/","gloss":"aplicativo"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-08', 'lesson-prepositions-b1-06', 8, 'sentence', 'Then, click on the button.', 'Depois, clique no botão.', '/ðɛn klɪk ɑːn ðə ˈbʌtən/', '"Then" = em seguida.', '[]'::jsonb, '[{"surface":"Then","pos":"adverb","ipa":"/ðɛn/","gloss":"então, depois"},{"surface":"click","pos":"verb","ipa":"/klɪk/","gloss":"clicar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"button","pos":"noun","ipa":"/ˈbʌtən/","gloss":"botão"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-09', 'lesson-prepositions-b1-06', 9, 'sentence', 'After that, enter your password.', 'Depois disso, digite sua senha.', '/ˈæftər ðæt ˈɛntər jʊr ˈpæswɜːrd/', '"After that" = depois disso.', '[]'::jsonb, '[{"surface":"After","pos":"preposition","ipa":"/ˈæftər/","gloss":"depois de"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"enter","pos":"verb","ipa":"/ˈɛntər/","gloss":"digitar, entrar"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"password","pos":"noun","ipa":"/ˈpæswɜːrd/","gloss":"senha"}]'::jsonb, NULL, NULL),
  ('unit-prepositions-b1-06-10', 'lesson-prepositions-b1-06', 10, 'sentence', 'Finally, you''re done.', 'Por fim, está pronto.', '/ˈfaɪnəli jʊr dʌn/', '"Finally" = por fim, finalmente.', '[]'::jsonb, '[{"surface":"Finally","pos":"adverb","ipa":"/ˈfaɪnəli/","gloss":"finalmente"},{"surface":"you''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"done","pos":"adjective","ipa":"/dʌn/","gloss":"pronto, feito"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
