-- Gerado por scripts/generate-course-seed.mjs a partir de supabase/content/. Não editar à mão.

-- Conteúdo original: frases do cotidiano com tradução pt-BR, notas, grupos sintáticos e anotações por palavra.

INSERT INTO public.course_catalog (id, slug, title, short_description, long_description, level, category, order_index, track, track_order, is_core, is_published)
VALUES ('course-idioms-b2', 'idioms-fluency-b2', 'Expressões Idiomáticas e Fluência', 'Idioms que nativos usam de verdade e os recursos que deixam sua fala natural: marcadores, opiniões suaves e histórias.', 'Expressões idiomáticas de trabalho, sentimentos, dinheiro e tempo, e as ferramentas de fluência que separam o B1 do B2: marcadores de conversa ("actually", "I mean"), como suavizar opiniões e como contar uma história. Cada nota traz o registro e o sentido literal × o real.', 'B2', 'social', 11, 'fluencia', 1, true, true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, short_description = EXCLUDED.short_description,
  long_description = EXCLUDED.long_description, level = EXCLUDED.level, category = EXCLUDED.category,
  order_index = EXCLUDED.order_index, track = EXCLUDED.track, track_order = EXCLUDED.track_order,
  is_core = EXCLUDED.is_core, is_published = EXCLUDED.is_published, updated_at = now();

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-01', 'course-idioms-b2', 1, 'Idioms de trabalho', 'Expressões que aparecem em reuniões e e-mails.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-01-01', 'lesson-idioms-b2-01', 1, 'sentence', 'Let''s touch base next week.', 'Vamos nos falar semana que vem.', '/lɛts tʌtʃ beɪs nɛkst wiːk/', 'Informal/trabalho. Literal: "tocar a base". Real: fazer um contato rápido.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"touch","pos":"verb","ipa":"/tʌtʃ/","gloss":"tocar, encostar"},{"surface":"base","pos":"noun","ipa":"/beɪs/","gloss":"base"},{"surface":"next","pos":"adjective","ipa":"/nɛkst/","gloss":"próximo"},{"surface":"week","pos":"noun","ipa":"/wiːk/","gloss":"semana"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-02', 'lesson-idioms-b2-01', 2, 'sentence', 'We are on the same page.', 'Estamos alinhados.', '/wiː ɑːr ɑːn ðə seɪm peɪdʒ/', 'Neutro. Literal: "na mesma página". Real: de acordo.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"same","pos":"adjective","ipa":"/seɪm/","gloss":"mesmo"},{"surface":"page","pos":"noun","ipa":"/peɪdʒ/","gloss":"página"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-03', 'lesson-idioms-b2-01', 3, 'sentence', 'Let''s think outside the box.', 'Vamos pensar fora da caixa.', '/lɛts θɪŋk ˌaʊtˈsaɪd ðə bɑːks/', 'Neutro. Igual ao português.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"outside","pos":"adverb","ipa":"/ˌaʊtˈsaɪd/","gloss":"lá fora"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"box","pos":"noun","ipa":"/bɑːks/","gloss":"caixa"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-04', 'lesson-idioms-b2-01', 4, 'sentence', 'I''ll keep you in the loop.', 'Vou te manter informado.', '/aɪl kiːp juː ɪn ðə luːp/', 'Trabalho. "In the loop" = por dentro do assunto.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"keep","pos":"verb","ipa":"/kiːp/","gloss":"manter"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"loop","pos":"noun","ipa":"/luːp/","gloss":"circuito, laço"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-05', 'lesson-idioms-b2-01', 5, 'sentence', 'That project is back on track.', 'O projeto voltou aos trilhos.', '/ðæt ˈprɑːdʒɛkt ɪz bæk ɑːn træk/', '"On track" = no caminho certo.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"project","pos":"noun","ipa":"/ˈprɑːdʒɛkt/","gloss":"projeto"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"track","pos":"noun","ipa":"/træk/","gloss":"trilha, caminho"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-06', 'lesson-idioms-b2-01', 6, 'sentence', 'It''s a win-win situation.', 'Todo mundo sai ganhando.', '/ɪts ə ˌwɪnˈwɪn ˌsɪtʃuˈeɪʃən/', 'Neutro. "Win-win" = bom para os dois lados.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"win-win","pos":"adjective","ipa":"/ˌwɪnˈwɪn/","gloss":"bom para todos"},{"surface":"situation","pos":"noun","ipa":"/ˌsɪtʃuˈeɪʃən/","gloss":"situação"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-07', 'lesson-idioms-b2-01', 7, 'sentence', 'Let''s get the ball rolling.', 'Vamos dar o pontapé inicial.', '/lɛts ɡɛt ðə bɔːl ˈroʊlɪŋ/', 'Informal. Literal: "fazer a bola rolar".', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"get","pos":"verb","ipa":"/ɡɛt/","gloss":"conseguir, chegar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"ball","pos":"noun","ipa":"/bɔːl/","gloss":"bola"},{"surface":"rolling","pos":"verb","ipa":"/ˈroʊlɪŋ/","gloss":"rolando"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-08', 'lesson-idioms-b2-01', 8, 'sentence', 'We need to cut corners to finish on time.', 'Precisamos simplificar para terminar no prazo.', '/wiː niːd tuː kʌt ˈkɔːrnərz tuː ˈfɪnɪʃ ɑːn taɪm/', 'Informal, às vezes negativo: "cut corners" = fazer de qualquer jeito.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"cut","pos":"verb","ipa":"/kʌt/","gloss":"cortar"},{"surface":"corners","pos":"noun","ipa":"/ˈkɔːrnərz/","gloss":"cantos"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"finish","pos":"verb","ipa":"/ˈfɪnɪʃ/","gloss":"terminar"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-09', 'lesson-idioms-b2-01', 9, 'sentence', 'She''s the go-to person for design.', 'Ela é a referência em design.', '/ʃiːz ðə ˈɡoʊtuː ˈpɜːrsən fɔːr dɪˈzaɪn/', 'Informal. "Go-to" = a pessoa a quem se recorre.', '[]'::jsonb, '[{"surface":"She''s","pos":"pronoun","ipa":"/ʃiːz/","gloss":"ela é, ela está"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"go-to","pos":"adjective","ipa":"/ˈɡoʊtuː/","gloss":"de referência"},{"surface":"person","pos":"noun","ipa":"/ˈpɜːrsən/","gloss":"pessoa"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"design","pos":"noun","ipa":"/dɪˈzaɪn/","gloss":"design"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-01-10', 'lesson-idioms-b2-01', 10, 'sentence', 'Let''s call it a day.', 'Vamos encerrar por hoje.', '/lɛts kɔːl ɪt ə deɪ/', 'Informal. Revisão do A1, agora no contexto de trabalho.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-02', 'course-idioms-b2', 2, 'Idioms de sentimentos', 'Dizer como você se sente com expressões nativas.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-02-01', 'lesson-idioms-b2-02', 1, 'sentence', 'I''m on cloud nine.', 'Estou nas nuvens.', '/aɪm ɑːn klaʊd naɪn/', 'Informal. Literal: "na nuvem nove". Real: muito feliz.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"cloud","pos":"noun","ipa":"/klaʊd/","gloss":"nuvem"},{"surface":"nine","pos":"numeral","ipa":"/naɪn/","gloss":"nove"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-02', 'lesson-idioms-b2-02', 2, 'sentence', 'I had butterflies in my stomach.', 'Eu estava com frio na barriga.', '/aɪ hæd ˈbʌtərflaɪz ɪn maɪ ˈstʌmək/', 'Informal. Literal: "borboletas no estômago".', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"had","pos":"verb","ipa":"/hæd/","gloss":"teve, tinha"},{"surface":"butterflies","pos":"noun","ipa":"/ˈbʌtərflaɪz/","gloss":"borboletas"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"stomach","pos":"noun","ipa":"/ˈstʌmək/","gloss":"estômago, barriga"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-03', 'lesson-idioms-b2-02', 3, 'sentence', 'She was over the moon.', 'Ela ficou radiante.', '/ʃiː wɑːz ˈoʊvər ðə muːn/', 'Informal. Literal: "acima da lua".', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"over","pos":"preposition","ipa":"/ˈoʊvər/","gloss":"por cima; superado"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"moon","pos":"noun","ipa":"/muːn/","gloss":"lua"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-04', 'lesson-idioms-b2-02', 4, 'sentence', 'I''m feeling a bit down.', 'Estou meio pra baixo.', '/aɪm ˈfiːlɪŋ ə bɪt daʊn/', 'Informal. "Down" = triste, desanimado.', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"feeling","pos":"verb","ipa":"/ˈfiːlɪŋ/","gloss":"sentindo"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"down","pos":"adjective","ipa":"/daʊn/","gloss":"dentro, topando (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-05', 'lesson-idioms-b2-02', 5, 'sentence', 'He flew off the handle.', 'Ele perdeu a cabeça.', '/hiː fluː ɔːf ðə ˈhændəl/', 'Informal. Literal: "voou do cabo". Real: explodiu de raiva.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"flew","pos":"verb","ipa":"/fluː/","gloss":"voou"},{"surface":"off","pos":"particle","ipa":"/ɔːf/","gloss":"(partícula: off)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"handle","pos":"verb","ipa":"/ˈhændəl/","gloss":"cuidar de, lidar com"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-06', 'lesson-idioms-b2-02', 6, 'sentence', 'It broke my heart.', 'Partiu meu coração.', '/ɪt broʊk maɪ hɑːrt/', 'Neutro. Igual ao português.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"broke","pos":"verb","ipa":"/broʊk/","gloss":"quebrou"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"heart","pos":"noun","ipa":"/hɑːrt/","gloss":"coração"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-07', 'lesson-idioms-b2-02', 7, 'sentence', 'I''m at the end of my rope.', 'Estou no meu limite.', '/aɪm æt ðə ɛnd ʌv maɪ roʊp/', 'Informal. Literal: "no fim da minha corda".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"end","pos":"noun","ipa":"/ɛnd/","gloss":"fim, final"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"rope","pos":"noun","ipa":"/roʊp/","gloss":"corda"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-08', 'lesson-idioms-b2-02', 8, 'sentence', 'She keeps her cool under pressure.', 'Ela mantém a calma sob pressão.', '/ʃiː kiːps hɜːr kuːl ˈʌndər ˈprɛʃər/', '"Keep your cool" = manter a calma; "lose your cool" = perder.', '[]'::jsonb, '[{"surface":"She","pos":"pronoun","ipa":"/ʃiː/","gloss":"ela"},{"surface":"keeps","pos":"verb","ipa":"/kiːps/","gloss":"mantém"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"},{"surface":"cool","pos":"adjective","ipa":"/kuːl/","gloss":"legal, massa"},{"surface":"under","pos":"preposition","ipa":"/ˈʌndər/","gloss":"no nome de, sob"},{"surface":"pressure","pos":"noun","ipa":"/ˈprɛʃər/","gloss":"pressão"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-09', 'lesson-idioms-b2-02', 9, 'sentence', 'That really got on my nerves.', 'Aquilo me irritou de verdade.', '/ðæt ˈriːəli ɡɑːt ɑːn maɪ nɜːrvz/', 'Informal. "Get on someone''s nerves" = irritar.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"really","pos":"adverb","ipa":"/ˈriːəli/","gloss":"muito, de verdade"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"nerves","pos":"noun","ipa":"/nɜːrvz/","gloss":"nervos"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-02-10', 'lesson-idioms-b2-02', 10, 'sentence', 'I''m walking on air.', 'Estou flutuando de felicidade.', '/aɪm ˈwɔːkɪŋ ɑːn ɛr/', 'Informal. Literal: "andando no ar".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"walking","pos":"noun","ipa":"/ˈwɔːkɪŋ/","gloss":"caminhada"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"air","pos":"noun","ipa":"/ɛr/","gloss":"ar"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-03', 'course-idioms-b2', 3, 'Idioms de dinheiro e tempo', 'Expressões sobre gastar, economizar e prazos.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-03-01', 'lesson-idioms-b2-03', 1, 'sentence', 'Money is tight this month.', 'O dinheiro está curto este mês.', '/ˈmʌni ɪz taɪt ðɪs mʌnθ/', 'Neutro. "Tight" = apertado.', '[]'::jsonb, '[{"surface":"Money","pos":"noun","ipa":"/ˈmʌni/","gloss":"dinheiro"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"tight","pos":"adjective","ipa":"/taɪt/","gloss":"apertado"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"month","pos":"noun","ipa":"/mʌnθ/","gloss":"mês"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-02', 'lesson-idioms-b2-03', 2, 'sentence', 'We''re saving for a rainy day.', 'Estamos guardando para imprevistos.', '/wɪr ˈseɪvɪŋ fɔːr ə ˈreɪni deɪ/', 'Neutro. Literal: "para um dia chuvoso".', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"saving","pos":"verb","ipa":"/ˈseɪvɪŋ/","gloss":"economizando"},{"surface":"for","pos":"preposition","ipa":"/fɔːr/","gloss":"para, por"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"rainy","pos":"adjective","ipa":"/ˈreɪni/","gloss":"chuvoso"},{"surface":"day","pos":"noun","ipa":"/deɪ/","gloss":"dia"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-03', 'lesson-idioms-b2-03', 3, 'sentence', 'That car cost me a fortune.', 'Aquele carro me custou uma fortuna.', '/ðæt kɑːr kɔːst miː ə ˈfɔːrtʃən/', 'Neutro. Igual ao português.', '[]'::jsonb, '[{"surface":"That","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"car","pos":"noun","ipa":"/kɑːr/","gloss":"carro"},{"surface":"cost","pos":"verb","ipa":"/kɔːst/","gloss":"custar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"fortune","pos":"noun","ipa":"/ˈfɔːrtʃən/","gloss":"fortuna"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-04', 'lesson-idioms-b2-03', 4, 'sentence', 'He is loaded.', 'Ele é cheio da grana.', '/hiː ɪz ˈloʊdɪd/', 'Gíria. Literal: "carregado". Real: muito rico.', '[]'::jsonb, '[{"surface":"He","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"loaded","pos":"adjective","ipa":"/ˈloʊdɪd/","gloss":"cheio da grana (gíria)"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-05', 'lesson-idioms-b2-03', 5, 'sentence', 'We''re running against the clock.', 'Estamos correndo contra o tempo.', '/wɪr ˈrʌnɪŋ əˈɡɛnst ðə klɑːk/', 'Neutro. Igual ao português.', '[]'::jsonb, '[{"surface":"We''re","pos":"pronoun","ipa":"/wɪr/","gloss":"nós estamos"},{"surface":"running","pos":"verb","ipa":"/ˈrʌnɪŋ/","gloss":"ficando (running late)"},{"surface":"against","pos":"preposition","ipa":"/əˈɡɛnst/","gloss":"contra"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"clock","pos":"noun","ipa":"/klɑːk/","gloss":"relógio (de parede)"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-06', 'lesson-idioms-b2-03', 6, 'sentence', 'Better late than never.', 'Antes tarde do que nunca.', '/ˈbɛtər leɪt ðæn ˈnɛvər/', 'Revisão: provérbio igual ao português.', '[]'::jsonb, '[{"surface":"Better","pos":"adjective","ipa":"/ˈbɛtər/","gloss":"melhor"},{"surface":"late","pos":"adjective","ipa":"/leɪt/","gloss":"atrasado"},{"surface":"than","pos":"conjunction","ipa":"/ðæn/","gloss":"do que"},{"surface":"never","pos":"adverb","ipa":"/ˈnɛvər/","gloss":"nunca"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-07', 'lesson-idioms-b2-03', 7, 'sentence', 'Time flies when you are having fun.', 'O tempo voa quando a gente se diverte.', '/taɪm flaɪz wɛn juː ɑːr ˈhævɪŋ fʌn/', 'Neutro. "Time flies" = o tempo voa.', '[]'::jsonb, '[{"surface":"Time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"},{"surface":"flies","pos":"verb","ipa":"/flaɪz/","gloss":"voa"},{"surface":"when","pos":"conjunction","ipa":"/wɛn/","gloss":"quando"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"are","pos":"auxiliary verb","ipa":"/ɑːr/","gloss":"são, estão"},{"surface":"having","pos":"verb","ipa":"/ˈhævɪŋ/","gloss":"receber, ter"},{"surface":"fun","pos":"noun","ipa":"/fʌn/","gloss":"diversão"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-08', 'lesson-idioms-b2-03', 8, 'sentence', 'I''ll do it in no time.', 'Faço isso rapidinho.', '/aɪl duː ɪt ɪn noʊ taɪm/', 'Informal. "In no time" = muito rápido.', '[]'::jsonb, '[{"surface":"I''ll","pos":"pronoun","ipa":"/aɪl/","gloss":"eu vou"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"no","pos":"determiner","ipa":"/noʊ/","gloss":"nenhum; não"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-09', 'lesson-idioms-b2-03', 9, 'sentence', 'We finished in the nick of time.', 'Terminamos em cima da hora.', '/wiː ˈfɪnɪʃt ɪn ðə nɪk ʌv taɪm/', 'Informal. "In the nick of time" = no último instante.', '[]'::jsonb, '[{"surface":"We","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"finished","pos":"verb","ipa":"/ˈfɪnɪʃt/","gloss":"terminou, terminado"},{"surface":"in","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"nick","pos":"noun","ipa":"/nɪk/","gloss":"momento exato (nick of time)"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-03-10', 'lesson-idioms-b2-03', 10, 'sentence', 'Let''s not waste time.', 'Vamos não perder tempo.', '/lɛts nɑːt weɪst taɪm/', '"Waste time" = perder tempo (desperdiçar). "Lose time" é outra coisa.', '[]'::jsonb, '[{"surface":"Let''s","pos":"verb","ipa":"/lɛts/","gloss":"vamos"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"waste","pos":"verb","ipa":"/weɪst/","gloss":"desperdiçar"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-04', 'course-idioms-b2', 4, 'Marcadores de conversa', 'As palavrinhas que deixam a fala natural.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-04-01', 'lesson-idioms-b2-04', 1, 'sentence', 'Well, it depends on the situation.', 'Bom, depende da situação.', '/wɛl ɪt dɪˈpɛndz ɑːn ðə ˌsɪtʃuˈeɪʃən/', '"Well" no começo ganha tempo para pensar.', '[]'::jsonb, '[{"surface":"Well","pos":"adverb","ipa":"/wɛl/","gloss":"bem"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"depends","pos":"verb","ipa":"/dɪˈpɛndz/","gloss":"depende"},{"surface":"on","pos":"preposition","ipa":"/ɑːn/","gloss":"em, sobre"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"situation","pos":"noun","ipa":"/ˌsɪtʃuˈeɪʃən/","gloss":"situação"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-02', 'lesson-idioms-b2-04', 2, 'sentence', 'Actually, I think you''re wrong.', 'Na verdade, acho que você está errado.', '/ˈæktʃuəli aɪ θɪŋk jʊr rɔːŋ/', 'Falso cognato: "actually" = na verdade, não "atualmente".', '[]'::jsonb, '[{"surface":"Actually","pos":"adverb","ipa":"/ˈæktʃuəli/","gloss":"na verdade"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"},{"surface":"you''re","pos":"pronoun","ipa":"/jʊr/","gloss":"você está, você é"},{"surface":"wrong","pos":"adjective","ipa":"/rɔːŋ/","gloss":"errado"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-03', 'lesson-idioms-b2-04', 3, 'sentence', 'I mean, it is not that bad.', 'Quer dizer, não é tão ruim.', '/aɪ miːn ɪt ɪz nɑːt ðæt bæd/', '"I mean" corrige ou explica o que você acabou de dizer.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"mean","pos":"verb","ipa":"/miːn/","gloss":"significar, querer dizer"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"is","pos":"auxiliary verb","ipa":"/ɪz/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"bad","pos":"adjective","ipa":"/bæd/","gloss":"ruim"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-04', 'lesson-idioms-b2-04', 4, 'sentence', 'You know, I have been thinking about it.', 'Sabe, eu tenho pensado nisso.', '/juː noʊ aɪ hæv bɪn ˈθɪŋkɪŋ əˈbaʊt ɪt/', '"You know" busca a atenção do outro. Não exagere.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"know","pos":"verb","ipa":"/noʊ/","gloss":"saber"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"have","pos":"verb","ipa":"/hæv/","gloss":"ter"},{"surface":"been","pos":"verb","ipa":"/bɪn/","gloss":"sido, estado"},{"surface":"thinking","pos":"verb","ipa":"/ˈθɪŋkɪŋ/","gloss":"pensando"},{"surface":"about","pos":"preposition","ipa":"/əˈbaʊt/","gloss":"sobre"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-05', 'lesson-idioms-b2-04', 5, 'sentence', 'Anyway, back to the point.', 'Enfim, voltando ao assunto.', '/ˈɛniweɪ bæk tuː ðə pɔɪnt/', '"Anyway" retoma o assunto principal.', '[]'::jsonb, '[{"surface":"Anyway","pos":"adverb","ipa":"/ˈɛniweɪ/","gloss":"enfim, de qualquer forma"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-06', 'lesson-idioms-b2-04', 6, 'sentence', 'By the way, did you call her?', 'Aliás, você ligou para ela?', '/baɪ ðə weɪ dɪd juː kɔːl hɜːr/', '"By the way" (BTW) = a propósito.', '[]'::jsonb, '[{"surface":"By","pos":"preposition","ipa":"/baɪ/","gloss":"até (prazo)"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"call","pos":"noun","ipa":"/kɔːl/","gloss":"chamada, call"},{"surface":"her","pos":"determiner","ipa":"/hɜːr/","gloss":"dela; a, lhe"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-07', 'lesson-idioms-b2-04', 7, 'sentence', 'Basically, we need more time.', 'Basicamente, precisamos de mais tempo.', '/ˈbeɪsɪkli wiː niːd mɔːr taɪm/', 'Resume a ideia principal.', '[]'::jsonb, '[{"surface":"Basically","pos":"adverb","ipa":"/ˈbeɪsɪkli/","gloss":"basicamente"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"need","pos":"verb","ipa":"/niːd/","gloss":"precisar"},{"surface":"more","pos":"determiner","ipa":"/mɔːr/","gloss":"mais"},{"surface":"time","pos":"noun","ipa":"/taɪm/","gloss":"vez; hora"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-08', 'lesson-idioms-b2-04', 8, 'sentence', 'To be fair, he did try.', 'Para ser justo, ele tentou.', '/tuː biː fɛr hiː dɪd traɪ/', '"To be fair" reconhece o outro lado.', '[]'::jsonb, '[{"surface":"To","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"fair","pos":"adjective","ipa":"/fɛr/","gloss":"justo"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"did","pos":"verb","ipa":"/dɪd/","gloss":"fez"},{"surface":"try","pos":"verb","ipa":"/traɪ/","gloss":"experimentar, tentar"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-09', 'lesson-idioms-b2-04', 9, 'sentence', 'So, what do you think?', 'Então, o que você acha?', '/soʊ wʌt duː juː θɪŋk/', '"So" no começo abre ou fecha um assunto.', '[]'::jsonb, '[{"surface":"So","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"do","pos":"auxiliary verb","ipa":"/duː/","gloss":"fazer; auxiliar de pergunta"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"think","pos":"verb","ipa":"/θɪŋk/","gloss":"achar, pensar"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-04-10', 'lesson-idioms-b2-04', 10, 'sentence', 'Let me put it this way.', 'Deixa eu explicar de outro jeito.', '/lɛt miː pʊt ɪt ðɪs weɪ/', 'Reformula quando o outro não entendeu.', '[]'::jsonb, '[{"surface":"Let","pos":"verb","ipa":"/lɛt/","gloss":"deixar, permitir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"put","pos":"verb","ipa":"/pʊt/","gloss":"colocar"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"this","pos":"determiner","ipa":"/ðɪs/","gloss":"este, esta, isso"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-05', 'course-idioms-b2', 5, 'Suavizando opiniões', 'Discordar e criticar sem soar rude.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-05-01', 'lesson-idioms-b2-05', 1, 'sentence', 'I''m not sure that''s the best idea.', 'Não sei se essa é a melhor ideia.', '/aɪm nɑːt ʃʊr ðæts ðə bɛst aɪˈdiːə/', 'Suaviza "that''s a bad idea".', '[]'::jsonb, '[{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"sure","pos":"adjective","ipa":"/ʃʊr/","gloss":"claro; certo"},{"surface":"that''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"best","pos":"adjective","ipa":"/bɛst/","gloss":"melhor"},{"surface":"idea","pos":"noun","ipa":"/aɪˈdiːə/","gloss":"ideia"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-02', 'lesson-idioms-b2-05', 2, 'sentence', 'It might be a good idea to wait.', 'Talvez seja uma boa ideia esperar.', '/ɪt maɪt biː ə ɡʊd aɪˈdiːə tuː weɪt/', '"Might" deixa a sugestão menos direta.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"might","pos":"modal verb","ipa":"/maɪt/","gloss":"talvez, poderia"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"good","pos":"adjective","ipa":"/ɡʊd/","gloss":"bom"},{"surface":"idea","pos":"noun","ipa":"/aɪˈdiːə/","gloss":"ideia"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"wait","pos":"noun","ipa":"/weɪt/","gloss":"espera; esperar"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-03', 'lesson-idioms-b2-05', 3, 'sentence', 'I see your point, but I''d suggest something else.', 'Entendo seu ponto, mas eu sugeriria outra coisa.', '/aɪ siː jʊr pɔɪnt bʌt aɪd səɡˈdʒɛst ˈsʌmθɪŋ ɛls/', 'Reconhece e depois propõe.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"see","pos":"verb","ipa":"/siː/","gloss":"ver, entender"},{"surface":"your","pos":"determiner","ipa":"/jʊr/","gloss":"seu, sua"},{"surface":"point","pos":"noun","ipa":"/pɔɪnt/","gloss":"ponto, argumento"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"},{"surface":"I''d","pos":"pronoun","ipa":"/aɪd/","gloss":"eu (gostaria)"},{"surface":"suggest","pos":"verb","ipa":"/səɡˈdʒɛst/","gloss":"sugerir"},{"surface":"something","pos":"pronoun","ipa":"/ˈsʌmθɪŋ/","gloss":"alguma coisa"},{"surface":"else","pos":"adverb","ipa":"/ɛls/","gloss":"mais, outro"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-04', 'lesson-idioms-b2-05', 4, 'sentence', 'It''s not exactly what we expected.', 'Não é bem o que esperávamos.', '/ɪts nɑːt ɪɡˈzæktli wʌt wiː ɪkˈspɛktɪd/', '"Not exactly" suaviza uma crítica.', '[]'::jsonb, '[{"surface":"It''s","pos":"pronoun","ipa":"/ɪts/","gloss":"é, está"},{"surface":"not","pos":"particle","ipa":"/nɑːt/","gloss":"não"},{"surface":"exactly","pos":"adverb","ipa":"/ɪɡˈzæktli/","gloss":"exatamente"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"expected","pos":"verb","ipa":"/ɪkˈspɛktɪd/","gloss":"esperado"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-05', 'lesson-idioms-b2-05', 5, 'sentence', 'Would it be possible to change the date?', 'Seria possível mudar a data?', '/wʊd ɪt biː ˈpɑːsəbəl tuː tʃeɪndʒ ðə deɪt/', 'Pedido indireto, mais educado que "Can you change…?".', '[]'::jsonb, '[{"surface":"Would","pos":"modal verb","ipa":"/wʊd/","gloss":"gostaria; condicional"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"be","pos":"verb","ipa":"/biː/","gloss":"ser, estar"},{"surface":"possible","pos":"adjective","ipa":"/ˈpɑːsəbəl/","gloss":"possível"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"change","pos":"verb","ipa":"/tʃeɪndʒ/","gloss":"trocar"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"date","pos":"noun","ipa":"/deɪt/","gloss":"data"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-06', 'lesson-idioms-b2-05', 6, 'sentence', 'I was wondering if you could help me.', 'Eu queria saber se você poderia me ajudar.', '/aɪ wɑːz ˈwʌndərɪŋ ɪf juː kʊd hɛlp miː/', 'Passado contínuo deixa o pedido bem educado.', '[]'::jsonb, '[{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"wondering","pos":"verb","ipa":"/ˈwʌndərɪŋ/","gloss":"me perguntando"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"you","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"could","pos":"auxiliary verb","ipa":"/kʊd/","gloss":"poderia"},{"surface":"help","pos":"interjection","ipa":"/hɛlp/","gloss":"socorro; ajudar"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-07', 'lesson-idioms-b2-05', 7, 'sentence', 'It seems a bit expensive to me.', 'Me parece um pouco caro.', '/ɪt siːmz ə bɪt ɪkˈspɛnsɪv tuː miː/', '"A bit" e "seems" suavizam.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"seems","pos":"verb","ipa":"/siːmz/","gloss":"parece"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"bit","pos":"noun","ipa":"/bɪt/","gloss":"pouco (a bit = um pouco)"},{"surface":"expensive","pos":"adjective","ipa":"/ɪkˈspɛnsɪv/","gloss":"caro"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-08', 'lesson-idioms-b2-05', 8, 'sentence', 'Correct me if I''m wrong, but…', 'Me corrija se eu estiver errado, mas…', '/kəˈrɛkt miː ɪf aɪm rɔːŋ bʌt/', 'Abre uma discordância com humildade.', '[]'::jsonb, '[{"surface":"Correct","pos":"verb","ipa":"/kəˈrɛkt/","gloss":"corrigir"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"},{"surface":"if","pos":"conjunction","ipa":"/ɪf/","gloss":"se"},{"surface":"I''m","pos":"pronoun","ipa":"/aɪm/","gloss":"eu estou, eu sou"},{"surface":"wrong","pos":"adjective","ipa":"/rɔːŋ/","gloss":"errado"},{"surface":"but","pos":"conjunction","ipa":"/bʌt/","gloss":"mas"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-09', 'lesson-idioms-b2-05', 9, 'sentence', 'With all due respect, I disagree.', 'Com todo o respeito, discordo.', '/wɪð ɔːl duː rɪˈspɛkt aɪ ˌdɪsəˈɡriː/', 'Formal. Use com cuidado: pode soar tenso.', '[]'::jsonb, '[{"surface":"With","pos":"preposition","ipa":"/wɪð/","gloss":"com"},{"surface":"all","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"due","pos":"adjective","ipa":"/duː/","gloss":"devido (due to)"},{"surface":"respect","pos":"noun","ipa":"/rɪˈspɛkt/","gloss":"respeito"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"disagree","pos":"verb","ipa":"/ˌdɪsəˈɡriː/","gloss":"discordar"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-05-10', 'lesson-idioms-b2-05', 10, 'sentence', 'That''s one way to look at it.', 'Essa é uma forma de ver.', '/ðæts wʌn weɪ tuː lʊk æt ɪt/', 'Discorda sem invalidar a pessoa.', '[]'::jsonb, '[{"surface":"That''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"one","pos":"pronoun","ipa":"/wʌn/","gloss":"uma (I owe you one)"},{"surface":"way","pos":"noun","ipa":"/weɪ/","gloss":"caminho; jeito"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"look","pos":"noun","ipa":"/lʊk/","gloss":"olhada"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;

INSERT INTO public.course_lessons (id, course_id, chapter_number, title, description)
VALUES ('lesson-idioms-b2-06', 'course-idioms-b2', 6, 'Contando uma história', 'Começar, criar suspense e terminar uma história.')
ON CONFLICT (id) DO UPDATE SET chapter_number = EXCLUDED.chapter_number, title = EXCLUDED.title, description = EXCLUDED.description;

INSERT INTO public.course_units (id, lesson_id, order_index, kind, text, translation_pt, ipa, explanation_note, syntax_groups, annotations, example_en, example_pt)
VALUES
  ('unit-idioms-b2-06-01', 'lesson-idioms-b2-06', 1, 'sentence', 'You won''t believe what happened to me.', 'Você não vai acreditar no que aconteceu comigo.', '/juː woʊnt bɪˈliːv wʌt ˈhæpənd tuː miː/', 'Abertura clássica que prende a atenção.', '[]'::jsonb, '[{"surface":"You","pos":"pronoun","ipa":"/juː/","gloss":"você"},{"surface":"won''t","pos":"modal verb","ipa":"/woʊnt/","gloss":"não vai (will not)"},{"surface":"believe","pos":"verb","ipa":"/bɪˈliːv/","gloss":"acreditar"},{"surface":"what","pos":"pronoun","ipa":"/wʌt/","gloss":"o que, qual"},{"surface":"happened","pos":"verb","ipa":"/ˈhæpənd/","gloss":"aconteceu"},{"surface":"to","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"me","pos":"pronoun","ipa":"/miː/","gloss":"me, mim"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-02', 'lesson-idioms-b2-06', 2, 'sentence', 'So there I was, waiting at the station.', 'Então lá estava eu, esperando na estação.', '/soʊ ðɛr aɪ wɑːz ˈweɪtɪŋ æt ðə ˈsteɪʃən/', '"So there I was" coloca o ouvinte na cena.', '[]'::jsonb, '[{"surface":"So","pos":"adverb","ipa":"/soʊ/","gloss":"tão"},{"surface":"there","pos":"adverb","ipa":"/ðɛr/","gloss":"lá"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"waiting","pos":"verb","ipa":"/ˈweɪtɪŋ/","gloss":"esperando"},{"surface":"at","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"station","pos":"noun","ipa":"/ˈsteɪʃən/","gloss":"estação"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-03', 'lesson-idioms-b2-06', 3, 'sentence', 'All of a sudden, the lights went out.', 'De repente, as luzes se apagaram.', '/ɔːl ʌv ə ˈsʌdən ðə laɪts wɛnt aʊt/', '"All of a sudden" = de repente. "Go out" = apagar.', '[]'::jsonb, '[{"surface":"All","pos":"determiner","ipa":"/ɔːl/","gloss":"tudo, todos"},{"surface":"of","pos":"preposition","ipa":"/ʌv/","gloss":"de"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"sudden","pos":"adjective","ipa":"/ˈsʌdən/","gloss":"repentino"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"lights","pos":"noun","ipa":"/laɪts/","gloss":"luzes"},{"surface":"went","pos":"verb","ipa":"/wɛnt/","gloss":"foi (passado de go)"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-04', 'lesson-idioms-b2-06', 4, 'sentence', 'At first, I thought it was a joke.', 'No começo, achei que era piada.', '/æt fɜːrst aɪ θɔːt ɪt wɑːz ə dʒoʊk/', '"At first" = no começo (ideia que depois muda).', '[]'::jsonb, '[{"surface":"At","pos":"preposition","ipa":"/æt/","gloss":"em, às"},{"surface":"first","pos":"adjective","ipa":"/fɜːrst/","gloss":"primeiro"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"thought","pos":"verb","ipa":"/θɔːt/","gloss":"pensou, pensado"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"joke","pos":"noun","ipa":"/dʒoʊk/","gloss":"piada"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-05', 'lesson-idioms-b2-06', 5, 'sentence', 'It turned out that he was the new boss.', 'No fim, ele era o chefe novo.', '/ɪt tɜːrnd aʊt ðæt hiː wɑːz ðə nuː bɔːs/', '"It turned out that" = acabou que.', '[]'::jsonb, '[{"surface":"It","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"turned","pos":"verb","ipa":"/tɜːrnd/","gloss":"virou, ficou"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"},{"surface":"that","pos":"pronoun","ipa":"/ðæt/","gloss":"isso, aquilo"},{"surface":"he","pos":"pronoun","ipa":"/hiː/","gloss":"ele"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"new","pos":"adjective","ipa":"/nuː/","gloss":"novo"},{"surface":"boss","pos":"noun","ipa":"/bɔːs/","gloss":"chefe"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-06', 'lesson-idioms-b2-06', 6, 'sentence', 'To make a long story short, we missed the flight.', 'Resumindo, perdemos o voo.', '/tuː meɪk ə lɔːŋ ˈstɔːri ʃɔːrt wiː mɪst ðə flaɪt/', '"To make a long story short" = resumindo.', '[]'::jsonb, '[{"surface":"To","pos":"preposition","ipa":"/tuː/","gloss":"para, a"},{"surface":"make","pos":"verb","ipa":"/meɪk/","gloss":"fazer; conseguir ir (make it)"},{"surface":"a","pos":"determiner","ipa":"/ə/","gloss":"um, uma"},{"surface":"long","pos":"adjective","ipa":"/lɔːŋ/","gloss":"longo, muito (tempo)"},{"surface":"story","pos":"noun","ipa":"/ˈstɔːri/","gloss":"história"},{"surface":"short","pos":"adjective","ipa":"/ʃɔːrt/","gloss":"curto"},{"surface":"we","pos":"pronoun","ipa":"/wiː/","gloss":"nós, a gente"},{"surface":"missed","pos":"verb","ipa":"/mɪst/","gloss":"perdi"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"flight","pos":"noun","ipa":"/flaɪt/","gloss":"voo"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-07', 'lesson-idioms-b2-06', 7, 'sentence', 'Luckily, nobody got hurt.', 'Por sorte, ninguém se machucou.', '/ˈlʌkɪli ˈnoʊbɑːdi ɡɑːt hɜːrt/', '"Luckily" = por sorte. "Get hurt" = machucar-se.', '[]'::jsonb, '[{"surface":"Luckily","pos":"adverb","ipa":"/ˈlʌkɪli/","gloss":"por sorte"},{"surface":"nobody","pos":"pronoun","ipa":"/ˈnoʊbɑːdi/","gloss":"ninguém"},{"surface":"got","pos":"verb","ipa":"/ɡɑːt/","gloss":"conseguiu, pegou"},{"surface":"hurt","pos":"verb","ipa":"/hɜːrt/","gloss":"doer, machucar"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-08', 'lesson-idioms-b2-06', 8, 'sentence', 'In the end, everything worked out.', 'No fim, deu tudo certo.', '/ɪn ðə ɛnd ˈɛvriθɪŋ wɜːrkt aʊt/', '"Work out" = dar certo. "In the end" = no fim.', '[]'::jsonb, '[{"surface":"In","pos":"preposition","ipa":"/ɪn/","gloss":"em, dentro de"},{"surface":"the","pos":"determiner","ipa":"/ðə/","gloss":"o, a"},{"surface":"end","pos":"noun","ipa":"/ɛnd/","gloss":"fim, final"},{"surface":"everything","pos":"pronoun","ipa":"/ˈɛvriθɪŋ/","gloss":"tudo"},{"surface":"worked","pos":"verb","ipa":"/wɜːrkt/","gloss":"trabalhou"},{"surface":"out","pos":"adverb","ipa":"/aʊt/","gloss":"para fora"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-09', 'lesson-idioms-b2-06', 9, 'sentence', 'Looking back, it was pretty funny.', 'Olhando para trás, foi bem engraçado.', '/ˈlʊkɪŋ bæk ɪt wɑːz ˈprɪti ˈfʌni/', '"Looking back" = em retrospecto.', '[]'::jsonb, '[{"surface":"Looking","pos":"verb","ipa":"/ˈlʊkɪŋ/","gloss":"aguardando (look forward)"},{"surface":"back","pos":"adverb","ipa":"/bæk/","gloss":"de volta"},{"surface":"it","pos":"pronoun","ipa":"/ɪt/","gloss":"isso, ele, ela"},{"surface":"was","pos":"verb","ipa":"/wɑːz/","gloss":"foi, estava"},{"surface":"pretty","pos":"adverb","ipa":"/ˈprɪti/","gloss":"bem, bastante"},{"surface":"funny","pos":"adjective","ipa":"/ˈfʌni/","gloss":"engraçado"}]'::jsonb, NULL, NULL),
  ('unit-idioms-b2-06-10', 'lesson-idioms-b2-06', 10, 'sentence', 'And that''s how I met my wife.', 'E foi assim que conheci minha esposa.', '/ænd ðæts haʊ aɪ mɛt maɪ waɪf/', 'Fecho natural de uma história.', '[]'::jsonb, '[{"surface":"And","pos":"conjunction","ipa":"/ænd/","gloss":"e"},{"surface":"that''s","pos":"pronoun","ipa":"/ðæts/","gloss":"isso é"},{"surface":"how","pos":"adverb","ipa":"/haʊ/","gloss":"como"},{"surface":"I","pos":"pronoun","ipa":"/aɪ/","gloss":"eu"},{"surface":"met","pos":"verb","ipa":"/mɛt/","gloss":"conheceu, encontrou"},{"surface":"my","pos":"determiner","ipa":"/maɪ/","gloss":"meu, minha"},{"surface":"wife","pos":"noun","ipa":"/waɪf/","gloss":"esposa"}]'::jsonb, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET order_index = EXCLUDED.order_index, text = EXCLUDED.text, translation_pt = EXCLUDED.translation_pt,
  ipa = EXCLUDED.ipa, explanation_note = EXCLUDED.explanation_note, syntax_groups = EXCLUDED.syntax_groups,
  annotations = EXCLUDED.annotations,
  kind = EXCLUDED.kind, example_en = EXCLUDED.example_en, example_pt = EXCLUDED.example_pt;
